### ISSUE TITLE
Table pagination and infinite scroll Guidance

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1018]
- research user scenarios driving the need for them
- publish guidance on when to use each
- update Figma design resources as needed

**Comment by MikeWalrath** [comment]
Thanks for creating this Vicky, 

Initially we will create variants for both pagination and infinite scroll. I believe the research will still be valuable from a guidance perspective. This is also something that we will look to test in the future to hopefully verify an approach and share with our stakeholders.

**Comment by vavalos5** [comment]
Created on some questions:

https://hpe-my.sharepoint.com/:w:/p/vicky_avalos/EVWZwdFBA4tEm-GdzAAS3cYBjK_Zs_ZvsqmDzill2c9nIA?e=tLhHXg

**Comment by ericsoderberghp** [comment]
Covered via https://design-system.hpe.design/components/table#use-pagination-or-infinite-scroll-with-tables
