### ISSUE TITLE
Look at Design System process through a Design Thinking "lens"

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1065]
Build upon prior discussion of this topic.

Propose another meeting where we spend a few minutes reviewing the notes from the last meeting and then discuss carrying it forward.

### Deliverables
- notes in this issue
- additional issues created for further work, potentially including a draft of proposed process changes

**Comment by gregfuruiye** [comment]
We have a Figma File going now to visualize and document an outline for the process:
https://www.figma.com/file/goujWKmRJ0LmvaOWO5NVDZ/Design-Thinking-Outline?node-id=1%3A2
