### ISSUE TITLE
Create more rich, enticing dashboard example to support cross-linkage

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1066]
On the Card page, there is a call to action to "See Cards in a Dashboard". There exist some enticing visuals of a dashboard, such as:
![Screen Shot 2020-08-21 at 2 54 14 PM](https://user-images.githubusercontent.com/1756948/90934244-332b7980-e3be-11ea-9824-cc9b86d611f7.png)

It would be nice to be able to use an example such as this to showcase cards in a dashboard context. We would need to be able to deliver on the promise, taking a user to a view which is represented by this preview image.

Similar need for "See Cards as Navigation":
![Screen Shot 2020-08-21 at 2 57 35 PM](https://user-images.githubusercontent.com/1756948/90934521-ad5bfe00-e3be-11ea-9df8-0ea9352d14c9.png)

**Comment by ericsoderberghp** [comment]
Closed in favor of new page layouts dashboard examples
