### ISSUE TITLE
Show selection summary in Figma designs

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1086]
Ensure we have any selection summary text shown across the Table designs related to selection.

**Comment by gregfuruiye** [comment]
the current design for selection, search, filter ... is here:

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=920%3A142510

**Comment by halocline** [comment]
Related: https://github.com/hpe-design/design-system/issues/1111

I have incorporated a selection summary in the "Manage Orders" example. Implemented the following:
- If nothing selected, do not display summary
- If selected items, display summary
- Adjusted summary text to read "X of Y items selected"

Please take a look and see if there are adjustments we want to make.

[Preview](https://deploy-preview-1089--keen-mayer-a86c8b.netlify.app/components/table#selecting-multiple-records-and-batch-actions)

**Comment by ericsoderberghp** [comment]
I'm not seeing the item count and selection summary labels in https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=816%3A139401
