### ISSUE TITLE
Data Visualization - Donut

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1090]

**Comment by vavalos5** [comment]
- [ ] Research best practices
- [ ] Provide guidance on how to use a donut chart and when to use it
- [ ] Accessibility +  references
- [ ] WCAG Standards  (references)
- [ ] NNG (references)
- [ ] Use Cases- How are other teams using donuts in their designs. Figuring out why are they using a donut. What are they trying to represent. Speak w/ a few people outside of the team
- [ ] Does Grommet currently use/have a donut chart? If so, how is it implemented. Discovering what pieces we can bring in from Grommet
- [ ] Speak w/ devs on how a donut is being structured
- [ ] Explore the look and feel of the donut chart

**Comment by MikeWalrath** [comment]
Combining issue with Meter #1092
