### ISSUE TITLE
Data Visualization - Big Number

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1091]

**Comment by vavalos5** [comment]
- [ ] Research best practices
- [ ] Provide guidance on how to use a donut chart and when to use it
- [ ] Accessibility +  references
- [ ] WCAG Standards  (references)
- [ ] NNG (references)
- [ ] Use Cases- How are other teams using big numbers in their designs. Figuring out why are they using a big numbers. What are they trying to represent. Speak w/ a few people outside of the team
- [ ] Does Grommet currently use/have a big number chart? If so, how is it implemented. Discovering what pieces we can bring in from Grommet
- [ ] Speak w/ devs on how big numbers chart is being structured
- [ ] Explore the look and feel of a big numbers chart

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/hpe-design-system/issues/1291

**Comment by ericsoderberghp** [comment]
Waiting for #846 to create issues later as needed instead
