### ISSUE TITLE
Align Layer corner radius 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1096]
Alignment between Figma and site have inconsistent corner radius. 
Site example:
![image](https://user-images.githubusercontent.com/17712467/91995348-f08a6b00-ecf4-11ea-9eb8-4f9a163130cc.png)

Figma: 
![image](https://user-images.githubusercontent.com/17712467/91995614-43fcb900-ecf5-11ea-8557-bb57f5179f5e.png)

**Comment by vavalos5** [comment]
Are we aligning this corner radius to what we have on the site (4px corner radius)?

**Comment by ericsoderberghp** [comment]
> Are we aligning this corner radius to what we have on the site (4px corner radius)?

What's your inclination, given the overall visual design?

**Comment by vavalos5** [comment]
Let me go back and try to remember what we have on other designs, but i want to say yes hehe😆

**Comment by vavalos5** [comment]
After discussing with the team, the designs on Figma are correct. We just need to align on the DS site.

**Comment by halocline** [comment]
Added https://github.com/grommet/hpe-design-system/issues/1341 to complete this work.
