### ISSUE TITLE
Is there an easy way to map grommet-icons to Figma? 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1098]
related to #1097 

![image](https://user-images.githubusercontent.com/17712467/91997799-b40c3e80-ecf7-11ea-8bb1-7ee8818a81d8.png)

We would like to make its as simple as possible to translate icons between our devs and designers.

**Comment by MikeWalrath** [comment]
Additional resource https://www.quora.com/How-do-I-get-icons-in-Figma

**Comment by ericsoderberghp** [comment]
Replaced by https://github.com/grommet/hpe-design-system/issues/1957
