### ISSUE TITLE
'disabled-text': 'text-weak'

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1102]
Designers are given guidance to use 'text-weak' for disabled text visualizations. To be consistent, proposing to update 'disabled-text' to 'text-weak'

Figma Color Comparison Analysis is here:
https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=277%3A2

**Comment by taysea** [comment]
@gregfuruiye I'm looking at the Figma file you've linked and it appears that `disabled-text` has a different HEX value than `text-weak`. Is the intent that they should be the same?

**Comment by taysea** [comment]
Per discussion with Greg, the value should be called `text-disabled` to align with our naming convention of `[name]+[descriptor]` and the value should be assigned that of `text-weak`.
