### ISSUE TITLE
Investigate 'status-disabled'

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1103]
We have a color style in Figma for 'validation-disabled' that does not match what is in the theme 'status-disabled' I'm wondering where this is currently being used in the theme (i.e. TextInput, buttons, ...?).

Figma color analysis:
[https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=1680%3A418](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=1680%3A418)

In the theme:
'status-disabled': '#CCCCCC',

In Figma:
'Validation, Disabled'
light: #0000000f (6%)
dark: #ffffff0d (5%)

**Comment by ShimiSun** [comment]
Linking to https://github.com/grommet/grommet-theme-hpe/pull/112 (last comment)

**Comment by taysea** [comment]
@gregfuruiye  `status-disabled` is not being used anywhere in the theme (aside from its definition). In all instances of disabled state, we have been using `text-weak` (in process of updating to `text-disabled`: https://github.com/grommet/grommet-theme-hpe/pull/133) and `border-weak`. We have not used any instances of this color in the DS examples. I am wondering if we should remove this color all together?

Additionally, I'm not sure I'm understanding the use case of a validation disabled. When would a disabled field be getting actively validated? I haven't seen us use it in site example, so is the color needed at all? Would love to see use cases

**Comment by gregfuruiye** [comment]
@taysea , totally agree with you and that was why this issue was created. I believe we had an iteration of disabled button and text input using a fill that we called 'validation-disabled' and then maybe got swapped with another iteration called 'status-disabled'. I'm also not aware of a current use case either.

The only use case for 'validation-disabled' that I could think of might be when you click on a button and during validation of the content of a form or something, you disable the content during the validation. But that still seems a bit odd. Let's simplify and propose removing both 'status-disabled' and 'validation-disabled'. The terms and uses themselves lead to confusion.

**Comment by taysea** [comment]
Great, I would agree with the notion of removing both colors. We will just need to keep in mind how to account for any backwards compatibility issues (in the case that any team has used it).
