### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1104]
Exploration of how to provide help to users. Some aspects that could be covered:

- [ ] short inline messages
- [ ] tooltips
- [ ] visible aside/section/column/panel
- [ ] modal Layer
- [ ] separate site

For all types explored, when to use which.

Deliverable: problem statements

This is a template the GLC has already implemented. The goal of this issue is to identify areas where the Design System can adopt, identify gaps, and apply to a general template for other teams to consume. 

Meeting Recording:  
https://web.microsoftstream.com/video/03e24db0-9042-4902-a633-58d0c60e88c1
Slides: 
https://hpe.sharepoint.com/:p:/s/msteams_532f51/Ecjho5kUzJFOvsv4EUNayN0BdVVGgLIPYybPICOqcMWycA?e=Xyrsbj
Figma file: 
https://www.figma.com/file/bbBDaRPdHJvLP1bKzl4UWI/F1992_Help_documentation?node-id=1%3A7
Jens also did an early designer prototype: 
https://designer.grommet.io/revision-1?id=US9760-inline-help-pentenrieder-hpe-com

**Comment by ericsoderberghp** [comment]
Related: https://github.com/grommet/hpe-design-system/issues/1324

**Comment by taysea** [comment]
Closing in favor of Gina's contextual help work.
