### ISSUE TITLE
Apply SEO meta tags to each page

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#111]
- [ ] Apply SEO meta tags to each page
  - [x] Home
  - [x] Guidelines
    - [x] Philosophy
    - [x] Human Centered
    - [x] Principles
    - [ ] Others????
  - [x] Foundation
    - [x] Branding
    - [x] Color
    - [x] Typography
    - [ ] Layout
    - [ ] Iconography
    - [ ] Tokens
  - [x] Components
    - [x] Controls
    - [ ] Inputs
    - [x] Layouts
  - [x] Develop
  - [x] Design
  - [x] Resources

**Comment by ericsoderberghp** [comment]
It's been over a year with no attention. Closing for now.
