### ISSUE TITLE
Change examples to open Layers within the Examples

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1115]
Currently, when opening Layers in the Examples, the Layer is positioned relative to the design system site. Instead, it would be better if it could be positioned within the Example. This would be especially helpful for the mobile example view.

A suggestion for how to do this would be to use https://v2.grommet.io/layer#target and set it to the appropriate Example viewport. The trick will be to not include this in the Example code. Or, perhaps we can include a helpful comment explaining what's going on. Perhaps something like `const { layerTarget } = useContext(ExampleContext);`?

**Comment by taysea** [comment]
Placing this on hold until Layer scroll behavior is improved. Right now, it makes the layer a bit jumpy as the page scrolls. I will be looking at this behavior in Grommet.
