### ISSUE TITLE
Design System cost/time value add 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1123]
How can we quantify and visually communicate the time and cost value savings of using the Design System?

**Comment by MikeWalrath** [comment]
Thoughts on measurable. 
- How satisfied are internal and external users (Grommet) 
- What is the health of the repo. How many issues are filed vs how many are closed. 
- How do we execute against milestones and timelines

**Comment by taysea** [comment]
Closing, this work will be addressed separately.
