### ISSUE TITLE
Documentation/Organization in Figma

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1127]
Explore how to organize and provide documentation within the Figma Files.

The exploration and possible recommendations are here:
https://www.figma.com/file/5nHER4TVcxgkHSCCp5kUJo/Organization-and-Documentation?node-id=0%3A1

There is a set of Figma Best Practice Guides from Figma as well:
https://www.figma.com/best-practices/

**Comment by gregfuruiye** [comment]
Here's a good place to start:

https://spotify.design/article/how-spotify-organises-work-in-figma-to-improve-collaboration

**Comment by vavalos5** [comment]
Wondering if we should create a Word doc or Figma file to implement screenshots and info of things we liked/don't like

**Comment by gregfuruiye** [comment]
A Figma File is great. Let's do two things:
1 - Explore and review how other teams are doing things (spotify, Figma community, Figma best practices...)
2 - Get some feedback from a few designers within HPE (Lauren, Jonathan, Raja's team, Scott Oja, Ray Mecari...)

1 is easy enough for us to dig in and collect some info
2 is something where we can set up some 30 min meetings with folks and get some 'rough' feedback

**Comment by vavalos5** [comment]
Figma file: https://www.figma.com/file/5nHER4TVcxgkHSCCp5kUJo/Organization-and-Documentation?node-id=0%3A1

**Comment by gregfuruiye** [comment]
Another reference to help guide us and consider:
https://www.figma.com/best-practices/

**Comment by ericsoderberghp** [comment]
I'm assuming this is "in review" to indicate that we'd like to review it with our partner teams who are using Figma.

**Comment by gregfuruiye** [comment]
I think it is in review in that we can take the exploration part and begin to break it out into smaller issues. In my mind, review for an exploration is more about reviewing what we've learned and that we've been able to clearly provide a problem statement. Trying to follow some design thinking process path a bit:
https://www.figma.com/file/goujWKmRJ0LmvaOWO5NVDZ/Design-Thinking-Outline?node-id=4%3A2

**Comment by ericsoderberghp** [comment]
Superceded by #2235
