### ISSUE TITLE
Table - Body 'leaks' above header when header is pinned + table parent has padding

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1128]

**Comment by taysea** [comment]
From initial exploration, I am only able to replicate this on Safari (Chrome and FF do not have this issue). Here is what the issue looks like:
<img width="1285" alt="Screen Shot 2020-09-15 at 3 53 27 PM" src="https://user-images.githubusercontent.com/12522275/93273015-aa5cef00-f76b-11ea-8911-88e6cb6155b3.png">
<img width="887" alt="Screen Shot 2020-09-15 at 3 53 18 PM" src="https://user-images.githubusercontent.com/12522275/93273018-acbf4900-f76b-11ea-9811-77a3557ecb62.png">

I had separately noted that `pin` on Safari doesn't properly fix the footer of the DataTable, so I wonder if Safari's handling of DataTable is just different than other browsers. Will look more into a fix now.

**Comment by halocline** [comment]
> From initial exploration, I am only able to replicate this on Safari (Chrome and FF do not have this issue). Here is what the issue looks like:

Let me provide prescriptive steps to reproduce on Chrome and FF. I did notice it there. I will follow up.
