### ISSUE TITLE
Table - Complete design, guidance, and examples for Table pagination vs. infiniteScroll

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1130]
Some guidance content has been written.

Need to flesh out:
- [x] Pagination designs https://github.com/hpe-design/design-system/issues/1018
- [x] Validate / modify guidance copy https://github.com/hpe-design/design-system/issues/1018
- [ ] Implement examples demonstrating pagination and infiniteScroll for tables

**Comment by MikeWalrath** [comment]
Adding additional feedback to consider. 
![image](https://user-images.githubusercontent.com/17712467/114626540-1acfde00-9c71-11eb-9142-542ccd25a281.png)

**Comment by taysea** [comment]
Closing due to staleness.
