### ISSUE TITLE
Resizable header columns on a Table

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1138]
- What does the separator look like?
-Guidance on what it does and when it should be used
- Is it adjustable on the left or right?

**Comment by vavalos5** [comment]
1. Would we use the browsers HTML standard cursor? Or would we use a range input inside of a cell header that is hidden using an assertive text class so users can tab to the input and interact with it as they would with any range slider.

2. Would we want to consider Auto-Size Columns? Each column can be 'auto resized' by double clicking the right side of the header rather than dragging it. I feel as though we probably do not. 

3. Would each column have a min and max width set? Or would we allow users to adjust the width accordingly to their liking? resulting in creating a horizontal scroll table.

4. If a column is expanded in size, would the columns to the right of it be pushed off without affecting their size (like in Grommet) or would the column next to it truncate in text? I tend to like what we're doing in Grommet, but just a thought/consideration. See Ex. below

<img width="831" alt="Screen Shot 2020-09-25 at 8 25 00 AM" src="https://user-images.githubusercontent.com/62117454/94285673-d6fdcd00-ff08-11ea-96f4-b5eea58bc5e6.png">
Reference Live Demo: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ColumnResizing/jQuery/Light/

5. I'm wondering if we want to have guidance/example on resizable grouped headers since in our Figma file we talk about flattening the table and avoiding. However, there may still be some use cases where service teams will continue to use grouped column headers. I think I answered my question? lol

**Comment by taysea** [comment]
> 1. Would we use the browsers HTML standard cursor? Or would we use a range input inside of a cell header that is hidden using an assertive text class so users can tab to the input and interact with it as they would with any range slider.

I would imagine we use the arrow cursor that shows up in this grommet example: https://storybook.grommet.io/?path=/story/datatable--sort

> 2. Would we want to consider Auto-Size Columns? Each column can be 'auto resized' by double clicking the right side of the header rather than dragging it. I feel as though we probably do not.

My first thought is that this may conflict with the button behavior of a sortable column, but I would be interested to see implementations where both sort + auto size play nicely.

> 3. Would each column have a min and max width set? Or would we allow users to adjust the width accordingly to their liking? resulting in creating a horizontal scroll table.

I think if a user is adjusting the width manually, they should be able to expand as wide as they'd like (knowing that it could result in horizontal scrolling), but would need to explore how the surrounding columns would know they are allowed to overflow as opposed to continuing to collapse to make space. This might be simple but I just haven't looked into it.

> 4. If a column is expanded in size, would the columns to the right of it be pushed off without affecting their size (like in Grommet) or would the column next to it truncate in text? I tend to like what we're doing in Grommet, but just a thought/consideration. See Ex. below
> 
> <img alt="Screen Shot 2020-09-25 at 8 25 00 AM" width="831" src="https://user-images.githubusercontent.com/62117454/94285673-d6fdcd00-ff08-11ea-96f4-b5eea58bc5e6.png">
> 
This seems like it plays into the above question about horizontal scrolling vs not. I think if I'm allowing my table to have horizontal scroll, then I might set some min-width for a column to shrink to after which its size is unaffected and it gets pushed off to the right. If I don't want to have horizontal scroll, then I think the column would continue to shrink and text would truncate.

This notion of when to allow horizontal scroll vs not seems like a discussion.

> Reference: [Live Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ColumnResizing/jQuery/Light/)
> 1. I'm wondering if we want to have guidance/example on resizable grouped headers since in our Figma file we talk about flattening the table and avoiding. However, there may still be some use cases where service teams will continue to use grouped column headers. I think I answered my question? lol

Those are all just my initial thoughts/first reactions, but would be interested to hear the same from others/talk more about any of the above points.

**Comment by ericsoderberghp** [comment]
Good thoughts. A few additional comments:
- I don't think we need to make resizing keyboard accessible, unless WCAG has some good guidance on doing it
- I think column resizing should work separately from horizontal scrolling. A table could have horizontal scrolling enabled or not and column resizing works within that context.
- I think columns should have a minimum size to at least be able to see whether they have content or not and to provide a means of triggering any tooltip to reveal that content.

**Comment by vavalos5** [comment]
First pass can be found here: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=1965%3A129592

**Question:** Do we want to provide a visual indication of when the user is resizing a column? According to NNG there should be feedback that an item has been dragged-and-dropped such as an outline or contrasting color 

I created a few explorations in the Figma file in case we do want to include a visual indication of when a user clicks and drags the end of the column.

**Comment by vavalos5** [comment]
1. Do we want to provide a visual indication of when the user is clicking and dragging a column? (see resizing explorations)
2. If we're hovering at the end of a column, should that header column have a hover state too?

**Comment by taysea** [comment]
> 1. Do we want to provide a visual indication of when the user is clicking and dragging a column? (see resizing explorations)
> 2. If we're hovering at the end of a column, should that header column have a hover state too?

When you say "hovering at the end", does that mean hovering over the resizer? and then with regards to "header column hover state" does that mean that the whole header cell receives a hover treatment, or something specific to the resizer?

**Comment by vavalos5** [comment]
Right, when hovering over the resizer, does that column header receive a hover since technically you are hovering over the cell. Let me know if that makes sense 🤔

**Comment by taysea** [comment]
> Right, when hovering over the resizer, does that column header receive a hover since technically you are hovering over the cell. Let me know if that makes sense 🤔

Gotcha, it does make sense. I am not sure I have an immediate response. Was one behavior happening more in the examples you researched?
