### ISSUE TITLE
Pagination + Infinite Scroll for cards and lists

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1140]
Guidance and examples of how to implement/use pagination for cards, lists and incorporating table.

Including infinite scroll here as it could also be applied

**Comment by taysea** [comment]
Some initial exploration on pagination component from a dev side that might be informative to some design options: https://github.com/grommet/hpe-design-system/issues/1142#issuecomment-707244843

**Comment by taysea** [comment]
Closing this since Pagination examples have already been added.
