### ISSUE TITLE
Research font weight question from Robert Gary

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1157]
Slack thread: https://hpe.slack.com/archives/C04LMJWQT/p1601413682009300

Findings:
- Unable to reproduce the font weight issue.
- Need to see if there is something affecting in his app

**Comment by taysea** [comment]
I had a conversation with Mike Kingdom today to go over some work he's been doing to implement the theme on Quake UI, and one comment he had around font was that he felt the new font was slightly fuzzier than the old. These screenshots are on Windows Chrome. It's subtle, but I definitely do notice the slight fuzziness. On the left is the sidebar with the old theme, and on the right is the sidebar on the new theme:
<img width="396" alt="Screen Shot 2020-10-02 at 2 45 29 PM" src="https://user-images.githubusercontent.com/12522275/94972370-f7f09000-04bd-11eb-8a62-8d653e2fdda9.png">
