### ISSUE TITLE
Primary color research documentation/rationale

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1163]
Expand the documentation regarding the primary color including research, WCAG compliance and Brand compliance.

Figma Color file:
https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=0%3A1

**Comment by ericsoderberghp** [comment]
Who wants this?

> Storage Team, Brand…Cover your butt clause in support of WCAG AAA

> Storage and Brand. My hope is that t will help facilitate the conversations with the two

> The resulting documentation is there, I think we just want to be organize the research and be more explicit in the findings

**Comment by gregfuruiye** [comment]
I've provided an attempt to document clearly, with notes, regarding brand and primary green.

https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=1834%3A0
