### ISSUE TITLE
How do we visualize Component Anatomy?

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1170]
We've explored this and used different visualizations. We need to standardize how we should do this that meets the needs of des and dev

**Comment by rajasekar-ramasamy** [comment]
https://www.figma.com/file/TyLfCDRpUbi9mDXuDZellq/Component-Anatomy?node-id=3%3A0

**Comment by ericsoderberghp** [comment]
Do we really need to go about red-lining everything? That seems like a lot of effort.
