### ISSUE TITLE
Multi-Select Input

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1171]
Conduct exploration research and recommendations with potential designs

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp @gregfuruiye I would like to know your feedback on the design option for Multiselect Input
https://www.figma.com/file/dMqsrFWxJW58EYBEAubyEq/Multiselect-Input?node-id=92%3A0

**Comment by ericsoderberghp** [comment]
I like the idea of doing some user testing on this. I think we should cover a range of scenarios:
- a wide range of label string lengths, for example "1" through "Los Angeles, California, USA"
- long lists of options, with tests that require searching
- range of selection lengths, for example 0, 1, 2, 5, 20
and, I think we should put it in some context, for example a Form with other types of inputs in it.
