### ISSUE TITLE
Notifications - Ideate on a Taxonomy

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1173]
Leveraging the Notifications Exploration research, ideate on a notifications taxonomy.

These help give guidance for decision tree #1169 and templates #1172

Exploration research findings:
https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=0%3A1

**Comment by gregfuruiye** [comment]
Taxonomy Research is addressed in issue #1208

**Comment by KennyAtHPE** [comment]
[Updated Notifications taxonomy](https://design-system.hpe.design/components/notification?q=notifi#taxonomy). User studies and research can be found [here](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=51%3A264).

Closing this ticket out.
