### ISSUE TITLE
Test out Table " how to build" with GLC team

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1176]
Raja has set some time to talk w/ the GLC team. Part of this meeting will be to see whether the 1-4 steps on the Figma file are easy to follow and whether it is something we'd like to incorporate into our other components/adjust. 

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2190%3A138540

**Comment by MikeWalrath** [comment]
Closing for now until a dedicated researcher is available.
