### ISSUE TITLE
Aligning sort icon on Table Headers to Figma file

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1180]

**Comment by vavalos5** [comment]
<img width="212" alt="Screen Shot 2020-10-09 at 10 18 36 AM" src="https://user-images.githubusercontent.com/62117454/95612881-ea388e80-0a18-11eb-93f4-e0934de08020.png">
<img width="237" alt="Screen Shot 2020-10-09 at 10 18 43 AM" src="https://user-images.githubusercontent.com/62117454/95612887-eb69bb80-0a18-11eb-813c-c971d3fd32d1.png">

**Comment by ericsoderberghp** [comment]
This sounds like a theme issue. Is it?

**Comment by halocline** [comment]
> This sounds like a theme issue. Is it?

I need to look closer, but I believe the alignment has to do with only showing the sortable icon on hover. The theme has the correct icon specified.

**Comment by vavalos5** [comment]
My apologies for not being more specific. This ticket is indeed to align the sortable icon on hover as shown on the images.

**Comment by ericsoderberghp** [comment]
It still sounds like a theme or grommet issue. I wouldn't expect the design system site to have any code related to this.

**Comment by halocline** [comment]
Tagging with this PR https://github.com/grommet/grommet/pull/4605

**Comment by halocline** [comment]
Here is a preview link to this behavior: https://deploy-preview-1218--keen-mayer-a86c8b.netlify.app/components/table

I believe this is the last outstanding item for Table alignment between dev and Figma. Adding [this issue](https://github.com/grommet/hpe-design-system/issues/1219) to serve as final pass review of the Table implementation, then incorporate all staged theme changes in the HPE Theme.
