### ISSUE TITLE
Fix padding of checkbox on Table header to align with checkboxes below it

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1181]

**Comment by vavalos5** [comment]
<img width="1139" alt="Screen Shot 2020-10-09 at 8 31 47 AM" src="https://user-images.githubusercontent.com/62117454/95613161-5c10d800-0a19-11eb-9859-ccc10db359d8.png">

**Comment by ericsoderberghp** [comment]
Can we convert to use DataTable's built in select? https://storybook.grommet.io/?path=/story/datatable--select

**Comment by halocline** [comment]
> Can we convert to use DataTable's built in select? https://storybook.grommet.io/?path=/story/datatable--select

Converted this example to use the built in select ~2 weeks ago. The alignment of the checkbox was correct at the time of that work, so need to investigate what is causing the misalignment now.
