### ISSUE TITLE
Update global/persistent header to align with CCP designs

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1185]
Take the CCP global header and incorporate that into the design system. Proposal is to add a "Global Header" page.
https://www.figma.com/file/qxdE6A2qswCVbW3R6Ti7KG/CCS-v0.09-(New-Navigation)?node-id=2796%3A67686

**Comment by taysea** [comment]
@ericsoderberghp I have a couple questions on this issue that I think will better help define what we hope to see implemented on the site:
1. How does global header differ from what we've already defined on the [header page](https://design-system.hpe.design/components/header) as "App Header"? If they are separate concepts, how do we define one vs the other?
2. With regards to the linked design, what happens when you click on the "menu" icon on the top left? I see here that there is a sidebar flyout (https://www.figma.com/file/qxdE6A2qswCVbW3R6Ti7KG/CCS-v0.09-New-Navigation?node-id=2581%3A2) Is the format of the content the becomes visible intended to be standard across all teams? or is this content flexible?
3. How does this header behave on mobile?

**Comment by ericsoderberghp** [comment]
> @ericsoderberghp I have a couple questions on this issue that I think will better help define what we hope to see implemented on the site:
> 
> 1. How does global header differ from what we've already defined on the [header page](https://design-system.hpe.design/components/header) as "App Header"? If they are separate concepts, how do we define one vs the other?

The Global Header will be used for everything in the CCS/CCP portal, basically everything in the coming HPE as-a-service UI. It is very opinionated. The App Header would be used for other contexts, like UIs for embedded device management, and can be flexible to the needs of the context. App Header is more of a concept guidance whereas the Global Header is specific instance.

> 2. With regards to the linked design, what happens when you click on the "menu" icon on the top left? I see here that there is a sidebar flyout (https://www.figma.com/file/qxdE6A2qswCVbW3R6Ti7KG/CCS-v0.09-New-Navigation?node-id=2581%3A2) Is the format of the content the becomes visible intended to be standard across all teams? or is this content flexible?

I'd check with the CCS designers. I believe it is standard, but perhaps I'm wrong.

> 3. How does this header behave on mobile?

I'd check with the CCS designers. I would lean towards the way the Slack app behaves on iOS.

**Comment by taysea** [comment]
Sounds good, planning to touch base with Diane tomorrow to gain clarity on a couple of those things. Thanks for the replies.

**Comment by taysea** [comment]
Summary from discussion with Diane:
- The sidebar is a left anchored Layer that appears when the user clicks the Menu button.
- On mobile, the Layer should take full screen. The "Home" and "Help" icons that appear next to the Avatar on Desktop are not present on mobile. She is going to follow-up to see where those icons would appear on mobile (potentially in the menu layer).
- Questions to be discussed and answered is: how does content in the sidebar stay fixed/scroll in cases where the menu content is too long for the viewport height (assumption to start is header/footer stay fixed but the middle region would scroll). Diane will follow-up with CCS team for clarity.

**Comment by taysea** [comment]
Documenting a couple areas that will be beneficial to have clarity on as we polish this example:
1. Currently, I am referencing the CCS Figma Designs. If we are going to link from the Design System site to a Figma file, are we planning to have a Design System Global Header in Figma? Or, are we linking to the CCP file?
2. The CCP file shows 3 name variations for the Header:
   - **HPE Console** (all bold)
   - Hewlett Packard Enterprise (no bold)
   - **Aruba** Network Manager (Aruba is bold, the subsequent name is not)
The question is, are these the only 3 variations that will ever exist or could something else ever take the place of "Console" or "Network Manager"? If so, How do we give guidance around when to bold vs not to bold?
3. From an implementation standpoint, the examples contains many elements beyond just the header. For example, when the Menu button is clicked, a sidebar layer comes out. When the avatar in the header is clicked, a drop comes down. All of these things are critical to demonstrating the behavior of the various elements, but it makes consuming the code from the site much more complicated from a scan-ability perspective. If we are planning to start with a "one source of truth" for where this header code lives, we may want to think of breaking it down into smaller files where teams could add a directory containing all the relevant files to their code.

**Comment by ericsoderberghp** [comment]
> 1. Currently, I am referencing the CCS Figma Designs. If we are going to link from the Design System site to a Figma file, are we planning to have a Design System Global Header in Figma? Or, are we linking to the CCP file?

My leaning is to have this in the Design System Figma, so that designers can pull it in the same way they use other components. But, I'll defer to the designers if they have other opinions.

> 2. The CCP file shows 3 name variations for the Header:
>    
>    * **HPE Console** (all bold)
>    * Hewlett Packard Enterprise (no bold)
>    * **Aruba** Network Manager (Aruba is bold, the subsequent name is not)
> 
> The question is, are these the only 3 variations that will ever exist or could something else ever take the place of "Console" or "Network Manager"? If so, How do we give guidance around when to bold vs not to bold?

Good questions for the CCP designers. I'd lean towards the first option in all cases. But, again, I'll defer to the designers. Also, I don't think that should be an `<h1 />`.
 
> 1. From an implementation standpoint, the examples contains many elements beyond just the header. For example, when the Menu button is clicked, a sidebar layer comes out. When the avatar in the header is clicked, a drop comes down. All of these things are critical to demonstrating the behavior of the various elements, but it makes consuming the code from the site much more complicated from a scan-ability perspective. If we are planning to start with a "one source of truth" for where this header code lives, we may want to think of breaking it down into smaller files where teams could add a directory containing all the relevant files to their code.

Agreed on smaller files. I'd start by building it the way you'd most want it as a developer for yourself. We can adjust the file structure later as needed.
