### ISSUE TITLE
busy, loading, transition behaviors

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1195]
What should be shown while:
- waiting for content to arrive
- changing pages
- ???

**Comment by MikeWalrath** [comment]
![image](https://user-images.githubusercontent.com/17712467/96492146-6d6b9880-1200-11eb-9055-37910143e223.png)

**Comment by MikeWalrath** [comment]
GreenLake Use Cases

Lists: “I want to display a loading state while I fetch the users for my UserList”
Infinite scroll: “I want to display a loading state while my UserList fetches the next chunk of paginated user data”
Dashboards: “I want to display a loading state while my dashboard loads its content (widgets, charts, etc). Should there be a single loader (like CA) or loadable sections (like C2)?”
Widgets: “I want to display a loading state inside my widget, between the point that it renders and the point that its data is loaded”
Charts: “I want to understand how/when to render my graphs in a widget or on a dashboard while its data is loading”
Pages: “I want to display a loading state while my page loads its data”
Contextual Switching (tenant & space loading): “I want to display a loading state while tenant & space switching. This may include the loading of the new permissions, spaces, etc”
Modals/Flyouts: “I want to display a loading state while my modal or flyout loads its data”
App: “I want to display a loading state during app-level events, like logging in or logging out”

**Comment by vavalos5** [comment]
Some initial questions I have are:

Are we looking to have different variations for different use cases? i.e. spinner, dots, rotating circle, large numbers, etc..
<img width="414" alt="Screen Shot 2020-11-06 at 2 11 50 PM" src="https://user-images.githubusercontent.com/62117454/98419579-37b91300-203a-11eb-80f2-df7926fb32de.png">
<img width="210" alt="Screen Shot 2020-11-06 at 2 11 35 PM" src="https://user-images.githubusercontent.com/62117454/98419582-3a1b6d00-203a-11eb-9367-141dc1dac05a.png">
<img width="619" alt="Screen Shot 2020-11-06 at 2 11 04 PM" src="https://user-images.githubusercontent.com/62117454/98419588-3ee02100-203a-11eb-896f-a81b98d70063.png">
<img width="788" alt="Screen Shot 2020-11-06 at 2 12 03 PM" src="https://user-images.githubusercontent.com/62117454/98419573-338cf580-203a-11eb-90c6-b07a08edea2c.png">

Sizing for different resolutions?

**Comment by ericsoderberghp** [comment]
I think there are a wide variety of use cases. Maybe we can start by creating some terms to categorize this stuff by?
I think size is a key aspect. For instance, loading large content, where we might want something like coarse blocky placeholders, vs. a small piece of content that takes a little longer to arrive.
I think it would be good to do some exploration, research on this problem space, find a wide range of examples, look for some existing research articles, etc.

**Comment by vavalos5** [comment]
Research can be found here:

https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Loading-Indicator-Component?node-id=1%3A18

**Comment by vavalos5** [comment]
Discussed and did a share out. Next step is to connect with Matt on Monday to synthesize the problem statement and next steps.
