### ISSUE TITLE
Form - Further documentation of validation guidance 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1197]
We need to be more explicit in explaining the functionality of validation within forms. We have different options to validation within forms and having guidance around when to use and what the benefits are will help design and dev.

It would also be valuable to add text within the long form example stating the scroll to the first validating error so it can be identified by the user.

Michael Plazek is very interested in this as well. Would be good to discuss with him more to collaborate on the guidance.

**Comment by halocline** [comment]
Related discussions and (potentially redundant) issues:
https://github.com/grommet/hpe-design-system/pull/999#issuecomment-665860825

https://github.com/grommet/hpe-design-system/issues/745
https://github.com/grommet/hpe-design-system/issues/593

**Comment by ericsoderberghp** [comment]
Replace by https://github.com/grommet/hpe-design-system/issues/2474
