### ISSUE TITLE
InfiniteScroll design

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1201]
Elaborate on the design of how infinite scrolling works.
- How far ahead does it load?
- What indication is there that it is working, if the loading takes a while?
- How does the scroll bar work? For example, does it cover the whole length or just what has been loaded so far.

**Comment by MikeWalrath** [comment]
Designs for review. 
https://www.figma.com/file/XOEwUOqtfLAowprV2psWHM/HPE-Infinite-Scroll?node-id=0%3A1
