### ISSUE TITLE
Page Layouts - complex filtering experience

### ISSUE THREAD

**Issue by lorbritton** [grommet/hpe-design-system#1202]
How might we create filtering for complex use cases that feels simple and intuitive for both technical power users, and non-technical customers?

* Consider:
    * Breakpoints/Experiences for 500, 1,000, 2,000 filters. 
    * How do we display their chosen filters at these breakpoints?
    * How can we help customers find the filter(s) they want to select quickly and easily.

Simplifying this experience will help us create the intuitive, consumer-like experience that customers expect with aaS. This is important because we will have less technical users as we move to aaS, and technical users are looking to outsource routine capabilities so they can focus on strategic work. More can be read in the ITDM study and CA usability study here:
https://hpe.sharepoint.com/:f:/t/hpe-design/EgQ_fD9_Ey5NlyYLluF6BGoBhdCvqJAlKsCr-2hcdx524A?e=u0rt8r
https://hpe.sharepoint.com/:b:/t/hpe-design/ERnlo8aaY7dAgW6JpuzYvF8B5mMS_u9dGd07GC76jFhL1w?e=JetVjH

**Comment by taysea** [comment]
Addressed by Data+friends Figma/Grommet components and guidance: https://design-system.hpe.design/templates/filtering
