### ISSUE TITLE
Read Only - Form Field Input 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1204]
How do we show information that is not a "disabled" but still valuable info to show the user?
![image](https://user-images.githubusercontent.com/17712467/96491176-17e2bc00-11ff-11eb-91a4-ef953a3766aa.png)

**Comment by ericsoderberghp** [comment]
Given that `disabled` doesn't mean "ignore", I think we should explore a different treatment for disabled fields such that they aren't so visually subdued.

See the CSS example for Account ID above as one approach for consideration.

**Comment by vavalos5** [comment]
A question I have is: Would this be considered a text input? I assume yes and would be added to the text-input Figma file.

**Comment by vavalos5** [comment]
Some questions:

Because a read-only is not something you put text into, is it still a text-input field? I ask because would it still be styled the same as a text-input or would it have different styling where the text is left-aligned rather than the 12px padding on the left and right of the text-field box. 

Trying to figure out how this would be styled so it isn't confusing when on a form.

**Comment by ericsoderberghp** [comment]
Good questions. I think we should consider it primarily in a Form context, where there are other TextInput fields that the user can edit in the neighborhood. So, I think viewing as a way to style a TextInput is a good approach.

**Comment by vavalos5** [comment]
Figma file: https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=2835%3A13

**Comment by ericsoderberghp** [comment]
Fantastic research!!!! I really appreciated the details around readonly vs. disabled, the accessibility aspects of keyboard interaction, and how form submittal works. Well done.

In the third Option, where it appears more like a TextInput, I think it will cause less confusion when interacting with the keyboard and it will be less surprising that the content is submitted with the form. So, I'm inclined to head that direction. But, it could be tricky to ensure the background color isn't too dark, reducing accessible legibility or too light, losing distinction.

**Comment by ericsoderberghp** [comment]
If we go with something like option 3, I think we should enhance grommet to allow theming of the readonly case different from the disabled case.

**Comment by gregfuruiye** [comment]
In regards to the background color and accessibility, the Option 3 design is WCAG AAA compliant, so we should be good there since all the colors should allow us to be successful there.

**Comment by ericsoderberghp** [comment]
OK. Need to take care of dark mode backgrounds. Also, should ensure it works against `background`, `background-front`, and `background-back` colors. I'm inclined to say it should have some opacity in it, which will help it work across various background colors.

**Comment by vavalos5** [comment]
So in dark mode, I realized that if we are going to be going with the 3rd option, we don't have a contrasting color that is opaque that would meet accessibility. In light mode, for the background color on the read-only input, it is `background-back` which makes it look like it has a sort of opaque background, however in dark mode, that doesn't translate the same. Rather the input field background is the same color as the background behind it. I have examples in the file for better visual clarification.

I think it might be best to go with option #1 as it's the most simplest. No background color, no border, just a text box with a value that is uneditable. 


https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=2932%3A40

**Comment by ericsoderberghp** [comment]
OK, let's go with your recommendation of Option 1.

What do we want to say about other input types? My inclination is that they should support read-only as well.
If so, can we see how they might look? For example, Select, CheckBoxGroup, RadioButtonGroup, TextArea.

**Comment by vavalos5** [comment]
Great point! I have a ticket for TextArea already so i'll include the others. Thanks Eric!
