### ISSUE TITLE
grommet Button sizes in Figma

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1205]
Bring the grommet functionality for Button sizes into Figma and the design system site.

Proposal is in Figma:
https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=1842%3A0

**Comment by gregfuruiye** [comment]
In Figma, we don't have icon sizes, yet. So we may want to consider adding icon sizes so that when using a large button, you get a large icon when needed, etc.

**Comment by ericsoderberghp** [comment]
Can we add a link to the appropriate Figma location for this?

**Comment by ericsoderberghp** [comment]
I'd like to understand what changes are needed on the grommet and HPE theme sides for this. From my reading of the Figma contents, grommet will need:
- scale the icon size to align with the line-height of the text, when no size is supplied by the caller
- scale the gap between the label and icon
then the HPE theme might need the pad and border rounding aspects to be updated. Or, are those already present in either grommet by default or in the HPE theme?

**Comment by gregfuruiye** [comment]
Here is the Figma file link, I've added it to the issue description as well:

https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=1842%3A0
