### ISSUE TITLE
Non-Linear Workflow Patterns/Behaviors

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1207]
The Wizard template provides for a simple, linear workflow. There is a need to provide behavior for non-linear workflows with wizard.

Problem Statement

> As a GLC UI developer I need to develop a user interface that supports nonlinear workflows and user experiences and I would like to reference a standard set of designs and samples that support this type of workflow.

Rally story is F2563
https://rally1.rallydev.com/#/335045685124ud/dashboard?detail=%2Fportfolioitem%2Ffeature%2F439388977744

**Comment by gregfuruiye** [comment]
**From Rally F2563 Description**

User Benefits:

Users can complete workflows that may require input from other services or certain functions may need to be 'incomplete' for a period of time without pausing the overall workflow.
Feature Use-Cases:

As a GLC UI developer I need to develop a user interface that supports nonlinear workflows and user experiences and I would like to reference a standard set of designs and samples that support this type of workflow.
Ensure that setShow/setHide are improved or replaced with a statefully-correct approach (see DE4548)
Workflows, Wireframes, UX designs:

An essential part of this feature is to investigate the difference between linear and nonlinear workflows based on input from the Q2C and CA teams.  Design work will flow from these investigations.
We will partner with the Design System team in this effort.
Feature Acceptance Criteria:

Requesting service teams, Q2C and CA, have been interviewed to identify specific use cases and requirements.
Service team driven use cases and requirements will form the prioritization for supporting designs and samples.
Requesting service teams will review all proposed designs and samples prior to feature completion.
Designs and samples will be published and communicated to the overall GLC UI developer community.
User Documentation:

No end user documentation required.
GLC Service UI developer documentation will be provided by the Pioneer team.
Training Needs:

Pioneer team will host a webcast to introduce new designs and samples.

**Comment by MikeWalrath** [comment]
Will re-open if use cases arise
