### ISSUE TITLE
Notifications - Iterate Taxonomy

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#1209]
Dependant upon #1208

Iterate Notifications taxonomy based on consuming on research results from #1208

**Comment by gregfuruiye** [comment]
@KennyAtHPE is going to review the research and identify additional needs.

**Comment by KennyAtHPE** [comment]
Created a [user study](https://manager2.userzoom.com/5834/monitor/1187) with Chris and will be sending that out this week. 

The main goals for the study:
- Iterate and/or validate existing taxonomy
- Categorize additional terms

**Comment by KennyAtHPE** [comment]
A new iteration of the notification taxonomy has been created based on the user study synthesis
