### ISSUE TITLE
Add a readonly text area into Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1213]
Once we decide on an approach for a read-only input, we can add the same styling to text area Figma file

**Comment by MikeWalrath** [comment]
Blocked by decisions on #1204

**Comment by vavalos5** [comment]
Realized there's a bit of researching to do for this as well since there is a corner icon on text-area. In text input, we have the value text box to meet the ends of the box around it, however, i'm not sure how it'll work with text-area due to the corner icon as text can overlap it

**Comment by ericsoderberghp** [comment]
Will be tracked via #1419
