### ISSUE TITLE
Button - break out tool tip from drop button and add to draft in Figma

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1214]
With Grommet tooltip in progress it causes confusion with it being in the library within Figma.

**Comment by ericsoderberghp** [comment]
https://www.figma.com/file/Jd34cI5yyZIPb5BIwkIPU2/HPE-Tooltip?node-id=1%3A280

**Comment by ericsoderberghp** [comment]
I think the 80% case is to put a tip on a Button that only has an icon. It would be good to have an example of that case. I think I'm just suggesting having the examples feel a bit more real.

**Comment by gregfuruiye** [comment]
I'll be adding in some researched best practices to contribute to a final design.

**Comment by ericsoderberghp** [comment]
Related to #2450

**Comment by KennyAtHPE** [comment]
Noted as part of #2450, closing this ticket out.
