### ISSUE TITLE
Final pass review of Table page implementation. Then move Table/DataTable styling to the HPE theme.

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1219]

**Comment by taysea** [comment]
- When header label is right justified, should the icon already take up space? Example here:
<img width="193" alt="Screen Shot 2020-11-04 at 10 14 21 AM" src="https://user-images.githubusercontent.com/12522275/98152408-8920a100-1e86-11eb-98b2-9a4c173d2fea.png">
