### ISSUE TITLE
Align form + wizard designs on DS site to align with Figma file + Add guidance

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1222]
After designs and guidance on Figma files have been determined, both need to be updated and added onto the DS site

**Comment by halocline** [comment]
Wizard alignment of site with Figma is now being tracked here: https://github.com/grommet/hpe-design-system/issues/1237

**Comment by rajasekar-ramasamy** [comment]
I have updated the Figma file for Wizard as per the Design System site 
https://www.figma.com/file/GEhgYzx3b8MejBjg9gAxyA/Wizarding?node-id=0%3A1

**Comment by vavalos5** [comment]
Made some small spacing adjustments, but overall, looks good to me! I think this is good to close
