### ISSUE TITLE
Notification Taxonomy Card Sort: Synthesis and Share-Out

### ISSUE THREAD

**Issue by lorbritton** [grommet/hpe-design-system#1224]
Data from the notification taxonomy card sort will be synthesized and shared out with the DS team.

**Comment by MikeWalrath** [comment]
Synthesis https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=51%3A264

**Comment by MikeWalrath** [comment]
Share out: https://hpe.sharepoint.com/teams/hpe-design/_layouts/15/Lightbox.aspx?url=https%3A%2F%2Fhpe.sharepoint.com%2Fteams%2Fhpe-design%2FShared%20Documents%2FStrike%20Teams%2FDesign%20System%2FResearch%2FNotification%20Taxonomy.mp4

Taxonomy Study: https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=51%3A264
