### ISSUE TITLE
Add indication of num filters applied on filtering examples

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1231]
https://www.figma.com/file/EA0OZFdocKVcQ55c7Jainb/HPE-Filter-Templates?node-id=1%3A3738

<img width="567" alt="Screen Shot 2020-11-04 at 9 39 43 AM" src="https://user-images.githubusercontent.com/12522275/98148326-bdde2980-1e81-11eb-81ec-be4354deb058.png">

**Comment by ericsoderberghp** [comment]
Duplicate of https://github.com/grommet/hpe-design-system/issues/1347
