### ISSUE TITLE
Missing guidance and examples coupling layout, background colors, gaps, etc.

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1240]
GLC is using the design system site and having trouble with page layout examples and guidance. For example:

- Page Layouts page (https://design-system.hpe.design/templates/page-layouts) uses gaps, rounding, and colors that are causing people to replicate rounding and gaps and to not understand how background color should be used.
- Examples (like https://design-system.hpe.design/templates/forms) have an outer border and rounding that are causing people to apply those styles.

We should audit the Examples to be more accurate in these details.

We should provide better guidance and examples on how background colors should be handled.

**Comment by ericsoderberghp** [comment]
Here's an example of what GLC is doing:

![image](https://user-images.githubusercontent.com/11637956/98304470-e2ff9480-1f74-11eb-8c9c-349f10d2be43.png)

**Comment by halocline** [comment]
Breaking this issue into 3:
- [Streamline page layout examples](https://github.com/grommet/hpe-design-system/issues/1253)
- [Remove outer border from Form examples on the site](https://github.com/grommet/hpe-design-system/issues/1244)
- [Provide guidance for how background colors should be applied](https://github.com/grommet/hpe-design-system/issues/1254)

**Comment by halocline** [comment]
Closing because has been replaced by split out issues.
