### ISSUE TITLE
Remove outer border from Form examples on the site 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1244]
Please remove the boarders from the form examples. 
![image](https://user-images.githubusercontent.com/17712467/98402973-6aa4dc00-2025-11eb-9363-bec3dff46f93.png)

**Comment by ShimiSun** [comment]
I think we should also remove it from Figma.

**Comment by MikeWalrath** [comment]
FYI https://github.com/grommet/hpe-design-system/issues/1245
