### ISSUE TITLE
remove outer border of forms within Figma 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1245]
Please remove the boarders on the form examples within Figma

**Comment by gregfuruiye** [comment]
Thank you for saying 'please' :)

Borders have been Removed
https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1

**Comment by halocline** [comment]
> Thank you for saying 'please' :)
😂
