### ISSUE TITLE
Provide guidance for how background colors should be applied

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1254]
- [ ] create a new "Background Color" page under Foundation, start with content in this issue below
- [ ] cross link to "Color" page

Split off from https://github.com/grommet/hpe-design-system/issues/1240

Here's an example of what GLC is doing. Note the incorrect use of `background-back`.

![image](https://user-images.githubusercontent.com/11637956/98304470-e2ff9480-1f74-11eb-8c9c-349f10d2be43.png)

- [ ] Ideate and recommend how/where guidance for background colors should be applied
- [ ] Create implementation issue for recommendation to be added to the design system site

**Comment by MikeWalrath** [comment]
Current issue in GreenLake 
https://rally1.rallydev.com/#/331417062296ud/custom/341539024872?detail=%2Fdefect%2F449083300548

![image (6)](https://user-images.githubusercontent.com/17712467/99429982-f4766400-28c5-11eb-88c9-36c048cd6ddc.png)

**Comment by ericsoderberghp** [comment]
Here are some thoughts on content for this:

Guidance on background colors

Basic

The basic approach to background color is oriented around keeping the overall user interface focused and un-cluttered. Separation of sections in the page is accomplished primarily via typography and margins. An app-wide sidebar or header could be distinguished by another color with opposite darkness, for instance a dark blue persistent navigation sidebar. If there is a section of the page with secondary content, for example help text, background-contrast could be used.

background - the default background color when no other background color is specified
background-contrast - could be used to indicate secondary content
background(dark) or another color(dark) - could be used to indicate a primary navigation sidebar or header

Layered

The layered approach to background color is oriented towards more complex content situations, using background colors to help separate content sections in addition to typography and margins. In this approach, the overall background color should be "background-back" and then specific content sections that should be the primary focus of attention should use "background-front". For example, a page with a header, some summary content, and then a grid of Cards would use background-front for each Card and then background-back for everything else. For a multi-column page layout, background-front could be used to distinguish the column that should be more in focus.

From an information architecture as well as from a component layout perspective, background-back should not be used within a context that already has background-front. For instance, a primary navigation header should not use background-front above a main content section that uses background-back.

background-back - the overall background color
background-front - the background color of content that should be the primary focus
background-contrast - could be used to indicate a secondary content area within a large content section
background(dark) or another color(dark) - could be used to indicate a primary navigation sidebar or header

Note

The overall design philosophy is not to use a lot of borders to distinguish content sections. This helps reduce visual clutter that the eye and brain of the user must sift through.

**Comment by taysea** [comment]
Just made a couple adjustments to paragraph breaks and formatted for (hopefully easy) copy + paste into MDX, overall think it was great. Posting question for one part in a reply.

# Background Color Guidelines
There are two approaches to how background colors should be used: [Basic](#basic) or [Layered](#layered). See guidance for each approach below.

## Basic

The basic approach to background color is oriented around keeping the overall user interface focused and un-cluttered. Separation of sections in the page is accomplished primarily via typography and spacing (via margins and padding).

An app-wide sidebar or header could be distinguished by another color with opposite darkness, for instance a dark blue persistent navigation sidebar. If there is a section of the page with secondary content, such as help text, `background-contrast` could be used.

[IN THE LAYOUT, WE CAN INCLUDE THE COLOR ROWS?]

`background` - the default background color when no other background color is specified
`background-contrast` - could be used to indicate secondary content
`background(dark) or another color(dark)` - could be used to indicate a primary navigation sidebar or header

## Layered

The layered approach to background color is oriented towards more complex content situations, using background colors to help separate content sections in addition to typography and margins.

In this approach, the overall background color should be `background-back` and specific content sections that should be the primary focus of attention should use `background-front`. For example, a page with a header, some summary content, and then a grid of Cards would use `background-front` for each Card and then `background-back` for everything else. For a multi-column page layout, `background-front` could be used to distinguish the column that should be more in focus.

From an information architecture as well as from a component layout perspective, `background-back` should not be used within a context that already has `background-front`. For instance, a primary navigation header should not use `background-front` above a main content section that uses `background-back`.

[IN THE LAYOUT, WE CAN INCLUDE THE COLOR ROWS?]
`background-back` - the overall background color
`background-front` - the background color of content that should be the primary focus
`background-contrast` - could be used to indicate a secondary content area within a large content section
`background(dark) or another color(dark)` - could be used to indicate a primary navigation sidebar or header

**Note**

The overall design philosophy is not to use a lot of borders to distinguish content sections. This helps reduce visual clutter that the eye and brain of the user must sift through.

**Comment by taysea** [comment]
> Here are some thoughts on content for this:
> 
> Guidance on background colors
> 
> Basic
> 
> The basic approach to background color is oriented around keeping the overall user interface focused and un-cluttered. Separation of sections in the page is accomplished primarily via typography and margins. An app-wide sidebar or header could be distinguished by another color with opposite darkness, for instance a dark blue persistent navigation sidebar. If there is a section of the page with secondary content, for example help text, background-contrast could be used.
> 
> background - the default background color when no other background color is specified
> background-contrast - could be used to indicate secondary content
> background(dark) or another color(dark) - could be used to indicate a primary navigation sidebar or header
> 
> Layered
> 
> The layered approach to background color is oriented towards more complex content situations, using background colors to help separate content sections in addition to typography and margins. In this approach, the overall background color should be "background-back" and then specific content sections that should be the primary focus of attention should use "background-front". For example, a page with a header, some summary content, and then a grid of Cards would use background-front for each Card and then background-back for everything else. For a multi-column page layout, background-front could be used to distinguish the column that should be more in focus.
> 
> From an information architecture as well as from a component layout perspective, background-back should not be used within a context that already has background-front. For instance, a primary navigation header should not use background-front above a main content section that uses background-back.

^ This is the only paragraph I'm not quite sure on. I'm not sure I fully following what "background-back should not be used within a context that already has background-front" meant 
> 
> background-back - the overall background color
> background-front - the background color of content that should be the primary focus
> background-contrast - could be used to indicate a secondary content area within a large content section
> background(dark) or another color(dark) - could be used to indicate a primary navigation sidebar or header
> 
> Note
> 
> The overall design philosophy is not to use a lot of borders to distinguish content sections. This helps reduce visual clutter that the eye and brain of the user must sift through.

**Comment by halocline** [comment]
> The overall design philosophy is not to use a lot of borders to distinguish content sections. This helps reduce visual clutter that the eye and brain of the user must sift through.

I think we should lead with this ☝️ . This is the purpose statement (the WHY).

Next (The WHAT):
The application of background colors creates a visual hierarchy supporting the information hierarchy for the page. When applying background colors to content or layout, it is helpful to think about that content's role and relation to the page's information hierarchy.

Followed by (the HOW):
> There are two approaches to how background colors should be used: Basic or Layered. See guidance for each approach below.

**Comment by halocline** [comment]
I am attracted to the idea of trying to draw tighter coupling between information hierarchy and background colors.

Primary content - background-front (e.g. tables, lists, cards, charts/diagrams, etc.)
Secondary content (page context) - background or background-back (e.g. paragraphs, descriptive text)
Secondary content (container context) - background-contrast (e.g. header/footer of container, sidebar content like a "Did your know?..." or help text in a multi-column layout) 
Tertiary content - background with contrasting color or shade (content not directly related to the page's content, e.g. navigation)

**Comment by vavalos5** [comment]
I had to read these over a few times to fully grasp everything. I think that what Eric wrote is perfect! My only confusion still is when do we use`background-back`? I was going through a few designs to see if we use it anywhere, but we don't. Just the DS site. However, we're also saying that in GLC it's incorrect? Maybe i'm missing something because from the screen shot above, it looks like they are using `background-back`unles... it's a different color? 

I also read through Chris's definition a few more times on Figma " Known as ‘ background-back’  in the theme, this is used in a way to define depth in your designs by choosing ‘background-back’ the background will change to a darker tint, prioritizing the content on top which is called ‘background-font’. This is handy when using the box component and general app layouts"

I'm confused as to when to use it.. Or am I? Maybe some things are getting lost here. 

However, I would agree with Taylor & Matt on the guidance of when to use it and when not to use, along with creating these hierarchical combinations. I think including some visuals along with the context would be helpful. Would be happy to pair up and work on this together because I think this needs some further dissecting.

**Comment by ericsoderberghp** [comment]
<img width="313" alt="Screen Shot 2021-01-08 at 12 56 52 PM" src="https://user-images.githubusercontent.com/11637956/104063415-fca99c00-51b0-11eb-99ee-5ffe5ffed574.png">

swatches aren't working when in dark mode

**Comment by ericsoderberghp** [comment]
<img width="475" alt="Screen Shot 2021-01-08 at 12 57 37 PM" src="https://user-images.githubusercontent.com/11637956/104063481-177c1080-51b1-11eb-92d6-c0f6f18c68c3.png">

- This needs some responsive layout help.
- The browser window bar, being the same color as the sidebar and app header, makes it harder to see what's going on
- I don't think we'd recommend having the app header and the sidebar be the same background color. I was thinking those would be different dark colors. Or, we'd use one or the other but less likely both. In other words, maybe in the cases where there are both, the app header would have the same background as the content, with just the sidebar being the dark contrast.

**Comment by taysea** [comment]
Thanks for the feedback, let me do some cleanup here!
