### ISSUE TITLE
Make FormField margin consistent across Figma & Site

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1256]
Derek reported inconsistency in spacing between form field in Figma and Theme/Site: https://hpe.slack.com/archives/C04LMJWQT/p1605209013095900

- [ ] Reconcile CCS/DS Figma/DS Theme
Here is the CCS proposed guidelines which have the spacing conditional based on grouped/ungrouped (need to think how this might work from a theme perspective)
![image (3)](https://user-images.githubusercontent.com/1756948/98995913-4b0f2700-24ef-11eb-8561-9c2717723841.png)

The following was written up prior to the CCS info above.
It looks like Figma files want a total 12px spacing between form fields, however the theme is producing 18px of total gap.

I believe the theme needs the following adjustments:
- [ ] Set `formField.margin.bottom: 'none'` (removes 12px, currently getting that from `base.js` default)
- [ ] Set `formField.label.margin.top: 'xsmall'` (adds 6px top margin when label is present) https://github.com/grommet/grommet-theme-hpe/blob/4cf0cef5967b309cdb0e704f98c58fe77a415fd7/src/js/index.js#L594
- [ ] Set `formField.errors.margin.bottom: 'xsmall'` (adds 6px bottom margin when error message is present) https://github.com/grommet/grommet-theme-hpe/blob/4cf0cef5967b309cdb0e704f98c58fe77a415fd7/src/js/index.js#L574
- [ ] Evaluate whether info message should also receive a bottom margin of xsmall

FormFieldContentBox already has 6px vertical margin, so these adjustments should always get us to 6px + 6px = 12px whether a label or error messages are present.

- [ ] Should Figma components have the 6px vertical margin built into the components?
- [ ] If so, add to components.

**Comment by ShimiSun** [comment]
Might be duplicated or related to #1246. @taysea ?

**Comment by halocline** [comment]
> Might be duplicated or related to #1246. @taysea ?

Different circumstance.
