### ISSUE TITLE
Add issues for read-only input controls

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1257]
Please include a read-only input field on the site to align with designs:https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=0%3A1

- [ ] grommet changes?
- [ ] theme changes?
- [ ] design aspects of other input components or just TextInput?

**Comment by ericsoderberghp** [comment]
Will be tracked by #1419
