### ISSUE TITLE
Bug - Investigate "card does not have focus on FF / Windows"

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1265]
https://hpe.slack.com/archives/C04LMJWQT/p1605723632108900?thread_ts=1605720649.104900&cid=C04LMJWQT

**Comment by halocline** [comment]
Just did a quick BrowserStack test running Windows 10 / FF 82 (latest) --

I am seeing focus on the card here:
![Screen Shot 2020-11-18 at 11 30 43 AM](https://user-images.githubusercontent.com/1756948/99572302-b0e92c00-2991-11eb-9209-9451bb9cfd69.png)

**Comment by halocline** [comment]
Also ran tests on:
- Windows 10 / FF 74
- Windows 8 / FF 82

Both showing focus:
![Screen Shot 2020-11-18 at 11 38 24 AM](https://user-images.githubusercontent.com/1756948/99572912-9cf1fa00-2992-11eb-9287-89333da550ca.png)

**Comment by taysea** [comment]
@ericsoderberghp -- after the call with Edgar, it seemed there were some design pieces that needed to get sorted out around what the Card interactive behavior should be (default elevation, hover elevation) etc. when the entire card is clickable before we could update anything theme related.

The card does receive focus on FF windows as Matt's screenshot shows, so I don't think that is a bug. I think #1270 and #1272 represent some of the outcomes of that call. Is that correct?

**Comment by ericsoderberghp** [comment]
That sounds right. I think this issue was to ensure we don't have a fundamental focus indicator issue with Card on Windows and Firefox. If we've verified that things are behavior correctly, I think we can close this issue and let the other issues carry things forward.

**Comment by taysea** [comment]
Closing, #1270 and #1272 capture new action items.
