### ISSUE TITLE
Card - Provide guidance and example for cards with multiple actions

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1272]
"Single-click first" mentality, but option to fallback to include multiple actions.

- CardBody should contain primary action
- CardHeader & CardFooter secondary controls and actions
- If a card has a single action, the entirety of the card should act as a button. If a card has multiple interactive elements, then contents in the header, body, or footer may be clickable, and the "entirety of the card as a button" should be removed.

**Comment by ericsoderberghp** [comment]
Superceded by #2462
