### ISSUE TITLE
Add guidance to Table Figma file to when cells are bold

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1279]
In the Figma file, add guidance on when cells are bold. For example, the first column should always be bold to stand out as a unique identifier. 

Also, interactive elements should be bold

**Comment by vavalos5** [comment]
Figma file: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A13974

This ticket should be paired with #1293

**Comment by halocline** [comment]
@vavalos5 I left comments in Figma and in our Slack thread.
