### ISSUE TITLE
Filtering - Add example of filtering within a table 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1282]
Please add an example of a table using search/filter.

Implementation should also close: https://github.com/grommet/hpe-design-system/issues/1343

**Comment by vavalos5** [comment]
I feel like these are done and completed, but we haven't published and i don't recall why. @gregfuruiye 

https://www.figma.com/file/ChTUhUi0PiDCJ5V6iAYw5p/HPE-Search-Templates?node-id=3%3A3937

https://www.figma.com/file/EA0OZFdocKVcQ55c7Jainb/HPE-Filter-Templates?node-id=1%3A3738

**Comment by gregfuruiye** [comment]
Filter will be an ongoing evolution :) I would just check in with dev and ensure the design and implementation are aligned. I did not publish yet as we were still fiddling with the design system site.
@vavalos5

**Comment by MikeWalrath** [comment]
This particular issue would be for the Design System site
