### ISSUE TITLE
Loading breadth story

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1288]
## Problem Statement
"As a Tech Professional and user of HPE as-a-service products, I need to execute tasks, gather information, configure new jobs, etc. in an effective, productive, and confident manner. Often, I have many people depending on me for important and time-sensitive tasks. Scenarios where I need to be productive and deliver results sooner rather than later, but am dependent on systems or processes for which I am not in control, my perception will always be that things are taking too long and might even be uncomfortable by not being able to directly affect my outcomes. In these scenarios, I need to feel like I am productive, confident, and in control."

--> For user’s initiating an action in an HPE application and waiting for the application to perform the action, how might we provide a sense of forward momentum and control?

--> For user’s initiating an action in an HPE application and waiting for the application to perform the action, how might we best manage the perception of time and increase sense of control?

- Help people perceive screens are loading faster
- Eliminate surprises (manage expectations)
- Provide clear indication of progress
- Show exactly what has loaded and what remains
- Provide a sense of control

### Exploration file 
https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Loading-Indicator-Component?node-id=1%3A18

Create a breadth oriented story involving a couple of screens to consider the loading topic in context.
 - initial page load - splash
 - sign in - spinner
 - content - skeleton

**Comment by halocline** [comment]
Slight revisions to the problem statement, design challenge, ideation prompts: https://slides.grommet.io/?id=Design-Thinking---Articulating-a-Problem-Statement-matthew-glissmann-hpe-com#0

**Comment by MikeWalrath** [comment]
Reference to the Figma file 
https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Loading-Indicator-Component?node-id=1%3A17
