### ISSUE TITLE
Accept checkbox on Form in Figma is misaligned

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1296]
![Screen Shot 2020-12-02 at 11 07 35 AM](https://user-images.githubusercontent.com/62117454/100920202-a057ac00-348f-11eb-8451-8f66b30f6a8b.png)
The box around the accept checkbox is misaligned due to the long string of text. 

Figma file: https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=54%3A14

**Comment by rajasekar-ramasamy** [comment]
Fixed the design issue and published in Figma
