### ISSUE TITLE
Clean up Wizard Figma File + Publish

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1302]
Some items to clean up before we publish the Figma File as well as some general discussion questions:
- [x] Adjust two-column width to use grommet t-shirt size of "large"
- [x] **How should text colors be used? Here, we are using `text-strong` always but what is our guidance of when users should use `text` vs `text-strong`**
- [x] File should reference text colors from DS library as opposed to custom hex of #000000
- [x] Table of Contents / other frames should be consistent with other Figma files. Remove if unnecessary or update to match other files.
- [x] How do we convey that the language of "Wizard" in the sample text is placeholder? We don't want teams to actually say "Continue, wizarding" but instead they should substitute with text that is specific for their context. For example, "Continue setup", "Continue sign up", etc.
- [ ] Extend footer to extend to the full two column width

**Comment by rajasekar-ramasamy** [comment]
All the changes we updated
