### ISSUE TITLE
Complete Button size designs

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1306]
Starting from https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=1842%3A0

- [ ] align icon size to font line height, custom icon sizes
- [ ] align gap between icon and text appropriately, custom gaps
- [ ] define border width for all sizes, we probably should not be using the same width for all
- [ ] incorporate into all types, primary, secondary, default, with examples for each

**Comment by rajasekar-ramasamy** [comment]
**align icon size to font line-height, custom icon sizes**
Currently, the icon box size is mapped to the line-height of the fonts in the button

**Comment by vavalos5** [comment]
Spoke a bit with Raja about this ticket and I think i'm confused what we mean by defining width for all sizes? I assume we're talking about the icon width? If so, do we need to recreate icons with different widths (create t-shirt sizing for them)? Or do we just change the width inside of the button and have text below explaining that it has x amount of width?

**Comment by ericsoderberghp** [comment]
> Spoke a bit with Raja about this ticket and I think i'm confused what we mean by defining width for all sizes? I assume we're talking about the icon width? If so, do we need to recreate icons with different widths (create t-shirt sizing for them)? Or do we just change the width inside of the button and have text below explaining that it has x amount of width?

I think we need to describe the icon dimensions for each Button size. I don't think we need to align those sizes to the existing icon t-shirt sizes. I think we can set custom sizes that are aligned well with the Button font sizes.

**Comment by bahriaditi** [comment]
This came up again in [this Slack thread](https://hpe.slack.com/archives/C04LMJWQT/p1629809829107200) started by @revanth.sreedhar@hpe.com

Once we are done with defining button sizes, we should consider offering guidance for text input and select components too. See #1801

**Comment by bahriaditi** [comment]
@Keeth-HPe as discussed, can you help us with this next? 

- [ ] Connect with Raja to see where he left off and gain any additional context
- [ ] Review HPE [T-Shirt sizing](https://design-system.hpe.design/foundation/tshirt-sizing)
- [ ] Learn how to make a variant in Figma using the secondary button "small" size as an example

**Comment by vavalos5** [comment]
@Keeth-HPe Here is the Figma file I was talking about where it somewhat shows you how to work with variants.

However, this [YouTube video shows steps how to create variants](https://www.youtube.com/watch?v=y29Xwt9dET0).

Let us know if you have any questions

**Comment by bahriaditi** [comment]
Hi @Keeth-HPe as part of this work, could you also update the Toolbar Button component so it does not include the arrow icon on the right? By doing this, it will be differentiated from the existing [Menu](https://design-system.hpe.design/components/menu) component.

<img width="510" alt="Screen Shot 2021-09-07 at 9 58 00 AM" src="https://user-images.githubusercontent.com/87677275/132386412-8481acf4-e81f-4590-933d-740f2291cdab.png">

**Comment by Keeth-HPe** [comment]
Hey  @bahriaditi , I have updated the toolbar button component also completed working in Large button components. https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=667%3A385

Should we also create X-Large button variants ?

**Comment by bahriaditi** [comment]
@Keeth-HPe Adding next steps as noted by @vavalos5

- Pair up with developer to double make sure all behaviors are aligned
- Once adjustments are made to both design system site and Figma (if any), you can remove the current button variants in Finished page and move the finished ones in WIP to Finished.
- Publish the variants by going to Assets>Team Library>Publish X amount of Changes>Publish X amount of Changes
- Go to the Design System Channel and give everyone on the channel an update on how t-shirt sizing for buttons are now available and include Figma link

**Comment by vavalos5** [comment]
I have revised, made some small changes on the Figma file, published and posted on the HPE DS Channel. Ticket good to close
