### ISSUE TITLE
First Pass at Loading Behavior 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1307]
Create a first pass at the Loading Behavior templates
https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Loading-Indicator-Component?node-id=1%3A17

**Comment by ericsoderberghp** [comment]
Replaced by:
https://github.com/grommet/hpe-design-system/issues/1318
https://github.com/grommet/hpe-design-system/issues/1320
https://github.com/grommet/hpe-design-system/issues/1319
https://github.com/grommet/hpe-design-system/issues/1321
