### ISSUE TITLE
Icon usage guidance 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1308]
Look at different solutions to provide guidance on when to use specific icons.

**Comment by rajasekar-ramasamy** [comment]
Here's the link for the Figma file 
https://www.figma.com/file/JNOuPKyuS0OzRX8nQjMIbW/Icon-usage?node-id=0%3A1

**Comment by rajasekar-ramasamy** [comment]
I have simplified the icon usage-based the GLC team recommendation
https://www.figma.com/file/JNOuPKyuS0OzRX8nQjMIbW/Icon-usage?node-id=0%3A1

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp @vavalos5 I have made changes to the icons page based on feedback 
https://www.figma.com/file/JNOuPKyuS0OzRX8nQjMIbW/Icon-usage?node-id=245%3A12032

**Comment by ericsoderberghp** [comment]
I am planning to review Raja's latest above and create several issues to break it up into chunks.

**Comment by MikeWalrath** [comment]
Additional information from Edgar and GL https://designer.grommet.io/?id=GLC-Icon-Usage-edgar-circenis-hpe-com

**Comment by ericsoderberghp** [comment]
Superseded by #2171
