### ISSUE TITLE
Footer buttons have no href

### ISSUE THREAD

**Issue by karatechops** [grommet/hpe-design-system#1309]
Links in [footer](https://github.com/grommet/hpe-design-system/blob/98d56348804fd52fae18aaeb932833ce9c03dc05/aries-site/src/layouts/main/Footer.js#L47-L52) are not clickable. These are propagating to the DOM as a `button` element instead of an anchor tag with an href value.

![Screen Shot 2020-12-08 at 3 09 01 PM](https://user-images.githubusercontent.com/5983843/101536388-f1701000-3967-11eb-8ab4-4b98f8558250.png)

**Comment by ericsoderberghp** [comment]
I think we just need to make sure we give the Buttons `href` values, so they will become `<a />` elements in the DOM.
