### ISSUE TITLE
Finalize ToolTip 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1317]
https://www.figma.com/file/Jd34cI5yyZIPb5BIwkIPU2/HPE-Tooltip?node-id=0%3A1

**Comment by MikeWalrath** [comment]
Updated figma designs
https://www.figma.com/file/Jd34cI5yyZIPb5BIwkIPU2/HPE-Tooltip?node-id=1%3A280

**Comment by ericsoderberghp** [comment]
Some notes on exploring implementing this design:

![Screen Shot 2021-01-09 at 1 14 20 PM](https://user-images.githubusercontent.com/11637956/104108804-97bb7800-527c-11eb-84b2-983bad6d4f27.png)

It's complicated to get the combination of the background + border with the caret without making the the drop outline a single SVG. The simple approach of overlaying and positioning a caret doesn't work when the background has opacity, as the border of the underlying Box shows through. This could be mitigated by changing the background to have no opacity or by removing the border, neither of which are ideal.

The rounding on the caret would also require a special SVG with a path to achieve it. This isn't too messy. The above issue is more problematic.

Here is a branch with the code from the exploration: https://github.com/grommet/grommet/pull/4873

I think we should pursue a different approach to styling the tip that will be simpler to render, either by using an opaque background, removing the border, or removing the caret. My inclination is towards removing the caret.

**Comment by ericsoderberghp** [comment]
Works for me. Thanks for simplifying it. :)
