### ISSUE TITLE
Wizard - Evaluate GL Wizard Usability Test 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1327]
GL conducted a usability test on the Wizard template with some interesting results. Please take a look at the below as we define next steps. 
https://www.figma.com/file/ZENKB9QAMQZnGfwgrZVh81/Wizard?node-id=13%3A481 

Read and decide whether to schedule a meeting for broader discussion or just create issues.

Deliverables
- [ ] new issues for any further exploration or changes to make
- [ ] tie off with the GreenLake folks

**Comment by ericsoderberghp** [comment]
Superseded by #1915
