### ISSUE TITLE
Refresh Principles & Values

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1331]
We really need a set of principles,standards and values that elaborates to users what they've come to use our design system). We need to take a step back and strengthen the foundation of our design system with principles.

**What are principles?** 
According to NNG, " Value statements that describe the specific goals or priorities which are essential to the success of a product." They help support faster decision-making and consistency and should be specific to our product and user goals.

**Design principles are not:**
Generic usability guidelines
Team mottos or work processes Feature lists
Replacements for creativity or judgment

**What are values?**
Principles are the practical, stern, opinionated standards that guide decision making. They reinforce the core values and help decisions move in a consistent direction.

To really understand how to come up with our own principles and values, we need to assess how we've changed, what we do, what our goals are and see how we differentiate from other open source frameworks.

**Comment by vavalos5** [comment]
Including a PDF file Chris sent to me with Principles he had previously written.

[HPE Principles.pdf](https://github.com/grommet/hpe-design-system/files/6078135/HPE.Principles.pdf)

**Comment by vavalos5** [comment]
Started working in here. Doing research & setting the stage of how to approach P&V, so nothing conclusive in terms of new P&V

https://www.figma.com/file/8jLGXR0nBgFeuy9cdQUxWH/Principles-and-Values?node-id=1%3A10

**Comment by vavalos5** [comment]
On hold as I shifted to a different project ( CTO & Innovation Hub)

**Comment by vavalos5** [comment]
Left this comment in our Slack channel:

"Hi everyone, I’ve been doing some more research on Principles and as I’ve mentioned before, values are essentially principles. After doing some more research, i’ve also learned that creating principles isn’t a 1 person solution, but rather a product itself that should have multiple contributors as our Design System is used by others.
Earlier today I had a convo with David who is having a meeting with a few folks on the adoption of the Design System and is also interested in creating principles for the team. So i’m super interested in what he has to say there. But, I have also gathered some information on what principles are, what they’re not, why we need them and what steps we can take to get there."

Steps we can take to get there: https://www.figma.com/file/8jLGXR0nBgFeuy9cdQUxWH/Principles-and-Values?node-id=27%3A24

**Comment by ericsoderberghp** [comment]
I'm supportive of having some conversations on this. There was a enough detail in the Figma file to lead me to want to start with a conversation about the process of working on it. Perhaps when I get back from Yosemite we can discuss?

**Comment by vavalos5** [comment]
We are good with closing. Next steps are discussing with Greg and getting input on how to coordinate/facilitate.
