### ISSUE TITLE
What's New page

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1335]
[Preview](https://deploy-preview-1362--keen-mayer-a86c8b.netlify.app/whats-new)

Implement based on the design on artboard Desktop - 25 in https://www.figma.com/file/ZF49kIemstIfIiAul0rvWj/What's-New-Page?node-id=132%3A1315

## Deliverables
- [x] new page published on the site with content going back to December 2020
- [x] pin a note in the staff slack channel on when/how we'll update it

**Comment by vavalos5** [comment]
Wanted to make sure that we're settled on artboard: Desktop-25. I only ask because I wanted to make sure that we like the hierarchy of this look and also the way items are listed. Wondering if the way it is broken down is easy to read and informative. :) 

Let me know if we should chat about any changes

**Comment by ericsoderberghp** [comment]
I think implementing Desktop-25 will give us a good base to build off of later. It's a reasonable first step.

**Comment by ericsoderberghp** [comment]
Include brief notes about interesting conversations in Slack, especially with resolutions that emerged.

**Comment by ericsoderberghp** [comment]
The HPE.com slim header and footer can be found via https://github.com/grommet/hpe-design-system/issues/1354

**Comment by halocline** [comment]
[Preview](https://deploy-preview-1362--keen-mayer-a86c8b.netlify.app/)

Work in progress. Current preview shows pure markdown implementation and placeholder contents.

To Dos:
- [ ] Need to update our layouts / NextJs routing to account for pages with apostrophes in their names.
- [ ] Allow Layout to accept page intros which don't adhere to our current templates
- [ ] Allow for markdown styling to align to Figma design, but remain semantically correct
- [ ] Fix mdx styling for markdown elements such as horizontal rule
- [ ] ...

**Comment by halocline** [comment]
Closed by https://github.com/grommet/hpe-design-system/pull/1362
