### ISSUE TITLE
Refresh home page

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1336]
Update the home page design to include a link to What's New and the new promo video.

We've got a bit of this already in https://www.figma.com/file/ZF49kIemstIfIiAul0rvWj/What's-New-Page?node-id=130%3A94

But, we don't have the video yet. I'm also wondering whether we should explore a simpler approach to What's New, perhaps with just a star shaped badge button labelled "See What's New!" but with no other content for it on the home page, to keep the home page more streamlined.

For the video, I think we should explore an embedded viewer option.

Also include whatever hpe.com header and footer elements will be needed as part of https://github.com/grommet/hpe-design-system/issues/1290

**Comment by halocline** [comment]
Moving this comment from the What's New Page issue, but it is actually belongs here: The HPE.com slim header and footer can be found via https://github.com/grommet/hpe-design-system/issues/1354

**Comment by vavalos5** [comment]
Figma file: https://www.figma.com/file/CWB0xMmfVx6cT0ugzluySl/home-page?node-id=0%3A1

Lot's happening still. Trying to figure out which layout works best and what really is important to have on the home page.
