### ISSUE TITLE
Layer and Filter components to follow consistent behaviour with sticky header and footer

### ISSUE THREAD

**Issue by rajasekar-ramasamy** [grommet/hpe-design-system#1342]
GLC UX team is looking for recommendations for using a sticky header and footer for long-form within the layer.  

## Deliverables
- [ ] document guidance based on the comment below

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp here the prototype link "https://www.figma.com/proto/tMYqY8NvX2ZIdlZ6jKWlRl/US17846-Notifications-based-on-Monitor-status-change?node-id=1%3A695&viewport=1248%2C265%2C0.25&scaling=min-zoom"

**Comment by ericsoderberghp** [comment]
We had a meeting to discuss where we noted:
- for short forms, this doesn't matter
- for really long forms, it's annoying to have to scroll all the way back to the top to be able to close the layer
- we don't want to add a second close control at the bottom of the layer
- for filtering, the submit button should always be visible and the footer should be fixed
- for non-filtering forms, the submit button should be at the bottom of the form, encouraging the use to see the entire form first
- for longer non-filtering forms, have the header scroll away as the user scrolls down but when the user initiates scrolling up, show the header fixed to the top. See https://github.com/grommet/hpe-design-system/issues/1353
