### ISSUE TITLE
Include an example in Filter on how to label results after a selection has been made

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1343]
Diane had a question on the HPE DS channel in regards to how to display items that are selected underneath the search bar after a filter has been applied and then makes a selection.

Diane: "Hi again! Looking for some guidance on how to display items that are selected. In the first image, a user selects an item and their selection is reflected underneath the search bar. If a user searches/applies a filter and then makes a selection, should that be reflected in lieu of the result set or displayed elsewhere?" 

**Conversation** can be found here: https://hpe.slack.com/archives/C04LMJWQT/p1609886905246900

**Screen shots:** 

![image (4)](https://user-images.githubusercontent.com/62117454/103809420-5756c280-500e-11eb-80dd-12d07b8f92dd.png)

![image (3)](https://user-images.githubusercontent.com/62117454/103809414-558cff00-500e-11eb-8b83-005c2b16bc4f.png)

**Comment by halocline** [comment]
Related https://github.com/grommet/hpe-design-system/issues/1282 (add example of filtering applied to tables)

**Comment by vavalos5** [comment]
@taysea @halocline Are you two taking care of this ticket? If so, please let me know what changes I should make in Figma :) Y'all are the best!!

**Comment by halocline** [comment]
Will do. @taysea is implementing an example on the site this week. It will likely spur some discussion where we may want to modify the behavior a bit more, but this will get us something to react to -- there are some nuances that aren't as apparent until you see the behavior "live."
