### ISSUE TITLE
Form Messaging/Notification

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1352]
Greg reached out on the HPE DS channel and put together a quick design for a small but useful use case. The use case is what type of messaging/validation would be useful when there is success validation or some other neutral validation.

Would be worth investigating whether this is how we want to apply them or if this goes along with notifications and a banner would pop up?

Conversation: https://grommet.slack.com/archives/C04LMJWQT/p1610064344274200

Figma file w/ example: 
https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=3525%3A3487

**Comment by MikeWalrath** [comment]
Adding another design from CCS https://www.figma.com/file/KGfphc2fWsEF8GpRC9vKbS/CCS-v0.1?node-id=9684%3A46564

**Comment by ericsoderberghp** [comment]
Closing for now. Happy to revisit in the context of an actual user flow demonstrating when it would be helpful.
