### ISSUE TITLE
Incorporate HPE.com Slim Header Footer

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1354]
Will follow up with code. Example can be found on the DEV home page. https://developer.hpe.com/

[slim-hfws-instruction.docx](https://github.com/grommet/hpe-design-system/files/5805371/slim-hfws-instruction.docx)

**Comment by ericsoderberghp** [comment]
waiting for https://github.com/grommet/hpe-design-system/issues/1335
