### ISSUE TITLE
Run Cyber Security Scan

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1357]
All applications must have a current dynamic application security scan completed that scans
for, at least, the OWASP top 10 vulnerabilities. This scan is run against a test instance of
the application to identify security issues at run-time. Vulnerabilities identified by this scan
must be remediated prior to submitting evidence to Cyber Security that the application is
secure. You can find details on completing a dynamic security scan at the following link.

https://hpe.sharepoint.com/teams/cyber-issue-mgmt/compliance/SitePages/Scanning%20tools%20with%20guidance%20documents.aspx

**Comment by MikeWalrath** [comment]
#1290

**Comment by abhishekisforyou** [comment]
Basically High Factor like Python And Sytax ...that's needs to be more upgrade

**Comment by taysea** [comment]
I've created follow on issues to resolve 2 of the identified alerts: #1465 #1466
