### ISSUE TITLE
Add preliminary guidance on Accessibility page

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1359]
To start, a small intro on why accessibility is critical to our design and dev process.

For now, some links to important resources like WCAG, helpful browser plugins like WAVE/axe.

In future, we can expand this content.

**Comment by vavalos5** [comment]
I really like the start of what you have and thank you for getting this started. Here are some comments:

In the second paragraph under the "Accessibility" heading, I think you can remove "who" the 2 other times mentioned in the same sentence.

For the designer part, I think we can add some details about the steps we take to ensure our components are accessible. Here's my stab:

At HPE, we like to ensure that we create components that could be used by all and ensure the best user experiences through inclusivity. 

How do we insure accessible and inclusive designs?

1. Research 
2. Usability Testing/ Ask Questions
3. We observe, empathize and research again
4. Include others into the mix
5. Test again
6. Deliver!

I'm leaving this here for now and will continue. Need to let it marinate and research more on what else we could include
