### ISSUE TITLE
Remove white background color from Default button (Figma library update)

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1365]
This question also came up during a meeting with the Financial Services team on whether our default button should have a background-color or not. When the button is taken off of the board, it currently has a white background. The question is whether this button should have a background color or not.

**Comment by taysea** [comment]
I don't think so. I believe the default button is intended to have no background color, only a hover background color and active state

**Comment by vavalos5** [comment]
Well, that was easy! Thanks! I'll leave this in the backlog for now and make changes as soon as I can.

**Comment by bahriaditi** [comment]
Done ✅ and published component updates to Figma library
