### ISSUE TITLE
Ordering of different items 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1375]
The general concept is a control or set of controls that allow the user to specify a desired order of items.
A specific context for this could be configuring the order of columns in a table.
Another specific context could be ordering a set of preferred networks to use.

Come up with several alternatives for how this control or set of controls could be done.

Ideally, the solutions would be focused on one or more components that could be used in a variety of contexts, wherever the need to order things arises. So, it could work inside a Form, in a modal Layer, inline, etc.

**Comment by vavalos5** [comment]
Would this be for list, tables, cards...and any others?

**Comment by vavalos5** [comment]
I'm adding what i've been exploring for HPEFS as runners for this ticket: https://www.figma.com/file/sbGnnra3nO5WIu9AFiLBjJ/column-ordering-examples?node-id=0%3A1

**Comment by vavalos5** [comment]
File i'm working in: https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=0%3A1

**Comment by vavalos5** [comment]
Eric approved to move into ideate.
