### ISSUE TITLE
Adding Margin/Padding (t-shirt size) to DS

### ISSUE THREAD

**Issue by rajasekar-ramasamy** [grommet/hpe-design-system#1379]
Most of the designer is not aware of the Margin/Padding (t-shirt size) as per DS standard.

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp here's the design link for spacing component
https://www.figma.com/file/TcrcU8uB9JoW1UQi0masqc/Spacing-Syatem?node-id=0%3A1

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp I have created a prototype, let me know your thoughts 
https://www.figma.com/proto/TcrcU8uB9JoW1UQi0masqc/Spacing-Syatem?node-id=3%3A61&viewport=-933%2C223%2C0.38631686568260193&scaling=min-zoom

**Comment by ericsoderberghp** [comment]
Works. Where would you envision linking to it from?

**Comment by MikeWalrath** [comment]
We could add it as a section within the Grid page https://design-system.hpe.design/components/grid

**Comment by ericsoderberghp** [comment]
It's more tied to Box than Grid. Although, I'm wondering if we should just make it its own page, perhaps "Margin, Padding, Gap, oh my!"

**Comment by vavalos5** [comment]
I love the title and love the ideas behind this!

**Comment by rajasekar-ramasamy** [comment]
Spacing can be a separate component, it can a related component to the Grid system
https://www.figma.com/file/TcrcU8uB9JoW1UQi0masqc/Spacing-Syatem?node-id=24%3A61

**Comment by ericsoderberghp** [comment]
I don't think we should call it a "component", since that has specific meaning in react. You wouldn't "add a Spacing component".

**Comment by vavalos5** [comment]
I'm not sure where this ticket has been left off. Are we implementing what Raja created into box component? In the Box [Figma file](https://www.figma.com/file/cgTYs856lxE8LZpBpAdf1v/HPE-Box-Component?node-id=368%3A274), we have a sections called "edge sizes" that could be used for gaps, margins and padding on a box. However, we don't have the detailed visuals created.

**Comment by ericsoderberghp** [comment]
I thought we were going to create a design-system site page in either the Foundation or Extend section to put this content. This is partly driven by the fact that the concepts apply to more than just Box, such as Card, etc.

**Comment by vavalos5** [comment]
Gotcha. It looked like something that was going to be included on the site given the webpage layout but I wasn't sure. That being said, is there anything else needed from the design side? 🤔

**Comment by MikeWalrath** [comment]
@rajasekar-ramasamy we have discussed this a couple of times. I know you have been engrained in GL the last couple of week. Do you need some help finalizing this issue?

**Comment by ericsoderberghp** [comment]
I think we're good enough on the design side to incorporate into the design-system site. But, I'll ask it back to see if there's anything that you think would be helpful to add, perhaps in Figma? Or, elsewhere?

**Comment by vavalos5** [comment]
I can add the box examples Raja created into the Box Figma file.

One comment I left on Raja's Figma file is that we can knock 2 stones with 1 bird by making all of the boxes equilateral. This would solve for both vertical and horizontal spacing. Plus, we can eliminate one tab on the site example he has on Figma.

**Comment by ericsoderberghp** [comment]
go for it

**Comment by ericsoderberghp** [comment]
Superseded by https://github.com/grommet/hpe-design-system/issues/1644
