### ISSUE TITLE
ColumnBrowser exploration 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1383]
To facilitate the work to be done on we need to conduct an exploration on the ColumnBrowser component. Leverage the designs below as well as gathering additional uses cases, research articles, other frameworks, and NNG/WCAG guidelines to build a complete view of the ColumnBrowser. 
https://www.figma.com/proto/qxdE6A2qswCVbW3R6Ti7KG/CCS-v0.09-(New-Navigation)?node-id=5945%3A39378&viewport=446%2C101%2C0.015625&scaling=scale-down
https://designer.grommet.io/canada?id=ColumnBrowser-eric-soderberg-hpe-com

**Comment by ShimiSun** [comment]
Related to https://github.com/grommet/grommet/pull/4810

**Comment by MikeWalrath** [comment]
[CCS A/B share out](https://hpe.sharepoint.com/teams/hpe-design/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2Fhpe%2Ddesign%2FShared%20Documents%2FHPExs%20Research%2FUsability%2FUserZoom%2FStudies%2FIAM%20A%2DB%20Study%20%28unmoderated%29%2FCCS%5FIAM%5FPresentation%2Emp4&parent=%2Fteams%2Fhpe%2Ddesign%2FShared%20Documents%2FHPExs%20Research%2FUsability%2FUserZoom%2FStudies%2FIAM%20A%2DB%20Study%20%28unmoderated%29&p=true&originalPath=aHR0cHM6Ly9ocGUuc2hhcmVwb2ludC5jb20vOnY6L3QvaHBlLWRlc2lnbi9FYWpBQ1dBUkM1UklvaWhhdFJMTVVxd0JpOHRmdUxDc2tXM0duMjlHYURKWkJBP3J0aW1lPV94QWJjWExCMkVn)
[CCS-IAMRolesStudy-Shareout.pptx](https://github.com/grommet/hpe-design-system/files/5869578/CCS-IAMRolesStudy-Shareout.pptx)
