### ISSUE TITLE
Incorporate spacing in between Tabs to align with Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1385]
Edgar pointed out that icons are looking rather close to one another when using them in tabs (see image below)
![image (3)](https://user-images.githubusercontent.com/62117454/105737587-f9b9e580-5eea-11eb-9e9b-a3aec8088e80.png)

Please see convo here: https://hpe.slack.com/archives/C04LMJWQT/p1611337132021000

The problem is that the HPE theme needs to incorporate 12 px spacing between tabs to align with Figma file

Figma file: https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=0%3A1

**Comment by taysea** [comment]
I have a recollection that initially Chris/Maggie had incorporated the spacing between each Tab as a way to ensure the focus indicator wouldn't be covered by adjacent tabs, but we solved for this in grommet without needing the extra space. I thought there had been discussion to remove the space between Tabs but it looks like it wasn't removed (not sure if it was intentionally not removed or just got lost with other work).

This is a quick add in the theme to put the 12px spacing, but I just want to confirm that is the design direction we want to take. If instead we want the Tabs to remain directly touching, are there any other ways to improve the affinity between icon and label that we'd want to explore?

I'm comfortable going either direction, but just wanted to share my recollection of the initial intent with the spacing between each tab.

**Comment by vavalos5** [comment]
I would connect with Maggie. I'm not sure what the discussions behind this was.

**Comment by taysea** [comment]
After chatting with Maggie, we concluded that there should not be a gap in between individual tabs. However, to address the issue Edgar noted around affinity of icon with the label, we're proposing that the horizontal padding of the individual tab is increased from `small` to `medium`. Here is a screenshot that compares:

With tab padding of { vertical: 'small', horizontal: 'medium' }:
<img width="666" alt="Screen Shot 2021-01-29 at 1 24 23 PM" src="https://user-images.githubusercontent.com/12522275/106329369-26953200-6236-11eb-8260-1416ac58ea93.png">

(current implementation) With tab padding of { vertical: 'small', horizontal: 'small' }:
<img width="580" alt="Screen Shot 2021-01-29 at 1 30 41 PM" src="https://user-images.githubusercontent.com/12522275/106329406-3745a800-6236-11eb-9fbb-3fb075261812.png">

Maggie has offered to update the Figma Tabs file as needed if that'd be easier and if we are comfortable with these changes.

**Comment by vavalos5** [comment]
I like the proposal. If we're removing the 12px padding, I believe that should resolve the issue Diane had brought up on how tabs aren't adjusting correctly in Figma. #1370
