### ISSUE TITLE
Card - Establish guidance for hover behavior when clickable

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1390]
What should the hover behavior be for Cards when the entire Card is clickable? Elevation medium --> large?

To-do:
- [ ] Create design guidance
- [ ] Update Figma
- [ ] Update site examples and add written guidance

**Comment by vavalos5** [comment]
Great points! I think we should also include the different behaviors and Cards have in Figma. It's a question that has come up often.

Another is do clickable cards look different from those that aren't?

**Comment by ericsoderberghp** [comment]
Have this in the theme now
