### ISSUE TITLE
Update center layer example with left aligned text 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1395]
Update Figma and the design system site center layer example with left aligned text. 
![image](https://user-images.githubusercontent.com/17712467/106332220-965de980-6243-11eb-9649-83cea7c91dcf.png)

**Comment by rajasekar-ramasamy** [comment]
Indentation is been removed for the layer copy.
https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=100%3A70 
 icon needs to be changed to "email icon" as per the Figma. DS site uses "mail-option"
