### ISSUE TITLE
Update Wizard in Figma to match site

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1404]
Changes that need to be made to Figma wizard to match the site examples are:
- [x] Header uses `background-contrast`
- [x] Step titles are now using h1, size="small"
- [ ] Wizard Title uses size medium
- [x] 6px space between "step 1 of X" and step title
- [x] 6px space between step title and step description
- [x] 48px gap between step description and top of inputs
- [x] Inputs should be width = "medium" (384px), if there are two-columns in a single step, there should be a 48px gap
- [x] 48px gap between last input and step footer

For reference, see red lines on CCS example: https://www.figma.com/file/qxdE6A2qswCVbW3R6Ti7KG/CCS-v0.09-New-Navigation?node-id=4921%3A30293

**Comment by vavalos5** [comment]
@taysea thanks for being on the look out for these changes. Was the `background-contrast` color a recent addition/change? I don't recall this.

**Comment by vavalos5** [comment]
Changes have been made in the Wizard Figma file: https://www.figma.com/file/GEhgYzx3b8MejBjg9gAxyA/Wizarding?node-id=0%3A1
