### ISSUE TITLE
Update Figma file to demonstrate TextInput drop suggestions

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1406]
Shimi brought up the fact that in Figma we are currently not showing examples on how TextInput has a drop to give suggestions. Please align with DS site: https://design-system.hpe.design/components/textinput

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp I have created a prototype for search suggestion based on your comments in Figma
https://www.figma.com/proto/KKHWJN4GAI0Mq5yh0snDT6/HPE-Search-Component?node-id=813%3A622&viewport=-1368%2C-2849%2C1.0467289686203003&scaling=min-zoom

**Comment by ericsoderberghp** [comment]
Looks good. One comment, we currently don't have an easy way to make the matching characters bold in the suggestion options.

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp I have removed bold from matching characters
https://www.figma.com/proto/KKHWJN4GAI0Mq5yh0snDT6/HPE-Search-Component?node-id=813%3A228&viewport=-4274%2C-2706%2C1.0418604612350464&scaling=min-zoom

**Comment by ericsoderberghp** [comment]
That matches what we've got :)
I think this just needs to get folded into the Figma for TextInput at https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=2644%3A86
