### ISSUE TITLE
Update Figma file to demonstrate drop suggestions on Search

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1407]
<img width="442" alt="Screen Shot 2021-02-03 at 10 44 52 AM" src="https://user-images.githubusercontent.com/62117454/106793917-ed313d80-660c-11eb-8819-28f6884ace7e.png">
Please update Figma files to align with DS site [(https://design-system.hpe.design/components/search)](url)

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp @vavalos5 here's the concept design for [Autocomplete Suggestions](https://www.figma.com/file/KKHWJN4GAI0Mq5yh0snDT6/HPE-Search-Component?node-id=702%3A100)

**Comment by ericsoderberghp** [comment]
Nice! Dropped some comments in Figma.

**Comment by vavalos5** [comment]
Ticket is ready for a review https://www.figma.com/file/KKHWJN4GAI0Mq5yh0snDT6/HPE-Search-Component?node-id=0%3A1

**Comment by ericsoderberghp** [comment]
Looks good to me!
