### ISSUE TITLE
Disabled color - disabled TextInput with a set value 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1409]
Ensuring a TextInput that has been disabled and has a set value, that the value text color still passes accessibility.
https://v2.grommet.io/textinput?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAbQDd1cR8AaRO-KAGrtOAXUQBeRACV86aADoQfAMpR0UIgHJMAT0RsO+TcQDcVRACd+IC0kLnqAHgAq+VFACSYbCCgPqiAAmMHToAEYEgf7UBpziZLH4AL7RiAgAwgAW6GAA5vjx+Cz4YIziAHy8-EKGhEUlUPJqFvmNicQpAYgA9OXmphRJQA 
For reference: https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=2006%3A393

**Comment by rajasekar-ramasamy** [comment]
@MikeWalrath @ericsoderberghp I have created a contrast ratio comparison for a disabled text that passes accessibility **user Input and graphical (WCAG AA: 3:1)** https://www.figma.com/file/fO285pXUqN9pVZ0xpRoKjL/HPE-Masked-Input-Component?node-id=1%3A93

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp I have added disabled text for the dark theme as well
https://www.figma.com/file/fO285pXUqN9pVZ0xpRoKjL/HPE-Masked-Input-Component?node-id=702%3A1382
please do share your feedback

**Comment by ericsoderberghp** [comment]
dropped some comments in Figma.

**Comment by ericsoderberghp** [comment]
Here are some discrepancies with the current grommet + theme: https://designer.grommet.io/?id=TextInput-eric-soderberg-hpe-com
Note that the FormField being disabled still leaves the value full strength. The disabled TextInput feels too hard to read, even though it is disabled.

**Comment by ericsoderberghp** [comment]
After some discussion, we've decided to leave `text-weak` as is and instead add `readonly` capabilities to input components. This effort is being tracked by: https://github.com/grommet/hpe-design-system/issues/1419
