### ISSUE TITLE
GreenLake NFR review

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1418]
Review the GreenLake Non Functional Requirements, https://hpe.sharepoint.com/:w:/t/hpe-design/EQ-224Tnam5FsHMwHb701VgBEKoXyVZk_QgtJmrBgn5mfw?e=5epbGr

Determine if there is anything in there that we should consider adding to the design system site. Create issues as needed.

**Comment by MikeWalrath** [comment]
The review I would consider complete. https://wiki.hpelabs.net/display/HCSS/1+Component+Comparison+Table

Next steps are to prioritize and create backlog items.

**Comment by MikeWalrath** [comment]
Review is complete. Will follow up with additional PRs/issues to ensure the issues are addressed.
