### ISSUE TITLE
Wizard example on design-system.hpe.design does not provide complete default form values

### ISSUE THREAD

**Issue by canyongrace** [grommet/hpe-design-system#1424]
### Is this issue related to the design system core library or design system website?

design-system-website

### Expected Behavior

My understanding is that all form values should have default values provided. If not, it can lead to browser warnings in development mode. (_Warning: A component is changing an uncontrolled input of type email to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components_)

### Actual Behavior

However the first wizard example here https://design-system.hpe.design/templates/wizard seems to be leaving out a couple, specifically firstname-validation and lastname-validation

### URL, screen shot, or CodeSandbox exhibiting the issue

https://design-system.hpe.design/templates/wizard

### Steps to Reproduce

Code examination

### Your Environment

- Design System version: Current web version
- Grommet version: Current version on site
- Browser Name and version: Firefox 85
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by halocline** [comment]
Also, when doing this work, add WizardContext.js file to the Wizard showCode examples.
