### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by rajasekar-ramasamy** [grommet/hpe-design-system#1427]
GLC team is looking for guidelines for vertical tabs,

**Comment by MikeWalrath** [comment]
@rajasekar-ramasamy could you add a bit more context in the description/title? We have guidelines on Tabs so Im wondering what the specific questions are? What might be missing from the existing guidance? The use case? Or if they have any screens for a proposal of what they would like to enhance?

**Comment by rajasekar-ramasamy** [comment]
@MikeWalrath @ericsoderberghp 
GLC team had requested Vertical tabs to divide and categorize dynamic content on pages with a large number of categories.
https://www.figma.com/file/MbIb9zusFPdHXwnNyvYk94/MLOps_Sites_Kubeflow?node-id=14%3A1738

**Comment by taysea** [comment]
Closing, we have decided not to move forward with vertical tabs: https://design-system.hpe.design/components/tabs?q=vertical%20tab#avoid-vertical-tabs
