### ISSUE TITLE
Wizard - Adding example of a a post submit "step" within Wizard 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1435]
A way to guide the user to some possible next steps. It would be optional, but would offer more guidance, assuming the user is in some larger sequence of tasks where the wizard is just one step of a larger process.
Use case/example: https://www.figma.com/file/KGfphc2fWsEF8GpRC9vKbS/CCS-v0.1?node-id=17467%3A136683

**Comment by ericsoderberghp** [comment]
Haven't been hearing requests along these lines since back when this was submitted.
