### ISSUE TITLE
Update Slack icon in the Figma icon library 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1448]
It looks like we have a discrepancy between the slack icon in Figma and what is in the Grommet icon library. 
https://www.figma.com/file/eJgKLe7Y5Vt7O8O3EsYDhf/hpe-icons-drafts?node-id=9%3A526 
https://github.com/grommet/grommet-icons/blob/master/public/img/slack.svg

**Comment by Keeth-HPe** [comment]
I have updated the slack icon in the Figma Icon Library
