### ISSUE TITLE
Table - Interactive Table Rows on Figma misaligned with Design System site

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1451]
There are some misalignments in Figma with the Design System site. It will be worth discussing with one of the developers to talk through it again. However, my hinge is that the one on the site is correct.

Right now, rows with checkboxes and interactive elements are receiving a background color on the entire row when hovering over them (in Figma). However, on the Design System site, only the interactive elements are receiving a background color. The question is whether or not the entire row still receives a hover background color. But as stated above, my hinge is that it doesn't as the entire row isn't clickable if there are 2 ore more interactive elements within.

**Figma:**
![Screen Shot 2021-03-01 at 8 41 06 AM](https://user-images.githubusercontent.com/62117454/109528890-ff669600-7a69-11eb-96d0-dcc05711ab36.png)

**Design System Site:**
![Screen Shot 2021-03-01 at 8 41 17 AM](https://user-images.githubusercontent.com/62117454/109528877-fd043c00-7a69-11eb-9ef6-afbcc4849903.png)

**Comment by ericsoderberghp** [comment]
> But as stated above, my hinge is that it doesn't as the entire row isn't clickable if there are 2 ore more interactive elements within.

agreed

**Comment by ericsoderberghp** [comment]
DataTable with `onClickRow="select"` will provide the designed behavior. However, we also have the ability to have interactive elements within the table cells, in which case the interaction is at the cell level and not the row level, for accessibility. Are not thinking we need examples of all variations at the moment.
