### ISSUE TITLE
Multi-select Component Usability Testing

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1452]
Currently working with Abby on creating a multi-select component as there is a need in GLC. 

Some users will be testing the designs Raja created: https://www.figma.com/proto/dMqsrFWxJW58EYBEAubyEq/Multiselect-Input?node-id=526%3A2019&viewport=1321%2C-1094%2C0.5&scaling=min-zoom

and others the one Abby created: https://www.figma.com/file/grzcCVl5TZILb0hik5sEm6/?node-id=464%3A0

Here are the recordings of the UT.https://wiki.hpelabs.net/display/HCSS/US19568%3A+Forms+Usability+Testing

**Comment by ericsoderberghp** [comment]
I think we've already got a Select component that supports selecting multiple options: https://storybook.grommet.io/?path=/story/input-select-search--search
Is this issue then to update it in some way?

**Comment by vavalos5** [comment]
Great question! I believe in the past, Greg has shown this example from Grommet to GLC multiple times. However, it seems like they want to be able to allow users to quickly see what choices they've selected along with implementing checkboxes in the drop. In general, she also wanted to test what the best way to design multi-select with search baked in.

**Comment by vavalos5** [comment]
Abby has conducted the UT and they can be found here: https://www.figma.com/file/grzcCVl5TZILb0hik5sEm6/Forms-Usability-Test?node-id=301%3A1462

After the share out, Eric had stated that he likes concept 1 the best as it is more aligned with the Design System. We will be doing some refinements and will be implemented into ticket #1454
