### ISSUE TITLE
Double focus on select on Design System Site

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1453]
<img width="281" alt="Screen Shot 2021-03-03 at 8 49 09 AM" src="https://user-images.githubusercontent.com/62117454/109841118-9748b900-7bfd-11eb-8f58-1233f4c8d290.png">
There seems to be a double focus when selecting an item from the list on select. See screen shot above

**Comment by ericsoderberghp** [comment]
Could be related to https://github.com/grommet/grommet-theme-hpe/issues/171

**Comment by taysea** [comment]
This issue must be due to something on grommet stable (when I revert to 2.16.3, I don't see the error) -- going to look for the commit that may have caused it.

The same behavior seen here is also occurring on Grommet Storybook
