### ISSUE TITLE
CheckBoxGroup with embedded search

### ISSUE THREAD

**Issue by abbyperez** [grommet/hpe-design-system#1454]
In GLC, there's a need to have a search embedded in CheckBoxGroups. Generally, the list of options are long and the list of items are longer and more complex. 

### Is this issue related to the design system core library or design system website?

design-system-website

### Expected Behavior

Be able to see guidance on having search embedded in CheckBoxGroups

### Actual Behavior

No guidance or examples on Design System

### URL, screen shot, or CodeSandbox exhibiting the issue

https://design-system.hpe.design/components/checkboxgroup
<img width="389" alt="Screen Shot 2021-03-03 at 9 55 58 AM" src="https://user-images.githubusercontent.com/74273299/109841800-a8e28e80-7c06-11eb-84c8-a4a80510b7c0.png">
<img width="403" alt="Screen Shot 2021-03-03 at 9 56 13 AM" src="https://user-images.githubusercontent.com/74273299/109841831-b0a23300-7c06-11eb-881d-19e4e7324f3e.png">
<img width="365" alt="Screen Shot 2021-03-03 at 9 56 21 AM" src="https://user-images.githubusercontent.com/74273299/109841849-b5ff7d80-7c06-11eb-87da-b2dd97235ac3.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version: whatever is live on Design System website
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by vavalos5** [comment]
This ticket is relevant to #1452

**Comment by ericsoderberghp** [comment]
This needs changes in grommet to build the search into CheckBoxGroup, similar to how search is built into Select.

**Comment by vavalos5** [comment]
Designs could be found here: https://www.figma.com/file/grzcCVl5TZILb0hik5sEm6/Forms-Usability-Test?node-id=0%3A1

After Abby's share out, we've concluded:

1. To keep concept 1 as is but to change the terminology such as "view selected" to "view only selected" as an example (unsure if this is the right terminology just yet.

2. Refine concept 2 to be simplified by getting rid of the select box like this example:
![Unknown](https://user-images.githubusercontent.com/62117454/110539077-a639da80-80d9-11eb-912a-62e590e739ae.png)

However, still debating whether the "view selection" and clear selection would live inside of the label container or outside
![Uploading Screen Shot 2021-03-09 at 9.59.09 AM.png…]()

We would also include the total number of items below the search box to let users know how many items live inside of the container

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp @vavalos5 @MikeWalrath  Here's the link on design iteration for the group CheckBox https://www.figma.com/proto/zkQOQRUt8frxiSo67kTkfE/HPE-Checkbox-Group-Component?node-id=931%3A3&viewport=391%2C-227%2C0.125&scaling=min-zoom&page-id=868%3A2549
Feedback are welcome

**Comment by vavalos5** [comment]
@ericsoderberghp Are we still working on this? I thought we were implementing into Grommet already?

**Comment by vavalos5** [comment]
Chatted with Eric and this is good to close. we've concluded on concept 1 is the direction we're going with. @rajasekar-ramasamy no need to do further exploration.

Figma file: https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=0%3A1
