### ISSUE TITLE
Adding FileInput component to Figma 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1461]
Adding a component in Figma for FileInput

**Comment by ShimiSun** [comment]
Here are some exploration findings for FileInput from when we worked on it on Grommet:
https://d74g4.csb.app/
https://codesandbox.io/s/d74g4 (Including the code)

Also, here are some designs from CCS:
![image](https://user-images.githubusercontent.com/6320236/109857848-59a55980-7c18-11eb-97e2-1665ec3c9ec7.png)

**Comment by vavalos5** [comment]
Figma file: https://www.figma.com/file/8HwAiiSDloOTjUxqvCTypq/Untitled?node-id=1%3A11

**Comment by ericsoderberghp** [comment]
Great start! A couple of comments:
- I think we should cover two cases:
1) the file is being selected but will not be uploaded to the server until the user clicks the Submit button on a form.
2) the file will be uploaded as soon as it is dropped or browse + selected.
- I think we should mention the possible variety of drop zone regions. For example, you could have it be the entire page or just a small area. For example, Slack accepts dropping files anywhere on the page but doesn't show this as a drop zone until the user actually drags a file over it, SmugMug shows a large drop zone when uploading photos, etc.

**Comment by vavalos5** [comment]
Figma file is ready for review. I have questions on a sticky note in the Figma file 😄 

https://www.figma.com/file/8HwAiiSDloOTjUxqvCTypq/Untitled?node-id=1%3A11

**Comment by ShimiSun** [comment]
Should we also create an issue to exemplify FileInput on the DS site?

**Comment by vavalos5** [comment]
I think that is the plan. We create a ticket for exploration first (design), then after exploration is done, we create one for ideation (design) and then after that is done we create and implementation one for the DS site

**Comment by vavalos5** [comment]
Research for this ticket has been conducted and good to close. Ready to move into ideation
