### ISSUE TITLE
TextArea Figma Component default height differs from the React Component

### ISSUE THREAD

**Issue by L0ZZI** [grommet/hpe-design-system#1473]
Figma TextArea Component defaults to 3 lines of text to set its default height, while the Design System site and the theme only uses 2 lines.

### Is this issue related to the design system core library or design system website?

Both potentially.

### Expected Behavior

TextArea just needs to be aligned on the code

### Actual Behavior

UI Dev can't align with Design's mock

### URL, screen shot, or CodeSandbox exhibiting the issue

Figma TextArea Component defaults to 3 lines of text to set its default height:
https://www.figma.com/file/evH1LQewFPc8Y2fteywMxM/HPE-Text-Area-Component?node-id=206%3A75
![Screen Shot 2021-03-05 at 11 27 43 AM](https://user-images.githubusercontent.com/1753301/110164241-f1847e00-7da5-11eb-9aa6-81bcc89d6d19.png)

The Design System site and the theme only uses 2 lines: 
https://design-system.hpe.design/components/textarea
![Screen Shot 2021-03-05 at 11 30 02 AM](https://user-images.githubusercontent.com/1753301/110164379-242e7680-7da6-11eb-911a-770be3e21665.png)

### Steps to Reproduce

NA

### Your Environment

NA

- Design System version: latest
- Grommet version: latest
- Browser Name and version: all
- Operating System and version (desktop or mobile): all

**Comment by vavalos5** [comment]
Figma file can be found here: https://www.figma.com/file/evH1LQewFPc8Y2fteywMxM/HPE-Text-Area-Component?node-id=0%3A1

TextArea examples in Figma are now aligned with the DS site. They now show 2 lines of text by default
