### ISSUE TITLE
CTO Innovation Hub Design 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1488]
Initial design effort based on the below white board for the CTO Innovation hub. 
https://miro.com/app/board/o9J_lVhj5v0=/

**Comment by vavalos5** [comment]
Awaiting last bits of imagery from Carole + video (which will take some time but placeholders are in file) 

https://www.figma.com/file/ufZXRYl4hFDiAQ0VEncUoX/CTO-Innovation-Hub?node-id=23%3A2

**Comment by vavalos5** [comment]
This is probably good to close. I sent Shimi the assets for her to get started on the development side.
