### ISSUE TITLE
Add guidance on how to label optional and required fields

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1502]
I find other designers aren't sure when to use an asterik to show required fields and whether they should use it on each label.

I found an article that states that the main reason for marking optional fields and not required fields is that most of your fields should be mandatory. Therefore, it makes sense only to mark those in the minority.

I think we need to do some research and define this in the Design System

**Comment by ericsoderberghp** [comment]
Additional guidance on this has been added under https://design-system.hpe.design/templates/forms?q=form#required-vs-optional-fields.
