### ISSUE TITLE
FileInput Component in Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1505]
Continue ideating on how FileInput would look like on a form, modal, etc.. with annotations and descriptions on how to use in designs

**Comment by vavalos5** [comment]
Ready for review: https://www.figma.com/file/8HwAiiSDloOTjUxqvCTypq/FileInput-Component?node-id=154%3A2511

**Comment by ericsoderberghp** [comment]
Unfortunately, Figma keeps crashing in my browser when I try to switch the file into comment mode :(

**Comment by vavalos5** [comment]
<img width="755" alt="Screen Shot 2021-04-14 at 11 03 20 AM" src="https://user-images.githubusercontent.com/62117454/114758760-30e1ab00-9d12-11eb-830e-bbc95366e324.png">
<img width="609" alt="Screen Shot 2021-04-14 at 11 13 26 AM" src="https://user-images.githubusercontent.com/62117454/114758988-78683700-9d12-11eb-822f-e82d6e7b3cf4.png">
<img width="755" alt="Screen Shot 2021-04-14 at 11 13 14 AM" src="https://user-images.githubusercontent.com/62117454/114758998-7bfbbe00-9d12-11eb-87b0-399097a5e00f.png">
<img width="775" alt="Screen Shot 2021-04-14 at 11 12 53 AM" src="https://user-images.githubusercontent.com/62117454/114759029-85852600-9d12-11eb-9bb7-d698843f69c5.png">
<img width="807" alt="Screen Shot 2021-04-14 at 11 12 39 AM" src="https://user-images.githubusercontent.com/62117454/114759059-8ddd6100-9d12-11eb-9467-71ffd7245943.png">
<img width="673" alt="Screen Shot 2021-04-14 at 11 12 24 AM" src="https://user-images.githubusercontent.com/62117454/114759070-9170e800-9d12-11eb-991b-38b076d04844.png">

**Comment by ericsoderberghp** [comment]
Comments labeled by Figma #:
71 - If you accidentally clicked on the wrong file, then you want to replace the file you selected with a different one. It's a bit heavier to have to remove the one you selected in order to get an empty box to select the other one. And, since we need the select control to be there in the multiple file case, why not make it easier? It also aligns with the browser native input element, which only allows replacing via re-selecting and doesn't have any remove mechanism.

**Comment by ericsoderberghp** [comment]
72 - "Select More Files" indicates that you want to select more files than the ones you've already selected. Is there another suggestion for this labelling? Perhaps Select Additional Files", which is a bit heavier.

**Comment by ericsoderberghp** [comment]
70 - I think keeping the control Button aligned to the right is consistent with other controls, like a remove icon button. Perhaps we should remove "or" so it just reads "Drag and drop" on the left and "Select File" on the right?

**Comment by ericsoderberghp** [comment]
73 - The example here https://design-system.hpe.design/templates/forms#settings uses "Description"

**Comment by ericsoderberghp** [comment]
74 - FileInput lives inside a FormField in the code. Perhaps Figma merges them? For instance, does a text form field have both a FormField and a TextInput in Figma?

**Comment by ericsoderberghp** [comment]
76 - I was assuming that once you had interacted with the element, you knew how it worked and didn't need the guidance anymore.

**Comment by vavalos5** [comment]
Thanks Eric, i'll respond to the comments. But I think this ticket good to close? Unless there were any other changes to make to FileInput
