### ISSUE TITLE
Multi-line support for TextInput description

### ISSUE THREAD

**Issue by derekhchen** [grommet/hpe-design-system#1508]
### Is this issue related to the design system core library or design system website?

Figma TextInput component does not support multi-line descriptions. According to Vicky, there is no auto-layout set on that component and the description aligns to middle.

### URL, screen shot, or CodeSandbox exhibiting the issue
![image](https://user-images.githubusercontent.com/38574571/112690285-c2a77800-8e38-11eb-8f6d-e51ac096de10.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by vavalos5** [comment]
I recreated TextInput to have auto layout with responsive text that wraps if there is more than 1 string of text.

Figma file: https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=0%3A1
