### ISSUE TITLE
Add Guidance on how to use an action button with an outline

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1513]
Currently on the Design System site, we show an example of an actions button and a filter button with an outline. However, we don't offer this in the design system. We need to come to a conclusion + discussion of when the outline should be used. Here is an example of how it looks like on the Design System

<img width="1028" alt="Screen Shot 2021-03-30 at 9 58 32 AM" src="https://user-images.githubusercontent.com/62117454/113028166-cfc9ad00-913f-11eb-992c-e5d17ad897b2.png">

and how it looks like in Figma:
<img width="612" alt="Screen Shot 2021-03-30 at 10 04 22 AM" src="https://user-images.githubusercontent.com/62117454/113028141-c93b3580-913f-11eb-8b88-9b64c75613a3.png">

Also, do we want to include this button in the Design System as a tertiary button with it's different behaviors?

**Comment by ericsoderberghp** [comment]
I believe this is a Menu component, as opposed to a Button component.

**Comment by taysea** [comment]
There are some Figma designs, such as Filtering button, that has the thin border. To do so, we have been doing a custom `styled-component`. Agreed we should decide _if_ and _when_ this button style should be used. Then, if we want to add it to the grommet-theme-hpe as a button kind we can OR at the very least create a demo of how to implement properly as a styled component.

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/hpe-design-system/issues/1701
