### ISSUE TITLE
Clean up Figma Color page to align with the site 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1530]
zfigma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=0%3A1
There is currently some confusing language within the color page. Specifically "Secondary." It would be nice to clean it up and align with the site. 
![image](https://user-images.githubusercontent.com/17712467/113327565-5b764180-92d8-11eb-9075-0d6c5b15b198.png)

**Comment by vavalos5** [comment]
I've made the changes above to better align with the site.

Figma file: https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=0%3A1

One thing I noticed is that on the DS site, we have 2 colors named "green"
<img width="1088" alt="Screen Shot 2021-04-13 at 11 21 03 AM" src="https://user-images.githubusercontent.com/62117454/114601509-6cb13d80-9c4a-11eb-836a-028aca3fe332.png">

Our brand color is named "green" and our light palette green color is called "green". However, in Figma, we have it as "light Green. Though on the DS site, the "light green color" is under "Light Palette", I think we should call all of the colors "light (color)" do differentiate that from our brand color.

<img width="344" alt="Screen Shot 2021-04-13 at 11 23 00 AM" src="https://user-images.githubusercontent.com/62117454/114601801-c7e33000-9c4a-11eb-8a57-6d8eb0c2942e.png">

**Comment by ericsoderberghp** [comment]
The color names on the design system site refer to the names in the HPE theme. There are no colors named "light ..." in the theme. So, the way the design system site labels the colors is accurate in that sense. Would it make sense to re-label the Figma colors to something like "green - light"?

**Comment by vavalos5** [comment]
Done :)

**Comment by vavalos5** [comment]
Changed brand color from "green" to "brand". Aligned this with Mike and Matt. Matt has also changed this in the back end. All colors are now aligned to the Design System site.
