### ISSUE TITLE
Add example and guidance for a max width header 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1531]
What is the ideal max width for a header and can we please add guidance and an example for the header component page?

**Comment by vavalos5** [comment]
Are these tickets relatable? #1475

**Comment by MikeWalrath** [comment]
Potentially. This issue is specifically for the header. Is our guidance to extend the header to meet the size of the screen or to stop at a specific point. Ill also reach out to Chris if its been established for CCS. 
![image](https://user-images.githubusercontent.com/17712467/113415049-9c736200-937b-11eb-9ba1-9033fdb1461f.png)
![image](https://user-images.githubusercontent.com/17712467/113415073-a8f7ba80-937b-11eb-961f-d40356d41f30.png)

**Comment by ericsoderberghp** [comment]
Let's include this one as part of the "Page Layouts" topic.

**Comment by ericsoderberghp** [comment]
Related to #1622

**Comment by ericsoderberghp** [comment]
will be covered by subsequent page layouts work
