### ISSUE TITLE
Verification modal example 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1542]
Adding an example of a verification modal. "Are you sure you want to delete?" 
https://designer.grommet.io/starter-dialogs?name=GLC%20Starter%20Pages
![image](https://user-images.githubusercontent.com/17712467/113788652-b3f37780-96fa-11eb-923f-abe684ea827c.png)

**Comment by vavalos5** [comment]
ticket #1514 ?
