### ISSUE TITLE
design thinking to revamp getting developers started

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1546]
Conduct a design thinking exercise, perhaps just a couple of days, to consider how we might revamp our guidance for developers to get started with the design system. Build upon recent interactions to create something practically useful, which the current approach doesn't seem to addressing. Consider bringing in a couple of developers outside the design system team who have recently started using the design system.

## Deliverables

Add issues as appropriate corresponding to the recommendations.

**Comment by halocline** [comment]
[Design sprint Mural board](https://app.mural.co/t/hpecdoresearchteam7715/m/hpecdoresearchteam7715/1618340338438/68f8c2ff1c30441fe912942097e2facf89abf653)

Next steps:
- [ ] place top solutions along level of effort axis
- [ ] create issues for each with recommendations for relative prioritization and timing
