### ISSUE TITLE
Iterate on Pagination Guidance 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1547]
Received the below feedback on the Pagination guidance. It would be good to expand the guidance for the different data sizes. 
![image](https://user-images.githubusercontent.com/17712467/114626948-a8abc900-9c71-11eb-95c7-b66016e580ea.png)

**Comment by taysea** [comment]
Closed by https://github.com/grommet/hpe-design-system/issues/3439
