### ISSUE TITLE
Add example of Table + ToolTip within Figma 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1551]
With the many ways ToolTip will be used it would be nice to add an example of how/when to use it within a Table. 
https://www.figma.com/file/Jd34cI5yyZIPb5BIwkIPU2/HPE-Tooltip

**Comment by vavalos5** [comment]
Would also good to know where the tooltip would show after hovering over truncated text. I saw in the Drop Figma file it can be determined through the drop, but it would be good to include in the Tooltip Figma file somewhere. I also noticed there were examples of a tooltip with interactive elements within the tooltip. However, on the design system site, we show guidance to avoid this. I realize that might be another ticket itself....

https://www.figma.com/file/0zhBD70lp2O8D7bAgLaM5T/HPE-Drop-Component?node-id=0%3A1

**Comment by vavalos5** [comment]
We have an example of a Tooltip being used in the Table Figma file found here: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A12752

I also included the examples to the Tooltip Figma file with text to direct users to the Table Figma file for more guidance

https://www.figma.com/file/Jd34cI5yyZIPb5BIwkIPU2/HPE-Tooltip?node-id=0%3A1
