### ISSUE TITLE
Guidance for localization/internationalization patterns

### ISSUE THREAD

**Issue by danielm-hpe** [grommet/hpe-design-system#1555]
### Is this issue related to the design system core library or design system website?

design-system-core

### Expected Behavior

Applications frequently have a requirement to be localized to many different languages.  This is usually achieved by creating a bundle of messages in each locale, and loading the correct locale's bundle at run/render time.

For user interfaces specifically the challenges usually revolve around binding dynamic values into localized text, and situations where markup and localized text needs to be mixed.

I've included a screenshot and snippet of some common cases of text that may need to be localized (the scenarios can be combined, such as dynamic values + markup in the same string).

### Actual Behavior

Since markup in react is achieved via components, it's not clear what a good strategy would be for i18n/l10n.  Can you provide guidance on recommended patterns for implementing i18n/l10n using grommet/design system?

### URL, screen shot, or CodeSandbox exhibiting the issue

```jsx
<Box direction="column">
  <Text>{5} of {10} items</Text>
  <Text>
    mixing <Text weight="bold">markup</Text> with text
  </Text>
  <Text>{/* date time formatting */}    
    {'04/15/2021 12:45 PM CST'}
  </Text>
</Box>
```

![image](https://user-images.githubusercontent.com/82606244/114919959-88eddf80-9dee-11eb-9209-fac1423798ed.png)

**Comment by MikeKingdom** [comment]
One option is react-intl. It's what GreenLake is using and they make a simple hook to access the messages from locale-specific objects containing key:message pairs.

**Comment by danielm-hpe** [comment]
Reading through the docs for react-intl, it looks like it would work for all of the cases mentioned:
https://formatjs.io/docs/react-intl/components#rich-text-formatting

I would probably be good still to have a blurb about i18n / l10n on the design system site and provide a reference to a recommended system / pattern (and ideally some examples), even if it's just mentioning react-intl as an option.

**Comment by ShimiSun** [comment]
Here is a summary and comparison we have done between different intl packages https://github.com/grommet/grommet-i18n
