### ISSUE TITLE
Developer Guidance - Create a step-by-step tutorial setting up HPE app from scratch

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1558]
Outcome of https://github.com/grommet/hpe-design-system/issues/1546

Create a step-by-step app set up to use as introduction to how Grommet, theme, and Design System work together. Use the tutorial to introduce fundamentals and best practices.

- Should explain how Grommet + HPE Theme work together and their roles
- Should introduce concepts such as t-shirt sizes
- Should touch on concepts such as:
  - Semantic headings
  - A11yTitles / aria-labels
  - Wave Accessibility tests
- Should ... lots of other opportunities
- Should show how to integrate global header footer?

This should probably be broken down into sub tasks for:
- [ ] Create an outline / script the tutorial should follow
- [ ] Ideate on visual presentation and format
- [ ] Set up a repository in which the tutorial app can live (?) -- might be nice to have branches for each step of the tutorial
- [ ] Other tasks ...

**Comment by halocline** [comment]
Idea: Structure similarly to a Lego instruction booklet

At the beginning of each step:
- Provides an image of the end state of what is being built.
  - This is our Figma design file. It is the reference for what is to be built.
- Lego lists the type and quantity for each brick used.
  - This could be a list of each component used, complete with cross references to their definitions, and a copy paste import statement.

Lego then details how those bricks are assembled:
- Lego breaks the assembly into substeps.
  - Detail how the components are composed at each substep.

**Comment by taysea** [comment]
One main question here is how high/low fidelity do we want the final product to be? 

Seems like having something a bit more fleshed out than the grommet starter would be nice. Particularly for areas that are intended to be pretty layout opinionated (like Global Header)

**Comment by halocline** [comment]
> One main question here is how high/low fidelity do we want the final product to be?
> 
> Seems like having something a bit more fleshed out than the grommet starter would be nice. Particularly for areas that are intended to be pretty layout opinionated (like Global Header)

Perhaps we can gradually phase in that fidelity as the tutorial progresses? We start with something like an AppContainer which is largely a blank canvas, maybe it has some boxes blocking out content sections for placeholder. Then, the end goal for each subsequent "step" is to add a finished, high-fidelity element. After that step, the rest of the app might be blank or low-fi, but that particular element is quite fleshed out.

Referring back to the Lego analogy, let's say the set we are building is a mechanic's garage. The garage might consist of a garage, a tool chest, a car, a retail/waiting area with counter and cash register, etc. Each one of those elements is a distinct "step" and at the end of it you have a finished element which may be placed into the larger context right away, or set aside to be placed at a later time.

If we treat each "step" as a "chapter" in the tutorial, we could even build and publish the tutorial one chapter at a time. Rather than waiting for a finished tutorial, we could aim to complete a chapter (or two, three) each sprint. Folks could follow along as we go even and provide feedback along the way.

Just dumping a few ideas as they come....

**Comment by halocline** [comment]
- [ ] Where will it live?
  - Part of the mono-repo?
  - TypeScript?
  - Linters
- [ ] Chapter elements
  - [ ] Objective (e.g. end state)
    - What are we trying to accomplish? (picture of the design -- what is it that we are building)
    - What considerations? What tools? (elaborate on decision making --> what tools to consider / "Lego bricks we are using"?)
  - [ ] Steps

- [ ] Potential chapters
  - [ ] Create react app
  - [ ] Install Grommet + HPE Theme (and explain their roles -- e.g. Grommet = components + theme = styling --> commentary about "Spidy sense" --> if you are adding your own styling, that should be a warning that something is wrong)
  - [ ] Starter on Box (built on flex-box --> direction, gap, pad (I'll take care of myself) vs. margin (obey my rules) --> composability ... )
  - [ ] AppLayout and scaffold (Header, Main, Footer)
    - [ ] Navigation
       - [ ] AppNav vs. GlobalNav + Routing
       - [ ] Hub & Spoke
  - [ ] PageLayout / ContentLayout (Column / Grid, semantic headings, primary vs. secondary content)
     - [ ] Layout to look nice across a variety of screens (ResponsiveContext)
     - [ ] Content (Button vs. Anchor, aria-labels, accessibility scan (Wave))
     - [ ] Main + Aside, Primary/Secondary, Side-panels, Modals,
  - [ ] Populate content
     - [ ] Start with a "use case" then pick the proper tool for the job.
       - [ ] Async fetching, loading, skeleton, success vs. error, ...
       - [ ] State management
       - [ ] List / table of XYZ
         - [ ] Prioritizing content responsively (e.g. table columns)
       - [ ] Cards
       - [ ] Implementing workflows (confirmation dialogs, wizard steps) -- how to facilitate? When to use each?
       - [ ] Forms

**Comment by halocline** [comment]
Sprint objectives (w/o May 17)
- [ ] Sample app - recommendation for where the app tutorial will live + branches/tags as markers for tutorial chapters
- [ ] Share out on chapter per sprint approach
- [ ] Share out on what each chapter should contain (objective/story + considerations (elaborate on thinking) + tools we will use + steps + summary conclusion of chapter)
- [ ] Chapter - Initial app setup
- [ ] Chapter - AppLayout (Header, Main, Footer)

**Comment by taysea** [comment]
Closing now since we have filed follow-on tickets with feedback. We can reference the checklist in this ticket for future sprints though.
