### ISSUE TITLE
Developer Guidance - Patterns/Best Practices & Anti-Patterns (high impact, high effort)

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1560]
Outcome from https://github.com/grommet/hpe-design-system/issues/1546

Provide patterns & anti-patterns. Initial steps might be:
- [ ] Create recommended scope -- how narrow or wide do we want to go? Should we focus on certain areas first?
- [ ] Identify the topic areas which are most in need of pattern guidance.
- [ ] How might these patterns be communicated?
- [ ] Create recommendation
- [ ] Create subsequent issues for next steps

**Comment by taysea** [comment]
Closing, stale.
