### ISSUE TITLE
Developer Guidance - Create-React-App template for HPE App, proposal called for Next and Gatsby implementations as well (mid impact, higher effort ==> probably a "forget it for now")

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1561]
Outcome from https://github.com/grommet/hpe-design-system/issues/1546

Create-React-App template for HPE App, proposal called for Next and Gatsby implementations as well (mid impact, higher effort ==> probably a "forget it for now")

Mid impact + High effort ==> may want to categorize as "we're not going to prioritize this any time soon, so we may want to go ahead and close this so as not to add to our clutter."

**Comment by taysea** [comment]
Closing, stale.
