### ISSUE TITLE
Developer Guidance - Provide written guidance on ResponsiveContext, t-shirt sizing -- expose pixel values of t-shirt sizes for clarity / familiarity (mid impact, lower effort)

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1562]
Outcome from https://github.com/grommet/hpe-design-system/issues/1546

Provide written guidance on ResponsiveContext, t-shirt sizing -- expose pixel values of t-shirt sizes for clarity / familiarity (mid impact, lower effort)

This should probably be broken down into sub tasks for:
- [x] Are there any other fundamentals which should also receive attention?
- [x] Create issues for each subject area (e.g. ResponsiveContext, T-shirt sizes, Semantic headings, ...)

Created and or updated the following: https://github.com/grommet/hpe-design-system/issues/1671, https://github.com/grommet/hpe-design-system/issues/1670, https://github.com/grommet/hpe-design-system/issues/1235

**Comment by ericsoderberghp** [comment]
Related to #1379

**Comment by halocline** [comment]
Have broken out into sub issues
