### ISSUE TITLE
Ordering of Items Behaviors

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1576]
Ideate on what the mouse and keyboard interactions will look like + behaviors

**Comment by vavalos5** [comment]
https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=453%3A0

**Comment by vavalos5** [comment]
Created 3 similar but different options to show drop. Those could be found here: https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=493%3A16973

**Comment by ericsoderberghp** [comment]
I think at this point we should transition to seeing what is easy to do on the implementation side to help choose between the various style options. I have a feeling that there will be some implementation constraints in this area.

**Comment by vavalos5** [comment]
@britt6612 @taysea As discussed on Friday, is option 4 the easiest to implement? It's also the simplest.

**Comment by vavalos5** [comment]
@ericsoderberghp Forgot to mention that there was one other option added that Taylor, Brittany and I worked on. Please take a look at option 4. https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=493%3A16973

**Comment by vavalos5** [comment]
I think this may be ok to close? Only thing that needs to be updated in designs is the background color on the drag and drop
