### ISSUE TITLE
Document and share experience consuming Design System development resources

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1582]
Document and share out:

- Experience
- Points of friction
- Opportunities
- Recommendations

**Comment by halocline** [comment]
Value chain/hierarchy concept:

Elements <----- component library ------ branded and themed components ------- examples w/ code ------- rich component (examples) ------ rich component (supported) -----> Application

**Comment by taysea** [comment]
Understanding which props are critical (such as accessibility related ones like htmlFor, id, name), ensuring designs use proper semantic headings vs text (or that we have more guidance around this for developers), simplifying wizard to be more componentized -- feels like there's ways for things to get lost as teams take and implement on their own
