### ISSUE TITLE
Create the process to refresh Principles and Values

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1593]
This issue covers the pre-work for some collaborative time to refresh the Principles and Values of the design system.

## deliverables

- [ ] schedule one or more meetings
- [ ] create agendas for them
- [ ] prepare any resources needed

**Comment by ericsoderberghp** [comment]
pre-work for https://github.com/grommet/hpe-design-system/issues/1331

**Comment by taysea** [comment]
Closing in favor of #4004
