### ISSUE TITLE
“Download CSV” action is important not a primary action

### ISSUE THREAD

**Issue by rajasekar-ramasamy** [grommet/hpe-design-system#1594]
Download CSV as button needs to be changed to secondary action 

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=1%3A2

**Comment by vavalos5** [comment]
Table Figma file has been updated to have "Download CSV" button from primary to secondar.

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=1%3A2
