### ISSUE TITLE
Skeleton - Implement first pass of site page

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1600]
[Current Guidance
](https://www.figma.com/file/dQG3xZ6m4AUt7Lwrdp1gVB/Skeleton-Guidance?node-id=216%3A1663&t=m7Kpg99SjOyveF02-1) Related Ticket #3088 

## Deliverables

- [x] Add to grommet-site
- [ ] Create a first pass of the Skeleton page on the DS site. Sections to include:
     - [ ] Main example
     - [ ] When to use/when not to use
     - [ ] Anatomy

**Comment by ericsoderberghp** [comment]
I have been wondering whether we should
- add a Skeleton component to grommet
- add a skeleton prop to various components, such as <Text skeleton />
- add a skeleton prop to Box and Grid and then internally use a SkeletonContext that all descendent components would use to render a skeleton version of itself
- just add a few examples to the design system site for reference

**Comment by britt6612** [comment]
Update 1/6
Kenny and I chatted 1/5 about the remaining things that needed to be added for the diagram and examples.

I started the page as a draft PR which is just the skeleton of the page until we flesh out the content.

**Comment by KennyAtHPE** [comment]
[WIP V3 of guidance](https://www.figma.com/file/dQG3xZ6m4AUt7Lwrdp1gVB/Skeleton-Guidance?node-id=216%3A1663&t=CvrAEVUQTtOSjoP8-1)

**Comment by britt6612** [comment]
1/12 update 

For this ticket: 
changing the deliverable for this sprint to have a PR for a first pass of the following until research is done on the rest of the page. 

![Image](https://user-images.githubusercontent.com/42451602/212113073-f7aa38ea-51c1-466f-a9c6-134c7aba28c5.png)



feedback on content for page from shareout 
- purpose statement: a key element of skeleton is to provide a sense of the structure of the page and the ability to anticipate where certain pieces and types of content are loading. 
- Disclaimer on anatomy "This is a skeleton card" is one presentation but might not always be laid out in Card.
- It's not used for kicking off processes, it's not used for, you know, submissions. It's solely a placeholder. While retrieving a collection of data objects. So whether it's a list of users, or a list of devices.

**Comment by britt6612** [comment]
1/13 update

- Added in the first example to get teams' reactions. 
- Kenny is going to work on making the antomy more lean basied on feedback from Eric then that will be implemented in the site for feedback

**Comment by britt6612** [comment]
1/20 update 

- Deployment preview [here](rhttps://deploy-preview-3077--keen-mayer-a86c8b.netlify.app/components/skeleton)
- Updated code based on Mike feedback for making it more "real world" example
- Updated content from Kennys latest changes
Ready for review either today or Monday
