### ISSUE TITLE
Button Guidance - Add example of a form, layer, with multiple buttons 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1601]
Request from the community to help provide guidance. https://hpe.slack.com/archives/C04LMJWQT/p1620248934167600
> Hi all, as I get into the HPE Design System pages, I have some basic questions about buttons. What is the recommended ordering/layout of buttons in forms or modals? I understand typically you have one primary button as your call to action, but say you have a form/modal with 1 primary and 2 secondary actions (Submit, Export, Cancel).  What is the recommended ordering and justification/alignment of them? In Template pages, basic form has primary button left aligned, but no examples with more than 1 button. In Grommet Storybook I see examples with secondary buttons first, primary button right aligned.

**Comment by KennyAtHPE** [comment]
Expanding this ticket to include layers, modals, and filters

**Comment by vavalos5** [comment]
If you feel you have enough research from what Rena and Maggie provided then i'd say go for it. But if you feel like you need to do further research for each of these, then i'd say lets break it down into 3 separate tickets. @KennyAtHPE

**Comment by KennyAtHPE** [comment]
Placing this back into the backlog, focusing on #1788 for this week

**Comment by vavalos5** [comment]
doneeezoooo woot woot
