### ISSUE TITLE
Add Ordering of Items as a Template 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1608]
Adding ordering of Items to the Templates section. 
https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=33%3A12 

I think we'll likely want to add ordering of lists to the List page and then add a template for table customization that includes ordering the columns, as well as selecting columns.

**Comment by ericsoderberghp** [comment]
Depends on https://github.com/grommet/grommet/issues/5215

**Comment by taysea** [comment]
Closing, this guidance has been added

https://design-system.hpe.design/templates/lists?q=ordering#item-order
https://design-system.hpe.design/templates/datatable-customization?q=table%20cu
