### ISSUE TITLE
Exploration on Page Layouts

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1618]
Conduct research on the different types of page layouts to further understand them and to back up our ideations.

**Comment by ericsoderberghp** [comment]
From our design sprint exploration work:
- https://app.mural.co/t/hpecdoresearchteam7715/m/hpecdoresearchteam7715/1615564823610/f79e7300691f062f2845ccdc3b01f21724554548
- https://app.mural.co/t/hpecdoresearchteam7715/m/hpecdoresearchteam7715/1615217435101/35c1bb956c625e2f2a87f2dd861719110ecf8312

**Comment by vavalos5** [comment]
I think this is at a good spot. There's still some info i'd like to include that I came across today but I didn't get to fully read it, so i'll be adding tomorrow. 

https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/App-Page-Layouts?node-id=881%3A3952

Let me know if there's any other areas I could potentially dig deeper into. But I covered: grids, break points and columns.
