### ISSUE TITLE
Fonts - Reconcile use of old MetricHPE w/ new MetricHPEXS

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1625]
There was question from the design community regarding HPE font files. Upon investigation, it looks like designs in Figma (specifically GreenLake related products) are be created with a mishmash of legacy MetricHPE w/ current MetricHPEXS.

Sources of "mishmash":
- [ ] Copy-paste from pre-existing designs (i.e. not built up from DS Figma components)
- [ ] [hpe.design](https://hpe.design) referencing old font files (top result when Googling "HPE fonts") 

Recommended next steps:
- [ ] Create awareness of the issue
  - [ ] Schedule quick call w/ DS + GL UX (Edgar? Salina?)
- [ ] Update / retire hpe.design?
- [ ] Add "Download Fonts" action to DS site

**Comment by ericsoderberghp** [comment]
Obsoleted by #1627 and #1628
