### ISSUE TITLE
All Components page on the DS site

### ISSUE THREAD

**Issue by ShimiSun** [grommet/hpe-design-system#1629]
The DS site will display a page with all the grommet components that are available in the DS (i.e. all grommet components supported by HPE theme).

It will be nice if the components on the page would have the name of the component and could be linked to the component guidelines (in case they exist).

The page will be useful for both developers and designers. 
The Developers will be able to navigate through the code of all the existing components. The Designers will be able to view all the existing DS components and easily navigate through our available components and report to us if a need or a question arises regarding potentially missing context/components.

The purpose of the page is:
1. Have greater transparency of which grommet components are supported within the DS.
2. Leverage the page for Applitools snapshots and maintain a wide baseline of all components.
3. Having a kitchen sink of all existing components so users will quickly find components or report components that are missing.

**Comment by taysea** [comment]
To make sure I'm understanding the proposal, this would be similar to https://storybook.grommet.io/?path=/story/all--all, except in terms of layout it would be more organized (maybe single column?) with headings for each component name and a button that would take you to the actual guidance page?

**Comment by ShimiSun** [comment]
Yea, @taysea, spot on. Thanks for adding this comment.

**Comment by vavalos5** [comment]
This would basically be a live interactive "sticker sheet". Love it!

**Comment by taysea** [comment]
Closing since this page has been added: https://design-system.hpe.design/components/all-components?q=all
