### ISSUE TITLE
Filtering - Add testing suite to support FilteringControls implementation

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1630]
Testing suite should cover user interactions such as the following:
- [ ] typing a search query
- [ ] click filter button to open filter layer
- [ ] select filter attributes, close layer w/o applying
- [ ] select filter attributes, apply filters
- [ ] after filters applied, open layer, deselect some attributes, close w/o applying
- [ ] after filters applied, open layer, deselect some attributes, apply filters
- [ ] after filters applied, open layer, reset filters
- [ ] after filters applied, click clear filters
- [ ] other scenarios ...

For each test, the success criteria should include:
- [ ] Results summary displays correctly (e.g. 2 results of 9 items)
- [ ] Filtered results are displayed with the correct number of results
- [ ] FilterButton displays a badge with the correct number of filters applied
- [ ] Snapshot tests as appropriate

**Comment by taysea** [comment]
Closing, now we have Data + friends and have removed this local implementation
