### ISSUE TITLE
Process - Create a Design System Contribution Guide

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1645]
This is an issue we've discussed per one of our retros.

It would be great to create some type of guide that we can share and pin in the Design System Channel that would help and allow others from other teams contribute to the DS.

We will have to do some explorations on how we want to tackle this.

**Comment by vavalos5** [comment]
I had posted and pinned this in the Design System Staff Channel previously.. Could be a helpful starter?

Hola Design System Channel! :sunflower:
We want to thank all of you for your continuous participation and would like to encourage you all to participate and contribute to the Design System. Whether that’s through submitting a bug :bug:, or adding a ticket :admission_tickets: to our backlog.

**Are you wondering how you can submit a ticket in the backlog?** :thinking_face:

1. Go our Design System GitHub backlog
2. Under “Triage” Column, click on the “+” icon
3. Name the ticket with a title of the problem
4. Click “Add”
5. Find your card on the Triage column and click on the ellipsis>Convert to Issue.
6. You will see a modal pop up where you can add more details and even edit your title. Select the hpe-design-system repo.
7. Once finished adding details, submit through click on “convert to Issue”
8. Congrats you’ve submitted a ticket! :tada:

if you’re feeling like you’re up for picking up a ticket from our backlog, GO FOR IT! Please reach out to us if you’d like to take a ticket on.

**LET’S MAKE THINGS HAPPEN!!** :raised_hands:

**Comment by ericsoderberghp** [comment]
That's a part of it. Maybe we should consider some working with Kenny to draft some text, to see how someone from outside of the team might approach it?

**Comment by bahriaditi** [comment]
Agree that we will eventually need a one page guide. But we need to hold on this until we tackle #2466 , #2467, and #2468

**Comment by bahriaditi** [comment]
Here's my WIP: https://www.figma.com/file/xeovADk4pcqfZqSf8rtxaF/Contributing-Guide?node-id=0%3A1

This doc is designed to give an overview on:
- Scale/ Types of contributions
- Decision Tree of when to make which type of contribution
- How to make contributions
  - Figma branching for small and medium contributions
  - GitHub for large and new features (Note that this will be eventually replaced with the "SandBox" idea)

**Comment by bahriaditi** [comment]
I was unable to document the Sandbox user flow this week - will revisit after I am back in office, along with testing the proposed contribution model with GLCP and Ezmeral.

Moving this back to To Do since this will be paused during the coming Sprint.

[Figma](https://www.figma.com/file/xeovADk4pcqfZqSf8rtxaF/Contributing-Guide?node-id=0%3A1)

**Comment by bahriaditi** [comment]
Marking as done (pending soft rollout and user testing). Next steps tracked in parent ticket #2220
