### ISSUE TITLE
Navigation - Header

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1651]
Figma Exploration section: https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1%3A20

i thought it would be good to begin with header. I'm including ideation/exploration tags to this as I feel that even though we've gone broad on the topic "Navigation". We now need to narrow down on topics, research and ideate.

Eric's comments per ticket #1564

I like the Structural, Associative, and Utility segmentation.

Some interesting aspects of Structural navigation in particular:

- because it is hierarchical, width and depth
- how do you structure the hierarchy, by resource type or by task type?
- do you organize by conceptual model or by frequency of user task?
- how to convey context for deep links, breadcrumbs vs. just immediate parent + back to home/top?
- which depth(s) in the hierarchy are persistently shown?
- I also think a Menu could be used for structural navigation.

**Comment by vavalos5** [comment]
This navigation stuff on headers is woof!

I have a few questions i've come across to realize:

1. How can we give guidance on whether or not to use a hamburger menu on the header for desktop and mobile view if we are currently not offering it on the Design System as an option.
2. I realize sidebar is a potential option to have along with a header. While we also don't offer this component, do we say that it can be used with a header or as the applications main navigational area?
3. Do we need to resolve those 2 questions above before getting into header?

**Comment by ericsoderberghp** [comment]
> 1. How can we give guidance on whether or not to use a hamburger menu on the header for desktop and mobile view if we are currently not offering it on the Design System as an option.

At this point, I think we should feel free to explore any options for how to handle navigation controls and components. I'm curious to see how we collapse navigation layers in mobile, where we have an HPE global navigation (UCEP), "central" navigation, like Green Lake or Storage central, and then app navigation, like bare metal as a service (BMaaS). That's three layers, and we're only to the top of the app navigation part. gulp.

> 2. I realize sidebar is a potential option to have along with a header. While we also don't offer this component, do we say that it can be used with a header or as the applications main navigational area?

We do offer a Sidebar component in grommet and teams are using this for primary navigation. I think we should consider at least two contexts: UCEP + central + app (as mentioned above), and stand alone app, like the admin console for a Proliant. A Sidebar could be a good choice when keeping the hierarchy wide rather than deep, allowing more options than a horizontal navigation structure in a header or tabs. Sidebars require a bit more thought for mobile, likely via a Button to open a drawer/layer.

> 3. Do we need to resolve those 2 questions above before getting into header navigation?

I think we should consider at least three navigation patterns:
- button control leading to a menu/layer
- horizontal controls, either in a Header or via Tabs
- vertical controls in a sidebar

I think we will need to include guidance for how to do them, when to use them, and how to use them in combination.

**Comment by vavalos5** [comment]
Had a chat w/ Chris earlier and it sounds like we might want to put this on pause until we know more about what the UCEP team is going to do. I'm going to be reaching out to Gina and Maggie on some research they had done so I can listen in to content that might be helpful

**Comment by vavalos5** [comment]
Chatted with Gina who showed me the work her and Maggie have been doing for Navigation and Headers.

Here's the link to the work they've been doing to refer back to: https://www.figma.com/file/AbxAC3KU59pPyHG5mnnh7R/HFS-North-Star?node-id=6%3A1

**Comment by vavalos5** [comment]
Refer to #2208

**Comment by vavalos5** [comment]
Guidance on Side-to-Side Navigation Figma file: https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1647%3A9562

including screen shot of this section
<img width="903" alt="Screen Shot 2022-01-28 at 2 57 01 PM" src="https://user-images.githubusercontent.com/62117454/151633001-28e65f66-82e0-4cad-817a-88e260fe2ddc.png">

**Comment by vavalos5** [comment]
Sorry for putting this to "in review" on a friday.. @ericsoderberghp 😿

**Comment by ericsoderberghp** [comment]
> Sorry for putting this to "in review" on a friday.. @ericsoderberghp 😿

no worries! dropped a comment in Figma

**Comment by vavalos5** [comment]
Putting on hold until we get a better understanding of page header. But we also need to define the local header. What is the purpose? Is it a page header??

**Comment by ericsoderberghp** [comment]
Good questions about differences in types of header:
- global header: shared across all apps, for things like user account and app navigation
- app header: shared across all pages in an app, for navigating among top level pages in the app
- page header: navigation related to this place in the page hierarchy, H1 for this page, ascending/up button, peer pages, page level actions
- section header: tabs within page, table header with caption, summary, filtering, and actions
Questions around which are optional and when to use or not to use them.

**Comment by vavalos5** [comment]
> * app header: shared across all pages in an app, for navigating among top level pages in the app

Thank you Eric, this was so helpful! I can imagine this being incredibly helpful to others as well as we continue to explore how we might organize this content with relevant examples. @ericsoderberghp

**Comment by vavalos5** [comment]
@ericsoderberghp do we want to continue having this in our backlog if UCEP owns the Global Header. Is this still relevant to Navigation? Are we implementing Global/Footer to the DS?

**Comment by ericsoderberghp** [comment]
I think the longer term direction is away from "app navigation" as we have more smaller services rooted in GreenLake. There's an interim aspect though about what to do with existing larger apps that are plugging in to GreenLake as is. I think we can leave the global header to Gina and team, ensuring we align and have examples on the design system site and component(s) in the design system Figma library. I believe Chris Carlozzi was working on this. I'd recommend connecting with him to discuss what he's working on in this area and what we might want to bring into the design system.

**Comment by taysea** [comment]
Closing for now, any new navigation work would require a reboot and kick-off.
