### ISSUE TITLE
Update Page Layouts

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1658]
Update the Page Layouts page on the design system site to reflect the latest designs and refer to the latest Figma resources.

https://design-system.hpe.design/templates/page-layouts

https://designer.grommet.io/?id=page-layouts-eric-soderberg-hpe-com

https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/App-Page-Layouts?node-id=881%3A3953

Given the skeletons in the designer, take this as an opportunity to explore how we might want to handle skeleton components in general.

**Comment by bahriaditi** [comment]
@ericsoderberghp @taysea this ticket seems to have preceded the 'big things' issue [#1794](https://github.com/grommet/hpe-design-system/issues/1794). Closing this because we will be addressing these topics in sub tasks #2055 and #2054
