### ISSUE TITLE
Make Menu one component in Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1663]
It has been confusing to many designers as to how the Menu Button works. If a designer were to search "Menu" in Figma, you'd think it would only be the Menu Button and wouldn't know to add the Drop.

Please make the Drop and Menu Button one component in Figma so it is easier to utilize.

**Comment by vavalos5** [comment]
https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=157%3A0

**Comment by vavalos5** [comment]
Had a convo with Chris on this. We both agreed we should offer a menu with and without the stroke. Will also need to create a ticket to link to this ticket to create a button with a stroke variant into Figma.

Putting on hold until we confirm we are adding a button with a stroke to DS.

**Comment by ericsoderberghp** [comment]
It's already in the theme and design system site: https://design-system.hpe.design/templates/filtering#filtering-with-selectable-results

**Comment by vavalos5** [comment]
We need to add a section in DS site that discusses when to use. We don't have it as a variant in button page

**Comment by ericsoderberghp** [comment]
Working on it: https://github.com/grommet/hpe-design-system/issues/1701

**Comment by vavalos5** [comment]
This ticket is relevant to #1708 

Changes have been made: https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=0%3A1
