### ISSUE TITLE
Order of Items - Keyboard interactions not working properly on the Design System site

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1668]
When on "Select Columns" Tab is selected, the focus does not go to the Search bar. The only other direction the user can go to using the keyboard is the next Tab. Please look into what's going on here.

**Comment by taysea** [comment]
Hi Vicky,

The user can tab to the search bar, but they first just have to go to "Order Columns" since this is the natural page order. However, the intended interaction is that the search input would have focus when the Drop opens?

**Comment by vavalos5** [comment]
I'm glad we discussed this via call because I did not provide enough context here 😖
