### ISSUE TITLE
Provide explanation of and guidance for "Sizing"

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1671]
Related https://github.com/grommet/hpe-design-system/issues/1562

Sub-issue created from https://github.com/grommet/hpe-design-system/issues/1562

As part of the findings from the developer onboarding research, greater clarity/explanation regarding "T-shirt sizing" was desired.

Create a page on the Design System site explaining "t-shirt" sizing, including:

- [x] Base spacing unit --> 24px
- [x] Explain "Why t-shirt sizing?" --> consistency, compatibility, flexibility
- [x] Concept of medium + medium = large ...
- [x] T-shirt sizing in terms of height/width (e.g. Box, Grid columns, ...)
- [x] T-shirt sizing in terms of spacing (e.g. gap, pad, margin, border, round)

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/hpe-design-system/issues/1644 as well.

**Comment by ericsoderberghp** [comment]
Proposal, create a "T-Shirt sizing" page in the design system. Transfer the sizing content from Figma to this page.
