### ISSUE TITLE
Navigate Design System site + Figma and find misalignments/bugs

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1676]
Go into the design system site and play around with the mouse and keyboard interactions to see if anything doesn't seem right. Go into Figma files and check if everything looks aligned.

**Comment by taysea** [comment]
## Dev changes
- [ ] Change accordion border color to "border" in theme
- [ ] DateInput uses `Close` icon on site, but Figma calls for `FormClose`

## Design changes
- [ ] DateInput is a heading and should be `text-strong`, Figma is using `text` (should change to `text-strong`)
- [ ] Menu has no "selected" state, should remove
- [ ] Table designs showing Data Table with Search Value need to be updated to match the filtering styling, currently using wrong/outdated text colors

Clarifications:
- [ ] Select in Figma uses "Form value" font-weight -- is this intended?
- [ ] Need to revisit this pattern in Table: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A13926

**Comment by ericsoderberghp** [comment]
Is there any reason not to add the "Batch Actions" in Figma to the design system site?

**Comment by taysea** [comment]
Good question. I think we should if this is a pattern that is finalized. For some reason, I was under the impression that it was up for discussion? Which is why I listed it under "Clarifications". If this pattern is final, we will also need to update the Filtering examples to match.

**Comment by vavalos5** [comment]
I too somewhat recall that we were going to discuss "Batch Actions" again. 🤔 But if we're ok with the approach we've got, then it is finalized in Figma

**Comment by ericsoderberghp** [comment]
I was going off the fact that the Batch Actions are published to the "Finished" page in Figma. I think the proposal is a reasonable starting point. I could see publishing it in an "out for review" context, with a request for feedback.

**Comment by taysea** [comment]
Closing this issue since related issues have been opened to the remaining to-do items.
