### ISSUE TITLE
Add guidance for which icon state should be used when toggling states

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1685]
From [this thread](https://hpe.slack.com/archives/C04LMJWQT/p1624494671145700)

Provide guidance for whether an icon button being used as a state toggle should display the current state or the future state to be applied.

- [x] Conduct research and best practices
- [x] Add guidance and supporting rationale
- [x] Apply findings to Design System site's theme mode tip and a11yTitle to read "Switch to dark mode".
- [x] Ensure table column sorting icons follow recommendation

@ecircenis answered this nicely: "A button should always indicate what will happen when you click it and not be an indicator of the current state.  And, for accessibility - think blind users - it is especially important that the a11yTitle explain what the button will do.
Thus, for a light/dark control, if you are in light mode, the icon would be a moon and if you are in dark mode, the icon is a sun (and the a11yTitle should not be "moon icon", but rather something like "Switch to dark mode").
Similarly, for passwords, when the password is obscured, use an open eye icon.  When the password is shown, use a closed or slashed eye icon."

"In every other scenario where a button is used, we are always saying what will happen (e.g. Submit, Save, Cancel, Close, View, …), so why should an icon button be treated any different? We are simply swapping out written language for another form of visual language. "

**Comment by vavalos5** [comment]
Most of my research is completed and can be found here: https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=3219%3A5092

Will create an "ideation" ticket next

**Comment by vavalos5** [comment]
Ready for review. Figma file: https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=3262%3A5285

**Comment by vavalos5** [comment]
Awaiting for PR to be approved to close this ticket #1578
