### ISSUE TITLE
Button Guidance - Research when should a button be left aligned vs right aligned on a form, modal, layer and wizard

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1704]
A question in the design system channel came in as to when should a button be left aligned vs. right aligned within a form, modal, layer or wizard.

It would be good to double make sure that what we have defined currently is aligned to common UX standards. 

Let's research and write guidance for each of these instances.

Slack convo can be found here: https://hpe.slack.com/archives/C04LMJWQT/p1625039040176200

**Comment by vavalos5** [comment]
Ephrem has done some research around this topic. Linking his Figma file with research for when we get around to this. https://www.figma.com/file/vK6LH6vXfdK7euQ7AmEgr4/Components-Templates-and-Guidelines?node-id=1097%3A43509

**Comment by bahriaditi** [comment]
Screenshot from Rena demonstrating need for guidance (this was brought up in today's design system office hours)
Figm file: https://www.figma.com/file/Ou9nGClJ0auVKhHsNWysPg/API-Gateway?node-id=20%3A0

![Screen Shot 2021-09-29 at 11 36 52 AM](https://user-images.githubusercontent.com/87677275/135329880-0569095d-7f48-40be-85bc-5d831205c5f1.png)
)

**Comment by vavalos5** [comment]
Adding some screen shots from the Ezmeral team on how they've written guidance for their team based on this issue. It seems like many teams are doing left aligned and many others are doing right aligned. This is a basic I think a lot of teams should have guidance on.
![Screen Shot 2021-10-06 at 12 32 46 PM](https://user-images.githubusercontent.com/62117454/136271548-b6a1e822-a722-43f7-9117-64abf2c8291e.png)

**Comment by vavalos5** [comment]
@KennyAtHPE Can you include the link to where your work is here so it's easier to track please :)

**Comment by KennyAtHPE** [comment]
Guidance is being written [within the buttons Figma page](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=2282%3A5045). Although this is much more generalized guidance for Layers, Forms, Wizards, and Modals.

**Comment by vavalos5** [comment]
@KennyAtHPE Are you awaiting for a review from myself?

**Comment by KennyAtHPE** [comment]
@vavalos5 nope, will be moving this back to in progress right now

**Comment by KennyAtHPE** [comment]
Closing out this ticket, relevant to #1788
