### ISSUE TITLE
Add new Toolbar button to Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1709]
Add new Toolbar Button component to Figma.

Create variants and publish to align with deploy link Taylor created: https://deploy-preview-1703--keen-mayer-a86c8b.netlify.app/components/button#toolbar-button

New buttons can be found here: https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1

**Comment by taysea** [comment]
Closing, toolbar buttons have been published.
