### ISSUE TITLE
When should Optional vs Asterisk be used on a Form

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1712]
I think we need to write more detailed guidance on when to use an "optional" vs "asterix" on a Form. Or should we use it at all. While we say if using a mixture of "required" and "optional" fields, is that apparent visually on a form? 

It is expected that all of the fields placed on a form should be "required", however, is that apparent enough? Is that good UX?

NNG helpful link we can refer to: https://www.nngroup.com/articles/required-fields/

Currently this is what we have on the design system site for guidance:

 "When possible, restrict Forms only to fields that are required. This ensures that the Form remains concise for the user. However, there may be cases where optional fields may be fitting.

When using a mixture of required and optional fields, apply the "required" prop to any given FormField restrict form submission until this field has been completed."

**Comment by Keeth-HPe** [comment]
Working on this to find answers, but is it just me or all find 'asterisks' missing in forms in Figma Library? 
<img width="794" alt="Screenshot 2021-08-12 at 3 40 44 PM" src="https://user-images.githubusercontent.com/86280029/129179979-23a9d7fa-7c85-4d0d-abf7-f58ba7757fd9.png">

While DS has (*) in all the fields 
![Uploading Screenshot 2021-08-12 at 3.33.36 PM.png…]()

**Comment by Keeth-HPe** [comment]
https://www.figma.com/file/Jn4PnzII1OEglj5Zc4GSGC/Optional-vs-asterisk?node-id=8%3A2

Here I collated few information on why using "optional" is better than having asterisk for all fields in a form. However, I believe this should be use case specific and it purely depends on the form the user is trying to fill. eg. when a user is trying to fill a form with 5 fields in it out of which 1 field is optional we need not add 4 asterisk where the mandatory inputs are required.

**Comment by vavalos5** [comment]
Good questions Keeth! I think there are misalignments on both the design system site and Figma. This ticket is to help get some research and validate which direction is the the correct way to go. We need to find some best practices and do some research on accessibility. Feel free to create other tickets on other problems that arise

**Comment by vavalos5** [comment]
We tend to go to NNG as well to find information on research already conducted. Here's an article from Nielsen Norman Group on asterix vs. using "optional"

https://www.nngroup.com/articles/required-fields/

**Comment by Keeth-HPe** [comment]
Research on when to use Optional vs Asterisk be used on a form. With some examples, I have gathered few guidelines. It's best to mark fields required (*) and optional in a form. Here's why:  https://www.figma.com/file/Jn4PnzII1OEglj5Zc4GSGC/Optional-vs-asterisk?node-id=8%3A2

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe! I agree with your assessment. @vavalos5 do you have any additional feedback/thoughts?

Meanwhile, it would be great if you can help with the following:
- [ ] Please put this research on the "🕵️‍♀️ Use Cases and Research" page of the Form file (I gave you editing access): https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=4988%3A3653
- [ ] Add a link/ source description of this research to the Figma file as part of your frames (so we can reference/ cite this research at a later date if needed)

**Comment by vavalos5** [comment]
Thanks @Keeth-HPe. It's looking great! I was just taking a peek at your research and guidance and I was having a hard time understanding which one was the research from the guidance. We may want to separate those into different pages as @bahriaditi mentioned. 

- [ ] I think another thing to make this more clear with your guidance is to provide visual examples. For instance, you might want to use a form in the area where you have "when to skip asterisk"

- [ ] I think we should also include any NNG information found that was useful to help validate the decisions chosen.

- [ ] Lastly, it might be good to also look into [WCAG](https://www.w3.org/TR/WCAG20-TECHS/H90.html) to double make sure whether the way we're labeling things in the back end are correct.

**Comment by Keeth-HPe** [comment]
Thank you for the feedback @vavalos5 and @bahriaditi. 
I have added this to  "🕵️‍♀️ Use Cases and Research" page of the Form file.
 Add a link/ source description of this research too.

@vavalos5 Sorry I did not make that clear. However, I have now mentioned which are the ones from research. And regarding, 'visual examples' for "when to skip asterisk" .. I have actually added screen grabs for all of it. Should I source in some more?

I have included info from NNG, but I'd like to discuss about [WCAG,](https://www.w3.org/TR/WCAG20-TECHS/H90.html) as I am not able to understand labels and legends

**Comment by vavalos5** [comment]
@Keeth-HPe It might be good for you to [go through this list of definition](https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html)s. It'll help you understand some of terminology used by developers to help guide you through your designs and to better understand how screen reads work.

While it's not necessary, it might be good to understand it for when you pair with a developer. Feel free to reach out to any of the developers as well to get a better understanding.

**Comment by Keeth-HPe** [comment]
I really needed this!! Thank you @vavalos5 . Will go through it. And yes I'll reach out to developer, I definitely need better Understanding.

**Comment by bahriaditi** [comment]
Adding notes from the dev + arch talks where @Keeth-HPe presented her work for review.

Next steps on this:

- Pair up w dev and understand how screenreader will work for mandatory vs. non-mandatory
- Keep asterisk and optional on the right
- Consider color of asterisk - red vs. same color as text (consider visual noise and color-contrast for accessibility)
- Create 2 visual examples (HPE specific):
  - Registration form (no asterisk, no ‘optional’)
  - Regular form (mix of ‘optional’ and asterisk)
 
Moving back to in progress.

**Comment by Keeth-HPe** [comment]
@bahriaditi  @vavalos5 

After Pairing up with dev and understanding how screenreaders work and Creating visual examples, here's the output: 
https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=4988%3A3653

**Comment by ericsoderberghp** [comment]
Nicely done!

**Comment by bahriaditi** [comment]
Closing - made a separate issue for adding to the site!
