### ISSUE TITLE
Include guidance to Design System site on how to use "Stack"

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1722]
In the design system site, we don't have any guidance on how to use "stack". Figma file has some guidance, but might be good to create more examples using real product examples showing the different flavors of "stack". I do realize the notifications one might be tricky as Notifications is currently being worked on.

Here's what we've got in Figma: https://www.figma.com/file/hX9HrBlvr6DTpUk2DSlikF/HPE-Stack-Component?node-id=0%3A1

**Comment by taysea** [comment]
Closing due to lack of need/interest.
