### ISSUE TITLE
Button - Explore badge variant

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1723]
Jitesh has requested we add a button with a badge variant to Figma+Design System site. Before we do so, it would be good to do some research on whether it's good UX to show many badges within one screen. For instance, if 4 buttons out of 5 buttons show badges, can this be overwhelming to a user? Should these badges live under 1 button where a user can select and view all of the badges in a screen? Does this turn into notifications?

Convo came from this Slack thread: https://hpe.slack.com/archives/C04LMJWQT/p1626099722307200

**Comment by vavalos5** [comment]
Yes, this sounds good to me!

**Comment by taysea** [comment]
Closing, `badge` has been added to grommet and Figma.
