### ISSUE TITLE
Figma — update DateInput month "June 2020" heading color

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1724]
DateInput/Calendar month "June 2020" is a heading and should be text-strong, Figma is using text (should change to text-strong)

**Comment by vavalos5** [comment]
Nice catch @taysea!

Done, done and done! 

https://www.figma.com/file/Mf9if6zyGETTWW5b9PsYNQ/HPE-Date-Input-Component?node-id=0%3A1
