### ISSUE TITLE
Figma — Remove "Selected" state from Menu

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1725]
Grommet menu does not support a "selected" state at the moment. In cases that need persistent selection, we use Select. We should remove "Selected" state from Menu Figma examples.

**Comment by vavalos5** [comment]
`Selected` has been removed from list items on `Menu`

https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=0%3A1
