### ISSUE TITLE
Figma — Table designs showing DataTable with filtering need to be updated to use `text` color

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1726]
Table designs showing Data Table with Search Value need to be updated to match the styling we show in Filtering Figma/on DS site.

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A242

**Comment by vavalos5** [comment]
+ Update spacing between total number of items below search input

**Comment by vavalos5** [comment]
Updates have been made: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=1%3A2
