### ISSUE TITLE
Modal should stay within mobile view in Wizard when canceling

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1733]
<img width="810" alt="Screen Shot 2021-07-14 at 2 16 22 PM" src="https://user-images.githubusercontent.com/62117454/125694341-06627550-e97c-4f76-9f93-b63c8102e808.png">
I think we should show an example of a much smaller modal that fits within the mobile view (see image). I've attached an example below of how it is in Figma.

https://www.figma.com/file/GEhgYzx3b8MejBjg9gAxyA/Wizarding?node-id=127%3A892

I'm also questioning whether we needs to shrink down the text within the button. It's rather long

**Comment by ericsoderberghp** [comment]
Can we do this with Layer `target`? https://v2.grommet.io/layer#target
