### ISSUE TITLE
Update color on Form Headers on Design System site

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1739]
<img width="382" alt="Screen Shot 2021-07-20 at 10 43 50 AM" src="https://user-images.githubusercontent.com/62117454/126371325-1afb81c8-1106-4889-92e3-a6390b8d7b52.png">
The Design System is currently showing regular text color on Form headers, but should be text-strong. Please update to align with Figma :) 

https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1

**Comment by ericsoderberghp** [comment]
Good catch. I think the form headers on the site should be using Heading, which should result in text-strong.
