### ISSUE TITLE
Update validation on Range Input in Figma to have validation icon

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1740]
<img width="478" alt="Screen Shot 2021-07-20 at 12 54 16 PM" src="https://user-images.githubusercontent.com/62117454/126387320-eee5a24f-bc45-4d1b-b913-325f6f336633.png">
Currently our R`angeInput` in Figma doesn't have the "validation icon" to the left of the validation error text. Please align to our other validation inputs.

Including `TextArea` as a reference: https://design-system.hpe.design/components/textarea#validation

**Comment by bahriaditi** [comment]
@vavalos5 this is done! https://www.figma.com/file/BqCjvjc0rECQ4Ln2QhyjNi/HPE-Range-Input-Component?node-id=0%3A1

**Comment by vavalos5** [comment]
Thanks Aditi! I noticed the icons on the light-mode but not on dark-mode. 🤪

**Comment by bahriaditi** [comment]
Whoops – sorry about that! Just updated the dark-mode too.
