### ISSUE TITLE
Create a Figma file to document what's new for Designers side

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1743]
Since we are now 2 designers, there will be multiple projects being worked on and it will be good for us to have a shared document where write down what we worked on so we can update the What's new page on a weekly cadence to submit PRs

**Comment by vavalos5** [comment]
Hey Aditi, this is the layout design I had created for our "what's new" page. We could create another page under the layers tab and create a document where we can document that. We could also do a Word doc.You pick 😄

**Comment by vavalos5** [comment]
- [ ] Let's also include bi-weekly tickets in backlog for us to rotate and update. 😄

**Comment by bahriaditi** [comment]
Document created here: https://hpe-my.sharepoint.com/:w:/p/aditi_bahri/Ea2iPWQ3vrZOqQwJJXUnCqcB5ch--upWeIww3CHRwgYqYA?e=GqxHpA
