### ISSUE TITLE
FileInput Component Design in Figma does not match the DS site

### ISSUE THREAD

**Issue by derekhchen** [grommet/hpe-design-system#1745]
### Is this issue related to the design system core library or design system website?

Both. The designs for the FileInput components in Figma does not match with the one on the DS website.

### Expected Behavior
I expect it to be consistent.

### Actual Behavior
I expect the value to be taking up the form/value styling and the trashcan icon to be the form icon.

Figma form value is using 'text/normal/default' and the website is using the bigger trash can.
### URL, screen shot, or CodeSandbox exhibiting the issue
This is what's show in Figma
![image](https://user-images.githubusercontent.com/38574571/126710855-3a5f1807-5f78-458c-8a98-0733775407ff.png)
https://www.figma.com/file/8HwAiiSDloOTjUxqvCTypq/HPE-FileInput-Component?node-id=408%3A14197

This is what's show on the website
![image](https://user-images.githubusercontent.com/38574571/126710927-e65dcb57-111a-4165-8f85-e337cfff6e2c.png)
https://design-system.hpe.design/components/fileinput#fileinput-with-multiple-files

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by britt6612** [comment]
<img width="536" alt="Screen Shot 2021-07-30 at 2 54 00 PM" src="https://user-images.githubusercontent.com/42451602/127710580-76b5cbcc-8738-4d82-adf8-b16746f2c7a4.png">
Figma and Site are aligned
