### ISSUE TITLE
Consider adding underline to the disabled state for anchor so that it is visually evident that it is a link/ interactive element

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1751]
Currently, disabled anchors are styled using a lighter grey font-color and do not have an underline. This is inconsistent with the default anchor styling which does have an underline. Without any indication that it is an interactive element, disabled anchors can be confusing and perceived as free standing copy without sufficient context.

It might also be beneficial to include contextual help messaging to indicate why an anchor is disabled in the first place. Something for @Keeth-HPe to consider in ticket [#1705](https://github.com/grommet/hpe-design-system/issues/1705)

Refer to best practices while considering this use case. Example: https://www.w3.org/TR/WCAG20-TECHS/F73.html

**Comment by Keeth-HPe** [comment]
Moved this ticket to the 'Design system', as 'Disabled Anchors' do have an underline and is consistent to the with the default anchor styling.

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe!


Recommended next step:
- [ ] Update [disabled anchor ](https://design-system.hpe.design/components/anchor#disabled-anchor)on the site to match design
Link to Figma file: https://www.figma.com/file/I7PsiUmvr7OEJ6311rBUfg/HPE-Anchor-Component?node-id=0%3A1

**Comment by taysea** [comment]
Would need valid use cases where anchors should be disabled. Closing for now.
