### ISSUE TITLE
Explore "selected" + "disabled" options on a Select component

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1756]
Dring a weekly synch up with CCS, a use case pop up where they are seeking to show both selected and disabled items within a Select component. 

We need to research how we might stylize that in a way that makes sense to a user. Perhaps what we've got in Grommet? https://v2.grommet.io/select?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAb[…]ZH6hinpnp4IAMIAFuhgSf6EZF4+8EippOIAfLz8QtmE3r5gxO2eAPTT5qYUqUA

Would be good to look other options

CCS Designs can be found here:https://www.figma.com/file/1Bc4bE0xFgWBxM9JabWBqZ/Application-Catalog?node-id=255%3A40559

**Comment by taysea** [comment]
This can be achieved in Grommet, closing: https://v2.grommet.io/select?theme=hpe&c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAbQDd1cR8AaRO-KAGrtOAXUQBeRACV86aADoQfAMpR0UIgHI42fEjpwQAJwj5NxANxVER-saSFr1ADwAhOKkQATGLejwwcQAiIzgAdyDEACslWGAAT2C9LyCAPidqRGdlfAJoRB1YenEyJm0wMx5NKDC4TSqoAAtbMxEAX0Q2DnxghHxInzp0ACMCLxKyvs12xAB6dMys2fdUBcRLCjagA

<img width="1167" alt="Screen Shot 2024-07-26 at 9 34 09 AM" src="https://github.com/user-attachments/assets/6f609f34-57ed-4b95-b97f-8117578ee131">
