### ISSUE TITLE
How would a user revert back to default ordering of items if they decide not to pursue changes?

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1759]
<img width="668" alt="Screen Shot 2021-07-29 at 10 30 17 AM" src="https://user-images.githubusercontent.com/62117454/127538474-f53c26ae-3db9-4b39-8a48-46705b163f07.png">
<img width="314" alt="Screen Shot 2021-07-29 at 10 30 08 AM" src="https://user-images.githubusercontent.com/62117454/127538488-f052ab8f-f684-4fd8-b6f1-ddc1edb3b75c.png">
Revanth commented on our Figma file for Ordering of Items. He brought up a good point about how can the user revert back to default ordering if they've made changes they no longer wish to pursue. Or if they want to cancel in general for that matter.

I think it would be good for us to explore what the best /common way of showing that. Is it a cancel button? An "x"? 

Please explore :)

**Comment by taysea** [comment]
Closing this, this can be achieved by a "controlled" pattern of the List component where the original order is stored in React state and reset if some "cancel" type button is clicked. https://v2.grommet.io/list#onOrder
