### ISSUE TITLE
Create icon-only variants for the toolbar button component in the Figma library

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1760]
Add missing icon-only variant for this button component

**Comment by bahriaditi** [comment]
https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1

<img width="613" alt="Screen Shot 2021-07-29 at 10 27 51 AM" src="https://user-images.githubusercontent.com/87677275/127538614-21cf0432-be7e-49f3-9d7a-f5021351b23e.png">

**Comment by bahriaditi** [comment]
@vavalos5 this is done! Can you take a quick look and let me know if I'm missing anything?
https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1

**Comment by vavalos5** [comment]
Looks good to me @bahriaditi Publish it 😄

**Comment by bahriaditi** [comment]
Published!
