### ISSUE TITLE
Button Guidance - Revisit modal/side drawer/ layer and explore whether we should have both a "x" to close and cancel button

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1761]
During a call with CCS, we came to agree that we need some guidance in the Design System explaining when an "x" to close the modal/layer would be used, if at all.

We also were questioning when we would include a "cancel" button if at all.

Reasoning is because sometimes there is a third button and the footer of the layer/modal then becomes busy.

It would be good for us to have guidance on whether the "x" should be there. We'll have to do some research on whether users click out of a modal/later more to cancel out or whether they click on "cancel" or "x"

**Comment by KennyAtHPE** [comment]
A couple of updates:
- A lot of research spurred from this, specifically dealing with accessibility on what is actually required (not much) + what is the best user experience (a lot of controversial takes)
- Lots of extra use cases to be taken into account for
- Providing guidance on the difference between an "x" button and a primary/default "cancel" button and how to design in a way that will allow end users to distinguish between the two

**Comment by vavalos5** [comment]
Feel free to create smaller tickets as needed @KennyAtHPE if you feel like it should be broken down

**Comment by ericsoderberghp** [comment]
Would like to be able to say that a close/cancel control should always be visible when a Layer is opened, allowing the user to quickly dismiss it in case it was opened accidentally. But, this would be in conflict with https://design-system.hpe.design/templates/forms#button-placement-and-labeling. Need to provide guidance to resolve this tension. Perhaps the close/cancel need not be visible if the form is long?

**Comment by taysea** [comment]
One consideration is if we remove the "X" from the actionable layers, where will the focus be placed when the layer opens and how will we give the user context about the form title/etc. Right now, we autoFocus the "X" button and provide an a11yTitle on it.

**Comment by KennyAtHPE** [comment]
@ericsoderberghp there is actually guidance for overflow behaviour and current implementation for buttons to sit on top of all other content found within the [Filtering Page](https://design-system.hpe.design/templates/filtering). This was a bit hard to find and I feel like this guidance and example should be found within the main [Layers page](https://design-system.hpe.design/components/layer).

A ticket for that example + others/guidance to be included within the Layers page has been made #1887

**Comment by KennyAtHPE** [comment]
@taysea Matt and I played around with this [example](https://storybook.grommet.io/?path=/story/layout-layer-target--target-layer) and found that screen reader could alternatively read out a message when the whole layer is selected. The flow would be like this for keyboard users:

Enter to open layer, tab to focus on the entire layer, the message would read out something like "You are in a layer containing a form to add new hosts, to close this layer, press Escape," tab again to focus onto the first field within the layer.

**Comment by taysea** [comment]
Thanks for this explanation! Would it be possible to have the flow be "Enter to open layer and automatically focus on the entire layer"? -- having to press tab again to focus on the layer seems like a confusing/redundant extra step.

**Comment by KennyAtHPE** [comment]
Confirmed with Matt that this would be doable if the "tab to focus on the entire layer" is eliminated. The flow would then be

Press enter to open the layer which then focuses on the entire layer, from here the message would be read aloud. Subsequent tabbing would take the user into the contents of the layer, they'll always have the ability to close the layer by pressing the "esc" key.

**Comment by bahriaditi** [comment]
Hi @KennyAtHPE. This came up again during office hours – Rena from CCS requested guidance on close button vs. "x" (see attached screenshot). 

After reading the comments above, I couldn't tell if we came up with a decision specifically around "whether we should have both a "x" to close and cancel button" And if we did, where can I find that documentation to point people to?


![Screen Shot 2021-09-29 at 11 42 43 AM](https://user-images.githubusercontent.com/87677275/135890458-d6337e12-7a89-4161-a5fb-976513bc31f1.png)

**Comment by KennyAtHPE** [comment]
Hey @bahriaditi for this specific example only the close button is required. The guidance (not implemented within the DS site yet) can be found [here](https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=1654%3A2735). 

As for the wording on the button, whether it should be "close" or "cancel," is being taken a look at in #1873
