### ISSUE TITLE
Explore options on how we might show "advanced search" within a filter or outside of a filter.

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1762]
During a call with CCS, they provided us with a use case for a need of "advanced search"

Link:https://www.figma.com/file/cN1hsViiv7ftiKcSSKQZCl/Activity-Filter-Enhancements?node-id=1%3A106

We will have to explore the following:

Does the user recognize the difference between "advanced search" and "filtering"?

How would the user know how to use this?

Does the user know what "advanced search" is?

How would we stylize this? Where would it live?

**Comment by vavalos5** [comment]
Came across this "advanced search" in our [HPE Brand site](https://hpe.kadanza.com/kadanza/photography/all-images#/overview?category=598&search=idea) as an idea.
![Screen Shot 2021-07-30 at 11 49 39 AM](https://user-images.githubusercontent.com/62117454/127699050-f574a33b-0e28-41a9-8bbb-01029f3cc8f3.png)
![Screen Shot 2021-07-30 at 11 49 47 AM](https://user-images.githubusercontent.com/62117454/127699045-108929f6-86db-4f24-815b-a50ac6170a4c.png)

**Comment by taysea** [comment]
Closing this, recommending use of Data + friends experience. Can revisit if requirements come up again.
