### ISSUE TITLE
Define the purpose of the HPE Design System Sticker Sheet and make updates

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1763]
Clarify what the [Sticker Sheet](https://www.figma.com/file/ItdN5pNBubFpV8GP5RowY3/HPE-Component-Sticker-Sheet?node-id=58%3A40) is used for. Based on this, make updates to the Figma file in a sustainable way so that it doesn't feel like extra overhead for the future. Consider a simple sticker sheet with links to more details/ complex components and patterns.

Consider updating related documentation on site to match these updates:
https://design-system.hpe.design/foundation/designer-guidance

**Comment by bahriaditi** [comment]
After separate conversations with Chris, Greg and Vicky, I am recommending retiring the Sticker Sheet as it doesn't provide any additional value beyond the individual component files and documentation. Instead, would like to focus this time and energy on developing a 'getting started' resource which could include:

- **Figma on boarding** : HPE specific doc explaining how to build user flows using components from the design system. My understanding is that this could be a great value addition for external teams [Here's a nice example from Shopify](https://www.figma.com/community/file/994263185745279952/Figma-onboarding)
- Links to foundational components and starter templates

**Comment by ericsoderberghp** [comment]
Sounds good to me :)

**Comment by bahriaditi** [comment]
Closing this ticket since I created two new separate tickets as a result: #1799 and #1800
