### ISSUE TITLE
Research whether it is a good/bad practice to have disabled items within a checkbox group

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1773]
We have had the ask of showing disabled items within checkbox group since we offer a disabled state for checkbox. Please research best practices around this and whether it is a negative user experience to show a disabled state if the user does not know why. Write guidance to confirm direction and include in Figma file. 

If we do choose to offer disabled states, let's complete Ticket #1442

Next step would be to let devs know decision made so they can implement onto the site.

**Comment by taysea** [comment]
Closing, stale.
