### ISSUE TITLE
TextInput is different dimension than "toolbar" button, causing slight height misalignment

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1778]
<img width="524" alt="Screen Shot 2021-08-12 at 1 42 59 PM" src="https://user-images.githubusercontent.com/12522275/129267010-a3072090-94c2-41b9-a350-29275e4645c3.png">

**Comment by ericsoderberghp** [comment]
Assuming that design is to have these aligned, is this an HPE theme issue or a grommet issue? Do a bit of investigation to determine.

**Comment by britt6612** [comment]
> Assuming that design is to have these aligned, is this an HPE theme issue or a grommet issue? Do a bit of investigation to determine.

The designs have the `toolbar` button aligned with the `Textinput` 
This is off by 2px the `toolbar` button is using grommets medium default size which is `36px` however `TextInput` height is `38px` 

One solution to just change in theme is to add a `extend: height: '38px'` to just the `toolbar` button if this is intended to only be used next to `TextInput`

**Comment by halocline** [comment]
@britt6612 - Can you confirm whether this issue is related to just the toolbar button, or all buttons?

**Comment by britt6612** [comment]
@halocline yes I just connected with @vavalos5 we actually to want `36px` so the button is fine the way it is.. the problem is the `TextInput` with the `search` going to look into that now
