### ISSUE TITLE
Update disabled anchor styling on the site to match design

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1782]
- [ ] Update [disabled anchor ](https://design-system.hpe.design/components/anchor#disabled-anchor)on the site to match design
Link to Figma file: https://www.figma.com/file/I7PsiUmvr7OEJ6311rBUfg/HPE-Anchor-Component?node-id=0%3A1
- [ ] Update `base.js` to include `anchor.disabled.textDecoration`
- [ ] Update `StyledAnchor.js` to apply `props.theme.anchor.disabled`
- [ ] Update TypeScript definition
- [ ] Update grommet-site documentation
- [ ] Specify styling in grommet-theme-hpe
- [ ] Apply latest stable theme to Design System site 

Based on ticket #1751

**Comment by taysea** [comment]
Closing this is no longer relevant with the current theme version.
