### ISSUE TITLE
Export stroke versions of icons for updating on Grommet Icons site

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1783]
This ticket is a result of discussions around ticket #1750. 

---
Hi @Keeth-HPe, 

As discussed, we need to replace some of the icons on the [Grommet Icons site ](https://icons.grommet.io//)with their stroked SVG versions (instead of outline). @taysea did a quick audit to identify the icons that need replacing and I'm listing them below in this ticket.

Please use the [HPE Icons](https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=261%3A0) file to export these SVGs. Let me know if you have any questions, or if you are having trouble locating any of these icons. 

Also – I know this is a long list, so please reach out for help if you need a break :wink:

**List of icon SVGs needed:**

- apps-rounded
- ascending
- Beacon
- Blades-horizontal
- Blades-vertical
- Caret-down-fill
- Caret-left-fill
- Caret-right-fill
- Caret-up-fill
- Certificate
- Circle-alert
- Clock
- Console
- Cpu
- Descending
- Disabled-outline
- Download-outline
- Firewall
- Flows
- Gateway
- Gem
- Help-option
- Keyboard
- Memory
- Moon
- Mouse
- Network-drive
- Package
- Phone-flip
- Phone-horizontal
- Phone-vertical
- Plug
- Sans
- Script
- Sd
- Share-round
- Sun
- Switch
- Tickock
- Unsorted
- Upload-option
- Usb-key

**Comment by Keeth-HPe** [comment]
Hey @bahriaditi  I was able to export around 20 icons. (light and dark themed icons)

1. But I could not find "caret-left"  "caret-Right"  and "caret-up" . I tried to create these add them to the library and yet it isn't showing up.
2. Could not find "Certificate" icon 
<img width="260" alt="Screenshot 2021-08-16 at 6 12 50 PM" src="https://user-images.githubusercontent.com/86280029/129565883-2afe1a5a-4045-40f0-94a2-badfb529c855.png">

3.  Should I Export the "outline" version , or it this just the naming convention for the stroke version of these icon that I have to export?  
<img width="153" alt="Screenshot 2021-08-16 at 6 10 05 PM" src="https://user-images.githubusercontent.com/86280029/129565967-f5d27f45-2cc5-48df-8a52-52482d43c652.png">

4. "Ascending" shows these icons below but "descending"  includes extra option of icons, which are the right icons to be exported?
<img width="259" alt="Screenshot 2021-08-16 at 6 18 41 PM" src="https://user-images.githubusercontent.com/86280029/129566313-31a886c5-6bc0-40d4-ba40-0c35851560dd.png">

<img width="255" alt="Screenshot 2021-08-16 at 6 18 54 PM" src="https://user-images.githubusercontent.com/86280029/129566658-8b497596-7cfe-4d23-a2ae-9fd5739e3adc.png">

**Comment by bahriaditi** [comment]
@Keeth-HPe see my notes/answers below. I've set up a quick meeting tomorrow morning to go over these in person.

⚠️  Note that the icons listed in the ticket follow the naming in the [Grommet icon library](https://icons.grommet.io/?). In some cases, these names are different from the [Figma library](https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=261%3A0) (which is why you may be having trouble locating them)
- "caret-left" "caret-Right" and "caret-up": These are in the "Icons Filled (Stroke)" section of the Figma file
- "Certificate" icon: this is named differently on Figma as "license-option" _(name may need to change on Figma side)_
- "Disabled"/ "Download": please export the stroke versions of these icons _(name may need to change on the grommet side)_
- "Ascending"/ "Descending": please follow the grommet icon naming to determine which icons need to be exported:
https://icons.grommet.io/?s=descending

**Comment by Keeth-HPe** [comment]
Hi @bahriaditi, thank you for the clarification. I have exported all the icons mentioned. Please review 
[Stroke Icons svg.zip](https://github.com/grommet/hpe-design-system/files/6999416/Stroke.Icons.svg.zip)

Some of them include more than one icon, because they have more than one option in the "stroke" version, I will exclude those after your review.

**Comment by Keeth-HPe** [comment]
Hi @bahriaditi  Thank you for the clarification.
 I have exported all the above mentioned icons in SVG format. Please review. 
[Stroke Icons svg.zip](https://github.com/grommet/hpe-design-system/files/6999471/Stroke.Icons.svg.zip) I have exported

**Comment by Keeth-HPe** [comment]
Here's the updated 'compressed'
[Stroke Icons svg.zip](https://github.com/grommet/hpe-design-system/files/7005006/Stroke.Icons.svg.zip)
 folder of icons.

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe 
@taysea when you get the chance, could you test these and let us know if they work for you? Thanks!

**Comment by taysea** [comment]
Hi @Keeth-HPe @bahriaditi, thanks for the work here. I took a look at the files. I noticed the dimensions are 25 x 24 (but they should be 24 by 24). Additionally, the first few files I clicked on didn't contain a stroke/strokeWidth property which I think we want to have and there were some extraneous things with `defs` and `clipPath`. I think we'd want the exports to be a bit cleaned up if possible, but I'm not a Figma --> SVG expert to know. @ericsoderberghp in the past have icons required manual clean-ups of the exports or should all the cleaning up be automated?

**Comment by ericsoderberghp** [comment]
I have a vague memory that @alansouzati created a script to help cleanup SVGs. I think he and @L0ZZI worked on it together.

**Comment by halocline** [comment]
> Hi @Keeth-HPe @bahriaditi, thanks for the work here. I took a look at the files. I noticed the dimensions are 25 x 24 (but they should be 24 by 24).

I think what is happening is that strokes/borders can be positioned centered, inside, outside. When a path is drawn with stroke centered, and then I size my path to fit 24x24, the path line is constrained to the 24x24, but the stroke width will cause the rendered path to exceed those dimensions slightly, depending on where the path meets the edges and the stroke-width used.

![Screen Shot 2021-08-19 at 3 18 03 PM](https://user-images.githubusercontent.com/1756948/130145586-6694c9f6-3f7b-4a49-aaa9-a10c5875a996.png)

This gets exported slightly too large: 
```
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 26 26" fill="none">
    <path d="M1 1C23.1215 15.9091 -14.8607 20.2727 11.852 8.27273C33.2222 -1.32727 23.8171 15.4242 16.4433 25" stroke="black" stroke-width="2"/>
</svg>
```

I'm not sure what techniques are available to account for / constrain the centered stroke width....

**Note:** This is also exported cleanly, sans extraneous clip markup (which seems like it would be a mask of somesort). Wondering if there is an export setting applied/not-applied...? [This article speaks to a potential setting](https://help.figma.com/hc/en-us/articles/360040028114-Guide-to-exports-in-Figma#h_fee7100a-1540-4b62-bd45-e7ad6fa943b7).

**Comment by bahriaditi** [comment]
Thanks, Matt!

**Comment by taysea** [comment]
A few of the icons with stroke did not export as expected. I am attaching screenshots below where the version on top is the new export and the version below is the currently published version:

The icons included are:
- Gem
- Package
- Script
- Unsorted
- Ascending
- Descending
- CaretUpFill / CaretLeftFill / CaretDownFill / CaretRigthFill

<img width="337" alt="Screen Shot 2021-08-31 at 4 06 15 PM" src="https://user-images.githubusercontent.com/12522275/131587401-cef17ed0-a1bd-4d59-b8f0-e12ef9a320a5.png">
<img width="265" alt="Screen Shot 2021-08-31 at 12 25 38 PM" src="https://user-images.githubusercontent.com/12522275/131587403-9a11f7f8-d215-4ad5-9068-7b8b2a8aa4ab.png">
<img width="318" alt="Screen Shot 2021-08-31 at 12 24 16 PM" src="https://user-images.githubusercontent.com/12522275/131587406-bcbfff5e-6dbb-4ffc-981a-de4392e9e6b0.png">
<img width="285" alt="Screen Shot 2021-08-31 at 12 22 00 PM" src="https://user-images.githubusercontent.com/12522275/131587407-92b3b506-9b6f-4c51-aa39-4562551d37f7.png">
<img width="314" alt="Screen Shot 2021-08-31 at 12 21 36 PM" src="https://user-images.githubusercontent.com/12522275/131587410-ee8ca196-0d3e-426a-bb1a-afb4d4217aa4.png">
<img width="391" alt="Screen Shot 2021-08-31 at 12 17 32 PM" src="https://user-images.githubusercontent.com/12522275/131587411-acfdf3ff-0472-4a51-90ad-7502aab94dc8.png">


<img width="201" alt="Screen Shot 2021-08-31 at 4 09 10 PM" src="https://user-images.githubusercontent.com/12522275/131587394-60543ee4-4ce4-4f73-b7d2-41250567913e.png">
<img width="277" alt="Screen Shot 2021-08-31 at 4 07 27 PM" src="https://user-images.githubusercontent.com/12522275/131587400-73f6cff0-6297-4129-9dd0-a438b9e1b29b.png">

**Comment by bahriaditi** [comment]
@Keeth-HPe as discussed, this may be solved by exporting these icons using Object> Boolean Groups> Union selection. 
Let me know if you have any questions.

**Comment by Keeth-HPe** [comment]
[Union selection.zip](https://github.com/grommet/hpe-design-system/files/7217459/Union.selection.zip)

Hi @bahriaditi, as mentioned above, I exported the icons using Union selection.  Please review

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe! Looks fine on my end. 
@taysea: as discussed, please test these new SVG exports to see if the issue is resolved. Moving to the review column.

**Comment by taysea** [comment]
I looked at the exports and see that the svgs still have the `fill="000"` as opposed to using `stroke` and `stroke-width`.

**Comment by bahriaditi** [comment]
> I looked at the exports and see that the svgs still have the `fill="000"` as opposed to using `stroke` and `stroke-width`.

[Taylor and I resolved this over Slack]

Making a note for future exports:
This was intentional for these particularly complex icons, so that a stroke could be added on the dev side.
