### ISSUE TITLE
Should toolbar button have hover treatment consistent with secondary button?

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1784]
Toolbar button has no hover treatment, but should border grow on hover the same way it does for a secondary button?

**Comment by Keeth-HPe** [comment]
As per design system, it should have a fill attribute and not border grow. But, yes currently there is no hover treatment. It have to be implemented.  

<img width="585" alt="Screenshot 2021-08-31 at 1 54 11 PM" src="https://user-images.githubusercontent.com/86280029/131468766-d0e5c7ef-df52-4f92-9888-a691550bf7f3.png">


https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=681%3A5164

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe!
@taysea I'll close this and create an issue for implementing on the design system site so it matches what we have on Figma
