### ISSUE TITLE
Button Guidance - Should "Cancel" button in a Form/Modal be secondary or default button?

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1785]
Related to #1761 
- [ ] Make decision
- [ ] Add guidance to site

**Comment by kennytrand** [comment]
Some previous [related research](https://www.figma.com/file/vK6LH6vXfdK7euQ7AmEgr4/Components%2C-Templates-%26-Guidelines?node-id=1619%3A65084) done by CCS

**Comment by vavalos5** [comment]
@kennytrand to work w/ Keeth on this as it is related to ticket #1601

**Comment by Keeth-HPe** [comment]
Hi @vavalos5,
After researching and also discussing use cases with the Indian team, here's what looks like an ideal solution to whether "cancel" should be a secondary or Default button:
https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4063%3A9258.

**Comment by vavalos5** [comment]
Thanks @Keeth-HPe I left a few comments on the Figma file. 😄

**Comment by vavalos5** [comment]
V1 completed. 
V2 to come next week in #2083
