### ISSUE TITLE
Button Guidance - What is button row responsive behavior in a form/modal?

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1786]
Once "small" breakpoint is hit, should buttons in a row wrap? stack to single column? if so, does primary action go first or last?

- [x] Make decision
- [x] Add example and guidance on site

**Comment by vavalos5** [comment]
Adding a screen shot on how Ezmeral team is doing this. Their examples are responsive to screen size and order of buttons.

![Screen Shot 2021-10-06 at 12 32 46 PM](https://user-images.githubusercontent.com/62117454/136271821-95c089c5-617a-4b88-9f0c-ee989f3f0b10.png)

![Screen Shot 2021-10-06 at 12 33 23 PM](https://user-images.githubusercontent.com/62117454/136271773-3aca35a3-7488-4380-ab22-49333540cb66.png)

**Comment by bahriaditi** [comment]
Hi @taysea @ericsoderberghp this looks like it is done: https://design-system.hpe.design/components/button#responsiveness

Figma: https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4713%3A9473

If you agree, we can close this ticket

**Comment by ericsoderberghp** [comment]
I believe we are done with this, but leaving it for @taysea in case she has some extra details I don't.

**Comment by taysea** [comment]
Yep we are done there!
