### ISSUE TITLE
Button Guidance - Add clear guidance on button positioning for forms, filters, and layers

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1788]
Related https://github.com/grommet/hpe-design-system/issues/1704 - This issue should follow resolution of #1704

There have been repeated questions around if buttons should be left-aligned or right-aligned in Forms/Wizards and whether the primary action comes first or last in a group of buttons. We have provided in the moment feedback to folks but there is no section on the Button page/different page to point to.

To-do:
- [ ] Add example and guidance to site

**Comment by KennyAtHPE** [comment]
Add clear guidance for the following pages:

- [ ] Buttons page
- [ ] Layers page
- [ ] Forms page
- [ ] Filters page
- [ ] Wizard page

Additionally, #1601 is for adding examples on these pages

**Comment by vavalos5** [comment]
Thanks Kenny, I'll take a look :)

**Comment by vavalos5** [comment]
Think we're good to close this too? @KennyAtHPE

**Comment by KennyAtHPE** [comment]
@vavalos5 is this not already closed?

**Comment by vavalos5** [comment]
LOL! i meant to put this comment in issue #2048
