### ISSUE TITLE
Order of Items Example - List data should be top-aligned

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1790]
Slack thread - https://hpe.slack.com/archives/C04LMJWQT/p1629231480089100

![image](https://user-images.githubusercontent.com/1756948/129800566-9b590d3c-df40-44d5-990a-dd9144c4636a.png)

**Comment by britt6612** [comment]
This is a combination of work in `Grommet` as well as `Hpe-theme`

The work will be tracked in two broken out issues that will complete the following:

- [ ] align needs to be added in for a prop or theme to be able to `align start` in Grommet
- [ ] utilize new prop/theme added to grommet to align start for List

**Comment by ericsoderberghp** [comment]
I think this makes more sense as a prop than in the theme. The alignment is primarily driven by the type of content within the list items, so I think the place where the list item rendering is done is where we should handle this, in the JSX props.

**Comment by britt6612** [comment]
> * issue her

Since we are going to enhance grommet to use a prop the second part of this ticket would  be to 
utilize that prop in this example  https://design-system.hpe.design/templates/lists#item-order

- [ ] Update list example in design system to use new prop to align text
