### ISSUE TITLE
Page Layouts

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1794]
Exploration

- [x] discuss with Ephraim, Scott, etc.
- [x] #1829

Ideation
- [x] #1830
- [x] #1912
- [x] #1994 
- [x] #2054
- [x] #2055
- [x] #2381
- [x] #2296
- [x] #1966
- [x] #2177
- [x] #2216
- [x] #2288

Implementation
- [x] #1831
- [x] #1658 
- [x] #2135 
- [x] #2178 
- [x] #2193
- [x] #2291

Test / Gather Feedback
- [x] #2179 

grommet Development

- [x] #2334

Design System site Development
- [x] #2426
- [x] #2427

Figma
- [x] #2428

**Comment by bahriaditi** [comment]
Meeting Ephrem next week on Wed (8/25). Stay tuned!

**Comment by bahriaditi** [comment]
Connected with both @ericsoderberghp  and Ephrem this week. Based on my notes below, I will be creating more issues to tackle each action item.

cc @halocline 

**Summary of discussions + action plan:**
- The Design System/ Grommet currently uses a CSS Grid + Flexbox approach allowing for more complex page layouts
- This allows us to move away from a device/viewport-specific mentality
- Good idea to begin page layout guidance by defining block level elements and their semantic value on a page
- Define a max, min width for content
- Define breakpoints (sm,md,lg) which will provide a framework for designers to consider and test their page layouts
- Define margins based on these breakpoints to avoid content being too close to the browser/device edge
- Collect use cases: What are some common page layouts being used across HPE platforms (beyond CCS)
- Finally, create template for these common use cases

**Comment by bahriaditi** [comment]
Reopening and moving to inspiration point :)
