### ISSUE TITLE
Table - How to show multiple row level statuses

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1796]
Scott Oja and I had a long conversation on how to show multiple statuses within a table. Here are the designs he's been working on: https://www.figma.com/file/tJu86S9nx4tY6p7POYQclQ/settings-properties?node-id=215%3A1016

Here is another examples where two attribute columns need to  provide statuses

https://www.figma.com/file/pheHQxOuuHrPF3VP8phqe9/CSU-SW-v.2?node-id=50%3A5666

i think one fo the problems is that there is terminology that could be confusing such as "status" and "state". He was wondering if we had anything along these lines. However, since we don't I thought it would be great for us to look into the taxonomy survey Greg and Kenny created, and leverage to provide guidance. 

It would also be good to see how other teams are doing this, best practices and how it would make the best sense to display for visually impaired users who use screen reads.

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/hpe-design-system/issues/1612

**Comment by vavalos5** [comment]
#1807 is also related

**Comment by KennyAtHPE** [comment]
Adding onto this ticket:
- Exploring combining status and state within a table to save real estate from having two different columns. 
- Might have to update status indicators alongside tables depending on conclusion

**Comment by ericsoderberghp** [comment]
I think this is related to 2b in https://github.com/grommet/hpe-design-system/issues/1855#issuecomment-922116509. Where there are separate columns for particular attributes and one could consider those attributes as having a status indicator associated with them. For example, if the item is your refrigerator, there might be a column for the door, showing open or closed, and a column for the internal temperature. If the door is open, perhaps warning icon would be associated with it. If the temperature is too high, perhaps a warning icon would be associated with it. In both cases, I think it would be important to make if clear that the status icon is a sort of badge tied to the specific attribute value. However, I could see a filter showing all refrigerators with anything of note, which would result in showing those that had the door open OR too high a temperature.

**Comment by bahriaditi** [comment]
Checked in w @KennyAtHPE and seems like this is dependent on #1920 (continuation of #1855)
Moving this back to To do - since this could be worked on in parallel/ after (but not before)

**Comment by taysea** [comment]
Closing, we've capture this in status indicator guidance.
