### ISSUE TITLE
Create a 'Figma getting started' guide to create awareness around tool best practices when using component libraries

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1800]
This will help serve the following needs:

- Alleviate any tool-related blockers to the adoption of the design system within HPE

- Create awareness around how best to leverage component libraries

- Could include an index of links to individual component libraries (TBD)

Here's a nice example from Shopify: https://www.figma.com/community/file/994263185745279952

Tasks include:
- [x] Finalize content sections (what will a skeleton for this guide look like?)
- [x] Review with @bahriaditi and @vavalos5 
- [ ] Design V1 (low fidelity)
- [ ] Review with team
- [ ] Design V2 (high fidelity)
- [ ] Publish to library + create ticket to link on design system site

**Comment by bahriaditi** [comment]
@Keeth-HPe for this week, please focus on finalizing the content flow for this guide. Keep in mind that the audience for this guide will include designers of all levels within HPE and in some cases, developers as well.

You can reference this starter guide draft started by @vavalos5 in addition to the external link in the description: https://www.figma.com/file/ehx1youYYwuaGasfwTbkNK/Figma-Basics?node-id=0%3A1

**Comment by bahriaditi** [comment]
@Keeth-HPe will continue work on this next week (See subtasks in description).

**Comment by Keeth-HPe** [comment]
Hi @bahriaditi,
I have written content for all the topics, however, I have a couple of questions in the file, whether the guidance has to be about how to use the existing style/variant of HPe or to create them from scratch?  Please do take a look : https://www.figma.com/file/ehx1youYYwuaGasfwTbkNK/Figma-Basics?node-id=509%3A305

**Comment by bahriaditi** [comment]
Closing this so we can track the subtasks through smaller tickets
