### ISSUE TITLE
Explore adding sizing options for text input and select components (dependent on #1306)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1801]
Ticket created from [this Slack thread](https://hpe.slack.com/archives/C04LMJWQT/p1629809829107200) started by @revanth.sreedhar@hpe.com

Should we consider adding button sizing based on [Tshirt sizing](https://design-system.hpe.design/foundation/tshirt-sizing)?

Grommet and [Grommet Designer](https://designer.grommet.io/) offer sizing flexibility, so it may be a good idea to reference capabilities there before creating design guidelines  on the Figma/ Design system side.

**Comment by vavalos5** [comment]
This ticket is relatable to ticket #1306 

We had discussed adding t-shirt sizing buttons with the appropriate icon size so that the height of the text and icon are aligned in-line.

I think we should probably break this ticket into 3 as well since they're 3 different components

**Comment by bahriaditi** [comment]
> This ticket is relatable to ticket #1306
> 
> We had discussed adding t-shirt sizing buttons with the appropriate icon size so that the height of the text and icon are aligned in-line. We just hadn't gotten around to it.
> 
> I think we should probably break this ticket into 3 as well since they're 3 different components

Good point @vavalos5 and thanks for connecting the dots there - My thinking is that we can keep it as one ticket to "explore" whether we need sizing options for all since they are related and most likely will end up having the same sizing options?

**Comment by vavalos5** [comment]
Good call!

**Comment by taysea** [comment]
Closing due to lack of specific use cases.
