### ISSUE TITLE
Menu Component in DS works irregular in Chrome browser.

### ISSUE THREAD

**Issue by bhim-dutta-chaurasia** [grommet/hpe-design-system#1803]
### URL - 
https://user-images.githubusercontent.com/73303084/130920730-e6210bc4-e59b-478e-8b5e-73612975bd15.mov

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version: Chrome Version 92.0.4515.159 (Official Build) (x86_64)
- Operating System and version (desktop or mobile):  macOS Big Sur Version 11.5.2 (Desktop)

**Comment by taysea** [comment]
Hi @bhim-dutta-chaurasia, can you go to this link and open the "Our Platforms" menu and let me know if you see the same lag? https://developer.hpe.com/

I am trying to see if this bug is specific to the DS site or more general to the Grommet Menu/Drop component

**Comment by halocline** [comment]
@taysea Here's the [Slack thread](https://hpe.slack.com/archives/C04LMJWQT/p1629731320095000?thread_ts=1629726593.094300&cid=C04LMJWQT) with additional context.

**Comment by taysea** [comment]
Thanks @halocline! Think it'll still be helpful for Bhim to confirm if he's seeing the same funky behavior on the HPE Developer site just as one other use case in a more complex site like DS site

**Comment by taysea** [comment]
Closing, this behavior is not occurring.
