### ISSUE TITLE
Finish up cleaning up icons in Figma for stroke/fill aspects

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1804]
From #1783 :
"There are few icons left behind and not exported : (Firewall, share-round, help option, Phone flip, phone-horizontal, phone-vertical, switch and usb-key) because some of them have fill attributes and not stroke attribute. Few icons have have mixed stroke levels so it's unlikely to be flattened as it does not remain in the same shape."

@Keeth-HPe can you please list all the icon names here that need attention? This will help us keep track of them in the future.

**Comment by taysea** [comment]
Closing, will handle with icon refresh from Chris's rework.
