### ISSUE TITLE
Specifically for showing small status icons with messaging, consider slightly larger icon sizing

### ISSUE THREAD

**Issue by eddieshowcase** [grommet/hpe-design-system#1809]
### Is this issue related to the design system core library or design system website?

Yes... was asking for recommendations around small status icon sizing with respect to showing status messaging in a status column in a DataTable. See Slack thread here: https://grommet.slack.com/archives/C04LMJWQT/p1630076749013100?thread_ts=1629998995.002700&cid=C04LMJWQT

### Actual Behavior

HPE DS team originally recommend we use 'small' icon sizing for this use case. However the small sizing of 12x12, especially for diamond and triangle appear way small (resulting vectors are more like ~9px).

<img width="129" alt="Screen Shot 2021-08-27 at 9 40 27 AM" src="https://user-images.githubusercontent.com/7239901/131153320-a6cf47f1-1aae-4ccf-b390-baaa92d1e604.png">

### Expected Behavior

Our dev team implemented a custom 16x16 icon size for this use case as we felt "small" was way too small and default "medium" icon size was way too big. Our 16x16 result looks better like this (resulting vector sizes are ~12-13px and more proportional to text:

<img width="143" alt="Screen Shot 2021-08-27 at 8 57 40 AM" src="https://user-images.githubusercontent.com/7239901/131152092-0c7ae1a9-d624-457f-a8e3-d58136a50c74.png">

### Your Environment

- Design System version:
- Grommet version: 2.17.4
- Grommet icons version: 4.6.0

**Comment by vavalos5** [comment]
Wondering if we still want to consider since we did change our icon sizes recently due to the brand refresh. As long as this isn't interactive, I don't believe the icon size matters.

**Comment by taysea** [comment]
Closing because icon sizes have been updated in v5 to address this.
