### ISSUE TITLE
Come back to the Design System Survey Created and create action items on how we can improve our process of working with other teams

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1823]
A while back, I had created a Design System survey where it was sent to multiple teams to gather feedback on why it's been hard or easy for them to use the Design System, why it's easy or hard working with us, what we can improve on, who they can go to for questions.

I think as a next step, we can either go off of it and create action items, or since we've progressed, we can create another similar one and then come up with a problem statement. From there we can create actions items to improve our process with other teams.

As the company is trying to transform, the Design System is a big part of that. This will help us to get to that 100% adoption :)

**Comment by taysea** [comment]
Closing, stale.
