### ISSUE TITLE
Update What's New Page 9/17

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#1834]
A place to collect updates that will be published to the Design System What's New page every other week. Comment on this issue with updates you think should be published on the What's New page.

Once the page has been updated at the end of 2 weeks, this issue will be closed and a new issue opened for the next 2 weeks.

---------

- Enhanced List to support vertical alignment and added guidance for multi-line lists (https://github.com/grommet/hpe-design-system/pull/1853)
- Fixed display of DataTable cells when in dark mode (https://github.com/grommet/grommet-theme-hpe/issues/206)
- Fixed Calendar accessibility by announcing the dates which have been selected (https://github.com/grommet/grommet/issues/5429)
- Added "rounded home" icon to Grommet Icons (https://github.com/grommet/grommet-icons/issues/247)
- Ensured Select component meets "do not nest interactive elements within a button" requirement (https://github.com/grommet/grommet/issues/5501)
- Advanced Design System site search capabilities. Work in progress.
- Aligned Toolbar Button hover implementation with Figma (https://github.com/grommet/hpe-design-system/issues/1818)
- Fixed unintentional line break bug in Markdown component (https://github.com/grommet/grommet/issues/5486)
- Fixed theme to ensure button and field input heights are the same dimensions (https://github.com/grommet/hpe-design-system/issues/1778)
- Completed research on "task focussed navigation" (https://github.com/grommet/hpe-design-system/issues/1742)
- Added guidance for toggle icon buttons (https://github.com/grommet/hpe-design-system/issues/1685)
- Allow DataTable checkboxes to be pinned (https://github.com/grommet/grommet/issues/5449)

**Comment by britt6612** [comment]
Add new guidance to mutli-line lists..https://github.com/grommet/hpe-design-system/pull/1853

**Comment by halocline** [comment]
I went through our archived issues and added relevant ones to the list above. We should see if there are any missing and also provide links to content where appropriate (e.g. "added guidance to ...",)

**Comment by jcfilben** [comment]
Great thanks for adding those @halocline

I can double check if we are missing anything and add links when needed

**Comment by vavalos5** [comment]
- Completed a usability test on toggle buttons and sortable columns within a table utilizing a user who uses a screen reader.
- Enhanced a11yText on our light/dark mode button on our [HPE Design System home page](https://design-system.hpe.design/)
- [Ideation on Navigation](https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1279%3A1206) coming to a finish.
- Completed adding t-shirt sizing for buttons.Figma publishing coming soon!
- Aligned RangeInput component to Grommet. Figma file coming soon!

**Comment by jcfilben** [comment]
- Enhanced [List](/templates/list-views) to support vertical alignment and added guidance for multi-line lists.
- Advanced Design System site search capabilities. Work in progress.
- Aligned Toolbar Button hover implementation with [Figma](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=681%3A5164).
- Completed research on [task focused navigation](https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1%3A18).
- Added guidance for [toggle icon buttons](/components/button).
- Completed a usability test on toggle buttons and sortable columns within a table utilizing a user who uses a screen reader.
- Enhanced a11yText on our light/dark mode button on our [HPE Design System home page](https://design-system.hpe.design/).
- [Ideation on Navigation](https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1279%3A1206) coming to a finish.
- Completed adding t-shirt sizing for buttons. Figma publishing coming soon!
- Aligned RangeInput component to Grommet. Figma file coming soon!

Here is the list I have. I removed some of the items related to grommet, theme enhancements, or grommet-icons so that the what's new page only includes strictly design-system updates since this seemed like how the previous updates were done.
