### ISSUE TITLE
How to show state and status within a table

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#1855]
Matt mentioned that Positano had a question on how state and status should be presented within a table.

Example:
![Screen Shot 2021-09-13 at 1 50 35 PM](https://user-images.githubusercontent.com/1756948/133147505-3b78cbcc-6ea8-47b2-ab11-96f6c3a31897.png)

They also mentioned that having separate columns for both state and status takes up too much real estate. Currently collecting use cases and ideating on different ways that state and status can be presented.

**Comment by KennyAtHPE** [comment]
Related to [#1796 ](https://github.com/grommet/hpe-design-system/issues/1796)

**Comment by halocline** [comment]
> Matt mentioned that Positano had a question on how state and status should be presented within a table. Their current designs can be found here: https://www.figma.com/file/S8mS2mWREnIdmaRzl2Kgyd/Positano---June-Release?node-id=3839%3A38193
> 
> They also mentioned that having separate columns for both state and status takes up too much real estate. Currently collecting use cases and ideating on different ways that state and status can be presented.

The question/request actually emerged from Ezmeral team in this [Slack post](https://hpe.slack.com/archives/C04LMJWQT/p1630001535010100?thread_ts=1629998995.002700&cid=C04LMJWQT), so it'd be good to grab use cases from Ian Erickson and the Ezmeral team as well.

**Comment by KennyAtHPE** [comment]
Through watching @vavalos5's interview with Bill, I noticed that he was having a difficult time understanding what the Status column was trying to display. For instead when hovering over it, it would just say "good" which doesn't really tell the user anything especially for someone using a screen reader. Furthermore, this breaks the current guidance on [status indicators ](https://design-system.hpe.design/templates/status-indicator) since the status indicator doesn't have any attached content with it. 

I'm proposing that the State and Status columns could be combined under one column instead. Therefore, when tabbing over said column it would present the user with "status is good, the server is currently running" rather than just "status is good." My inclination is that this column would be called "State."

**Comment by MikeKingdom** [comment]
Be careful about assuming State and Status are directly related. Ie. the State may not determine the Status. I've been involved with different projects that determine the status from a larger set of things related to the object (e.g. does the object have any open alerts?). In many cases, the status is simply "Hey you need to look at me" or "I'm fine." Some things can have many different states and could be green, yellow, red or gray in the same state. Especially when portrayed in a table, you would want the ability to sort or filter based on one or the other. If they are combined, that would be much more awkward.

**Comment by KennyAtHPE** [comment]
Had a great discussion with @MikeKingdom on this issue. 

**Summary of why combining the two columns wouldn't work:**
- Removes the ability to filter each column independently
- Could be even more confusing for users with screen readers (ex. the cell could read "Status is critical, State is server is running." This is not a 1:1 connection and could make the user second guess what's actually the Status/State)
- Tables aren't meant to showcase the entire problem anyways other than providing a quick preview/indicator. Being told that the "Status is critical" is a good enough indication that the user should open up this specific cell 

**Things to explore:**
-  Could there be any alternative to provide the user with more context within the Status column?
- Are there specific use cases in which combining the two columns would be okay? Even so, should this be practiced?
- Should the columns within the table be adjacent to one another?

**Comment by vavalos5** [comment]
This might close ticket #1877 if you come to a conclusion :)

**Comment by KennyAtHPE** [comment]
> **Things to explore:**
> 
> * Could there be any alternative to provide the user with more context within the Status column?
> * Are there specific use cases in which combining the two columns would be okay? Even so, should this be practiced?
> * Should the columns within the table be adjacent to one another?

- As long as the requirements are met for status indicators (shape, color, and content) this would be provide enough context.
- No, these columns should be separated. Instead the content for the status indicator could be better written, to provide more context of the actual issue.
- No, does not have to be.

**Comment by KennyAtHPE** [comment]
[Table Design System page](https://design-system.hpe.design/components/table#table-behaviors-and-actions) has a perfect example for this currently. No changes on that page need to be updated, just some guidance within Figma.

**Comment by vavalos5** [comment]
Looks great Kenny! Left 2 comments on the Figma file.
We'll have to pair up with a developer + create a ticket to make changes on the deign system site as next steps

**Comment by halocline** [comment]
A few items I want to make sure we have answers to / covered in the analysis and recommendations:

From [Slack discussion](https://hpe.slack.com/archives/C04LMJWQT/p1630001535010100?thread_ts=1629998995.002700&cid=C04LMJWQT): 
"Thanks for sending the staging links. Overall looks really good. I think you should/need to show use of status indicator plus messaging in a table or datatable. We have many use cases of this and breaking up ‘state’ and ‘status’ into two columns everywhere is not going to fly well with designers in terms of eating up real estate in a table."

- [ ] Per the above quote, have we collected use cases from Ezmeral? Can we use those use cases to test the recommendation?
- [ ] Though there is a sound argument that status and state should not be dictated to be combined, are there scenarios where they may be combined? Should we demonstrate / contrast the two types of scenarios?
- [ ] How should state and status be displayed in within limited real-estate (e.g. smaller laptop or mobile screens -- we should make sure our designs cover the range of device view ports)? In limited real-estate, are there scenarios where they can be presented together? Should one trump the other (i.e. if I had to choose one over the other to display, which should be displayed and why)?
- [ ] This may be handled in another issue, but should we provide guidance for how the status indicator icons should read to a screen reader?

**Comment by vavalos5** [comment]
@halocline to your last checkbox, there's a ticket in the backlog similar to what you're implying Ticket #1877

**Comment by KennyAtHPE** [comment]
Contacted Ian Erickson a couple of days ago for use cases from Ezmeral, currently waiting for a response. I Will follow up next week.

Additionally, opened up #1888 off of a discussion Matt and I had on his points above.

**Comment by ericsoderberghp** [comment]
A few thoughts ...

I can see several scenarios here:

1) A lot of reasons could be driving a particular status, or there is no formal concept of "state" for a particular item. In these cases, it could make sense to have a single status column with some secondary text that provides a bit more detail about "why" the status is what it is. For example, if the item is your home security system, the status might have a warning icon and be accompanied by some text saying "garage door is open".

2) There is a formal concept of state. In this case the state should likely be its own column, allowing for sorting and filtering based on the possible discreet values.

2a) There is also a formal concept of status. In this case, status should be its own column.

2b) There isn't a formal concept of status. I actually wonder if in this case it might make sense to use a status icon as a secondary indicator for the state. For example, if the item is your garage door, the state might be "open" and it might have a warning status icon next to it. Just thinking out loud on this one.

**Comment by KennyAtHPE** [comment]
Reached out to Rajiv Kaul from the Ezmeral team for some use cases.

**Comment by bahriaditi** [comment]
Checked in with @KennyAtHPE and sounds like the research phase/ collecting different use cases is competed (including from Ezmeral). Closing this ticket, creating a new one to focus on creating examples for different scenarios.
