### ISSUE TITLE
Banner Notifications

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#1859]
Figma Link: [Banner Notifications](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=2118%3A4676)
[Latest page outline for DS site
](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=3231%3A12029)

- [x] #2352 
- [x] #2364 
- [x] #2387 
- [x] #2366 

## Global Banner

- System generated (never user action/task generated)
- Acknowledge/Dismissible/View Details 
- Display type - inline
- If dismissed, tracked by Notification Center: ? TBD
- Important system messages can be dismissed by current user for remaining session, redisplay on next log-in? 

## Section Banner

- User action/task generated -
- Action required/Dismissible (optional close icon)/View Details
- Actions - 1.n - inline anchors (short/terse), default buttons, CTA/secondary buttons (max 2 actions + ‘x’ close icon)
- Display type - overlay
- If dismissed, tracked by Notification Center: yes
- If user actioned upon the banner, tracked by Notification Center : maybe - depends upon the type of action?

## Page Level Banner

- System and User action/task generated, communicates page state - form input validation, stale data, etc.
- Persisted/actionable/dismissible
- Display type - inline
- If dismissed, tracked by Notification Center : no
- Page level alert notifications contextual to data collections, forms, wizards
- Inserted inline under the page header in a reserved container
- Possible support for form level validation, page level validation, data collection notifications ‘stale data’, provide managed object status
- Possible Dependencies - tied to Page Header pattern work that Kenny is owning

## prior structuring, left for reference

**Exploration**
- [x] #1860
- [x] #1861

**Ideation**
- [x] #1862
- [x] #1863
- [x] #1864
- [x] #1865
- [x] https://github.com/grommet/hpe-design-system/issues/2364
- [x] #2387 

**Implementation**
- [x] #1866
- [x] #1867
- [x] #1868

**Comment by KennyAtHPE** [comment]
CCS is currently working on designs for error state banner notifications and Ephrem reached out asking for any current research/designs that we had.

**Comment by ericsoderberghp** [comment]
Also, add guidance for when and when not to use banner notifications, tied to https://github.com/grommet/hpe-design-system/issues/1169

**Comment by eddieshowcase** [comment]
Here is how we currently define and use banner messaging/notifications:

<img width="987" alt="Screen Shot 2022-02-09 at 11 55 26 AM" src="https://user-images.githubusercontent.com/7239901/153270463-5b17b636-a372-4b78-b840-d2304e049198.png">

<img width="1327" alt="Screen Shot 2022-02-09 at 11 54 38 AM" src="https://user-images.githubusercontent.com/7239901/153270468-8f59f0d5-9530-4473-8523-af18f858fcab.png">

**Comment by ericsoderberghp** [comment]
We are in a reasonable state with banner notifications for now. We will open new issues to address future work as needed.
