### ISSUE TITLE
Banner Notifications - Review existing use cases and temporary solutions

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1860]
Currently looking over designs done by CaaS, GLC Platform, GLC, MCC Platform, CA Health Checks, Nimble, & CCS

Lots of different designs and use cases, so may need to schedule some meetings with designers from these teams to get a better understanding of what each platform needs. Currently leveraging interviews and other notes collected previously for Toast Notifications.

All collected use cases can be found here: 

https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=1%3A14

**Comment by ericsoderberghp** [comment]
Superseded by #2352
