### ISSUE TITLE
Banner Notifications - Research external solutions and accessibility guidelines

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#1861]
Collecting and understanding requirements from WCAG and NNG. A lot of this has already been collected previously for Toast Notifications found here: 

https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=1%3A6

Link above also contains guidelines from other design systems and misc. sites. Specific use cases arising from (Reviewing existing use cases and temporary solutions) may need to be furthered explored.

**Comment by ericsoderberghp** [comment]
Superseded by https://github.com/grommet/hpe-design-system/issues/2352
