### ISSUE TITLE
Banner Notifications - How might we layout Banner Notifications on the Design System site

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#1865]
Create content to be presented on the Design System site. 

Work for this would be found here: 
https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=1354%3A1784

**Comment by KennyAtHPE** [comment]
I'm thinking that the page layout would be something like this (with examples in between):

- When should you use a Banner Notification?
- Anatomy/Different types of Banner Notification
- Content
- Placement
- Accessibility
- Persistence
- Variants

**Comment by ericsoderberghp** [comment]
Superseded by https://github.com/grommet/hpe-design-system/issues/2352
