### ISSUE TITLE
Code Blocks - Add a page with guidance

### ISSUE THREAD

**Issue by derekhchen** [grommet/hpe-design-system#1870]
Related PRs:
- [Site](https://github.com/grommet/hpe-design-system/pull/1903)
- Theme:
    - [Approach A](https://github.com/grommet/grommet-theme-hpe/pull/214)
    - [Approach B](https://github.com/grommet/grommet-theme-hpe/pull/215)

### Is this issue related to the design system core library or design system website?
I'd imagine it's mostly design system website since it'll just be guidance on which 3rd-party tool to use unless it'll be built straight into Grommet. 

### Expected Behavior

We need a way to display code snippet that will update some values based on user input in the UI.

### Actual Behavior

Nothing, we don't have this in our guidance yet.

### URL, screen shot, or CodeSandbox exhibiting the issue

https://www.figma.com/file/Ou9nGClJ0auVKhHsNWysPg/API-Gateway?node-id=1109%3A14130
![image](https://user-images.githubusercontent.com/38574571/133464628-03bfc452-2a21-4b31-957f-c105599adf45.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
For this, I am thinking we would:
- [ ] pick a particular formatter, perhaps rainbow, highlight.js, or prism?
- [ ] create an appropriate stylesheet for it and publish it
- [ ] add a page to the design system website
- [ ] add any guidance, for instance: scrolling behavior

**Comment by jcfilben** [comment]
I looked into `react-syntax-highlighter` (this is what they are using on [developer.hpe.com](https://developer.hpe.com/)). It gives you the option to use either highlight.js or prism, use one of their themes or create your own.

My thoughts so far are we should have an option for light and dark modes. We should include guidance on when to wrap lines and when to include line numbers.

Below is an option using highlight.js a11y-dark theme for dark mode and a11y-light for light mode. Next step is I would like to talk to a designer about the theming (@bahriaditi @vavalos5). I would like to discuss if we should use one of the built in themes (like the ones shown below) or if we need to create a custom theme.
<img width="861" alt="Screen Shot 2021-09-21 at 11 58 05 AM" src="https://user-images.githubusercontent.com/54560994/134223055-12aeb5c8-1487-4d06-bc70-40950b944bff.png">
<img width="863" alt="Screen Shot 2021-09-21 at 11 58 36 AM" src="https://user-images.githubusercontent.com/54560994/134223121-125bf1b6-613a-44ed-8458-3261be1fb618.png">

**Comment by vavalos5** [comment]
As discussed, I can connect w/ you on this tomorrow @jcfilben during the PRty
