### ISSUE TITLE
Button - Language for buttons within layers/forms/modals/side drawers

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#1873]
![image](https://user-images.githubusercontent.com/86075038/164564280-ca7bc048-d0d2-445e-8184-377a7a4c5799.png)

Some confusion on what language should be used for primary buttons within layers/forms/modals/side drawers. Is this something we need to define and write guidance on or is this more up to the designers and devs?

A similar question arose from the Page Header work around whether or not there should be guidance on what common verbs can be used for menu buttons  #2368 

@CitizenFox is also working on something similar with realigning and creating consistency in our terminology and general language

**Comment by CitizenFox** [comment]
In my mind, we can write fairly direct button language guidance for layers/forms/modals/side drawers (I'll call these LFMSDs for short) for these two scenarios:

1) The LFMSD allows the user to perform an action. In this case:
- The primary button reiterates the LFMSD's task as a verb, most commonly as create, update, delete.
- A noun can be added to the primary button's verb if there's any ambiguity regarding what the user is acting on.
- A secondary button is always provided to give users a safe way to step back from an action. This is typically displayed as "Cancel" but may take other forms. 

2) The LFMSD displays read-only information. In this case:
- The primary button should be the only button present and have the text "Close" to show that no action, other than closing the LFMSD, is being performed.

Those are my rough initial thoughts BUT there are almost always exceptions so we can iterate as needed. Like with UI elements, it's really helpful to collect live examples to test our guidance against. 

Thoughts?
