### ISSUE TITLE
Table - enhance so screen reader reports x-number of results retrieved

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1876]
During a small usability test with Bill Tipton, we received great feedback on how he'd expect the screen reader to say how many results were retrieved after searching for a specific item within a table.

As next steps:

- [ ] we need to further understand what that a11yText would look like 
- [ ] make changes to the design system site

**Comment by taysea** [comment]
Closing, a screen reader announcement is made with Data + friends to indicate how many results are shown.
