### ISSUE TITLE
Change description on status icons's a11yText from saying icon name to a description of what it symbolizes

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1877]
During our small usability test with Bill Tipton, we received feedback that he did not know what was being described when on the "status good small" icon. Instead of the screen reader describing the name of the icon, it should describe what that graphical element symbolizes.

We should research this and enhance.

Below is an image of where we came across this issue + [DS site link](https://design-system.hpe.design/templates/filtering#filtering-with-selectable-results):

<img width="476" alt="Screen Shot 2021-09-15 at 1 45 58 PM" src="https://user-images.githubusercontent.com/62117454/133507282-5123acf0-aef3-42ec-8b9f-4c8dd5e63ded.png">

**Comment by KennyAtHPE** [comment]
My thoughts on this are that all status indicators within tables should have the following three elements to satisfy WCAG requirements:
- Shape
- Color
- Content
Within this example, the status indicator would need to be accompanied by the term "good" for it to meet these requirements. 

As for screen readers, I believe that the cell should only say "status good" omitting the icon size. When taking this into context, the user would know what these statuses imply. "Good" means nothing to see here, while "Unknown" and "Critical" would be enough to alert the user to go into that specific cell and check the actual problem.
