### ISSUE TITLE
Layer - add more examples

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#1887]
The Layers page is currently missing many use cases such as but not limited to:
- [ ] Filtering within layers
- [ ] Confirmation Modals
- [ ] Forms within Modals
- [ ] Filters within Modals

Some of these can actually be found within other pages (ex. filtering within layers can be seen within the Filtering Page), however, I believe having them all within one place or at least providing direct links to these pages would make this overall page seem more like a one-stop-shop. 

In addition, it is missing guidance on:
- [ ] Overflow behavior within layers (guidance for overflow for filters within layers can already be found [here)](https://design-system.hpe.design/templates/filtering)
- Other missing guidance can be found here: #1851

**Comment by eddieshowcase** [comment]
Screenshots for how Ezmeral team is styling and using titles, subtitles, and descriptive text in Modals and Drawers:

<img width="989" alt="Screen Shot 2022-03-30 at 9 28 27 AM" src="https://user-images.githubusercontent.com/7239901/160872783-e68f186d-0b38-45d4-94d8-2b4970a8489e.png">

<img width="472" alt="Screen Shot 2022-03-30 at 9 27 58 AM" src="https://user-images.githubusercontent.com/7239901/160872787-3d3046cc-1a8c-4a1b-89e4-486df5aa995f.png">
