### ISSUE TITLE
Enhance RangeInput

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#1901]
After looking at `RangeInput` in the design system there was a few things that we can enhance in Grommet to make the component better aligned with figma.

- [x] #1908
- [x] #1909
- [x] #1910
- [x] #1911
- [ ] Make an example in Figma of a real use case that we would have internally

<img width="745" alt="Screen Shot 2021-09-22 at 4 26 32 PM" src="https://user-images.githubusercontent.com/42451602/134430172-41c1b120-10d3-4ba8-a66b-9c8ad18461f4.png">

**Comment by taysea** [comment]
Closing, stale.
