### ISSUE TITLE
PropertyList - review grommet component API with staff

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1904]
Review API approaches started on the following PRs:
- Approach 1: Box drives layout https://github.com/grommet/grommet/pull/5623
- Approach 2: Grid drives layout https://github.com/grommet/grommet/pull/5626

**Comment by ericsoderberghp** [comment]
Can we also look at a flavor that is more markup based? For example:
```
<NameValueList>
  <NameValuePair>
    <NameValueName>Model type</NameValueName>
    <NameValueValue>MXQ83700F3</NameValueValue>
  <NameValuePair>
</NameValueList>
```

or, with alternate naming:
```
<PropertyList>
  <Property>
    <PropertyName>Model type</PropertyName>
    <PropertyValue>MXQ83700F3</PropertyValue>
  <Property>
</PropertyList>
```

or, with other alternate naming:
```
<DefinitionList>
  <Definition>
    <DefinitionName>Model type</DefinitionName>
    <DefinitionValue>MXQ83700F3</DefinitionValue>
  <Definition>
</DefinitionList>
```

**Comment by ericsoderberghp** [comment]
Here's another approach, still markup but a different flavor that can be more compact. It still allows a lot of flexibility in the value but simplifies the name/label as that is less likely to need flexibility.
```
<DefinitionList>
  <Definition label="Model type">MXQ83700F3</Definition>
</DefinitionList>
```

**Comment by britt6612** [comment]
I can look into this 👍

**Comment by ericsoderberghp** [comment]
I think we should also look at some real-world data where we take a real Javascript object and then create the List from that data. I'm wondering whether it feels better to transform the object into a `data` array and pass as a prop or to do it with markup. Especially if other parts of the page are being rendered via markup and using the object directly elsewhere.

**Comment by MikeKingdom** [comment]
> Here's another approach, still markup but a different flavor that can be more compact. It still allows a lot of flexibility in the value but simplifies the name/label as that is less likely to need flexibility.
> 
> ```
> <DefinitionList>
>   <Definition label="Model type">MXQ83700F3</Definition>
> </DefinitionList>
> ```

Personally I like this a lot. This really would have worked well for how I would have wanted to use it in previous products.

In the cases I can think of I wouldn't have been wanting to do it with a data attr.

**Comment by britt6612** [comment]
closing this first pass of API for NameValueList
