### ISSUE TITLE
Page Layouts - Identify common templates and use cases

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1912]
Based on research done in #1829 + [Eric's work on Grommet designer](https://designer.grommet.io/?id=page-layouts-eric-soderberg-hpe-com):

- [x] Identify common, overlapping use cases so they can be grouped into different types of layouts (single column page, two column page, three column page, page w table, page w table and sidebar, wizard single column, wizard two column, dashboard, custom dashboard etc.)
- [x] Review with team to validate groupings
- [ ] Create design guidelines for each page layout type

**Comment by ericsoderberghp** [comment]
I think we need to focus on a few key page layouts tied to what Maggie and Ephraim have been working on.

**Comment by bahriaditi** [comment]
Did a mini share out with the Design System team. General consensus is to focus on these page layouts categories in order of priority:

1. Dashboards
2. Wizards
3. Lists
4. Tables
