### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1919]
@gregfuruiye is exploring UX designs for tags based on needs arising on the Compute platform.

Members from the Design System team will collaborate with Greg and shadow key stakeholder meetings to facilitate the development of this component (@vavalos5 + @MikeKingdom)

**Figma file with Greg's designs:** https://www.figma.com/file/ow8t09chbbp9IiXcWVguXA/Tags?node-id=20%3A5736

Tickets:

- [x] #1925 
- [x] #1930
- [x] #1940 
- [x] #1960 
- [x] https://github.com/grommet/grommet/issues/5777
- [x] #2044 
- [x] #2131 
- [ ] #2172 
- [ ] #2165 
- [x] #2161 
- [x] #2155

**Comment by vavalos5** [comment]
Greg and I chatted this morning to walk through the progress he has made. Research is completed. Currently he is in ideation mode and exploring different ways to style and group tags.

**Comment by eddieshowcase** [comment]
Thought I would add a few screenshots of use cases we have or examples to consider. Considering using tags/pills/badges for our Host "tags" and will be in a Table.
<img width="1220" alt="Screen Shot 2021-10-01 at 12 29 13 PM" src="https://user-images.githubusercontent.com/7239901/135681068-44179205-c0fb-4edd-9be1-395063a51301.png">
<img width="1177" alt="Screen Shot 2021-10-01 at 12 28 28 PM" src="https://user-images.githubusercontent.com/7239901/135681072-9db1eb29-d877-4f09-9be0-b2a6ae410eef.png">
<img width="1206" alt="Screen Shot 2021-10-01 at 11 53 43 AM" src="https://user-images.githubusercontent.com/7239901/135681075-b8822ada-80ea-4e51-ad7a-19b7e0d92074.png">

**Comment by eddieshowcase** [comment]
We are considering using tags/chips/pills/badges (whatever you call them) for our Host tags...
<img width="1392" alt="Screen Shot 2021-10-01 at 2 16 21 PM" src="https://user-images.githubusercontent.com/7239901/135681271-d0c391de-2c06-46b5-9433-b60602464ff4.png">

**Comment by vavalos5** [comment]
Will be setting up time w/ Ian to further understand some of these use cases

**Comment by vavalos5** [comment]
Was ticket #2020 deleted? I saw it was added to this ticket above...@ericsoderberghp @MikeKingdom

**Comment by ericsoderberghp** [comment]
Closing this issue as the primary use cases are completed. The few remaining issues related to additional examples will be handled separately.
