### ISSUE TITLE
Text Input - Design guidance on displaying actions to modify or interact with input (ex: copying or revealing content)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1924]
This came up during Design System Office Hours. 

CCS is looking for guidance around when the input has a button to copy it (screenshot attached from related [Slack chat on ccs-ux](https://hpe.slack.com/archives/C016NNY4TA9/p1633025944061800))

<img width="235" alt="Screen Shot 2021-09-30 at 11 22 51 AM" src="https://user-images.githubusercontent.com/87677275/135894195-f11082b8-5984-48a9-bb3a-c431825d4f2a.png">

**Comment by vavalos5** [comment]
Brought up during GLCP Crit on 6/27 and in a Slack conversation this morning.

[Figma file](https://www.figma.com/file/9JDPwHsK6dnut8HWXtsdOb/branch/1GmOWvQBhlmyMbftWww0Xr/API-Management?type=design&node-id=4600-57162&mode=design&t=jA5GFSpIFby6YPrV-0)

[Slack conversation](https://hpe.slack.com/archives/C04LMJWQT/p1687878630362069)

Example Edgar provided:
![Screen Shot 2023-06-27 at 11 12 01 AM](https://github.com/grommet/hpe-design-system/assets/62117454/5a4eb027-81dc-41b1-b715-e17b94ee1258)

**Comment by vavalos5** [comment]
Helpful link I found: https://blog.prototypr.io/3-ways-to-copy-to-clipboard-5077f5774b55

https://www.patternfly.org/v4/components/clipboard-copy/design-guidelines/

https://chakra-ui.com/docs/hooks/use-clipboard

https://chakra-ui-git-fix-typescript-autocomplete.chakra-ui.vercel.app/docs/hooks/use-clipboard

https://cloudscape.design/components/copy-to-clipboard/

**Comment by taysea** [comment]
Closing, have added `readOnly` and ability to copy: https://design-system.hpe.design/components/textinput?q=text#readonly
