### ISSUE TITLE
Button Guidance - Add Guidance and update examples for how to close a Layer

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1926]
- [x] Update all Layer examples to align with new guidance around how to close a layer
- [x] Add/Adjust written guidance on site

Guidance + example changes can be found [here](https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=2%3A14).
This ticket stems from #1761

**Comment by KennyAtHPE** [comment]
CCS recently asked for guidance on this specific issue. Pointed them to this [research](https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=1654%3A2735) until the DS site is officially updated.
