### ISSUE TITLE
Icons - Enhance icon meta names to match more typical usage

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1934]
This discussion came up during Design System Office Hours.

Review current naming of icons and see if there is a way to align these with common terminology used across teams (ex: “health”, “configuration”, “firmware” etc.) 

**This will help:**
- Encourage use of the icon library ([Grommet](https://icons.grommet.io/?) and [Figma](https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=582%3A6))
- Avoid using different icons for the same purpose

- [ ] research additional common names, likely interviewing Edgar, others
- [ ] create an issue in grommet-icons with guidance from the research findings

**Comment by bahriaditi** [comment]
@ericsoderberghp should the research part of this ticket be "in progress" given that Chris Conetta is actively working on this?

**Comment by ericsoderberghp** [comment]
#2171 is now the overall big things issue. This issue was used to track the initial research to identify the core icon set and the icon and name variations currently in use.
