### ISSUE TITLE
Figma Guide - Design V2 (high fidelity)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1935]
Based on #1800 
Create a final design in Figma that we can publish in the Figma library and link on the site.

**Comment by Keeth-HPe** [comment]
Hi @bahriaditi ,
 Here is the completed prototype of [Figma guide](https://www.figma.com/proto/ehx1youYYwuaGasfwTbkNK/Figma-Guide?page-id=425%3A284&node-id=846%3A1435&viewport=334%2C48%2C0.09&scaling=scale-down&starting-point-node-id=644%3A590). Please review and share feedback. Thanks!

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe! This is looking really good. Jeff, Vicky and I reviewed this collectively this morning. I am happy to walk you through our feedback later this evening (your Thursday morning:). I'll ping you for a quick check in.

**Comment by jeffstolz** [comment]
HI @Keeth-HPe great work - I'm going to go through the copy today and make some updates

**Comment by vavalos5** [comment]
Great changes @Keeth-HPe and @jeffstolz. 🎉 I left a few minor comments on the Figma file. Other than that, it's ready to come to the finish line. It's like 99.99% done lol!

One thing I noticed was that we had periods on every single sentence including bullet points and steps. I think sentences is fine, but i'm thinking it's a bit much and probably not necessary for bullet points and steps. Maybe just a nit-picky thing. @bahriaditi what do you think? I added examples below to reference what I mean: 
<img width="542" alt="Screen Shot 2021-11-16 at 3 17 06 PM" src="https://user-images.githubusercontent.com/62117454/142081828-5fe203b0-8d85-4704-ab8f-3ac26eaef0bd.png">

<img width="388" alt="Screen Shot 2021-11-16 at 3 18 44 PM" src="https://user-images.githubusercontent.com/62117454/142081825-11b36a92-0171-4baf-bdc4-50d547b1a633.png">

**Comment by KennyAtHPE** [comment]
@Keeth-HPe @jeffstolz just left some comments on the Figma file. Overall looks super awesome and I learned a thing or two going through it :)

**Comment by vavalos5** [comment]
Thank you @Keeth-HPe I left 1 last comment. Once that's done, you can close this. Good job!

**Comment by bahriaditi** [comment]
> Great changes @Keeth-HPe and @jeffstolz. 🎉 I left a few minor comments on the Figma file. Other than that, it's ready to come to the finish line. It's like 99.99% done lol!
> 
> One thing I noticed was that we had periods on every single sentence including bullet points and steps. I think sentences is fine, but i'm thinking it's a bit much and probably not necessary for bullet points and steps. Maybe just a nit-picky thing. @bahriaditi what do you think? I added examples below to reference what I mean: 
>

agreed!

**Comment by Keeth-HPe** [comment]
Thank you @vavalos5  I agree on that too. I have excluded using 'periods' from the bullet points and steps. It looks better now:)

**Comment by bahriaditi** [comment]
Link to completed guide:
https://www.figma.com/file/ehx1youYYwuaGasfwTbkNK/Figma-Guide?node-id=425%3A284
