### ISSUE TITLE
Tags - Connect w/ Greg to review progress & update team

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1940]
Connect w/ Greg to find out progress
Share w/ team on progress + any Qs

**Comment by ericsoderberghp** [comment]
A few comments ...

I notice from the research that Carbon and Material both have single term tags, not key+value. key+value seems to be coming primarily from an Azure context in the research.

I see the need for allowing the end user to be able create their own key+value pairs to align with their usage context and to allow richer filtering. For example, it is easier to ask "show me everything without a 'location' key" using the key+value structure.

I think we should eventually allow both flavors. I can see the simpler case being either "label", to align with GitHub, or "tag" to align with Material and Carbon. Perhaps the key+value flavor could be called a "structured tag"?

The need for the user to be able to create and manage them seems to be orthogonal to how they are represented when being used. The PatternFly "chip group" seems to be more oriented to being used in a filtering context and not when labelling an individual item. I'd like to understand more about whether these are expected to be used for filtering, in which case the ability to show which values are being filtered on and being able to clear individual values seems completely separate from the ability for a user to create custom key+value tags.

Or, are these expected to be used more to decorate individual items to make it easier to scan and visually group them, which also seems separate from the need for the user to be able to create custom key+value tags.

So, I see at least three scenarios in play here, all of which seem orthogonal to one another:
1. how to indicate a key aspect of individual items, this could be a user created key+value tag, a simple tag, or some out-of-the box attribute
2. how to show currently applied filters and allow an in-place means of removing them, this also seems like it could apply outside of the domain of #3 below.
3. a mechanism for the end user to create custom key+value or simple tags for individual items or groups of items.

I'm not sure that they always all go together.

From reading the "Requirements" section of the research, the third scenario seems to be the most important one. The visualization and interaction aspects seem to focus more on #2 but without considering a non-structured-tag possibility. For scenario #2, why is this being strictly tied to #3? Where are the current design system filtering guidance and templates insufficient? If they are insufficient, I'd rather see #2 in a more generic context of overall filtering, not just within the context of #3.

The term "tag" seems to apply most directly to the first scenario, where it is most strongly associated with the item itself, akin to a luggage tag.
