### ISSUE TITLE
How might we implement a requests button to the design system site?

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1947]
From the [Design System Retro Share Out](https://www.figma.com/file/FVqKLHf3TjLwoboUD2WJPl/Design-System-Process-Workshop?node-id=0%3A1), stakeholders are asking for a button to be implemented onto the design system site so that it is easier for them to make component requests, page design reviews etc..

Let's go back to stakeholders and ask about what specifically they're asking for when it comes to this button. 

Are they asking for a way to make comments and requests on the site itself? Are they asking for a a simple one click and fill in information for requests type of solution?

Once we've gathered more information, let's create a ticket on next steps so we can make this happen.

**Comment by ericsoderberghp** [comment]
Already have "Leave Feedback" at the bottom of each page with a variety of ways to express requests.

Expecting this to be superseded by #1645
