### ISSUE TITLE
How might we educate other teams on design system related information?

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1948]
There has been a big ask from the [Design System Retro Survey](https://www.figma.com/file/FVqKLHf3TjLwoboUD2WJPl/Design-System-Process-Workshop?node-id=0%3A1) on learning about new components, new documentation, how to contribute to the design system, etc.. This is something we hear a lot from teams.

The designers are already working on a Figma file that will be [showing HPE specific example gifs](https://www.figma.com/file/ehx1youYYwuaGasfwTbkNK/Figma-Basics?node-id=425%3A284) on how to use certain areas of Figma.

However, as a team, we need to ask around on what specifically teams would like to see/learn from us.

Is it quarterly lunch and learns?
Is it videos on how to use a component? 
Is it guides?

We may want to do some A/B testing too. For example, if people want videos and guides, let's test which one does better so we know where to spend more of our time on. We don't want to create something people aren't going to use/watch. So lets learn whether either videos or guides are easier to follow.

**Comment by ericsoderberghp** [comment]
Related to #1874

**Comment by taysea** [comment]
Closing, stale. Will reopen if necessary.
