### ISSUE TITLE
Follow up with Edgar on How might we statement voted on from DS Retro Workshop

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1951]
Reach out to Edgar to get a better understanding on what he meant by his How might we statement...
<img width="317" alt="Screen Shot 2021-10-13 at 2 03 53 PM" src="https://user-images.githubusercontent.com/62117454/137212317-230fb36c-5399-4e37-a17b-2b0d1220d434.png">

- [x] Gather feedback
- [ ] Make any necessary tickets
- [x] Report back to team

**Comment by MikeKingdom** [comment]
I think the biggest thing that will help here is collaboration. Product teams are always going to develop components to help achieve patterns they use the most. We want to provide what the pieces they need to do so and they can also contribute back to grommet. The key will be collaborating to stay on the same page and move forward in both spaces.

Note also that saturn components are being deprecated and the goal is to move more and more to Grommet components. A direct quote from Ryan Collins yesterday:

> The basics is that Saturn UI are the components we've had to build in order to fill the gaps of the design system/grommet so that our service teams aren't all duplicating work and coming up with inconsistent solutions.  We have a new major version coming out soon that eliminates "most" of those components.  Our goal is to ultimately fully rely on Grommet / the Design System and we have been working with the Design System Council on that goal."
