### ISSUE TITLE
Update aries-site dependencies

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#1954]
Currently we had to revert back our `"prismjs": "1.24.0",` to use `1.24.0` 
Upgrading to `1.25.0` was causing our project to break. I have a issue in their backlog that we can track. Trying to recreate the issue in `codesandbox` so we can link in issue. 

https://github.com/PrismJS/prism/issues/3154

**Comment by jcfilben** [comment]
Closing since we no longer have prismjs as a dependency on aries-site
