### ISSUE TITLE
Icons - Make icon names consistent between Grommet and Figma to reduce confusion between dev and design

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1957]
**From @halocline  (via Slack)**
"In Figma, I see both ‘home’ and ‘house’ icons, but in the published library this is only an outline of ‘house’ and a solid of ‘home’ ?

We also noticed that the ‘cluster’ icon in Figma is the ‘nodes’ icon in the grommet library, and what is currently the ‘cluster’ icon in the grommet library doesn’t seem to exist in Figma? My devs/designers were asking which they should use as the discrepancy leads to a mismatch between design/dev.

While I can use the Figma icons for the ‘source of truth’, the problem is that we can’t implement those icons in development…. unless we do manual exports of the SVGs… which I guess isn’t that big of a deal for a few icons… but would be good to have a ‘dev’ ticket to update the grommet library."

This is an ongoing challenge for us. I'm realizing that this may be because of the open source nature of Grommet and the many contributors involved. Two action items for this:

- [ ] Audit Grommet and Figma library to surface inconsistencies in naming
- [ ] Make decision to either change in Figma or Grommet
- [ ] Have parity with metadata on both sides as well
- [ ] Brainstorm a way to create some checks in place to avoid these types of conflicts in the future

-----------------------------------------------------
[Current list of Icons](https://hpe-my.sharepoint.com/:x:/p/ojas_srivastava/ERz6_l0NNtNGi52iwx6kAicBvrLOhMzJHwKwKh7ouCFLmg?e=eDaccF) that Ojas has audited.

Related tickets [Missing Icons in Figma](https://github.com/grommet/hpe-design-system/issues/2766), [Missing Icons in Grommet](https://github.com/grommet/grommet-icons/issues/279)

**Comment by bahriaditi** [comment]
Noting that this work should happen after Chris Conetta's research on icon naming. He is currently working on normalizing 'core' icons between services.

**Comment by vavalos5** [comment]
He's doing a share out today on a column icon study. Did you want to be in that?

**Comment by bahriaditi** [comment]
> He's doing a share out today on a column icon study. Did you want to be in that?

Thanks for the heads up Vicky – I don't think I need to attend especially if you will be there to listen in :)

**Comment by saggiemilva** [comment]
Does this issue cover the case for icons that are in the Figma library but not in Grommet? Otherwise I will submit a new issue to make sure all icons are available in both places.

**Comment by bahriaditi** [comment]
@saggiemilva good question! This ticket is limited to naming of icons only. So yes, a new ticket will be much appreciated!

**Comment by jcfilben** [comment]
Here is a link to the metadata which lists all the grommet icon names and what terms they can be searched by

https://github.com/grommet/grommet-icons/blob/master/src/js/metadata.js

**Comment by KennyAtHPE** [comment]
Related to #2622

**Comment by KennyAtHPE** [comment]
Oja's Contributions:

**Applies for both Light and Dark modes**
- [ ] Rename "Technology / connect" to “Technology / action”
- [ ] Rename "Filled / apps" to "Filled / rounded-apps" (2x2 icon)
- [ ] Rename "Office / calendar-option" to "Office / plan"
- [ ] Rename "Technology / camera" to "Technology / webcam"
- [ ] Rename "Misc / license-option" to "Misc / certificate"
- [ ] Rename "Status / Disabled to "Status / Disabled-outline"
- [ ] Add metadata to applicable icons.

**Comment by taysea** [comment]
Closing, will be addressed in future with icon refresh.
