### ISSUE TITLE
Create Testing Guidance

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#1959]
Tracking issue to create Testing guidance for Grommet

- [x] Share out with the team to discuss testing guidelines and decide which ones should be enforced on Grommet.
- [x] Create a draft of testing info to add to the contributing guide under the 'testing your code' section.
- [x] Create a checklist related to testing best practices for reviewers to go over when checking PRs.
- [x] Update the pull request template testing section to include info about testing best practices.
- [x] Update the tests for a component to follow the best practices so we can reference those tests as examples
- [x] Enable the eslint-plugin-testing-library gradually, rule by rule.

**Comment by ericsoderberghp** [comment]
I think we can add sub-tasks/issues for many of the items above.

I'm wondering if we are primarily linking to an external document for the rest of the suggestions whether we need our own separate testing guidance document or whether we can just beef up https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md#testing-your-code a bit. Perhaps we can start with a first pass there and separate it out if it starts getting too long.

**Comment by jcfilben** [comment]
Closing, all tasks in the issue description have been completed.

Note: an ongoing item related to this issue is to gradually enable the eslint-plugin-testing-library on more files as tests are enhanced to follow guidance. Currently the  eslint-plugin-testing-library is only active on the Accordion testing file.
