### ISSUE TITLE
Tags- Connect w/ Greg and discuss finalizing designs to hand off to devs

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1960]
- [x] Connect w/ Greg to get a better understanding on design approaches + examples
- [x] Greg to clean up Figma file and [move to this Figma file](https://www.figma.com/file/8zrInotU4JK9LWP4WyZy25/HPE-Design-System-Tags?node-id=2%3A11) as it will then be located into our Design System Figma folder
- [x] Greg to give me variants to hand off to Mike 
- [x] Greg to create examples to include onto DS site + hand off to Mike
- [ ] Greg to create guidance to hand off to Mike

**Comment by vavalos5** [comment]
@ericsoderberghp Will Tags be an actual Grommet component or just a simple template on the design system site? (cc: @MikeKingdom)

**Comment by vavalos5** [comment]
Eric, Greg and myself chatted earlier on the variants, naming and examples. Eric has approved variants. Greg is cleaning up and will be sending again for implementation. Examples and guidance to follow

**Comment by MikeKingdom** [comment]
> @MikeKingdom While i'm OoO next week, can I leave you in charge of this ticket? Please connect with @gregfuruiye to discuss the rest of deliverables 😄

@vavalos5 Certainly
