### ISSUE TITLE
Page Layouts - Dashboard (Explore)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1966]
Based on #1912, design template options for Dashboards

Deliverables:
– Research use cases across HPE product experiences
– Categorize and define types of dashboard layouts

**Comment by bahriaditi** [comment]
Moved to 'To do' because I didn't get to work on it this week :/

**Comment by bahriaditi** [comment]
@Keeth-HPe hoping you can use any remaining time this week to help me move forward on this ticket.

Can you conduct preliminary research on the following topics:
- Definition & purpose of a Dashboard 
- Recent dashboard use cases & designs from HPE team members in India

**Please document your findings here:** 
https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Layouts?node-id=2012%3A16377

Thank you!

**Comment by Keeth-HPe** [comment]
@bahriaditi  yes sure! Will begin work on it.

**Comment by Keeth-HPe** [comment]
@bahriaditi  

- [ ] Definition & purpose of a Dashboard
- [ ] Recent dashboard use cases & designs from HPE team members in India

Documented the findings in the file, please take a look. The Indian team had only one use case & design. No one, (except one) worked dashboard yet.  But tried to collect some examples. 👇

https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Layouts?node-id=2012%3A16377

**Comment by bahriaditi** [comment]
Closing this issue with the note that I will tackle 'Defining types of dashboard layouts' in the Ideation phase (ticket #2177)
