### ISSUE TITLE
Text Input - Update Figma "finished" page with example of an "optional" field

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1968]
Based on #1712, we need to update the [text input component](https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=0%3A1) on Figma to include two new variations: Enabled/Required and Enabled/Optional

cc @vavalos5

**Comment by Keeth-HPe** [comment]
@bahriaditi , I have added dark version now. Thank you!

**Comment by vavalos5** [comment]
Hi @Keeth-HPe Aweesomeeee job!! My only comment would be to have the same description text you have in light mode match in dark mode. I noticed there were some information missing. Other than that, looks good!

**Comment by Keeth-HPe** [comment]
@vavalos5 Yes!  I've added that description text. Thank you !!

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe  - all looks good, closing this ticket with one last comment:
I changed the naming from "Text Input/Enabled/Required" to "Text Input/ Required"

<img width="185" alt="Screen Shot 2021-10-21 at 11 43 15 AM" src="https://user-images.githubusercontent.com/87677275/138337888-442784cf-ed2f-42e8-994b-0133896f6d65.png">
