### ISSUE TITLE
Synthesize themes from Design System Workshop to articulate next steps

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1974]
https://www.figma.com/file/FVqKLHf3TjLwoboUD2WJPl/Design-System-Process-Workshop?node-id=0%3A1

- [ ] Create clusters of themes like we did for the FigJam file the India team had provided. 
- [ ] Include next steps
- [ ] 
**Common themes:**
- Office Hours
- Needs Discussion
- Direct Responses
- Design System Backlog

**Comment by taysea** [comment]
Closing, stale.
