### ISSUE TITLE
Design Token - Discuss with team and stakeholders on a dedicated Design Tokens Page

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1976]
I was just doing some browsing and noticed many design systems have 1 dedicated page where Design Tokens live. Rather than having numerous of different areas where styles live, it would be great to have all of these elements live in a single page.

Before we take any actions. It would be great to have a chat here in the Design System team and consult with stakeholders on how valuable this would be for them.

Idea came from the following articles:
https://blog.prototypr.io/design-tokens-with-figma-aef25c42430f
https://uxdesign.cc/design-tokens-for-dummies-8acebf010d71

Design Systems with Design Tokens:
https://designsystem.digital.gov/design-tokens/
https://www.lightningdesignsystem.com/design-tokens/
https://spectrum.adobe.com/page/design-tokens/
https://www.duetds.com/tokens/
https://shopify.github.io/polaris-tokens/
https://www.carbondesignsystem.com/guidelines/themes/overview/

**Comment by taysea** [comment]
Closing, recent design tokens documentation tickets have been filed to capture this.
