### ISSUE TITLE
Name-Value List - Publish component and variants to Figma library

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1990]

**Comment by bahriaditi** [comment]
@vavalos5 before I publish to the library, could you please glance over this Figma file and review the components I created?
https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/HPE-Name-Value-Pair?node-id=2%3A93

Thank you!

**Comment by vavalos5** [comment]
Looks fantastic @bahriaditi! I left a few comments in terms of how some of the text strings are wrapping and icons.

I also made one small change to one of the containers that wasn't 96px (XS) in width for ya :)

**Comment by bahriaditi** [comment]
Thank you @vavalos5 - you're the best 🏆

**Comment by jcfilben** [comment]
Closing, looks like this issue was moved to 'Done' but never closed
