### ISSUE TITLE
Typography - Offering additional weights for MetricHPE (other than regular and bold)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1995]
From Slack thread with Geetha Priya Padmanaban (Ezmeral): https://hpe.slack.com/archives/C04LMJWQT/p1634932007014800

In terms of action items, @halocline summed this up nicely:

We have the font files for these and they are already part of the HPE theme. I think the main items are:

- [ ] What guidance and application use cases do we want to provide/support? (e.g. I believe our FormField labels and values already use medium)

- [ ] Enable in Figma

**Comment by taysea** [comment]
Closing, we support the standard range of font-weights.
