### ISSUE TITLE
Form - Add IP/HOST/Network setting validation logic to one of our form validation examples

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1998]
Matt Muggeridge shared this validation approach for IP/Host/Network settings inputs.

Consider if this is something we'd like to add to make it more shareable or if there is a better venue for sharing.

If we do implement, reply to the Slack thread with link to example to close the loop and express gratitude.

https://hpe.slack.com/archives/C04LMJWQT/p1635379845045600?thread_ts=1635349541.039000&cid=C04LMJWQT

**Comment by ericsoderberghp** [comment]
I'd suggest reading through the slack thread and determining what would be helpful to add to the design system site examples. The `validator` example isn't aligned well with how grommet form validation works, which wants to be per-field. I'm also wondering whether the `validator` package is what we'll always want to recommend or whether there might be a few common cases we should just include inline and then add a reference to `validator` as another option.

**Comment by taysea** [comment]
Closing, stale.
