### ISSUE TITLE
Card - Drag and Drop

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2001]
This card has also come from a request from the India team. This came from the FigJam Retro file:
https://www.figma.com/file/MkQZjhZNstTJS6MyfTKzFZ/DS-queries?node-id=0%3A1

**Next steps:**

- [ ] Request and collect Use Cases to further understand needs
- [ ] Best Practices
- [ ] Accessibility
- [ ] NNG
- [ ] Understand Keyboard  + mouse behaviors
- [ ] Understand Interactions such as on hover, drag & drop

**Comment by jcfilben** [comment]
Closing, work can be tracked in https://github.com/grommet/hpe-design-system/issues/3492
