### ISSUE TITLE
Skeleton Loading- Implement to the design system site

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2003]
Raja had created skeleton screens here: https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Loading-Indicator-Component?node-id=221%3A17108

which have not been included into the design system site. The India team has requested this from a retro done w/ them. 

Please implement into the design system site.

**Comment by jcfilben** [comment]
Closing, a Skeleton page has been added to the design system site.
PR: https://github.com/grommet/hpe-design-system/pull/3077
Page: https://design-system.hpe.design/components/skeleton
