### ISSUE TITLE
FileInput- Add trash icon to Validation variant in Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2015]
Per a conversation in office hours, it came to our attentions that we are currently not showing a trash icon on the Validation variant. It would make sense to implement the trash icon should the user not want to attach an item if the form field isn't requiring it.

Please add a trash icon in the validation example in Figma located here: https://www.figma.com/file/8HwAiiSDloOTjUxqvCTypq/HPE-FileInput-Component?node-id=1164%3A43348

**Comment by halocline** [comment]
For issue https://github.com/grommet/hpe-design-system/pull/2017, I've implemented a validation example on the Design System site to complement the Figma work. 

[PR here](https://github.com/grommet/hpe-design-system/pull/2061)

[Demo here](https://deploy-preview-2061--keen-mayer-a86c8b.netlify.app/components/fileinput#fileinput-validation)

**Comment by vavalos5** [comment]
- [ ] Create validation w/ trash for light and dark mode

- [ ] Create a section on the right named: When a new file has been added and it needs validation

**Comment by Keeth-HPe** [comment]
Hi @vavalos5, Both the tasks above are completed. 
Leaving space for description under the "[When a new file has been added and it needs validation](https://www.figma.com/file/8HwAiiSDloOTjUxqvCTypq/HPE-FileInput-Component?node-id=0%3A1)" section. Not sure what to add there.

**Comment by vavalos5** [comment]
Looks good @Keeth-HPe I left some comments on the file.

First question, you bring up a good point! The description text is optional but I'm wondering if we will want to add an example on the site @halocline? Let us know if we should add a ticket in the backlog.

Second question. The name in the container should technically be the name of the file that was attached. The text below is letting the user know why the file was not able to be uploaded.

**Comment by Keeth-HPe** [comment]
@vavalos5 I have added a section for 'Multiple files Validation' as per the Design system site and changed the main component as well. Please do a review. Thanks
