### ISSUE TITLE
Forms guidance does not match examples + broken link

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/hpe-design-system#2016]
### Is this issue related to the design system core library or design system website?

Website: https://design-system.hpe.design/templates/forms

### Expected Behavior

Forms page has broken link and guidance does not match sample code.

### Actual Behavior

Two issues:

1. The examples do not match the guidance for `required`
    a. Guidance states: `For login/registration forms, apply required={{ indicator: false }} to the FormFields to remove the required indicator.` The samples with login/registration do not use `required={{ indicator: false }}`.  This makes it very easy to miss.
2. You have a dead link 
[Forms where 'asterisk' and 'optional' can be skipped](https://design-system.hpe.design/forms#sign-in)

Bonus points for supporting site-search matching for "Login" and "Sign".

### URL, screen shot, or CodeSandbox exhibiting the issue

https://design-system.hpe.design/templates/forms

### Steps to Reproduce

As above.

### Your Environment

N/A.

**Comment by britt6612** [comment]
@LiveFreeAndRoam 

> The samples with login/registration do not use required={{ indicator: false }}. This makes it very easy to miss.

I went through the `signUp` and `signIn` examples in which are using the `required={{ indicator: false }}.` I wasn't sure which example you were referring to that did not include this?

**Comment by LiveFreeAndRoam** [comment]
There may be other cases... two examples are ResetPassword and Change Password.

**Comment by britt6612** [comment]
@LiveFreeAndRoam thank you I will fix these!
