### ISSUE TITLE
Possible terminology change for Status and State

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2019]
A lot of confusion between Status and State has been causing inconsistencies between platforms and within the Design System. A couple of reasons for this are:

- Status and State are too similarly worded and users often forget which is which
- A third terminology, "health," has often been associated with these two (health and status have commonly been used synonymously within some platforms)
- Guidance on the differences between the two hasn't been very widespread

This terminology issue is mostly affecting issues revolving around DataTables and Notifications

[Current Guidance](https://design-system.hpe.design/components/notification#state-vs-status)
Related to #1972

**Comment by ericsoderberghp** [comment]
Superseded by https://github.com/grommet/hpe-design-system/issues/1612
