### ISSUE TITLE
DataTable - Consider simplifying status content

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2020]
Current guidelines state that all Status Indicators require 3 out 4 components to meet accessibility guidelines
- Color
- Shape
- Icon
- Accompanying content

This research was done originally for notifications, however, could Status Indicators be displayed differently within DataTables? One suggestion is to cut the content and to just display an icon with a11y text. This would help save on screen real-estate 

Related to #1972

**Comment by taysea** [comment]
Closing as stale, will continue with our current recommendations based on accessibility requirements.
