### ISSUE TITLE
DataTable - add guidance for empty states

### ISSUE THREAD

**Issue by jeffstolz** [grommet/hpe-design-system#2022]
Add guidance for how to render cells that have no content in them, both to Figma and to the design system site examples and guidance.

**Comment by jeffstolz** [comment]
Created from the attached conversation in Figma
<img width="319" alt="Screen Shot 2021-11-04 at 4 50 54 PM" src="https://user-images.githubusercontent.com/2924479/140418171-b2ff60bc-ec63-4f21-9c6e-98d03a7f17c9.png">

**Comment by taysea** [comment]
We have implemented this: https://design-system.hpe.design/components/datatable?q=table#handling-empty-cells
