### ISSUE TITLE
Lists Navigation - Ideation

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2036]
Started doing some thinking about the different types of List Navigation.

 https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1997%3A11919

**Comment by vavalos5** [comment]
Ready for review: https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1647%3A9622

Guidance is very close to what Card has

![Screen Shot 2021-11-16 at 4 10 24 PM](https://user-images.githubusercontent.com/62117454/142085950-ce6966b6-0e1b-48a7-967d-ad410ecbf10e.png)

**Comment by vavalos5** [comment]
Jeff and I got together and cleaned up the CArd, List and Table guidance/when to use as it was identical and made it more generic. Here's the new look: https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1997%3A11919

![Screen Shot 2021-11-17 at 9 43 31 AM](https://user-images.githubusercontent.com/62117454/142253844-a9a15e88-6ec7-48e7-921d-229b66ea8663.png)

**Comment by ericsoderberghp** [comment]
I've added some comments in Figma. I do think we can clean up the graphics just a bit.
