### ISSUE TITLE
Guidance on Date/Time formatting

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2039]
Do we want to provide guidance around how dates and times should be formatted? For example, locale / does time include seconds? does it mark am/pm ? is it "zero padded" (01/03/21)?

**Comment by ericsoderberghp** [comment]
Yes, we want to.

**Comment by MikeKingdom** [comment]
I'm sure it's context dependent (like if you're scheduling something that needs seconds.)
We should always be handling it internally as an Date object or an ISO 8601 string (just the zulu version). Anytime it's displayed it should be done with the browser locale and timezone specific functions to get their preferred am/pm and day, month, year ordering etc. We shouldn't have to really care about timezones or such internally.

**Comment by ericsoderberghp** [comment]
I suspect we will have a variety of flavors here for different contexts.

**Comment by vavalos5** [comment]
Closing since we're addressing it in #2463
