### ISSUE TITLE
Reverse Navigation - Exploration

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2041]
Should you always show a back button to go back to the previous page? Do we want there to be explicit guidance to have a back button?

Should reverse navigation be mentioned together w/ "Drill Down" or should it be it's own Navigation? Is there a clear differentiator between the two of them? If they are together, how do we make it clear?

Is the "home" or "logo" a form of "reverser navigation"?

**Comment by ericsoderberghp** [comment]
I'd suggest that this be re-oriented towards "context navigation". In other words, someone can send me a deep link to a page and I can see what this page's "parent" is and I can navigate to that when I choose. So, it's not really a "back" button but more of a "where is this page contained" button.

I think "home" or "logo" can be a "context navigation" control.

**Comment by vavalos5** [comment]
Closing as it is a duplicate. Can be tracked in #1652
