### ISSUE TITLE
Guidance around how to visually indicate missing value in NameValueList / other contexts

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2042]
When a value in a Form is empty and we are displaying data in a NameValueList, if there is not a value for a given field, do we want to display as "--" or something else?

As of now we've been using "--" as that has been seen in other designs/we have been using.

- [ ] Establish guidance
- [ ] Implement on design site

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/hpe-design-system/issues/2022

**Comment by taysea** [comment]
We have implemented this already: https://design-system.hpe.design/components/namevaluelist?q=nameval#name-value-pair-with-empty-value
