### ISSUE TITLE
Tags - Examples + Guidance

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2044]
As a part of the work that Greg has done on Tags, he will be creating examples and guidance on how to use the different types of tags he has created. This ticket is to track that issue.

**Comment by vavalos5** [comment]
Greg to be working on this today or tomorrow :)

**Comment by gregfuruiye** [comment]
Here is a first draft of documentation with some rough examples from Compute:  https://www.figma.com/file/ow8t09chbbp9IiXcWVguXA/Tags?node-id=5437%3A19816

**Comment by gregfuruiye** [comment]
Hey guys, I moved the draft version of the guidance from my CCS design file to the Design System Tags file to keep things together.  Here's the updated link to the guidance: https://www.figma.com/file/8zrInotU4JK9LWP4WyZy25/HPE-Design-System-Tags?node-id=126%3A1962

**Comment by vavalos5** [comment]
Eric has reviewed and ready to be implemented onto the site. Closing and creating a implementation ticket.
