### ISSUE TITLE
Button Guidance - v2 implement feedback on guidances for filter, forms, and layers

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2047]
Directly related to #1788

**Comment by vavalos5** [comment]
This looks great Kenny! I left a few comments.

After the share out on Thursday, we may be able to close this out depending if there is any other feedback. :)

**Comment by KennyAtHPE** [comment]
@vavalos5 Thanks for the feedback, replied to most of your questions in the threads on Figma.

**Comment by vavalos5** [comment]
Thanks for answering questions. looking forward to share out :)

**Comment by vavalos5** [comment]
We can close this since it is done :) Good job Kenny!
