### ISSUE TITLE
Page Layouts - Overview (Definition & Anatomy)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2054]
Deliverables include:
- Definition of layout (documentation)
- Anatomy of a page (documentation)

**Comment by vavalos5** [comment]
moving to the "triage column" since we won't be working on it this week and to clear the "in progress" column

**Comment by bahriaditi** [comment]
@ericsoderberghp @halocline @vavalos5 
Please review V1 of the documentation - hoping to get your feedback in by end of the week: https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Layouts?node-id=1876%3A16251

**Comment by vavalos5** [comment]
@bahriaditi Looks good! I've left some comments on your Figma file :)

**Comment by halocline** [comment]
Thank you, @bahriaditi. I dropped comments in the file. I think we are hitting on the right concepts and talking points.

As I was going through, I was thinking about how this translates into implementation and a lot of my comments have that in mind. I wonder if a good next step would be to start a branch where we start coding up some layouts and see how well the terminology and concepts align to implementation and whether there are points we need to feed back into the content drafted here. Thoughts?

**Comment by bahriaditi** [comment]
> Thank you, @bahriaditi. I dropped comments in the file. I think we are hitting on the right concepts and talking points.
> 
> As I was going through, I was thinking about how this translates into implementation and a lot of my comments have that in mind. I wonder if a good next step would be to start a branch where we start coding up some layouts and see how well the terminology and concepts align to implementation and whether there are points we need to feed back into the content drafted here. Thoughts?

Love that idea – I'll set up some time to connect with you on this next week.

**Comment by bahriaditi** [comment]
@halocline based on our discussion yesterday, I updated the documentation to reflect some of the terminology change. I also included a little more info around the "Grid" section but I know this is probably something that deserves its own time and thinking. Hopefully you have everything you need for #2135 

Figma: https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Layouts?node-id=1876%3A16251

Closing this ticket but please feel free to reach out for any questions!
