### ISSUE TITLE
Page Layouts - Container

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2055]
Deliverables include:
- Content width (design & dev)
- Responsive design (documentation)
- Breakpoints and padding (design & dev)

**Comment by vavalos5** [comment]
moving to the "triage column" since we won't be working on it this week and to clear the "in progress" column

**Comment by bahriaditi** [comment]
@ericsoderberghp @halocline @vavalos5 
Please review V1 of the documentation - hoping to get your feedback in by end of the week: https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Layouts?node-id=1876%3A16251

(^ same figma link as in #2054 )

**Comment by taysea** [comment]
Closing, work is completed and published: https://design-system.hpe.design/templates/page-layouts?q=page
