### ISSUE TITLE
Navigation - Table Ideation

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2058]
Begin guidance and example visuals for Table

**Comment by jeffstolz** [comment]
@vavalos5 this is ready for review - I followed the patterns established for cards and lists when building the guidance and example for DataTables. Perhaps we can review the section together and find ways to consolidate the guidance to eliminate unnecessary repetition? https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1%3A17

**Comment by vavalos5** [comment]
Agreed. Lets connect during the PRty time @jeffstolz
