### ISSUE TITLE
Icons - When should icons be text-strong vs. default text

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2062]
The design system has some nuances where it isn't using the correct icon color. We need to create guidance on when to utilize default text color and when to use text-strong.

I'm thinking:

Anything that is an icon that is interactive/ behaving like a button should be text-strong and anything else that is utilizing an icon but isn't interactive should be default text color.

**Comment by ericsoderberghp** [comment]
Sounds like a good direction.

**Comment by vavalos5** [comment]
Example where we see an interactive icon (trash icon) and a critical/warning icon (not an interactive icon)

![Screen Shot 2021-11-16 at 10 24 30 AM](https://user-images.githubusercontent.com/62117454/142043954-ada616ca-8e43-4f26-b2de-2fcb6da64e30.png

Design system site example using an interactive "button" that is using default color but should be text-strong
![Screen Shot 2021-11-16 at 10 23 53 AM](https://user-images.githubusercontent.com/62117454/142043971-0c776014-6dd3-433e-94e1-7aab665fff17.png)

Lets do a bit of researching also to make this case strong

**Comment by taysea** [comment]
By default from theme, anytime an icon is implemented as a button `icon`, it will automatically use `text-strong`. When an icon is just used as text (non-interactive) it will be `text` by default. Closing since no further work is needed.
