### ISSUE TITLE
Ordering of Items - Change cog icon to column icon

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2063]
Per a test that Melissa created on which icon resembles "column ordering", the team has agreed to change the cog icon to a column icon.

Please update in Figma file:https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=33%3A12

Once cleaned up in Figma, create a ticket for developer to implement changes onto the design system site.

The study can be found here: https://hpe-my.sharepoint.com/personal/melissa_meingast_hpe_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmelissa%5Fmeingast%5Fhpe%5Fcom%2FDocuments%2FReports%2F2021%2FECP%20Manage%20Column%20Icon%20Findings%2Epdf&parent=%2Fpersonal%2Fmelissa%5Fmeingast%5Fhpe%5Fcom%2FDocuments%2FReports%2F2021

Here are some screen shots from the study:
<img width="1405" alt="Screen Shot 2021-11-16 at 2 02 12 PM" src="https://user-images.githubusercontent.com/62117454/142078824-1eb53597-ca64-4bb6-8643-c83234aab549.png">

<img width="1414" alt="Screen Shot 2021-11-16 at 2 02 58 PM" src="https://user-images.githubusercontent.com/62117454/142078835-c6abd99a-211f-4d3b-a5dd-4f8496bc4009.png">

**Comment by Keeth-HPe** [comment]
Heyy @vavalos5 

The Figma file is updated. Changed the cog icon ("Settings-option" icon)  to a column icon ("Navigation/splits" icon) as mentioned above. 
https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=33%3A12. 

Closing this ticket and creating a new ticket for developer to implement changes onto the design system site.
