### ISSUE TITLE
Navigation - Matrix Navigation Ideation

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2068]

**Comment by vavalos5** [comment]
Started Ideating already https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1647%3A9780

**Comment by vavalos5** [comment]
I've completed Matrix, @bahriaditi @ericsoderberghp @britt6612 Can you please take a look and leave any feedback/comments please. Thanks!

https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1647%3A9780

**Comment by bahriaditi** [comment]
Added my comments ✔️  Great work 👏🏼

**Comment by vavalos5** [comment]
Thank you, i've taken another stab, cleaned up the file and ready for review

**Comment by vavalos5** [comment]
I'm going to close. I've received okay from Aditi and Scott. If I receive feedback on changes, I will create another ticket to implement changes
