### ISSUE TITLE
Notifications Center

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#2072]
Exploration
- [x] Notification Center - Consume existing notifications research
- [ ] #2076
- [x] Notification Center - Stakeholder Interview

Ideation
- [ ] #2073
- [ ] #2074
- [ ] #2075

Implementation
- [ ] #2077
- [ ] #2078

**Comment by gregfuruiye** [comment]
Existing Design System Notification Work:
https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=1353%3A1782

Working Figma File for the Notification Center design:  
https://www.figma.com/file/kDGDt00S1QImKPOZcrhFe6/Notification-Center?node-id=2210%3A354

Figma File with Design System Council presentation: 
https://www.figma.com/file/ARxvqb9nZosmTgn6Vz2pgV/Notification-Center?node-id=1%3A621

**Comment by ericsoderberghp** [comment]
The current plan for a "Notifications Center" is to let the GreenLake platform take the lead in designing it. The HPE Design System team will engage to:
- collaborate towards the designs aligning with existing patterns in the design system
- extend the design system with any new needs identified, such as how whether a notification has been read or not is indicated. Any extensions will be tracked as new issues.
