### ISSUE TITLE
Button Guidance - Implementing new button positioning guidance with examples

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2082]
Implementation based on research and exploration from #2048, #2047, #1788, #1785

All items are linked to Figma designs.

Additional written guidance for these design pages:
- [ ] [Buttons](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4153%3A9026)
- [ ] [Layer](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4153%3A9007)
- [ ] [Form](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4153%3A8992)

Current examples to be changed:
- [ ] [Side Drawer Modal](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4153%3A9007)
- [ ] [Filter example in Forms page](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4153%3A8992)

**Comment by bahriaditi** [comment]
@taysea do you think we can include Keeth's documentation around Cancel buttons in #2083, or should I create a new ticket for implementing that on the site? 

See: https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4063%3A9258
^ note that we will be making this more concise, but wondering specifically about the do's and the dont's
