### ISSUE TITLE
Button Guidance - V2 of "Should "Cancel" button in a Form/Modal be secondary or default button?"

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2083]
Since Keeth did research and received feedback from me on ticket #1785 for first ideation, this is V2.

Please pair up with @KennyAtHPE  to complete this ticket. Almost there.

Don't forget to add link to this ticket when completed.

Receive feedback

When all is approved, pair up w/ developer

**Comment by Keeth-HPe** [comment]
Hi @vavalos5 @bahriaditi,

After discussing button alignment and ordering with Kenny, I have updated the visual examples along with guidance. Here's the link: https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=4063%3A9258 
Please share your feedback :)

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe this is looking good to me, can you plan for a share out with our extended team for this week? (Depending on how you're feeling)

**Comment by Keeth-HPe** [comment]
Yes, @bahriaditi  1. Working on that guidance, also trying to understand from the Indian design team, as there are some use cases where they have used more than 3 buttons.
 2. I agree, I have now changed that example to something more easier to understand and that's not off brand.
 
Yes, as discussed. planned to do a shareout for this week.

**Comment by Keeth-HPe** [comment]
As per my online research 

> Thanks @Keeth-HPe this is mostly looking good to me. Two comments:
> 
> * Have we considered adding guidance around the maximum number of buttons on a single form? Ex: no more than 3?
> * In your example of 3 buttons, can we use an alternate label for the "reject" button? That copy seems off brand and also clashes with the default "cancel" button.
> 
> Can you also plan for a share out with our extended team for this week? (Depending on how you're feeling)

- As per my research on "guidance around the maximum number of buttons on a single form", there is actually no set limit. But best practice is to not use too many buttons in a single form. Standard limit of buttons used in a screen are 2 (primary and secondary) but a third one can be included as per the use case, provided it is of a different variant, eg: default variant  such as "cancel" or "skip".    

- Buttons have to be prioritised according to the most important action that we want our users to take and make decisions accordingly. But it's advised not to use more than one primary button

**Comment by KennyAtHPE** [comment]
Guidance from #2079 is included within this issue

**Comment by taysea** [comment]
Closing, updated guidance published and patterns use "Default" treatment.
