### ISSUE TITLE
Button Guidance - Ideation for "Should "Cancel" on Wizard be "Exit" instead?"

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2084]
Ideation for #1884

**Comment by bahriaditi** [comment]
@Keeth-HPe assigning you this ticket to work on next. Please let me know if you need more info or if anything is unclear. Thank you!

**Comment by Keeth-HPe** [comment]
@bahriaditi  Thank you! This seems clear and straightforward. On it 💪

**Comment by bahriaditi** [comment]
@Keeth-HPe I reviewed your work in progress and added a comment for you – let me know if you have any questions

**Comment by Keeth-HPe** [comment]
@bahriaditi,  I did a little feedback gathering from the Indian team and seems all are leaning towards having it "Cancel".  added some feedback to the file. Please do review.

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe – getting feedback is always helpful!
I connected with our content expert Will (@CitizenFox) today who said:

> "I think the action of cancellation is tricky here because it remains ambiguous as to whether the user is:
> A) Leaving the flow
> B) Cancelling the action of leaving the flow
> 
> When it isn't immediately clear what cancellation does, I really like doing these two things:
> 
> 1. Provide a clear binary choice.
>     Example: yes or no.
> 2. Provide a secondary term that reaffirms the action.
>     Example: stay or leave."

Based on this and the feedback you provided, we settled on the following messaging (screenshot attached):

> **Are you sure you want to exit the wizard?**
> (Wizard Title)
> 
> You have unsaved changes. Leaving this page will cause you to lose all of your progress.
> 
> No, Stay / Yes, Leave

With this approach, the label next to the close icon on the Wizard can still say "Cancel"


![Wizard example](https://user-images.githubusercontent.com/87677275/146459973-e8238f57-260a-4edc-aac2-5de7d8852e1b.jpg)

![Confirmation Layer](https://user-images.githubusercontent.com/87677275/146460037-65cf9712-09b8-40d6-ab88-03b713d1d424.jpg)

**Comment by bahriaditi** [comment]
Moving to review so @taysea (original ticket creator) + @ericsoderberghp can get their eyes on this before implementation on site

**Comment by Keeth-HPe** [comment]
> Thanks @Keeth-HPe – getting feedback is always helpful! I connected with our content expert Will (@CitizenFox) today who said:
> 
> > "I think the action of cancellation is tricky here because it remains ambiguous as to whether the user is:
> > A) Leaving the flow
> > B) Cancelling the action of leaving the flow
> > When it isn't immediately clear what cancellation does, I really like doing these two things:
> > 
> > 1. Provide a clear binary choice.
> >    Example: yes or no.
> > 2. Provide a secondary term that reaffirms the action.
> >    Example: stay or leave."
> 
> Based on this and the feedback you provided, we settled on the following messaging (screenshot attached):
> 
> > **Are you sure you want to exit the wizard?**
> > (Wizard Title)
> > You have unsaved changes. Leaving this page will cause you to lose all of your progress.
> > No, Stay / Yes, Leave
> 
> With this approach, the label next to the close icon on the Wizard can still say "Cancel"
> 
> ![Wizard example](https://user-images.githubusercontent.com/87677275/146459973-e8238f57-260a-4edc-aac2-5de7d8852e1b.jpg)
> 
> ![Confirmation Layer](https://user-images.githubusercontent.com/87677275/146460037-65cf9712-09b8-40d6-ab88-03b713d1d424.jpg)

This is great 💪

**Comment by ericsoderberghp** [comment]
I'm good with the direction to make the prompts, especially the button labels, clearer and keep using "Cancel".

**Comment by bahriaditi** [comment]
Closing this ticket - will make a new one for implementation on site!
