### ISSUE TITLE
update @eslint airbnb

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2096]
update `eslint` and `eslint-config-airbnb` for grommet

**Comment by britt6612** [comment]
When updating to the latest `@airbnb eslint package` we get over 1500 errors this is all mostly caused by a new rule that was changed from "off" to "error" in the latest release. This was not documented within the release notes so I had to dig a little to find the change. 

I did find another issue though documenting the same problems we are running into here https://github.com/airbnb/javascript/issues/2505

There is an open PR for this issue that was opened about a month ago https://github.com/airbnb/javascript/pull/2501
<img width="755" alt="Screen Shot 2021-12-06 at 12 00 55 PM" src="https://user-images.githubusercontent.com/42451602/144906034-daa157c5-ebb3-4fa1-9217-3675b59a5746.png">
In this PR you can see where the rule got [changed](https://github.com/airbnb/javascript/blame/master/packages/eslint-config-airbnb/rules/react.js#L528)

We can either upgrade and turn this rule "off" and keep track of the progress in the airbnb repo or we can wait to upgrade until it is resolved. Locally I did turn off the rule and I have about 49 errors which is much more reasonable to go through and see the changes..

@ericsoderberghp I'm leaning towards turning this rule off for now and moving forward with an update but would like your opinion as well.

**Comment by ericsoderberghp** [comment]
Agreed. Let's turn it off for now, with a comment where we do that referring to this issue.

**Comment by britt6612** [comment]
> Agreed. Let's turn it off for now, with a comment where we do that referring to this issue.

sounds good I'll get to it!

**Comment by MikeKingdom** [comment]
Same here. That's an annoying default. I wonder if it would go better if we changed it to only enforce what we seem to prefer like arrow-function for named and unnamed components? Not sure all which styles we use.

**Comment by britt6612** [comment]
> Same here. That's an annoying default. I wonder if it would go better if we changed it to only enforce what we seem to prefer like arrow-function for named and unnamed components? Not sure all which styles we use.

I can look into something like this I believe for the most part we are using arrow-functions but with this rule it did not like the arrow-function it was wanting me to put back the `function` so seemed like we were regressing..
