### ISSUE TITLE
FormField - Create "horizontal" FormField variant to support "edit mode" for horizontal NameValueLists

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2100]
Request from CCS team (Ephrem & Derek) during office hours + follow on convo on 11/30. Urgency --> Designs for this are already being handed off to be coded => the longer we wait to implement, the greater the divergence between a custom implementation vs. a Grommet/Design System implementation.

Design exploration needed: 
- [ ] Placement of help (i.e. description) text, likely directly below label
- [ ] Placement of infos text, likely directly below input (as currently implemented)
- [ ] Placement / treatment of errors text, likely directly below input (as currently implemented)

Will likely need:
- [ ] FormField to accept a `direction` prop
- [ ] Orientation of Box from column to row with Label+Help in column1 & Input, Info, Error in column2 (columns 1 & 2 to be vertically aligned top / align="start")
- [ ] Theme - specify spacing - Ideally, preserve all spacing as is, however, FormField margin will need adjustment when in horizontal orientation
- [ ] Follow up with Ephrem + CCS developer (Satish?) to bring new functionality into CCS frontend codebase

Related issue being created for implementation of example on Design System Site.

**Comment by ericsoderberghp** [comment]
Holding off on this for now. Exploring using the existing FormField without `label` as the `value` for NameValuePair.

**Comment by ericsoderberghp** [comment]
Replaced by #2120 and #2101
