### ISSUE TITLE
NameValue List - Create Figma example for horizontal editable form fields

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2101]
Brought up by Ephrem (CCS)

- [ ] how are form buttons handled, submit, cancel?
- [ ] where are form level validation messages located?
- [ ] is anything else from the current Form details missing?
- [ ] is the right way to think of this as still a NameValueList but with FormField values, where the FormField doesn't have `label`? This would allow keeping the name side of the NameValueList intact.

Example use case (read only and editing):
Figma: https://www.figma.com/file/5VkmCUaEs7aMdyn5ZqypYP/Portal-Customization?node-id=86%3A15038

<img width="677" alt="Screen Shot 2021-12-01 at 11 22 19 AM" src="https://user-images.githubusercontent.com/87677275/144299913-b4b18b4b-abe3-4ee2-be7e-c55866b4e210.png">

<img width="678" alt="Screen Shot 2021-12-01 at 11 19 30 AM" src="https://user-images.githubusercontent.com/87677275/144300018-ff6d23a9-fcca-4baa-b14e-859090995bb7.png">

Corresponding HPE Design System site example: #2120

**Comment by bahriaditi** [comment]
@Keeth-HPe depending on your availability this week, is this something you can take on?

We need to align the Name-Value List [Figma file ](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/HPE-Name-Value-List?node-id=798%3A2829)to recent updates made on the Design System site:
Please add [Name-Value Pair as a read-only display in horizontal](https://design-system.hpe.design/components/namevaluelist?q=name#name-value-pair-as-a-read-only-display-in-horizontal) example to the appropriate section in the Figma file. You can use [Ephrem's file](https://www.figma.com/file/5VkmCUaEs7aMdyn5ZqypYP/Portal-Customization?node-id=86%3A15038 )  (linked in description) as a starting point.

I've given you editing rights to the NameValue List file–let me know if you have any questions!

**Comment by Keeth-HPe** [comment]
@bahriaditi,

I've added the Name-Value Pair as a read-only display in horizontal example to the [Figma file](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/HPE-Name-Value-List?node-id=798%3A2829)

Please review and let me know if it looks fine :)

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe!

Can you also please add in the editable version (to show form fields once you click on the edit button)?

**Comment by bahriaditi** [comment]
This is done! https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/HPE-Name-Value-List?node-id=798%3A2829
