### ISSUE TITLE
Buttons - Update Figma with new hover states for Primary + Color Buttons (Based on #1271)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2115]
Based on design direction from #1271, please update the [Button component in Figma](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1)

**Comment by Keeth-HPe** [comment]
Hi @bahriaditi, I've updated the hover state for Primary & Color buttons for both light and dark themes in the Figma library. Please have a look : https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1

**Comment by Keeth-HPe** [comment]
Hover state for primary buttons (for light theme) are updated with 'Brand Green' color at 75% opacity for better legibility.
Also published in the Figma library.
@bahriaditi

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe ! Moving to done. Dev implementation captured in #2122
