### ISSUE TITLE
NameValueList - create a horizontal editable example

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2120]
Create another example, similar to https://design-system.hpe.design/components/namevaluelist?q=name#name-value-pair-as-a-read-only-display-for-text-inputs but with horizontal layout. Use FormField without `label` for the `value` of each NameValuePair.

Following guidance from https://github.com/grommet/hpe-design-system/issues/2101

**Comment by bahriaditi** [comment]
@taysea @britt6612 this is looking great! Two minor spacing-related comments:

1. **Labels with descriptions**: Can we remove spacing between label and description so they feel like a tighter unit?

2. **Stacked version**: When the fields begin to stack on smaller screens, I noticed there is no spacing between the input field and the corresponding labels. Can we add a 6px spacing please?

<img width="641" alt="Screen Shot 2021-12-13 at 10 49 18 AM" src="https://user-images.githubusercontent.com/87677275/145871782-f84f4926-eef5-4fb9-8b93-2780e0b8bf87.png">

**Comment by halocline** [comment]
> 2. **Stacked version**: When the fields begin to stack on smaller screens, I noticed there is no spacing between the input field and the corresponding labels. Can we add a 6px spacing please?
> 
> <img alt="Screen Shot 2021-12-13 at 10 49 18 AM" width="641" src="https://user-images.githubusercontent.com/87677275/145871782-f84f4926-eef5-4fb9-8b93-2780e0b8bf87.png">

I am leaving a code comment that should correct for this. NOTE: Currently, at 'medium'+ widths, formfields receive vertical margins of 6px, however at 'small' width that vertical margin is reduced to 3px. Ideally we rely on the HPE theme here.
