### ISSUE TITLE
Buttons - Update HPE theme & Design System site with new hover states for Primary Buttons (Based on #2115)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2122]
For dev:
Connect with Keeth/ Design team to update new hover styling 

Figma: https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=3644%3A8574

**Comment by halocline** [comment]
🤔 

1.  Isn't the point of the example to show that you can apply color (from the palette) to a button if your use case necessitates that?
2. What is the rationale behind showing two different colors? I would think it would be the same color (namespace) and either be color!, color.light, or color.dark.

**Comment by britt6612** [comment]
> 🤔
> 
> 1. Isn't the point of the example to show that you can apply color (from the palette) to a button if your use case necessitates that?
> 2. What is the rationale behind showing two different colors? I would think it would be the same color (namespace) and either be color!, color.light, or color.dark.

those are good points that is where my confusion came in because I thought any `color` could be passed through but if we are restricting those `colors` we need say explain why.. since `color` is a prop anyone can pass whatever color into this `button` its not like the theme where we can  restrict  someone's changes

**Comment by bahriaditi** [comment]
Hi @halocline @britt6612 I'm going to tag @vavalos5 and @ericsoderberghp so they can chime in. I feel like I'm missing some historical context.

**Vicky** - do you recall why we have two different color values for the light and dark mode for Color Button?

**Comment by vavalos5** [comment]
I'm not sure.. this was something Chris and Greg had worked on but I cannot seem to remember the reasoning behind that..

**Comment by britt6612** [comment]
@bahriaditi Im wondering if we should put this back in TODO and maybe dive a little deeper with the design side of things of how `colored` buttons should be addressed

**Comment by bahriaditi** [comment]
Hi @britt6612 – yes good idea, I'll make a separate issue to address the Color Button. 
But we should probably still move forward with updating the hover states for the Primary Button.

**Comment by britt6612** [comment]
sounds great! also I will put what Greg had mentioned to me 

```
I don’t think there was any reasoning other than to show that color button could be any color within the palette. There is not a requirement to use the teal or purple. However, we did discuss NOT including color button altogether as it poses a risk for teams to misuse it. For example, using critical red with white text.

```
