### ISSUE TITLE
Tags - Implement Guidance and examples to the Design System site

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2131]
Please add guidance on Tags and examples to the design system site. Figma file can be found here to reference: https://www.figma.com/file/8zrInotU4JK9LWP4WyZy25/HPE-Design-System-Tags?node-id=126%3A1962

Sub-tasks:
- [x] #2136
- [ ] #2137
- [ ] #2138
- [ ] #2139

**Comment by taysea** [comment]
Closing this ticket because the sub-tasks associated are capturing the progress.
