### ISSUE TITLE
Error States & Missing Data Conditions - Review use cases

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2132]
This request comes from the Cloud Services team and has been brought up in both the India and US Office Hours. Tagging @ecircenis as I understand that he is the point person for this request.

@jeffstolz provided [this Figma file](https://www.figma.com/file/3TWrKICGzaXRoZUJqHPcDn/Error?node-id=0%3A1) which acts as comprehensive catalog of use cases for error handling in the Cloud Services.

From Jeff: "The "Cloud Service Standards" page [in Figma] is what the group has determined as the best path forward, although that still needs to be cleaned up and there is a lot of variance there"

Action items:
- [x] Review use cases and recommendations in the above posted Figma link
- [x] Create more tickets!

**Comment by ericsoderberghp** [comment]
split up into errors and no data

## errors

### scenarios

- form validation errors
- item removed
- data retrieval error, API result issue
- variety of error codes: timeout, non existent, not authorized, ?
- 404

### aspects

- visual styling, icon?
- messaging, especially per-error code

## no data

- day zero friendly messaging, as opposed to something like a table header with a "no Xs" message
- no search results
- waiting for data to arrive, waiting for an API to validate something

## contexts

page, section, NameValueList, NameValuePair, Meter, Chart, Table, List, Cards, CardBody, TableCell, Drop content

**Comment by taysea** [comment]
Going to close this, I have opened a new ticket for prioritization.
