### ISSUE TITLE
Button - Color Buttons

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2146]
Based on #2122, there is some confusion around the Color Buttons especially around the Teal and Purple.

From Greg: 
> I don't think there was any reasoning other than to show that color button could be any color within the palette. There is not a requirement to use the teal or purple. However, we did discuss NOT including color button altogether as it poses a risk for teams to misuse it. For example, using critical red with white text.

- [ ] Make a decision around whether or not to include the Color button guidance on site
- [ ] Align Figma and site with same color examples/ documentation
- [ ] Make more tickets if needed

**Comment by ecircenis** [comment]
Instead of using color buttons for disruptive actions, cloud services uses normal primary buttons and a double/triple confirmation pattern.  You can see some (dated) examples of these here: https://designer.grommet.io/?id=Confirmation-Patterns-edgar-circenis-hpe-com

**Comment by taysea** [comment]
We have removed color button guidance, closing.
