### ISSUE TITLE
Navigation - "Ascending" Type

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2148]
During a conversation with Eric, we discussed how there's a 5th type of Navigation we should add into Navigation. While we're not sure on the name, hence "Ascending", we want to understand what it's called so we can include into the design system Navigation page as well as button guidance.

**Comment by vavalos5** [comment]
For the guidance i've written for Ascending Navigation, Brittany made a valid point about whether or not we're pointing that a user can move up in the hierarchy through the use of the "ascending button" since I didn't mention it in my file. 

**Questions:**

- Should we include a real example of how Ascending Navigation would work in the app (though it wouldn't be consistent with the other examples I have)?
- OR Should we let the ascending button guidance live elsewhere (perhaps Button or Page Layouts) and direct the user?

https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=2486%3A14738

**Comment by vavalos5** [comment]
I decided to create a second version and include it with Ascending Navigation. However, I changed the page name to "Ascending Button for Navigation".

https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=2540%3A14250

**Comment by ericsoderberghp** [comment]
> * Should we include a real example of how Ascending Navigation would work in the app (though it wouldn't be consistent with the other examples I have)?
> * OR Should we let the ascending button guidance live elsewhere (perhaps Button or Page Layouts) and direct the user?

I'm inclined to have both, with the Navigation context showing how it complements drill down navigation and the Button context showing it as another kind of Button.

**Comment by vavalos5** [comment]
Thanks, [I have included both on the page](https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=2540%3A14250). I also decided to call it " Ascending Button in Navigation".... Thoughts A tad long..

Heres a screen shot of the work I created:<img width="738" alt="Screen Shot 2022-01-11 at 2 33 50 PM" src="https://user-images.githubusercontent.com/62117454/149032220-f1dfbe7f-878f-4342-a0e6-c8dd24606f01.png">
