### ISSUE TITLE
Button - "Ascending" button

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2149]
During a conversation with Eric, we discussed how we want to give guidance to the way this particular button is used. Though it can assimilate a "back button" or how Eric refers to it "breadcrumb button-ish", it is not a back button.

This discussion came up during a discussion of adding an "Ascending Navigation" type to Navigation. In order to better understand what we mean by "ascending button", i'm including an example below:

- "It's not a back button but the button that takes you back to the hub from which the details view comes from"
<img width="1244" alt="Screen Shot 2021-12-15 at 2 25 06 PM" src="https://user-images.githubusercontent.com/62117454/146275530-19993430-fef9-4fa5-9dba-82c165b2edc5.png">

**Comment by halocline** [comment]
@taysea and I have also discussed wanting a specialized button which aligns nicely to the headings and all content below. Currently if we use a default button, because of the left padding, the button label gets pushed to the right and the label ends up not being visually aligned with the rest of the content.

**Comment by vavalos5** [comment]
Have either of you come up with any ideas or thoughts? Just curious

**Comment by halocline** [comment]
> Have either of you come up with any ideas or thoughts? Just curious

We implemented a custom version of default button with a negative left-margin adjustment to offset the button properly. Though that's not something we'd necessarily want consumers of the Design System doing. We'd rather give them a turn-key solution that "just works."

- One option is to create a new kind of button, similar to what we did for the [toolbar button](https://design-system.hpe.design/components/button#toolbar-button).
- As I'm typing, another option is that this might be a candidate for our Page Header work. If we were to provide Page Header template layouts as a component, the "ascend" or "parent" button could be accounted for in that layout.

**Comment by ericsoderberghp** [comment]
waiting for #2148 to provide a more complete set of design references

**Comment by vavalos5** [comment]
@halocline You definitely had the right idea going in mind about having the guidance live in Page Header template. I've come across[ Material UI's Top Bar App Header](https://m3.material.io/components/top-app-bar/guidelines) page where they mention the "ascending button" as a form to Navigate upward to the Hub page or to move back the previous page. But they don't go into details.
<img width="1074" alt="Screen Shot 2022-01-04 at 2 50 46 PM" src="https://user-images.githubusercontent.com/62117454/148134788-a63d5b44-a67c-41d1-97cb-662aa0e6b621.png">

**Comment by vavalos5** [comment]
Including my Figma link of where i'm including research. This might move. https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=1%3A20

**Comment by vavalos5** [comment]
Also had Keeth help me with retrieving use cases where the up button could be found and where we're directing the user: https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=2405%3A13984

A question I have is are there certain/different scenarios when the user expects to go back to the parent page of the detail page they went to. While the answer seems obvious, if the user goes deep into the hierarchy, do they expect the "back button" to take them back in the hierarchy order they came from or do they expect it to go to the parent page of the details page? While there is also the option to use the browser back button, I want to further understand whether this is a common expected behavior

**Comment by vavalos5** [comment]
Since we've figured out how we want to proceed forward with "reverse nav" and "ascending nav" and i've created the first draft for ascending, i'm going to close this ticket. 

https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=2486%3A14738
