### ISSUE TITLE
Revisit active Tab styling

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2151]
Feedback has been received that the styling of the active tab state is confusing and not clear which tab is currently active.

ToDos:
- [ ] Connect with @ecircenis to collect any user testing data / videos / readouts where they have received this feedback during user tests.
- [ ] Re-visit past research and rationale for current decisions. 
- [ ] Determine whether we should explore additional ideations.
    - [ ] If yes, ideate and test next iterations.
    - [ ] If no, add documentation to site speaking to the rationale for not adjusting the active tab styling to something like the "selected green".

**Comment by halocline** [comment]
This topic came up in office hours again on 5/18/22 and seems to be affecting multiple product designs and causing cascading UX issues such as adding a lot of redundant headings which clutter user interfaces and add to cognitive load.

Moving this back to Triage for reassessing prioritization. For reference, prior to moving this issue was sitting immediately below: https://github.com/grommet/hpe-design-system/issues/2139

**Comment by MeganBeierle** [comment]
Met with Beza and Matt to discuss best path forward on this one. I'm going to meet with Edgar next to see what kind of research has been done on our tabs and to get some feedback on how it is working throughout the system.

**Comment by vavalos5** [comment]
Adding Chris's NorthStar designs where we're using buttons as "tabs" in case its needed to consider. https://www.figma.com/file/tbxY1HaiyJjEI9Wm2dQ9nR/HPE-Prototypes?node-id=3213%3A106425

**Comment by MeganBeierle** [comment]
I met with Aditi to discuss my findings from research and conversations with other team members. After assessing the situation and designs that Chris has created in North Star work we have decided to do a quick A/B test on a slight design change. I will close this task out and create a new one for the testing.
