### ISSUE TITLE
Proper font color for default button active state?

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2152]
During office hours is was pointed out that the font color for an active default button is lighter than when at rest (text vs. text-strong). 
Example: https://design-system.hpe.design/components/button#button-states

ToDos:
- [x] Confirm whether or not the font color should be text or text-strong
    - [x] If text-strong update HPE Theme and Figma accordingly.
- [x] Regardless of outcome, report back to Pooja with the findings so that she may share with her team.

**Comment by bahriaditi** [comment]
Active states for Default Button (and all other button variants) are now updated in the [Figma library](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=3644%3A8574) as the text-strong color. This was updated for both light and dark modes. Thanks, Keeth!

I'll create a separate ticket for implementation on site.

@Keeth-HPe can you please let Pooja know and then check off that task in the ticket descriptions once you notify her? Thanks!

**Comment by taysea** [comment]
This has been resolved, closing.
