### ISSUE TITLE
Tags - Add guidance on how Tags are not Buttons

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2172]
Although in [Grommet we have an "OnClick" behavior for Tags](
https://storybook.grommet.io/?path=/story/type-tag-onclick--on-click). Are we going to want to support that on Design System? If so, what's the use case on that? When is it used?This might be a separate ticket..

What this ticket is about:  Wondering if we want to have guidance stating that Tags are not buttons. I see we say that the “x” is a button, but perhaps we want to be more specific that only that part receives button behavior rather than the entire tag container.

**Comment by taysea** [comment]
I have seen an example in the Tag WIP from @gregfuruiye that allows `onClick` on Tag. In this use case, the Tag can be clicked as a way to filter a dataset by that tag and navigate back to the summary page. I believe this is a pattern being used in one of the services at the moment. [Figma link](https://www.figma.com/file/8zrInotU4JK9LWP4WyZy25/HPE-Design-System-Tags?node-id=126%3A2714).

I am not saying we have to continue to support `onClick` but it seems a discussion is needed before adding guidance that `onClick` should not be used.

**Comment by halocline** [comment]
> I have seen an example in the Tag WIP from @gregfuruiye that allows `onClick` on Tag. In this use case, the Tag can be clicked as a way to filter a dataset by that tag and navigate back to the summary page. I believe this is a pattern being used in one of the services at the moment. [Figma link](https://www.figma.com/file/8zrInotU4JK9LWP4WyZy25/HPE-Design-System-Tags?node-id=126%3A2714).
> 
> I am not saying we have to continue to support `onClick` but it seems a discussion is needed before adding guidance that `onClick` should not be used.

Agree that filtering behavior is quite common and that onClick is valuable.

Thinking we should have guidance regarding "no onClick & remove at the same time".

**Comment by taysea** [comment]
Work being handled in #4033
