### ISSUE TITLE
Align Card Header color on Design System site to Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2205]
On the Design System site, we are showing the header color to be our default text color, however, since it is a header, it should be text-strong. Please align to [Figma](https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=36%3A65). Thanks

Figma styling:

<img width="386" alt="Screen Shot 2022-01-11 at 2 23 47 PM" src="https://user-images.githubusercontent.com/62117454/149030981-1616538f-c123-4f90-832c-231696abe019.png">

Design System site currently:

<img width="1370" alt="Screen Shot 2022-01-11 at 2 21 23 PM" src="https://user-images.githubusercontent.com/62117454/149030969-51463f90-a1ce-40d4-92f3-4bbb493c3d08.png">
<img width="1335" alt="Screen Shot 2022-01-11 at 2 21 16 PM" src="https://user-images.githubusercontent.com/62117454/149030971-26819c20-5c9b-4610-b334-9bc3e703945b.png">
!

**Comment by halocline** [comment]
🤔  I don't believe these should be semantically implemented as HTML "headings" (i.e. h1-h6). I think we may be misleading folks by using the Heading components and should be using Text instead.

If we want the color to be `text-strong` that's fine, but we should use the correct semantic markup for the scenario.

**Comment by vavalos5** [comment]
Good eye, I was referring to only the color rather than HTML heading. I can correct those from Figma.

**Comment by vavalos5** [comment]
Documenting that i've updated the Figma file and removed HTML h1-h6 headings on cards and replaced w/ bold xxlarge t-shirt size
