### ISSUE TITLE
Navigation - Decide on an A/B test or conversing with stakeholders on "ascending button"

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2206]
During a call this morning with the Designers and Scott, we discussed how many people see the Ascending Button as a "back button" as a form of moving BACK in the sequence a user navigated. We thought it would be a good idea to either 1. Have a conversation with stakeholders and try to see if we can hash it out OR 2. Do an A/B test where we can utilize Chris Connetta's research expertise to decipher which experience is most recognizable (whether users automatically see the "ascending button" as a form to move up in the hierarchy or a way to move back in the order they came from"

**Comment by ericsoderberghp** [comment]
If I follow a link like: https://my.app/servers/1, I would expect enough context there to indicate that I am looking at a server and a control to get to other servers.
- If this button is used to go back in the navigation hierarchy, how would the other aspects be covered? 
- Would tying it to the navigation history require it to be shown on every page, for consistency?

**Comment by vavalos5** [comment]
Fair point. Perhaps this isn't needed then.

**Comment by vavalos5** [comment]
Closing as we no longer need to do this
