### ISSUE TITLE
Revisit Multi-Select guidance and behavior

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2207]
In our early Filtering work, we strayed away from using Select with multi-select and instead encouraged teams to use CheckBoxGroup.

However, in cases like assigning value-only Tags (https://deploy-preview-2198--keen-mayer-a86c8b.netlify.app/components/tag?q=tag#assigning-value-only-tags), allowing multi-select seems plausible and more efficient for the user.

Similar non-HPE use cases would be when assigning labels to a Github issue, assigning reviewers. You can select multiple labels/reviewers before the drop closes.

To-Do:
- [ ] Determine when Select + multi-select is valid to use
- [ ] Add / direct to example on the site

**Comment by halocline** [comment]
Cross-linking this with #2234 which has additional details.

**Comment by geepriya** [comment]
Cluster Selection Component (Single Select Explorations) 
https://www.figma.com/file/yZyMsoTk6zSn2TgHH257Ea/Ezmeral-Components-V2?node-id=597%3A40487

**Comment by bahriaditi** [comment]
Closing because this ticket is now merged with #2234
