### ISSUE TITLE
Accessibility Page - Create Visuals for Core Principles

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2211]
Please create visuals for the following core principles: perceivable, operable, understandable, and robust

The principles would appear right below the introduction of what accessibility is in this [Figma file.](https://www.figma.com/file/xKOmIiwc6h3yPsdLERxCbV/Accessibility?node-id=311%3A298)

Amanda's pR example: https://deploy-preview-2202--keen-mayer-a86c8b.netlify.app/foundation/wcag-checklist

**To Dos:**

- [x] Explore for inspiration
- [x] Create visuals for each principle
- [ ] Get feedback

Other Frameworks inspirations:
https://material.io/design/usability/accessibility.html#hierarchy

https://www.equalweb.com/html5/wcag/a11y.taf?did=1116&type=WCAG_2.1&filterBy=All&trace=USA_WCAG&_gid=654321&utm_source=adwords&utm_medium=ppc&utm_term=web%20accessibility%20guidelines&utm_campaign=ADAM+US&hsa_cam=1649673773&hsa_grp=87179809629&hsa_ver=3&hsa_mt=b&hsa_kw=web%20accessibility%20guidelines&hsa_ad=409134634496&hsa_tgt=kwd-297836297410&hsa_net=adwords&hsa_src=g&hsa_acc=3256854121&gclid=Cj0KCQiAuP-OBhDqARIsAD4XHpczcW7_newwTgJdqOMEGm2RB-O_kcKvF_SiAqUlIQyWk-6YhLt08HMaAgIcEALw_wcB

https://spectrum.adobe.com/page/principles/

**Comment by vavalos5** [comment]
@Keeth-HPe Here are the core principle definitions Amanda has provided. I've included the link and a screen shot of the principles w/ definitions. Let me know if you have any questions:

https://www.figma.com/file/xKOmIiwc6h3yPsdLERxCbV/Accessibility?node-id=419%3A363
![Screen Shot 2022-01-18 at 9 27 53 AM](https://user-images.githubusercontent.com/62117454/149987929-de6372d7-932a-4fb0-bb29-14887887669d.png)

I'm going to add more specific ideas later today

**Comment by Keeth-HPe** [comment]
Hi @vavalos5, thank you! No questions on the definitions. It's clear to me.  

Also, thank you for the insights on each visual, so helpful!

**Comment by Keeth-HPe** [comment]
Hi @vavalos5
[Here](https://www.figma.com/file/xKOmIiwc6h3yPsdLERxCbV/Accessibility?node-id=431%3A606) are the visuals created for the four core principles, also updated the copy shared by you. Please take a look and let me know what you think. For the "operable" principle, I have 2 extra options, was not able to decide on one. 

Thank you!

**Comment by vavalos5** [comment]
@Keeth-HPe These look AMAZING!! Thank you for creating them. I think the current design you have for operable is great. This ticket is done. 👏🏼
