### ISSUE TITLE
Ascending Navigation - Receive feedback and implement changes

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2222]
Last week i received feedback on how the 4 squares that make up the example is hard to view in different resolutions, so i'll have to look for another alternative.

**Comment by vavalos5** [comment]
Chatted with Brittany and we're trying to come up w/ two different solutions of possibly doing this:
1. simplifying the examples which i've done here: https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=2725%3A18556
2.  Creating an example that only allows you to click on the interactive elements like in this simple prototype I created. However, we have a concern about this being accessible. We wanted the user to walk through the experience, but we're not sure if this is going to give the full picture.

**Comment by ericsoderberghp** [comment]
I think we should ensure that the user is not required to interact with anything in order to understand the essence of the concepts.

**Comment by vavalos5** [comment]
[I've implemented changes in the Figma file](https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=2725%3A18556) in both light and dark mode. I'll be doing a share out tomorrow and collect any other feedback. Will create a ticket should we need it.
