### ISSUE TITLE
Typography - add new header styling for menu sections

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2230]
**From Gina Taylor:**
'The header team has a need for a new Gray text color. #757575 passes accessibility for AA. It will be a "weak" text, but will NOT be disabled. It will be used for section headings in the header and in some other places (example shown below)."

- [x] Validate need for new text color through more existing use cases 
- [x] Add new color to DS style library in Figma with description
- [ ] Make issue for implementation on site

![Screen Shot 2022-01-19 at 5 21 10 PM](https://user-images.githubusercontent.com/87677275/150234926-44620982-23a0-43ed-8673-5946887529dd.png)

**Comment by eddieshowcase** [comment]
Did we ever capture the issue of HPE DS website and Figma library not having the 'medium' weight for typography? Curious... this made me think that we had some need or want to use of 'medium' weight as it is provided in the Grommet HPE theme and available for use.

**Comment by ericsoderberghp** [comment]
Can we elaborate on why the current typography patterns aren't sufficient here?

**Comment by L0ZZI** [comment]
@ericsoderberghp Yes! 😁 Weak text doesn't bring much depth to the text styles. When stacked up it's hard to discern the difference from strong/default/weak. This came out of some discovery on the marketing side to have a style that's softer but still WCAG AA compliant. Thoughts?

![Screen Shot 2022-01-26 at 3 20 01 PM](https://user-images.githubusercontent.com/1753301/151267166-49f54d86-7862-4854-b33d-3173323be5a1.png)

**Comment by ericsoderberghp** [comment]
Looks like we should just make "weak" weaker?

**Comment by GinaTaylor** [comment]
I think there was an error with the above image, I think what is labeled Weak is actually the default text color. Weak is too light to be used for page content. #BBBBBB does not pass accessibility (it is for disabled text only). We are proposing that we have a lighter text color (that is accessible and can be used for active text) to provide additional hierarchy to our content. In the image below, you can see the difference.

![Screen Shot 2022-01-27 at 8 39 48 AM](https://user-images.githubusercontent.com/89482747/151380865-e5b091c5-ec17-4544-abc1-2c90681a50b0.png)

**Comment by bahriaditi** [comment]
@Keeth-HPe can you add some screenshots that you've come across from the India team here?

**Comment by Keeth-HPe** [comment]
@bahriaditi  Here are some I found, these might not be section headings nor a disabled text. But "text weak" is being used. 
<img width="724" alt="Screenshot 2022-02-01 at 7 06 29 PM" src="https://user-images.githubusercontent.com/86280029/151978496-9806f61e-97c5-4edc-9d79-276b7dea2ed2.png">

<img width="578" alt="Screenshot 2022-02-01 at 7 04 23 PM" src="https://user-images.githubusercontent.com/86280029/151978507-19d0567d-ea79-4f0d-8158-687206b03e7f.png">

<img width="585" alt="Screenshot 2022-02-01 at 7 03 41 PM" src="https://user-images.githubusercontent.com/86280029/151978555-c798abac-1373-48e3-a2f
<img width="237" alt="Screenshot 2022-02-01 at 7 03 20 PM" src="https://user-images.githubusercontent.com/86280029/151978583-caa382ac-35b2-4521-aac8-99fad69730fb.png">
0-66c630cc3cd2.png">

![Group 1](https://user-images.githubusercontent.com/86280029/151978620-442e1af5-70d8-4e56-88ad-ea93b63b9043.png)

**Comment by GinaTaylor** [comment]
@bahriaditi these are great examples. however, text weak (BBBBBB) is too light to pass accessibility with a white background and should not be used in our use case. #757575 is the lightest that passes accessibility.

![Screen Shot 2022-02-01 at 8 54 04 AM](https://user-images.githubusercontent.com/89482747/151991798-13b636b8-a6c7-4ecc-94ca-4c00d53f719e.png)
![Screen Shot 2022-02-01 at 8 54 13 AM](https://user-images.githubusercontent.com/89482747/151991803-d445a5e5-124b-4c2d-94b3-243ca6c3c46a.png)
.

**Comment by bahriaditi** [comment]
Hi @GinaTaylor, don't worry – we just needed to collect more examples of how people are using a lighter gray text (whatever the hex value might be) ;) 

@ericsoderberghp sounds like this is definitely something thats needed, beyond just section headings. I feel the ticket title might be a bit misleading. I'll go ahead and move this to in progress so Keeth can work on it this week.

**Comment by ericsoderberghp** [comment]
sounds good to me, I'm still leaning towards changing `text-weak` and making the current `text-weak` be `text-xweak`, as opposed to inserting a new color name between the existing `text` and `text-weak`.

**Comment by Keeth-HPe** [comment]
@bahriaditi  

Hi Aditi, I tried a new grey shade that passes the accessibility for both light and dark themes. Also wrote a description  for it.

Documented it here: https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=4076%3A403
Please do review.

**Comment by eddieshowcase** [comment]
While making the text-weak a bit darker for accessibility seems like a good idea. My one caution or concern in seeing the Figma link above is that it doesn't show or take into account one of the primary use cases for it... which is labeling for disabled inputs and controls. 

If the text-weak become darker, will disabled form inputs still look disabled? Or am I to understand per Eric's comment above disabled inputs/controls would all then use 'text-xweak'? 

I can say that disabled controls now really are light and hard to see... but when 'disabled' they aren't visible to the accessible user (usually hidden from the DOM). If you choose to make disabled controls use a new darker 'text-weak'... you should consider a different presentation/style for indicating disabled, like a grayed our input area or something. 

Just some things to think about...

**Comment by ericsoderberghp** [comment]
Good feedback. I think we should add some evaluation of what making this change will look like in various contexts. I'd recommend pairing up with a developer to look at all of the cases where `text-weak` and `text-xweak` are currently used within grommet components and within HPE Design System examples, picking out some interesting ones, and showing before and after.

**Comment by bahriaditi** [comment]
> While making the text-weak a bit darker for accessibility seems like a good idea. My one caution or concern in seeing the Figma link above is that it doesn't show or take into account one of the primary use cases for it... which is labeling for disabled inputs and controls.
> 
> If the text-weak become darker, will disabled form inputs still look disabled? Or am I to understand per Eric's comment above disabled inputs/controls would all then use 'text-xweak'?
> 
> I can say that disabled controls now really are light and hard to see... but when 'disabled' they aren't visible to the accessible user (usually hidden from the DOM). If you choose to make disabled controls use a new darker 'text-weak'... you should consider a different presentation/style for indicating disabled, like a grayed out input area or something.
> 
> Just some things to think about...

Thanks Ian, all good points. At the moment we are leaning towards disabled inputs/controls would all then use 'text-xweak' (per Eric's comment above). That said this is still in work in progress, and I'm reviewing the implications of changing the color value of "text-weak" on all existing instances in Figma files.

**Comment by bahriaditi** [comment]
Hi @GinaTaylor @L0ZZI we now have an additional text color for use in the Figma library based on your request. 

So, in effect, the following text colors are available to choose from:
- Text (default)
- Text, strong 
- Text, weak (new)
- Text, xweak (formerly "Text, weak"; for use on disabled states only)

_See screenshot._

@ericsoderberghp I'll create a new issue for implementation on the site. 

----------
Light mode:
<img width="491" alt="Screen Shot 2022-02-03 at 11 21 33 AM" src="https://user-images.githubusercontent.com/87677275/152413939-f1cd4631-5c50-45bb-9bcc-0d5483f815fc.png">

Dark mode:
<img width="499" alt="Screen Shot 2022-02-03 at 11 21 43 AM" src="https://user-images.githubusercontent.com/87677275/152413955-121b4e64-937b-4cba-9838-781cf489bed5.png">
