### ISSUE TITLE
Select - Guidance on multi-select

### ISSUE THREAD

**Issue by StingRay005** [grommet/hpe-design-system#2234]
Merging this ticket with #2207. Closing #2207.

**Existing Design System Resources:**
Figma component: https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=1%3A1027
Site: https://design-system.hpe.design/components/select?q=mult#multi-select
Grommet: https://storybook.grommet.io/?path=/story/input-select-many-options--many-options

---------
**From Taylor:** (#2207)
In our early Filtering work, we strayed away from using Select with multi-select and instead encouraged teams to use CheckBoxGroup.

However, in cases like assigning value-only Tags (https://deploy-preview-2198--keen-mayer-a86c8b.netlify.app/components/tag?q=tag#assigning-value-only-tags), allowing multi-select seems plausible and more efficient for the user.

Similar non-HPE use cases would be when assigning labels to a Github issue, assigning reviewers. You can select multiple labels/reviewers before the drop closes.

------------

**Discussed during 1/20/22 India office hours and 2/2/22 US office hours.** 

Request is for a variant of multi-select to be added to the Design System site and Figma component variant which includes:
- [ ] Multi-select functionality and visual design
  - GL designs are using checkboxes similar to [this](https://storybook.grommet.io/?path=/story/input-select-many-options--many-options), however that is not what is represented on the DS site, nor in Figma.
- [ ] Ability to create new select option
- [ ] Create visual example to demonstrate the flexibility of component based on [@geepriya's](https://github.com/geepriya) work: https://www.figma.com/file/yZyMsoTk6zSn2TgHH257Ea/Ezmeral-Components-V2?node-id=918%3A51121
- [ ] "This is a good opportunity to partner with Storage by validating the design with Sherry Mead and their use cases" - Scott Oja.

**Comment by halocline** [comment]
@MikeKingdom 's implementation: https://codesandbox.io/s/multiselect-vuzkd

**Comment by MikeKingdom** [comment]
I can provide the final implementation used in Quake that uses the HPE theme and a few other details if needed.

**Comment by halocline** [comment]
Scott Oja  12 minutes ago
Here is a link to the DSCC searchable multi-select pattern spec. that we'll eventually need to provide guidance on. https://www.figma.com/file/wZ7ciVTVqHK6zCJN6pps22/SC_Forms?node-id=0%3A1.

**Comment by ericsoderberghp** [comment]
Similar to https://github.com/grommet/hpe-design-system/issues/2207

**Comment by ericsoderberghp** [comment]
I think we should step back to consider a variety of contexts for this, all related to choosing multiple options but differing in aspects of scale. For instance:

## How many options are there?

- When there are only a few options, it might be best to show all of the options with a CheckBoxGroup. However, if there is a good default that will be sufficient 80% of the time, maybe a Select with the right option defaulted would be preferable as it wouldn't compete for the user's attention as much.
- When there are a large number of options, say 1000, then the user likely will benefit from being able to search for the options they want.

## How many options might be selected

- If there are typically only a couple of options selected, showing all selected options might be preferrable
- But, if many options might be selected, it might be preferable to provide the user with a means to reveal all selected options on demand. This might also provide a better means of adding the ability to search among the selected options to see if a particular option is selected or not.

In all cases, keeping the interface simpler tends to make accessible use easier.

**Comment by bahriaditi** [comment]
> @ericsoderberghp as discussed we're breaking this issue into smaller chunks, starting with #2370 So, should we go ahead and close this?

Never mind, @KennyAtHPE is on it!

**Comment by KennyAtHPE** [comment]
Closing this ticket. Use cases, external research, and findings can be found under "Resources" in #2370
