### ISSUE TITLE
Figma - file template for components

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2235]
Create a standardized template to present published components and use cases in Figma, without causing overhead.

**Why we need this:**
- Duplicate documentation on Figma and site is not sustainable and can create a future maintenance nightmare
- We need to promote the Design System site as a single source of truth.

References:
https://www.figma.com/file/vK6LH6vXfdK7euQ7AmEgr4/Components%2C-Templates-%26-Guidelines?node-id=58%3A2025

https://www.figma.com/file/jv2wp5oJNmtGUDhSYYWGWI/SAML-SSO?node-id=1501%3A49996

[Figma file Vicky + Greg started on this topic a while ago ](https://www.figma.com/file/5nHER4TVcxgkHSCCp5kUJo/Organization-and-Documentation?node-id=0%3A1)

**Comment by vavalos5** [comment]
Connected to #1127 https://github.com/grommet/hpe-design-system/issues/1127

**Comment by vavalos5** [comment]
Some ideas on how we might start this process:

- Figuring out the purpose of these templates ( I know it's obvious, but lets write it down)
- Discuss how this is going to be helpful to others
- Look at other [Frameworks](https://www.designsystemsforfigma.com/) to look for inspiration and do a comparative analysis
- Do's and Don'ts - What do we want these guides to do/look like, what do we not want them to do/look like
- Start exploring!
- Ideate!
- Repeat!

This can be edited some more later on... Just jotting some ideas

**Comment by bahriaditi** [comment]
Based on the discussion this morning around component deprecation plans, we need to come up with a plan for how to structure our Figma Design System Project moving forward. This ticket feels relevant to this work, so tracking it here.

- Moving all published components to a single file (instead of having them live in separate files)
- Figuring out where to move previous iterations/ research
- Deciding on way forward for designs that are in WIP + new draft files

@KennyAtHPE feel free to change the description as needed :)

**Comment by KennyAtHPE** [comment]
Things to include in the template for a component's finished page:
- [ ] Overview of component with quick guidance + link to DS site
- [ ] Anatomy
- [ ] How to use component within Figma
- [ ] Chart of all variants
- [ ] Diagram of Component Properties
- [ ] All Interactiveness
- [ ] Any additional templates

**Comment by KennyAtHPE** [comment]
The finished file template can be found [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components?node-id=1249%3A24833). Closing out this ticket
