### ISSUE TITLE
Button - Revise Figma file and update

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2242]
I noticed that we have a lot of work in the WIP section that we might've already approved. We will need to go back to the file and make sure we clean it up and move items from WIP to Finish once they've been approved.

Lets go through the file, clean it up if needed, move items to appropriate pages.

We should also make sure things have been updated on the design system site. If they haven't, lets create tickets for them and let the devs know.

https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=667%3A385

**Comment by vavalos5** [comment]
Aditi and I discussed this last week, and we're ok with closing since she has Keeth working on something similar on another ticket

**Comment by bahriaditi** [comment]
Hi @vavalos5 

- All work in WIP has been moved to the Finished page in Figma
- I reviewed again and looks like all updates were made and published on the site except "Button Ordering"

I'm going to make a ticket for implementing that guidance and then close this issue.
