### ISSUE TITLE
User Research - formPrevious icon vs Previous icon

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2263]
Currently, the "back button" is using `formPrevious` icon from our library. Yet, if I’m using a screen reader and I’m in a detailed view of a card, this wouldn’t make sense to me. We have 2 of these icons: one that falls in the category of Form which is called `formPrevious` and one under Core which is called `Previous`.

So lets further understand:

- How do our stakeholders refer to this icon?
- What would make the most sense to call the icon for our users who use screen readers?
- Work w/ Chris Conetta to create a study on how someone coming to the design system site might look for the "back/up/ascending" button.

**Comment by ericsoderberghp** [comment]
Unfortunately, "FormPrevious" has a "Form" prefix primarily because it is sized similar to other icons used within a Form context. So, it's an unfortunate name in that it's really more of a "Previous" variant. But, we cannot change the name without breaking backwards compatibility.

**Comment by vavalos5** [comment]
I haven't seen the formPrevious icon being utilized within a form. From my understanding, we're using this icon as the main icon within all designs using "back button".

**Comment by britt6612** [comment]
> Unfortunately, "FormPrevious" has a "Form" prefix primarily because it is sized similar to other icons used within a Form context. So, it's an unfortunate name in that it's really more of a "Previous" variant. But, we cannot change the name without breaking backwards compatibility.

Wondering if we could still use `FormPrevious` since it has the desired size but could maybe change the `aria-label` to be `previous`? `FormPrevious` on a screen reader for an ascending Button for example may not make sense to a user that is using a screen reader. Or we can give guidance on how to change the `a11ytitle` prop to be `previous`

**Comment by taysea** [comment]
Closing, current guidance is to use the standard, non "Form" icons.
