### ISSUE TITLE
Navigation - Conduct more research on how teams are supporting breadcrumbs

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2276]
Connect w/ stakeholders to further understand how they're composing different levels of navigation such as ascending buttons, breadcrumbs, etc.. 

What should this section be called? In-App heading? Page Heading?

Related to #2208

People to chat w/:
GLC- Edgar
Aruba - Fred Mouveaux
Data Services - Cheri
Compute - Greg
Ezmeral - Ian
DCE - Janice

**Comment by vavalos5** [comment]
- Gather information from Sherry on how they're handling Breadcrumbs
- Connect w/ Katy on studies to be conducted on for Breadcrumbs

**Comment by taysea** [comment]
Closing, can open new ticket if this pattern comes up in future.
