### ISSUE TITLE
Onboarding - Intro to the Design System team and related processes

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2293]
https://github.com/grommet/hpe-design-system/wiki

For whom:
To facilitate on-boarding of new team members.

Why:
As we scale and bring in new team members (contractors, temporary assignments, interns), it will be beneficial to have documentation around our team's process, including (but not limited to):

- How our Sprint cycle works
- How the GitHub project board works (ex: what each project board column is for)
- Team principles/ values 
- Contribution guidlines/ invitation to contribute
- Communication channels
- Other relevant links - Ex: Grommet, Figma library etc.

As discussed with @taysea , the scope of this work is to create a simple overview of how we work and operate as a team. 

Dev and designer guidance will be tackled separately.

**Comment by ericsoderberghp** [comment]
I'm wondering if we should put most of these in a README.md file and point off to individual wiki pages as needed. This would mirror how `grommet` does things.

**Comment by bahriaditi** [comment]
I created a first pass of this using [Figma](https://www.figma.com/file/fq01PAuHIKAW8JJtVWmfVv/HPE-Design-System-Onboarding?node-id=30%3A747), which gives us the ability to secure any confidential info (email addresses etc.).

@taysea @halocline tagging you both to review this through a dev perspective. 
cc @vavalos5 

Also, as you are reviewing, I'd love to hear your ideas on the format of this document - where should this information ultimately live, so that it is easy to maintain, share and update as needed.

Thank you both!

**Comment by taysea** [comment]
@bahriaditi Thanks for getting this started. Agreed with the considerations for confidentiality.

In terms of the implementation of this and where it lives, some success criteria I'm thinking about would be:
- [ ] Anyone on our team feels comfortable updating documentation/resources (designer, dev, pgm, etc.)
- [ ] Easy to update (team processes change, people shift teams, etc.) since this will always be a living document

**Comment by vavalos5** [comment]
While this document is Design System specific and focused, it is also an onboarding documentation and i'm wondering if we should also include the how to set up your YubiKey + HPE email to this doc. Or we could also link to the docs that Chris and Greg have created. It's a nice reference to refer to even for us who are onboarding others. Plus, when we have issues w/ our YubiKey, we can also reference back to it. I know that these docs live all over the place, but adding to one doc might be nice.

**Comment by vavalos5** [comment]
> I'm wondering if we should put most of these in a README.md file and point off to individual wiki pages as needed. This would mirror how `grommet` does things.

Would this make it hard if you don't have your HPE email set up yet? I think we can have it live somewhere on the site and have it password protected?

**Comment by bahriaditi** [comment]
> @bahriaditi Thanks for getting this started. Agreed with the considerations for confidentiality.
> 
> In terms of the implementation of this and where it lives, some success criteria I'm thinking about would be:
> 
> * [ ]  Anyone on our team feels comfortable updating documentation/resources (designer, dev, pgm, etc.)
> * [ ]  Easy to update (team processes change, people shift teams, etc.) since this will always be a living document
> * [ ]  Some established cadence of when to revisit this and ensure it's up to date (every quarter? just prior to onboarding a new member? etc.)

Agreed with making this an accessible and sustainable doc :)

**Comment by bahriaditi** [comment]
> While this document is Design System specific and focused, it is also an onboarding documentation and i'm wondering if we should also include the how to set up your YubiKey + HPE email to this doc. Or we could also link to the docs that Chris and Greg have created. It's a nice reference to refer to even for us who are onboarding others. Plus, when we have issues w/ our YubiKey, we can also reference back to it. I know that these docs live all over the place, but adding to one doc might be nice.

Agreed that this is important info to have, but not convinced that this Design System team specific doc should cover it. My understanding is that Amanda Vogel is leading the efforts to create a much better and more in-depth experience with instructions for contractors/employees that join, people leaders and onboarding buddies. I would reach out to her directly with any ideas or recommendations. Hope that helps!

**Comment by bahriaditi** [comment]
Here's where we are with the onboarding doc: https://www.figma.com/file/fq01PAuHIKAW8JJtVWmfVv/HPE-Design-System-Onboarding?node-id=30%3A747

I'm going to create a new ticket for finding a home for it, one that is easy to maintain and accessible to both designers and developers.
