### ISSUE TITLE
TextInput - Update Figma component to allow wrapping for field description

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2306]
Update the description based variants of following components in Figma to allow for responsive text wrapping:

**Checkbox**
https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/HPE-Checkbox-Component?node-id=1315%3A1

**Checkbox group**
https://www.figma.com/file/zkQOQRUt8frxiSo67kTkfE/HPE-Checkbox-Group-Component?node-id=64%3A748

**Radio Button group**
https://www.figma.com/file/aZyY606ENQedz4FXugdzgS/HPE-Radio-Button-Group-Component?node-id=78%3A0

**Date Input**
https://www.figma.com/file/Mf9if6zyGETTWW5b9PsYNQ/HPE-Date-Input-Component?node-id=1%3A567

**Comment by gregfuruiye** [comment]
@bahriaditi, I've discovered that TextInput works appropriately when wrapping the description. However, here are the components that do not:

- Checkbox
- Checkbox group
- Radio Button group
- Date Input

These are the ones I've identified so far. The proposed designs for review are in the TextInput WIP Figma file:
https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=3469%3A1073

**Comment by bahriaditi** [comment]
Thanks @gregfuruiye - this is so helpful! I'll look at your TextInput file this week. 
We'll also review the form patterns you've identified in Figma and make new tickets to clean them up where needed.

**Comment by Keeth-HPe** [comment]
@bahriaditi 
Fixed all the broken 'description' components. It now wraps the descriptive texts appropriately. Also published them all. I checked the components, it all works fine for me 👍
Please let me know your feedback.

**Comment by bahriaditi** [comment]
This looks good to me, closing this issue.
cc @gregfuruiye

**Comment by vavalos5** [comment]
@bahriaditi @Keeth-HPe I saw changes were made on the TextInput Figma file but not published. Making sure these are ok to get implemented?
