### ISSUE TITLE
Form - Update optional vs. required guidance for use case when there is a single form field

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2307]
Do we need to show an asterisk to signify required field if there is a single form field? Ex use case: Delete confirmation modal

From Greg (during Office Hours):

> In reading the "required vs optional", I would conclude that no asterisk is needed. Only when both required and optional fields are present do we show which fields are required and which ones are optional. Am I reading that correctly? https://www.nngroup.com/articles/required-fields/

Existing guidance on site: 
https://design-system.hpe.design/templates/forms#required-vs-optional-fields

Recording of office hour session:
https://hpe-my.sharepoint.com/:v:/p/kamlesh_thakur/EVLWTKfqb5RMrSkIzE9vB-gB0GWkWTAq41-GsmZngLWGQg

**Comment by Keeth-HPe** [comment]
Hi @bahriaditi 

Please review the file [here](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=5902%3A12285)
