### ISSUE TITLE
Typography - Add new text-color to theme/site (based on #2230)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2312]
From #2230 

We will need to audit everywhere in the theme/examples where `text-weak` is currently being used and decide if it should be `text-xweak `now

**Comment by britt6612** [comment]
Usage of `text-weak` in Hpe theme 
Button - Disabled Text color
FileInput - Message placeholder
FormField - Disabled Label color
Pagination - Disabled color
Tab - Disabled text color

Usage of `text-weak` in Design System
Filtering - Offline color of the icon
List - First example of the disabled person

**Comment by ericsoderberghp** [comment]
Thanks for the review.
- We should evaluate changing the disabled colors to `text-xweak`, which might have accessibility issues but would distinguish it more from the other text elements.
- We should align the placeholder in FileInput with the placeholder color used for TextInput, Select, etc.

**Comment by britt6612** [comment]
Ill start by changing the colors locally and running it against WAVE to see if anything comes up with accessibility.

Agree on FileInput I will change that to be aligned with other inputs
