### ISSUE TITLE
Accessibility Page - V2 Hierarchy Enhancements

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2322]
Continuation of ticket #2281

**Comment by vavalos5** [comment]
https://www.figma.com/file/proMb3RZasbybYcQsduI7h/Untitled?node-id=2%3A767

**Comment by vavalos5** [comment]
I've:
- narrowed down a lot of content
- removed content
- added imagery
- inserted ideas on removing/adding content

@CitizenFox Do you have time to go through this? The current version on the design system site is located to the right of it for reference on items i've dissected.

**Comment by vavalos5** [comment]
@amandadupell Please take a look at the Figma file to view the new designs 😄

**Comment by vavalos5** [comment]
received feedback and making some small adjustments

**Comment by CitizenFox** [comment]
This looks more approachable. I added a few minor comments to the Figma file but nothing mission critical. Nice work all around!

**Comment by vavalos5** [comment]
Made last changes. While there might be some small other changes, this ticket is good to close.
