### ISSUE TITLE
DataTable - Background color on DataTable header incorrect color

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2325]
The Design System site is showing a bug on the DataTable header. Here's an image of what it's showing:
![Screen Shot 2022-02-07 at 8 49 57 AM](https://user-images.githubusercontent.com/62117454/152839285-e2d98bf6-6bcf-4c9d-a6e6-b235c688c9c2.png)

[Please align to Figma](https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-DataTable?node-id=2390%3A5274). Thanks :)

**Comment by ericsoderberghp** [comment]
meaning without the background color?
