### ISSUE TITLE
revisit Heading sizes 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#2329]
For some sequence, such as H2 small and H3 small, it can be difficult to differentiate between them.

Explore whether to adjust the sizes, perhaps looking across large, medium, and small.
Explore whether we should shift an octave, such that today's small becomes tomorrow's medium.
Consider adding something like a `screen` to Grommet, with values like "phone", "projector". Or, maybe `displayMode` with values like "presentation", "app", etc.

**Comment by jcfilben** [comment]
Closing, no longer relevant. Heading sizes were adjusted during the brand refresh. See https://github.com/grommet/grommet-theme-hpe/pull/310
