### ISSUE TITLE
Layer - Allowing for text wrapping on Side Drawer component title and subtitle in Figma

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2350]
Based on #2297 one remaining tiny bug on Figma component:

<img width="538" alt="Screen Shot 2022-02-11 at 9 55 30 AM" src="https://user-images.githubusercontent.com/87677275/153643848-21d72a70-c911-4970-8c03-7a12e5613fba.png">

**Comment by Keeth-HPe** [comment]
@bahriaditi This is fixed. Thank you!
https://user-images.githubusercontent.com/86280029/153749497-01ee9e01-cbea-4df3-9f2d-72aa6c172c4b.mov
