### ISSUE TITLE
Page Header - explore: research variations in use in products today

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2353]
Gather use cases from following teams:
- [x] Storage
- [x] Ezmeral
- [x] CCS/CCP
- [x] Compute/GLC

Also....
- [x] Gather outside resources/variations
- [x] Accessibility?
- [ ] Share Out

**Comment by vavalos5** [comment]
Link to [Figma Page Header](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?node-id=2%3A3) findings

**Comment by ericsoderberghp** [comment]
Nicely done, interesting to see a variety of detail. Just a few observations: Having a level 1 heading seems universal, as does having page level actions on the right. Ascending button vs. breadcrumbs. Then, how much additional detail about the page belongs in the heading vs. below the heading?

**Comment by vavalos5** [comment]
While i haven't done a share out yet, i'll look for some time to share w/ the team next week. I'm in ideation mode now and awaiting feedback from some stakeholders as i'd like to hear reactions on the simplicity of the approach. This ticket is good to close.
