### ISSUE TITLE
Icons - Revisit Virtual Machine icon design

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2359]
Based on [this Slack thread ](https://hpe.slack.com/archives/C04LMJWQT/p1645027428491099)in the design-system channel

Seems like our current VM icon resembles the VMware logo a little too closely, so we need a new icon design for 'virtual machines'.

[Figma link](https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=261%3A0)

<img width="580" alt="Screen Shot 2022-02-17 at 9 11 50 AM" src="https://user-images.githubusercontent.com/87677275/154535006-e61af0a1-b4d6-4ca7-af25-dfc489c6aae5.png">
<img width="417" alt="Screen Shot 2022-02-17 at 9 12 57 AM" src="https://user-images.githubusercontent.com/87677275/154535049-e150bc30-472e-4709-a1c0-c7d3cc33b876.png">

- [ ] Verify issue
- [ ] Check in with Chris Carlozzi to get more context/ direction
- [ ] Explore new icon design

**Comment by taysea** [comment]
@SeamusLeonardHPE tagging you here

**Comment by SeamusLeonardHPE** [comment]
Closing as stale - 
Design system has access to [new icon library](https://www.figma.com/design/l9N1FUHCbMstMZH5AoAWiP/Stroke-Icons?node-id=510-8444&t=01ig7XdNWq6pG8KU-1) that will launch with the V2 figma component refactor.
A visual check reveals that the virtual machine icon has been updated.

**Comment by jcfilben** [comment]
@SeamusLeonardHPE just flagging that the virtual machine icon on figma doesn't match what we have on grommet icons

Grommet:
<img width="168" alt="Screenshot 2024-09-16 at 11 25 55 AM" src="https://github.com/user-attachments/assets/9a5ad629-9374-43c1-9b80-143f378b34af">

Figma:
<img width="96" alt="Screenshot 2024-09-16 at 11 26 11 AM" src="https://github.com/user-attachments/assets/86108df3-d9d2-4eeb-bc2d-ec8f446deafb">

**Comment by jcfilben** [comment]
@SeamusLeonardHPE do we need a new ticket opened? Which is the correct icon, the one in Grommet or the one in Figma
