### ISSUE TITLE
Banner Notifications - Refine placement/styling guidelines for Global Banner Notifications

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2364]
Based on feedback from the Banner Notifications share out, we should explore and refine our styling and placement guidelines. NOTE: This would be for Global Banner Notifications, NOT page-level banner notifications.

1. Should a global banner notification have a background that runs the full width of the page, but cap the content width?
<img width="1675" alt="Screen Shot 2022-02-17 at 11 14 05 AM" src="https://user-images.githubusercontent.com/12522275/154554193-4614da0c-e36e-4b80-a339-1b606fa575a2.png">

2. Should a global banner notification have space between itself and the global header (but not span full-width)?

<img width="1680" alt="Screen Shot 2022-02-17 at 11 12 08 AM" src="https://user-images.githubusercontent.com/12522275/154554227-67207ce9-6260-4a2f-9d01-cc7c2d23a57c.png">

3. Should there be a hover indicator on the clickable region?

4. Should we allow for more clear calls to action? e.g., anchors or buttons.

**Comment by KennyAtHPE** [comment]
New/updated content from this ticket can be found [here](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=3231%3A12029)

To summarize
1) Yes, this will help differentiate the global banner from other banners (banner messages and page-level alert banner messages)
2) Yes, the spacing should be 12px between the global header and global banner
3&4) Banners themselves should not be clickable, instead provide anchors that will direct users to specified links relating to the notification. As for buttons, I do not believe that they are necessary for global banners based on our use cases but may be applicable for other types of banners. Further exploration and research are needed for those banner variants.

**Comment by ericsoderberghp** [comment]
Unresolved comments will be addressed tracked as part of https://github.com/grommet/hpe-design-system/issues/2387
