### ISSUE TITLE
Multi-Select

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2367]
## Problem Statement
How might we design an accessible, responsive and adaptable multi-select component that enables a user to quickly scan through a list of items, choose multiple options, view their current selection, and edit it as needed?

### Discovery & Research
- [x] #2429
- [x] #2373
- [x] #2563
- [x] #2600
- [ ] Multi-Select - Identify edge cases

### Visual Design
- [x] Multi-Select - Revisit default styling
- [ ] Multi-Select - Example with rich content (related to #2412)

### Interaction
- [x] #2586
- [x] #2594
- [x] #2595
- [x] Multi-Select - Editing selection (removing selection, clearing all selections)
- [ ] Multi-Select - Creating or editing list items (Phase II)
- [x] #2662
- [x] #2696
- [x] #2716
- [x] #2713

### Content Considerations
- [ ] Multi-Select - List order (relevancy, chronological, recency etc.)
- [ ] Multi-Select - Long lists and scroll behavior
- [ ] Multi-Select - Copy guidance (Label, Placeholder text, List item)

### Variants (this section may evolve as we get into design details)
- [ ] Multi-Select - Assigning tags 

### Accessibility
- [x] #2661
- [x] #2740
- [x] #2697

### Documentation
- [x] #2738
- [x] #2739

### Implementation
- [x] #2746
- [x] #2790
- [ ] Multi-Select - Update documentation on Design System site

## Background
Note: This ticket originated from #2234 

## Resources
Figma Link: [Multi-Select](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=1%3A1026)
[Existing Multi-Select components](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=965%3A5827)
Use Cases for Multi-Select - [GLC](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=964%3A1985), [Storage](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=964%3A2148), [Ezmeral](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=964%3A3297)
[Previous user study on MultiSelect (1yr ago)](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=967%3A5203)
External Research - [Carbon, Github, Oracle](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=967%3A4954)

**Comment by ericsoderberghp** [comment]
In addition to the variations based on number of options and amount of detail with each option, I'm wondering if we should consider variations in how many options are selected. For instance, having only a few options selected might lend itself towards showing all of them all of the time. But, having many options selected might mean only showing them upon request. And, if could be a lot, would you want to be able to search the selected options?

**Comment by vavalos5** [comment]
Here's some studies a previous designer and I worked together on where you can find the following on [multi-select](https://www.figma.com/file/grzcCVl5TZILb0hik5sEm6/?node-id=308%3A592):

Current problems
Goals of user Testing
Concepts
Designs Tested (2 concepts)
Results

[Recordings on study can be found here](https://wiki.hpelabs.net/display/HCSS/US19568%3A+Forms+Usability+Testing). Unfortunately, I don't have access to wiki, but i'm sure we can get it if needed.

**Comment by bahriaditi** [comment]
Adding a possible use case that came up in this morning's office hours: 
**Multi-select list that supports the creation of new objects** 

@ericsoderberghp is it safe to say that this is related to the multi-select component?

In the flow below, the user has the option to select or add additional SSH Key/ Volumes to the list of options. In this current design, the two actions of selecting and adding feel disconnected. I wonder if this may be resolved by providing a variant of the multi-select component which supports the ability to create new items. 

Of course we need to validate this need by collecting similar use cases across other apps.

<img width="1147" alt="Screen Shot 2022-04-13 at 11 01 50 PM" src="https://user-images.githubusercontent.com/87677275/163323592-d6f14008-0465-4d07-858a-0a156779b017.png">
 <img width="1245" alt="Screen Shot 2022-04-13 at 11 02 07 PM" src="https://user-images.githubusercontent.com/87677275/163323598-78870eb6-d371-45fc-8456-87612ddd88f2.png">

**Comment by bahriaditi** [comment]
Updating task description, so recording previous description here so we don't lose it, in case we need to reference later:

### Multi-Select with Search
Use case - when many options are present
Searchbar contains placeholder text + icon
Selections and search results are located in separate containers
Selections still appear based on user's searches
Search results are scrollable. Should there be a limit to the number of search results?
By default, amount of selections viewable is limited. Incorporate "show all" and "show less" options
Should there be an option to clear all selections?


### Multi-Select without Search
Use case - when few options are present (recommended for <10 options)
Use CheckBoxGroups
Should all selections be viewable once collapsed? Alternative instead to have a number indicator of how many are selected
Truncate long text and use tips


### Multi-Select variants to consider
Assigning tags
Options containing icons, images, cards, etc.

**Comment by jcfilben** [comment]
Marking this as done. Any additional items will be tracked as separate, individual tickets.
Remaining work:
- https://github.com/grommet/grommet-site/issues/362
- Creating or editing list items (new ticket created: https://github.com/grommet/hpe-design-system/issues/2887)
- Finalize Design System Guidance and publish (Chatted with Kenny this morning and he is planning to create a ticket for this. I will link ticket here once it is created)
