### ISSUE TITLE
Select - Multi-Select with Search V1 Designs

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2370]
Related to #2367 

---------

[Existing MultiSelect components](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=965%3A5827)
Use Cases for MultiSelect - [GLC](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=964%3A1985), [Storage](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=964%3A2148), [Ezmeral](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=964%3A3297)
[Previous user study on MultiSelect (1yr ago)](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=967%3A5203)

External Research - [Carbon, Github, Oracle](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=967%3A4954)

[Current recommendations and areas to explore](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=971%3A4980)

**Comment by bahriaditi** [comment]
@ericsoderberghp Archiving this issue since I updated the tasks in the parent ticket #2367
