### ISSUE TITLE
Multi-Select - Identify variants

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2373]

**Comment by bahriaditi** [comment]
@ericsoderberghp based on requests and discussions in #2234 I think we need to consider the following capabilities for multi-select. Note that is a brain dump of my initial thoughts after reviewing [use cases and research from other design systems](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=986%3A5471). This warrants a thoughtful discussion and I'll set some time on our calendars for next week. 

### 1. Default styling:
We need to review the existing styling and see if we want to update this
<img width="333" alt="Screen Shot 2022-02-25 at 8 23 11 AM" src="https://user-images.githubusercontent.com/87677275/155750431-eddcb838-cd3d-4e09-9329-b2d1d86205ab.png">

### 2. Multi Select with Search:
- Have the ability to have a multi select with Search (not sure if this will need separate variant, given we already have a [select w search](https://design-system.hpe.design/components/select?q=multi#select-with-search))
- Best practices of when to include search (for ex: this could depend on the number of choices)

### 3. Multi Select with Checkbox Group
<img width="416" alt="Screen Shot 2022-02-25 at 8 28 35 AM" src="https://user-images.githubusercontent.com/87677275/155751227-9f5a0ec0-c22e-4251-b75f-b15faff33349.png">


### 4. Multi Select with Actions to select all, view selection or remove selections
<img width="360" alt="Screen Shot 2022-02-25 at 8 32 12 AM" src="https://user-images.githubusercontent.com/87677275/155751813-da1958d9-1a60-461f-81e5-cf3258105f9d.png">

<img width="584" alt="Screen Shot 2022-02-25 at 8 32 19 AM" src="https://user-images.githubusercontent.com/87677275/155751978-13506d2f-bf18-4414-b6e8-a5df4a50bea0.png">


Finally, in all of these cases, and to your point, we need to provide the user with a means to see their selections (especially when the list is long). There are many ways to do this and we need to finalize a design for this.

In this example, the selected options surface to the top of the list:
<img width="310" alt="Screen Shot 2022-02-25 at 8 10 58 AM" src="https://user-images.githubusercontent.com/87677275/155752385-90d7d80a-f210-4c6c-8213-05d6af41df62.png">


From Mike's work:
<img width="302" alt="Screen Shot 2022-02-23 at 1 57 22 PM" src="https://user-images.githubusercontent.com/87677275/155752565-847f94b7-90c7-4272-b483-d7558759f921.png">

From Storage:
<img width="392" alt="Screen Shot 2022-02-25 at 8 41 50 AM" src="https://user-images.githubusercontent.com/87677275/155753281-5320da15-111c-49ce-bddd-61b8ab3d29de.png">

**Comment by ericsoderberghp** [comment]
I like the breakdown above. I might add one more scenario at the end where the list of options selected is so long that search would be helpful, to determine whether an option is currently selected.

FYI, I'm not a big fan of using something that looks Tag-ish to display selected options. I think it's harder to visually scan and doesn't scale well.

**Comment by bahriaditi** [comment]
Discussed with Scott, Eric, Kenny and Jessica and feel like we have a good direction here. I updated the tasks in #2367 as a result of these discussions. 

[Figma](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=987%3A6679)
