### ISSUE TITLE
Banner Notifications - Design v2 page outline for DS site

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2387]
Current [page outline](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=3395%3A11466)

Create variant sections for global banner, banner messages, and page level alert banner messages. Include roadmap section to provide visibility on what's being worked on

**Comment by KennyAtHPE** [comment]
[v2 page outline for banner notifications](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=3231%3A12029)

Focused on presenting guidelines for banners more generally rather than only in the perspective of global banners (moved to its own section under variants).

**Comment by ericsoderberghp** [comment]
I want to clarify that the expectation for this ticket is to finalize for "global banner notifications" and leave placeholder content for other variations of banner notifications, like page and section.

**Comment by KennyAtHPE** [comment]
Objectives for this sprint:
- [ ] Meet with Greg for feedback on current banner guidance
- [ ] Finalize global banner guidance with Eric and Taylor
- [ ] Shareout current guidance to the team

**Comment by KennyAtHPE** [comment]
Got great feedback from the team throughout the week and the current version can be found [here](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=3395%3A11466). Closing this ticket out and will be updating #2366 for implementation.
