### ISSUE TITLE
Layer - Add example where modal size is "content-driven"

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2398]
Follow on to https://github.com/grommet/hpe-design-system/issues/2332

& stemming from Arch & Dev discussion on 2/24/22.

- [ ] Add example to Figma
- [ ] Add example to site
- [ ] Example should be accompanied by copy explaining the purpose and use cases.
- [ ] Consider revisiting the order of the examples provided.

**Comment by taysea** [comment]
Closing, will handle "content" vs "container" driven layouts in separate work.
