### ISSUE TITLE
HPExs Design System Slide

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#2401]
The ask is to take the following slide as a starting point -
https://hpe-my.sharepoint.com/:p:/p/scott_oja/EYu3eZJ4FPNIg7KxF7Us-lIBygcKYgMQsJ41t2OHDjfzLQ?e=fLEzi9

It is a building slide intended for David S. and others in HPExs Team to help communicate the benefits associated with following our HPE design system, building upon the lowest basic atomic tokens all the way up to consistent page layouts to cross product work flows.

Feel free to redesign this to be consistent with our current HPE DS site look and feel. 
To be added is a set of screen captures to show responsiveness that was overlook in the starting deck. Let me know if there are any questions.

**Comment by Keeth-HPe** [comment]
Hi @SOjaHPE 

I have redesigned and prototyped the entire slide on Figma. The first few screens are to show what "Atomic design Methodology" basically is and then also added a simple transition to show the build-up of the diagram that is shown in the PPT.  Please take a look and let me know if there are any changes.

Here's the link to the prototype : https://www.figma.com/proto/HH3l4xY2Uocvyn4QTFKGGM/HPE-DS-Atomic_Blocks?page-id=0%3A1&node-id=3%3A395&viewport=241%2C48%2C0.06&scaling=scale-down&starting-point-node-id=3%3A395

Thanks!

**Comment by bahriaditi** [comment]
Tracking Scott's feedback here:

> - Spoke with David S. and went through your slide. He loves it, having it available in Figma is perfect for most of our stakeholders, there are several folks in HPE Management that don't know how to use Figma so we'll need to get a Microsoft Powerpoint version of the slide, to allow him to easily insert it into his slide decks moving forward.
> - The only feedback item I observed was a glitch at the end of the figma prototype. From the start, clicking on the keyboard it will advance you to slide 8... at the templates slide, the clicking on the space bar doesn't advance you after that point, you have to click on the page to advance to the next 'pages' slide. Continuing to the atomic framework build slide, after it is done building, when you click on the page it redirects you back to the templates page.
> 

@Keeth-HPe once this glitch is resolved, can you mark this ticket as complete, please?
Also– please create a new ticket to track the powerpoint work. 

Thanks!

**Comment by Keeth-HPe** [comment]
Closing this ticket and creating a new issue for the power work.

Thanks!
