### ISSUE TITLE
Tabs - Explore design direction and best practices for responsive behavior

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2413]
We recommend <=5 tabs are used in order to minimize chances that tabs wrap and to keep cognitive load to a manageable level. That being said, we also want to support a fairly flat navigation experience. 

We should explore ways to handle cases when teams need > 5 tabs in a single group.

One pattern I've seen is the concept of responsive tabs. This can be seen on Github with the "Code" "Issues" "Pull Requests": https://github.com/grommet/grommet/pull/5958
- as the user condenses the screen, the tabs to the right collapse into a "..." menu

**Vicky:**
Worked w/ Beza to break this down ticket a bit. Once she's done collecting the items above, I'll create another ticket for her to continue her ideations.

- [x] Screenshots of use cases
- [x] screenshots of outside examples + guidance
- [x] collect accessibility information

**Comment by vavalos5** [comment]
- [ ] Screenshots of use cases
- [ ] screenshots of outside examples + guidance
- [ ] collect accessibility information

**Comment by vavalos5** [comment]
Worked w/ Beza to break this down ticket a bit. Once she's down collecting the items above, I'll create another ticket for her to continue her ideations.

**Comment by vavalos5** [comment]
Beza has completed gathering use cases, research, and some accessibility research. This ticket is completed and ticket #2484 to follow.
