### ISSUE TITLE
Table - Guidance on wrapping

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2414]
Currently on the design system site, we're saying that we can wrap text within a table. However, we need to be more specific as to when exactly you can as we wouldn't want people to wrap all columns within a table.

Action items:

- [ ] Research on best practices/accessibility on wrapping
- [ ] gather use cases of when wrapping would be needed
- [ ] create guidance on when exactly wrapping + examples would be used

**Comment by taysea** [comment]
Closing, we support both and leave it up to the designer to decide was is appropriate for the use case.
