### ISSUE TITLE
Page Header - Contextual Information

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2424]
Identify what goes into the contextual info. How much detail goes here? How much is too much?

**Comment by vavalos5** [comment]
Reach out to stakeholders this week so they can you annotate on the designs/use cases they have while i'm OoO so when I return I have information/understanding of:

- what they're calling this area
- why they need them
- why it's important to the user 
- what's the purpose of it

**Comment by SOjaHPE** [comment]
Please reach out to Gina T. as work on this pattern starts.. 

She provided a list of folks that are working on this effort from the global HFS level. I can provide additional background info too.

**Additional contact info for those that are currently focused to provide:**
* Ross Shepherd, Mark Davis - DCE working on a repo to replace TCaaS Zoomin
* Catherine Lyman, Clai Duvall, Emily Wilton - Tech content on GLC
* Josh Johnson (ezmeral docs)
* Michael Johnson (compute docs)

* Katherine Lyman is the content , technical writer from GLC, PointNext is rewriting their own content repository to replace the TCAS ZoomIn Repository.. use ours, repo in the background.
    * DCE is coding it

Open question regarding all the different interactions and behaviors we'd want across the platform. Might be able to get screen caps from @ecircenis 
    * Q. How is contextual help implemented in GLC? Clicking a contextual help icon opens a drawer, as of now. Is that what we really want to be doing? 


**Storage Use Cases**
From a Mar 17, 2022 mtg discussing 'In Product Doc for DSC in GreenLake'

Attached slide deck screen caps -
<img width="1122" alt="Overview" src="https://user-images.githubusercontent.com/83719939/160197072-8fd4af8b-4ac6-4770-86f4-4a366d77c11b.png">

<img width="1328" alt="Content levels" src="https://user-images.githubusercontent.com/83719939/160197137-bdac340b-644b-48a8-affc-7f8585407573.png">

Field level contextual help -
<img width="1128" alt="Screen Shot 2022-03-17 at 4 08 18 PM" src="https://user-images.githubusercontent.com/83719939/160197207-7b712f6b-0109-43fe-8b30-b68e7963b139.png">

Storages Articles widget
<img width="1139" alt="How can we help you" src="https://user-images.githubusercontent.com/83719939/160197353-d20dc806-ca86-42fd-9851-5e354d7d5e85.png">

Searchable
<img width="1134" alt="Screen Shot 2022-03-17 at 4 10 16 PM" src="https://user-images.githubusercontent.com/83719939/160197407-b0f4b000-eb75-418b-80bf-df91251888cd.png">

Provides a means to have a contextual help ‘articles’ widget up while the user is interacting with the underlying page.
* The user can move the widget around

**Comment by vavalos5** [comment]
I'm not sure how this is relevant to PageHeader? To me, these examples seem to be on the local header rather than the Page Header. Is the idea to have contextual help button live within the page header? Seems more like a Global Header action.

**Comment by vavalos5** [comment]
Reached out to Gina

"It isn't contextual help in just the header. Working on contextual in app help across the entire platform and ecosystem"

We are connecting next week.

**Comment by vavalos5** [comment]
Ready to be reviewed. However, also awaiting a chat on Monday w/ Edgar on use cases

https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?node-id=493%3A40086

**Comment by vavalos5** [comment]
This is good to close. For next week, it'll be a continuation of ideating v2 + share out.
