### ISSUE TITLE
Colors - Update light-mode validation colors values in HPE Theme and document on the Design System site.

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#2425]
Based on  #2339

Update Colors:
- [ ] In HPE Theme
- [ ] On Design System site

The Hex values for validation-warning, Validation - critical & validation-ok have to be updated as per issue #2339 for both Light and Dark Theme.

The color values are as follows : 

<img width="746" alt="Screenshot 2022-03-09 at 11 58 12 AM" src="https://user-images.githubusercontent.com/86280029/157384922-7fa7dad5-f3d6-4a63-802e-20c9bf5aae64.png">

**Comment by bahriaditi** [comment]
Hi @halocline @ericsoderberghp, based on @KennyAtHPE 's share out on the dark mode notification colors this morning, the scope of this ticket should be to only update values for the light theme. 

Kenny is going to create a new ticket for updating the dark theme validation colors on the design side first. Let me know if you have any questions.

**Comment by KennyAtHPE** [comment]
Exploration ticket for dark theme validation and status colors #2446
