### ISSUE TITLE
Page Layouts - update design system site to use new grommet components

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2426]
Update site examples:
- [x] Content Layouts (1)
- [x] Dashboards (3)
- [x] DataTable Customization (1)
- [x] Tags on a Detail Page (1)

Adjusting the actual site to use page/page content (Taylor)

Make Changes in HPE theme

**Comment by jcfilben** [comment]
Site examples have been updated, the site is using Page and PageContent components, and the hpe theme has been updated with the correct width for page
