### ISSUE TITLE
Page Header - When should breadcrumbs be used vs ascending button

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2431]
While there are teams using breadcrumbs and many who don't because the design system doesn't offer it. I've been coming around the same question over and over: when should breadcrumbs be used vs the ascending button?

My inclination is that we want to stick to a hub&spoke model where we always use parent to child and vice versa type of navigation. However, I realize this isn't always the case. Yes, you can use ascending button when you are deep in a hierarchy like Dashboard>Devices>Devices Details, but at what point is a breadcrumb appropriate?

Should we solve for breadcrumbs is even a bigger question..

**Comment by ericsoderberghp** [comment]
Good question! I'd be interested in seeing a few specific task flows that require the use of intermediate breadcrumbs vs. just ascending or home.

**Comment by vavalos5** [comment]
I’m beginning to think that we don’t need to cover breadcrumbs use cases due to the fact that teams should be following our hub & spoke navigation model and therefore should only have 1-2 levels deep per parent page.

According to [NNG](https://www.nngroup.com/articles/breadcrumbs/), breadcrumbs are not needed for flat hierarchies with only 1 or 2 levels that are deep.

**Comment by vavalos5** [comment]
A questions I asked Ian as a follow up

**Q: Hey Ian, how often would you say your users jump between pages when there are more than 3 levels of hierarchy on a breadcrumb?**

**A:** "Hmm..hard to say. Probably not very often for jumping more than 3 levels. I think we only have 2 features, maybe a 3rd in development that even have 3 or 4 levels of depth. I would say there is very little need to jump multiple levels at a time, but there is huge need/value in knowing which level you are on for context. Most users are going to go back and forth between level 2 & 3, or 3 & 4, but without the breadcrumb they would be lost.  One example might be we have a feature for data modeling with topology of  Home > Data Sources > Data Source XYZ > Modeling Files > Model ABC. A user wants to study different data modeling/manipulation scripts on data, they would navigate to a particular data source, then create and work on different models against that data. So in this case 4 levels, and I can see the users going back and forth between model list and  working on a model. Then jumping up to Data Sources to pick a different Data Source to work on and navigate back down to models etc."

**Comment by vavalos5** [comment]
While in the design system. we want our IA to be simple and to follow the Hub & Spoke model, there are teams such as Storage and Ezmeral with more complex flows that have more than 3 levels. I think special use cases such as these require more of a conversation to come up with a solution as some teams don't have the resources or money to recreate those structures. After conversations with Scott, i'm putting breadcrumbs specifically on pause and focusing on finishing out ascending button.

**Comment by vavalos5** [comment]
Considering we're putting anything to do with breadcrumbs or deep levels, we can consider this ticket done since we've got the Up Button defined.
