### ISSUE TITLE
Button Guidance - button ordering

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2436]
This was brought up during office hours (3/9) by Samuel and Edgar.

Should button ordering be static (primary button being first vs. last) regardless of the overall alignment of the buttons?

 [Our current guidance.](https://deploy-preview-2363--keen-mayer-a86c8b.netlify.app/components/button?q=butt#button-ordering)

**Comment by KennyAtHPE** [comment]
Articles to explore:
- https://medium.theoremone.co/button-ambiguity-alignment-order-a42736e25334#d4fc
- https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/
- https://balsamiq.com/learn/articles/button-design-best-practices/#5-in-small-windows-the-primary-action-button-should-be-placed-at-the-bottom-right
- https://balsamiq.com/learn/articles/button-design-best-practices/#6-full-page-designs-should-have-the-primary-button-on-the-left-side-of-the-page

**Comment by britt6612** [comment]
Next steps:
Go through some of those resources I've linked to evaluating whether or not we want to change our current guidance

**Comment by halocline** [comment]
Closing in favor of https://github.com/grommet/hpe-design-system/issues/3387
