### ISSUE TITLE
Table - resolve units differences

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2441]
There is one example of units in the Figma file: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-DataTable?node-id=2390%3A13237
but I suspect this is a carryover from other designs and wasn't necessarily offered as design direction. There is no mention of "units" in the published designs.

The grommet DataTable `units` are currently rendered without parentheses with `text-weak` color.

We need to decide which direction to go and then unify Figma, the theme, and the site.

To Do:
- [x] Implement Design System site examples using `units` on DataTable
- [ ] Determine theming on design side
- [ ] Update Figma examples
- [ ] Update grommet-theme-hpe

**Comment by taysea** [comment]
@CillianHPE @SeamusLeonardHPE can you confirm if we are aligned across dev and design on this?

**Comment by CillianHPE** [comment]
@taysea 

It's hard to see Eric's example as the link just lands on the cover page. 

But to the question of if units are being displayed in the refactored Table.

Yes, it's part of the Header Cell type and it's styled using **Text Weak**.

<img width="791" alt="image" src="https://github.com/user-attachments/assets/ff0fee4d-b7a5-44d2-b4da-364ceac5b32d">

**Comment by taysea** [comment]
Great, I was meaning current dev on our docs site and Figma. From what you're showing here, looks good. Closing, thank you!
