### ISSUE TITLE
Forms — Audit examples and page structure

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2443]
The Forms page structure is inconsistent with made of our other pages. Additionally, some of the examples being shown feel random / unhelpful. Wondering if we can audit and make sure we are showing helpful, realistic forms with appropriate guidance.

**Comment by ericsoderberghp** [comment]
Is this essentially the same as https://github.com/grommet/hpe-design-system/issues/745? If so, can we add to that one instead and move it back into Triage?

**Comment by halocline** [comment]
> Is this essentially the same as #745? If so, can we add to that one instead and move it back into Triage?

Wow. 2 years later, I think I am still largely in agreement with my thinking at that time 🤪  -- normally, there's a bit of drift. Kidding aside, the outline, guidance, and direction still resonate with me and feel right.

**Comment by taysea** [comment]
This is a repeat, closing this in favor of #745. Adding 745 into triage instead.
