### ISSUE TITLE
Site Selector - "app-wide" filter

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2445]
A ticket Eric suggested: What about something like an "app-wide" filter like a site selector?

Use case came from Edgar. I've already followed up with him to gather these use cases. I'll set some time w/ him to get a better understanding

Identify why it's living within the PageHeader currently and whether it's a common experience.

Refer to main PageHeader ticket for conversations on this item.

Currently i'm unsure and a little hesitant to include this use case as it's 1 special use case and it has already been talked about to be move to the Global Header later this year.

**Comment by vavalos5** [comment]
I'm a little hesitant to include the site selector use case after some chats with Edgar. Especially if the idea is to change where it lives at the end of the year.

Edgars comments:

"Here are three things to consider: The first two are from our unified private cloud designs for March demo and June-Sept production. The first is our "homepage", and the second is an example of what the user would see if they were to click on the "Virtual Machines" button in the navbar on the first. But, there are drawbacks to this hub/spoke approach. We want the entire app suite to be subject to a single site selector -- so that, no matter where/how you navigate, the selector is global and applies both for forward and backward navigation. To that end, I am working on a NorthStar concept for UPC inside of GLCP. A year from now, we should not need to have many stacks of headers like we have today (e.g. the first example has three headers - yuck). So, I am ignoring current constraints and dropping down to a single header at the highest level and placing a site selector there.
<img width="818" alt="Screen Shot 2022-03-25 at 8 21 07 AM" src="https://user-images.githubusercontent.com/62117454/160149804-c4044194-39e5-45b1-a611-b1237fc70068.png">

**Comment by vavalos5** [comment]
Upon having a conversation with Edgar, it sounds like this is no longer a requirement the Design System needs to worry about as it is now implemented into the Global Header which UCEP owns. Is it safe to say that this can be closed @ericsoderberghp 

See screen shot below where site selector is on Global Header.
![Screen Shot 2022-04-18 at 11 46 36 AM](https://user-images.githubusercontent.com/62117454/163861811-7d821296-ec73-484c-abc8-b21c6b4b80b9.png)
?

**Comment by ericsoderberghp** [comment]
Yep. We can re-open if the need returns.
