### ISSUE TITLE
Navigation - Reverse Anchor Guidance and Visual adjustments

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2448]
After going through research/testing and have reviewed through feedback and implementations, create guidance and best practices on the use of the ascending button

**Comment by vavalos5** [comment]
I've changed the name on the PageHeader work i've been doing to "reverse button". Don't think this a PageHeader specific ticket anymore, but a Navigation change to make. Will update title and re-add to triage column.

**Comment by vavalos5** [comment]
Will also have to await on Chris Connetta to understand any insights to see if we need to change or adjust guidance.

**Comment by vavalos5** [comment]
Changed the name to "Reverse Anchor Guidance and Visual Adjustments" as this ticket will serve as any needed changes to the Reverse Navigation page. Changes to be made will be added once we get to this ticket.

**Comment by ericsoderberghp** [comment]
Superseded by #2580
