### ISSUE TITLE
Page Header - Further annotate use cases

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2449]
While i'm OoO next week, i'd like our stakeholders who i've collected use cases to annotate their use cases so I can further understand what they're calling certain areas such as the contextual part.

I'd like to further understand what type of information lives there, why it's important and how important is it to have it there.

Another question is, how much information should go there and when is it too much?

**Comment by vavalos5** [comment]
I've chatted w/ Sherry this morning. Gathered some screen shots. While i'm out, i've asked Sherry to get me a Figma file w/ the rest of the use cases.
![Screen Shot 2022-03-11 at 8 42 50 AM](https://user-images.githubusercontent.com/62117454/157912316-cb3e808f-9767-42a2-8b17-22891ed8dd48.png)
![Screen Shot 2022-03-11 at 8 42 30 AM](https://user-images.githubusercontent.com/62117454/157912320-b1c75f6f-f297-4ead-96cd-9cab9a6a35a6.png)
![Screen Shot 2022-03-11 at 8 40 54 AM](https://user-images.githubusercontent.com/62117454/157912325-bd90b26f-d626-451a-8cb9-b57a928f4e9d.png)
![Screen Shot 2022-03-11 at 8 40 41 AM](https://user-images.githubusercontent.com/62117454/157912327-1395cb14-fd36-4246-b4b4-e2a991a5ec62.png)
![Screen Shot 2022-03-11 at 8 40 17 AM](https://user-images.githubusercontent.com/62117454/157912328-74c67748-ab04-4543-b917-e3cdd1dc0767.png)
![Screen Shot 2022-03-11 at 8 39 18 AM](https://user-images.githubusercontent.com/62117454/157912329-70e7f255-0ba0-4e9a-94bf-7f963b44bd77.png)
![Screen Shot 2022-03-11 at 8 39 09 AM (2)](https://user-images.githubusercontent.com/62117454/157912332-88a9f5a7-1ede-4414-9e45-38c3143360ae.png)
![Screen Shot 2022-03-11 at 8 39 08 AM](https://user-images.githubusercontent.com/62117454/157912336-70294305-5885-4260-9e59-3d6f2619f73f.png)
![Screen Shot 2022-03-11 at 8 38 37 AM](https://user-images.githubusercontent.com/62117454/157912337-960f7c68-176b-4c5a-b699-cdc48273c057.png)




Also from Edgar: 
"Here are three things to consider:  The first two are from our unified private cloud designs for March demo and June-Sept production.  The first is our "homepage", and the second is an example of what the user would see if they were to click on the "Virtual Machines" button in the navbar on the first.  But, there are drawbacks to this hub/spoke approach.  We want the entire app suite to be subject to a single site selector -- so that, no matter where/how you navigate, the selector is global and applies both for forward and backward navigation.  To that end, I am working on a NorthStar concept for UPC inside of GLCP.  A year from now, we should not need to have many stacks of headers like we have today (e.g. the first example has three headers - yuck).  So, I am ignoring current constraints and dropping down to a single header at the highest level and placing a site selector there."
![image (29)](https://user-images.githubusercontent.com/62117454/157911686-35bd3333-2a0b-4831-971e-6ae46b6308e9.png)
![image (27)](https://user-images.githubusercontent.com/62117454/157911818-7f4c9dac-bb70-4e5a-ae12-eff54ac27ecc.png)
![image (26)](https://user-images.githubusercontent.com/62117454/157911905-7810daa2-441f-4140-9125-cf9fc116955d.png)

**Comment by vavalos5** [comment]
Awaiting a file from Ian and Sylvia. They will send it to me while i'm OoO.

**Comment by bahriaditi** [comment]
From Sylvia:

> Maggie has add her annotation on [Vicky's research page](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?node-id=228%3A6100). From my end, I think Vicky had covered most of the usecases in her file but here is a [GLCP heading style research page ](https://www.figma.com/file/zfPcP1O1xfgtD0gLP9amNx/GLCP-page-header--research?node-id=685%3A3242)for your additional resources

I also reached out to Ian today who said he'll send something today.

**Comment by vavalos5** [comment]
Thank you @bahriaditi for taking this and following up. I'll take over from here.

**Comment by vavalos5** [comment]
i think this can be closed. I've received all annotations and have gone through them.
