### ISSUE TITLE
Table - Guidance for when a row has a vertical list

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2455]
_Chandan Tiwari brought this up during Office Hours (Mar 16, 2022)_

**Use case:**
See Machine Inventory column in the table below:
<img width="699" alt="Screen Shot 2022-03-16 at 8 25 11 AM" src="https://user-images.githubusercontent.com/87677275/158627400-3c3ffcbc-ca55-4888-9806-4bfe50415907.png">

**Comment by vavalos5** [comment]
Here's another use case:
https://portal-ext-fut.support.hpe.com/connect/s/designsystem?language=en_US&tab=Tables
<img width="1382" alt="Screen Shot 2022-03-24 at 2 37 37 PM" src="https://user-images.githubusercontent.com/62117454/160014683-ffceafd8-d828-485d-b2f0-a60b0f8a7e30.png">
