### ISSUE TITLE
Colors - Extend color palette for use with graphics

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2456]
Request from Sam Goff during Office Hours (Mar 16, 2022)

This will help especially with data viz - charts, bar graphs etc.

**Figma explorations from Sam**
https://www.figma.com/file/l3FDIpjasWopkb15HaVPrP/Bare-Metal?node-id=0%3A1

https://www.figma.com/file/jFd4pwFAI7RA9Zn8DXAocK/Widget-Concepts?node-id=12%3A0

- [ ] Regroup with Chris Carlozzi on HPE color palette
- [ ] Align with Brand

**Comment by taysea** [comment]
@SeamusLeonardHPE @oliverHPE In case these links are helpful for reference in datavis color explorations, tagging you.

If you feel our direction is clear enough, feel free to close.

**Comment by SeamusLeonardHPE** [comment]
Closing as this work has been surpassed by Joelle and Olivers work on for tokens color:

https://www.figma.com/design/N8hC3gZtlqMcOsOxWQoHhB/Data-Visualization-Colors?node-id=0-1&t=BZ6krRQTPVsG0ScY-1
