### ISSUE TITLE
Navigation - URL guidance

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#2461]
Adding as a placeholder, based on sync up conversation with @ericsoderberghp

**Comment by ericsoderberghp** [comment]
Let's leave the title guidance as a part of https://github.com/grommet/hpe-design-system/issues/2451 and convert this to just URL guidance.

**Comment by SOjaHPE** [comment]
This ticket is related to the Navigation Pattern: Reverse Navigation / Browser Back Button guidance section. It is important from an implementation perspective we define the experience that our customers will encounter when hitting the browser back button. There needs to be unique URL's at points in a flow so the user's perception of the 'last page' maps to how a flow is coded. It would be a big usability issue if minor partial page refreshes are captured in the browser 'back' page history, as an example.   
**Reference article which captures this -**
https://baymard.com/blog/back-button-expectations

**Comment by taysea** [comment]
Closing, current guidance is published here: https://design-system.hpe.design/templates/ascending-navigation
