### ISSUE TITLE
Process - Contribution model proposal deck for DS Council

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2468]
_Original issue: #1991_ 

**Goal:**
To show the DS Council that there is momentum from our side, communicate and express our plan/vision and that we're executing on that. Allowing us to scale and meet the needs of all BU's.

**Outline:**
- Definition of what qualifies as a contribution - ‘what’
- Importance of contributions - the ‘why’
- Types of contribution: Scale and level of effort for each type
- Tools we can leverage for contributions: Figma, Sandbox
- DS core team in a steward capacity: train and pair with contributors, maintain a positive environment that fosters collaboration
- Things to consider for each contribution: Shared need across teams, cost of dev (time & effort needed)
- Possible blockers to people contributing
- Incentives to encourage contributions

**Comment by taysea** [comment]
Closing, can create new tickets when the DS Council begins again.
