### ISSUE TITLE
Form - Help text for asterisk meaning

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2475]
Office Hours 3/23 It was brought to our attention that users may not know what * means we should explore looking at adding a help text above a form explicitly saying what the asterisk means

**Comment by taysea** [comment]
According to NNG, an asterisk is a suitable and standard way to mark a required field. https://www.nngroup.com/articles/required-fields/

It feels like an industry standard.

**Comment by bezAdane** [comment]
Based on our research that we have gathered, asterisk has become very common on the web and users are familiar with its meaning. Its main advantage is that it does not take up much space and looks different enough from the label text. Also it is important to mention using an asterisk to mark form required fields  is an easy way to improve the usability of your forms. In this [Figma file](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=5332%3A11280) you will find guidance on common use of Asterisk (  * ) . Also for more information and guidance you can [View full guidance on HPE Design System Site](https://design-system.hpe.design/templates/forms?q=forms)
