### ISSUE TITLE
HPExs Design System Slide - Create Microsoft Powerpoint version of the slide

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#2479]
Based on #2401 

Create a Microsoft Powerpoint version of the Figma prototype created earlier.

**Comment by Keeth-HPe** [comment]
Hi @SOjaHPE 
[Presentation.pptx](https://github.com/grommet/hpe-design-system/files/8371384/Presentation.pptx)

Here's the Powerpoint version of the Figma prototype created earlier. Please do take a look at it, and feel free to let me know if there are any changes :)

**Comment by SOjaHPE** [comment]
@Keeth-HPe  Thank you for posting the new slide deck. It looks great considering it doesn't have all the smooth transitions of Figma but it does the job conveying the concept. My only feedback is related to either a missing character or image.. see the callouts in the inline image.

<img width="928" alt="Screen Shot 2022-03-29 at 9 17 30 AM" src="https://user-images.githubusercontent.com/83719939/160646154-b5039ea7-513b-4c02-bb95-7d403baf25ce.png">

I'll forward your link to David S. for feedback.

**Comment by Keeth-HPe** [comment]
Hi, @SOjaHPE 
Apparently, Powerpoint does not support transitions like in Figma, but I now found out that it supports Gifs. So I can add the transitions as gifs to the slides. To make it more appealing. 
And, yes, I will fix the ' missing character'

**Comment by Keeth-HPe** [comment]
@SOjaHPE  Tried my best, but was not able to add the transitions, gif don't really work while presenting. However, the missing characters are fixed :)

**Comment by SOjaHPE** [comment]
@Keeth-HPe  thank you for addressing the missing char issue. The last open item for this ticket is to use the correct HPE marketing 9:16 pptx template. Let me find out from David S. whether he prefers the light or dark version.
