### ISSUE TITLE
Figma - Prioritize new components to be built

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2482]
## Problem Statement

How can we provide the most value to designers in other teams be updating our older Figma components in the right order?

## Deliverables

- an initial prioritized list of components with any relevant notes

We just need a first pass at this. We can update down the road as we learn new things.

----

Related to #2483, #2450

**Areas to explore**
- Figma Analytics
- Identifying base components
- Focus on components requested by GLCP, Storage, and Ezmeral

**Comment by KennyAtHPE** [comment]
Moving this into the to do. Will be focusing on #2483 for this week before taking this on

**Comment by KennyAtHPE** [comment]
The first component built - #2561
Built using - #2495

**Comment by KennyAtHPE** [comment]
Currently planning to work on the family of input components:
- TextInput
- MaskedInput
- DateInput
- FileInput
- TextArea
- FormField

**Comment by KennyAtHPE** [comment]
Moving this back into to do until we've finished the input components.

**Comment by KennyAtHPE** [comment]
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

**Comment by vavalos5** [comment]
List of related issues can be found in this [Github Backlog](https://github.com/orgs/grommet/projects/13/views/1)

**Comment by vavalos5** [comment]
Calling this done :)

**Comment by KennyAtHPE** [comment]
I will be meeting with @bahriaditi and @SOjaHPE to identify the next couple of components to prioritize after #2688 is completed

**Comment by KennyAtHPE** [comment]
Priority List

Button
Menu
List
ToolTip
Cards
Tabel

**Comment by KennyAtHPE** [comment]
Prioritized List can be found [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2438%3A45572)

**Comment by ericsoderberghp** [comment]
Are there any dependencies between components that is driving the ordering? Also, are there any logical groupings that might help galvanize the work? For instance, doing Button, Menu, and List as the first group?

**Comment by KennyAtHPE** [comment]
@ericsoderberghp some considerations that went into this order:
- Starting at the most atomic level first and building up (ex. Buttons are used in Lists and Lists are used in Cards).
- Figma analytics + feedback from other teams. More info in #2745

Open to grouping them and doing a larger release, don't think time-wise though that it will fit all within one Sprint cycle.

**Comment by ericsoderberghp** [comment]
I wasn't thinking of grouping within a sprint but more as a sort of a milestone goal. Rather than having just a long list instead having a few groups that would help give us a sense of interim progress. Perhaps "batch" would be a better term than "group". One other idea was that the grouping might facilitate us having a work together session for a half-day, where a group of us are in a virtual room and working on them in parallel, spreading the effort but trying to make it a bit more fun.

**Comment by bahriaditi** [comment]
Makes sense to prioritize in batches. I think when we get to this next phase, we can decide on details of how best to approach this and set some timelines internally.

@KennyAtHPE I updated the sandbox section with the 3 main contributions in order of priority.

**Comment by KennyAtHPE** [comment]
Everything looks good to me, will be sending out a message on the design system channel for more exposure. Closing out this ticket.
