### ISSUE TITLE
Tabs - Best Practices + Responsive Behavior Share out + Feedback

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2484]
This ticket is a following ticket from #2413 as research is completed. For this week, Beza will be creating a deck for a share out, gather feedback and implement any changes.

- [x] create deck
- [x] share out
- [x] gather feedback

**Comment by bezAdane** [comment]
Did a share out on Thursday and got feedback. Reached out to stakeholders after a share out to further understand a use case asked during a share out. The question & comment  that came from a share out using Vertical vs horizontal tabs. I went back and got use cases from Sylvia.  Next steps, I am going to be brainstorming with dev. teams to continue exploring designs and possible options when we have more that 5 tabs.
