### ISSUE TITLE
Typography - Establish guidance for subtitle and descriptive text treatment

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2490]
In 3/30 Office Hours, a question was raised about the lack of text hierarchy between subtitles and descriptive text in some patterns.

![image](https://user-images.githubusercontent.com/12522275/160922452-e27aba07-7bd9-4af2-a273-ad8eb8a69c43.png)

TO DO:
- [ ] Establish design treatments for subtitle text and descriptive text
- [ ] Add guidance to site
- [ ] Update examples accordingly
- [ ] Follow up with Chandan Tiwari who raised this issue and Ian Erickson who mentioned Ezmeral currently has a pattern for this

**Comment by eddieshowcase** [comment]
Here is what we have for Ezmeral team on the subject of Modals and Drawers for title, subtitle, description text patterns..

<img width="989" alt="Screen Shot 2022-03-30 at 9 28 27 AM" src="https://user-images.githubusercontent.com/7239901/160943491-86499543-539b-4e7b-ab82-2edb1f5af262.png">

<img width="472" alt="Screen Shot 2022-03-30 at 9 27 58 AM" src="https://user-images.githubusercontent.com/7239901/160943494-8e68649d-a595-4f5d-b4ce-5e7b1a84940a.png">

Also see more guidance and examples in our Figma file here: 
https://www.figma.com/file/yZyMsoTk6zSn2TgHH257Ea/Ezmeral-Components-V2?node-id=164%3A13413

**Comment by vavalos5** [comment]
Feeling like we can close this since we have a new brand refresh. Any thoughts..? Anyone? :)

**Comment by taysea** [comment]
I've seen some differences in typography sizing for layer subtitles, etc. across services. I think my questions are:
1. Do we have a firm stance on what these treatments should be?
2. If we do, is that clear in the existing guidance we have published?
3. Does it still hold with v5 refresh?
4. Are there any stakeholders we should connect with to ensure this guidance is on people's radar screen/that they're on board?

I imagine this could be time-boxed to a few hours for questions 1-3.

**Comment by taysea** [comment]
Closing, stale.
