### ISSUE TITLE
Form - Add guidance for Terms and Conditions Agreement flows

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2493]
Ideally we allow the user to just accept the terms and conditions without requiring the user to scroll through the content, but we should double check EULA rules.. might need to check w/ legal. Could be product line specific?

![image](https://user-images.githubusercontent.com/12522275/160927708-f1d2f847-fc6b-4791-ac5a-bed96f179af4.png)

TO DO:
- [x] Double check legal rules
- [x] Add guidance to site
- [x] Add an example to site
- [x] Follow up with Chandan Tiwari who raised this issue

**Comment by bezAdane** [comment]
Here are some respond i got from what rules from business  GLCS use from stand point of EULA for terms & conditions.
<img width="983" alt="Terms conditions" src="https://user-images.githubusercontent.com/101587768/170347535-bcf8a5eb-d683-4498-b28b-ffccf3acac8f.png">

**Comment by bezAdane** [comment]
@ericsoderberghp @SOjaHPE
 Amenda and her team are still have yet to complete the terms and conditions as a standard for her team but [this recent design](https://www.figma.com/file/4sq7AcKoyCJvU0P8hn1oPK/Add-on-Management?node-id=391%3A47695) has been approved. For more context, I will upload the recording that demonstrates some of the conversation  around their thought process in Cloud Service once i get the access. Please let me know if you have any questions/ comments?

**Comment by bezAdane** [comment]
@ericsoderberghp @SOjaHPE 

Here more context--  per, Amenda Vogel, Tiwari, Chandan
 [this recording ](https://hpe-my.sharepoint.com/personal/chandan_tiwari_hpe_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fchandan%5Ftiwari%5Fhpe%5Fcom%2FDocuments%2FRecordings%2FLicensing%20Agreement%20Text%20Review%2D20220520%5F193252%2DMeeting%20Recording%2Emp4&parent=%2Fpersonal%2Fchandan%5Ftiwari%5Fhpe%5Fcom%2FDocuments%2FRecordings&ct=1655837417912&or=OWA%2DNT&cid=ba67a81f%2Dc7c1%2D2baa%2Dda2f%2Ddfd93e8d9be0&ga=1)demonstrates some of the conversation around our thought processes in Cloud Services .

**Comment by bezAdane** [comment]
Tabor, Todd is the legal person of contact to respond and gives direction to terms and condition guidance.  He is out of the office through July 6. @SOjaHPE shall we still  keep this ticket in progress?

**Comment by bezAdane** [comment]
I have created  the Terms and Conditions guidance, Reviewed with @britt6612 & @taysea added guidance to our site.              

 Attached the figma link for a reference based on Todds advice which is to move to the  [Simple link approach](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=6843%3A13279). Closing this ticket.

**Comment by ericsoderberghp** [comment]
We shouldn't close the issue until the pull request with the guidance is merged so the site is updated.
