### ISSUE TITLE
Figma - V1 Create guidelines on how to make new components

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2495]
**What to include:**
- Common properties/values found across all components
       - States
       - Descriptors, error messages, footers, etc.
       - Sizing
       - Dark/Light mode
- Auto layout and text wrapping consistency
- Resizable and swappable elements if applicable
- Optimal ways to build a master component(s)
        - Avoid clutter in search and instance window
        - Streamline editing and publishing
        - Naming conventions
        - Semantic versioning ([Figma plugin](https://www.figma.com/community/plugin/1046106377087666849/Semantic-Versioning))
- Differences between component sets, components, and variants
        - When to build what
        - Explore terminology
- Interactive components

**Gather initial feedback from:**
- GLCP
- Storage
- Ezmeral
- Understand how this will have an effect on the dev's perspective

**Comment by Keeth-HPe** [comment]
https://www.figma.com/file/IpxvTNHkD0Oz2GXw3KWgcw/Audit---HPE-Design-System-Library?node-id=303%3A7027

A document to help designers run through before creating a new component.  (WIP) 🚧

**Comment by KennyAtHPE** [comment]
#2561 was a test run for the V1 components. V2 will be based on extra findings from that, will be closing out this ticket.
