### ISSUE TITLE
Navigation - Navigation Changes Visual Updates

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2519]
Scott and I to go through this on a weekly basis.

- Update visuals on Navigation pages so there is a hierarchal flow
- Update any new name changes

**Comment by vavalos5** [comment]
@SOjaHPE How do you feel about us closing this ticket since it's not "trackable" in a one week sprint? Instead, I can create tickets based off of what's next after we do reviews together.

**Comment by SOjaHPE** [comment]
@vavalos5  yeah I think it is okay to close this one. Sounds good.
