### ISSUE TITLE
Figma - global HPE header component

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#2543]
Since the Design System has worked with platform to create a new HFS based on grommet and the design system, we need to create an equivalent one on the designer side in figma. 

Since no official HFS component has been created, that has introduced inconsistency across the BU's that have rolled their own. As HFS requirements change it increases the overhead across the design teams to remain current. 

It would be good to align the grommet reference we built for the HPE team that delivers the official one. 

The DS designer will need to work with Gina T. during the implementation in a pair coding manner to ensure it meets her expectations. Moving forward, Gina T. would need to follow our contribution process as bugs, enhancements or major changes are proposed.

**Latest HFS specification**
https://www.figma.com/file/AbxAC3KU59pPyHG5mnnh7R/HFS-North-Star?node-id=2819%3A83081

**Comment by Keeth-HPe** [comment]
Closing this ticket, as we have our new [GLOBAL HEADER](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3028%3A58745&t=ocpzaS4q4wSjwJc8-1) component in our HPE design system. 

@SOjaHPE
