### ISSUE TITLE
Multi-Select - create problem statement

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2563]
## Problem Statement

- How might we create a useful problem statement for multi-select work?

## Deliverables

- problem statement for multi-select

**Comment by bahriaditi** [comment]
Hi @ericsoderberghp, I updated the parent task description here: https://github.com/grommet/hpe-design-system/issues/2367. Moving to review column - please let me know if you have any feedback! 

cc @SOjaHPE

**Comment by bahriaditi** [comment]
How about:

> How might we design an accessible, responsive and adaptable multi-select component that enables a user to quickly scan through a list of items, choose multiple options, view their current selection, and edit it as needed?
