### ISSUE TITLE
Form - How to handle adding, editing, removing groups of items.

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2570]
As shown in the examples below, the problem space is when there are multiple items, where each item has multiple fields associated with it. The need is to be able to add and remove items as well as edit the associated fields.

We'd like to avoid the extra border box as a delineation of items. One suggestion is to leverage typography a bit more.

ToDo's:
- [x] clarify the problem statement. Reach out to Ezmeral, Uma, and Revanth to collect use cases
- [x] Explore/ research
- [ ] Come up with a few alternative designs that are ready for internal review (this will be broken into a separate ticket )

**Comment by Calypso4597** [comment]
Hi, my name is Sanmid and I am from the Ezmeral UX team working with Ian. Here are some of the use cases for this in Ezmeral. We are using the small light button with the trash icon across multiple selections.

![EzSideDrawer](https://user-images.githubusercontent.com/31819567/182207997-08518572-7187-4237-8cd2-364c16df6fd5.png)
![Gloabal Side Overlay-1](https://user-images.githubusercontent.com/31819567/182208001-c6bba061-69ba-443f-952a-d30654eae585.png)
![Gloabal Side Overlay](https://user-images.githubusercontent.com/31819567/182208002-b3325ff4-e7ae-4d60-84b5-11b6251d8616.png)

**Comment by bezAdane** [comment]
Needed to get more insight for the use case provided and will meet today with Geetha, and Revanth/Keeth. Also communicating with Ries and Lauren and from research team  whom is putting together for me what best practice and WCAG requirements. this should be moved  to review in the next 2 days.

**Comment by bezAdane** [comment]
Will close this ticket today once i create a new  follow up ticket for " ideation/ alternative designs iterations".

**Comment by bezAdane** [comment]
Closed this ticket and opened a new ticket for ideation.[#2859 ](https://github.com/grommet/hpe-design-system/issues/2859)
