### ISSUE TITLE
Navigation - Adjust main page guidance

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2578]
### Design Challenge
Using the feedback and findings and research on Navigation, adjust the guidance and visuals on the Navigation home page to represent easier to comprehend material. Material on the Navigation page should take stakeholders to the proper pages ( e.g. Drill Down, Side-to-Side, Reverse Button for Navigation and Cross Navigation) to provide further details. The material should present the proper cross links on the Navigation home page and be usable by keyboard and screen reader users.

### Deliverables
**Assessment**
 Based on the feedback, findings and research for Navigation, evaluate whether the guidance shown in the Navigation Home Page:

-  Create a cohesive story
- Introduce the proper Navigation terminology
- Introduces the Hub&Spoke model we refer to in types of Navigation (by having a shallower hierarchy, we can avoid having local navigation and avoid depth)
- Recommend the Hub&Spoke model and explain that this provides the opportunity to provide more width within designs, more focused on the functionality than the depth. 
- Recommend and explain how users should know where they are in the hierarchy so they're not disoriented
- Recommend the proper summaries for each type of Navigation
- Visuals are properly representing Navigation type 

**Recommendation and rationale**

- Adjust guidance and visuals on the Design System site for our audience
- Should present all Navigation types in a cohesive and easy to understand manner across each Navigation type
- Should be easier to read and understand for all levels (Jr.-Sr.)
- Work with new content strategist, Dahlia for input
- Work with Chris Carlozzi on visual representations
- Include real product examples
- Navigation types should navigate to proper links
- Story should properly flow (Intro, types of Navigation, Cross links, etc..)
- Create follow on issues for each type of Navigation
- Provide implemented example to stakeholders as new adjustments once completed and approved

### Background
Research conducted with Chris Conetta on Reverse Button (previously Ascending Button) and chats with Scott have pointed out that our guidance on the different types of Navigation has been hard to understand. We want to create an easier to follow Navigation home page so our stakeholders can find the guidance needed when working on building application or services navigation.

### Others
- Need to go back and listen to recording on notes Scott and I made before making changes

**Comment by vavalos5** [comment]
Changes Chris and I made to the Navigations visuals:

Before:
![Screen Shot 2022-05-10 at 4 13 42 PM](https://user-images.githubusercontent.com/62117454/167739644-36beec4f-e229-44ed-8e2e-691ca0dc9769.png)



![Screen Shot 2022-05-10 at 4 12 14 PM](https://user-images.githubusercontent.com/62117454/167739552-8b60e905-41b8-481f-af56-b8f4f9567fa4.png)


@ericsoderberghp @SOjaHPE What are your thoughts?

**Comment by vavalos5** [comment]
@dahliaferrer Are you available to revise the content i'm reworking for Navigation? Let me know if you'd like to set some time up if you have any questions.

**Here's the content before I changed it:**

"Navigation is the way users traverse through the structure of an application or website. Navigation provides users screen direction to complete a task logically and easily.

Part of creating a seamless application or interface is creating an obvious flow from one view/interaction to the next. Think of Navigation as a story map where you help guide your user through each process. "


**Here's the content with revisions to create a better story flow, talk about what Navigation is, why its important and introduces the hub&spoke model our designers and developers should be utilizing:**

"Navigation is the creation of how users traverse and interact through the structure of an application or website in the least frustrating way.

At HPE, creating a delightful experience across applications and services is important to make interactions easier for our customers, provide user confidence and enhance user understanding.

The best type of navigation is one that is shallow and follows the hub & spoke model to provide a flawless experience for our users through width rather than depth. Using the hub & spoke model across applications ensures that functionalities are easier to locate in less clicks and prevents users from navigating deep in the hierarchy to find important information such as the status of a system. Lastly, the hub & spoke model also prevents the use of a local navigation to provide users a wider overview of functionalities and task flows that provide ease when troubleshooting if something is wrong within the application."

**Comment by ericsoderberghp** [comment]
Is there a Figma link to use for comments?
For now, regarding the visuals,
- I like the reverse visual
- I wonder if the drill down visual should have only two levels, to align with the reverse visual
- For the cross navigation, the visual seems to imply that a blue goes to a green, one level up, but doesn't seem to indicate that blue could go to blue. Not sure how to represent that without it getting too complicated.

**Comment by vavalos5** [comment]
> 

Hi @dahliaferrer here's our [Design System site](https://design-system.hpe.design/). In order to get to the Navigation page, you'd have to search "Navigation", that should take you to the Navigation home page, which is the content i'm currently working on. Currently, the DS site shows the previous content i've written, but we're trying to implement the deliverables writen above in this ticket. Happy to chat.

**Comment by dahliaferrer** [comment]
Hi, I think a more direct description in the Navigation card could also be beneficial. Instead of "The entry point for..." maybe something along the lines of "Make it easier for your user to find information and complete tasks."

https://design-system.hpe.design/templates/page-layouts

(scroll down to the Navigation card)

**Comment by vavalos5** [comment]
> Hi, I think a more direct description in the Navigation card could also be beneficial. Instead of "The entry point for..." maybe something along the lines of "Make it easier for your user to find information and complete tasks."
> 
> https://design-system.hpe.design/templates/page-layouts
> 
> (scroll down to the Navigation card)

Happy to discuss @dahliaferrer as i'm not sure I fully understand.

**Comment by dahliaferrer** [comment]
@vavalos5 I laid this out in Word. Let me know if you have a moment today to go over it!? https://hpe-my.sharepoint.com/:w:/p/dahlia_ferrer/EWkByuKbgqpJquW4KWGAHNMBc7nuYD4Cm6gK1P-x448MKQ?e=IFWOBx

**Comment by CitizenFox** [comment]
@dahliaferrer I'm wondering if we could explore variations of simple options like "navigational element" or "navigational object." While not exactly creative, something like that could quickly convey a general idea of what we're talking about. Thoughts?

**Comment by vavalos5** [comment]
First round is completed after working w/ Dahlia. I've sent to the designers and Matt for feedback.

Here is what has been implemented:

- New intro introducing Navigation and talking about the importance of the hub& spoke model
- Do's and Don'ts of flat vs deep hierarchies
- Introducing the types of Navigation
- New descriptions on the types of Navigations
- New imagery on the Cards showcasing the types of Navigation

CC: @dahliaferrer @bahriaditi @KennyAtHPE @Keeth-HPe @bezAdane @halocline for feedback

**Comment by dahliaferrer** [comment]
Nice summary, Vicky!
________________________________

**Comment by vavalos5** [comment]
@SOjaHPE @ericsoderberghp This is good to get your eyes on now. I don't want to drag it out longer.

https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=3521%3A19577

**Comment by vavalos5** [comment]
Walked Eric through this. Awaiting feedback from @SOjaHPE. Since we've already had a round of implementation from Dahlia and I, I'm going to close this. I've created a ticket (#2613 ) to track feedback.
