### ISSUE TITLE
Tabs - publish Figma component

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2588]
## Problem Statement

How might designers from product teams be able to leverage the latest Tabs component in Figma?

## Deliverables

- publish the Tab related components to reflect the responsive behavior
- Objectives: 
- [x] Variants for all use cases

 -Disabled arrows for right and left, sizes, states, (focus, default)
- [x] Responsiveness, has auto layout, all different states
- [x] All layers, groups, and properties/values are named correctly (possibly pair with devs on this)
- [x]  Review session with either Kenny or Keeth
- [x]  Review with Scott
- [x] Review with stakeholders 

Reference the new [TextInput [[component]](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components)
Tab component in Figma is [here](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=3352%3A36087)

**Comment by bezAdane** [comment]
Finished creating responsive tab components. Closing this ticket and opened [here](https://github.com/grommet/hpe-design-system/issues/2625) to add tab component guidance for figma file.
