### ISSUE TITLE
Figma - Create DS 2.0 file ( V1) 

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#2589]
Create the Figma file for DS 2.0. 
- Summary
- List of all new components
- Update log of component changes (semantic versioning)
- Figure out where component research will go
- List of design tokens (colors, states, typography, etc.)
- Template for component pages

**Comment by KennyAtHPE** [comment]
For this week the focus will be primarily on:
- Summary page
- Update log
- Template for component pages
- Figuring out where component research will go

**Comment by Keeth-HPe** [comment]
Design system library references from other design systems:

Polaris : https://www.figma.com/file/re2K7Vzm3AtjQjT0NQpqJk/Polaris-for-Admin%3A-Components-(Community)?node-id=2474%3A62

Ant Design : https://www.figma.com/file/bug0fYSwE88r1ri5sBYeB1/Ant-Design-Open-Source-(Community)?node-id=1%3A3

Changelog from Clarity : https://www.figma.com/file/CPvgciKuWvsTSzr9zajWOq/Clarity-UI-Library---light-5.0.0-(Community)?node-id=472%3A16

Uber Base Gallery : https://www.figma.com/file/YKUFhAGB9l4LLbriT1omcQ/%E2%9D%96-Base-Gallery-(Community)?node-id=3%3A4200

**Comment by Keeth-HPe** [comment]
Figma plugins to organize DS 2.0 File : 

Design System Organizer :  https://www.figma.com/community/plugin/802579985985331070/Design-System-Organizer

Toolabs Design System Manager : https://www.figma.com/community/plugin/862818788004280193/Toolabs-Design-System-Manager

Design Lint :  https://www.figma.com/community/plugin/801195587640428208/Design-Lint
