### ISSUE TITLE
Filtering - Adjust Filtering Figma file to properly align Design System site

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2591]
## Acceptance Criteria

- [x] Figma designs are updated and published with the correct filter icon

## Initial notes

During office hours (May 11), it came to our attention that the filter icon in the filtering design in Figma are not aligned to the Design System site. Please update all of the filtering designs to use the proper core 'filter' icon rather than the form 'filter' icon.

[Design System Site](https://design-system.hpe.design/templates/filtering?q=filter)
[Filtering Figma File](https://www.figma.com/file/EA0OZFdocKVcQ55c7Jainb/HPE-Filter-Templates?node-id=1%3A3738)

**Comment by KennyAtHPE** [comment]
Might be a good opportunity to update our other "template" files as well to properly align with the DS site. Layers, Forms, etc.

**Comment by ericsoderberghp** [comment]
> Might be a good opportunity to update our other "template" files as well to properly align with the DS site. Layers, Forms, etc.

Is it easy to split the work up into smaller chunks? I'd rather take smaller steps we can complete than have larger steps that end up dragging out beyond one sprint.

**Comment by vavalos5** [comment]
> > Might be a good opportunity to update our other "template" files as well to properly align with the DS site. Layers, Forms, etc.
> 
> Is it easy to split the work up into smaller chunks? I'd rather take smaller steps we can complete than have larger steps that end up dragging out beyond one sprint.

I think that's a good idea. We can scope out the different types of templates that need to be adjusted and break it down further and also figure out how much design time this is going to take. If I recall, the call out for this was the fact that we're using a different filter icon in the Figma file from the design system site, so the idea here was to replace those. However, there might be other discrepancies. So that will also have to be looked at.

**Comment by vavalos5** [comment]
Here are the changes i've made to the Filtering Figma file"
- adjusted all of the button examples with the correct filter icon.

Noting down thing i've noticed that are different on Figma from design system site:

- we are providing an example where you can filter a list of items through select but no search. I question why there wouldn't be a search bar. We don't have this as an example on the site. Do we still want to keep in Figma? OR just add the search bar to the Figma example?

- replace the "Actions button" with the correct one as it was using our select component. This is dependent on ticket #3132 since we currently do not have an icon variant on the Figma component.

- Modal roundness. Currently it's 24px and should be 6px. Will have to replace with new layer components
- We show an example with tags when filtering, do we want to keep that? We do not have that example on the site anymore.
- recreate examples using all of our most up to date components, i.e. card, layers, etc...
- recreate examples using our new text styles

**Comment by vavalos5** [comment]
@KennyAtHPE can you review this to see if all buttons have been update with the correct filter button please? [DS Filtering examples for refrence](https://design-system.hpe.design/templates/filtering?q=filter)

**Comment by KennyAtHPE** [comment]
@vavalos5 looks like there were two icons that were still unchanged but I went ahead and swapped them out. Everything else looks good and thanks for marking those misalignments down.

**Comment by vavalos5** [comment]
> @vavalos5 looks like there were two icons that were still unchanged but I went ahead and swapped them out. Everything else looks good and thanks for marking those misalignments down.

Thank you thank you. Gonna keep peeking around to see what else needs changes 🔍  and then i'll create other tickets.

**Comment by vavalos5** [comment]
If I had to say what next steps are, i'd say we'd have to just rebuild all of the examples using our new refactored components and aligning the examples to the ones on the design system. I can see this just being one medium size ticket. @ericsoderberghp thoughts?

**Comment by KennyAtHPE** [comment]
Wondering if it'd be beneficial for us to create some common filtering patterns as their own components so that designers can quickly access those?

**Comment by vavalos5** [comment]
@KennyAtHPE Yea, I think that's a good idea. We'll want to look at the contribution that Geetha had previously done called "toolbar" and create variants of that.

**Comment by vavalos5** [comment]
Filter buttons have been replaced with the correct ones. Closing and created a follow up ticket: #3135

**Comment by ericsoderberghp** [comment]
> Wondering if it'd be beneficial for us to create some common filtering patterns as their own components so that designers can quickly access those?

I think it might be good to tie this together with Data, Toolbar, DataSearch, DataFilters and related grommet components.
