### ISSUE TITLE
Tabs - Create Figma Component

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2596]
Objectives:
- [ ] Variants for all use cases
- Disabled arrows for right and left, sizes, states, (focus, default)
- [ ] Responsiveness, has auto layout, all different states
- [ ] All layers, groups, and properties/values are named correctly (possibly pair with devs on this)
- [ ] Review session with either Kenny or Keeth
- [ ] Review with Scott

Reference the new [TextInput component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components?node-id=41%3A678) for guidelines

Current Tab work is [here](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=3136%3A69604)

**Comment by bezAdane** [comment]
Clothing this issue, there is a ticket already created [Here](https://github.com/grommet/hpe-design-system/issues/2588)
