### ISSUE TITLE
Multi-Select - Anatomy

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2600]
Define anatomy of the component: what are the elements that make up a multi-select pattern?

**Comment by KennyAtHPE** [comment]
Outcome of #2609 could be related to multi-select if the component needs to be rebuilt

**Comment by bahriaditi** [comment]
Received feedback from Eric, Jessica and Matt - documented as comments in Figma. Overall, direction is good to go. Closing this ticket.
