### ISSUE TITLE
Figma - Create New Figma Core Components File ( V2)

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#2601]
[Previous Ticket
](https://github.com/grommet/hpe-design-system/issues/2589)
- [Explore other Design Systems](https://github.com/grommet/hpe-design-system/issues/2589#issuecomment-1125055537)
- Rewrite Summary
- List of all new components (Enhance the template)
- Update log of component changes (Explore semantic versioning)
- List of design tokens (colors, states, typography, etc.)
- Template for component page - version 2

**Comment by KennyAtHPE** [comment]
Will be creating separate tickets for each bullet point in the future when needed, closing this ticket out.
