### ISSUE TITLE
Figma - Recreate input components

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2609]
Within this [Figma file](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components?node-id=0%3A1), will be recreating the following Input components:
- [x] TextInput
~~[ ] MaskedInput~~
- [x] DateInput
- [x] FileInput
~~[ ] TextArea~~
~~[ ] FormField~~
- [x] Search

All of these components will be built similarly to or using the TextInput component as a base component, which is being tracked in #2583

Followup tickets will have to be made to:
- Gather feedback on these from stakeholders (#2583 )
- Deprecate old components
- Replace instances of old components within our files

**Comment by KennyAtHPE** [comment]
The outcome of this could be helpful for #2600

**Comment by Keeth-HPe** [comment]
https://www.figma.com/file/uoU2AbO7mnv4gIP9W3zQS4/Test-2.0-component?node-id=0%3A1

In this file, the new input components built for DS 2.0 will be presented for review so that we could get some early feedback.

**Comment by Keeth-HPe** [comment]
Creating new tickets for masked Input and FormField.
As both have dependencies.
Masked input - We Are holding it off this week. To decide whether it has to be an individual component or the same as text input
Form-field - Includes other components like select & radio button group components which are yet to be created.

**Comment by KennyAtHPE** [comment]
Search is completed besides having a bug with the Focus effect. Ticket to fix that: #2654

**Comment by KennyAtHPE** [comment]
Will also need to revisit TextArea. That component is a bit trickier to build on. The ticket for that is #2655
