### ISSUE TITLE
Navigation - Implement feedback received on home page

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2613]
Implement feedback received from Scott and others.

Continuation of ticket #2558

**Comment by vavalos5** [comment]
Awaiting feedback from @SOjaHPE 
cc: @ericsoderberghp 

I've also sent this file to: Edgar, Ian, Gina, and Greg to review the new guidance along with the before to compare what's changed.

Figma file: https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=3521%3A19577

**Comment by vavalos5** [comment]
I put this ticket back in "triage" as it was unable to get feedback.

**Comment by SOjaHPE** [comment]
@vavalos5  as mentioned in slack Friday evening, I'm working on this navigation feedback on Tuesday and Wednesday. I'll be able to meet with Dahlia at that time.

Please contact Edgar, Ian, Gina, and Greg and have them hold off on reviewing, guidance that is incomplete, no need to waste their time if changes are forthcoming. I was unable to work super late on a friday evening, Dahlia was out.

My daughter graduates from High School today, friends and family are in town, my birthday is on Sunday. Feedback is OTW.

@ericsoderberghp  FYI

**Comment by vavalos5** [comment]
Per Ian's feedback: 

"The new guidance and visuals for navigation look good. I find the explanations and terminology much more intuitive. I guess my main feedback is that I really hope to see actual coded clickable grommet page examples that illustrate the navigation patterns in a way that the HPE DS thinks are acceptable. For example, right now I’m tasked with coming up with a new application design for a new product, I need to decide which navigation approach to use. Though reading through the guidance here of which navigation patterns there are, I don’t really know where to start from an implementation perspective…. for example, “side-to-side” navigation talks about “navigational tabs” … so do I use regular Tab components for this? Or do I use normal buttons as tabs across the top with custom styling to show act as tabs or something else? We aren’t using the Global Header. Does the HPE DS provide a navigation bar or something to support this? Or can I use a sidebar like Ezmeral does now to achieve side-to-side navigation, same concept? Can I use a menu? Originally the HPE DS system showed example pages with a sidebar and or hub-n-spoke using cards etc, and these were things designers and developers could borrow from. The new guidance here explains different navigational patterns as concepts well, but leaves out any examples of implementation. Perhaps this is on purpose as not to suggest what can or should be designed? I just preferred the original navigation pages where you had a sidebar example, a menu example, hub-n-spoke example, and an example with top navigation… those I could grab and start using (both from a design and development) perspective"

**Comment by vavalos5** [comment]
Not entirely specific to this page, but an e-mail i've received from Edgar where I was CC'd in regards to the work Gina is doing for Navigation. An interesting way to think of CRUD in Navigation.

"Because I’m heading out on vacation, I wanted a chance to educate and elaborate on some things that were discussed in our meeting today.
 
In general, there are CRUD permissions for every resource type (Create, Read, Update, Delete).  For example, for a bare metal server resource type:
C may allow me to create (provision) it.
R allows me to see that it exists and view it and its attributes.
U allows me to edit its attributes. (there could potentially be multiple U permissions for the same resource type, controlling which attributes can be edited or what other actions can be taken)
D allows me to delete (de-provision) it.
 
A resource can be anything: a report in CA, a data source in CA, a Kubernetes cluster, a storage device, a router, a policy, a user, a group, etc.  Everything is a resource.  Resources may also contain sub-resources with their own CRUD permissions.
 
A role is a set of permissions. For example, a CaaS (containers as a service) admin role might involve: CRUD for clusters, namespaces within clusters, and applications within namespaces.
 
However, a CaaS user role might be defined as: R for clusters, R for namespaces, and CRUD for applications within namespaces.
 
Roles can be very granular or very high level.  For example, a role can be built from existing roles. A user with C permission on role resources could create a new role named “Fred” that is comprised of more atomic roles shipped by HPE.  For example, a Fred might include: VMaaS admin, CaaS admin, and BMaaS user roles.  They can then assign the Fred role to all of the “Freds” in their organization.
 
Because all personas ultimately are realized in terms of roles, there cannot be differing navigation for different personas.  There are just different permissions.  For example, a devops user likely won’t have R permission on cost reports so won’t even know they exist and cannot see them.  Similarly, a financial role will have R permission on a cost report (and may even have all CRUD), but may not have any permissions to see or do anything with other resources.
 
Ultimately, there is a landing page where a user ends up after logging in.  Their R permissions should be used to define the kind of content visible on that page as well as what they are allowed to navigate to.  If you cannot R, you cannot go there.  Once you are somewhere (including your first landing page), you may or may not have C/U/D permissions for the resource represented by the page.  Your permissions dictate the kinds of actions that can be performed on the resource represented by the page.
 
A resource has attributes which may or may not include sub-resources (e.g. a Kubernetes cluster is comprised of one or more node pools and each node pool is comprised of one or more servers.  Also, the Kubernetes cluster can contain one or more namespaces and each of these can contain one or more sets of quotas. 
 
If a resource has a large number of attributes, they can be organized within sections on a single scrolling page, or tabs can be employed to limit scrolling and help focus the user.  Headings/sections within a page are equivalent to tabs.
 
A navigation bar is different.  At the top level of a service, there may be direct access to multiple types of resources (that may or may not have a parent/child relationship).  For example, at the top level of Data Fabric, there are Fabrics, Clusters, and Volumes.  In Consumption analytics, there are Dashboards, Reports and Data Sources.  A navigation bar (button bar) is used to navigate within a service to what could be termed a sub-service.
 
These sub-services typically start out with lists/tables of resources (e.g. Clusters, Volumes, Reports, etc).
 
Table row click is often used to navigate to a detail page for the resource represented by the table row.
 
Once looking at a single resource, you are back to “a resource has attributes” and may scroll through sections or may navigate tabs to see these.
 
Sometimes a resource attribute may be another resource or a relationship to another resource.  For example, a volume is in a cluster, so when viewing a data fabric cluster, the owning fabric is listed as an anchor, but only if the user has R permission on the fabric.  These anchors are known as deep links and allow the user to directly navigate from one branch in a resource hierarchy to another.
 
Because of all this architecture, it is possible to think generically when it comes to navigation:
 
A user typically wants to log in and see useful information on their landing page.  If that page’s content is derived from the user’s roles, problem solved. Note: this can be done programmatically and doesn’t require having to define what each persona sees, but rather what each R permission may see.  Then, roles can be created to match the real persons instead of the not-real personas.  All we need to do is figure out how to organize the information that might be displayed (e.g. Chris’s vision has an organization of Home, Dashboard, Services, Workflows, Resources. And, within those sections, there are sub-sections to further categorize content).
If the user has the ability to edit their landing page (U permission on landing page resource), then they may be able to choose from landing page content presented to the user (R permission on each service’s content) that they can add/remove to/from the landing page. 
If there is enough variation in the type of content (attributes) to present to the user (i.e. a lot of different categories of landing page attributes), then tabs or headings (or a combination of the two as seen in Chris’ vision) can be used to split it up into categories.
When a user has a role that includes permissions for one or more services, we need to realize that the customer is paying for services and the user wants quick, direct access to those services – from anywhere.
It will be the rare user that has so many services that showing them a menu of their services will overwhelm them.
The 80% use case is not shopping for more services, but there needs to be a way to do that for every role.
Advertising should be kept to a minimum and eliminated entirely once a user is within a service.
Every user has a day-0 experience and a day-N experience that are different based on the state of the resources associated with that user’s roles/permissions. 
E.g. If I have not yet set up a user profile (resource), or set user preferences (resource, or multiple per-service resources that might be presented centrally), then I should see something that guides me there.  I always need an ability (subject to RU permissions) to see and update my profile/preferences, but it doesn’t have to be in my face on day-N.
E.g. If I go to the DevOps service and no projects have been created, a C permission might show me a message telling me to create a project to get started and putting a create button in the middle of the screen.  But, lack of a C permission may result in a message telling me that there aren’t any projects that I have access to.
 
There’s more, but that’s enough for now.
 
-Edgar"

**Comment by vavalos5** [comment]
Awaiting feedback from Chris on Thur.

**Comment by vavalos5** [comment]
@dahliaferrer Feel free to tag me here or on Slack once changes have been made so I can polish out the page and close this ticket. Thanks!

**Comment by vavalos5** [comment]
Doneeeee!! 🎉  Thank you @dahliaferrer for the content!!

https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=3941%3A19710
