### ISSUE TITLE
Feedback button *proactive* for content strategy

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2616]
For an efficient content strategy, analytics are crucial. Data is needed from a wide audience (within our target market) and as close after publishing date as possible, so adjustments can be made quickly. "Fail fast" and adjust quickly! 

Currently this is how I see we do things: we go through many internal rounds with thoughtful, internal brainstorming/guessing and maybe a few outside opinions. After weeks of working on a guide, we finally publish it. We post the link in a couple of Slack chats and reach out to some of our familiar colleagues for feedback, who may or may not actually be using this guide for an actual project. The feedback button is down at the bottom of a long page and offers 3 options. 

One of the processes in the publishing and content strategy we can better is to be a little more proactive in getting feedback on a new guidance published by:

1. getting analytics from a wider group of people, not just the "regulars" on a Slack channel or our close colleagues who may think like us already

2. getting analytics from designers/devs who are actually using that guidance page for a real-life, active project

3. make the feedback button a little more proactive (my experience would be to put it at the section in the page where most likely the user would "bounce" from that page)

4. give one feedback option, preferring an easy, quick impression over three options and down at the bottom of the page, where the feedback request is hidden and passive

I like this example: 
https://feedletter.co/feedback-button/

**Comment by dahliaferrer** [comment]
@MeganBeierle Check out how I set up this ticket. I dk if we should combine it with your ticket, which is more about GLCP, or just continue using this one when we are looking at the functionality/usefulness for the Design System...?

**Comment by dahliaferrer** [comment]
@MeganBeierle is the feedback that you are working on available for us to use in the Design System?

**Comment by MeganBeierle** [comment]
@dahliaferrer Hello! 

I need to complete some additional design options for the component this week and Brittany still needs to code it but then it will be ready for our site. You can go ahead and get the questions that you want to ask ready and I can create a mock up. Let me know if you have any other questions.

**Comment by ericsoderberghp** [comment]
Waiting on https://github.com/grommet/hpe-design-system/issues/2760

**Comment by dahliaferrer** [comment]
Oh, exciting! Thank you again, for all your research and reaching out to people on this. It'll be very helpful 🙂
________________________________

**Comment by jcfilben** [comment]
Closing, a feedback button has been implemented on the design system site
