### ISSUE TITLE
Icons - Add "hide" icon from Grommet to Figma library

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2618]
Srinivas (Storage) pointed out that we don't have the "hide" icon in Figma. We need to add this to the library. 

**On Grommet:**
<img width="1054" alt="Screen Shot 2022-05-24 at 11 08 33 AM" src="https://user-images.githubusercontent.com/87677275/170105765-123e3a7d-27f4-498a-8552-bcd3cf011b4c.png">

**On Figma:**
<img width="627" alt="Screen Shot 2022-05-24 at 11 09 40 AM" src="https://user-images.githubusercontent.com/87677275/170105917-49927689-ffc1-4b3a-9bfc-4e6f376e9f8f.png">

-----

**Related tickets:** 
#1840
#1957

**Comment by vavalos5** [comment]
Icon has been created in [Figma here](https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=1483%3A80).

Will be connecting with Brittany tomorrow morning to ask her some Qs on implementation.

**Comment by vavalos5** [comment]
Icon has been made. Had Kenny take a peek to make sure nothing was missing. I've published it in Figma. You can find it here. https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=582%3A6
