### ISSUE TITLE
Icons - Inconsistent naming hindering component properties

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2622]
Currently, icons within Figma are named/built incorrectly which is hindering the usage of the new "instance swap" property. This property allows users to easily swap between icons and is currently/planned to be used in a lot of our components (affects any component with icons)

---------
**Expected**

Changing a component's state from enabled to disabled should also update the icon's color.
<img width="356" alt="Screen Shot 2022-05-25 at 9 46 09 AM" src="https://user-images.githubusercontent.com/86075038/170317075-0eca81cb-88de-4b45-8879-0e2c4ce2d4c5.png">

When using the instance swap property, icon colors should override.
<img width="348" alt="Screen Shot 2022-05-25 at 9 48 19 AM" src="https://user-images.githubusercontent.com/86075038/170317463-533d3e38-04aa-4b83-9fe3-c009ff32d1df.png">

--------
**Actual**

Icon colors do not change based on state.
<img width="343" alt="Screen Shot 2022-05-25 at 9 52 11 AM" src="https://user-images.githubusercontent.com/86075038/170318120-8b21e162-bd0e-4516-9c40-19f7c5fad9fd.png">

Icon colors do not override when using the instance swap property.
<img width="338" alt="Screen Shot 2022-05-25 at 9 53 33 AM" src="https://user-images.githubusercontent.com/86075038/170318342-7c24778c-fa21-4355-8bea-15f653046a92.png">

-------
**Problem + Solution**

Within Figma, component properties (such as for instance swap) identify and update elements based on their name. Currently for our icons, the elements making up the component are given unique names. For example:

Stroke for the Refresh icon is called refresh and the stroke for the Down icon is called Path (Stroke). Because of this, Figma doesn't recognize these as similar components but rather completely different entities
<img width="377" alt="Screen Shot 2022-05-25 at 9 57 39 AM" src="https://user-images.githubusercontent.com/86075038/170319104-58676f76-5e35-49ea-a7de-a2264c5ae516.png">

To fix this issue, we need to have one singular name for the elements making up an icon. Here is my proposal for a universal name: 
<img width="388" alt="Screen Shot 2022-05-25 at 10 02 03 AM" src="https://user-images.githubusercontent.com/86075038/170319844-4f403de9-c9c5-425b-a1d8-5fb30f5f8654.png">
 Here, the icon's name is still unique but the elements within it are consistent across all icons.

**Comment by KennyAtHPE** [comment]
There may be plugins from the community that we could utilize to quickly rename these layers. I would start by doing some research on that.

**Comment by SOjaHPE** [comment]
@KennyAtHPE  thank you! looking forward to what you find, if there is an existing plug-in to do this repetitive work.

**Comment by KennyAtHPE** [comment]
All icons, minus a few exceptions, have been updated so that components such as buttons can now correctly utilize the instance swap property. An icon's color will now override when changing states. 

Closing ticket.
