### ISSUE TITLE
Figma - Explore Figma Tokens plugin

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2627]
**Problem Statement**
Our currently established tokens within Figma (fonts, colors, drop shadows/focus) were created to maintain parity between Grommet and Figma components, as well as to achieve consistency between designs. We have observed and been noted by other teams that our current library of Figma tokens does not account for all values (ex. spacing and sizing), which is causing confusion and inconsistencies between designs. How might we expand upon our current Figma token library so that we can maintain a higher level of consistency both internally and for those consuming the Design System?

**Deliverables**
- Explore and evaluate this [plugin](https://www.figmatokens.com/). [Overview video](https://www.youtube.com/watch?v=0lH_FTHtvVo&t=385s) from Config
- Evaluation of our current tokens and cross-reference on the dev side. Note areas we are missing/could improve upon
- Connect with Srinivas Padma. He has shown interest in helping us out :)

**Comment by SOjaHPE** [comment]
Started a figJam board related to this topic..
https://www.figma.com/file/B0DYkRZ8AiYHGqsMUv2gtZ/Design-Token-Symbolic-Naming?node-id=0%3A1

**Comment by KennyAtHPE** [comment]
Opened #2777 for the next exploration steps. Will be closing this ticket out.
