### ISSUE TITLE
Navigation - Implement feedback and iterate for Side-to-Side

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2639]
- Dahlia to provide feedback
- Run by Chris
- Show Eric
- Implement any feedback

**Comment by vavalos5** [comment]
Met with Dahlia earlier today to discuss comments she left on file and they've been addressed. Will try to fill Chris in on Thurs. too.

**Comment by vavalos5** [comment]
@ericsoderberghp Would you be able to take a look at this and let me know if you see anything that might need changes please. Thanks!

https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=3547%3A19626

**Comment by vavalos5** [comment]
Eric, Aditi and I are meeting on Monday to collect any feedback and make any changes should there be any so we can finalize.

**Comment by vavalos5** [comment]
@bahriaditi @ericsoderberghp I've implemented the changes Eric suggested to Side-to-Side which was including a "When not to use" section with an example of how the navigation bar shouldn't be used. Lmk if you have any further comments/questions or if this is good to close. Thanks!

https://www.figma.com/file/b6hiokanRCwNnc93PpHdgQ/HPE-Design-System-Navigation?node-id=3547%3A19626

**Comment by bahriaditi** [comment]
Thanks @vavalos5 - I dropped some comments in Figma, hope it helps

**Comment by vavalos5** [comment]
donezo
