### ISSUE TITLE
Avatar - Feedback on designs

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2643]
- [x] Review [design contribution](https://www.figma.com/file/Tw2PiwyLS21l20VTXKbQfS/Avatar?node-id=0%3A1) from Sylvia (GLCP)
- [x] Leave comments on the Figma file to align with Design System
- [x] Circle back with Sylvia to walk through feedback

**Comment by bahriaditi** [comment]
@ericsoderberghp could you glance over Sylvia's initial designs and leave any additional comments? We'd love to get your perspective on it too.

**Comment by ericsoderberghp** [comment]
dropped a few comments in Figma
