### ISSUE TITLE
Form - Add guidance for credential validation error wording

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2648]
**Problem**

Guidance is needed for how to word Form credential validation errors, such as that of a username/password failure.

**Problem Statment** 

How may we add further wording guidance for instructions on entering name/password form fields and subsequent error messages when there is a credentials validation failure in edge cases (when the name and password do not pass authentication)?

**Comment by bezAdane** [comment]
@dahliaferrer let me know when it is ready to be reviewed :)

**Comment by dahliaferrer** [comment]
Need to go over Scotts and Beza's comments. I've started to look at them but realized a little chat might be helpful.

**Comment by dahliaferrer** [comment]
This will be brought up in the Office Hours on July 20

**Comment by dahliaferrer** [comment]
**The initial objective was finished a long time ago, with Edgar's guidance.** 
HMW "add further wording guidance for instructions on entering name/password form fields and subsequent error messages when there is a credentials validation failure in edge cases (when the name and password do not pass authentication)?"

However, I combined this project with the need for a new guidance template and used the "forms" guidance as our tester/guinea pig. This has made it more complex and longer to close out, but it forges us in a direction towards testing something until we arrive at a good, strong, user-friendly template for all future guides.

In the past weeks we've been working on: 
- finalizing the layout of the new guidance
- talking about getting a developer (Brittany volunteered!) to get the interactive example going for the Do's and Don'ts
- survey/testing/feedback with the Research department.

**Comment by dahliaferrer** [comment]
I'm closing this ticket and continuing in #2756
