### ISSUE TITLE
Tabs - Deprecate old component

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2649]
Steps to deprecate old tabs component and to publish new component:
- [x] Rename each old component to "🛑 Deprecated"
- [x] Within each old component, include a description that tells the user that the component is deprecated and include a documentation link to the newly published component
---------
Once [#6117](https://github.com/grommet/grommet/issues/6117) and any other dev related issues on Tabs is finished move on to these steps:
- [x] Move all old components to a separate deprecated page. Follow the [Deprecated Components page in Icons](https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/HPE-Icons?node-id=6563%3A695) as an example.
- [x] Move the new component and its guidance into the Finished page
- [x] Review w/ Kenny, Vicky
- [x] Publish the new component and include a short description as well
- [x] Publish the name changes and include a short description about why we are deprecating, where they can find the new component, and who they can contact if they have questions. Note: Doing some testing for this task will update as soon as we figure it out. 
- [x] Send out an announcement about the deprecation and the newly published component within the HPE-Design-System channel

**Comment by bahriaditi** [comment]
Recording of the process as discussed with Kenny + Beza:
https://hpe-my.sharepoint.com/:v:/p/aditi_bahri/EUp3YVHZ0XZKm8Pk2kVUW9MBlNwG09pg9YsNobOSmY_8dQ

**Comment by vavalos5** [comment]
Once Beza completes this, I'll review 😄

**Comment by bezAdane** [comment]
@vavalos5  all the tabs are Rename to old component to "🛑 Deprecated" and are ready to review :) Per our conversation I will hold off to give the description and documentation until we figure out what to call it.

**Comment by vavalos5** [comment]
Thanks Beza! Looks good. Lets see if we can connect w/ Kenny and figure out a solution before end of week.

**Comment by KennyAtHPE** [comment]
@vavalos5 @bezAdane for the announcement message I'd mention the specific changes from the old component and an explanation of how we will be deprecating the old component. Additionally, please omit mentions of the New Figma Core Components project since this will live separately from that file for right now as we are still getting that set up

**Comment by vavalos5** [comment]
@bezAdane, lets change the description text in the Component Details section to "Deprecated on xx-xx-xx" within the description field and keep the link you currently have linking to the finished page within the documentation link section.

Note that we still don't have a precise date on when deprecation will be done as we're awaiting on devs to get that finalized so that's why we'll keep it as "xx-xx-xx" to fill in after. 


Once that is completed, take a stab at creating an explanation on Kenny's comment above ( what changes have been made to the new component from the old one.) 

Let me know if you have any questions.

**Comment by vavalos5** [comment]
@bezAdane can we add the link to where we can find the announcement here so we can track it if needed.

Leaving an update here too that Jessica has created a PR which can be found in #2668 . Once that is completed, Beza will make an announcement on the new changes implemented into Figma and DS site.

**Comment by bezAdane** [comment]
Here is the announcement [link](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=3701%3A39737).

**Comment by vavalos5** [comment]
Tabs was merged, woooooo!!!

Beza and I will be meeting on Tues. to finish up the rest of this ticket 😄 🎉

**Comment by bezAdane** [comment]
All the items on check list have been completed!!!!!
