### ISSUE TITLE
Figma - Finalize finished pages for input components

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2656]
Related to #2235 

Within each component page, there should be:
- Guidance + relevant links (DS site, grommet, etc.) ([Example](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components?node-id=143%3A584))
- Variant board showcasing all the components ([Example](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components?node-id=486%3A16254))
- Component Property Anatomy ([Example](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components?node-id=494%3A17491))
- Visuals of all interactions ([Example](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components?node-id=507%3A17671))

For this ticket we will be focusing on:
- [x] TextInput
- [x] DateInput
- [x] FileInput
- [x] Search

**Comment by Keeth-HPe** [comment]
- [ ] Guidance + relevant links (DS site, grommet, etc.) 
- [ ] A variant board showcasing all the components
- [ ] Component Property Anatomy
- [ ] Visuals of all interactions

Completed task for TextInput, DateInput, FileInput, Search.  

@KennyAtHPE

**Comment by KennyAtHPE** [comment]
File templates from #2235 have been applied to the input component pages. Closing out this ticket.
