### ISSUE TITLE
Multi-Select - MVP Prototype

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2662]
Create a low fidelity prototype of proposed design with the goal of:

- Reviewing accessibility and noting additional considerations/ best practices
- Uncovering interaction details that we need to consider: keyboard behavior, animation timing etc.
- Aligning design and dev, discussing tradeoffs where necessary

**Comment by jcfilben** [comment]
The following accessibility improvements from #2661 were added to this prototype:

- Improved Search label
- Communicate that no matches were found on search
- When user hits 'Enter' while searching and options were found, the users focus will move to the first option and the screenreader will read out that option and the total number of options found.
