### ISSUE TITLE
Form - Add guidance for full-page vs layer

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2666]
**Questions raised during office hours 6/14/22** 

- We currently have something called layer within the design system component and one can utilize this for forms using side drawer/layer. There are some use cases which needs full space to be occupied. Currently we don’t have guidance and example.   **Reference:**  [Figma](https://www.figma.com/file/Lh01flLH73cFNGZiFxEFth/HPE---Office-Hours?node-id=460%3A6264)

- needed guidance on when to use a full page forms.

ToDos:

- [x]  Collect use case from different services team. ( where full page and layer are used), find out other services and guidance are used.
- [x] Research/explore

**Comment by bezAdane** [comment]
Got more insights on context of use from [Chandan (India team)](https://www.figma.com/file/yRiRwKzfB4xIsc3nOww3fK/Design-for-Compute-Groups-(Projects)-page-Phase-2---US36393---F5773?node-id=517%3A57646)   [Geetha (Ezmeral) ](https://www.figma.com/proto/FiE6ZMK6MmQ7G3jtSEaA6I/User-Management?node-id=2647%3A116790&scaling=min-zoom&page-id=2647%3A116762&starting-point-node-id=2647%3A116763)   [Sylvia (GLCP)](https://www.figma.com/file/vK6LH6vXfdK7euQ7AmEgr4/Components%2C-Templates-%26-Guidelines?node-id=700%3A9560)

Closing this ticket so we can begin ideation/guidance as a next step. https://github.com/grommet/hpe-design-system/issues/2750
