### ISSUE TITLE
Navigational Tabs - Implement component to Figma and DS site?

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2669]
In Navigation, we talk about using a Navigation Bar above the PageHeader for navigating between pages. Although it is a set of buttons placed together on the same level, should we make this a component with guidance?

Part of the reasoning why i'm inserting this as a question is because it is also implemented in the work i've been doing for Navigation where it talks about how the items located within this "container" are side-to-side navigation. Essentially the way users can move or navigate in. I'm thinking this should be a component where we direct people to navigation guidance and vice versa.

**Here is the NorthStar link to Chris's work where we can see how it is being utilized.**

https://www.figma.com/file/tbxY1HaiyJjEI9Wm2dQ9nR/HPE-Prototypes?node-id=3976%3A123202

Screenshots:
<img width="1035" alt="Screen Shot 2022-06-16 at 10 10 07 AM" src="https://user-images.githubusercontent.com/62117454/174128113-4f843c62-48d7-421d-a47b-ad974b2c3650.png"><img width="906" alt="Screen Shot 2022-06-16 at 10 10 23 AM" src="https://user-images.githubusercontent.com/62117454/174128087-710bed72-51ce-40cf-b362-4214d5dd163b.png">

**Comment by vavalos5** [comment]
<img width="1035" alt="Screen Shot 2022-06-16 at 10 10 07 AM" src="https://user-images.githubusercontent.com/62117454/174128113-4f843c62-48d7-421d-a47b-ad974b2c3650.png"><img width="906" alt="Screen Shot 2022-06-16 at 10 10 23 AM" src="https://user-images.githubusercontent.com/62117454/174128087-710bed72-51ce-40cf-b362-4214d5dd163b.png">

**Comment by ericsoderberghp** [comment]
Here's an example from what we've got currently: https://designer.grommet.io/?id=navigation-bar-eric-soderberg-hpe-com

Where the code looks like:
```
<Nav align="center" flex={false} direction="row">
  <Button label="first" />
  <Button label="second" />
  <Button label="third" />
  <Button label="fourth" />
</Nav>
```
I'm wondering if this is simple enough or we should consider something like:
`<Nav items={[{ label: "first" }, { label: "second" }, { label: "third" }, { label: "fourth" }]} />`

**Comment by taysea** [comment]
Closing, outdated and navigational work with be addressed in newer work.
