### ISSUE TITLE
Figma Refactor - Recreate Lists

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2675]
Lists is an essential atomic component that is used to create many other complex components (accordions, menu, etc.)

Related to: #1467, #2640 

To do:
- [x] Identify components that are built using Lists. Should certain components have their own Lists component?
       - [Accordions](https://www.figma.com/file/UvTBUQdhk07wV79nijsrtr/HPE-Accordion-Component?node-id=0%3A1)
       - [Menus](https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=606%3A1489)
       - TBD 
- [x] Assess Lists components, variants, and component properties as needed
- [ ] Recreate Lists component [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Core-Components?node-id=1058%3A18489)
- [ ] Finalize Lists page

**Comment by Keeth-HPe** [comment]
@KennyAtHPE 

Accordions and menu component should have their own individual component. With major differences in size, properties, and spacing we will not be able to build a component using the Lists. 

Tried to use the List component as the base. But auto layout does not support the spacing between header and description. 
<img width="441" alt="Screenshot 2022-06-21 at 8 04 02 AM" src="https://user-images.githubusercontent.com/86280029/174704099-b799c40b-cea0-4adc-86f7-b8e190c6ba2e.png">

**Comment by KennyAtHPE** [comment]
@Keeth-HPe makes sense, thanks for taking a look at this. I'm thinking that the List components for Accordion and Menus should be separate unpublished components and even if they aren't built using the main List component, they should still have similar variants + component properties and naming conventions.

**Comment by StingRay005** [comment]
@Keeth-HPe could you please comment on where this is at?

**Comment by Keeth-HPe** [comment]
> @Keeth-HPe could you please comment on where this is at?

Hey, It's complete. @KennyAtHPE  will be reviewing it today.

**Comment by KennyAtHPE** [comment]
Left review comments in the file. I will be discussing this with Keeth

**Comment by KennyAtHPE** [comment]
@Keeth-HPe please close this ticket once you've reviewed the final round of Figma comments. Thinking that this is 99% of the way there.

**Comment by Keeth-HPe** [comment]
Reviewed 👍 and it works fine👌 Hence closing the ticket :)
