### ISSUE TITLE
Template for DS Guides - design work

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2676]
Looking for assistance from designers. This template is meant for any future guides published on the Design System website: https://design-system.hpe.design/

Template made by content strategist (Dahlia): 
https://www.figma.com/file/qbbYGi73ncFAoLQ0IM1Y7x/DS-Guide-Template?node-id=3704%3A19539

End goals:
1. Table of contents, titled "Jump to" design to be easily replicated into new and retroactively into previous design guides.
2. Decide how best to show the comments. Currently they are in brackets, but there might be a better way to display those. Seeking ideas from designers.

Ideas for table of contents:
1. Directly after the definition and description.
2. Front and center, until the user starts scrolling down. In that case it could move to the side, out of the way but floating and constant:
 https://deploy-preview-2134--keen-mayer-a86c8b.netlify.app/components/anchor (TAYLOR SENT THIS!)
3. Responsive to smaller screens solution could be a floating, persistent menu that is collapsed, with a small bar to indicate you can open the menu.

Ideas for comments:
None yet! lol

**Comment by bahriaditi** [comment]
Hi @dahliaferrer 
Here's an iteration of the template you created with annotated section descriptions: https://www.figma.com/file/qbbYGi73ncFAoLQ0IM1Y7x/DS-Guide-Template?node-id=3875%3A20038

Let's meet tomorrow to discuss more (I sent you a calendar invite).

Few comments/ questions:

- **Overall**: Should we consider marking some sections as nice to have/ optional?

- **Do’s and don’ts**: These are typically section specific, so not convinced that we can have them all under a single section that can be linked to.

- **Use cases and real-life examples**: I like this idea - do you mean showing a look book - a catalog of different scenarios of using the pattern?

- **Common problems**: Again, I like this idea, would be good to see an example of what you are proposing. I don’t think we currently do this. Also, wondering if this will this be overkill for each pattern?

- **Exceptions**: I like this idea too, but I think it would be helpful to see some example content as part of the template.

**Comment by dahliaferrer** [comment]
Installed Annotation plugin https://www.figma.com/community/plugin/859894273811051899/Annotate-it

- [ ] Add "annotation" box with a list of all of the content types as inspiration for designers when they are creating the guidance
- [ ] Show Aditi's initial idea for the table of contents (i.e. "Jump to" section) and create another "issue" to track the work on the table of contents with a designer.

**Comment by ericsoderberghp** [comment]
I just reviewed, it's looking good to me.
