### ISSUE TITLE
Revanth requested IDEAS and review of a low-fidelity design

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2678]
"CA - Budgets Feature Exploration - CAP is migrating this feature to GLC-CA with improved experience to visualise and feed budgets to the system. Note: Explorations and ideations can be found in their respective pages in the figma file."

https://www.figma.com/file/0YPuV20WoKKf43d3mvpLfa/Budgets?node-id=201%3A9833

Use cases and business value:
https://rally1.rallydev.com/#/347360349432ud/dashboard?detail=%2Fportfolioitem%2Fmarketable%2F627199077037

**Comment by jcfilben** [comment]
No longer relevant
