### ISSUE TITLE
Status Indicator - Guidance on icon usage and terminology

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2681]
**Questions raised during the discussions:**
- When/where to use Status vs. Health _(It was decided during this call to stick to Status, but we have no official documentation on this in the DS)_

<img width="796" alt="Screen Shot 2022-06-27 at 8 01 52 AM" src="https://user-images.githubusercontent.com/87677275/175972098-44aee80e-92cd-4b69-b9cd-652e87967623.png">

- When we use icons, should we always use the same labels/ terms across service use case? Terms should match the icon names - we want to be able to see some standardization across labels (Ok vs Operational) Similarly in this example, 'Running' and 'Stopped' is a state and that’s why the icon doesn’t fit 

<img width="634" alt="Screen Shot 2022-06-27 at 7 57 24 AM" src="https://user-images.githubusercontent.com/87677275/175971186-bbfff5d5-ce6e-46e2-bb81-fd336f99b503.png">

- Is it correct to say that icons are always related to status?
- How should we display icons? Guidance for when it icons are okay to display without a label. Related to #2020

**Comment by taysea** [comment]
Closing: https://design-system.hpe.design/templates/status-indicator?q=status#icons-and-shapes
