### ISSUE TITLE
Figma - Look at Figma Analytics on which components are detached

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2688]
As a continuation of #2482, lets take a look at Figma analytics to better understand:

1. which components are being detached/broken
2. Going to stakeholders to get a better understanding of why they're breaking them
3. Ask which component they'd benefit the most and why as a continuous effort of recreating components in Figma

Prior to this, a plan should be put in place on how we might tackle this due to all the components we have.

**Comment by vavalos5** [comment]
**The following has been completed on this ticket:**

[- Defined the Problem, Problem Statement, benefits of this ticket and design challenges.
](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1363%3A26915)

![Image](https://user-images.githubusercontent.com/62117454/176939556-b5b4e411-b097-4910-9e8c-908b54f09677.png)


- Gathered screen shots of Figma analytics on all of our components from A-T.
- Began a DataTable where I've collected the most commonly detached components to have a better overview rather than going back and forth on the screen shots
- Began grabbing screen shots of exactly where people are detaching our components, understanding what they're doing with them and writing summaries of what's wrong. i.e. does the DataTable cell have more padding between the text and the end of the cell?

**What still needs to be done:**
- Continue collecting the most commonly detached components into the [DataTable](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1527%3A33241) ( I left off at Name-Value List, the following still need to be analyzed: Notifications, PageHeader, Radio Button Group, RangeInput, Search, Select, Stack, Tabs, Text Area, Text Input, and Tip).
- Continue analyzing the rest of the components and go through files of where components are being detached. Finally, grab screen shots of those, the link of where the detached component lives and create a quick summary of what is wrong
- Next steps would be going to the direct source (this is where the link of the detached component comes handy because you can see who owns the Figma file) and begin to ask why... Referring back to the goals on the screen shot above would be helpful to reference to.

**Comment by bezAdane** [comment]
Closing this ticket to break down ticket  to smaller task here #2745
