### ISSUE TITLE
content review - BMaaS Volume attachments

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2691]
Revanth (UX Designer) posted this in Slack seeking APPROVAL - Jeff Stolz approved already ... he probably should know I need to look at it as well

https://www.figma.com/file/yRiRwKzfB4xIsc3nOww3fK/Design-for-Compute-Groups-(Projects)-page-Phase-2---US36393---F5773

attach/detach a volume from compute group and show its details in a volume/compute instance page.
For reference: Explorations

**Comment by jcfilben** [comment]
Closing, I don't think this content review work is planned anymore
