### ISSUE TITLE
content review - Budgets Feature Exploration

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2693]
Revanth posted this in Slack seeking REVIEWS / IDEAS

https://www.figma.com/file/0YPuV20WoKKf43d3mvpLfa/Budgets?node-id=201%3A9833

He states these are low fidelity designs

Use cases and business value - M1142
https://rally1.rallydev.com/#/347360349432ud/dashboard?detail=%2Fportfolioitem%2Fmarketable%2F627199077037

Note: Explorations and ideations can be found in their respective pages in the figma file.

**Comment by dahliaferrer** [comment]
Amanda and I chatted on Thursday 7 July about the differences between "by field" vs "single" budgets and I'm researching accounting terms to see if there is something more industry-standard.

**Comment by dahliaferrer** [comment]
Need to chat with @halocline to chat about this accounting aspect. 

Otherwise, I just need some head-down time to continue with all of the edits for the India team.

**Comment by dahliaferrer** [comment]
Matt and my research seem to confirm that the terminology they are using "by field" is vast, unique and there doesn't seem to be counterpart that we can identify in accounting. He also understood what a "single" budget was in contrast to the field, so I think we're good.

**Comment by jcfilben** [comment]
Closing, this ticket was moved into 'Done' without being closed
