### ISSUE TITLE
Figma - Release/announcement plan

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2694]
We need to write an announcement message for the new Figma Components, which will be documented [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1469%3A28700).

There are two main goals for this ticket.

1) Figure out what to include within the message. Here are some possible things to mention:
- Link to summary page, deprecation plan, new figma file, any other relevant links.
- Details about which component are being released
- Where/who to contact for questions
- TBD

2) Where will this message be released? Here are some possible outlets:
- Slack channels (HPE-Design-System)
- Include in Kamlesh's newsletter
- Present in OH, record it, and ship it to teams individually
- Add into the What's New section
- Link somewhere on the DS site (update any old Figma links to this file)
- Reaching out to teams directly

**Comment by bahriaditi** [comment]
@KennyAtHPE @Keeth-HPe cc @SOjaHPE 

Here's the draft for the announcement - hope this helps. Feel free to edit if needed before posting it next week.

-------

**Designers: We have some exciting news for you!**

For the past couple of months, we’ve been hard at work updating components in our Figma library to meet your requests and design needs. We are thrilled to announce the release of the first batch of these updates, which include new and improved versions of: 
- [Date Input](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=212%3A578)
- [File Input](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=387%3A1967)
- [Text Input](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2%3A8)
- [List](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1058%3A18489)
- Page Header
- [Search](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=417%3A9849)

**Highlights of this release include:**
* Introduction of interactive components for quick prototyping
* New component variants with properties for added flexibility
* Consolidation of components into a single file “[HPE Design System Components](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2%3A26)”
* Bug fixes 


Owing to the complexity and scope of this work, Figma component updates will continue to be released in phases. We are currently working on prioritizing the next set of component updates.

As always, the HPE Design System team is committed to helping you design, prototype and build consistent and accessible HPE digital experiences. With these updates, we are hoping to provide you with greater flexibility while designing and increasing your overall workflow efficiency.

**Questions? See our guide to using the new components [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1825%3A34637).**

**Comment by KennyAtHPE** [comment]
Leftover comment about where we should announce this update: 

- Slack channels (HPE-Design-System)
- Include in Kamlesh's newsletter
- Present in OH, record it, and ship it to teams individually
- Link onboarding doc in the summary
- Added in What's New
- Link somewhere on the DS site (update any old Figma links to this file)
- Reaching out to teams directly

**Comment by KennyAtHPE** [comment]
Added/Edited a couple of things from the first draft

------------
**Designers: We have some exciting news for you!**

For the past couple of months, we’ve been hard at work updating components in our Figma library to meet your requests and design needs. We are thrilled to announce the release of the first batch of these updates, which include new and improved versions of: 
- [Date Input](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=212%3A578)
- [File Input](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=387%3A1967)
- [Text Input](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2%3A8)
- [List](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1058%3A18489)
- Page Header
- [Search](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=417%3A9849)

**Highlights of this release include:**
* Introduction of interactive components for quick prototyping
* New component variants with properties for added flexibility
* Consolidation of components into a single file “[HPE Design System Components](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2%3A26)”
* Bug fixes 


Owing to the complexity and scope of this work, Figma component updates will continue to be released in phases. We are currently working on prioritizing the next set of component updates.

As always, the HPE Design System team is committed to helping you design, prototype and build consistent and accessible HPE digital experiences. With these updates, we are hoping to provide you with greater flexibility while designing and increasing your overall workflow efficiency.

**Questions? See our guide to using the new components [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1825%3A34637).**
