### ISSUE TITLE
Add guidance on the use of the word "Health"

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2695]
To "Health" or not to "Health" that is the question. In the last Office Hours the devs/designers were confused on when to use the word "health," vs "status." If memory serves: Eric? and Scott? and maybe a few others agreed that we shouldn't be using health since there's no clear definition or distinction between status and we are already using the words status and state. MUST ADD TO OUR  guidance: under Taxonomy and "State v.s. Status"

https://design-system.hpe.design/components/notification?q=status#what-are-they-for?

**Comment by MikeKingdom** [comment]
State is different than status. Status can be ok or failed or such. But state is typically something more like booting, sleeping, initializing etc etc. Health and status tend to be synonomous for the most part in our products over the years. It definitely depends on the resources we're talking about but for the most part people want to understand if their services or resources are 'ok' or compromised or flat out critical/failed/down. In most cases we really try to convey this as the 'health' of these things. If you haven't talked to Edgar Circenis yet (he may have been in the office hours) I'd trust his input. He's been through this discussion many times over the years.

**Comment by dahliaferrer** [comment]
Hi, Mike, yes, this came up in the last Office Hours and we couldn't find a justification for using the word "health." Whereas most people thought it was a subset of "status," I thought just the opposite; that health is an overall state of being of all of these pieces. Also, I found an example of how Windows / MS products?? use health. I have a screenshot of something that looks like this:

[LEFT COLUMN]
Disk 0
Dynamic
20.00 GB
Online

[RIGHT COLUMN]
(C:)
20.00 GB NTFS
Healthy (System, Boot, Page File, Crash Dump)

Thinking of the future, if we haven't already started using "health" the same way as MS products, I think we should. 

Anyway, I think I just wanted to document this train of though.

**Comment by taysea** [comment]
Closing, added guidance here: https://design-system.hpe.design/components/notification?q=health#state-vs-status-vs-health
