### ISSUE TITLE
Multi-Select - Accessibility best practices (including feedback from Bill)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2697]
From Bill Tipton:
 
I enjoyed working with you all yesterday briefly as I evaluated those two multi-select prototypes with my screen reader JAWS (Related: #2661 #2662).
 
Besides what we discussed I had two more suggestions below:

- We did not test this although I am assuming  the selected items that are bubbled up to the top can be de-selected by using the space bar or enter key  then they would move back down to the list of unselected items.
- When you are only able to select a given number as the screen reader user selects each item it would be nice if there was a message stating how many items were selected out of how many items. Example using something like ARIA Live Region to have the screen reader speak selected to of five possibilities. Or better yet use native HTML if possible?
Please ask if you have any follow up questions from our meeting yesterday.

**Comment by jcfilben** [comment]
Marking as done, accessibility guidance from Bill has been incorporated. (See https://github.com/grommet/hpe-design-system/issues/2746#issuecomment-1216927586 for more detail)
