### ISSUE TITLE
Contribution - Common Toolbar for data collection

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2702]
Contribution by Geetha (Ezmeral)
[Figma link](https://www.figma.com/file/goiSj6Ox3AlJb6HgPLgjsJ/Search-Toolbar?node-id=0%3A1)

We think there is a lot of value in adding this to our Design System from the dev side - issue writeup here: https://github.com/grommet/grommet/issues/5438

**First next step:**
- [ ] Review designs and give feedback to Geetha 

------

**From Scott** ([Slack thread here](https://hpe.slack.com/archives/GPPLUK6LR/p1656517928392709)):
This fills a big hole in our design system, a common "compact" data collection toolbar (e.g. list, card, data table) that supports the most common data collection use cases- taking a large set of objects, utilizing Search/Filtering to narrow down the result, and actions to perform on the refined list of items. Actions can be selection dependent, common CRUD or custom actions that work in a 'selection mode'  etc..
What I like about it is, it puts the toolbar elements in a predictable consistent location. It also puts those elements into a single row, which makes is really easy to scan. This layout is easy to gracefully degrade as we get into narrower 'responsive' breakpoints. The only variants views I could see expanding upon would be use cases where applied filter chips would be exposed to easily communicate w/ the user what the active sort/filtering is and allows them to easily remove them.

As [@matthew.glissmann](https://hpe.slack.com/team/U026XM47AGH) mentioned, naming, details etc can be worked out later but I see this as a 'common toolbar' for all data collections.

**Comment by ericsoderberghp** [comment]
I like where this is heading. I've added some comments in Figma.
