### ISSUE TITLE
Feedback - Collect use cases

### ISSUE THREAD

**Issue by MeganBeierle** [grommet/hpe-design-system#2703]

**Comment by MeganBeierle** [comment]
[Original request can be found here](https://github.com/grommet/hpe-design-system/issues/2651)

I am breaking this task up into smaller parts. This task is to collect use cases from the requestors. This needs to be completed before the project can move on

**Comment by dahliaferrer** [comment]
Example of nice feedback: 
Click and scroll down a bit. You'll notice a subtle feedback request open up on the right (smiley face)
https://carbondesignsystem.com/

**Comment by MeganBeierle** [comment]
@ericsoderberghp Hi Eric! Can we move this one to the active board? I'll be able to close it out tomorrow.

**Comment by dahliaferrer** [comment]
@MeganBeierle Hi, have we come up with a design for feedback? I'd love to see it! I'd like to integrate it into the "Forms" guide, which should be published soon.

**Comment by MeganBeierle** [comment]
Hi @dahliaferrer 

Not into the design phase yet but I'd like to get you involved, I've sent you a meeting invite for tomorrow.

**Comment by MeganBeierle** [comment]
Use cases have been collected and reviewed, that can be seen here: https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-widgets?node-id=0%3A1
