### ISSUE TITLE
content review - New Components Guidelines KENNY

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2706]
Kenny brought this up individually to me on Slack "Wanted to get your eyes the outcome of this ticket."

https://github.com/grommet/hpe-design-system/issues/2626

**Comment by KennyAtHPE** [comment]
@dahliaferrer created a review ticket which will be populated with more context here: #2710

**Comment by jcfilben** [comment]
Closing, looks like review work is being tracked in #2710
