### ISSUE TITLE
Component Guidelines - Review

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2710]
Followup on #2626 

Will be getting reviews for the Component Guidelines which can be found [here](https://www.figma.com/file/mLpptzhm7RUZM3sIj1vxkd/Component-Guidelines?node-id=64%3A1647).

I will be reaching out and getting reviews from:
- Keeth
- Scott
- Aditi
- Beza
- Dahlia
- At least one dev [TBD]

Specific areas to note when reviewing:
- WIP

**Comment by KennyAtHPE** [comment]
Moving back into the available column. Unfortunately wasn't able to have review sessions with people due to being sick most of the week. Will tackle next sprint instead

**Comment by taysea** [comment]
Closing, stale.
