### ISSUE TITLE
Components Figma File - Finalize summary page

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2711]
As part of the new HPE Design System Components release, we will need to create a summary page detailing all of the new significant changes. That will be documented [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1825%3A34637).

After swarming with the designers to gather ideas, we have settled on creating an FAQ style summary. Here we will collate and answer all of the most common questions people may have related to this new release.

Some initial questions from that swarming session:
- Why are we doing this? Include benefits of the new components
- What are the new Figma components?
- Deprecation Plan (What happens to the old components?) (How does this affect existing designs?)
- What does this release include?
- How does this affect me? What do I have to do to stay up to date? Include instructions 
- How can I contribute (component guidelines, sandbox)
- What will happen to the old component files?

Additionally, we will need to include relevant links (Figma guide, Contribution Guide, Core Assets file, etc.).

**Comment by bahriaditi** [comment]
Hi @MeganBeierle I updated the copy in [Figma](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1529%3A33241)

Can you review when you get a chance? As discussed, this page may need some visual design help as well. We can then share with the rest of the team during our designer check in on Tue. Thanks!

**Comment by MeganBeierle** [comment]
@bahriaditi Great! I'll check it out and design it today.

**Comment by bahriaditi** [comment]
@KennyAtHPE @Keeth-HPe cc @SOjaHPE 
I've finished adding copy to this page. Could you please review one last time? Thanks!
[Figma link](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1825%3A34637)

**Comment by MeganBeierle** [comment]
@bahriaditi I made a few tiny changes, it looks sooooo good! Good job all : )

**Comment by KennyAtHPE** [comment]
@bahriaditi @bahriaditi @Keeth-HPe @SOjaHPE 
Added/edited a couple of things, everything looks good now. I'd hold off on closing this ticket until the end of the week. Will be adding things here and there as I continue to clean up the file, also gives time for Scott to review. Thanks to everyone so far!

**Comment by KennyAtHPE** [comment]
Triple checked everything, looks good to me. Will add more to it once questions come in after the release but will be closing this ticket.
