### ISSUE TITLE
Multi-Select - v4 prototype

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#2716]
Create prototypes for each of the designs show here: https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=1666%3A14355

**Comment by bahriaditi** [comment]
Linking updated prototypes from Jessica here:

Default
- https://deploy-preview-6222--sad-tereshkova-173d07.netlify.app/?path=/story/input-select-multi-select-option-1--multi-select&globals=theme:hpe

Variant
- https://deploy-preview-6230--sad-tereshkova-173d07.netlify.app/?path=/story/input-select-multi-select-variant--multi-select&globals=theme:hpe
- https://deploy-preview-6230--sad-tereshkova-173d07.netlify.app/?path=/story/input-select-multi-select-variant-2--multi-select-2&globals=theme:hpe

---

Based on my discussions with Jessica and inputs from stakeholders this week, some pending issues we are hoping to resolve before we retest with Bill Tipton next week:

1. Variant: There are use cases (ex: Serve selection in Bare Metal), where selected items can't be unselected. In these cases, we could disable checkbox but that will create an accessibility issue for screen readers. Decision on design and dev side TBD.

2. Variant: Once items are selected, and the user decided to unselect some, those remain in position (i.e. don't disappear from input level) until next time the drop is expanded. This is great for accessibility but can potentially be a confusing/ awkward UX.
