### ISSUE TITLE
Feedback - Content strategy

### ISSUE THREAD

**Issue by MeganBeierle** [grommet/hpe-design-system#2718]
[Design research task can be found here](https://github.com/orgs/grommet/projects/12/views/1)

****Problem Statement****
We don’t have contextual locations in the GLCP to collect customer feedback. We will create three types of feedback collection components that can be utilized in a variety of placements and will provide three potential metrics: Net Promoter Score (NPS), Customer satisfaction survey (CSAT), and Customer effort score (CES). 

****Business Goals****
_What do you want to achieve with this project?_ 
Know how our GLCP customers experience a specific product or customer process.

_What features are essential to this?_
Different ways of gathering feedback and gaining metrics. 

_What kind of feedback do you need to achieve your goals?_
Actionable

_What problems can you potentially solve with the right feedback?_
We will be able to know if customers are satisfied with the platform and the apps, gauge if specific flows are easy for customers to walk through, evaluate effectiveness of content.

****User Goals****
_What motivates them to use your product?_
Consolidation of data and analytics, ease of use

_What features will truly deliver value to the users?_
Simple customer actions, actionable data, large quantities of data consolidated in one place

_What kind of feedback do you need to learn about your users and what they need?_
We need to know if our applications are easy to use, effective and invaluable to our customers. 

Research and provide content for the three types of surveys we will be implementing. Megan will work on design in tandem. [Figma file with research and use cases can be found here](https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=1%3A148)

**Comment by dahliaferrer** [comment]
I'd created this issue on May 24 #2616 
Condensed summary:

For an efficient content strategy, analytics are crucial. Data is needed from a wide audience (within our target market) and as close after publishing date as possible, so adjustments can be made quickly. "Fail fast" and adjust quickly!

I'd like to
- get analytics from a wider group of people, not just the "regulars" on a Slack channel or our close colleagues who may think like us already

- get analytics from designers/devs who are actually using that guidance page for a real-life, active project

- make the feedback button a little more proactive (i.e. contextual, not in the footer, like it is currently)

- give one feedback option, preferring an easy, quick impression (vs 3 options that we have now, user might get decision paralysis and decide it's best not to give an answer at all)

I like this example:
https://feedletter.co/feedback-button/

**Comment by jcfilben** [comment]
Closing, feedback guidance has been added to the design system site https://design-system.hpe.design/templates/user-feedback-collection?q=feed
