### ISSUE TITLE
Design System Adoption Assessment

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#2721]
**Discovery Phase**: Starting with preliminary discovery working meetings reviewing product flows from a Compute Ops Management instance.

**Goal**: to generate a step by step 'Draft Working Script' based on these 'by-hand' assessment working sessions, reviewing Compute Ops implementation screen by screen, element by element to efficiently evaluate them as coded. Plan is to iteratively improve and adapt this stepped process to an efficient guided format where it will be repeatable and enable a designer/developer to perform self-assessments of their GreenLake Platform product service flows.

**Concrete Deliverables**
- Review the Compute Ops Manag. working session assessment notes, organize and compile them into clear and concise steps.
- Collate and merge the latest step by step assessment script with the current D[S Adoption and Assessment Criteria Checklist](https://hpe.sharepoint.com/:x:/r/teams/hpe-design/_layouts/15/Doc.aspx?sourcedoc=%7B294AC767-3FAC-4D58-B750-8ECC7C25B7AF%7D&file=DS%20Adoption%20and%20Assessment%20Criteria%20Checklist.xlsx&action=default&mobileredirect=true&cid=0bb39ddc-3490-40cc-ac89-f0fcf0299a06) 'Compute Assessment Criteria' tab to put it into a consumable form.

**Comment by taysea** [comment]
Closing, stale.
