### ISSUE TITLE
GLCP - Arising issues that have been observed

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2725]
Upon chatting with Scott on how my time during GLCP is going, he mentioned it would be good for me to add a ticket to our backlog to document problems i've been seeing within GLCP to further understand issues and potentially come up with solutions. @SOjaHPE @ericsoderberghp

**Comment by vavalos5** [comment]
- Devs are directing UX design rather than listening to designer on what is already available (meeting has been set up to discuss Pagination with a developer). I suggested we include a developer from the DS so they can best give direction as the suggestion I gave didn't seem to cover what they wanted to do. See screenshots below:
<img width="547" alt="Screen Shot 2022-07-12 at 2 36 35 PM" src="https://user-images.githubusercontent.com/62117454/178600210-24eeeaa2-26ce-4c78-9fba-d75bc0c8a581.png">
<img width="537" alt="Screen Shot 2022-07-12 at 2 37 04 PM" src="https://user-images.githubusercontent.com/62117454/178600222-fa07c39b-a3d5-410e-a0af-302a949575b8.png">

<img width="462" alt="Screen Shot 2022-07-12 at 2 37 17 PM" src="https://user-images.githubusercontent.com/62117454/178600231-29922b4b-67eb-4e66-b8f8-b8d2f41bb0a9.png">

<img width="535" alt="Screen Shot 2022-07-12 at 2 37 56 PM" src="https://user-images.githubusercontent.com/62117454/178600237-f9d03965-1f2a-4ad5-90ff-5b8052790af8.png">




- Devs are not using theme/don’t know about theme and basing padding/spacing off of direct designs
- Devs coming from Aruba Central don’t seem to know about Design System/t-shirt sizing
- UI Component direction being influenced in PAL by higher ups/management causing the DS to not be the single source of truth

**Comment by taysea** [comment]
Closing, stale.
