### ISSUE TITLE
Add guidance on "Placeholder text"

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2727]
To add some value and ease of use for our customer end users, we should give our devs/designers guidance on instructions to write as placeholder text.

Currently, what I've seen is pretty redundant and a misuse of real estate. For example: 

[field label] Cluster name*
[empty field where user can enter name]

[field label] Description Optional
[field with placeholder text where user can enter a description:] Write your description here. 

A better placeholder text for the optional description field could be along the lines of: Write a helpful description to easily differentiate this cluster from others.

RELATED: In our guides we haven't been taking advantage of that real estate, either. We often put lorem ipsum placement text when we could, instead, speaking to our devs/designers in these fields with what is important to place in those fields.

**Comment by taysea** [comment]
Closing, stale.
