### ISSUE TITLE
Add an in-page table of contents to increase visibility of page content

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2734]
To improve the ability to discover page content and navigate to it, an in-page "jump to section" navigation should be implemented.

Design file: https://www.figma.com/file/qbbYGi73ncFAoLQ0IM1Y7x/DS-Guide-Template?node-id=3875%3A20038

- [x] The "jump to section" should remain sticky on scroll so it's always in view
- [x] The current section should be marked as active and update as the user scrolls
- [x] The headings should be parsed from the markdown and pulled in dynamically to ease maintenance as more guidance is written

**Comment by dahliaferrer** [comment]
For background, just mentioning that this is related to the following tickets:

"Forms" guidance 
https://github.com/grommet/hpe-design-system/issues/2610

DS Guide Template
https://github.com/grommet/hpe-design-system/issues/2676

**Comment by taysea** [comment]
Can use https://github.com/grommet/hpe-design-system/pull/2134 as a reference starting point

**Comment by JCoder121** [comment]
Will review current iteration with Taylor when she gets back, then may meet with Dahlia to discuss further direction.
