### ISSUE TITLE
Multi-Select - Test prototype v4 with Bill Tipton

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2740]

**Comment by bahriaditi** [comment]
Recordings can be found using these links:

Variant (Jessica, Aditi, Bill T.)
https://hpe-my.sharepoint.com/:v:/p/aditi_bahri/EciU-xAN4nROuIllchevC0UBmQQdCKvNkiTR3OQ4gvLXaA?e=xuFebf

Default (Matt, Aditi, Bill T.)
https://hpe-my.sharepoint.com/:v:/p/aditi_bahri/Ecq4Hnpda6RHmjF3dujY2MsBF64jhKHy1mlGubGRwlioGA?e=N8gU12

I've noted some key takeaways in ticket #2746
