### ISSUE TITLE
Design System Home Page - Redesign Home Page

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2741]
After seeing the GLC Plaftorm Updates for Edmonton and the new brand suggestions, it would be great to redesign the home page. 

It would be good to start gathering insights on what people come here for primarily to understand how they engage with the site. Figure out what goes on this page.

- [ ] Site Refresh - Create a few different designs for feedback
- [ ] Site Refresh - Implement based on latest design

**Comment by taysea** [comment]
Closing, will handle refresh work in newer ticket since design has shifted.
