### ISSUE TITLE
Multi-Select - grommet Implementation

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#2746]
Implement Multi-Select on Grommet based on the designs in [Figma](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=1666%3A14355).

Here are prototypes of the multi-select designs:
[Default Version](https://deploy-preview-6222--sad-tereshkova-173d07.netlify.app/?path=/story/input-select-multi-select-default--multi-select&globals=theme:hpe)
[Default w/ Limited Selections](https://deploy-preview-6222--sad-tereshkova-173d07.netlify.app/?path=/story/input-select-multi-select-limited--multi-select-limited&globals=theme:hpe)
[Variant](https://deploy-preview-6230--sad-tereshkova-173d07.netlify.app/?path=/story/input-select-multi-select-variant-2--multi-select-2&globals=theme:hpe) (Shows selections at the input level)

Code can be found here:
[Default](https://github.com/grommet/grommet/pull/6222)
[Variant](https://github.com/grommet/grommet/pull/6230)

Code notes:

- Notice most of the 'heavy lifting' is being done in the story files. We might want to consider if there are opportunities to simplify the pattern we are handing off to hpe devs and have more built into grommet. Multi-Select could potentially be its own component.

- In the variant code, notice the changes to the DropButton in `Select.js` to accommodate having options at the input level. Might be tricky to build something like this into the current Select code without making too many changes.

Additional notes:

- Aditi and I did some accessibility testing with Bill. We only had time to go over the variant and didn't get to test the default version with him so that may happen sometime next week.

- The multi-select should have the ability to specify the number of options to show before we enable scrolling (for example show 10 options before I have to scroll to see more). Note that this is something that is not currently built into the prototypes.

- The CheckBox in the options shouldn't have a hover styling since we already have hover styling on the Button containing the option.

Key areas for accessibility:
- When we are limited in the number of options we can select once we hit that limit the remaining options should be disabled, but still accessible via keyboard navigation and read out by a screenreader.

- In the variant when we remove selected options at the input level we want to make sure the screenreader reads out that an option was removed and which option.

- When searching if the user presses enter the focus should be moved to the first item in the results.

- 'Select All' button should notify a screenreader user when selected that all options were successfully selected without reading out every option.

**Comment by bahriaditi** [comment]
Based on [#2740](https://github.com/grommet/hpe-design-system/issues/2740), noting additional accessibility considerations here:

- [ ] Clear description indicating what kind of input it is Ex: Bill suggested “select dropdown/ pulldown”
- [ ] Clear description of search field including helpful context like “search to filter select options”
- [ ] Easy way to distinguish between selected and unselected items
- [ ] Validating which item has been selected or unselected (Ex: "Selected Strawberry" instead of "Selected")
- [ ] Easy way to exit dropdown without changing selection, other than Esc key
- [ ] Call out how many search results there are, or if no matches are found
- [ ] In the default version, don't announce all selected items when input is collapsed
- [ ] Some way of letting the user know that they are at the end of the list (NICE TO HAVE 🍪 )
- [ ] Limited selection: Clearly communicate how many selections are permitted and notify when user has reached their limit (Should say “max limit reached” instead of just indicating that a list item is “unavailable”/ disabled)

**Comment by jcfilben** [comment]
- [x]  Clear description indicating what kind of input it is Ex: Bill suggested “select dropdown/ pulldown” 
When you navigate to the select the screenreader (tested with voiceover on mac) reads: "listbox popup collapsed button" this is consisted with how other select components are read out by the screenreader.
- [x]  Clear description of search field including helpful context like “search to filter select options”
Screenreader reads: 'Search to filter options. Search text field.'
- [x]  Easy way to distinguish between selected and unselected items
Selected options read “<Name of the list item> selected (x of total amount)”.
Unselected options read “<Name of the list item> not selected (x of total amount)”
- [x]  Validating which item has been selected or unselected (Ex: "Selected Strawberry" instead of "Selected")
- [ ]  Easy way to exit dropdown without changing selection, other than Esc key
For now this wasn't implemented. Closing with Esc key is how components like Calendar and DropButton are currently working. I think this step will require some additional thought on how we want to handle this and changes will extend beyond the MultiSelect component.
- [x]  Call out how many search results there are, or if no matches are found
Once the user presses enter on the search their focus will be moved to the first item which will include the number of results when read out.
- [x]  In the default version, don't announce all selected items when input is collapsed
Changed to announce the number of selected items instead of reading them out.
- [x]  Some way of letting the user know that they are at the end of the list (NICE TO HAVE 🍪 )
Once they get to the last option it will read out the option which includes reading out (x of total amount).
- [x]  Limited selection: Clearly communicate how many selections are permitted and notify when user has reached their limit (Should say “max limit reached” instead of just indicating that a list item is “unavailable”/ disabled)
When the user reaches the maximum number of selections the screenreader will read "Maximum number of selections reached".

**Comment by jcfilben** [comment]
Done, component was added in https://github.com/grommet/grommet/pull/6275
