### ISSUE TITLE
Notification - create taxonomy & anatomy for inline notifications

### ISSUE THREAD

**Issue by MeganBeierle** [grommet/hpe-design-system#2748]
[Please see the research task for this topic. ](https://github.com/grommet/hpe-design-system/issues/2523)

- [x] Review research and use cases that have been gathered
- [x] Define taxonomy of inline page banners
- [x] Create anatomy of inline page banners

**Comment by KennyAtHPE** [comment]
Will be connecting with Devs on the WIP for the next sprint.

**Comment by KennyAtHPE** [comment]
Taxonomy [here](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=4403%3A17695)
Anatomy [here](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=4403%3A17751)

After reviewing the use cases and requirements, thinking that there are two types of components needed here.
1) Page-Specific Banners
2) Inline Alerts

Reviewed work with Taylor and Aditi, next steps are to further explore how multiple page-specific banners can be displayed. That is being tracked in #2788

Closing out this ticket.
