### ISSUE TITLE
Feedback - Component description

### ISSUE THREAD

**Issue by MeganBeierle** [grommet/hpe-design-system#2749]
[Please see past progress on feedback component here](https://github.com/grommet/hpe-design-system/issues/2737)

- [x] Meet with Dahlia to clarify copy request
- [x] Meet with Brittany to review anatomy 
- [x] Begin writing description for website
- [x] Develop additional designs needed for website

**Comment by MeganBeierle** [comment]
Here is a link to the current work: https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=178%3A9151 

I'm open to feedback on everything!

**Comment by ericsoderberghp** [comment]
Looking good to me
