### ISSUE TITLE
Compute - Apply Page, PageContent, PageHeader to Compute Ops Management

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2751]
Contribute easy Design System adoption wins to Compute team.

Page, PageContent, and PageHeader might be a good place to start.

**Comment by taysea** [comment]
https://github.com/compute-cloud/indigo/pull/454

**Comment by taysea** [comment]
This PR has been approved by their team and is awaiting merge from the deployment team. Closing since our work is completed.
