### ISSUE TITLE
Modal - Figma and site unaligned

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2752]
The design system site is showing an h2 for the heading but Figma is showing an h4. Please align the Figma file to an h2 so it is semantically aligned with design system site.

<img width="1768" alt="Screen Shot 2022-07-25 at 3 34 11 PM" src="https://user-images.githubusercontent.com/62117454/180885644-28f6428d-d7a7-435e-bea2-7ff059ebc348.png">

<img width="1236" alt="Screen Shot 2022-07-25 at 3 34 21 PM" src="https://user-images.githubusercontent.com/62117454/180885639-cb5f87d8-9314-4cbe-925d-b7c108ac28a6.png">

**Comment by bezAdane** [comment]
Updating the [Figma component file](https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=100%3A70) text size to H2 and published the changed updated component. 

Closing this ticket
