### ISSUE TITLE
Forms page crashes if you have a direct link or refresh the browser on that page

### ISSUE THREAD

**Issue by MikeKingdom** [grommet/hpe-design-system#2754]
If you go directly to https://design-system.hpe.design/templates/forms (or refresh the page while on that url) it crashes.

### Is this issue related to the design system core library or design system website?

design-system-website

### URL, screen shot, or CodeSandbox exhibiting the issue

![image](https://user-images.githubusercontent.com/12054362/180892330-81bbd074-c039-474b-993c-4e07d0d17674.png)

![image](https://user-images.githubusercontent.com/12054362/180892382-9e5962ea-9a22-4141-8a37-d5248688ec4c.png)

### Steps to Reproduce

Go directly to https://design-system.hpe.design/templates/forms or hit browser refresh while on that page

### Your Environment

Windows 10 and Chrome browser

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by britt6612** [comment]
looking at this looks like has to do with `fileInput`

<img width="1020" alt="Screen Shot 2022-07-25 at 7 19 13 PM" src="https://user-images.githubusercontent.com/42451602/180901927-65215d55-2774-4ed3-8ba3-9079f0ea7721.png">
