### ISSUE TITLE
Spinner -inconsistency in a component  and grommet spinner  color - 

### ISSUE THREAD

**Issue by bezAdane** [grommet/hpe-design-system#2755]
Geetha brought this to our attention where Spinner color has inconsistency.
- The grommet hpe theme spinner is primary green but the component has a different color. We need clarification on which one is correct so we can fix this.

**Here are the examples** 

https://storybook.grommet.io/?path=/story/visualizations-datatable-placeholder--placeholder&globals=theme:hpe

https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Loading-Indicator-Component?node-id=615%3A4428

**Comment by britt6612** [comment]
closing since https://github.com/grommet/grommet-theme-hpe/pull/259 was merged
