### ISSUE TITLE
Keyword audit of DS guide pages - metatags

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2758]
Problem: currently searches on the DS website do not conjure up results using semantics/synonyms or related words.

The cards on the Design System home page will get to be too many. Devs/Designers are trying to find things quickly. I'm betting most go directly to the search bar. But we do not have enough semantics on any of our guide pages. Also it sounds like speaking with Matt and others that maybe we could do something with the "search" algorithm. All this is towards increasing user-friendliness, adoption and accuracy in designs.

**Comment by dahliaferrer** [comment]
Matt gave me some analytics on the page views. This was helpful in determining, based on popularity, which of the guides we should add more tags/keywords/semantics.

Components
Color
Our Brand
Typography
Dashboards
DataTable Customization
Forms
Content Layouts
Page Layouts
Button

I'm tracking progress here in an Excel sheet. We currently have **68 guides**!

https://hpe-my.sharepoint.com/:x:/r/personal/dahlia_ferrer_hpe_com/_layouts/15/Doc.aspx?sourcedoc=%7B6C26EC54-A0C2-47B1-80F8-A2713DAC3084%7D&file=Book.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=dahlia.ferrer%40hpe.com&ct=1659116591442&wdOrigin=OFFICECOM-WEB.MAIN.EDGEWORTH&cid=014a1647-8fbb-4b86-a630-578776c39def

**Comment by dahliaferrer** [comment]
The DS website somehow keeps the metadata for all of the guide pages in three files, one for each category in the site: Foundation, Components, Templates... separate from each page! I really don't know how search engines read this, but for the purposes of HPE designers and developers searching the site, I've been changing the intro sentence to be more of a precise definition and with the idea of letting the reader know whether they've hit the right page or not. 

Taylor sent me the MDX files for each category and I've been adding some metatags and updating the first sentence. Sometimes editing the SEO metatitle.

**Comment by taysea** [comment]
Closing, added these in a PR previously.
