### ISSUE TITLE
August Grommet Hpe theme release

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2763]

**Comment by taysea** [comment]
@jcfilben Should we add the menu group separator color that's in aries-site, so we can strip it out of the local theme?

https://github.com/grommet/hpe-design-system/blob/master/aries-site/src/themes/aries.js#L9

**Comment by jcfilben** [comment]
> @jcfilben Should we add the menu group separator color that's in aries-site, so we can strip it out of the local theme?
>
> https://github.com/grommet/hpe-design-system/blob/master/aries-site/src/themes/aries.js#L9

Yes good call! I think we should get that in before we release, I can go ahead and make a quick PR to add this

**Comment by jcfilben** [comment]
> > @jcfilben Should we add the menu group separator color that's in aries-site, so we can strip it out of the local theme?
> > https://github.com/grommet/hpe-design-system/blob/master/aries-site/src/themes/aries.js#L9
> 
> Yes good call! I think we should get that in before we release, I can go ahead and make a quick PR to add this

Pull request created https://github.com/grommet/grommet-theme-hpe/pull/274
