### ISSUE TITLE
A/B testing new DS template vs previous

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2764]
**Problem**: Currently each Design System guidance page presents guidelines in an inconsistent manner. Most people on our team have noticed that having some predictability for our users in terms of sections on the page is highly desirable, for better usability and efficiency of our users' information-gathering task. 

I've created a draft template and we will need to test it to see how our devs/designers like it in comparison to the previous formatting. 

For feedback and to discover what we could tweak to make the template better, we are using a multi-faceted approach.

- A/B analysis
- In-context feedback (being developed by Megan)
- Testing/surveys with the Research dept.

THIS TICKET is only concerned with the A/B analysis.

Tasks:

- [x] Ensure that the information matches in the new template and the previous format of the "forms" guidance (which we are using as our first test). This is important so that the users do not give a higher rating to one or the other based on the quality of the information. We are only testing the template/format in which the information is presented. Not the quality, therefore the quality must be equal across both A and B.

- [ ] Have someone set up the A/B testing in Github. Scott had mentioned speaking to Taylor.

**Comment by taysea** [comment]
Closing as outdated/stale.
