### ISSUE TITLE
New video for DS home page

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2765]
Problem: the video that is currently on the site is good. But I wonder if it would be more effective if we opened the video with a developer actually implementing the grommet component and using the DS guides? Quick, quality video...?

Also, at Discover HP Brand released new sounds for videos and the new logo, or "badge." Eventually we should probably update these in the video anyway.

**Comment by jcfilben** [comment]
@halocline can we close this? It doesn't feel like this is something we should invest resources in at this point

**Comment by halocline** [comment]
Agree. Timing and priorities are not right for this effort. Closing due to not planned in the near or mid term roadmap.
