### ISSUE TITLE
Contribution - Center Modal templates (Medium enhancement)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2767]
Sanmid from Ezmeral has contributed modal patterns for us to consider adding to the Design System library. Taylor and I have already walked through the file with Sanmid to get a good understanding of whats being proposed.

I think this will be super helpful for designers to create quick mockups in Figma. This also looks pretty close to completion so potentially an easy win if we can wrap it up.

[Figma sandbox link](https://www.figma.com/file/JMgO7PiNSfP2BONCYwB0kf/Modals?node-id=3%3A141)

**Comment by vavalos5** [comment]
I'd be interested to hear which examples we're planning to include into Figma/Design System site because I was thinking of adding some PAL examples too. :)

**Comment by bahriaditi** [comment]
> I'd be interested to hear which examples we're planning to include into Figma/Design System site because I was thinking of adding some PAL examples too. :)

That's great to hear @vavalos5! Go ahead and add them to a separate page on the Sandbox file:
https://www.figma.com/file/JMgO7PiNSfP2BONCYwB0kf/Modals?node-id=0%3A1

**Comment by vavalos5** [comment]
Totally didn't see the comment above. Once I get around to this, I can add examples. For now, here's the link to PAL where there's many different variations of Modals: https://www.figma.com/file/6hYD74saV26sSgoLd3Fu9q/PAL-(Platform-Asset-Library)?node-id=1047%3A26608

**Comment by taysea** [comment]
Closing stale, aiming for content driven modals.
