### ISSUE TITLE
DataTable Customization - Create Figma component for column configuration

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2768]
Sylvia requested a Figma component for use in GLCP designs, based on the guidance we have on the site: https://design-system.hpe.design/templates/datatable-customization?q=data#column-visibility

She has the component 50% completed and wanted us to take it over. Would be good if we can prioritize within the next couple of weeks and get this into their local PAL library. 

[Sylvia's design (Figma)](https://www.figma.com/file/6hYD74saV26sSgoLd3Fu9q?node-id=5116:121342#236343262)
[Previous DS design (Figma)](https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=868%3A38562)

**Comment by Keeth-HPe** [comment]
@bahriaditi  @KennyAtHPE 

https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=2138%3A14227
Please do take a look & share feedback.

**Comment by bahriaditi** [comment]
Thanks for your work on this, @Keeth-HPe 
It's mostly looking good except for a few minor details. I moved your work to the [WIP page](https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=2295%3A21772) and left some comments for you. Let me know if you have any questions.

**Comment by bahriaditi** [comment]
This is done ✔ 
[Figma link](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2915%3A56106)
