### ISSUE TITLE
Tool Tip - Deprecate duplicative component in Figma

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2776]
Priority of this component fix can be tracked [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2438%3A45572). @ericsoderberghp 

Currently, in Figma we have two similar components that are causing confusion for external teams.
1. [Tip](https://www.figma.com/file/Jd34cI5yyZIPb5BIwkIPU2/HPE-Tip?node-id=215%3A558)
2. [Tool Tip](https://www.figma.com/file/0zhBD70lp2O8D7bAgLaM5T/HPE-Drop-Component?node-id=181%3A190)

The "Tool Tip" component currently has two issues with it:
- It showcases a tip without a border
- It has an example with an anchor in it

GLCP is currently using tips with and without a border due to this inconsistency. 

### Objectives

- [x] Combine the two components into a new component while omitting the issues from the "Tool Tip" component.
- [x] Move the newly created component into the [HPE Design System Components file](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=0%3A1). 
- [x] Deprecate the two old components
- [x] Move the files of the old components into "Working Files" and update their thumbnail to [this](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2000%3A62061).

**Comment by Keeth-HPe** [comment]
@KennyAtHPE  Please test the component [here](https://www.figma.com/file/Jd34cI5yyZIPb5BIwkIPU2/HPE-Tip?node-id=2215%3A4009&t=mV26uBEjL4ryKQwz-1) And share feedback when you get the chance to.

**Comment by KennyAtHPE** [comment]
This component looks completed @Keeth-HPe. Please go ahead and deprecate the 2 older components, move this over to the Design System Components file, fill out the component template sheet, and publish/announce the component.

**Comment by KennyAtHPE** [comment]
The component has been completed, closing out the ticket.
