### ISSUE TITLE
Tokens - Explore Figma plugin sync with GitHub

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2777]
Building on #2627

### Objectives
- Test Figma Tokens plugin syncing features with GitHub. ([Plugin Docs](https://docs.tokens.studio/sync/github))
       - Can changes be pushed and pulled easily?
       - Are there any limitations?
- Test with multiple collaborators within a Figma file. 
       - Are tokens shared between users?
       - Are token updates automatic between users?

**Comment by SOjaHPE** [comment]
@KennyAtHPE  finally located the link to the Schema 2021 talk video that covered Design Tokens

- [https://www.youtube.com/watch?v=ylDed18OVdY](url)

**Comment by KennyAtHPE** [comment]
Exploration on this plugin has been completed by Ashley, Joelle, Taylor, and myself. We will instead be utilizing the new Figma variables feature. Closing ticket.
