### ISSUE TITLE
Brand Refresh - first draft `hpe` theme pull request

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2779]
In order to advance the evaluation of the recent HPE brand update, we should explore the details of the impacts to grommet components and with the `hpe` theme.

## Deliverables

- [x] an initial pull request for changes to the HPE theme to adapt to the new HPE brand direction
- [x] Submit pull request against NEXT branch

**Comment by halocline** [comment]
Closed by https://github.com/grommet/grommet-theme-hpe/pull/261
