### ISSUE TITLE
Notification - Explore how to showcase multiple notifications at a page-level

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2788]
Building off #2748 

Work can be found [here](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=4403%3A17695)

-------------------------------------
### Deliverables

- [x] Reach out to stakeholders to gather more insight and use cases
- [x] Reevaluate past research and formalize a problem statement
- [x] Explore accessibility concerns and WCAG requirements (connect w/ dev?)
- [x] Explore other concerns and create success criteria
- [x] Define specific use cases where multiple notifications are needed and when a different solution should be sued
- [x] Begin design iterations
- [x] Create follow-on tickets

#### Exploration

Through the use cases and requirements received, there are some instances in which multiple page-specific banners are needed. Some considerations to keep in mind:

- How many banners can be shown at once and what limit should be imposed? Keep in mind screen real estate and how this would work on smaller screens.
- Keep in mind accessibility concerns.
- Should there be a limit to the amount of text?
- How can different status banners be differentiated from each other?
- What use cases are these applicable for and when should the designer instead defer to using a notification center?

-----------------------------------------
#### Stakeholders and resources

- Sherry Mead
- Greg Furuyie
- Amanda Vogel

[WCAG Notification documentation](https://www.w3.org/WAI/tutorials/forms/notifications/)

**Comment by KennyAtHPE** [comment]
Another [use case](https://www.figma.com/file/OTL2PLdD9TkAAeYuPbP3fE/Clusters-and-Blueprints-Visualisation?node-id=360%3A12120&t=c3KqGvFkBhEAjWBA-1) of multiple banners being shown from Chandan

**Comment by halocline** [comment]
In addition to the above, I would be interested in seeing an option where if there are multiple notifications, the notifications are consolidated to a single notification which summarizes the number of issues by criticality and provides links to the instances of inline notifications.

Alternatively, an option where only one notification is shown at a time. Notifications will be prioritized by criticality. As each notification is resolved, the next one would appear.

These might not be the direction we end up going, but should be in the consideration set.

**Comment by wenannie8** [comment]
![Image](https://github.com/grommet/hpe-design-system/assets/137263626/9fa49b90-1939-4cc4-acc0-8f8e6a80b9c3)

**Comment by KennyAtHPE** [comment]
8/8 Update:

Met with Sherry, Greg, and Amanda to gather more use cases. Gathered accessibility insights and researched guidance from other design systems. Will be formulating a problem statement, success criteria, and a list of use cases where multiple notifications could be used.

**Comment by KennyAtHPE** [comment]
Shared out w/ team during show and tell. Follow up ticket to continue explorations has been created #3513. Closing this ticket.
