### ISSUE TITLE
Search behavior

### ISSUE THREAD

**Issue by jensy** [grommet/hpe-design-system#279]
![Kapture 2020-01-22 at 13 17 55](https://user-images.githubusercontent.com/105723/72930647-a4685880-3d19-11ea-9caf-0f11a4bf0b4c.gif)

A couple of things I have noticed.

1. Animation of the search results box seems slow, is it necessary to animate this?
2. Search input field seems "too smart" as you can't type anything in there that does not match with an existing page. Instead you might want to track this to inform what people would like to see.
3. Search input is not carrying over when you select a result.

**Comment by halocline** [comment]
Conducted an evaluation regarding "[How might we enhance the search experience](https://github.com/grommet/hpe-design-system/issues/1787)?" That issue will close this ticket and elaborate next steps for implementation.
