### ISSUE TITLE
Multi-Select - Create Figma component

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2790]
Create Figma component locally first. Wait to publish and distribute until component is published on Grommet/ site.

**Comment by bahriaditi** [comment]
This ticket is blocked by #2816 so most likely carry over to the next week

**Comment by Keeth-HPe** [comment]
@bahriaditi 

Made two options of components with different variants. 
one is the exclusive multi-select component:  https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=2335%3A27308

The other one includes the 'multi-select list' within the select component. 
https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=3131%3A14956
I'm aware on the grommet side multi-select is different from 'select'. But I was wondering if there is a way to make changes to the grommet. 

I tested this with a few mates from the India team, and they also felt having multi-select with the select works well

**Comment by Keeth-HPe** [comment]
@bahriaditi 
https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=3162%3A11572
 I have added input variants that we disscussed. Please take a look. 🙌

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe 
Based on our call this morning, making a note of some next steps:

- Create SelectMultiple as a separate component from Select (to avoid having a long list of properties which can be overwhelming for users)
- For Visible Selection variant - create a toggle switch, similar to the FileInput component construction

**Comment by Keeth-HPe** [comment]
@bahriaditi  @KennyAtHPE 
 select multiple is now a separate component from Select. Request you to please review :) 

- [ ] Create SelectMultiple as a separate component from Select (to avoid having a long list of properties which can be overwhelming for users)
- [ ] For the Visible Selection variant - create a toggle switch, similar to the FileInput component construction

**Comment by KennyAtHPE** [comment]
Will be getting to this, apologies on the delay.

**Comment by KennyAtHPE** [comment]
Left some comments for review.

**Comment by Keeth-HPe** [comment]
Comments have been fixed. The component is ready. 

P.S Documentation is pending.
