### ISSUE TITLE
Brand Refresh - Consume the grommet-theme-hpe NEXT-stable branch in the Design System site

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2793]
- [x] Create either a draft PR w/ deploy preview or use the NEXT branch on hpe-design-system site which consumes the grommet-theme-hpe NEXT-stable branch

This will be used for auditing the HPE Theme with new branding elements.

**Comment by taysea** [comment]
https://github.com/grommet/hpe-design-system/pull/2799
