### ISSUE TITLE
Brand Refresh - Create a list of all instances where Grommet components consume Button

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2794]
This work will assist in the audit for how rounded buttons may affect how Buttons are consumed by other Grommet components. For example, Drop buttons, Select options, interactive Table cells, etc. We will want to understand whether all instances should receive rounding or whether certain components should receive component specific button styling such as allowed for in FileInput and Pagination.

- [x] Create a comprehensive list of all Grommet components which consume Button.
- [x] Add that list to a comment on this issue. This will serve as a component audit checklist which will identify any areas of additional theme or Grommet work needed.

**Comment by taysea** [comment]
- AccordionPanel
- Calendar (days, Calendar header arrows)
- Carousel (left/right arrows, stepper buttons)
- DataChart (legend)
- DataTable
   - ExpanderCell
   - Header
- DateInput (Calendar button)
- DropButton
- FileInput (browse and remove buttons)
- List (ordering)
- MaskedInput
- Menu
- Notification (close toast button)
- Pagination —> PageControl
- Select
- Tab
- Tag (remove button)
- Video (controls)
