### ISSUE TITLE
Leverage "useIntersection" hook for Jump to Section

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2798]
Leverage HPE project scripts useIntersection hook in place of one-off implementation for consistency across projects.

https://github.com/HewlettPackard/hpe-js-project-scripts/tree/master/packages/react-hooks#useintersection

**Comment by jcfilben** [comment]
Closing, based on comments in https://github.com/grommet/hpe-design-system/pull/2829 the jump to section functionality is working correctly without `useIntersection`
