### ISSUE TITLE
Brand Refresh - Make Yes/No decision on whether the Design System should support PageHeader "size"

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2803]
- [x] Setup meeting with @SOjaHPE , @bahriaditi , @MikeKingdom , @taysea , @halocline 
- [x] Review [PageHeader size use case and recommendation](https://github.com/grommet/hpe-design-system/issues/2773#issuecomment-1200066831)
- [x] Decide "yes, support" or "no, don't support"
- [x] Create follow on issues as needed: https://github.com/grommet/grommet/issues/6273

**Comment by halocline** [comment]
Yes, support.

**Comment by ericsoderberghp** [comment]
Yes to adding `<PageHeader size="" />`. Assuming this would impact both `margin` and Heading `size`.

**Comment by taysea** [comment]
Would we want the subtitle size to also be able to size down/up as well?

**Comment by taysea** [comment]
Closing this ticket since https://github.com/grommet/grommet/issues/6273 has been created to track next steps.
