### ISSUE TITLE
Brand Refresh - determine visual impacts of button changes to Grommet components consuming button

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2806]
Follows #2794 

- [x] Identify any instances where the new button rounding is not desired by Grommet components (e.g. table cells, etc.)

**Comment by taysea** [comment]
Placing screenshots for all components below that were listed in #2794. Generally, all looks good. Some areas of question I'll place at the top are:
1. Do we want to "restyle" pagination controls to match the new rounding style?
![Image](https://user-images.githubusercontent.com/12522275/183711938-eaf1a4c5-40d2-4c97-bad9-5efe8b1d6866.png)

2. Do we want the FileInput "Browse" button to match the new rounding?![Image](https://user-images.githubusercontent.com/12522275/183711882-327d9885-10a0-49b8-b898-4f00a6727a77.png)

3. Do we want the Video controls to be rounded or square edges?![Image](https://user-images.githubusercontent.com/12522275/183711816-8dd8e5ba-6af9-44ff-9636-2e9074422d7b.png)

The rest look fine:

### Tag
![Image](https://user-images.githubusercontent.com/12522275/183712018-ea095174-82e1-4ff3-ae8f-daa59e26f32d.png)

### Tabs
![Image](https://user-images.githubusercontent.com/12522275/183712017-f3de86dd-b948-47d1-9f47-7dccfcb1d848.png)

### Select
![Image](https://user-images.githubusercontent.com/12522275/183712020-5686fe87-00c3-4024-acac-1ca84c071aef.png)

### Notification
![Image](https://user-images.githubusercontent.com/12522275/183712024-ee961ede-384e-4487-9bda-3e1ee2a11ba3.png)

### Menu
![Image](https://user-images.githubusercontent.com/12522275/183712022-86e62c57-2740-4d88-ab7c-2be0be66ea37.png)

![Image](https://user-images.githubusercontent.com/12522275/183712023-34daf327-4318-4ac1-abe3-c6a6cbac96e9.png)

### List
![Image](https://user-images.githubusercontent.com/12522275/183712021-75183456-5e32-42e1-a5b4-440aacaf239c.png)

### FileInput
![Image](https://user-images.githubusercontent.com/12522275/183712026-86f2a30a-c602-447c-bfda-0b8ce8757554.png)
![Image](https://user-images.githubusercontent.com/12522275/183712028-231cbb66-2899-46dc-a187-fe42eec444e4.png)

### DateInput
![Image](https://user-images.githubusercontent.com/12522275/183712027-d9008edd-6505-4128-856f-b8ffacc715e2.png)

### DataTable
![Image](https://user-images.githubusercontent.com/12522275/183712030-779b398a-8b30-4c2f-ad9f-1fda38970c5b.png)

### DataChart legend
![Image](https://user-images.githubusercontent.com/12522275/183712031-9090d1d5-4532-4a80-b823-45e049ebce51.png)

### Calendar
![Image](https://user-images.githubusercontent.com/12522275/183712029-31563e38-f552-4fdf-ba91-172f264d5e6c.png)
![Image](https://user-images.githubusercontent.com/12522275/183712032-0f707941-d548-4ac5-88b3-93e86c722ea3.png)

### Accordion

![Image](https://user-images.githubusercontent.com/12522275/183712034-1dc78483-1472-4316-99ac-c683439d62af.png)

**Comment by halocline** [comment]
@taysea this is looking great. Can you schedule a meeting to review/discuss?

**Comment by halocline** [comment]
@bahriaditi FYI...

**Comment by SOjaHPE** [comment]
<img width="740" alt="Screen Shot 2022-08-10 at 11 48 05 AM" src="https://user-images.githubusercontent.com/83719939/183981422-b1c96c39-5fc4-49e9-9ac3-d309fd7c5ba4.png">

https://uxplanet.org/the-rounded-user-experience-ff7a1898ab33

- Something we'll need to consider and take into account.

**Comment by ericsoderberghp** [comment]
I'm questioning whether the extra horizontal padding for icon-only buttons is the right approach, especially the one in the FileInput seems a little awkward to me.

I could see the Pagination controls, the close in Notification and Tag, the Calendar dates and month selection, etc. all being rounded like the one shown in the Tag close above.

**Comment by taysea** [comment]
Agreed that we should do more explorations about what we would propose for the padding / rounding on various components. Some exploration of varying amounts of rounding/which components it affects has been started here: https://www.figma.com/file/qCyazxbxne5pTIO4PA9Q7p/Button-Rounding-%2F-Theme-v4-Flavors?node-id=0%3A1

However, some should be done for the specific components you mentioned above.
