### ISSUE TITLE
CheckBox - Figma component updates (needed for #2790 & 2768)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2807]
We need to update the [existing Figma component](https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/HPE-Checkbox-Component?node-id=1315%3A1) in order to create the Multi-select #2790 and 'Column config' #2768 components in our Figma library. We are following the new component guidelines from the Figma refactoring project for this work.

- [x] Create component variants in alignment with Theme
- [x] Review with Aditi & Kenny
- [x] Review with at least one dev (most likely Jessica)

_Note: We plan to publish and distribute this component update with the Multi-Select and the Column Config components. So we will hold on deprecating older versions of the checkbox component until then._

**Comment by bahriaditi** [comment]
@KennyAtHPE can you please review this work by eod today and see if everything looks good from your perspective?

[Figma link](https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/HPE-Checkbox-Component?node-id=4027%3A1238)

**Comment by KennyAtHPE** [comment]
@Keeth-HPe @bahriaditi left a couple of comments.

**Comment by bahriaditi** [comment]
This is done ✔ but not yet announced or distributed, because we want to do that in sync with the column config and multi-select components. Closing this ticket.
