### ISSUE TITLE
Checkboxes have a built-in padding that breaks visual hierarchy

### ISSUE THREAD

**Issue by ecircenis** [grommet/hpe-design-system#2810]
When checkboxes are placed below other form items, the checkboxes are visibly indented and tend to look like they are dependent on the non-indented items.  Can the padding be removed so that checkboxes can be left aligned with other form items?

![image](https://user-images.githubusercontent.com/17883783/183945291-a7d68225-a9f0-47f3-a673-1f92a23bd886.png)

**Comment by britt6612** [comment]
@ecircenis I wanted to see why you wouldn't use the `checkbox` inside of a FormField? Just want your thoughts behind that. Thinking we can have the logic that if a `checkbox` is used outside of a Formfield then just remove the horizontal `pad`

**Comment by ecircenis** [comment]
In product design, there are many cases where only a single checkbox is needed to turn a feature on or off.  At times, this single checkbox may control progressive disclosure.  These use cases do not work well when the checkbox is in a formfield.  See the image for examples.  In most cases, any formfield label you come up with will introduce unnecessary redundancy.  And an unlabeled formfield is just odd.  Unlike textinputs, textareas, selects, etc, a checkbox already has its own label and does not need to be surrounded by a formfield.
![image](https://user-images.githubusercontent.com/17883783/184030899-8b4f2b74-368a-42dc-87f7-51e6c0c0f7bf.png)

**Comment by britt6612** [comment]
Thank you for clearifying this helps me in understanding 👍  @ecircenis
