### ISSUE TITLE
CheckBox - Add variant with no border

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2811]
grommet + hpe theme now has cleaned up hover interaction for use inside FormField or DataTable cells where padding and background color are used as well as outside of those contexts where border color and width are used. This issue is for the associated Figma components and Design System site guidance.

## Deliverables

- [ ] Figma components for use in FormField, DataTable, and vanilla
- [ ] Design System site guidance on when and when not to use CheckBox outside of FormField and DataTable

Currently on the design system site, we don't have any examples of how a checkbox without a border could be utilized. In Figma we have an example in the [Checkbox Group file,](https://www.figma.com/file/zkQOQRUt8frxiSo67kTkfE/HPE-Checkbox-Group-Component?node-id=64%3A240) that states " for use outside of forms". However we need to further the guidance on when to utilize such component, provide example(s) and possibly do a bit of further research...?
<img width="827" alt="Screen Shot 2022-08-10 at 8 40 09 AM" src="https://user-images.githubusercontent.com/62117454/183949718-19f5d79a-ac2c-46f4-99d2-6d1db9df6e0e.png">

**Comment by britt6612** [comment]
closed via https://github.com/grommet/hpe-design-system/pull/2987
