### ISSUE TITLE
PageHeader - Add Avatar component to PageHeader

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2812]
Once Avatar Sandbox contribution is completed, we'll need to update the PageHeader in Figma to include an Avatar. In efforts of eliminating components within PAL, this has been a joint agreement to add to the design system.

Here are PAL's PageHeader component for reference: https://www.figma.com/file/6hYD74saV26sSgoLd3Fu9q/PAL-(Platform-Asset-Library)?node-id=3263%3A73554

**Comment by KennyAtHPE** [comment]
Dropping in some links...

Our current [PageHeader component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2079%3A44189)

[The WIP avatar component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3027%3A58201). It's currently named as "Sandbox-Test"

**Comment by KennyAtHPE** [comment]
Should we hold off on publishing this update until Avatar is officially released @vavalos5? Here's a [ticket ](https://github.com/grommet/hpe-design-system/issues/2889)I created that mentions what components should be released in the next batch, wondering if this should be included in that as well.

**Comment by Keeth-HPe** [comment]
Thank you @vavalos5
I've added the avatar to the page header component. It's added as a toggle (Boolean property) @KennyAtHPE & @vavalos5 
Please take a look when you get the chance to. 

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2122%3A50932

**Comment by vavalos5** [comment]
@KennyAtHPE I think that makes sense. We will have it completed and ready until ready to release.

@Keeth-HPe Thank you for creating. I've taken a look and have left a comment. Looking good!

**Comment by vavalos5** [comment]
I've reviewed and good to close. Thank you @Keeth-HPe :)
