### ISSUE TITLE
Design System Site - PageHeader buttons not responding correctly

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2813]
The buttons on the PageHeader component look like they're not responding correctly. :D Please correct responsiveness. Thank you
![Screen Shot 2022-08-11 at 11 37 52 AM](https://user-images.githubusercontent.com/62117454/184214889-01d6684f-fa13-44d8-b4e0-615167fddf75.png)

**Comment by halocline** [comment]
@vavalos5 I'm assuming you are referring to the button labels wrapping in the anatomy example, but having to guess. Can you confirm? Providing specifics would be helpful.

**Comment by vavalos5** [comment]
Yes, exactly! I meant to come back to this ticket and explain what it should look like. Thanks for pointing out. Will come around to put more context.

**Comment by vavalos5** [comment]
- Buttons should not wrap on large resolutions. Notice the screen shot above states that the screen size is 1216 x1193 and buttons are wrapping. At medium page layout size, all buttons but the primary button should overflow into the ellipsis.
- Breakpoints can be found below:
<img width="880" alt="Screen Shot 2022-08-15 at 1 42 58 PM" src="https://user-images.githubusercontent.com/62117454/184715086-663fec6e-0a31-44af-a8e0-6250e0a68ff9.png">

-Responsiveness examples can be found[ in Figma here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2122%3A51047).
