### ISSUE TITLE
Explore hover treatment of CTA buttons

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2815]
Should the new CTA buttons have a more elegant hover treatment than just darkening the background color? Likely something to ideate on / consult w Chris

<img width="368" alt="Screen Shot 2022-08-11 at 1 08 48 PM" src="https://user-images.githubusercontent.com/12522275/184232548-96a8a70e-1068-4150-b15d-7ee4b3f9a57f.png">
.

**Comment by MeganBeierle** [comment]
@bahriaditi Would you like me to take this task? I have time this week and I'm meeting with Chris tomorrow so I can run it by him.

**Comment by bahriaditi** [comment]
Sure @MeganBeierle that would be great! Please connect with Matt & Taylor before you start on this. They may have more context for you :)

**Comment by MeganBeierle** [comment]
https://www.figma.com/file/NbUF6lBKdXzSxZUF7Kild5/Element-CTA-Buttons?node-id=0%3A1

Scheduling time with @taysea and @halocline to review what I have been exploring and to tell them about my meeting with Chris.

**Comment by MeganBeierle** [comment]
This project will continue on but I feel that the exploration has proven that a non-generic hover treatment will be ideal for this particular button.
