### ISSUE TITLE
Select - Figma component update (Requirement for #2790)

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2816]
As part of creating the new Multi-Select component in Figma, we need to update the [Select component ](https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=103%3A140)first.

**Comment by bahriaditi** [comment]
@Keeth-HPe @KennyAtHPE could you do one final check on this before I close the ticket?
The plan is to publish this under a name different than "Select" so we can buy time to create a deprecation plan for the original Select component.

**Comment by bahriaditi** [comment]
[Figma link](https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=3075%3A3413)

**Comment by KennyAtHPE** [comment]
Looks good to me. This ticket also extends out to #2412.
