### ISSUE TITLE
Form - full-page vs Layers Ideation & guidance Implementation

### ISSUE THREAD

**Issue by bezAdane** [grommet/hpe-design-system#2817]
This ticket is a continuous from [#2750](https://github.com/grommet/hpe-design-system/issues/2750) and ready for implementation . Other reference on this tickets,  such as use cases brought up to us and problem statement can be seen on ticket  [#2666](https://github.com/grommet/hpe-design-system/issues/2666)

## Deliverables
- [ ] implement guidance and examples from [#2750](https://github.com/grommet/hpe-design-system/issues/2750) on the design system site

**Comment by halocline** [comment]
A couple updates here:
1) We've been able to assemble good detail on guidance for how full-page forms should be presented
2) I believe we lost sight of the [original issue](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8?node-id=7302:16163#268009082) which was to provide guidance for and answer "when should I present a form in a layer vs. in a full-page?"

I have started a [decision-tree](https://www.figma.com/file/MschNQ9oZEcX7V7PbHvT4p/Form-presentation-decision-tree?node-id=0%3A1) to help us answer this question. Hopefully it provides a logic path for us to reason through and arrive at recommendations. Comments/reactions/debate welcome.
