### ISSUE TITLE
Header Footer Service - Plan for creating component and process for future updates

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2827]
- How might we create a HFS component that is easily adaptable to future iterations from Gina and team? 
- What would the process of absorbing new updates look like so that designers are always using the latest version?
- Where does Gina's Figma file live? Should we add a link to this in our documentation?

**Comment by bahriaditi** [comment]
Kenny, Scott and I met on this briefly today and below is a summary of our discussion:

- Consider creating a single Global Header component with variants for the different versions needed (based on each release)
- Create a draft of this component (desktop only for now) to share with Gina. This will give us a chance to review the component structure with her before we get too far ahead.
- As part of the MVP, we will not be including any dropdown menus
- Consider prioritizing the Avatar component (currently in the Sandbox) as it is one of the building blocks for the Header

**Comment by KennyAtHPE** [comment]
Reopening this ticket once those top items have been completed.

**Comment by KennyAtHPE** [comment]
@bahriaditi @SOjaHPE please review the test [component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3028%3A59651). It includes a bunch of toggable icons, an example of how the versioning property could work, and examples of sizing as well. 

Side note, it's using the WIP avatar sandbox component as well if you're curious how that turned out.

**Comment by bahriaditi** [comment]
Hi @KennyAtHPE this looks great! Thanks for the quick turnaround.
I was wondering if we should put in the latest logo for GreenLake in this test. You can grab this vector from Matt's Brand Refresh Synthesis file: https://www.figma.com/file/9B2TP2j8gVaCCBfZoq05ee/HPE-Design-System-Brand-Refresh-Synthesis?node-id=11%3A148

**Comment by KennyAtHPE** [comment]
@bahriaditi good point, it's been changed. Left the old version with the previous banner as an example. Will close ticket once @SOjaHPE gets a chance to review.

**Comment by halocline** [comment]
https://d3hq6blov2iije.cloudfront.net/images/hpe-greenlake/hpe_greenlake_blk_pos_rgb.svg
https://d3hq6blov2iije.cloudfront.net/images/hpe-greenlake/hpe_greenlake_grn_pos_rgb.svg
https://d3hq6blov2iije.cloudfront.net/images/hpe-greenlake/hpe_greenlake_grn_rev_rgb.svg
https://d3hq6blov2iije.cloudfront.net/images/hpe-greenlake/hpe_greenlake_wht_rev_rgb.svg

@KennyAtHPE FYI.

**Comment by KennyAtHPE** [comment]
Thanks @halocline!

Component prototype can be found [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3028%3A58745). Final version will need flexible navigational tabs (users can have more/less if needed). Will be meeting with Gina next week and will create a new ticket based on the outcomes of the meeting. 

Closing this ticket.
