### ISSUE TITLE
GLCP Contribution - Pagination flexibility to determine x amount of items per list/DataTable

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2832]
GLCP has had a need to provide the user with flexibility to determine how many items they'd like to view at once. 

While I do think this a great contribution, we should also gather other use cases to decipher need, understand how this affects accessibility, how it'll work with filtering and validate best practices. I'm attaching screen shot below as well as [Figma file of where it lives within PAL](https://www.figma.com/file/6hYD74saV26sSgoLd3Fu9q/PAL-(Platform-Asset-Library)?node-id=5698%3A117970).

![Screen Shot 2022-08-16 at 11 58 31 AM](https://user-images.githubusercontent.com/62117454/184959925-0c946cc0-c80f-4aef-8308-de395ebd37c2.png)

**Comment by halocline** [comment]
closed by https://github.com/grommet/grommet/pull/7133
