### ISSUE TITLE
Avatar - Write guidance on the Figma file and the Design System site

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2838]
Building on #2836 

[WIP guidance
](https://www.figma.com/file/d7a74LgBABdgTZR6HrzWKo/HPE-Avatar?node-id=1521%3A1773)
### Objectives
Currently, the component has been created and can be found [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3027%3A59677). It is only being used by Vicky and Sylvia to help create sandbox contributions and has yet been released publicly. Before doing so, the following must be completed:

- [x] Fill out [component template](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3027%3A61406) within Figma file. Be sure to fill out the "how to use" section with instructions on the three different variants!
- [x] Add additional guidance to the Design System as needed. The use cases can be found [here](https://www.figma.com/file/Tw2PiwyLS21l20VTXKbQfS/Avatar?node-id=402%3A112).
- [x] Deprecate old [Avatar file](https://www.figma.com/file/d7a74LgBABdgTZR6HrzWKo/HPE-Avatar?node-id=0%3A1) (change thumbnail, move items to leftovers, etc.)
- Announcement for this component will be a part of #2889

**Comment by KennyAtHPE** [comment]
Met with Brittany on this and a couple of questions came out of our convo:
- Should the "Square frame" variant be removed in accordance to the Brand updates?
- Guidance on when to use "Circle frame" vs "Rounded Square frame" should be included

**Comment by vavalos5** [comment]
@KennyAtHPE saw this was in review. Did you need someone to review your work?

**Comment by KennyAtHPE** [comment]
@vavalos5 this was being reviewed by Brittany but currently working on writing the guidance. Forgot to move it back.

**Comment by KennyAtHPE** [comment]
Brittany is currently reviewing the Guidance, requesting additional reviews from @ericsoderberghp if you are available.

**Comment by vavalos5** [comment]
This comment isn't particularly on guidance, but more of so the use of other companies logos. Might be good to have a conversation with Chris on this and see what he says.

**Comment by KennyAtHPE** [comment]
Guidance has been completed, next steps are tracked in #2933
