### ISSUE TITLE
Voice and tone strategy: DS devs/designer users

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2843]
So we are all on the same page, what is the voice and tone that we aim towards for our two audiences?

1. The Design Team's audience (HPE devs/designers) as they are reading our guidance pages

2. The HPE devs/designers who are designing UI's for their users ("customer admins")

This is related to:
#1890

This ticket addresses number 1 and number 2 is addressed in ticket #2844
  
According to our current voice and tone guidelines, HPE aims to convey the following values: 
- Open: We foster inclusive experiences that are personal, accessible, and transparent.
- Courageous: We empower users with decisive and experienced guidance.
- Inspired: We share our drive of 'yes we can' with users.

While originally this was meant with the customer admin end user in mind, I think it's a great tone of voice for our Design System users, as well!

HWM give guidance and tools for our team to transmit three these values to Design System users?

**Comment by taysea** [comment]
Closing, stale.
