### ISSUE TITLE
Voice and tone strategy "customer admin" user

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2844]
To address number 2
We have guidelines from Brand on how HPE should deliver messages to the end customer. Although the theories are useful as a base, they are talking about marketing, presentations and communications with customers. They don't address user interfaces. 

Here are some of the useful guidance I picked out from the HPE brand v&t guide for our user interfaces:

- "The main evolution that distinguishes the HPE voice is gravitas: we project an authority more appropriate for business customers. Jargon almost always gets in the way of openness and clarity. It is only acceptable to use jargon in technical communications, when there is no other way to ensure universal understanding."

- With regard to being "courageous" 
"Always speak in the affirmative. Everything we say should sound positive and supportive."

- With re: to being "inspirational"
"...our purpose is to 'advance the way people live and work.'”

HWM give more concrete guidance for our designers and for us, "reviewers" who are helping maintain some consistency in the courageous, open, inspirational tone we want to set.

This is related to #2843

**Comment by taysea** [comment]
Closing, stale.
