### ISSUE TITLE
Tabs- Modify Figma files to accommodate new active state design

### ISSUE THREAD

**Issue by MeganBeierle** [grommet/hpe-design-system#2846]
Based on user research we have decided to modify the active state tab to increase user recognition time. The new active state design can be found here: https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=4317%3A40074

- [x] Update design system Figma files to reflect this change

The hover state will remain the same.

**Comment by bezAdane** [comment]
Based of research finding i updated DS [Figma file of Tabs active state](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=3631%3A40501). Increased pix size to 6 and changed color (darker) the new updated and published component is available now. Closing this ticket.
