### ISSUE TITLE
Global Header - Update component based on Gina's feedback

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2849]
Based on original ticket #2786 

The [Global Header](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3028%3A58403) needs to be updated based on the following feedback from Gina:
- [x] Variant that allows a different number of navigational tabs. A variant to toggle them all on and off as well.
- [x] Possibly omitting search and home icons
- Should there be variants for each platform?
- [x] Review HPE badge spacing (currently waiting on the outcome of Brand Refresh Synthesis)
- [x] Include variant for white labeling
- [x] Include variants for mobile view

--------------
Once tasks above are completed:
- [x] Review with Gina

**Comment by vavalos5** [comment]
@KennyAtHPE Is this in review with Gina?

**Comment by KennyAtHPE** [comment]
@vavalos5 yes, will be meeting with her at the end of the week on this component

**Comment by KennyAtHPE** [comment]
Closing tickets, next steps will be tracked in #2900
