### ISSUE TITLE
Tabs - Enhancement to provide additional support of summary information to convey to the user a count or summary of objects

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2851]
A use case arose on the Platform team where it's important for a user to know how many items live within a tab to get an overview on x amount of inventory. Please see screen shots of how Platform is currently styling (they're using cards). But after chatting with Scott, we both agree they should be in tabs. 
**Use Case 1**
https://www.figma.com/file/F7KAxVKcigWR4tjd7vcsr4/GLCP-Experience-(Dublin)?node-id=1504%3A58087 
![Screen Shot 2022-08-24 at 10 16 20 AM](https://user-images.githubusercontent.com/62117454/186482334-bb22be4a-1692-4dde-9ab1-9fbaaefca9dd.png)
![Screen Shot 2022-08-24 at 10 16 05 AM](https://user-images.githubusercontent.com/62117454/186482341-8f864d06-5215-4034-ad49-b2ea21bbff9b.png)

**Use Case 2:**
"Consider these number are the most important information when the user come to this page. It is not just used as a filter but a summary - Sylvia"

![Screen Shot 2022-08-24 at 10 20 02 AM](https://user-images.githubusercontent.com/62117454/186482798-ee25b19d-131c-4950-9c8c-9a657cd5c799.png)

How Storage is styling tabs currently:
<img width="776" alt="Screen Shot 2022-08-23 at 3 32 25 PM" src="https://user-images.githubusercontent.com/62117454/186482448-dbb65adf-2eff-40b3-83a7-dae84b943dec.png">
<img width="1663" alt="Screen Shot 2022-08-23 at 3 32 15 PM" src="https://user-images.githubusercontent.com/62117454/186482457-da3b3d02-edca-4497-a55f-39396926d93e.png">

Ticket is to explore which direction is best and validate direction.

**Comment by halocline** [comment]
I'm interpreting the Platform and Storage use cases differently:
- With Storage, the "tabs" are switching views between distinct data collections. This seems appropriate as I am switching the collection I am looking at. 
- With Platform, the buttons/cards are serving as a filtering mechanism applied to a single data collection. They are acting upon the data collection, not a means of navigating to another distinct collection. I do think the "toggle" metaphor is appropriate here, as I am toggling the application of different filters.

Thoughts/questions:
- I think it is worth exploring a "toggle button," in both basic and rich executions.
- Is toggle the right metaphor for switching between distinct collections/subjects? Not sure. It could be, but worth thinking through from a standardization aspect (tabs for switching between different subjects? toggle for applying action to the current subject?)

**Comment by taysea** [comment]
Closing, we are recommended "Selector" for this pattern at the moment: https://design-system.hpe.design/templates/selector
