### ISSUE TITLE
Wizard – Clarify "Next" button placement guidance

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2855]
Based on feedback in Slack from Dilip: https://grommet.slack.com/archives/C04LMJWQT/p1661450899392709

Deliverables:
- [ ] Update guidance
- [ ] Follow up with Dilip in original Slack thread

**Comment by vavalos5** [comment]
I noticed that we included the next icon on the button. Should we be more specific that the previous and next icons should be utilized for these buttons?
