### ISSUE TITLE
Contextual help on Forms - add clear visual

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2857]
Contextual help, even in its most simplest form, is sometimes inconsistent. Written clarification would be useful on:

1. When to use/not use placeholder text.
2. When to use/not use help text below the field label.
3. When to use/not use required information.
4. When to use/not use the info icon and tooltip pop-up.

A visual example could easily clarify where each type of help should be placed. If you can imagine this

Field label
[help text]
 ---------------
|  [placeholder  | 
 ________________
[requirements]

**Comment by ericsoderberghp** [comment]
Check with @SOjaHPE about connecting with Gina or Diane on this one.

**Comment by ericsoderberghp** [comment]
This is a duplicate of #2051
