### ISSUE TITLE
Form- Managing objects(add/edit/remove) with in a form- Ideation

### ISSUE THREAD

**Issue by bezAdane** [grommet/hpe-design-system#2859]
Continue from  [#2570 ](https://github.com/grommet/hpe-design-system/issues/2570)

ToDo's

- [x] Explore a few alternative designs  option 
- [x]  Ideation review with designers & Dev.
- [x] Connect with dev. (Matt & Brittany)

**Comment by vavalos5** [comment]
Beza to finish cleaning up mock ups to align to whiteboard session as a final step for this ticket. 

Next week's follow up ticket is: #2889
