### ISSUE TITLE
Align Figma `border` sizes to match t-shirt sizes.

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2860]
Figma file
https://www.figma.com/file/cgTYs856lxE8LZpBpAdf1v/HPE-Box-Component?node-id=368%3A287

in hpe theme the `border` sizes are:
"xsmall": "1px",
"small": "2px",
"medium": "4px",
"large": "12px",
"xlarge": "24px"

**Comment by vavalos5** [comment]
@Keeth-HPe Can you work on this in the mean time please.

**Comment by Keeth-HPe** [comment]
The border size was incorrect only for the Large size in Figma 
Changed the "large": "8px", to "12px" as mentioned. The rest oof it seems fine.

<img width="757" alt="Screenshot 2022-09-22 at 10 59 47 PM" src="https://user-images.githubusercontent.com/86280029/191813179-7781073d-7e3f-47db-be1f-96c24b2c2324.png">

**Comment by vavalos5** [comment]
Thank you Keeth. It looks like we didn't update the border sizes on the left. I went ahead and made that small change. This is good to close, thank you :) 

![Image](https://user-images.githubusercontent.com/62117454/191854186-ac0c3cc4-f274-4713-8897-edd3b5df6e6b.png)
