### ISSUE TITLE
checkBox hover outside of FormField

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2862]
Discuss the hover treatment for `checkBox` outside of a FormField.

**Comment by vavalos5** [comment]
Currently there are 3 different CheckBox treatments:
- a checkbox within a DataTable where the cell receives background color but on focus the checkbox receives focus
- checkbox FormField input receives contrast color on list item
- within Grommet, the checkbox container has an outline and goes from purple to black upon hover

Do we only want to solve for FormField? As @KennyAtHPE and @Keeth-HPe have been working on refactoring components at the atomic level, I feel this should be more carefully considered to provide more of a consistent experience.

**Comment by britt6612** [comment]
Will need to update in figma but the plan is to have:

**CheckBox Not in form field**

- No padding
- Hover treatment border goes from default —> border-strong

**CheckBox In FormField**

- Padding
- Hover treatment: background-contrast
- Hover treatment border goes from default —> border-strong

**CheckBox In DataTable**

- Padding
- Hover treatment: background-contrast
- Hover treatment border goes from default —> border-strong

**Comment by britt6612** [comment]
Update Figma for CheckBox 
https://github.com/grommet/hpe-design-system/issues/2923
