### ISSUE TITLE
RadioButton - Recreate Figma component

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2863]
Recreate the RadioButton component in Figma to align with our new component design guidelines. This is being prioritized as part of Vicky's work on[ Selectable Cards](https://www.figma.com/file/UAlilhaQXOwHh01Qj7B0V9/Selectable-Cards?node-id=2%3A878).

Please reference the [newly redone CheckBox component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2971%3A63108) for this work.

- [x] Create new components in RadioButton Group Figma file on the WIP page - do not publish yet (name these "WIP")
- [x] Align with a developer to verify all states (hover, focus, disabled etc)
- [x] Review with at least two designers (Vicky + Kenny)

**Other Resources:**

- [RadioButton Group Figma file](https://www.figma.com/file/aZyY606ENQedz4FXugdzgS/HPE-Radio-Button-Group-Component?node-id=78%3A0)
- [RadioButton Group on DS Site](https://design-system.hpe.design/components/radiobuttongroup?q=radio%20button)
- [Grommet StoryBook](https://storybook.grommet.io/?path=/story/input-radiobutton-simple--simple)

**Comment by Keeth-HPe** [comment]
Created the radio button component and also have asked Jessica to verify it.
Meanwhile, if you'll get a chance, please review the component and share feedback :slightly_smiling_face:
[Radio Button component](https://www.figma.com/file/aZyY606ENQedz4FXugdzgS/HPE-Radio-Button-Group-Component?node-id=2364%3A4526)

**Comment by vavalos5** [comment]
@Keeth-HPe This is looking great! I left a few comments in the Figma file. @KennyAtHPE when you get a chance next week, can you revise too please. Thanks!

**Comment by Keeth-HPe** [comment]
@vavalos5 I've addressed your comments. Thank you so much reviewing. :)

**Comment by KennyAtHPE** [comment]
@Keeth-HPe will review today.

**Comment by KennyAtHPE** [comment]
@Keeth-HPe Awesome job on this! Left some minor comments.

**Comment by KennyAtHPE** [comment]
Next steps can be found [here](https://github.com/grommet/hpe-design-system/issues/2892)

**Comment by vavalos5** [comment]
@Keeth-HPe is RadioButton ready to review again or in In Progress? Want to make sure this is in the right column in backlog.

**Comment by Keeth-HPe** [comment]
Hey @vavalos5 
We can actually close this ticket. 
Kenny has created the 'next steps' in a different ticket, which are the addition of a group variant & interactive prototype. 

So we shall close this ticket
