### ISSUE TITLE
Grommet September Release

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2867]
Releasing a bit earlier than usual to give partners a published version of SelectMultiple to release with.

**Comment by halocline** [comment]
- [ ] https://github.com/grommet/grommet/pull/6336 -- review
- [ ] add test for Select to make sure `null` is accepted value [Matt]
- [ ] SelectMultiple change icon for open state [Jessica]
- [ ] [#6332](https://github.com/grommet/grommet/issues/6332) - value = undefined [Eric + Jessica]
- [ ] SelectMultiple - handle null values? [Eric + Jessica]
- [ ] overflowWrap on Heading documentation [Matt]
- [ ] add global.backgrounds to theme doc [Matt]
- [ ] Write release notes + contributor names [Matt]
- [ ] Storybook smoke test across browsers [Matt --> Safari] [Jessica --> FireFox] [Chrome-HPE --> Matt] [Chrome-Grommet --> Jessica]
   - [ ] Touched components
   - [ ] Console error free
   - [ ] Wave tests? Accessibility plugin.
- [ ] Grommet site
  - [ ] Any component touched in release

**Comment by jcfilben** [comment]
v2.26.0 of Grommet has been published
