### ISSUE TITLE
Upgrade build image for sites using 'Xenial' image

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#2876]
A number of grommet owned sites need to be upgraded to use a newer build image. Some sites are using the xenial image which is no longer being supported. All support for the xenial image will end on November 15th, 2022.

**Comment by ericsoderberghp** [comment]
I've updated the grommet and HPE Design System sites. There are a few older sites or sites owned by other teams that we don't need to take care of.
