### ISSUE TITLE
Toolbar (Contribution) - Review with stakeholders

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2877]
Based on discussion with Eric, Ian, Geetha and team, we are ready to share a url to the draft documentation with stakeholders outside the Ezmeral team.

**Draft documentation:** https://www.figma.com/file/goiSj6Ox3AlJb6HgPLgjsJ/Toolbar?node-id=500%3A5750

The goal is to get their help in evolving the best practices as well as any “do’s” and “don’ts” that would be good to include.

**Comment by taysea** [comment]
Closing, stale.
