### ISSUE TITLE
Toolbar (Contribution) - Dev implementation

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2878]
[Figma link](https://www.figma.com/file/goiSj6Ox3AlJb6HgPLgjsJ/Toolbar?node-id=500%3A5750)

Based on the design provided by Geetha above, we need to consider how best to implement this pattern on Grommet and the Design System site.

This is a placeholder ticket–please feel free to break this down as needed. 

For any clarifying questions, contact @geetha-priya.padmanaban from the Ezmeral team.

**Comment by taysea** [comment]
Closing, has been added with Data+friends components in Grommet and Design System site.
