### ISSUE TITLE
Toolbar (Contribution) - Figma component

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2879]
Once #2877 is complete and #2878 is underway, begin building out the Figma component for the Toolbar pattern based on our new design guidelines.

[Figma link for Toolbar](https://www.figma.com/file/goiSj6Ox3AlJb6HgPLgjsJ/Toolbar?node-id=500%3A5750)

Note: This is a placeholder ticket and may be broken down into smaller issues once a designer begins work on this.

**Comment by taysea** [comment]
Closing, have added Toolbar in Figma
