### ISSUE TITLE
Card - draft 2-3 common kinds

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2885]
Draft 2-3 common types of cards, building on the existing work.

Previous work: https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=1548%3A372

Proposal for potential kinds to explore (navigational, call-to-action, % of whole): https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=2581%3A8414

## Deliverables

- [x] decide on the 2-3 common types
      - Call-to-Action and Navigational
- [x] Figma examples in draft form, does not need to be a publishable component
      - [x] Complete 2-5 variants/flavors of Call-to-action card
      - [ ] Complete 2-5 variants/flavors of Navigational card
- [x] pull request for the design system site containing examples, does not need to be reviewed yet
- [x] pull request for the design system site containing guidance, does not need to be reviewed yet

**Comment by vavalos5** [comment]
Defining criteria of questions we should answers:

- How card should behave
- keyboard/mouse
- announcement
- Should things be treated as sections
- Styling

**Comment by halocline** [comment]
Updates:
- Pull request containing card type definitions and guidance has been submitted (on [CARD-TYPES feature branch](https://github.com/grommet/hpe-design-system/tree/CARD-TYPES))
- Example card designs are still in progress
- Blocked - Pull request with example cards

**Comment by vavalos5** [comment]
@taysea Are we ok with closing this ticket. I think we've covered the above requirements and in the midst of the next steps such as testing with Bill.

**Comment by taysea** [comment]
Before we close it,let's file tickets with the remaining work and link to it here.

**Comment by taysea** [comment]
Drafts of 2 common kinds have been created (in Figma and PR). The follow-on work can be found in these tickets:
- #2911 
- #2912 
- #2913
