### ISSUE TITLE
SelectMultiple - Creating or editing list items

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#2887]
Create a design for allowing users to edit the list of options or create new options in SelectMultiple

Related comments: https://github.com/grommet/hpe-design-system/issues/3409#issuecomment-1599241978

**Comment by vavalos5** [comment]
@jcfilben Are there any examples that can be inserted in this ticket so the next person working on this has a reference and better understanding?

**Comment by jcfilben** [comment]
> @jcfilben Are there any examples that can be inserted in this ticket so the next person working on this has a reference and better understanding?

I looked through Aditi's research for SelectMultiple, but unfortunately wasn't able to find anything she collected for editing/creating new options. We decided early on in the process that editing and adding new options would be a 'v2' of SelectMultiple so I am guessing she didn't collect anything on this for that reason.

We do have a storybook example of what adding an item could like like in the Select component
https://storybook.grommet.io/?path=/story/input-select-create-option--create-option&globals=theme:hpe


<img width="367" alt="Screen Shot 2022-09-12 at 5 03 58 PM" src="https://user-images.githubusercontent.com/54560994/189773279-1893b6c8-e7ba-431f-b1a6-55ed1f4b5a4d.png">

**Comment by jcfilben** [comment]
Requested in office hours by Sam Goff 2/2/23

Also found this related comment on ticket #2367 

> Adding a possible use case that came up in this morning's office hours: **Multi-select list that supports the creation of new objects**
> 
> @ericsoderberghp is it safe to say that this is related to the multi-select component?
> 
> In the flow below, the user has the option to select or add additional SSH Key/ Volumes to the list of options. In this current design, the two actions of selecting and adding feel disconnected. I wonder if this may be resolved by providing a variant of the multi-select component which supports the ability to create new items.
> 
> Of course we need to validate this need by collecting similar use cases across other apps.
> 
> <img alt="Screen Shot 2022-04-13 at 11 01 50 PM" width="1147" src="https://user-images.githubusercontent.com/87677275/163323592-d6f14008-0465-4d07-858a-0a156779b017.png">
> 
> <img alt="Screen Shot 2022-04-13 at 11 02 07 PM" width="1245" src="https://user-images.githubusercontent.com/87677275/163323598-78870eb6-d371-45fc-8456-87612ddd88f2.png">

**Comment by halocline** [comment]
Similar situation for labels in Github: 
![Screenshot 2023-06-20 at 11 49 13 AM](https://github.com/grommet/hpe-design-system/assets/1756948/1aab3424-f02b-4dd8-a14e-412f1ac97381)

**Comment by ashifalinadaf** [comment]
As per my understanding I am guessing we need to add an option to edit/ delete the option in 'multi select component'.

**Questions:**
- Edit and delete option should be applicable to current options or for the new options.
- Do we have to have minimum and maximum number of options? - set the guidance?.
- We need to have a different variant or different component?  
- Will it affect the current component? 


**Deliverables:** 
- Collect the use cases/ explore the current ones. 
- Review use cases and come up with optimal solution.
- New variant to the 'select multiple component' that has an option to edit/delete the options. 
- Explore the outcomes and decide on the different prototype. 
- Test with designers and developers for feedback. 
- Implement the design.

**Comment by ashifalinadaf** [comment]
Collected some use cases from GLCS team, however no specific use cases have been found. 
Exploring on the current components like text input and tags and also other examples found on internet - could find some features that can be implemented. 

Initial explorations: [Figma](https://www.figma.com/file/txvA1RE8lShGvLc11jdNyB/Select-Multiple-component---Add%2Fedit-options?type=design&node-id=16-18037&mode=design&t=LOPaV1RhcerNLy6t-11)

**Comment by ashifalinadaf** [comment]
After the careful analysis and feedbacks from the users following things can be concluded. 

- There are less specific uses cases for create/edit/delete options for select multiple component. 

**Edit option**
- Most of the use cases from different services pointing towards **complex inputs for options** of select multiple, which requires multiple, specific and lengthier inputs and they already have 'modal options'/ 'edit option on the dashboard'. - **Edit** option **within** the select multiple is not possible for such cases.  
- There are less use cases that requires only option 'edit option' (that doesn't require complex inputs, ex- Name) 
- So its' better to provide the **anchor/button within the select multiple component**  that leads to an option for editing the current option with modal dialog.  
- This **rules out need for the editing the current option within the select multiple component.** 
- Options can be edited within the list of items from the backend/ from the dashboard that allows editing items. 

**Add option**
- Similar to the case of 'edit option' options that require **complex inputs** already have 'modal options'/ 'edit option on the dashboard'. 
- We can provide the **anchor/button within the select multiple component** that leads to an option for editing the current option with modal dialog.  
- Add items at the end of the select multiple options can help users to edit the options. 

**Delete option**
- Not necessary at this stage as the primary action is to select the multiple options than performing dangerous actions like delete. 
- A separate request to delete such options can be performed - outside the scope of performing within the select multiple component. 
- Ruling out using any of such dangerous actions.

**Comment by SOjaHPE** [comment]
@ashifalinadaf after reviewing the research and proposed solutions. 

**Solution 2** - seems most appropriate and is in-alignment with a common create supported functionality in many other MultiSelect components. The user has the MultiSelect component open, they scroll and browse through the item set and eventually search the list of values as a last step in an attempt to narrow it down. When the contains match isn't located - a **Create**__ item control below the list of objects is the next step if the user doesn't find what they expected. Having it inline has lower interaction costs then forcing the user from exiting the input feeling empty handed to only now have to create the new object before returning back to the multi-select to try that input one more time.  

'Add items' default button/ text at the end of the select multiple options can help users to edit the options.

Create is the creation of something that doesn't exist in the system. Whereas to Add is associated with adding an existing entity or object.

**Comment by vavalos5** [comment]
Asif, love the research and explorations you've conducted! It was easy to follow along with comparing other components we have that could be a similar approach we could take.

A few things I'd like to see is what do the steps look like when clicking on the "anchor button". The current designs show a bold text and neither a default button style nor anchor. 

What does the modal look like with steps? How do I know which ones I can and cannot edit?

**Comment by SOjaHPE** [comment]
@ashifalinadaf I feel at this time it would be good to keep it simple and just focus on the 'create' use case and not support editing of objects in the MultiSelect list - the user should be able to manage those objects from an appropriate object list page/manage page data collection table where they maintain those child objects. 

**Referencing your previous recommendation write-up comments**

> Options can be edited within the list of items from the backend/ from the dashboard that allows editing items.

This ticket is ready to be closed and follow on tickets created.

**Comment by halocline** [comment]
> @ashifalinadaf I feel at this time it would be good to keep it simple and just focus on the 'create' use case and not support editing of objects in the MultiSelect list - the user should be able to manage those objects from an appropriate object list page/manage page data collection table where they maintain those child objects.
> 
> **Referencing your previous recommendation write-up comments**
> 
> > Options can be edited within the list of items from the backend/ from the dashboard that allows editing items.
> 
> Follow on ticket for figma work - [#3477](https://github.com/grommet/hpe-design-system/issues/3477)

So, confirming the proposal is to allow creation inline (i.e. within the select dropdown)? This seems to add a significant amount of complexity for implementation. An alternative could be having the simply having a slot for an X button. The button could be create, edit, etc. and could open a modal dialog, take to another screen, etc.

**Comment by halocline** [comment]
Closing since https://github.com/grommet/hpe-design-system/issues/3477 has been created
