### ISSUE TITLE
SelectMultiple - Finalize guidance and draft changes to DS site

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2888]
Building on #2716 

### Current Status
~~- [ ] [Figma component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3206%3A58995) has been finalized~~
- [x] Component is available on Grommet and documented on Grommet site
- [x] Fill in [Figma component template](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3279%3A98077)
- [x] Review and update [ the guidance](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/SelectMultiple-Component?node-id=2178%3A23519) Aditi had worked on as needed, from developer perspective [Jessica, Taylor, Vicky, Kenny]
- [x] Create a draft pull request to update the DS site, ready for review, minimal content, time-box to 1 day?
~~- [x] fix caret behavior in Figma and grommet~~

### follow on work
- do's and don'ts in Figma
- more detail for screen reader annotations, is it not clear enough now?
- Publish Figma component
- Announcement of this component will be part of #2889

**Comment by vavalos5** [comment]
@Keeth-HPe has been working on the Figma component template. Thanks for doing this! I was taking a look at the behavior here and noticed that upon selecting the select input field, the caret does not flip like the select component does. However, I also noticed that within Grommet, the caret remains in the upward position. I'm not sure if this was explore by Aditi. But do want to align for consistency. Connect with @jcfilben to discuss this.

@KennyAtHPE to work on guidance next week.

**Comment by jcfilben** [comment]
Update: I reviewed the guidance in Figma. I made some minor edits and added a comment. Otherwise looks good.

**Comment by jcfilben** [comment]
> @Keeth-HPe has been working on the Figma component template. Thanks for doing this! I was taking a look at the behavior here and noticed that upon selecting the select input field, the caret does not flip like the select component does. However, I also noticed that within Grommet, the caret remains in the upward position. I'm not sure if this was explore by Aditi. But do want to align for consistency. Connect with @jcfilben to discuss this.

I believe the behavior Aditi wanted was for the arrow to be pointing up when the drop is open and down when the drop is closed. Currently in grommet this is working only when `showSelectedInline` is true. I will get this fixed on the Grommet side so that it is working both with the default and selected inline versions of SelectMultiple.

**Comment by vavalos5** [comment]
I was able to review the guidance and examples and left some comments on the Figma file. Overall, I think it looks great, just needs a few minor clean ups.

**Comment by jcfilben** [comment]
> I believe the behavior Aditi wanted was for the arrow to be pointing up when the drop is open and down when the drop is closed. Currently in grommet this is working only when showSelectedInline is true. I will get this fixed on the Grommet side so that it is working both with the default and selected inline versions of SelectMultiple.

Correction to my previous comment, in the grommet theme the icon does not flip, but in the hpe theme the icon does flip. This matches the behavior for select as well as Aditi's designs (for the hpe theme). I don't think any action is needed on the Grommet side

**Comment by KennyAtHPE** [comment]
Unchecking "Figma component has been finalized"

@jcfilben and I are doing an audit on the Figma component to make sure it is consistent with the Grommet component. Loose notes and findings are found within these [comments](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3599%3A93714)

**Comment by KennyAtHPE** [comment]
Separating component building into a separate issue, #2921
