### ISSUE TITLE
Figma - Publish and announce new components

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2889]
These components must be published and old versions must be deprecated before announcing them in Slack. Additionally, all associated tickets must be resolved beforehand. The following components will be released in a single batch:

**New Components**
- [x] [SelectMultiple](https://github.com/grommet/hpe-design-system/issues/2888)
- [x] [Ordering of Items](https://github.com/grommet/hpe-design-system/issues/2890)

**Component Enhancements/Component Refactor**
- [x] [PageHeader with Avatar variant
](https://github.com/grommet/hpe-design-system/issues/2812)
- [x] [Avatar](https://github.com/grommet/hpe-design-system/issues/2838)
~~- [ ] [Checkbox](https://github.com/grommet/hpe-design-system/issues/2891)~~
~~- [ ] [RadioButton](https://github.com/grommet/hpe-design-system/issues/2893)~~

-----------
- [x] [Update this chart](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2438%3A45572) once the components have been released.
- [x] Update [TOC](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2%3A2)

**Comment by vavalos5** [comment]
Thank you for creating these tickets Kenny!

**Comment by vavalos5** [comment]
Radio Button and Checkbox have bugs within Figma due to some limitations.

Closed tickets #2892 and #2894 as they both are being put on pause due to Figma bugs. Kenny and I will be reviewing later and creating new tickets for them.

**Comment by KennyAtHPE** [comment]
New tickets:
- Checkbox #2923
- RadioButton #2924

**Comment by KennyAtHPE** [comment]
Will be releasing RadioButton and Checkboxes at a separate time. Currently still working on SelectMultiple and Avatar guidance is being implemented on the DS site.

**Comment by KennyAtHPE** [comment]
Will be swapping out button components in SelectMultiple, Ordering of items, and pageheader once the button component is released. That is being tracked in

**Comment by KennyAtHPE** [comment]
Components have been published and announced. Closing ticket
