### ISSUE TITLE
DataTable - Finalize Ordering of Items component

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2890]
### Current Status
- [Figma component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2915%3A56106) has been finalized

### Next Steps
- [x] Fill in [Figma component template](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2915%3A60783)
- [x] Add interactivity. Users should be able to toggle between tabs.
- [x] Reach out to Sylvia for last reviews (she originally requested this component)
- [ ] Update the Figma link on the [DS site](https://design-system.hpe.design/templates/datatable-customization?q=data)
- [ ] Announcement of this component will be part of #2889

**Comment by vavalos5** [comment]
@Keeth-HPe Assigning you to this ticket as you've been working on it this week. Kenny and I met and thought you'd be able to continue this work next week. Please feel free to ping me should you have any questions. 

Additionally, I left a comment in the Figma file on the component template you've worked on :)

**Comment by vavalos5** [comment]
@Keeth-HPe were you able to complete the rest of the items on this list?

**Comment by vavalos5** [comment]
There is also a comment from Kenny on this Figma files in regards to some of the alignment. Can you please look into it and update ticket here when completed. Thanks.

**Comment by Keeth-HPe** [comment]
Hey @vavalos5 
I fixed Kenny's comment. 

I've requested Sylvia to review the component and share feedback.

**Comment by vavalos5** [comment]
@KennyAtHPE This component has been fixed.

**Comment by KennyAtHPE** [comment]
@Keeth-HPe Awesome job Keeth! @vavalos5 moving this into review. Thinking this ticket can close out once Sylvia's comments (if any) are resolved.

**Comment by Keeth-HPe** [comment]
@vavalos5 
Sylvia tested the component and gave me a 👍 thumbs up.
This ticket is good to close.
