### ISSUE TITLE
Checkbox - Deprecate old component and publish the new one

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2891]
Building on #2894 
[Figma component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2971%3A63108) can be found here

### Next Steps
- [x] Fill in [Figma component template](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2940%3A64707)
- [x] Deprecate old [checkbox component](https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/HPE-Checkbox-Component?node-id=1744%3A1)
- [x] Review with Kenny
- [x] Publish new Figma component
- [x] Announcement of this component will be part of #2889

**Comment by vavalos5** [comment]
@Keeth-HPe Once you complete the DataCustomization ticket, please begin on working on the items listed in this ticket. Reach out if there are any questions :)

**Comment by KennyAtHPE** [comment]
[The component ](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2940%3A62424&t=qYgZJmmPcftV30vO-1)has been finalized and published.
