### ISSUE TITLE
RadioButton - Add a Group variant and include interactive prototyping

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2892]
Building on #2863 
Component can be found [here](https://www.figma.com/file/aZyY606ENQedz4FXugdzgS/HPE-Radio-Button-Group-Component?node-id=2359%3A4304)

### Deliverables
- [x] Include a group variant that allows users to toggle from a single RadioButton to a group of RadioButtons
![image](https://user-images.githubusercontent.com/86075038/189822863-6b304e7d-d44f-4847-825d-389707049dfd.png)

- [x] Add interactive prototyping

**Comment by KennyAtHPE** [comment]
Next steps are [here](https://github.com/grommet/hpe-design-system/issues/2893)

**Comment by vavalos5** [comment]
@Keeth-HPe Thank you for addressing the previous comments. I left just one last small fix to make on the dark mode components. Other than that, it's looking great!

**Comment by Keeth-HPe** [comment]
Thank you for reviewing this in detail, Vicky. 
Helped so much in crafting the component to perfection. 

Here's the link to the [component page](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3522%3A86687) & its variants. If it's good to go we shall close the ticket.

**Comment by KennyAtHPE** [comment]
@Keeth-HPe will do reviews today, apologies have been backed up on other issues

**Comment by vavalos5** [comment]
It looks good to me from my end. Once @KennyAtHPE reviews, I'm ok with you closing @Keeth-HPe  👏🏼

**Comment by KennyAtHPE** [comment]
I’ve reviewed the component and left a few comments. I have concerns with some of the bugs I’ve identified similarly to checkbox. Will be discussing with Vicky for possible further steps

**Comment by vavalos5** [comment]
How about we close this ticket @Keeth-HPe and Kenny since we know that both this ticket and checkbox have issues, let's add those issues to your primary ticket where these are linked.

**Comment by vavalos5** [comment]
Closing due to the fact that Kenny and I need to reevaluate the way the component is being built due to bugs. I've also reference this ticket in the main one: #2889
