### ISSUE TITLE
CheckBox - Finalize Figma Component

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2894]
### Current Status
- [Figma component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2971%3A63108) can be found here

Some more context [here](https://hpe.slack.com/archives/C04LMJWQT/p1663091768662529)

### Deliverables
- [x] Include variants with toggles
- [ ] Both toggle and checkbox variants should have the flexibility to be left or right-aligned This property is called "Reverse"
![image](https://user-images.githubusercontent.com/86075038/189978017-f664cbb9-b2ec-4aa0-a6da-bd852648528d.png)
![image](https://user-images.githubusercontent.com/86075038/189978121-50f92a1c-923f-406f-a006-87fee5bc7cca.png)
- [ ] Reach back out to Amanda Vogel for review once the component is finished

**Comment by KennyAtHPE** [comment]
Next steps are here #2891

**Comment by Keeth-HPe** [comment]
@KennyAtHPE  @vavalos5 

I've added the toggle as a boolean (Right+Left). But had to include variant selection drop (checkbox / Toggle)
Not sure if it's right, but after many tries, that's what I felt was a good way to go about it.

Please do take a look when you get the chance to. Will be super helpful. 
[Test Component here ](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3692%3A106768)

**Comment by vavalos5** [comment]
@Keeth-HPe Kenny and I chatted on this and we feel that it needs a further conversation as we're starting to see many bugs and complications with the creation of migrating checkbox and toggle together. Lets put this on pause until Kenny and I discuss further. Thanks.

**Comment by Keeth-HPe** [comment]
Thanks, @vavalos5 
I did see one major bug, which was a silly mistake. Having two right  & left toggles. I have fixed that one. 
But yes, will pause on this, until you'll review it again :)

**Comment by vavalos5** [comment]
Closing due to the fact that Kenny and I need to reevaluate the way the component is being built due to bugs. I've also reference this ticket in the main one: #2889
