### ISSUE TITLE
Homogenize capitalization across all DS guides

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2897]
Related to: #2744

Now that we've started to enforce the sentence case capitalization and that we've published the new guideline, we should ensure that we are also following sentence case across all of our guides on the DS website. We, ourselves should adhere to it, as well! 

Here's a [list in Excel of all of our DS Guides](https://hpe-my.sharepoint.com/:x:/r/personal/dahlia_ferrer_hpe_com/_layouts/15/Doc.aspx?sourcedoc=%7B6C26EC54-A0C2-47B1-80F8-A2713DAC3084%7D&file=Audit%20of%20Guides%20on%20DS%20Website.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=dahlia.ferrer%40hpe.com&ct=1663172461323&wdOrigin=OFFICECOM-WEB.MAIN.EDGEWORTH&cid=4dca23cc-256e-4f72-8e03-eaac81fc9b3b) and unless there is a better place to track it, we can track progress there.

**Comment by taysea** [comment]
Closing, has been done by #2744
