### ISSUE TITLE
Global Header - Explore breakpoints for sizing variants

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2900]
Building on #2849 
Component can be found [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3028%3A58403)

### Problem
-------------------------
The current component allows up to 6 navigational tabs however the defined breakpoints cannot support that. 

![image](https://user-images.githubusercontent.com/86075038/190806918-3b0092f3-da18-490c-95c8-f2e768b7b637.png)

Based on the [Page Layout](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=190%3A3718) work, it has been defined that the Large size encapsulates screens from 1081px - 1439px. The image above shows the component at a 1081px sizing. As for the Medium size (769px - 1080px) we currently do not display navigational tabs at all. Gina has proposed that tabs shouldn't show once screen sizes are <1200px.

### Deliverables
-----------------------------
- [ ] Explore alternative sizing for Global Header (up to 6 tabs, also some languages have longer text)
- [ ] Review with Gina

----------------------------------
Additionally, on her end Gina will be working to create master components for the [profile menu,](https://www.figma.com/file/AbxAC3KU59pPyHG5mnnh7R/HFS-North-Star?node-id=2779%3A70644) [rubix menu](https://www.figma.com/file/AbxAC3KU59pPyHG5mnnh7R/HFS-North-Star?node-id=4055%3A78316), and [help menu](https://www.figma.com/file/AbxAC3KU59pPyHG5mnnh7R/HFS-North-Star?node-id=4055%3A78188). Will need to prototype the Global Header component with instances of these components when they have been created.

**Comment by taysea** [comment]
Closing, implemented by #2902
