### ISSUE TITLE
Button - Figma Button Bug on Hover behavior

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2909]
Please investigate why the Button component isn't receiving hover behavior upon changing the variant within the props panel. Oddly enough, we have them built out in the variant section but when toggling in toolbar section, the hover behavior isn't applied. Please see image below. Seems to only happen with the Primary button.
<img width="518" alt="Screen Shot 2022-09-21 at 4 58 13 PM" src="https://user-images.githubusercontent.com/62117454/191630196-ed3a17fd-2e8a-45ca-b693-94e942594be7.png">

**Comment by vavalos5** [comment]
@Keeth-HPe Please also work on this one in addition to #2860

**Comment by Keeth-HPe** [comment]
@vavalos5 
It is working fine. 
<img width="334" alt="Screenshot 2022-09-22 at 2 30 27 PM" src="https://user-images.githubusercontent.com/86280029/191704904-f4487642-c4b1-4a44-813c-50211cb893eb.png">
<img width="348" alt="Screenshot 2022-09-22 at 2 30 49 PM" src="https://user-images.githubusercontent.com/86280029/191704964-e62f43a5-8640-48f3-80ef-d1f47601a0bc.png">


<img width="329" alt="Screenshot 2022-09-22 at 2 31 02 PM" src="https://user-images.githubusercontent.com/86280029/191705007-8a0826cc-85b2-42ae-a2ed-6f7f6b1c39ac.png">

**Comment by Keeth-HPe** [comment]
However, I see, Hover state and active state of Toolbar button do not have any difference. Is that on purpose? 
@vavalos5 
<img width="551" alt="Screenshot 2022-09-22 at 6 03 58 PM" src="https://user-images.githubusercontent.com/86280029/191748068-817ef750-3b30-4451-9509-e3ec8e6c58d8.png">

**Comment by vavalos5** [comment]
Thanks for investigating and fixing Keeth. I tried it out and it worked!

In regards to the Toolbar Button, that's a good question and I'm not sure if this is the actual behavior we want. After reviewing the Toolbar component on the design system and interacting with it, it looks like onClick, it doesn't continue to have a background contrast color applied. @jcfilben Is this issue similar to the one we've been discussing for menu?

**Comment by vavalos5** [comment]
Adding Button Figma link here: https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1

**Comment by jcfilben** [comment]
> After reviewing the Toolbar component on the design system and interacting with it, it looks like onClick, it doesn't continue to have a background contrast color applied. @jcfilben Is this issue similar to the one we've been discussing for menu?

Yeah this sounds like it is kinda related to what we were talking about with Menu. I think once the Menu is open the menu button shouldn't have active styling to avoid multiple things on the page being 'active'

**Comment by taysea** [comment]
We generally use `active` to denote a button that is currently "applied". `active` state of the button has to be applied intentionally by the dev via `active` prop (it doesn't automatically happen when a button is clicked). A common use case of active is a navigation button that remains `active` when you're on that route. For example "Components" button when at [Components page](https://design-system.hpe.design/components).

We have `active` state for all button kinds (default, secondary, primary, etc.) however I'd say default is the main button kind that ever receives this treatment.

In response to your question @vavalos5 -- The active styling we have documented for toolbar is consistent with other button kind active states (good), but I don't think we ever actually apply `active` for Toolbar button in any of our patterns at the moment (however, nor do we for secondary or primary either but they still have active states in Figma).

**Comment by vavalos5** [comment]
Thank you @jcfilben and @taysea for the information.

After a chat with Taylor, I clarified that the styling in the Figma button components are aligned from dev side. However, Taylor suggested that we may want to consider having a further discussion with another designer and dev opinion to consider removing `active` from toolbar. Reasoning is because right now we don't currently have any specific use cases where an `active` state is needed for a primary or secondary button.

Adding a ticket to our backlog to keep track of needed discussion here: #2919 

@Keeth-HPe This ticket is ok to close.
