### ISSUE TITLE
Small content updates: Voice & Tone

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2910]
As we come to conclusions on what we'd like to clarify and update in our guide (as a result of discussions, such as Office Hours) we should have a way to track any work towards it and **_publish_** so we can help the HPE devs implement it.

To that end, I suggest that:
In this ticket we track small updates/clarifications that we want to add to the Voice and Tone guide on our DS website.

DS designers/devs can track what's been agreed that we need to clarify here.

If a suggestion for an update is complicated and requires research/talks with stakeholders then

**Comment by jcfilben** [comment]
> In this ticket we track small updates/clarifications that we want to add to the Voice and Tone guide on our DS website.

Closing this and proposing that if there are any updates needed to the voice and tone page those can be filed as separate issues as they come up.
