### ISSUE TITLE
Card - Connect w/ Taylor, Matt and Kenny to identify how we might design Card components within Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2916]
[Figma file
](https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=2865%3A11483)
## Problem

When configuring the Card component, I need to specify several regions, props and variants. In addition, for each variant, I need to provide designers flexibility to turn props off and on such as content, buttons, imagery and background colors. In addition, designers should be able to edit content quickly and change imagery.

The problem I face is that the amount variants needed to provided flexibility can be a lengthy process within Figma. I could be most productive if I created a few variants with a header, body and a footer with paired examples. Largely due to the fact that there are still more variants of cards that we haven’t addressed.

## Problem Statement

As a Designer, how might we best create the Card component within Figma to provide designers the flexibility to quickly configure props when creating designs? Configuring props include turning text, imager and buttons on and off. As well as editing content or adding imagery.

## Next Steps

- [x] Create a problem statement

- [x] Connect w/ Kenny, Taylor, and Matt to discuss how we'll want to create components within Figma. Whether that's with props + variants or provide variants with examples besides them. Given the complexity/variety that can be created, we'll want to look at the pros of adding props and variants vs. implementing them how we have in the past.

## Deliverables
- [x] identify how we're going to build cards within Figma
- [x] Get Sylvia and Greg to play with component and review
- [x] Implement any feedback received
- [ ] deliver one set of cards in light and dark mode

**Comment by vavalos5** [comment]
@KennyAtHPE Can you take a look [at the variants I created](https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=2839%3A11019) and tell me if you see anything weird.

Oddly enough, yesterday when I applied the Avatar component, i was able to swap between logo and image but today I don't see those options show up.

Also, for the navigational row one, I've still gotta fix the icon so it aligns properly.

LMK if you see anything else. Thanks!

**Comment by KennyAtHPE** [comment]
@vavalos5 Avatar worked fine when I was testing it 🤷‍♂️ . Left some comments, it's looking good!

**Comment by vavalos5** [comment]
@KennyAtHPE Ready to get your eyes on it one more time :)

Also sending to Sylvia and Greg to test drive

**Comment by KennyAtHPE** [comment]
Tested component responsiveness for sizing and text behavior. Everything looks great! Had some very small comments on frame naming and the default Avatar logo. Awesome job!

Thinking that the next steps for this component in terms of variants is to provide options with multiple buttons and dark mode.

**Comment by vavalos5** [comment]
Thank you!! :) 

Yea, i'd agree. Those are my next steps. I'm meeting w/ Taylor on Monday to discuss naming and once we've got everything defined I'll create dark mode. Thanks @KennyAtHPE

**Comment by KennyAtHPE** [comment]
Met w/ Taylor to review the Card Figma component. Currently making revisions

**Comment by KennyAtHPE** [comment]
Will be connecting with Greg on Monday to talk about potential next steps

**Comment by KennyAtHPE** [comment]
Connecting w/ Vicky before closing. Next steps will be tracked in #2955
