### ISSUE TITLE
Button - Discussion on removal of active state for Primary, Secondary and Toolbar Button

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2919]
Based on #2909

### **Problem**
Active states are being applied to primary, secondary and toolbar buttons when there are no use cases for them.

### **Background**

While Keeth was doing some button clean ups on Figma file. She pointed at the fact that the toolbar button's active state had the same behavior applied to it as the hover. In connecting with the devs, I clarified that the styling in the Figma button components are aligned from dev side. However, Taylor suggested that we may want to consider having a further discussion with another designer and dev opinion to consider removing `active` from toolbar. Reasoning is because right now we don't currently have any specific use cases where an `active` state is needed for a primary or secondary button.

### **Objective**
- Gather as a team to conclude relevance of the active button.
- Revisit use cases or determine if we need to gather more recent use cases if any.

**### Goal**
Determine whether we should offer actie states for primary, secondary and toolbar buttons.

**Comment by taysea** [comment]
Closing, stale.
