### ISSUE TITLE
List - Add additional variants to the Figma Component based on GLCP use cases

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2922]
Sylvia did some testing with our current [List component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=1058%3A18489) and identified areas in which the component satisfied or did not satisfy their use cases.

Sylvia's [test file ](https://www.figma.com/file/UHoXXKufEnlPQkMpcQOld4/UI-Design-Debt-(GLCP)?node-id=1%3A2)
Related to #2412
 
### Deliverables
- [ ] Connect with a dev to understand the function and implementation of the List Grommet component
- Outline
     - [ ] How many components are needed + what type of components are needed (i.e. slot components, unpublished, and published components)
     - [ ] What variants and component properties are needed based on the Grommet props for the component (h
- [ ] Review w/ a dev
- [ ] Build component(s) with slots
- [ ] Test build by recreating the variants that Sylvia brought up.
- [ ] Review w/ a dev on layer naming, grouping, sizing, and spacing/margins
- [ ] Review w/ a another designer
- [ ] Deprecate old List component [(Guide](https://www.figma.com/file/grsz2h0yjVw0lGalHIcu2A/Deprecation-Process?type=design&node-id=0%3A1&mode=design&t=4PtXDo2FHJ1gTE03-1))
- [ ] Publish and announce component

**Comment by halocline** [comment]
I am thinking that List should not have any opinion about how its children appear. List should solely be a layout component.

I recommend pairing up with a developer to discuss how List might be built, what it should be responsible for, and what it should not be responsible for.

**Comment by taysea** [comment]
Closing, have taken a more slot-based approach to list.
