### ISSUE TITLE
CheckBox - Fix Figma component bugs

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2923]
Building on #2894 
[Figma Component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2940%3A62424)

The component has been fully built however Vicky and I have identified several bugs.

### Deliverables
- [x] Address any issues with the Figma component
- [x] Include changes from #2938 and #2811 
- [x] Review w/ Vicky, Keeth

**Comment by KennyAtHPE** [comment]
Next steps #2891

**Comment by KennyAtHPE** [comment]
Be sure to include variants of [checkboxes that are outside of a formfield ](https://design-system.hpe.design/components/checkbox?q=chec#checkbox-outside-of-formfield)

**Comment by KennyAtHPE** [comment]
Will be reviewing with Jessica to maintain consistency with the Grommet component. Tagging @vavalos5 and @Keeth-HPe for additional review.

[CheckBox test
](https://www.figma.com/file/mKDjcFzkvbjFRsTaGMg33q/Component-Building?node-id=6%3A1885&t=gKa2JAZQsGwAe6lo-1)[CheckBoxGroup test](https://www.figma.com/file/mKDjcFzkvbjFRsTaGMg33q/Component-Building?node-id=7%3A29725&t=gKa2JAZQsGwAe6lo-1)

**Comment by vavalos5** [comment]
They both look great Kenny! I left a few comments on the CheckBox test. I didn't see any issues with the CheckBoxGroup
