### ISSUE TITLE
RadioButton - Fix Figma component bugs

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2924]
Building on #2892 

The component has been fully built however Vicky and I have identified several bugs.

### Next Steps:
- [x] Address any issues with the Figma component
- [x] - Outline and identify how many components are being built at the atomic level. Then for each one of those being built, what are the variants and the component properties.
- [x] - Pair up with a developer and build components and ask any necessary questions like whether to include certain variants or component properties. i.e. the radio button with a focus around the circle.

### Deliverables
- [x] Review w/ Kenny, Vicky, Keeth

**Comment by KennyAtHPE** [comment]
Next steps #2893

**Comment by KennyAtHPE** [comment]
[RadioButton](https://www.figma.com/file/mKDjcFzkvbjFRsTaGMg33q/Component-Building?node-id=37%3A17854&t=1bdltg8OGYfK4YuU-1)
[RadioButtonGroup](https://www.figma.com/file/mKDjcFzkvbjFRsTaGMg33q/Component-Building?node-id=38%3A17855&t=1bdltg8OGYfK4YuU-1)

Requesting review @vavalos5 @Keeth-HPe

**Comment by Keeth-HPe** [comment]
@KennyAtHPE Thank you! Looks good so far. 
I left a few comments on the file
