### ISSUE TITLE
Text Input - Add 'Numerical field variant'

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#2926]
For numerical form fields, the text input component's input field should be flexible. So that the user can reduce the width of the input field while the label & error message can span the entire width of the input field. 

<img width="444" alt="Screenshot 2022-09-26 at 2 04 05 PM" src="https://user-images.githubusercontent.com/86280029/192776765-17bf0d31-cbdd-49fd-9e49-70973dec085f.png">
<img width="990" alt="Screenshot 2022-09-26 at 11 54 46 PM" src="https://user-images.githubusercontent.com/86280029/192776802-83390eb8-55f0-4b8c-9b0b-89a4c5a20b25.png">

**Comment by vavalos5** [comment]
Thank you for adding this ticket Keeth. Did you mean to tag @KennyAtHPE or is this a ticket you're investigating into?

**Comment by Keeth-HPe** [comment]
My bad, wanted to tag him but assigned him by mistake.
I'm going to work on it :) 
@vavalos5

**Comment by KennyAtHPE** [comment]
Noticed this was in the review column, is this something you're ready to get eyes on @Keeth-HPe ?

**Comment by Keeth-HPe** [comment]
Yes, please review and share feedback :) @KennyAtHPE

**Comment by vavalos5** [comment]
Some quick questions:

If we're only allowing for numerical fields to go within this input, should I be allowed to turn on the left and right icon? Are we able to limit it for this variant?

In dark mode, the description, info., and error text is still showing up as light text.

**Comment by KennyAtHPE** [comment]
@Keeth-HPe left some comments about minor issues. Looking great so far, very close to the finish line with this one!

Agree with @vavalos5 that this variant doesn't need icons on the left or right. We can remove this option by deleting the left + right side icons from these variants.

**Comment by Keeth-HPe** [comment]
@KennyAtHPE  Thank you for reviewing and sharing your feedback 🙌
I fixed the minor comments - 
1. Description not being disabled (Light & dark theme)
2. deleting the left + right side icons from these variants

However,I wasn't sure of your last comment on giving this variant a fixed width. If we give it a fixed width, the input field would not wrap the input text. Please let me know how that would work. Will be helpful. Thanks :) 

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=304%3A1001

**Comment by KennyAtHPE** [comment]
@Keeth-HPe thanks for the quick fixes! You made a good point on having it as fixed width rather than hug contents, totally agree with you there. Everything looks good to me and I think this ticket should be good to be closed if you think everything is done.

**Comment by vavalos5** [comment]
Looks great Keeth. Left two comments on Figma. :) So close!

**Comment by vavalos5** [comment]
Look good @Keeth-HPe. You can close this now :)
