### ISSUE TITLE
DataTable – Fix units in Fixing header row/columns

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2928]
https://design-system.hpe.design/components/datatable?q=datata#fixing-header-row-and-or-columns

The above example should be using the `units` aspect of DataTable columns and rely on the default styling (similar to https://design-system.hpe.design/components/datatable?q=datata#paginated)

**Comment by halocline** [comment]
closed by https://github.com/grommet/hpe-design-system/pull/2943
