### ISSUE TITLE
Create Avatar Page in DS site

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2933]
Based on this issue we can create a new Avatar Page.
https://github.com/grommet/hpe-design-system/issues/2838

Use this [figma](https://www.figma.com/file/d7a74LgBABdgTZR6HrzWKo/HPE-Avatar?node-id=1521%3A1773)

based on the page complexity thinking this can be done in one sprint. 

Should we add Dalhia to review content now?

**Comment by KennyAtHPE** [comment]
@dahliaferrer requesting reviews whenever you are free. Thank you!
