### ISSUE TITLE
SelectMultiple - Review Figma component

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2934]
Building on #2921
Test Component can be found [here](https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/SelectMultiple-Component?node-id=2711%3A74801)

### Goals
- [x] Review revised component w/ Jessica 
- [x] Update based on review as necessary
- [x] Rreview with Sylvia
- Component announcement tracked in #2889

**Comment by KennyAtHPE** [comment]
Finished reviewing and updating the component with Jessica. Will be sending out the component to Sylvia for testing next week.

Requesting review from @Keeth-HPe and @vavalos5 as well.

**Comment by Keeth-HPe** [comment]
Hey @KennyAtHPE 
The component looks great!! It is now much easier to understand. 🙌

I just had one comment on the 'Help text' property. The toggle does not show any changes  . Please Refer the recorded video is below. 


https://user-images.githubusercontent.com/86280029/194794377-61669f82-4e50-46fe-b217-4f29debd8a55.mov

**Comment by vavalos5** [comment]
It looks so good Kenny! I dropped a few comments on your Figma file.

**Comment by KennyAtHPE** [comment]
Thanks for the reviews @Keeth-HPe @vavalos5! The component has been updated based on your feedback. Sylvia also just finished reviewing this component earlier today and was not able to find any issues with the component.

Closing this ticket
