### ISSUE TITLE
grommet Quality Fest

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2935]
## Problem

Recently, we've had multiple issues for regressions in grommet behavior. How can we improve the quality of grommet to avoid these issues?

## Suggestion

- review grommet issues from the last four months, look for patterns and propose how to focus improvements
- anything we should change in our review processes?
- anything we should add/change in our unit tests?
- anything we should add/change to our interactive tests?
- should we be paying more attention to code coverage?

## Deliverables

- [x] new issues created that describe changes to make

**Comment by britt6612** [comment]
created a new issue for what we can tackle now:
https://github.com/grommet/hpe-design-system/issues/2944

mural board in which we used for exercise:
https://app.mural.co/t/hpecdoresearchteam7715/m/hpecdoresearchteam7715/1664910459003/eae7c410aba60e861d4066ee64cd5e54156e7b45?sender=brittanyarchibeque8003
