### ISSUE TITLE
Brand Refresh - Update Figma Button

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2937]
Button in Figma will require the following changes:

<img width="515" alt="Screen Shot 2022-10-04 at 1 13 31 PM" src="https://user-images.githubusercontent.com/12522275/193932924-6196516b-b1e7-4be9-a5f5-d21516b814b5.png">

`small`:
- [x] rounding `6px`
- [x] font-size: `16px`, line-height: `22px`

`medium`:
- [x] rounding `6px`
- [x] font-size: `19px` (necessary to meet contrast requirement on HPE green), line-height: `24px`

`large`:
- [x] rounding `8px`
- [x] font-size: `20px`, line-height: `26px`
- [x] vertical pad: `8px`

`xlarge`:
- [x] rounding `10px`
- [x] font-size: `22px`, line-height: `28px`
- [x] padding: vertical `10px`, horizontal `20px`

Add NEW CTA button variant:

<img width="282" alt="Screen Shot 2022-10-04 at 1 15 24 PM" src="https://user-images.githubusercontent.com/12522275/193932852-7e04732c-a7db-4626-8084-bd39b3680564.png">

`cta-primary`:
- [x] label color `text-strong`.dark (white) for dark and light mode
- [x] icon: Hpe element, color white
- [x] background color: `brand`
- [x] rounding: `100px`
- pad:
   - [x] small - vertical: `3px`, horizontal: `12px`
   - [x] medium - vertical: `6px`, horizontal: `16px` (36px tall)
   - [x] large - vertical: `8px`, horizontal: `20px` (42px tall)
   - [x] xlarge - vertical: `10px`, horizontal: `28px` (48px tall)

`cta-alternate`:
- [x] label color `text-strong`.light
- [x] icon: Hpe element, color brand
- [x] background color: `#F2F2F2` (introduced in theme as `background-cta-alternate`
- [x] round same as `cta-primary`
- [x] padding same as `cta-primary`

**Comment by KennyAtHPE** [comment]
Additional steps for refactoring the Figma button component
-------------------------------------------------------------
Currently, [our button](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1) has 7 different components
- 3 light and 3 dark components separated by three different sizes
- 1[ light Medium component that lives within the Leftovers page](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=1904%3A1386) (not sure why this one exists or why it is living in the Leftovers)

The component with the most usage is currently the one within the Leftovers page so moving forward let's use this Button as our main component. **All of the outline steps will be in reference to this component.** 

- [ ] The component should have the following variant, component properties, and values
        - Variants
                - [ ] Theme - Light, Dark
                - [ ] Type - Primary, Secondary, Default, Toolbar, Color
                - [ ] CTA variant - Default, Primary, Alternate
                - [ ] Size - Small, Medium, Large
                - [ ] State - Enabled, Hover, Focus, Active, Disabled
                - [ ] Icon - None, Left, Right, Icon Only
         - Component Properties
                - [ ] Icon - Swap instance property
- [ ] Apply style changes outlined above to Small, Medium, and Large sizes
- [ ] Default Button variant for users should be "Light theme, Primary type, Default CTA variant, Medium size, Enabled state, No icon" 

- [ ] Review with Kenny + a Dev
- [ ] Move the updated Button component to the Design System Components file. [Article on how to do that](https://help.figma.com/hc/en-us/articles/4404848314647-Move-published-components)
- [ ] Deprecate the [6 other button components](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1)
       - [ ] Change component names to "🛑 Deprecated"
       - [ ] Add the date they were deprecated within the description
       - [ ] Add a link to the new button component page in the documentation field
       - [ ] Push update for these changes and include a message of where people can find the new component and who to reach out to for questions.
       - [ ] Move components to their own deprecated page
       - [ ] Update thumbnail to this [template](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2000%3A62061)
       - [ ] Move file from Library to Working Files
- [ ] Publish new Button component and announce it within the HPE-Design-System channel

**Comment by vavalos5** [comment]
@Keeth-HPe As you complete these, pleas ensure you mark off completed items.

**Comment by Keeth-HPe** [comment]
Would love to receive some feedback on the button component
[Please do test it here](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=6940%3A12103)

Uploading @vavalos5  comment here, as I need some help on this. 
<img width="293" alt="Screenshot 2022-10-19 at 9 05 22 PM" src="https://user-images.githubusercontent.com/86280029/196737882-5d3de81d-6a5d-444a-8db4-aeb998b90ec1.png">

@KennyAtHPE

**Comment by KennyAtHPE** [comment]
Left some comments just now @Keeth-HPe, apologize for the delay. I also left a suggestion on how to address that comment.

**Comment by Keeth-HPe** [comment]
Thank you so much @KennyAtHPE and @vavalos5, I appreciate all the detailed reviews.
I have fixed the comments. https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=6897%3A11226
If this the component is working fine , I shall work on the next steps.

**Comment by KennyAtHPE** [comment]
Hey @Keeth-HPe after talking with Taylor, we think that the disabled states for the new CTA variants should be omitted for now since we don't currently have any use cases for it. 

Besides that everything looks good to me, awesome job on this!

**Comment by KennyAtHPE** [comment]
The component has been published and announced. Closing ticket
