### ISSUE TITLE
Brand Refresh - add gradients and textures as tokens in Figma (alongside colors?)

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2940]
The latest brand [gradients, textures, datawaves, etc.](https://brandcentral.hpe.com/brand-central/content/distinctive-brand-assets/flexible-ingredients#c2-color-and-texture-style-2) that are supported out of the box from grommet-theme-hpe v4 should also be added into Figma.

Will leave it to a designer to fill-in deliverables/how to approach.

## Deliverables

- [x] Add gradients to Figma
- [x] Guidance on how they should be used

## Steps to complete

- [x] Discuss with Chris on whether we should add these to Figma
- [x] Where should they be located to avoid people from using it
- [x] Await gradient values from Chris/Tim
- [x] Apply gradient values to Figma
- [x] Create guidance on how they should be used

**Comment by vavalos5** [comment]
Will be chatting with Chris today on this and whether they're items that should be living within the Figma or if people should be pointed to brand.

**Comment by vavalos5** [comment]
Putting a reminder here to also add button hover gradient treatment when creating gradients.

**Comment by vavalos5** [comment]
3/31 - have a meeting set up with Chris on Monday to discuss whether we should implement in Figma.

**Comment by vavalos5** [comment]
4/03 - Chatted with Chris, we both agreed we should create the gradient styles in Figma. In addition, we will be adding some text so when you hover over the gradient, it'll tell you that it is only used for Edge. One problem I pointed out to Chris is that we need the gradient numerical values as the ones I replicated do not blend or transition nicely. I was informed that Tim has added other shades in between to the ones from Brand. Will have to wait until Chris gets a hold of those to complete this.

**Comment by halocline** [comment]
> Tim has added other shades in between to the ones from Brand.

We will need to update the HPE theme gradients when we get the new values from Tim/Chris/brand. We filled in our best guess at intermediate gradient values to avoid the muddy, washed out look.

When you have a chance, can you add this to the "steps to complete" in this issue's description? 🙏

**Comment by vavalos5** [comment]
Pinged Chris 4/5 but no answer.

**Comment by vavalos5** [comment]
4/11 - Pinged Chris again. He was able to retrieve hex values from Tom. Chris is going to work on implementing these gradients with a Figma plug in as I don't have access to Adobe Illustrator (files sent from Tom).

**Comment by vavalos5** [comment]
Chris has given me a [Figma link](https://www.figma.com/file/hu87GnO6Cz7znjc3FAudE9/Revised-Gradients-for-web?node-id=14%3A26&t=DqJDJPtUVkKpNQzt-1) where he's added the gradients to. He's awaiting for a response from brand and web teams to see if their code has any banding to it due to the fact that the first pair doesn't transition as smoothly as the second pair Chris created. 

![Image](https://user-images.githubusercontent.com/62117454/232567558-da322b64-b682-411f-bbf4-85c115c9b6f1.png)

**Comment by vavalos5** [comment]
Gradients have been added to [Figma](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=6238%3A644&t=iguPQZWFuiXnM9hu-1) and added as gradient color styles. In addition, i've worked with Jessica to implement the gradient style for the primary button on hover.

@KennyAtHPE can I get your eyes on this and let me know if you see anything odd.

Will be sending to Chris too for review.

**Comment by vavalos5** [comment]
For reference when checking color styles:

**Gradients for Edge use cases:**

purple blue yellow should be : Gradient/gradientEdge  | Gradient only to be used for "edge" use cases.
orange yellow green should be : Gradient/gradientEdge  | Gradient only to be used for "security" use cases.
purple blue should be : Gradient/gradientEdge  | Gradient only to be used for "data" use cases.
purple magenta yellow should be : Gradient/gradientEdge  | Gradient only to be used for "cloud" use cases.

**Button Color:**

button background color on hover: Gradient/primaryButton  | Used for primary button only! Do not use as the primary button on hover will already have the gradient applied to it.

Chris has reviewed and approved

**Comment by halocline** [comment]
@vavalos5 did an issue get created for ensuring the HPE theme has these same gradient definitions?

https://github.com/grommet/hpe-design-system/issues/2940#issuecomment-1495091664

**Comment by vavalos5** [comment]
@halocline thanks for the reminder! I was told by Chris that the devs on the web team are currently using images when using gradients (not the best approach). In instance where gradients are coded, it's a background fill with banding an all (no easing). I did want to ask whether the devs would want to have further convos with Chris on this behalf, create a better solution and maybe show to brand?
