### ISSUE TITLE
Grommet Quality Follow up

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#2944]
Ideas we can start doing with the November release:

- [ ] Break release up across 2 sprints (sprint 1 QA es coverage) sprint 2 is notes/docs/release
- [ ] Have 2 people when fixing a bug or doing an enhancement ( 1 person codes the fix while the other writes a test)
- [ ] Create a 30min meeting for us to explore ways to break certain components or new features.
- [ ] Make sure there is a test with every bug fix.
- [ ] Showcase good behavior in our slack channels we don't need to fix things right away but let users know a bug is on our radar.

**Comment by taysea** [comment]
Closing, stale.
