### ISSUE TITLE
Pagination – Add example of Select control for # of items per page

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2948]
Request from Design System council for a pattern of how to show a control for the # of item per page. Feels like something to be added to "Pagination" page or "DataTable"/"Lists".

Deliverables:
- [ ] Example added on Design System site
- [ ] Guidance added of when to use, what default step should be, what options for steps should be (to connect with designer here)

**Comment by JCoder121** [comment]
Note: use datatable server side pagination example and provide a link to reference the example in the DS Pagination component page.

**Comment by halocline** [comment]
closing in favor of https://github.com/grommet/hpe-design-system/issues/3777
