### ISSUE TITLE
Card - Explore alternative build for Figma component

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2955]
Building on #2916 
[Figma component
](https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=2835%3A11195)

-----------------------------------------
The component is currently built in the same pattern as our new refactored components. This is causing some constraints when it comes to flexibility for our users. Let's explore an alternative way, Slot component, to build the Card Figma component.

### Steps
- [x] Connect w/ Greg on his exploration on Slot components
- [x] Create a Card Figma component using the slot component strategy
- [x] Review with designers + Taylor
- [x] Create a study by connecting with Maria to test our current Card component vs the new Slot Card component w/ other designers
- [x] Create Criteria
- [x] Review with Kenny, Maria and Scott, Greg
- [ ] Implement feedback from review

**Comment by vavalos5** [comment]
After having a discussion with Greg, Scott and Kenny, Kenny and I have decided to create a study where we will have designers test out 2-3 different variations of built out components. While we do appreciate Greg's voice, I think it is important for designers who will be utilizing the component to create designs should have an opportunity to provide us with insights on which component is easiest to create their use cases.

As a next step, I will be connecting with Maria from the research team to discuss whether she has time in the next week to help us run the study. I will also be working on questions to ask designers. Kenny will be cleaning up the Card component.

**Comment by vavalos5** [comment]
I've reached out to Maria and have worked out a first draft of we'd like to test which I will be showing Maria once we are able to connect.

**Comment by vavalos5** [comment]
I've created the study which can be [found here](https://hpe-my.sharepoint.com/personal/vicky_avalos_hpe_com/_layouts/15/doc.aspx?sourcedoc={81035778-4277-4b96-b446-53af592cf218}&action=edit). I've reviewed it with Kenny and have sent it to Maria and Scott for review.

**Comment by vavalos5** [comment]
I've also sent to Greg and will be walking him through study. Awaiting feedback still from Maria and the last bit from Scott.

**Comment by vavalos5** [comment]
Going to close this ticket as I haven't been able to review and implement feedback. Ticket to follow is: #2989
