### ISSUE TITLE
Menu - Implement new Menu styling

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2964]
## Deliverables

- [ ] pull request on grommet-theme-hpe: https://github.com/grommet/grommet-theme-hpe/pull/287
- [ ] review and merge

Please implement the new Menu styling to the design system site as noted in ticket #2907:

Solution: Option 1 no longer has additional padding top or bottom of the list items. In addition, we decided to remove the padding below and above the separators to remove the "unintentional" look/feel Sam discussed in the comment above. This provides a smoother transition between list items when hovering over them.

Lastly, we decided to have the separators go edge to edge of the menu to be consistent with our other designs like DataTable and Lists who have separators going end to end. The separators have also been changed from `border-weak` to `default border `color. Reasoning is to have consistent border colors like that on the toolbar button.

Adding an image below of new styling:
![195206196-6fb9b807-f665-469f-ac2a-0d4c514782c0](https://user-images.githubusercontent.com/62117454/195457344-46af6412-d4e6-4ab8-9f98-c2ea2f242b37.png)

[Figma file](https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=3107%3A1576)

**Comment by vavalos5** [comment]
@halocline when you begin to work on this or whichever other developer, lets connect to discuss whether the menu button should have a border. In Figma, right now we have the toolbar button styling for the meny button, but on the design system site, by default it is our default button but show examples of a menu toolbar button within a DataTable.

**Comment by vavalos5** [comment]
Upon looking at Figma Menu analytics on where Menu is being utilized, it looks like not many teams are using it and if they are, they're adjusting the menu button to the correct styling. Except for PAL. Since in Figma we currently have the menu button as a toolbar, we will need to update that to a default button and add notes to Figma that Menu styling should be default button and that toolbar menu button should only be utilized at the toolbar level. Attaching screenshots of Figma data collected.



![Image](https://user-images.githubusercontent.com/62117454/197290692-3fabc44d-a79e-43d0-b345-abb1ab12d532.png)



![Image](https://user-images.githubusercontent.com/62117454/197290700-dd9cc303-fc6d-4fbc-bf89-2684f2e5ee3f.png)



![Image](https://user-images.githubusercontent.com/62117454/197290713-62e578cb-c426-4f59-9d33-26ba7cf5212c.png)



![Image](https://user-images.githubusercontent.com/62117454/197290720-efa09333-24f8-43cd-923d-eba3a82e3aeb.png)

**Comment by taysea** [comment]
Thanks for pasting the analytics. It might be good to get a small group together next week to discuss how to approach changing in Figma, implications for the breaking change, and how to communicate with teams? I'd be interested in being involved to learn how this is handled on the design side.

**Comment by vavalos5** [comment]
#2997 next steps
