### ISSUE TITLE
Feedback Component - Create Figma component

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#2965]
[Figma link can be found here.](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=5554%3A77765&t=s1DUkyjh1TpOcr1K-1)

~~Megan will be helping us create the Feedback Figma component. [Implementation can be found on the Design System site](https://design-system.hpe.design/). This component will be worked on sometime within the month.~~

The design system team will be creating the Figma component.

### Steps to complete
- [x] Create a V1 of the component while keeping the following things in mind:
   - Component Resizes correctly
   - Text Behaves as intended (wrap or truncate)
   - All component properties have been applied
   - All variants have been created
   - All elements, variants + component properties, and their respective values are named appropriately
   - If applicable, include necessary interactions
- [x] Review w/ Kenny + a dev
- [x] Create a branch on the [Design System Components file](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=0%3A1)

**Comment by britt6612** [comment]
https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=178%3A9151&t=UxXUVC5gWvXJ4cYu-0

<img width="240" alt="Screen Shot 2022-11-17 at 2 26 51 PM" src="https://user-images.githubusercontent.com/42451602/202564160-28170ea2-6ae6-44fe-98a4-574819ed29d8.png">


<img width="237" alt="Screen Shot 2022-11-17 at 2 27 05 PM" src="https://user-images.githubusercontent.com/42451602/202564112-c9481369-d0e6-4c09-826e-e0e2a9c4ea45.png">

<img width="268" alt="Screen Shot 2022-11-17 at 2 30 06 PM" src="https://user-images.githubusercontent.com/42451602/202564144-937bca1f-e18c-45a2-b692-9e472f186147.png">

**Comment by vavalos5** [comment]
While I started creating this component, a lot of questions came to mind. I connected with Brittany and asked why spacing is not aligned to our t-shirt sizing, which component we're going with and i'm beginning to question the guidance written. 

I think we need to revisit the guidance along with the styling to ensure it is aligned with our theme and our other guidance. I'll start writing in this ticket other things i've noticed.

- In the figma file, I noticed the heading for the feedback component is being referred to in the guidance as a "headline". It also states that this is optional. I'm not sure why a heading would be optional

**Comment by vavalos5** [comment]
I've reached out to Megan to add all of the items/pages/examples into the WIP page I created so it is easier to see what is supposed to be implemented. I also duplicated a page of her completed guidance and wrote down notes/feedback.

@KennyAtHPE @britt6612 @taysea or @halocline if either of you are available to look through the [Figma file](https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=662%3A10986&t=L7KjSf6bIqC7Vq5k-1) where I left comments and provide any additional feedback by Monday noon, i'd appreciate it. I'll be connecting with Megan on Monday to go through the feedback i've written. I know it's a short notice so don't worry if you can't.

**Comment by vavalos5** [comment]
@halocline @taysea thank you for dropping comments on the file!

**Comment by vavalos5** [comment]
We've decided to move forward with Slots as they're the most flexible. 

@KennyAtHPE @britt6612 Take a look at the components and let me know if you see anything wonky. Feel free to play around with it [here](https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=806%3A37632&t=VYBhbv103gSFX4x8-1).

**Comment by vavalos5** [comment]
Will publish and update links in the Figma file once it is published on the DS site. But this is done.

**Comment by vavalos5** [comment]
Re-opened and placed in review as i'm connecting w/ the designers tomorrow to discuss pros/cons on two different directions. Ultimately looking for the least maintenance and flexibility.

**Comment by taysea** [comment]
@vavalos5 Did Kenny have any thoughts on the footer action button alignment as a prop, instead of just "1, 2" how it is now?

Also, I might propose we call the property that's currently called "Feedback" as "Example" to align with what Kenny has done on Layer.

**Comment by taysea** [comment]
Got it, should this ticket still be open if we there are plans to add the button alignment?

Also the component is called "Feedback", so having the property also called "Feedback" is a little weird. Maybe "Type" then given the options you proposed. My perspective was to try to have a more consistent prop structure from component to component, and if "Example" could work for both as "here's some preset versions" then that would be nice.

**Comment by vavalos5** [comment]
@taysea I don't think it does. Its a small change that I will be making. All it is, is a matter of alignment. 

Please trust that I know the steps I need to take to get this done.

**Comment by KennyAtHPE** [comment]
@taysea definitely agree with keeping the prop structure aligned from component to component and that's something we've been keeping in mind when building the new component, just don't think in this case specifically that "Example" would be a good fit. Thinking that in this case it's a bit more of a concrete pattern rather than just an example a designer could use as a basis for their design but agree with the wording "Type." We've used this here and there before in the other components as well so that fits nicely, thanks for the suggestion!

**Comment by vavalos5** [comment]
Feedback component was added and published in [Figma Components File](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=5451%3A77424&t=Zd5NFvUlqquJ9tew-1).

A few things that will need to be updated once we have them up on the design system are (FYI @britt6612 @KennyAtHPE ):
The link in Figma of where the component is located on the DS site
Grommet link

@KennyAtHPE I know you were going to make an announcement of available and published components, but since you're out, i'll go ahead and do just this one and you can do the rest.

**Comment by vavalos5** [comment]
Taylor and I have had chats in regards to how the component is built. We worked together yesterday to make changes from the ones Kenny and I had previously made. 

I'd love to re-open this to get Kenny's perspective on the new approach. While all of the approaches we've built are very similar, an issues we've been noticing is that there shouldn't be multiple bodies as slots that can be toggled off and on, there should be a body container but not transferring over into the component due to the way its built.

**Comment by vavalos5** [comment]
After much thought and working on the Card component, I've recreated the Feedback styling and aligned with our other slot components. Second version can be found in this [Figma link](https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=982%3A39622&t=XGdbWcxgxhzXsnw1-1). @taysea lmk if you have any questions

**Comment by vavalos5** [comment]
I've chatted with Kenny and Taylor and have come to an agreement to keep the design similarly to what we previously had.

Feedback has been published. [Figma link can be found here.](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=5554%3A77765&t=s1DUkyjh1TpOcr1K-1)


[All research and explorations are in this file.](https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=931%3A39575&t=nOfVTlbTl55GdTcH-1)
