### ISSUE TITLE
List - Remove "Remove Item" from list example without checkboxes

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2967]
On the DS website, we have an example under the "[Item Order](https://design-system.hpe.design/templates/lists?q=list#item-order)" example where the action toolbar button shows a list of actions : Add Item, Remove Item and Re-Order Items. It doesn't make sense to have "remove item" if we don't provide checkboxes within this example.

Some questions to ask ourselves: can list items have checkboxes?

Should we just remove the "remove item" action from this example?

Do we provide an example with a checkbox to help support the "remove item" action?

including image below:
<img width="718" alt="Screen Shot 2022-10-13 at 4 09 37 PM" src="https://user-images.githubusercontent.com/62117454/195727309-c9e4b184-eb21-44af-a2d6-927c888e9651.png">

### Deliverables:

- [x] Dev/designer pair up to discuss whether we should include an example of list items with checkboxes OR if we should remove that item from the example.
   - Resolution (discussion between Taylor, Kenny, and Beza): Just remove the "Remove item" menu item for now. Explorations about selectable list items will be handled in a separate scope of work: https://github.com/grommet/hpe-design-system/issues/2975
- [ ] Add re-order list variant to Figma
- [ ] Update DS site

**Comment by taysea** [comment]
For this ticket, we've decided to just scope it down to fixing the example. Explorations re: selectable list items is a separate pattern that requires more work. I have filed a ticket for that: https://github.com/grommet/hpe-design-system/issues/2975.
