### ISSUE TITLE
Card - decide which approach to take with Figma, slots vs. more formal?

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2968]
Scott and I ended met on 11/28 to discuss the study I had created. We decided that we will not be conducting the study since we’ve been talking about Slots for some time and have gotten validation that they’re the most flexible from Figma. As a next step, i'll be cleaning out Card component and publishing the slot component direction. After it has been published, we’ll wait out a few months and look at Figma analytics + feedback received on how flexible the component really is/ how it's working for others.

- [x] Clean up Figma file
- [x] Create dark mode version
- [x] Review with Kenny + Taylor
~~- [ ] Publish Card slot component~~
- [x] Create ticket on next steps: provide visuals to show how slot components work + provide content on what a slot component is and why we've decided to move in this direction

**Comment by vavalos5** [comment]
Will be using this [FigJam template](https://www.figma.com/file/dqrPE10QKk3e4jM85oAhfi/Analyse-and-report-usability-test-results-(Community)-(Copy)?node-id=0%3A1) to analyze study results

**Comment by ericsoderberghp** [comment]
Is it better to be more flexible with slots or is it better to be easier to handle common cases without slots?

**Comment by ericsoderberghp** [comment]
Trading off designers not being familiar with slot components so much today but maybe they are the way to go down the road and we just need to train?

**Comment by vavalos5** [comment]
We've decided to move forward with Slots as they're the most flexible. 

@KennyAtHPE @britt6612 Take a look at the components and let me know if you see anything wonky. Feel free to play around with it [here](https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=806%3A37632&t=VYBhbv103gSFX4x8-1).

**Comment by vavalos5** [comment]
@taysea Take a peek and lmk if you see any funkyness happening.

**Comment by vavalos5** [comment]
Think i found a solution for Card's header. The problem we were having within Figma is that the Avatar and the Icon weren't sizing properly if we replaced the instance with either one of them. They wouldn't basically size properly. 

Another example I had previously done was that I had created booleans for both the icon and the Avatar, however, we came to the realization that we don't have the option to show either one or the other if we have booleans for both the avatar and icon.

Finally, I decided to create instances instead to the header. I've created a local component and it seems to be working properly.

@KennyAtHPE and @taysea[ take a peek at the test example i've created here](https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=3330%3A16414&t=5Oqx0e1GWF8dXhBc-1). Lmk what you think.

**Comment by KennyAtHPE** [comment]
The heading section worked well when I was testing it. Awesome job on finding a solution for that!

**Comment by vavalos5** [comment]
Taylor and I got on a quick call to discuss a simple version of card. I've created a [test example here](https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=3330%3A16414&t=MwNPZqgxxqt73ibA-1) with detailed steps on how to replace the body section with a custom made local component.

@KennyAtHPE take a peek and test it out. Would love your input. Thanks!

**Comment by KennyAtHPE** [comment]
@vavalos5 @SOjaHPE @ericsoderberghp

Taylor and I believe that the next steps for this component are to conduct user testing with other designers and then incorporate that feedback for a v2 of the component.

@vavalos5 left some additional feedback comments on the current component [here](https://www.figma.com/file/mKDjcFzkvbjFRsTaGMg33q/Component-Building?node-id=102%3A18400&t=emZlGJUYFdtcLMfv-1)

[Next steps](https://github.com/grommet/hpe-design-system/issues/3065) Closing ticket.
