### ISSUE TITLE
Card - Review feedback received on study and implement

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2989]
This ticket is a continuation of #2955.

Review the feedback received by: Maria, Kenny, Scott and Greg. Make necessary changes to the study.

Nest steps would be to run the study a few times to time length as it is getting lengthy.

**Comment by vavalos5** [comment]
I've reviewed feedback from Greg, Scott, Kenny and Maria and [implemented.](https://hpe-my.sharepoint.com/:w:/r/personal/vicky_avalos_hpe_com/_layouts/15/Doc.aspx?sourcedoc=%7B81035778-4277-4B96-B446-53AF592CF218%7D&file=Designer%20Card%20Study.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=vicky.avalos%40hpe.com&ct=1666814154236&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=1b21351e-3ec9-4ec4-a53f-4565541daf09)

@KennyAtHPE want to take a peek and let me know your thoughts?

**Comment by KennyAtHPE** [comment]
@vavalos5 left some small comments. It looks great, can't wait to conduct and see the results of the studies.

**Comment by vavalos5** [comment]
Next steps: #2968
