### ISSUE TITLE
Meta retro - Create issue template prototypes

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2994]
As output of "[meta retro](https://www.figma.com/file/SHuwUkpEcBGDgOmfdI3GAp/Meta-Retrospective-September-2022?node-id=0%3A1)," create issue templates to track and facilitate deliverables across Design Thinking steps.

These steps are meant for issues where we are starting an initiative from "scratch." Updating or re-evaluating a design decision may jump to the appropriate stage in the Design Thinking process. These templates are not for minor enhancements, bug fixes, etc.; only for tasks where divergent and convergent thinking modes are needed.

- [ ] Tracking issue
- [ ] Empathize
  - Deliverables: Use cases, industry best practices, WCAG 
- [ ] Define
  - Deliverables: Problem statement, design challenge, success criteria
- [ ] Lo-fi
  - Deliverables:
    - UX solution --> 2-3 wireframe approaches w/ recommendation
    - UI / visual treatment --> 2-3 approaches
    - Implementation --> 2-3 API/architecture approaches
    - Shareout and review
- [ ] Hi-fi
  - Deliverables:
    - Interactive examples (Grommet Designer / Codesandbox / Design System site / Storybook)
    - Explore interaction behavior
    - Polish styling
    - Shareout and review
- [ ] Test
  - Demo, stakeholders
  - Demo, Bill Tipton
- [ ] Publish
  - Figma component
  - Grommet component
  - Design System site documentation and examples

**Comment by halocline** [comment]
10/11 - Shared progress update with Scott, Taylor, Kamlesh
  - Explored template formats
  - Discussed where we can keep record of deliverables for each phase so that they are easy to access and reference.
  - Began looking into possibility of using Github actions to automate appropriate issue creation (e.g. Closing an empathize issue triggers the automatic creation of a define issue, title + description + project board + assignee?)

**Comment by julauxen** [comment]
Hey @taysea I would say so
