### ISSUE TITLE
Figma Colors - Update all components within Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3008]
As i'll be publishing the new dark theme colors, we'll need to go through every single Figma file, accept changes and ensure colors have been correctly applied. IF there are any changes that didn't go through or see problematic issues, then we will have to manually go in and apply colors. Please create any necessary tickets if there are any issues so we can address them.

Please check off the following as you go through them:

- [x] TextInput
- [x] TextArea
- [x] FileInput
- [x] MaskedInput
- [x] Search
- [x] Lists
- [x] Button
- [x] PageHeader
- [x] Global Header
- [x] SelectMultiple
- [x] DataTable Customization
- [x] DataTable
- [x] Pagination
- [x] Card
- [x] Checkboxes
- [x] Radio Button/Group
- [x] Menu
- [x] Tip
- [x] Icons
- [x] Tabs
- [x] Name-Value List
- [x] Form
- [x] Notifications
- [x] Tags
- [x] Layer
- [x] Select
- [x] Wizard
- [x] Spinner
- [x] Anchor
- [x] Accordion
- [x] Stack?
- [x] RangeInput
- [x] Footer

**Comment by Keeth-HPe** [comment]
@Vicky @KennyAtHPE 
Updated and published all the components mentioned. 
We do not have a Figma component or file for Tags & stack, so I haven't checked them in the list. 
Also, [Data Table](https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-DataTable?node-id=1%3A2) includes various other updates, not sure if I should publish them. 

<img width="451" alt="Screenshot 2022-11-03 at 9 01 01 PM" src="https://user-images.githubusercontent.com/86280029/199764291-93748da3-cc3c-43b7-8558-5a2661c1a5f4.png">

**Comment by KennyAtHPE** [comment]
@Keeth-HPe  [Stack](https://www.figma.com/file/hX9HrBlvr6DTpUk2DSlikF/HPE-Stack-Component?node-id=0%3A1), [tags](https://www.figma.com/file/8zrInotU4JK9LWP4WyZy25/HPE-Design-System-Tags?node-id=0%3A1)

Also, good catch on the pending updates for DataTables, let's wait and see if @vavalos5 knows anything about those changes.

**Comment by Keeth-HPe** [comment]
Thank you, @vavalos5 Vicky. I've now updated and published Tags and stack ✅

Reg., the changes in the data table, I mean that,  if you go to *Libraries* and check the 'changes' made, you'll see there are 26 changes, which I'm not sure if it's the theme color update. 

<img width="444" alt="Screenshot 2022-11-14 at 11 20 37 PM" src="https://user-images.githubusercontent.com/86280029/201730843-d8416aaf-2546-4e31-b3df-f486cd37e80e.png">

**Comment by vavalos5** [comment]
I did see that. The new theme must've been applied. It looks aligned to me to the design system site. Go ahead and publish. Thanks for checking @Keeth-HPe

**Comment by Keeth-HPe** [comment]
Thanks for confirming on this @vavalos5. 
Closing this issue as all tasks are complete in this ticket.
