### ISSUE TITLE
Button - Update all components within Figma

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3009]
With the newly published Button Figma component, we will need to update our current components and templates that still contain instances of the old Button component.

The following components/templates within the "Library" section will need to be updated:
- [x] Form Templates
- [x] FileInput
- [x] PageHeader
- [x] Global Header
- [x] Menu
- [x] Layer
- [x] Sticker Sheet

**Comment by Keeth-HPe** [comment]
Hey @KennyAtHPE , I've updated all these current components and templates as mentioned, I'm going to find out if there are anymore components that needs the button update, meanwhile, it would be great if you could review, please. 
 (P.S, I haven't published these changes yet) 
 

- [ ] 1.  [Form Templates](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1)
- [ ] 2.   [FileInput](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=486%3A16254)
- [ ] 3.   [PageHeader](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2122%3A50932)
- [ ] 4.   [Global Header](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3028%3A58745)
- [ ] 5.   [Menu](https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=606%3A1489)
- [ ] 6.   [Layer](https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=0%3A1)
- [ ] 7.   [Sticker Sheet](https://www.figma.com/file/ItdN5pNBubFpV8GP5RowY3/HPE-Component-Sticker-Sheet?node-id=0%3A1)

**Comment by KennyAtHPE** [comment]
@Keeth-HPe left comments and pinged you on all the components/files that weren't checked.

**Comment by Keeth-HPe** [comment]
@KennyAtHPE Fixed all the comments. Thank you for the great-detailed review. Appreciate it🙌

**Comment by KennyAtHPE** [comment]
@Keeth-HPe Sweet, everything looks awesome. Please publish these components with a description and add to the changelog. Thanks!
