### ISSUE TITLE
DateInput - Support days of the week

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3016]
In the[ DateInput Figma file](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=980%3A18265), we received a message from Chandan asking if we can add days of the week on the calendar so it is easier for a user to understand what day they're picking along with the date. I think this is a valid request. Upon looking at Grommet and our DS site, we don't support it. I'm attaching a screen shot below and one of Carbon who supports the day of the week.

<img width="925" alt="Screen Shot 2022-11-14 at 5 11 14 AM" src="https://user-images.githubusercontent.com/62117454/201668686-3b6faa8f-ab04-4bdf-8c33-bb8379117982.png">
<img width="389" alt="Screen Shot 2022-11-14 at 5 06 22 AM" src="https://user-images.githubusercontent.com/62117454/201668691-b0875538-c501-4543-a2b2-79b59323bdda.png">
<img width="446" alt="Screen Shot 2022-11-14 at 5 05 57 AM" src="https://user-images.githubusercontent.com/62117454/201668692-b8700767-c46d-4380-8bd9-1d4f0de62742.png">

It would be good to:

- Connect with a developer to understand how this could be supported int he API and discuss how it will be implemented. 
- Update Figma
- Update design system site
- Follow up with Chandan

**Comment by vavalos5** [comment]
Great to know, thanks for linking @jcfilben!

**Comment by Keeth-HPe** [comment]
https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/yIz7w5Juq4ZUOZYvUTPYFX/HPE-Design-System-Components?node-id=212%3A578&t=XMOmlKtwG7RYWsf5-1
(created a branch of the main hope Design system figma file) 

@vavalos5 I've added the days of the week to the date input component. Please review.

**Comment by vavalos5** [comment]
It's coming along Keeth. I think you'll want to connect with a dev like @jcfilben to discuss some of the text styling and behaviors for the DateInput. I left some comments in Figma :)

**Comment by vavalos5** [comment]
Connected with Keeth this AM during designer check in and discussed the following:

- We need date input to have an icon swap, but Keeth to check w/ Jessica on the left and right carets. Specifically whether they’re buttons on Grommet?
- the days of the week - can we make an enhancements on Grommet since the color is `text-weak` and not accessible. Does it need to be accessible?
- She’s awaiting on Kenny for feedback

**Comment by KennyAtHPE** [comment]
Connected w/ Keeth and she suggested the following changes:



![Image](https://user-images.githubusercontent.com/86075038/214901543-8a1a3087-bd73-49ac-8482-c47ef90c6328.png)
Current implementation


![Image](https://user-images.githubusercontent.com/86075038/214901603-21dab665-927b-4abe-a630-6580ab13b9c6.png)
Due to accessibility issues, the days of the weak should instead be Text/Strong and a medium font-weight

**Comment by taysea** [comment]
I don't get any accessibility issues with color contrast with the existing text color/weight as it's implemented in grommet-theme-hpe. It seems like we shouldn't have to change it.

**Comment by vavalos5** [comment]
@taysea The current days of the week's text weight and color don't meet accessibility. I'm attaching a screen shot that show its fails at small and large t-shirt sizes.
<img width="478" alt="Screen Shot 2023-01-27 at 7 36 14 AM" src="https://user-images.githubusercontent.com/62117454/215126413-33f47a77-69b2-4124-8087-b0e0303a1bc8.png">

**Comment by vavalos5** [comment]
Actually, I just reviewed it again. It looks like keeth is using `text-xweak `on the text instead of the default` text `color. I was under the impression that the days of the week were text-xweak on Grommet. Agreed with Taylor, we should keep as is on Grommet and HPE theme.

**Comment by jcfilben** [comment]
> I don't get any accessibility issues with color contrast with the existing text color/weight as it's implemented in grommet-theme-hpe. It seems like we shouldn't have to change it.

The accessibility tools I tested with, weren't able to test the contrast on the color since it uses an opacity. The tools said manual testing was required for this/ Was this what you were getting too? If not which tool did you use?

**Comment by taysea** [comment]
> > I don't get any accessibility issues with color contrast with the existing text color/weight as it's implemented in grommet-theme-hpe. It seems like we shouldn't have to change it.
> 
> The accessibility tools I tested with weren't able to test the contrast on the color since it uses an opacity. The tools said manual testing was required for this. Was this what you were getting too? If not which tool did you use?
> 
I was using "WAVE" browser test -- we should confirm with manual testing then.

**Comment by jcfilben** [comment]
Looks like it is not passing accessibility
<img width="1033" alt="Screen Shot 2023-01-27 at 9 40 17 AM" src="https://user-images.githubusercontent.com/54560994/215143120-0538fe54-9024-4d61-8dae-67b065de8cdb.png">

**Comment by jcfilben** [comment]
It we move the opacity up to 72 we meet AA, 82 meets AAA

**Comment by taysea** [comment]
Thanks for confirming -- we should consider updating that color then to be accessible since we are using in areas that are supposed to be read. I'll take it as a note to look at with the Brand Refresh work to make sure the new color value will meet AA minimum.

**Comment by jcfilben** [comment]
> text-weak (if we aren't already using that) since that is more subtle, but still meets AA contrast requirements.

Good note, we are not currently using text-weak. We are using the default text color with an opacity of 50%. If text-weak is passing accessibility then I think it would make sense to switch to use that.

**Comment by taysea** [comment]
Gotcha, I don't see any [DateInput theme object ](https://v2.grommet.io/dateinput#theme) to adjust that -- is a grommet enhancement needed?

**Comment by taysea** [comment]
Grommet issue filed: https://github.com/grommet/grommet/issues/6610

**Comment by vavalos5** [comment]
Keeth has requested for feedback on her branch. I've left comments on her Figma file on some small changes to make. 😄 

@KennyAtHPE Please take a look as well. Ty

**Comment by vavalos5** [comment]
I chatted with Jesica this AM on the following:

Confirming the left and right arrows on the calendar are buttons, @Keeth-HPe can we change this.

Discussed whether the DateInput header should be a header or bold text? Jessica looked at a few other DateInput components in other frameworks and are not using headers. @ericsoderberghp We would like to get your thoughts on this and engage in a conversation if needed.

Discussed whether we should add t-shirt size `small `and `large` to Figma  as options to make the components match more closely to the grommet component. @ericsoderberghp what do you think?

**Comment by Keeth-HPe** [comment]
Hey @vavalos5, Thank you for te feedback!

We'll have to work on the button component for this. 

The button component does not have an icon swap property. I'll update the button component first and then include the changes to the calendar component.

**Comment by ericsoderberghp** [comment]
I think the Calendar should use a Header as the container but agree with using Text instead of Heading for the text content.

I think having t-shirt sizing for Calendar in Figma would be a good alignment with grommet.

**Comment by vavalos5** [comment]
@Keeth-HPe Can you help us by providing updates on this ticket and where you currently are please. Please connect with @SOjaHPE too. Thanks!

**Comment by vavalos5** [comment]
Thank you for making the changes Keeth. I'm noting down next steps:

- due to button having some complications, in particular to the icon swap property (Kenny is trying to work on fixing that) we may have to hold off on the left and right caret buttons for now.
-  in the mean time, please add t-shirt sizes `small` and `large `as a variant. Connect with @jcfilben along the way to ensure we're in alignment to the Grommet components.
- in addition, please also review the comment i've left in your Figma file. Work with Jessica to ensure your containers are as closely aligned to that in the code.
- Remove h3s and utilize text-bold closest to the current heading sizes (see my notes in Figma)
- In general, ensure all of your containers are aligned to the code, work with Jessica on this
- Once you feel you are at a good place, feel free to tag me again. Keep Scott in the loop by either writing updates here or directly to him on Slack. Let us know if you have any questions.

@SOjaHPE FYI

**Comment by KennyAtHPE** [comment]
Related ticket #3133

**Comment by vavalos5** [comment]
@Keeth-HPe Please let me know if you had a chance to take a look at next steps and whether or not if you have any questions.

**Comment by Keeth-HPe** [comment]
@vavalos5  Yes! 
My apologies, I could not connect with Jessica Friday, it was too late for me. 
Today I met with her early and we discussed all the details mentioned by you that have to align with the grommet.
I will make the changes and send it for review.
I have no questions. Jessica gave me good clarity. 👍

**Comment by vavalos5** [comment]
Keeth has begun creating the DateInput component in size small. 😄 @Keeth-HPe Let us know if you feel like this can be completed by Tuesday or if you for-see it taking a little longer.

**Comment by KennyAtHPE** [comment]
After discussing with @Keeth-HPe , we are scaling the scope back a bit so that this ticket may be closed by the end of the sprint.

Next Steps:
- [ ] Finalize Default variants only
- [ ] Review w/ Kenny and Vicky
- [ ] Create a new ticket for any additional variants (small, large, etc.)

**Comment by Keeth-HPe** [comment]
@KennyAtHPE Thank you for helping in updating the ticket. 

I have updated the Default variant of the calender. Request you'll to review @vavalos5 @KennyAtHPE

**Comment by vavalos5** [comment]
Thank you Kenny for updating ticket. I will review today @Keeth-HPe

**Comment by vavalos5** [comment]
Fantastic job @Keeth-HPe Thank you for making all of those changes. It looked good to me. I left the tiniest of comments on your file. But this is good to close and publish.

Before you do close, please create a follow up ticket to implement sizes small and large to the designs. Please add that ticket number to this ticket and add this ticket number to the new ticket. Let me know if you have any questions.

**Comment by vavalos5** [comment]
@jcfilben Can you add a ticket to our backlog please. :) 

@Keeth-HPe in Figma, I removed the red border, background and rectangle applied to the completed sections. Great job!

**Comment by jcfilben** [comment]
Grommet follow on ticket: https://github.com/grommet/grommet/issues/6637

**Comment by vavalos5** [comment]
DateInput follow up ticket to add small and large variants #3145
