### ISSUE TITLE
Card - update with CTA button variant

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3017]
Revisit the Card Variant CTA figma component and update it to use the newly created figma CTA card component which has been released. This will provide parity between the rebranding assets and UI toolkit components available to designers.

- Need to review and see if there are other changes that need to be made to the first pass MVP card variant components
- Reassess the proposed card study, what has changed the past two week? We should review it and adjust accordingly

## Deliverables

- [x] include an example on the design system site

**Comment by vavalos5** [comment]
I've updated these in Figma.

@taysea was this something you were thinking of updating on the DS site this sprint?

**Comment by taysea** [comment]
> I've updated these in Figma.
> 
> @taysea was this something you were thinking of updating on the DS site this sprint?

I can update the CTA card examples.

**Comment by taysea** [comment]
Reopening so we don't forget next week -- Figma button still needs to be updated to use the CTA primary button.

**Comment by vavalos5** [comment]
Although Card components are not published in Figma, the Cards do have the CTA primary button. Only change needed is to replace the arrow within the button to the HPE element logo. On my list and will be updated soon.

**Comment by vavalos5** [comment]
done

**Comment by taysea** [comment]
@vavalos5 I just reviewed the Call to action card and it does not look like the correct CTA button. The dimensions are not aligned to the theme (should be 36px tall). Is there a reason we aren't just using the CTA variant that our Figma button offers? That one seems to be the correct dimensions.

**Comment by vavalos5** [comment]
Hmm.. I'm using the Figma button we have published. It just was set at Large by default for some reason but its not at our medium 36px tall.
