### ISSUE TITLE
Layer - common modals

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3019]
## Description
The first pass at this work is to provide guidance making recommendations to address known issues that prompted Ezmeral/GLCP/Storage to create their own design pattern guidance to ensure a consistent implementation for dialogs/panel drawer layers.   Currently there is nothing.

They did their dialog pattern work to keep the gaps, button alignment, keep size, font size, padding consistent. Could be solved by simple guidance. Full page of guidance about modals and side drawer panels.

Quick win.. we need to follow up w/ Sandmid with his work with Sandbox dialog contribution.

## Deliverables

- [ ] MVP is to deliver a full page of guidance with recommendations: https://github.com/grommet/hpe-design-system/pull/3040
- [x] review https://github.com/orgs/grommet/projects/10?fullscreen=true&card_filter_query=layer for potential aspects to consider. Have tagged issues PR 3028 takes care of in the PR description, and dragged things we should tackle next into Next Active.
- [x] Evaluate whether a grommet component should be created: It seems like Layer component could be extended with a `title`, `subtitle`, and `actions` props that would opt the user into some specific themed behavior that can be theme driven (typography sizing, spacing, padding, etc.). I don't necessarily think we need to create a new grommet component.

**Comment by taysea** [comment]
For next sprint: https://deploy-preview-3030--keen-mayer-a86c8b.netlify.app/components/card#misuses

**Comment by taysea** [comment]
Carrying this ticket into next week.
