### ISSUE TITLE
Typography - refresh weights and sizes

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3020]
Coordinate with Chris and Joelle on updates to the typography weights and sizes to align with new brand direction.

[Chris's Typography exploration](https://www.figma.com/file/Ceilu1kjl81OE8FMwz12op/HPE-Unified-Campaign?node-id=1056%3A20774&t=4oIS6tmwrepLBZj0-0)

[Vicky's Figma Typography Explorations](https://www.figma.com/file/gc3XXwjDdxUicFlfiId2Tb/Typography-explorations?node-id=0%3A1&t=mcs8FgJpMdBmWUnC-1)

[Product screenshots file](https://www.figma.com/file/MpEsy69KugjW4xYzaVp1ND/Typography-impact-evaluation?node-id=0%3A1&t=UVzjoWVr3KKGAk2N-0)

## Deliverables

- [x] create a new HPE theme on a branch
- [x] evaluate with existing products
  - [x] [Design System site](https://deploy-preview-3030--keen-mayer-a86c8b.netlify.app/)
  - [x] [GLCP](https://www.figma.com/file/MpEsy69KugjW4xYzaVp1ND/Typography-impact-evaluation?node-id=18%3A87&t=3Z4M9pX6FO1Xf8Vv-4)
  - [x] [Ezmeral](https://www.figma.com/file/MpEsy69KugjW4xYzaVp1ND/Typography-impact-evaluation?node-id=10%3A28&t=3Z4M9pX6FO1Xf8Vv-4)
  - [x] [Compute Ops Manager](https://www.figma.com/file/MpEsy69KugjW4xYzaVp1ND/Typography-impact-evaluation?node-id=1%3A107&t=L0zkRIFkZCOZJBCl-4)
- [x] HPE theme release (minor/major?)
  - The combination of font weights, colors, sizing, and line-heights result in significant visual changes, potentially layout changes, and will require teams additional work to adjust things like `<Text weight="bold" />` to bring into alignment, I think we should treat this as a major version bump with a migration guide.

## Summary of changes
- **Overall** - Move away from bold, shifting to thinner weights, for a lighter, more sophisticated presentation.
- **Text colors** - shifting slightly, up (down?) the greyscale anchoring at a dark grey instead of absolute black.
- **Font sizing** - Sizes are fairly similar, have tweaks in large/xlarge sizes, and lessened line-heights throughout.
- **Heading line heights** are the same as their font-size, allowing for tighter presentation, particularly in marketing contexts. —> Likely will impact content layouts requiring tweaks to gap values. —> Implementations using margin and padding for content alignment are likely to experience the most impact.
- **Font-weights** change based on font size (e.g. a large font may have a 300 weight, but smaller fonts bump up to a 400). —> Will require enhancements to Grommet to accommodate greater specificity.

## Questions
- Do `text-weak` and `text-xweak` values need to be adjusted to play better with new `text-strong` and `text` values?
- **FormField text styling** - probably should bump weight down for label and input value. Input value color and placeholder color are too similar when at lighter weight. Use new `text-strong` for input value color?
- Do border colors need to be adjusted to play better with thinner font weights?
- Current border colors were recently made with opacity. This causes issues when borders overlap such as in Accordion where adjacent panel borders appear darker than edge panels.
- Re-calculate maxWidths for paragraph sizes?
- Chris is introducing a new type of typography “quote (e.g. positioning statement),” is this a typography type we want to add to Grommet?
- Icon colors
- Is the text legible on `background-back`? Does it need more contrast?
- What do disabled states look like? Is there enough differentiation?
- Informational text looks too washed with `background `color. Would be even more muted on `background-back` color.
- Would we resize icon strokes to align more with the new text weights?
- Given the fact that font stroke is thinner, should we increase padding between inputs to create more visual space between elements for readability? Right now with the new text stroke applied, it is hard to identify labels on inputs within a form.
- Inline notifications such as ones you'd see at the bottom of a form would not be accessible due to the `font-size` being size `xsmall`. The validation color against `font-size ``xsmall `makes is not accessible.
- What text styling would we apply to x number of items below a search box within a DataTable? Would the new medium text-weight be as prominent as the bold used to be? Would that be more prominent, resulting in dismissing the description next to the x number of items?
- Does the new text-weight make it even more difficult and less legible to follow data within a row in a DataTable?
- This could just be my opinion but when comparing the headings heavier weight, it makes all other content on the page, especially form fields look disabled.
- #F6F6F6 is not accessible when applied above the following colors: primary orange, secondary purple, primary yellow, primary blue, status- warning, status-critical, primary-teal(small-text), primary-green(small text). Not that it affects a lot of work, but it does affect the visual we've annotated utilizing some of these colors which use the current default text color.
- Along with Matt's comment on border color adjusting, should we also adjust the border weights to better align with the text-weights?
- When it comes to the Name-Value List component, will the Name be as prominent as it is now in comparison to the Value with the new text-weights? TBD
- Description text within an input is too similar to the label. Not as much hierarchy as there used to be.

## To implement in theme and evaluate

- [x] Heading
- [x] Paragraph
- [x] Text
- [x] FormField
- [x] Anchor --> No theme changes. May want to explore bumping weight down from 500 to 400 and/or darkening color on hover state.
- [x] Accordion --> No theme change applied.
- [x] Button --> Bumping default weight down to 500 to experiment (leaving primary as bold). Recommend that we also look at button as a separate scope of work, since Chris's Figma file shows a variety of changes and sizing.
- [x] Menu --> Dependent on default and option buttons.
- [x] Tabs
- [x] Tip --> No theme change applied.
- [x] PageHeader --> No theme changes, but may want to consider adding `color="text-strong"` to the ReverseAnchor in the `parent`. Alternatively, we may want to consider extending `theme.pageHeader.parent` to have either `font` or `extend` as a child property it accepts any box props.
- [x] Pagination
- [x] DataTable
- [x] NameValueList
- [x] Tag
- [ ] FileInput

**Comment by halocline** [comment]
Apparently the typography direction is recommending two font scales:

One for web (larger)
One for product (smaller)

If we are going to be supporting multiple scales, we might want to consider a new theme repo for `grommet-theme-hpe-web` or something along those lines. This could be a const `hpeWeb = deepFreeze({ // font size overrides }, hpe);`

**Comment by ericsoderberghp** [comment]
Or, one repo/package but with two exported themes: `hpe` and `hpe-web`?

**Comment by halocline** [comment]
**Based on impact evaluation, here is a summary of items to resolve**:
- [ ] Recommendation for how to handle to typography scales (i.e. web scale & product scale) --> Support a `grommet-theme-hpe-web` which overrides font sizes but inherits everything else? Treat buttons similarly?
- [ ] Finalize the 'product scale' for the font sizes. Still seems in flux and should be examined closer.
- [ ] Figure out a plan for how to resolve issues like `<Text weight="bold" />` now no longer fitting as well with majority of font weights. Use a non-standard font-weight mapping (e.g. map 700 weight to HPEMetricMedium; 900 to HPEMetricBold, etc.)?
- [ ] Make recommendation regarding text grey-scale if needed for better contrast, especially when presented on validation colors, background-back, background-contrast, and other colors (e.g. a colored card on a dashboard)?

**Comment by halocline** [comment]
> Or, one repo/package but with two exported themes: `hpe` and `hpe-web`?

Good call.

**Comment by taysea** [comment]
Next steps:
- [ ] Matt to summarize current state of work based on discussions from right before winter break
- [ ] Matt to publish demo branch of Design System site with web + product type ramps
- [ ] Schedule kick-off session with Chris (discuss plan of action below, incorporate any of Chris's thoughts into plan etc.)
- [ ] Internal collab session (Matt, Taylor, Vicky, ...) with new product type ramp applied to Design System site examples: take screenshots of any problematic examples (e.g., inputs in row with buttons potentially)
- [ ] Collab session with Chris + team (Joelle, ...) to share what's working/what's not, discussion, etc.
- [ ] After collab session with Chris + team, determine next steps

**Comment by halocline** [comment]
**Notes from kick-off with Chris:**

Motivations:
- Tighten up spacing in product experience
- Simplify by reducing choices
- Have typography sizing be based on viewport context. Per context, headings, paragraphs, and text should all scale proportionately.

Thoughts/ideas:
- Proposed viewport contexts: desktop, tablet, mobile
- Organisms and molecules such tables, cards, menus, lists, page headers, ... , should have typography which also scales
- Desire to reduce the number of text size options for HPE so that we minimize misalignments ---> Figma, reduce values available; code, hpe theme maps xxl-6xl --> large, xxsmall-xsmall --> small? eslint-hpe rule for no use of size prop?

**Comment by halocline** [comment]
**Friday (1/6/23) status update**

- ToDo: Monday, schedule internal collaboration session with @vavalos5 , @KennyAtHPE , @taysea , @halocline to go through preview deploy of the DS site and identify any points of friction with the product type ramp.
- I think a successful outcome of this sprint is to deliver an impact assessment for the proposed product type ramp, which includes a list of ToDos needed if we accept the proposal as is. This should inform and set up our future scope(s) of work and provide an idea of whether this work is Sm/Med/Large/XL.

Defined as an assessment, sprint confidence rating is 🟢 (green).

**Comment by taysea** [comment]
Friday 1/13/23 status

- Progress has been made on collecting the majority of screenshots in preparation for a Tuesday meeting with Chris's team. We are on track to complete by Tuesday.
- To do: Finish gathering screenshots for Wizards and Dashboards

Final step:
- Meeting with Chris and his team on Tuesday to gain shared understanding of impact of typography changes

**Comment by taysea** [comment]
We demoed the friction areas captured in this [Figma file](https://www.figma.com/file/27PoHGdweJLEhfmbEDCMQ8/Typography-Assessment?node-id=0%3A1) to Chris and his team.

Key takeaways:
- Shared understanding of the difficulties with switching from 24px line height for default text to `20px` -- highlighted in screenshots
- Discussed potentially taking an "incremental approach" to adopting the new brand direction. The "first step" might include: 1) new heading sizes and weights, 2) new font colors, 3) a "tightened" up scale across sizes for paragraph while still keeping 24px baseline, 4) extending Grommet's typography components to be more "viewport aware" and able to scale accordingly

Next steps:
- [ ] Create branch of HPE theme that demos theme with all changes except changes to paragraph/text sizing
- [ ] Apply theme branch to DS site to be able to do a side by side comparison with the [current deploy](https://deploy-preview-3074--keen-mayer-a86c8b.netlify.app/) and send to Chris for review
- [ ] Chris will then need to determine what is the final "on brand" criteria and we will need to make necessary grommet/theme enhancements accordingly

Other areas of discussion for separate consideration:
- How might we make it easier to adapt typography sizing changes in "Button-like" components (Select, Menu, etc.) without being bound to the `19px` label size required for primary buttons with HPE green background?
- Should we consider an "inline button" kind that doesn't have any padding and aligns with the typography sizes

**Comment by halocline** [comment]
☝️ Edited the above comment with additional detail and notes.

**Comment by halocline** [comment]
https://github.com/grommet/hpe-design-system/issues/3102 represents the remaining work. All status updates should be followed there.
