### ISSUE TITLE
JAWS Inspect - evaluate

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3021]
Setup and evaluate JAWS inspect tool

Deliverables:
- [x] setup jaws
- [x] test with some storybook stories
- [x] test on DS site
- [ ] put together quick overview report of problem areas in grommet with JAWS and differences between voice over. Report doesn't need to be super in depth. Goal is to get 'lay of the land' for grommet JAWS support. Create issues as needed.

**Comment by jcfilben** [comment]
I tested JAWS on the following:

- [Design System Home Page](https://design-system.hpe.design/)
- [Design System Components Page](https://design-system.hpe.design/components)
- [Grommet site Home Page](https://v2.grommet.io/)
- [DataTable Clickable Story](https://storybook.grommet.io/iframe.html?args=&id=visualizations-datatable-clickable--clickable-data-table&viewMode=story)

JAWS:
- Calls out main region of the page
- Didn't read the image or some of the icons on the DS homepage
- More strict about reading aria-labels (won't read them if they are not placed on landmarks or interactive content). Lots of places JAWS didn't read icons or images.
- Refers to icons as graphics
- Lets user know they are entering a code editor and gives them accessibility options.

JAWS DataTable:
- No indication of current column or row
- No indication rows are clickable
- No indication of empty rows
- No indication of meter
- Can move through rows but not read out

VoiceOver:
- Doesn't call out main region
- Read the image on the DS homepage
- Reads the name of icons, but doesn't give an indication that they are a visual element
- On the DS components page the images in cards were not read
- No indication to user that they are in a code editor

VoiceOver DataTable:
- Column and row read out
- Meter is read as image without conveying a value
- Slight indication rows are clickable (beginning of table says ‘no selection’)
- Unable to move through rows

Both:
- No pause between reading card heading and card content
- Ignored the video on the DS homepage
- Unclear that examples within the cards on the components page are just visual examples and not part of the page. (Footer card example reads as an actual Footer)

DataTable both:
- On click row, no indication of layer opening


Additional Notes:
Different screenreaders interpret the page differently. A screenreader will look for different aria tags or placement than another screenreader. This leads to a page or component working well in one screen reader but not another. The only way to ensure accessibility is to test with multiple screenreaders. As we incorporate JAWS testing into our development process we can gradually increase our knowledge of what each screenreader expects.
