### ISSUE TITLE
ANDI - evaluate

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3022]
Spend an hour or two doing an evaluation of https://www.ssa.gov/accessibility/andi/
Decide whether there's something we should be using it for.

## Deliverables

- [ ] document findings in this issue
- [ ] create new issues as needed

**Comment by jcfilben** [comment]
## Evaluation Comments

I think that ANDI goes more in depth and tests more than tools like Axe DevTools or our storybook accessibility plugin. This tool is easy to setup and very quick to run and traverse through. I could see our team using this tool to get a quick idea of the accessibility of a page or component before going more in depth with screenreader testing.

Pros:
- easy setup
- helpful guides and additional info
- more in depth than other browser plugins for accessibility

Cons:
- Pages with Content Security Policy rules need to explicitly allow ANDI to run
- There were some issue that axe devTools caught that ANDI didn't and vice versa

ANDI has a few more features than the typical browser accessibility testing tool. Some of the unique features include:

### **Focusable element evaluation**

This tool gives a warning if there are any elements on the page that are hidden from a screenreader user. There is also a feature to show the tab flow of the page. In the screenshot below the tab order is indicated by the yellow box with a number
<img width="1296" alt="Screen Shot 2022-12-12 at 10 00 59 AM" src="https://user-images.githubusercontent.com/54560994/207107205-e9020025-c392-4b9c-843a-ad470bf23be1.png">
There is also a keyboard accessibility warning if there is an element on the page that is expected to be intractable and there isn't a way for a keyboard user to interact with it.

Similar to the tab order tool, you can also view the reading order of the page.
<img width="1208" alt="Screen Shot 2022-12-12 at 10 26 56 AM" src="https://user-images.githubusercontent.com/54560994/207112679-f730e27b-c8ac-4f71-bdfc-fd04f560fa62.png">

### **ANDI warns you if you have links with the same name on a page.**

### **Structures visualization**

Although other tools have a similar feature to display the heading structure of a page I liked how ANDI points to and highlights the heading on the page when you hover over the heading in the list.
<img width="1792" alt="Screen Shot 2022-12-12 at 10 05 53 AM" src="https://user-images.githubusercontent.com/54560994/207108308-2cbd1008-c67a-4793-864f-284f07d6b023.png">

### **Contrast Playground**

ANDI has a tool to experiment and test the contrast of different colors

<img width="424" alt="Screen Shot 2022-12-12 at 10 09 24 AM" src="https://user-images.githubusercontent.com/54560994/207109090-2c6fa7d3-4a45-42fb-8a95-9b96ac5f0b71.png">

### **Additional Info**

Clicking on a warning will open a separate window with additional details. From here you can navigate to additional tutorials, alert info, faq's and more.

<img width="1011" alt="Screen Shot 2022-12-12 at 10 11 01 AM" src="https://user-images.githubusercontent.com/54560994/207109420-08743f35-a32b-44b9-a784-993d621b4b96.png">
