### ISSUE TITLE
Layer - Create updated Figma component

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3031]
Create and publish a Figma component that should:
- [x] Enforce consistent padding, gap between header/body/footer, elevation, rounding, title typography, subtitle typography
- [x] Allow for flexible body content
- [x] Allow for flexible footer actions

**Comment by taysea** [comment]
Here is an exploration I started where the container enforces spacing between regions, rounding, elevation, typography but the content area is flexible: https://www.figma.com/file/EXCZSi7csDXNo8d2evSEhc/Layer-Test?node-id=0%3A1&t=tkhLOv2F1Pwz3qm5-1

**Comment by KennyAtHPE** [comment]
V1 of the component can be tested [here](https://www.figma.com/file/EXCZSi7csDXNo8d2evSEhc/Layer-Test?node-id=43%3A56446&t=a18m73BsGzXMJP8t-1)

**Comment by KennyAtHPE** [comment]
Few updates:
- Created a different version where each layer type has its own component.
- Added new informational and actionable variants for each layer type
- Added additional variants for footer actions (3 button group)
- Updated placeholder text

**Comment by KennyAtHPE** [comment]
The Layer component will be broken into 3 separate components: side drawer, center layer, and fullscreen layer (does not include wizards). Relevant metadata will be added to these components as well. 

Components have been finalized, here are the [next steps](https://github.com/grommet/hpe-design-system/issues/3064). Closing out the ticket.
