### ISSUE TITLE
Data - create unit tests

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3036]
Add unit tests for `<Data />` and related components as part of https://github.com/grommet/grommet/pull/6343.

## Deliverables

- [ ] unit tests covering all properties to 85% statement coverage, green bars

**Comment by ericsoderberghp** [comment]
Current coverage:
<img width="1127" alt="Screenshot 2022-12-08 at 10 56 21 AM" src="https://user-images.githubusercontent.com/11637956/206543045-9d183227-ad34-4bdd-af73-cc7ef744e0aa.png">
<img width="1127" alt="Screenshot 2022-12-08 at 10 56 49 AM" src="https://user-images.githubusercontent.com/11637956/206543137-e25203fb-5c7d-40ed-bbcc-49fb684c6d37.png">

**Comment by jcfilben** [comment]
Updated test coverage from the tests I pushed up yesterday
<img width="1776" alt="Screen Shot 2022-12-09 at 11 30 46 AM" src="https://user-images.githubusercontent.com/54560994/206768920-4c787786-5920-4e04-88ef-6af54041b307.png">

<img width="1773" alt="Screen Shot 2022-12-09 at 11 31 30 AM" src="https://user-images.githubusercontent.com/54560994/206769004-b43bd2f2-5a5b-47ad-98e5-8433e693b4b9.png">
