### ISSUE TITLE
Clean up design system dependabot issues

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3050]
Address the warnings identified by dependabot:
https://github.com/grommet/hpe-design-system/security/dependabot

## Deliverables

- [x] no issues identified at the URL ^^^

**Comment by britt6612** [comment]
https://github.com/grommet/hpe-design-system/security
There is no dependabot issues listed here

**Comment by ericsoderberghp** [comment]
Hmm... I'm still seeing things listed here: https://github.com/grommet/hpe-design-system/security/dependabot

<img width="809" alt="Screenshot 2022-12-12 at 3 44 09 PM" src="https://user-images.githubusercontent.com/11637956/207183571-753b6850-72ef-45ff-85ad-dcd109df6ad2.png">

**Comment by britt6612** [comment]
strange that link doesnt come up for me good to know why I commented though maybe Im not on a certain setting we can connect tomorrow

**Comment by britt6612** [comment]
In `aries-core` the following were upgraded:
```
    "@storybook/addon-actions": "^6.5.15",
    "@storybook/addon-links": "^6.5.15",
    "@storybook/addon-storysource": "^6.5.15",
    "@storybook/addons": "^6.5.15",
    "@storybook/react": "^6.5.15",

```

In `aries-site` the following were upgraded 
```
    "@applitools/eyes-testcafe": "1.17.4",
    "@testing-library/testcafe": "^5.0.0",
```

in main `pageage.json` the following were upgraded
```
  "@babel/eslint-parser": "^7.19.1",
    "eslint": "^8.30.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.11",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^2.8.1"
   "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "styled-components": "^5.3.6"
```

**Comment by britt6612** [comment]
The following steps will be to upgrade the remaining packages
https://github.com/grommet/hpe-design-system/issues/3063
