### ISSUE TITLE
Deprecate aries-core

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3067]
`aries-core` is not needed anymore. In the early stages of the Design System we were exploring having an HPE specific component library but we've since decided to rely on Grommet. Given this, we can remove `aries-core` as it may only cause confusion to people looking at our documentation.

Deliverables:
- [ ] Transfer "Identifier" and "AppIdentity" patterns to `aries-site` templates
- [ ] Update any import statements for the above to point to the new paths
- [ ] Delete `aries-core` directory
- [ ] Update README to remove references to aries-core

**Comment by halocline** [comment]
FYI, discussions have re-emerged speaking to the potential value of using aries-core as a better repository for component re-use. Components living here might be proofs of concept, alpha or beta versions where utility is being explored and may eventually "graduate" to Grommet, opinionated or too narrow to belong in Grommet.

**Comment by ericsoderberghp** [comment]
How would it differ from example components? Would it work to pull into that, instead of having a separate package?

**Comment by halocline** [comment]
More of an organization mechanism to encourage greater re-use, discoverability, clarity of purpose and where they are used and consumed. Give them more formality. Examples would consume them.

It would also serve as a mechanism to keep the site focused strictly on content and content presentation, while allowing aries-core to serve as a dedicated home to templates and patterns. Folks will make changes to these focussed on a particular example, not considering all the other places in may be consumed. WIth the current site project structure, they tend to get buried, lost, forgotten, then reinvented, etc. 

We could move them to another directory within aries-site. However, this seemed like it might make things nice and clear, focussed, etc.

**Comment by taysea** [comment]
Closing, using this for accessibility testing and reusable patterns.
