### ISSUE TITLE
Page Templates - plan and explore

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3071]
[Figma File
](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5052%3A22410&t=eVhKM38wJB2VM9aV-1)
## Problem Statement

Designers and developers would be able to deliver faster and more consistently using detailed, design system aligned page templates that could be copied and pasted.

## Pain Points:

How might we provide designers page templates that could be easily utilized quickly within Figma for their designs?

How might we determine the correct taxonomy for each Page Template type so our users can quickly find and utilize them?

How might we determine which Page Template(s) should be prioritized based on needs?

How might we provide visual examples to show them useful information when creating page layouts?

## Deliverables

- [x] update this issue's description with any interesting further details and planning steps
- [x] review existing screen catalogs from prior Page Layouts work
- [x] collect and catalog potential pages from Chris, Gina, and Justin, Sylvia, Amanda, Megan and Diane
     - [x] Set a call with Eric, Chris, Gina and Justin to understand what they're expecting from Page Templates, their mental list of 
             prioritization, apply RICE Modal, and which template would have the biggest impact
     - [x] understand how page layouts are currently being utilized and gather other pain points
     - [x] determine which layouts are most commonly used and which one take priority over others
- [x] determine how many templates to provide in the first round (about 2-3)
- [ ] give each a meaningful name and key purpose 
- [x] once we've narrowed down, share w/ stakeholders and gather any feedback
- [x] share with a dev and discuss
- [x] share with team

## Future Next Steps

 - [x] connect w/ Kenny/Greg to previous taxonomy study conducted to understand steps taken
     - [ ] collect taxonomy internally of how people are calling layouts
     - [ ] collect taxonomy of external frameworks, NNG, etc.. of how they're naming layouts
     - [ ] with a developer, collaborate on creating a list of commonly used taxonomy based off of findings
     - [ ] create a study based off of findings to collect more insights
     - [ ] connect w/ research team to gather input

- [ ] explanation on how to use/guidance
- [ ] create follow-on issues to implement the templates and guidance (likely different single column layouts building within Figma as a next step/ticket)

## Some Questions

- Are we looking to create page templates as components where they can be swapped in the instance panel?
- What about for different resolutions? Confirmed with Scott, yes. Eric said no, not at this moment but sometime later on.

## Summary of Findings

In the Figma file, I was able to determine the top 3 most commonly used page layouts : 1 column, 2 column, and 3 columns. There are some examples of how content may be laid out based on use cases gathered from GLC, Compute, and Storage. It is even broken down further by:

- clusters: examples of dashboards with 2,3,4 columns
- 1-2 column wizards
- 1-2 column lists, datatables and charts

Lastly, the [2 column dashboard example is broken down to 3 different page templates](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=2360%3A18885&t=eVhKM38wJB2VM9aV-1): simple, with nested grids and an other.

**Comment by vavalos5** [comment]
Today was spent chatting with Chris, Gina and Justin to collect use cases and pain points. Please see notes below:

**Eric:**

“We’re cataloging and grouping on what the key things are for.
We’re collecting some web and product designs as of right now to just get a better understanding of what is going out with other teams
Capture just the designs - more of the ladder, can we come up with a place we’re going to, enough detail of its viability
For now its where do we need to go and if we need to add or change components to Grommet then we will do that

**Chris:**
Shared examples of some layouts he’s recently worked on
Justin will have a more accurate layout of the cards and Gina may have a better accurate layout of the list view
Hub page is common, some form of list, there might be some form values and details, take into consideration when there are thousands of tasks on a list, is a list or a card view better? It would be good to consider that
Chris is trying to boil it down templates into these buckets that  accommodate the experiences
Making sure as we walk through a hub to a list to a detail are we hitting the right beats, are they going to satisfy the right needs, where does the flexing need to be to help us to give a variety without having to make too many templates
AI, brand elements, general types of templates

**Gina/Justin:**

One of the problems we often see within services is Navigation - how might we simplify some of the layouts so we don’t feel the need to have everything in one view like the Cloud Services screen
Typography would be good to look at as well - Gina shared screens where she changed the headers from our text-strong color to a grey so it isn’t so harsh. She also changed the name-value pair styling
How do we change the behavior of where grids and layouts are better used?
IF DS is too prescriptive, we need to be able to be flexible based on the content so UX Designers can best leverage layouts.
What’s the best way to avoid designers from interpreting the templates DS creates differently over time?
What are some areas where we are failing at providing great navigation and letting the user know where they are? ( See Dashboard example Justin shared)
Why are we wasting so much space? Why are we center aligning everything?
Responsiveness is not great as you get down to smaller screens. For example, cards are not fluid and rather stay the same width through out each size.
What would we want to show?

I've also already started capturing a variety of screens of different layouts from GLCP, Compute.

Started categorizing them by 1 page, 2 page, 3 page, 4 page layouts

Awaiting screens from Diane, possible others from Sylvia, Amanda and Megan.

**Comment by vavalos5** [comment]
Based on the conversation I had with Chris yesterday, it sounded like we were both on the same page about the idea of providing our designers with simple layouts to provide services with flexibility. Over time, we can build upon these layouts. Adding a screenshot of something he's been working on:



![Image](https://user-images.githubusercontent.com/62117454/211923603-df27ccad-a9a0-4ae1-8689-9773d36caecb.png)


In addition, i'm adding a screen shot of the RICE model i've used to determine which top 2 designs we should focus on. Please see screen shots below.

![Image](https://user-images.githubusercontent.com/62117454/211921593-ff47d8bf-50c9-4dfd-87bc-397f1d6727eb.png)

**Comment by SOjaHPE** [comment]
Comments about Chris C's list of templates above - the ask is for simple templates - common principles and view requirements

**Comments about each of the Template Types**

1. **Login/Access** - This user flow and underlying page layout is being designed/validated in the current GLCP Sign-In design sprint - We can work w/ the final artifacts, adding necessary hooks and target containers into the template for specific placement assets. We should make sure to be included in some sprint design reviews to stay on-top of the progress. Chris C. is working with Diane L with this page.

2. **Dashboard/home/landing** - This page layout is pretty straight forward, just need to provide support for a variety of column #'s / container layouts we'd recommend
- DS devs have many engagements supporting the coding of these page types. Outside of last year's dashboard template work that Aditi did and Eric's Wellness dashboard the other page inventory covers much simpler catalog, services landing pages. An arrangement of sections housing different collections of navigational cards / other card types.

3. **List/Inventory/Entries/Categories** - homogenous lists of objects/entities
- Main content region usually display data collections
- Depending on the # records, or how the workflow designed their page to manage the above objects
- Users will rely upon a combination of filtering, sorting, searching functionality to narrow down # of objects - they will use batch actions, toolbar/row level CRUDE actions

4. **Detail/Object/Instance/Data/Service/Product** - the size and scope of different objects are very different
- Vary from simple to complex object details
- Complex objects could have nested tables of child objects and require inline tabs to break up the different facets or dimensions of an object

5. **Layers** - These are secondary content container templates -  they have been overall defined with Taylor's layers component work. Different layouts for full page create/edit, and wizard flows might need exploration.

**Purpose of each page** - It is hard to think about any product page in a stand alone context, it would help to think of how user's access these pages. String them together to form page flows.. task flows. When you frame them in that mental flow context you'll be able to start assigning the purpose of what each screen provides. It is possible that some pages have a mixed purpose based on the contents of the page regions.

**Card Sorting Exercise** - If needed in the next sprint to further understand the purpose of each screen and help w/ taxonomy, Vicky and I discussed a quick card sorting exercise. It could be really hands off, create a board and duplicate it. Expectations and introduction can be provided in a quick video of instructions how to do it. Provide testers a URL, can be un-moderated.

- Empty buckets w/ names of screen types, testers would drag and drop them into the buckets
- Ask users what they perceive the purpose that page
- They would be provided cards if they want to propose another name for a bucket

**Comment by vavalos5** [comment]
@ericsoderberghp @SOjaHPE Ok for us to close this ticket?

I've created a follow up ticket on next steps:

Next Step Ticket: Taxonomy Card Sorting Study #3092 

Currently i'm working on a FigJam file for the card study exercise with steps.

**Comment by ericsoderberghp** [comment]
Can we work on building out the first template without waiting for the card sorting exercise?

**Comment by vavalos5** [comment]
In parallel to the card study ( ticket #3092) , I will be working on ideating on a dashboard template ( ticket #3098 ).

Scott, Eric and I agreed that the study should not take a lot of effort as we will be sending a FigJam file to our stakeholders and give them about 1.5 weeks to complete on their own time. It will not require moderating and should take stakeholders about 20-30min of their time.
