### ISSUE TITLE
Data - document a how-to guide

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3072]
Write an initial guide for a single use case of "Data" in an application: "How to use Data to display search/filter with a DataTable"
- [ ] Write guide (using https://diataxis.fr/how-to-guides/ as reference) + grab screenshots of what the steps should look like
- [ ] Publish PR against site and have the guide tested by ... (tbd who will be testers)
- [ ] Publish guide to Design System site (no index page on site, only route for this guide will be created)

**Comment by ericsoderberghp** [comment]
A proposal for steps to start with:

1. start with just a `DataTable`, with `data` and `columns`
2. wrap with `Data` to get generic search + filter
3. customize by pruning down which properties to filter on

One thing to consider would be whether to show wiring it up to an external API. On the one hand, that is the preferred practice. On the other hand, maybe it complicates the example too much such that the user loses focus?

**Comment by halocline** [comment]
> One thing to consider would be whether to show wiring it up to an external API. On the one hand, that is the preferred practice. On the other hand, maybe it complicates the example too much such that the user loses focus?

Since we are in how-to guide mode (recipe mode), I think we can execute it so that it just says "Here's the code for the API call, add it [here]" which should provide the benefit without too much distraction.

**Comment by MikeKingdom** [comment]
When wiring up to an API, there's some rather non-obvious details about sort/filter/paging requirements that aren't represented in our examples. I see developers stumble over this all the time and very much paint themselves into a corner. I'd be careful about oversimplifying. It seems like we need some doc/examples that do real things.

**Comment by MikeKingdom** [comment]
> Keeping separate will keep each thing more focused.

Well that makes me question the guide a little bit if it's 'use case of Data in an application.'

**Comment by halocline** [comment]
Good callouts. Would envisioning this as "chapter 1" and things like sorting or pagination as chapters building upon chapter one address the cohesiveness and breadth of "use case of Data in an application" while allowing chapter 1 to focus on the key:
1 - start with just a DataTable, with data and columns
2 - wrap with Data to get generic search + filter
3 - customize by pruning down which properties to filter on
?

New ground to explore. Time to experiment!

**Comment by taysea** [comment]
Friday status summary:
- [Published PR](https://github.com/grommet/hpe-design-system/pull/3078)
- Ready for review: requesting feedback on wording, how intuitive the guide is, length, etc.
- List other "nice to haves" in PR description

**Comment by taysea** [comment]
1/13/23 update:
- Just waiting a final review then will be merged.
- On track for this sprint
