### ISSUE TITLE
Button - post submit busy indication - Phase 2

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#3075]
Based of https://github.com/grommet/hpe-design-system/issues/1321

The Next steps will be : (Pasting Scott's comment)

The submission button will actually dismiss the layer and return the user to the underlying original launching page after the Submit 'Succeeds' - so the 'busy indicator' will display for 1.n ms. The real expectation management w/ the system would be the 'addition of the new entity/object' added to the top of the data collection list. The notification, toast or inline style displayed by the page.

2.In the use cases were the user is managing child objects, adding 1.n items, the action control would again show the 'busy indictor' but the true system status communication would happed in the UI of the layer where the 'inline' information would be displayed as shown in Flow 3.

**Comment by Keeth-HPe** [comment]
Based of #1321

The Next steps will be : (Pasting Scott's comment) 
1. The submission button will actually dismiss the layer and return the user to the underlying original launching page after the Submit 'Succeeds' - so the 'busy indicator' will display for 1.n ms. The real expectation management w/ the system would be the 'addition of the new entity/object' added to the top of the data collection list. The notification, toast or inline style displayed by the page.

2.In the use cases were the user is managing child objects, adding 1.n items, the action control would again show the 'busy indictor' but the true system status communication would happed in the UI of the layer where the 'inline' information would be displayed as shown in Flow 3.

**Comment by Keeth-HPe** [comment]
https://www.figma.com/proto/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?page-id=667%3A385&node-id=7590%3A29276&viewport=-112%2C516%2C0.03&scaling=contain&starting-point-node-id=7590%3A29276&show-proto-sidebar=1

Phase 1 - I received some great feedback from @ericsoderberghp  @halocline @KennyAtHPE @SOjaHPE 
Thank you all so much! 
Based on those comments I have updated those visuals/ button animations. 

Please review the flows and share feedback as comments 🙂

**Comment by ericsoderberghp** [comment]
Added some comments in Figma, nice progress.
