### ISSUE TITLE
Grommet February Release 

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#3086]
We are thinking of taking a different approach for this release. Due to some regression issues in recent releases, we want to spend extra time on ensuring the quality of this release.

Our plan is to spend two weeks on the release process. The first week will be spent on QA and the second week spent on notes/docs/release.

Some ideas for the QA week:
- [x] Ensure that there is a test for every bug fix and enhancement
Changes that did not include tests:
https://github.com/grommet/grommet/pull/6632 - since this involves scroll behavior there isn't a good way to test this with jest. I'll add a note to our e2e issue
https://github.com/grommet/grommet/pull/6627 - added test
https://github.com/grommet/grommet/pull/6587 - couldn't test with jest since this is related to drop positioning. I'll add a note to our e2e testing issue.
https://github.com/grommet/grommet/pull/6613 - this one is also related to drop positioning. I'll add it to the e2e issue.

Extra areas to manually test:

Storybook
- [x] Chrome (grommet theme) Brittany
- [x] Chrome (hpe theme) Jessica
- [x] FireFox (hpe theme) Jessica
- [x] Safari (grommet theme) Britttany

Grommet site 
- [x] Make sure any changes from release are included in docs and remove 'stable' flags (Brittany) https://github.com/grommet/grommet-site/pull/453

Grommet Designer
- [x] Check that any new props/components have been added to grommet designer
- [x] https://github.com/grommet/grommet-designer/pull/119

Release Process
https://docs.google.com/document/d/1uYfXfkMaVjfmZfmHgO0vxbOdGrWYQhlna6IDxIJplkw/edit?usp=sharing
- [x] Release notes (Brittany)
- [x] Contributors (Brittany)

**Comment by jcfilben** [comment]
Closing, grommet v2.30.0 has been released https://github.com/grommet/grommet/releases/tag/v2.30.0
