### ISSUE TITLE
Page Templates - create first Dashboard/home/landing template

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3098]
### Problem Statement

How might we provide easy to use Dashboard visual examples to our designers and developer so that they can copy and paste them when designing?

### Deliverables

- [x] create success criteria
- [x] review Dashboard examples and understand what a Dashboard entails of
- [x] review PageLayouts and understand what it entails of (basics like grids, header, body, etc..)
- [x] gather dashboard examples from other teams like Storage and wellness dashboard
- [x] ideate ideas on how to visually layout Dashboard (skeletal to more detailed view((examples))
- [x] connect w/ Taylor
- [x] share + gather feedback from Scott + Eric
- [x] implement feedback
- [x] share + gather feedback from stakeholders
- [x] implement feedback
- [x] V1 of how headers + content adheres on XL-S resolutions

### Summary of Ticket
Scott, Eric and I connected on 1/17/23 to discuss the next steps following ticket #3071. We agreed that the first great win for the team is to focus on ideating on a template for Dashboard views. The idea is to pick one of the page layouts Chris posted on the exploration ticket that we think would be most useful based on stakeholder feedback and simplicity. We'd like to learn from the process we're taking on this template and see if we can apply easy wins to the other template work.

**Stakeholders**:
Chris
Gina
Justin
Amanda
Diane?

**Comment by vavalos5** [comment]
Worked on some success criteria for my ticket, understanding the whys and I also gathered the different types of dashboard use cases and started breaking it down from like a basic grid, to then adding containers of different elements that I saw within the layouts. Taylor and I to touch base on Monday.

**Next steps** 
- to swarm and walk Taylor through what i've got, discuss if we're heading in the right direction.
- I'll also be connecting with stakeholders to understand their use cases a bit further and understand what content is most important within a dashboard/home page.

**Comment by vavalos5** [comment]
Connected with Scott and Taylor to collect feedback today.

Next steps:

I've set up a call to discuss with Chris tomorrow on how he determines a 2 page layout when designing a home/dashboard page. What is the importance of content so we can utilize his most recent example and provide it as an example on the site of how things will stack + how that'll look like on smaller screens.

How or does he use our grid system?


Others:

Provide examples of how content could be stacked. We don't want to be prescriptive on this to provide teams flexibility.
Rework examples i've created to align to the DS example layouts

**Comment by vavalos5** [comment]
Some notes from chat w/ Chris today:


**My questions:**
In continuation to what we were discussing earlier during show and tell, when i applied the grid to some of the screens I collected from you, I noticed that some of the content isn’t aligned to the beginning of the grid but rather indented further in which is aligned to our t-shirt sizing pixel widths.

We’re looking at implementing grids as part of our page layouts, how do you determine the gutter space when you’re creating a 2 page layout since the gutter between elements is different from our grid.

- he does use t-shirt sizing, as the drivers and not our grid
- t-shirt sizing doesn’t adhere to the grid
- he’d like to have a grid with a min/max so we don’t rely on t-shirt sizing + behaviors
- doesn’t design for larger than 1920 px width
- a lot of his designs are taken too prescriptive

Do we need to go back and revise our grid system?
- maybe using our existing grid, we re-align Chris's designs using our card t-shirt sizing and adjust
- Chris knows we know we have grids and people don’t use them.
- Currently, Chris dk what the default grids are or how prescriptive they are. 
- do we have prescriptiveness past 100% width? Some prescriptiveness is good. There should be some principles on how we handle some of the content. 
- Chris knows there are some basics on how we want to lay the layout in specific scenarios.

- How do you imagine content to align when you get so smaller screens on the home page I got from you? 
- should naturally cascade in smaller screens


![Image](https://user-images.githubusercontent.com/62117454/214445028-2d27af58-65a3-414f-9b59-ff6cc061deb8.png)

![Image](https://user-images.githubusercontent.com/62117454/214445044-0bbf2e18-5f6a-43ee-8956-d36ae3cbfa5f.png)



**Some questions to think further on/questions for team...**
- How prescriptive do we really want to be and how much time do we really invest on it?

**Next steps:**
- We should look at the min/max widths, the work I have now is important on understanding what makes up a page layout
- We can do some more research on grids but we need to figure out how the header and the content adheres on XL-S resolutions first
- large screen is something we need to be aware of bc of legibility
- 1920 px widths - There’s no value to go larger than that due to legibility. - maybe ask gina on this
- ask Justin and a few others to validate how they see content stacking when moving to smaller screens bc we want to ensure this is a shared mentality
- how do we want to treat this? Is it a 12 column grid? and we show how the content is layed out?

![Image](https://user-images.githubusercontent.com/62117454/214445028-2d27af58-65a3-414f-9b59-ff6cc061deb8.png)

- what are the card sizes that we want people ideally to use?


@SOjaHPE FYI

**Comment by vavalos5** [comment]
Scheduled meeting to walk Justin through the work i'm working on + ask similar questions as I asked Chris

**Comment by SOjaHPE** [comment]
During standup today we made the decision to not include GRID details in this MVP Home page layout template. This is due to a recommendation to use min/max widths for cards & other elements which would making it hard to align a rigid specifications once users begin to fill out the templates. Focus is to remain on the overall page structure, including the header, heading, and any navigational elements, things outside the grid itself. Within in the content region, the template should provide the larger content container layouts.

**Comment by vavalos5** [comment]
Chatted w/ Justin yesterday. It came to my attention that the column on the rights is typically saved for highly important content like marketing something like whether the user has experienced our cloud platform and if not, click here!!

It would be foolish not to think of how important content is laid out based on importance, based on the Z pattern of how people scan pages.

I've also pinged Chris on my file to ensure whether the layout order he's given me is in fact aligned to his thinking or if Justin's comments align with his thinking on how items stack once on a smaller screen.


**Next steps:**
I've set up a meeting to chat w/ Taylor on Monday on Global Header max/min widths + ensuring we're aligned on widths of whether content live on sizes XL-S

**Other questions:**

@ericsoderberghp It would be good to get your thoughts on how much content we should be providing on these templates. For instance, do we want to give 2-3 different flavors of a 2 column layout for instance. One might be simpler, one might have more cards, and and another might just be built out with a slots to allow designers with flexibility to insert content. You can take a peek at what I've currently got [here](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5226%3A110552&t=Q88sf9GjidnF14X4-1).

**Comment by vavalos5** [comment]
Great quick chat w/ Eric this AM. Eric agreed on us having 1 template as a starting point. As next steps for next sprint, i'd like to connect w/ stakeholders and observe whether the template is easy or not easy to use, receive feedback, implement. 

Also chatted w/ Taylor on min./max widths and how that works using the Grommet CSS grid. We agreed on annotating the designs I have to give designers an example of how they might do the same for their designs to make it an easier hand off to devs. This creates better communication on how grid columns should behave vs. following design exactly as it is created.

We also confirmed the margin pixel widths, placement and how content behaves. I have a few adjustments to make based on this discussion.

**Comment by vavalos5** [comment]
Annotated the designs to explain min/max grid widths and adjusted designs to aligned sizes M- XS to the correct margins.

As stated above, next steps are to test the designs with stakeholders to understand easiness of templates.

**Comment by ericsoderberghp** [comment]
The key deliverable was to have a single template that stakeholders could take a stab at using. (this screen: https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5226%3A110552&t=DAU3IeruIyfQ7dEf-0) Having the responsive behavior and build up of detail is an extra bonus but wasn't strictly required but we can get feedback on now that we have it. The next steps outlined in #3123 to review with stakeholders should then ask them to test drive the template and provide feedback on how useful it is, what's missing and what's unnecessary.
