### ISSUE TITLE
Grommet - Revoke current circleci keys and create new ones

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#3099]
We should go through and revoke our current circleci keys and create new ones. As we are going through this process it might be nice to document it so it is easier in the future.

Deliverables:
- [x] Chromatic key
- [x] NPM key
- [x] Github key
- [x] Deploy key
- [x] Document process https://github.com/grommet/grommet/wiki/Key-Rotation

**Comment by krenekj** [comment]
Yes - please document it.

**Comment by jcfilben** [comment]
Update 1/24: Updated our chromatic token but then ran into an issue trying to reference circleci project variables within our `circleci/config.yml`. I filed a support ticket with circleci and waiting to hear back.

**Comment by jcfilben** [comment]
Update 1/27: renewed our Chromatic and NPM tokens. Attempted to renew our Github token but it looks like we are using a different account to authenticate. Need to see who is able to access this account and then try to reset the key from that account.

**Comment by jcfilben** [comment]
All keys have been rotated, the process is [documented here](https://github.com/grommet/grommet/wiki/Key-Rotation), and an [issue](https://github.com/grommet/hpe-design-system/issues/3134) to rotate our keys again in 6 months has been created.
