### ISSUE TITLE
Grommet - January Patch Release

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#3100]
There was a regression in our latest v2.29.0 release. Once https://github.com/grommet/grommet/pull/6577 gets merged we should create a new release.

**Ensure that there is a test for every bug fix and enhancement** 
- [x] https://github.com/grommet/grommet/pull/6585

**Storybook**
- [x] Chrome (grommet theme)
- [x] FireFox (hpe theme)
- [x] Safari (grommet theme)

**Grommet site** 
No doc changes needed

**Grommet Designer**
No designer changes needed

**Process**
- [x] Release notes
- [x] Contributors

**Comment by britt6612** [comment]
Released v2.29.1
