### ISSUE TITLE
Refactor Datatable Customization example to use Data

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3101]
We should refactor relevant examples with search + filtering to use Data. Examples include:
- [ ] DataTable Customization: https://design-system.hpe.design/templates/datatable-customization

**Comment by JCoder121** [comment]
2/10/23:

- Ticket is now unblocked, remaining work is to incorporate enhancements and ensure functionality matches existing example.

**Comment by JCoder121** [comment]
2/14/23 work remaining:

- Bug with RangeSelector filter max and min values, discuss and either file issue or resolve it manually
- Refactoring filter config labels and properties using `properties` in the Data component to custom render filter labels
