### ISSUE TITLE
Typography - Create and demo "incremental" version of theme adjustments

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3102]
- [x] Create branch of HPE theme that demos theme with all changes except changes to paragraph/text sizing
- [x] Apply theme branch to DS site to be able to do a side by side comparison with the [current deploy](https://deploy-preview-3074--keen-mayer-a86c8b.netlify.app/)
- [x] Send to Chris for review

Chris will then need to determine what is the final "on brand" criteria (if the incremental approach is sufficient or if further "tightening up" of the text sizes needs to occur.

**Comment by halocline** [comment]
Deploy preview - https://github.com/grommet/hpe-design-system/pull/3113
HPE Theme NEXT PR - https://github.com/grommet/grommet-theme-hpe/pull/305/

**Comment by taysea** [comment]
Next steps are to complete the Brand Audit: https://github.com/orgs/grommet/projects/12/views/1?pane=issue&itemId=18680811
