### ISSUE TITLE
Global Trade Services - Busy Indicator

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3106]
[Research and Exploration
](https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Spinner-Component?node-id=2716%3A5832&t=fc8zDaViialkDY0q-1)
## **The problem to be solved**
Global Trade Services is used to evaluate whether the end user should be allowed to access the requested resource. This involves an API call that will take a variety of durations to respond. Sometimes it will respond in a tens of milliseconds, sometimes an a second or two, and sometimes the service is offline and it won't respond for a good long time. 

GLCS is working on implementing a loading spinner to give feedback to the user. The current solution doesn't align with the HPE Design System. It is essential that we review and propose a solution that will keep GTS consistent with HPE GreenLake products. If our current guidance doesn't cover all the behaviors or use cases we need to expand that guidance as appropriate.

## **Original Intention of the design**
Our proposal is to show progress loader while user waits for GT Screening when it’s down.

- We decided on progress loader instead of a message since it can flash quickly in some cases and not allow users to read the message. 

- To avoid a quick flash of progress loader when GT Screening is not down,  we will only display the progress loader after a 2 seconds delay.

- The maximum time, progress loader can show is 9 seconds; we will increment progress accordingly.

- Progress loader will display in the following screens (rough mock ups) and will block the user from clicking around until progress finishes.

## **Progress loader will display in the following screens**
1. **Choose Account Page:**
![Image](https://user-images.githubusercontent.com/83719939/213207928-99ccb6aa-d42b-4d21-8469-4d39197f2c73.png)

2. **Switch Account Page:**
![Image](https://user-images.githubusercontent.com/83719939/213208095-5819b798-f519-4717-87f3-af6ee0e8136e.png)

3. **Create Account:**
![Image](https://user-images.githubusercontent.com/83719939/213208227-65d72631-f47f-43b5-b520-ffd3b49a356e.png)

4. **Create Customer Account:**
![Image](https://user-images.githubusercontent.com/83719939/213208362-69ed0e8e-88f6-4260-ba90-d9b5d16c9634.png)

5. **Launch Customer Account from Customers main page:**
![Image](https://user-images.githubusercontent.com/83719939/213208489-1163e803-6205-4217-b1f5-a4d293300267.png)

6. **Launch customer Account from Customer Details page:**
![Image](https://user-images.githubusercontent.com/83719939/213208600-379c132d-a9a1-4006-aa1d-eab84b786f1e.png)

7. **Edit Account Details:**
![Image](https://user-images.githubusercontent.com/83719939/213208698-dc6ed9ad-1767-4663-aff8-252184307ddd.png)

## **Deliverables**

- [x] review and evaluate the GTS use cases
- [x] review current [HPE DS loading guidance]([design system loading patterns](https://design-system.hpe.design/components/spinner?q=load#guidance))
- [x] document gaps in our guidance if any exist
- [x] propose enhancements to our guidance
- [x] ideate on loading solutions for GTS, which align with the HPE Design System
- [x] review with stakeholders

## **Use cases and success criteria**

**Use Cases**
- Quick API response 
   - Loading is <X ms
- Service is offline and/or it won’t respond in a long time
   - Loading is >X ms
- API response takes [a,b] ms

**Success Criteria**
- Loading indicator
   - Provides clear and progressive visibility of the system’s status
   - Does not interrupt the user’s mental model
   - Users receive a confirmation on whether or not the process succeeded or failed
- Behaviors
   - Loading is announced to screen readers
- Style
   - Feels visually consistent with the rest of Design System designs.

## **Stakeholders to keep informed**

- chesley.ratliff@hpe.com / github @chesleyratliff  (GLCP PM)
- sailaja.brahmandam@hpe.com (GLCP Engineering)
- lokeshmd@hpe.com (GLCP PM)
- mojgan.ghanbaran@hpe.com (GLCP Engineering)

**Comment by KennyAtHPE** [comment]
**1/19 update**

Mike and I connected on this issue and went over our questions and some possible solutions. The next steps are to:
- Define success criteria
- Meet w/ stakeholders to gain a better understanding of flows
- Mockup potential solutions (this work is related to #1321

**Comment by KennyAtHPE** [comment]
**1/30 Update**

Handed off of our [proposed designs](https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Spinner-Component?node-id=2749%3A11515&t=C2ZRoZh2F2J8mJUj-1) to stakeholders. Will be meeting with them later today to go over their questions and concerns.

**Comment by KennyAtHPE** [comment]
The meeting w/ Stakeholders went well, we were able to clear up their questions and concerns. They asked for us to mockup several other screens for them and the solution/direction for those was also discussed.

**Comment by KennyAtHPE** [comment]
Been messaging Mojgan back and forth on questions that their devs had on our mockups. Everything seems more or less cleared up now and everybody is on the same page. Will create a followup ticket and close this one out.
