### ISSUE TITLE
Brand Audit - GLCP

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3117]
The **purpose** of this ticket is to conduct the actual 'Plaque Test' and 'Compile test results' steps of the GLCP [Brand Audit](https://hpe-my.sharepoint.com/:p:/r/personal/melanie_merton_hpe_com/Documents/OneDrive%20-%20Hewlett%20Packard%20Enterprise%202/UCX/Brand%20Assessment/OCTO%20Brand%20Assessment%20Plan%20.pptx?d=w9e1fb8e3435b4910a80351f4666a2877&csf=1&web=1&e=mVqUr5).

The **intention** is a targeted brand compliance assessment of implemented code of identified key GLCP platform task flows. The assessment is the latest definition of what being On Brand means, this is part of the larger HPE "Brand Refresh" initiative that kicked off from Discover last summer.

**Goal**  is to identify elements not in alignment with the updated HPE Theme, will need to be tracked and addressed in a deliverable that will specify to Engineering the list.

## **Dependencies**

- [x] Defined 'On Brand' Criteria for audit ([Figma](https://www.figma.com/file/wtwk7YovJMvDb3cfWCMWpu/HPE-Product-Brand-Guidelines?node-id=1%3A9&t=xFNug5VFCHrn2CH0-0))
- [x] Defined GLCP testing page flow scope ([pages](https://www.figma.com/file/T66NMq81BTNgeVPyaCX8o2/GLCP-Brand-Audit?node-id=8255%3A35254&t=unf17mDaEekCffMA-0))
- [x] Designed branding audit plaque test

## **Deliverables**

- [x] Run GLCP plaque test
  - [Screens to audit](https://www.figma.com/file/T66NMq81BTNgeVPyaCX8o2/GLCP-Brand-Audit?node-id=1504%3A58087&t=unf17mDaEekCffMA-0)
  - [Audited screens](https://www.figma.com/file/rKZTBjKiBPkARKXAP2Gdzy/GLCP-Brand-Audit?node-id=0%3A1&t=GQzLLHO2EX2UlvDZ-0)
- [x] Compile test results, exact format is expected to be combination of annotated screen captures in figma and/or bugs filed in the [GLCP bug/enhancement](https://hpe.sharepoint.com/teams/hpe-design/UX/Lists/Bugs%20and%20Enhancements/Public%20View.aspx?viewpath=%2Fteams%2Fhpe%2Ddesign%2FUX%2FLists%2FBugs%20and%20Enhancements%2FPublic%20View%2Easpx) system
  - [Results summary](https://hpe.sharepoint.com/:w:/r/teams/hpe-design/_layouts/15/Doc.aspx?sourcedoc=%7BD21C71C0-FFF2-488B-8597-3FACC59CB353%7D&file=Brand%20Audit%20-%20HPE%20GreenLake%20Platform.docx&action=default&mobileredirect=true&cid=c93ed545-cef6-47c5-ba0a-d112c4d2d23e) 
  - [Results todos](https://hpe.sharepoint.com/:x:/r/teams/hpe-design/_layouts/15/Doc.aspx?sourcedoc=%7B16CC4EA6-A4D9-4937-9A15-8C84671F4610%7D&file=GLCP-Brand-Audit.xlsx&nav=MTVfezcwRDM2NDhCLTU0NTctRkQ0My1CRTdGLTU3NTBERThDOUIyN30&action=default&mobileredirect=true)
  - [Results annotations](https://www.figma.com/file/rKZTBjKiBPkARKXAP2Gdzy/GLCP-Brand-Audit?node-id=0%3A1&t=s19OIOX4qLsIQVRt-0)

## **Next Steps**

Upon completion of this GLCP Branding Compliance Audit, new tickets will need to be created to track steps to conduct a Brand Audit of GLCS 
- [x] Issue for defining scope - https://github.com/grommet/hpe-design-system/issues/3146
- [x] Issue for updating plaque test approach - https://github.com/grommet/hpe-design-system/issues/3147

**Comment by halocline** [comment]
Feb 3 - Status
- Screen grabs and annotations largely complete. We could not find/get the page to properly render couple screens.
- Tracked down the account management email templates. Have not found the subscription management emails nor the welcome email.

Next steps:
- Write summary of findings
- would like to audit/comment on some table spacing / layout type comments
- To Do list and audit due to working group / Melanie Feb 6.

**Comment by halocline** [comment]
Closed by delivering audit results and creating follow on tickets for GLCS audit and plaque test improvements (issues linked in the "deliverables" section above).
