### ISSUE TITLE
Grommet Security - Vulnerability Scanning and VTN

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3127]
Deliverables:

- [x] Reach out to Chris Hubbard to learn more about VTN
- [x] Reach out to Suhas Shivanna about vulnerability scanning
- [x] Reach out to Brandon Carson to see if we can get access to the Coverity tool

Next steps:
- Create SBOM in SPDX-JSON format
- Get access to VTN tool
- Once we have access, setup the Coverity with the grommet repo

**Comment by jcfilben** [comment]
Follow on tickets:
https://github.com/grommet/hpe-design-system/issues/3128 - VTN
https://github.com/grommet/hpe-design-system/issues/3129 - Coverity
