### ISSUE TITLE
Button - Fix icons within the Figma component

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3133]
Noticed a couple of bugs within the [Button component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=4489%3A78687&t=UmvwXgUjsIcpox73-1) related to icons that need to be addressed:
1. Some variants have a mixture of 1 icon, 2 icons, or 3 icons (I'm assuming this was an issue when copying and pasting variants when originally building the component). This is causing issues for the "Icon Swap" property. If there are >1 icon in a variant, the "Icon Swap" property will swap all the icons and turn any hidden icon(s) on.

<img width="545" alt="Screen Shot 2023-02-02 at 10 07 03 AM" src="https://user-images.githubusercontent.com/86075038/216407568-f1b97532-f261-4fe4-94f9-3f4f26b5820f.png">

The solution is to go through every variant and remove any additional icons, however, I'm not sure if this will affect people's instances once we publish those changes.

2. The icons are currently being named "Icon right," "Icon left," and "Icon only." There isn't a need for this and the icons should just be given a single name, "Icon." This can cause issues where icons are not being maintained once a user swaps between variants since Figma points to a layer's name.

Related ticket #2622

**Comment by Keeth-HPe** [comment]
@KennyAtHPE  @vavalos5 

1. Went through every variant and removde all the additional icons. It definitely won't affect anyone's instances. Since we are keeping one icon according to the icon property.  

2. Connected with Taylor on icon sizes. Pasting her comment here ;
"There’s still some discussion about what the icon sizes will be in the different button sizes with this new brand refresh, so it’s probably best to wait for a little on that if possible"

**Comment by vavalos5** [comment]
Thank you for doing this @Keeth-HPe. @KennyAtHPE can you take a look today as I won't have the chance to today. I'll take a look on Monday. Thank you!

**Comment by KennyAtHPE** [comment]
@Keeth-HPe Looks good on my end. Thanks for the quick fix on this. We will have to remember to double check icon sizes when we get more info on that.

**Comment by vavalos5** [comment]
Thank you indeed for making this quick fix @Keeth-HPe!!

One super small thing I noticed on the icon instance swap is that i'd have to look for the icon library in the instance menu. So it looks like the icon library isn't specifically chosen when swapping the instance and as a designer, i'd have to look for the icons rather than being able to easily change the instance from the icon library specifically. Can we change that please.

After that, feel free to publish 🥳

**Comment by Keeth-HPe** [comment]
@vavalos5 
If you tried swapping within the HPE design system file, you will have to look for the icon library in the instance menu, because it will show all the local components first.

If tried outside the file, it will show icons library specifically.

**Comment by Keeth-HPe** [comment]
Pubished the changes  🎉👍

**Comment by KennyAtHPE** [comment]
Connected with @Keeth-HPe and did a review on the button. For some reason, we were seeing different things on both of our ends when utilizing the icon swap feature. Additionally, looks like there were some variants that still had multiple icons within them. 

Next steps:
- [ ] Both myself and Keeth will comb through the variants one final time
- [ ] Keeth will be working on finding a solution for the icon swap
- [ ] Publish changes

**Comment by Keeth-HPe** [comment]
I fixed the icon swap issue
Apparently, I had picked the wrong instance while giving the swap property, my bad. Figured that out. So now even if we try swapping within the same file, it should still work fine 👍 Vicky Thank you for reviewing this in detail.

**Comment by Keeth-HPe** [comment]
@KennyAtHPE  

- [ ] I've looked through all the Variants. Looks good to me.

**Comment by KennyAtHPE** [comment]
Thanks @Keeth-HPe. I reviewed the button component and found that there are still a couple of underlying issues. To finish out this ticket, we'll need too:

- [ ] Rename all Icon layers to "Icon" so that icon swapping preserves between variants
- [ ] Apply the swap property to all variants (looks like only a few have them right now)

I'm going to take a stab at this to help swarm and finish out the ticket.

**Comment by Keeth-HPe** [comment]
@KennyAtHPE @vavalos5 

😅I installed some plugins to recheck the naming and made sure the swap property is applied to all variants.
Hope it's complete. 

@KennyAtHPE Thank you again for helping in the review. 👍

**Comment by vavalos5** [comment]
@KennyAtHPE Did you do some work on this? I want to ensure this is in the right column or if it does in fact need review.

**Comment by KennyAtHPE** [comment]
@vavalos5 

Checked through all of the variants for the correct icon naming and that the swap property is applied throughout. Found some small issues but those have now been resolved.

Feel free to publish @Keeth-HPe

**Comment by Keeth-HPe** [comment]
Published the changes. 👍

Thanks for the support @KennyAtHPE  @vavalos5
