### ISSUE TITLE
File-input - Change the rounding (Radius) for the hover background.

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#3149]
While we hover over the "select file" button within the file input component, the button appears to have a background with rounded edges/Radius.

Not sure if this is a mistake. But it's inconsistent with other components/ Design system standards. 
<img width="378" alt="Screenshot 2023-02-14 at 9 23 18 PM" src="https://user-images.githubusercontent.com/86280029/218789210-9e1aaf43-39f6-4d20-9972-dc9cda79c8a3.png">

**Comment by halocline** [comment]
Rounding treatment is expected and matches rest of rounded buttons.
