### ISSUE TITLE
PageHeader - Adjust padding above PageHeader in Figma to size medium on small and xsmall resolutions to align with theme

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3159]
[Figma Link](url)

While taking a look at the PageHeader component and chatting with Taylor, it has come to my conclusion that we need to made the padding above the reverse anchor to size medium on t-shirt sizes small and xsmall to align with theme. Please make these adjustments in Figma. Adding a screen shot here below for reference.
<img width="1436" alt="Screen Shot 2023-02-23 at 10 56 25 AM" src="https://user-images.githubusercontent.com/62117454/221003811-3dea32aa-6a9d-48a8-880b-e38c28591bc8.png">

**Comment by vavalos5** [comment]
Asif doesn't appear on our list of people. I'm adding this to the "in progress" column for now.

**Comment by ashifalinadaf** [comment]
Had a discussion with Vicky and working on the ticket.

**Comment by vavalos5** [comment]
@ashifalinadaf Thank you for quickly making these changes, it looks great! I did leave one comment where the examples are. Can we replace those older examples with the newer component please.

I've also reached out to Jessica, one of the developers on the team to verify whether the gap above the reverse button is medium or large for the medium PageHeader variant.

**Comment by ashifalinadaf** [comment]
I will be making the necessary changes.

**Comment by ashifalinadaf** [comment]
Changes have been made and in for review with Vicky.

**Comment by vavalos5** [comment]
I've walked Asif through the steps on how to transfer the approved changes he made to the main file. We have done this together and have published it in Figma.
