### ISSUE TITLE
Grommet - April Release

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#3164]
### QA:
- [x] Ensure that there is a test for every bug fix and enhancement
We should consider adding jest tests to cover the following PR's:
  - [x] https://github.com/grommet/grommet/pull/6704 **[Matt]** PR: https://github.com/grommet/grommet/pull/6764
  - [x] https://github.com/grommet/grommet/pull/6642 **[Jessica]** Added test in this PR: https://github.com/grommet/grommet/pull/6758
  - [ ] https://github.com/grommet/grommet/pull/6715 **[Jessica - no test added, decided to revert this PR]**
  - [x] https://github.com/grommet/grommet/pull/6725 **[Matt]** PR: https://github.com/grommet/grommet/pull/6764

### Extra areas to manually test:

- https://github.com/grommet/grommet/pull/6693
- https://github.com/grommet/grommet/pull/5943

### Storybook
- [x] Chrome (grommet theme) **[Jessica]**
- [x] FireFox (grommet theme) **[Jessica]**
- [x] Safari (hpe theme) **[Jessica]**

### Grommet site 
- [ ] Make sure any changes from release are included in docs and remove 'stable' flags
https://github.com/grommet/grommet-site/pull/471

The following PR's still need documentation updates on grommet site:
- https://github.com/grommet/grommet/pull/6704 **[Matt]** updated docs in this PR: https://github.com/grommet/grommet-site/pull/473
- https://github.com/grommet/grommet/pull/6749 **[Eric]** added docs in this PR: https://github.com/grommet/grommet-site/pull/472

### Grommet Designer [Eric]
- [x] Check that any new props/components have been added to grommet designer

The following PR's include functionality that has not been added to grommet designer:
(Note that some of these may be a heavier lift to add. In that case we can hold off adding them. No need to delay the release to get these in.)
- https://github.com/grommet/grommet/pull/6642 **[Eric - no changes needed in grommet designer, doesn't do border arrays yet]**
- https://github.com/grommet/grommet/pull/5943 **[Eric - no changes needed in grommet designer, doesn't do form validation yet]**
- https://github.com/grommet/grommet/pull/6722 **[Eric - no changes needed in grommet designer]**
- https://github.com/grommet/grommet/pull/6749 **[Eric]**
- https://github.com/grommet/grommet/pull/6704 **[Eric - not needed in grommet designer]**
- https://github.com/grommet/grommet/pull/6656 **[Eric]**

### Release Process
- [x] Release notes 
- [x] Contributors

**Comment by jcfilben** [comment]
Changing this release from March to April since we released 2.31.0 in March.

**Comment by jcfilben** [comment]
Update 4/14: 🟢 on track, I have put together release notes and added missing documentation to grommet site. Ideally https://github.com/grommet/grommet/pull/6725 should be merged before the release.

**Comment by jcfilben** [comment]
Release Notes:

General:

- Added support to Box for using border between in a border array. ([#6642](https://github.com/grommet/grommet/pull/6642))
- Added busy, messages, and success props to Button to support an animation while button is loading and when the button action succeeds. ([#6656](https://github.com/grommet/grommet/pull/6656))
- Changed status-error color to meet accessibility contrast requirements. ([#6690](https://github.com/grommet/grommet/pull/6690))
- Changed Calendar to honor reference when set. ([#6715](https://github.com/grommet/grommet/pull/6715))
- Enhanced FormField to allow triggering validation at the FormField level. ([#5943](https://github.com/grommet/grommet/pull/5943))
- Fixed issues using Grommet in a shadow root. ([#6698](https://github.com/grommet/grommet/pull/6698))
- Fixed issue in DateInput when deselecting a date. ([#6693](https://github.com/grommet/grommet/pull/6693))
- Fixed display of NameValueList with gird layout in Safari. ([#6691](https://github.com/grommet/grommet/pull/6691))
- Fixed FileInput focus traversal. ([#6391](https://github.com/grommet/grommet/pull/6391))
- Fixed issue where NameValueList’s align prop was ignored. ([#6722](https://github.com/grommet/grommet/pull/6722))

DataTable:

- Changed DataTable to use a primaryKey value as the row key. ([#6742](https://github.com/grommet/grommet/pull/6742))
- Fixed an issue with disabled rows and lazy loading. ([#6706](https://github.com/grommet/grommet/pull/6706))
- Fixed issue where border is not applied to CheckBox cells. ([#6718](https://github.com/grommet/grommet/pull/6718))
- Fixes an issue where the second argument (‘datum’) passed to onSelect was always undefined. ([#6750](https://github.com/grommet/grommet/pull/6750))

SelectMultiple:

- Fixed a bug where the drop would scroll back to the top after selecting an option. ([#6735](https://github.com/grommet/grommet/pull/6735))
- Fixed an issue when using object options and showSelectedInline. ([#6738](https://github.com/grommet/grommet/pull/6738))

Typescript:

- Fixed type error on List’s `children prop. ([#6687](https://github.com/grommet/grommet/pull/6687))

Data: (beta)

- Changed DataFilters to use tip. ([#6707](https://github.com/grommet/grommet/pull/6707))
- New DataTableGroupBy component.  ([#6749](https://github.com/grommet/grommet/pull/6749))
- Fixed an issue in Data with filtering when filter value is an object. ([#6725](https://github.com/grommet/grommet/pull/6725))
- Added support to Data’s filtering for when a property is an array. ([#6704](https://github.com/grommet/grommet/pull/6704))
- Added a default tooltip to DataTableColumns. ([#6746](https://github.com/grommet/grommet/pull/6746))

**Comment by jcfilben** [comment]
Found an issue with Button onClick while checking storybook. PR filed here: https://github.com/grommet/grommet/pull/6759

**Comment by jcfilben** [comment]
Found an issue with setting root="shadow" in storybook. PR filed here: https://github.com/grommet/grommet/pull/6760

**Comment by jcfilben** [comment]
Found a potential regression in https://github.com/grommet/grommet/pull/6715.

If Calendar `reference` is set and then we switch to a different month and select a date, the Calendar switches back to the reference month.

Tested with the following code:
```javascript
const [date, setDate] = useState();

return (
  <Box>
    <Box align="center" pad="large">
      <Calendar
        reference={'01/01/2023'}
        onSelect={(nextDate) => {
          setDate(nextDate !== date ? nextDate : undefined);
        }}
        date={date}
        animate={false}
      />
    </Box>
  </Box>
);
```
https://user-images.githubusercontent.com/54560994/233156995-d05425b4-cba7-4dec-944c-1e17c3008ce0.mp4

**Comment by jcfilben** [comment]
I'm having trouble finding a good solution to the above issue where both the dual calendar story works and the `reference` props behavior matches the [documentation](https://v2.grommet.io/calendar#reference)

**Comment by jcfilben** [comment]
@ericsoderberghp I'm proposing we revert https://github.com/grommet/grommet/pull/6715 and reopen https://github.com/grommet/grommet/issues/6609. Let me know if that sound okay

**Comment by ericsoderberghp** [comment]
> @ericsoderberghp I'm proposing we revert [grommet/grommet#6715](https://github.com/grommet/grommet/pull/6715) and reopen [grommet/grommet#6609](https://github.com/grommet/grommet/issues/6609). Let me know if that sounds okay

I agree. We still need to find a fix for 6609, but agreed on reverting 6715 for this release.

**Comment by ericsoderberghp** [comment]
When adding Button `busy` to grommet-designer I noticed that using it with the default grommet or hpe Button appears to just remove the label, which feels a bit broken. `success` works though. I'm wondering if we should apply the same color detection as we use in the `success` case for the `busy` case?

**Comment by ericsoderberghp** [comment]
grommet-designer changes have been made

**Comment by jcfilben** [comment]
> When adding Button busy to grommet-designer I noticed that using it with the default grommet or hpe Button appears to just remove the label, which feels a bit broken. success works though. I'm wondering if we should apply the same color detection as we use in the success case for the busy case?

Created a PR to fix this: https://github.com/grommet/grommet/pull/6765

**Comment by jcfilben** [comment]
> > @ericsoderberghp I'm proposing we revert https://github.com/grommet/grommet/pull/6715 and reopen https://github.com/grommet/grommet/issues/6609. Let me know if that sounds okay

> 
> I agree. We still need to find a fix for 6609, but agreed on reverting 6715 for this release.


Created a pull request to revert 6715 https://github.com/grommet/grommet/pull/6766

**Comment by jcfilben** [comment]
Version 2.32.0 of grommet has been released https://github.com/grommet/grommet/releases/tag/v2.32.0
