### ISSUE TITLE
New Global Header HFS Prototype

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3179]
There is a request to build part of the new global header in grommet on a "real" product page context for accessibility testing (low vision users). This will be part of testing data visualizations. The changes to the header include, incorporating the smaller buttons and some limited functionality. Not every menu needs to be accurately represented. 

Why the need for an actual coded page? Figma isn't best prototyping tool since it will "resize" the page (and font) and I need it to be true to size to test the new text size with low vision users.

**Designer:** Gina T.
**Test Facilitator:** Lauren Britton
**Deadline:** Testing will be Mar 27th

We should be able to leverage the previous HPE global header Taylor coded. Adjusting this one: https://github.hpe.com/grommet/hpe-global-header

Next Steps:

- [x] Reach out to Gina T. to get a figma link documenting the scope of the global header enhancements, recommended product page to be used for this page.
- [x] Meet with Gina to iron on any questions confirm the ask.

**Comment by SOjaHPE** [comment]
@GinaTaylor will review this ticket next week and provide feedback/updates

**Comment by SOjaHPE** [comment]
@ericsoderberghp in a discussion with @lorbritton yesterday we discussed the importance of their team to have access to all prototypes (preferably) 3 business days before the scheduled test. This will allow them adequate time to review the script and make adjustments if necessary. That would push the deadline of this ticket up to Mar 22nd by EOD (inclusion in our sprint which starts today - Wed Mar 15).

**Comment by taysea** [comment]
Test page has been published: https://silly-rugelach-0b55e7.netlify.app/

**Comment by taysea** [comment]
Will be meeting with Gina and Eric monday morning to iron out one question on icon-sizing.

**Comment by taysea** [comment]
We resolved the icon-sizing question and will go with `16px` for readability. The link has been updated to reflect the latest.
