### ISSUE TITLE
Formal process to support DS & GLCP UX

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3181]
Need the team to review this document - deadline for April HPExs All-Hands

https://www.figma.com/file/8pInYUjeKnr1fYH0ygpwC0/PAL--%3E-DS-proposal?node-id=0%3A1&t=Y2Ww5pNeVKkEf0Di-1

        * Derek has made significant updates to this

It is necessary to review this, especially the contribution model
Is this document going to address previous issues w/ supporting GLCP?

**Comment by halocline** [comment]
@SOjaHPE - Can you please elaborate on any specific items you'd like feedback on? Specific questions?

Can you also add a date you need the feedback by?

**Comment by halocline** [comment]
Closing as I believe a efforts are underway to tighten up this collaboration.

**Comment by SOjaHPE** [comment]
[like]  Oja, Scott reacted to your message:
________________________________
