### ISSUE TITLE
Tabs - Identify styling for vertical tabs

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3196]
[Figma Link](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?type=design&node-id=5533%3A125029&t=Qwvk3PNeskYQRfF7-1)

## Summary
During the Page Template work, it came to my attention that there are many teams using vertical tabs. I began to do [some explorations on what those might look like with our current design system theme and our future brand refresh.](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?node-id=5533%3A125029&t=n4UDFUteIhOJ9jLG-1)

We will need to discus with Chris and others to decide whether any of the explorations are worth pursuing or if we need to go back and continue exploring.

We'll also have to think about the hierarchy semantically.

------------------

## Considerations

Even if vertical tabs are not ideal, the HPE Design System should have an initial solution (which can be deprecated in the future if needed/desired).

- [x] Consider executions which currently exist (GLCP may be the most prominent)
- [ ] Consider how vertical tabs may / should respond when screens get narrow
- [x] Create 2-3 flavors of vertical tabs

## Deliverable

- [ ] Create initial design direction vertical tabs. 
- [ ] Provide recommendation with accompanying design rationale.

**Comment by vavalos5** [comment]
In a quick chat with Chris earlier, I mentioned how during the time I was doing Page Template work, I was taking an extra step on how we might handle vertical tabs. In this instance, we were going to provide them as just examples within the Page Template work, however, i'm wondering if we're looking to have these implemented as actual components or still thinking of just PageTemplates? I can go either way, but beginning o lean towards components since they've been a big ask for some time.

@halocline @SOjaHPE would love your thoughts.

**Comment by vavalos5** [comment]
I've already got 4 different explorations based on some previous conversations i've had with Chris in the past. They've been implemented in both the background and background-back color.

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/dd1844c7-2209-4349-8286-9eda05644dcc)


![Image](https://github.com/grommet/hpe-design-system/assets/62117454/26132030-09d9-47e4-a14a-71f9f4ad159b)


I'll be discussing w/ Chris next on whether his team has explored how these would behave in smaller resolutions and follow from there.

**Comment by vavalos5** [comment]
Had a great conversation with Chris on direction of tabs and we both concluded that we shouldn't accommodate vertical tabs. The reasonings are:

- in our guidance, we've mentioned keeping a flat navigation - this would go against our principles.
- we are afraid some people will misuse the vertical tabs and include them with horizontal tabs as well, making the experience more confusing.
- we've gotta make sure within the design system we keep to our principles and designers ensure they leverage our components correctly. There really is no need to have them vertically.
- breaks general convention for experience
- if there's too many vertical tabs within smaller resolutions, designs with vertical tabs are going to either 1. going have to have the tabs show up horizontally or 2. move them into a menu
- in general, adding more complexity to show some information 

Based on the above, @SOjaHPE and @halocline do we want to continue explorations on this ticket or not continue?

**Comment by SOjaHPE** [comment]
@vavalos5  thank you for updating this ticket with the outcome of your discussion with Chris. I'm in agreement with this conclusion. In addition to what you mentioned in the bullet points above.

- We don't have an agreed upon a clean responsive or adaptive solution displaying these vertical tabs in the S and XS breakpoint widths. Having the page reflow, stacking these navigational elements on top of the page content just doesn't work.
- It is a waste of important real estate, now that we have an inline user guide help panel, possible left inline in-app local navigation panel. We're wasting a huge % of our screen to provide the user 'current location' context.

Let me connect with @halocline later today regarding this.

**Comment by halocline** [comment]
@vavalos5 - I like the conclusion and supporting rationale. Can we transform the bullet points you and @SOjaHPE have listed into a draft rationale we can add to the Design System site in the future?

For example, something along the lines of "Considering the UX principles of consistency, simplicity, responsive, ... , the HPE Design System does not support or recommend the use of vertical tabs for the following reasons: 
- fsadf
- adsfasd
- asdfas
- ...

Instead, it is recommended to use ____________ or _____________ ."

This ☝️ plus its review and creating an issue (or submitting a PR) to add this guidance to the Design System site can consider this issue "done." The deliverables for this issue are 1) Create initial design direction vertical tabs.
2) Provide recommendation with accompanying design rationale. The design exploration and direction has been done, the recommendation made with rationale made -- I'd just like us to turn the rationale into a clear statement we put on the HPE Design System site for future reference.

**Comment by vavalos5** [comment]
Absolutely! I'll work on that and create a subsequent ticket to add to our site.
