### ISSUE TITLE
Brand Refresh - share-out

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3212]
## Tasks

- coordinate with Chris to ensure we have HPE brand's voice included

## Things to include

- overview of changes
- why are we changing
- introduction to the migration guide

## Acceptance Criteria

- [ ] share-out regarding v5 theme release scheduled with agenda

**Comment by ericsoderberghp** [comment]
Waiting on:
- release of version 5 of the HPE theme
- Figma updates
- migration guide content for Figma

**Comment by halocline** [comment]
3/31 - 🟢 on track. Scheduled a meeting with Chris to discuss format and request for his involvement.

Next steps:
- Meet with Chris
- Confirm share-out format
- Schedule time(s) for share-out and Q&A

**Comment by halocline** [comment]
4/7 - 🔴 off track. Discussed share-out approach with Chris. Agreed on the following:
- Should speak to a wide audience speaking to HPEXS + some representation from product teams (PM, designers, devs)
- Likely set up as a recording which can be shared out and distributed asynchronously as well. Chris mentioned that this potentially could be represented in some manner on Brand Central as well.
- Agenda should largely be made up of Brand sharing out the "what" and "why" (i.e. the motivations driving the changes and the rationale behind the changes). Limited time reserved for speaking to the "how" (i.e. where do I get the refreshed assets? How do I consume them? What resources are available to me to make my transition successful?). Rest of the time should be an open forum for Q&A where folks may ask questions ("why this? What about that?"). 

Next Steps:
- Chris to propose outline, largely focussed on the "what" and "why" portion.

**Comment by jcfilben** [comment]
@halocline can we close this? I believe this share out has already happened
