### ISSUE TITLE
File Input - add alert icon within file-Input for validation variant- In figma

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#3213]
In figma - we are missing the icon for the validation variant.

![Image](https://user-images.githubusercontent.com/86280029/225213274-5936d83a-ca9d-49b4-aee1-78909a50ce35.png)

**Comment by Keeth-HPe** [comment]
The component is also missing focus and hover elements for the variants, both dark and light theme

- [ ]  Add the focus effect for focus variants

- [ ] Add hover Background for hover variants

**Comment by vavalos5** [comment]
Thanks for sharing and working on this Keeth. I wasn't sure which frame to leave comments or look at so I left comments on both. Thank you :)

**Comment by KennyAtHPE** [comment]
@Keeth-HPe Variants with the alert icons look good. Nice solution on providing a toggle for the alert icon within the fileinput list item component. 

Left two small comments about the dark mode version. Good job on this!

**Comment by Keeth-HPe** [comment]
Thank you @vavalos5  @KennyAtHPE  for looking into the nuances & for the feedback. Appreciate it! 

I have fixed your comments. Request for another round of review :)  Thank you!

**Comment by vavalos5** [comment]
Thank you Keeth, i've reviewed and looked good to me!! 😄

**Comment by Keeth-HPe** [comment]
Thank you! I'm going to merge the file with updates. And this ticket is good to be closed. :)
