### ISSUE TITLE
Export data pattern - Add examples and guidance to Design System Site

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3214]
Follow on ticket from #3169

Please add guidance and examples to the design system site.

[Examples can be found here.
](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?node-id=2426%3A40792&t=XnCUgxUwzGyhSKx0-1)
[Guidance](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?node-id=2426%3A40792&t=XnCUgxUwzGyhSKx0-1)

ToDos:

- [x] Create an Export data container like this: https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8?node-id=2426:40792#385808856 -- This should be implemented aries-site/src/examples/templates/export-data
- [x] Have the export data container be revealed when clicking on "Export devices" from this example: https://design-system.hpe.design/components/pageheader
- [x] Create issue for Export Data page under pages/templates directory and add example for exporting data from a data collection toolbar and a second from a PageHeader. https://github.com/grommet/hpe-design-system/issues/3368

**Comment by vavalos5** [comment]
@JCoder121 Can you link your PR here so I can take a peek at it please 😄

**Comment by JCoder121** [comment]
Link to deploy preview: https://deploy-preview-3356--keen-mayer-a86c8b.netlify.app/components/pageheader

**Comment by JCoder121** [comment]
Link to PR for first 2 ToDos: https://github.com/grommet/hpe-design-system/pull/3356

**Comment by halocline** [comment]
Todos completed and issue created for follow on implementation.
