### ISSUE TITLE
Inline Notifications - Review with stakeholders

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3216]
Follow up on #2886 
[Guidance](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=5091%3A27871&t=B3TfQlbfnhz35Z54-1)
[Figma Component](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=5091%3A29442&t=B3TfQlbfnhz35Z54-1)

---------------------------------------------

Review with:
- [ ] Greg
- [ ] Edgar
- [ ] Derek
- [ ] Sylvia ?
- [ ] Cynthia ?

More TBD

**Comment by halocline** [comment]
@KennyAtHPE has this work been completed? If so, can we close?

**Comment by KennyAtHPE** [comment]
Work has been completed. Component is finalized and published. Closing ticket.
