### ISSUE TITLE
Figma Evaluation - Analyze what colors or other misalignments to the theme

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3218]
Analyze all of our current colors and others to document misalignments to the theme. This is for us to see which changes need to be made in the Figma side and what we need to remove before making changes on #3217

**Comment by vavalos5** [comment]
Adding tickets i've found so far:

https://github.com/grommet/hpe-design-system/issues/3188
https://github.com/grommet/hpe-design-system/issues/3159
https://github.com/grommet/hpe-design-system/issues/3219
Adding gradients and textures in Figma - https://github.com/grommet/hpe-design-system/issues/2940




Other changes:
https://github.com/grommet/hpe-design-system/issues/3161
https://github.com/grommet/hpe-design-system/issues/3152
https://github.com/grommet/hpe-design-system/issues/3027
https://github.com/grommet/hpe-design-system/issues/2941

Uncertainties:
Recreate TextArea: https://github.com/grommet/hpe-design-system/issues/2655
Adjust focus styling on tabs: https://github.com/grommet/hpe-design-system/issues/2680
Tag sizing in Figma: https://github.com/grommet/hpe-design-system/issues/2289
Tip adding to Figma - Do we still need to do this? thought it was recreated in Figma refactored work: https://github.com/grommet/hpe-design-system/issues/2674
Figma plug in testing: https://github.com/grommet/hpe-design-system/issues/2777

**Comment by vavalos5** [comment]
Since we have found tickets that will need further analyze whether we still need to make any other changes after brand refresh. I'm going to create a follow on ticket to make changes since we are focused on making brand refresh changes first.

Follow up ticket: #3226

**Comment by vavalos5** [comment]
Re-opening because Kenny and I feel strong that we should keep it open since we're still finding discrepancies across Figma. Can we keep in the backlog as we continue to add to this?

**Comment by vavalos5** [comment]
3/31 - This is likely to remain open for this sprint too as we continue to add misalignments. We should be closing out at the end of sprint and hope to apply changes after.

**Comment by KennyAtHPE** [comment]
Components that require updating/refactoring in Figma:

- (S) Tabs: page examples and overview section needs to be updated. Figure out how to accommodate for this example. 

![Image](https://user-images.githubusercontent.com/86075038/231396770-ca244718-8dc8-45b9-a1d7-31cb0c45a3e2.png)



- (XS) Menu: overview section needs to be populated
- (S) Search: Needs to be realigned with latest v5 theme
- (XS) Select: overview section needs to be populated
- (XS) Global Header: icons needs to be replaced with icon only buttons
- (L) Lists: requires further exploration on how this component should be refactored. Leaning toward making it a slot component
- (M) Layer: Examples from the layer file within the library folder need to be updated and moved over and to the main DS components file. File then needs to be moved to working files.
- (XS) Footer: Needs to be moved to the main DS component file.
- (XS) Tags: Needs to be moved to the main DS component file.
- (XS) Spinner: Needs to be moved to the main DS component file.
- (XS) RangeInput: Needs to be moved to the main DS component file.
- (XS) Pagination: Needs to be moved to the main DS component file.
- (M) NameValueList: Needs to be moved to the main DS component file.
- (M) Notification: Toasts and Global notifications need to be refactored. Toasts, Global, and Inline needs to be moved to the main DS component file.
- (XL) Datatable: #3258
- (XL) Card: #3065
- (S) Anchor: Requires refactoring
- (S) Accordion: Requires refactoring
- (M) Text Area: Requires refactoring
- (M) Masked Input Requires refactoring
- (S) Stack: Is this component still needed? If so, requires refactoring
- (XL) Templates (page layouts, forms, wizards, etc.): needs to be moved into one singular file

**Comment by vavalos5** [comment]
We can close this since we now have the remaining items we wanted to add within this ticket.

#3226 is a follow on ticket

**Comment by vavalos5** [comment]
- [ ] (XS) Tags : Add t-shirt sizing in Figma
