### ISSUE TITLE
DataTable - Analyze Figma component for refactoring

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3224]
[Figma component](https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-DataTable?node-id=1%3A2&t=3gKi9O3KqLYooZb5-1)
[Brand Refresh related changes](https://github.com/grommet/hpe-design-system/issues/3201)

-----------------------------------------

Our DataTable Figma component has yet to be refactored. We are also noticing that many teams are not using the DataTable component. Teams have also created their own components, and when using ours they oftentimes detach their instances.

### Deliverables
- [x] Explore how other teams are creating DataTables. Gather any relevant links on the way such as master component files, templates, guides, etc.
- [x] Evaluate our current DataTable component. Keep note of:
       - Any issues/bugs
       - Any missing use cases/variants
       - Areas to refactor (check for auto layout, do we need to combine components/variants?, etc.)
- [x] Create tickets for items in Next Steps

---------------------------------------

### Next Steps

As you go along, fill out this section for potential next steps.

- Mark down all the required components, variants, and values that the Refactored components should have.
- Refactor component
- Apply Brand Refresh changes

**Comment by vavalos5** [comment]
Would be great to keep this ticket in mind too when thinking about refactoring.

**Comment by Keeth-HPe** [comment]
Marked the issues and bugs here : https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/branch/HRhETpmdTWiodHNOJoTPf0/HPE-DataTable?node-id=2390%3A13237&t=lanNXC78OwUtSYIg-1

**Comment by Keeth-HPe** [comment]
Closing this ticket as all the issues and bugs are documented and now the component has to be refactored. Created a new ticket for the refactoring process.  #3258
