### ISSUE TITLE
DataTable - Update Figma examples

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3234]
Please update all DataTable examples in Figma so they:
- no longer have examples of the sidebar
- use the correct header
- use the correct filter icon
- update the buttons so they're using the new theme and not deprecated ones
- update the headings

See screenshot below:
<img width="812" alt="Screen Shot 2023-03-24 at 10 36 27 AM" src="https://user-images.githubusercontent.com/62117454/227600040-6cc0cea2-f421-4dac-8ddf-9f6fd9c030cf.png">

- update filtering example to align to site
<img width="862" alt="Screen Shot 2023-03-24 at 10 42 51 AM" src="https://user-images.githubusercontent.com/62117454/227600895-e52af90d-0c9d-47b1-8fd1-db0a30067da9.png">

**Comment by vavalos5** [comment]
Ensure to update spinner examples too when datatable examples are completed as it has datatable examples with spinner

**Comment by SeamusLeonardHPE** [comment]
Closed as table refactor has moved[ component to main file](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=28797-3082)
We have archived and deprected the old file 

Table examples have been [moved to library file](https://www.figma.com/design/fupkQ4sOefx3qUVoV6WfJi/Template-Library?node-id=3886-2)
