### ISSUE TITLE
Brand Refresh - Design Migration Guide

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3235]
Write Designer Migration Guide

- What's the best way we can communicate to designers that breaking updates will come?
- What's the best way designers can preserve the styling of their old designs? Version control?
- Add to the current migration guide on breaking changes designers should expect, and if any, preventative measures they can take

## Acceptance Criteria

- [x] Written and published doc

## Key Content

- [x] Discuss where it should live
- [x] Details of how if you're not using components, updates won't be made
- [x] Details to update components if components are deprecated, detached or not using correct components
- [x] Details of changes to theme

**Comment by KennyAtHPE** [comment]
[Migration Guide](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=8477%3A113355&t=iRKRBGL2gjJ8sOxr-1) has been completed and shared out to the team. Next steps are documented in #3220. Closing out ticket.
