### ISSUE TITLE
Brand Refresh - Refactor Figma components

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3242]
Sub ticket of #3220
[Select component
](https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=103%3A140&t=Im88WfPfCK1WWlFD-1)[Tab component](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=0%3A1&t=VcvtY9iaKwcmi1tY-1)
[Responsive Tabs component](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=0%3A1&t=VcvtY9iaKwcmi1tY-1)
[Menu component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=6062%3A116334&t=FiBlW8OCEWuMVZvk-1)

------------------------------------------

Select, Tabs, Responsive Tabs, and Menu currently have outstanding issues that prevent us from updating them to align with the latest Brand Refresh update.

Effort to complete ticket:
- 1 sprint
- Requires 1 designer (named Kenny) and review from 1 designer and 1 developer

#### Deliverables
- [x] Refactor Select
- [x] Refactor Tabs
- [x] Refactor Responsive Tabs
- [x] Update Menu
- [x] Update FileInput
~~- [ ] Update Search~~
- [x] Send announcement of new components

-------------------------------------------

#### Steps to complete

**Select**
- [x] Consolidate components into one component
    - [x] Align with Grommet component (sizing, responsiveness, states, etc.), apply the latest Brand Refresh updates
- [x] Review component with another designer and developer
- [x] Move component to the great designer system components file
- [x] Deprecate old select component
- [x] Publish new component

**Tab**
- [x] Evaluate whether or not we need to recreate the component entirely or update what we currently have
     - [x] Align with Grommet component (sizing, responsiveness, states, etc.), apply the latest Brand Refresh updates
- [x] Review component with another designer and developer
- [x] Move component to the great designer system components file
- [x] Publish changes

**Responsive Tabs**
- [x] Evaluate whether or not we need to recreate the component entirely or update what we currently have
     - [x] Align with Grommet component (sizing, responsiveness, states, etc.), apply the latest Brand Refresh updates
- [x] Review component with another designer and developer
- [x] Move component to the great designer system components file
- [x] Publish new component

**Menu**
- [x] Align with default buttons (sizing + padding)
<img width="177" alt="Screen Shot 2023-03-28 at 10 18 01 PM" src="https://user-images.githubusercontent.com/86075038/228433701-1c6c3a2f-cfbd-429e-81e9-a272dc582e2e.png">

- [x] Remove this variant
- [x] Review component with another designer and developer
- [x] Push component update

**Comment by SOjaHPE** [comment]
@KennyAtHPE  - just had a conversation with @GinaTaylor - @dianeumoh  and Justin B. are looking for the refreshed tab component to include in their new Wellness and Home page designs. Make sure to connect with them as soon as they are published.

**Comment by KennyAtHPE** [comment]
@vavalos5 @taysea Requesting review on [Select](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=8985%3A115143&t=CmzQbX5wMRH93pkQ-1) and [Tabs + Responsive Tabs](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=5197%3A48199&t=lb2jQHCJvfvPdjE2-1)

Finishing up menu right now so will ping for review on that later today.

**Comment by taysea** [comment]
> @vavalos5 @taysea Requesting review on [Select](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=8985%3A115143&t=CmzQbX5wMRH93pkQ-1) and [Tabs + Responsive Tabs](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=5197%3A48199&t=lb2jQHCJvfvPdjE2-1)
> 

Thanks, dropped a few comments!

**Comment by vavalos5** [comment]
Good job Kenny, they're looking great. Left a few comments.

**Comment by KennyAtHPE** [comment]
@taysea @vavalos5 Requesting review on [menu](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=9007%3A114814&t=dBBdfqB6zCxDJZqq-1)

Not entirely confident with how this one turned out, please comment on anything you might notice.,

**Comment by vavalos5** [comment]
> @taysea @vavalos5 Requesting review on [menu](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=9007%3A114814&t=dBBdfqB6zCxDJZqq-1)
> 
> Not entirely confident with how this one turned out, please comment on anything you might notice.,

Looks good! Left one comment :)

**Comment by KennyAtHPE** [comment]
Components have all been updated, released, and announced. closing ticket.
