### ISSUE TITLE
Update What's New page for Feb.- to Mid April

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3244]
PRr: #3295 

Update the what's new page for the months of February through Mid-April

- [x]  Go back and review all completed tickets
- [x]  Create a list of completed items
- [x]  Set up a PR
- [x]  Get a review
- [ ]  Publish

**Comment by vavalos5** [comment]
4/14 - Will have a PR running by Monday 😄

**Comment by vavalos5** [comment]
#3295

**Comment by vavalos5** [comment]
@halocline @jcfilben ready for review again :)
