### ISSUE TITLE
Data table - Refactor the component

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#3258]
Based on #3224. 

As per the issues and bugs documented, refactor the component 
Apply brand refresh

**Comment by Keeth-HPe** [comment]
- [ ] Remake the Header Cells components with variants
- [ ] Create Header Rows
- [ ]Remake the Cells components with variants
- [ ] Create cell rows ( instead of columns)
- [ ] Create Numerical Value Cells

- [ ] *Data Table with Variants*

**Comment by Keeth-HPe** [comment]
https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/branch/HRhETpmdTWiodHNOJoTPf0/HPE-DataTable?node-id=10589%3A219075&t=qwrbWwnK9WphqnEc-1
Here are all the Atmoic level components created for the Data table. @SOjaHPE I Request you to review it.
Created the basic Data table as well.

To create the overall Datatable, we require the [Vertical tabs as well](https://github.com/grommet/hpe-design-system/issues/3196)

should I pause this ticket and work on Vertical tabs or continue  ?

**Comment by SOjaHPE** [comment]
@Keeth-HPe the data table atomic level component list looked great. Left one comment regarding the numerical identifier column component section, were you able to locate an example use cases?

It believe this table ticket is in good shape overall. Maybe look for a few example data table use cases with some edge case data, truncated strings, multiple stacked strings in a cell, see if verify the atomic components will work when pushed a bit more. Thank you

**Comment by vavalos5** [comment]
I don't want to add a can of worms to this because well, no one does 😄 but, I just met with Sanmid, and I felt that he had a valid point of the idea of including some already made DataTables with variants that include the toolbar (something we need to explore) and pagination. I wanted to document that so we can potentially keep it in mind or consider it in other future iterations.

**Comment by SeamusLeonardHPE** [comment]
Surfacing as part of our branch clean.

Figma related branch linked below:
12 conflicts indicated 

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/branch/HRhETpmdTWiodHNOJoTPf0/HPE-DataTable?type=design&mode=design&t=THYnkeFbUKnDnm3h-1

Review if changes should be backed up onto new file & this file deprecated during current file refactoring



![Image](https://github.com/grommet/hpe-design-system/assets/135040188/a4cfa55b-3e83-4813-bd1d-6e7d010a81cc)

**Comment by SeamusLeonardHPE** [comment]
Resurfaced do to our branch cleaning projects.
https://hpe-my.sharepoint.com/:x:/p/kenny_tran/EagZuftPiF9Hj2m-hR6hiMMBx1_aL8mrD9ZscMFTtQhAVQ?e=ghXMmX

Figma branch linked:

Archived branch to facilitate tidy up.
[File can still be retrieved](https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/branch/HRhETpmdTWiodHNOJoTPf0/HPE-DataTable?type=design&node-id=1%3A2&mode=design&t=aE0GfDqZHh8pFwYj-1) but should not be merged into main.

**Comment by SeamusLeonardHPE** [comment]
Closed as will be covered in refactor ticket #3705
