### ISSUE TITLE
DataTable Customization Guidance Update

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3260]
During today's GLCP UX Design Critique - Rena G. showed a design that incorrectly incorporated the column selection/order feature in the DataTable toolbar.

**The following DS guidance was referenced**

- [DataTable Customization](https://design-system.hpe.design/templates/datatable-customization) - example shows the toolbar + DataTable w/ the Column Select/Order icon button on the left near the view controls.
- In the [Anatomy of a customizable DataTable](https://design-system.hpe.design/templates/datatable-customization?#anatomy-of-a-customizable-datatable) guidance it references the following
- The action is references as the 'Edit' icon which meant the designer interpreted the use of a typical CRUD edit 'pencil' icon was used by the designer. 
- The guidance also recommends the 'Edit' icon should be next to the 'Actions' menu for the data table on the right side above the data table.

**Scope of work**

- [x] Update the example to show tooltips for the Column Select/Order control - referencing the control as 'Manage Columns'. https://github.com/grommet/grommet/issues/6743
- [x]  Updated guidance to call out the correct location of the Column Select/Order controls to be located on the left with other 'View' controls to match to example at the top of the page. 
- [x] Update the content to reference the column control as 'Manage Columns', not the confusing 'Edit' CRUD action.

**Comment by SOjaHPE** [comment]
Example of the page wireframe created by the designer

![Image](https://user-images.githubusercontent.com/83719939/229948565-64eae3f0-ce92-4019-a010-ae9f895dbf61.png)

**Comment by SOjaHPE** [comment]
Created a PR - https://github.com/grommet/hpe-design-system/pull/3262

**Comment by halocline** [comment]
Should this be closed since the PR merged?

**Comment by SOjaHPE** [comment]
Acceptance criteria to close this ticket -

Dev to update the Data table customization coded example to show a 'Manage Columns' tooltip for Column Select/Order control

**Comment by halocline** [comment]
☝ - DataTableColumns is used in this implementation. I don't believe the caller has the ability to specify a tooltip. Created: https://github.com/grommet/grommet/issues/6743
