### ISSUE TITLE
Empty State

### ISSUE THREAD

**Issue by jeffstolz** [grommet/hpe-design-system#3263]
Referencing the following issue on the Program Increments board:

https://github.com/grommet/hpe-design-system/issues/3221

**Comment by jeffstolz** [comment]
I believe I need to transfer the issue from the "Program Increments" board into the "Current Sprint" board but want to check with the team before doing so.

**Comment by jcfilben** [comment]
Closing, Empty State work can be tracked in https://github.com/grommet/hpe-design-system/issues/3221
