### ISSUE TITLE
Update DS figma global header component to match the GLCP new version

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3269]
This requirement is related to jira ticket [GLCP-42637](https://hpe.atlassian.net/browse/GLCP-42637)

The only contents in the jira ticket is the following comment:

- Gina can provide more context on what’s required here. (Points of contact: Chris & Justin)

ToDos:
- [x] Bring Figma component inline latest design
- [x] Review w/ Chris and Vicky
- [x] Publish changes
- [x] Create issue to update the Global Header on DS site

**Comment by KennyAtHPE** [comment]
4/27 Update

Kurt and I chatted with Chris and he mentioned that:
- The logo has been changed from 48px to 36px
- The navigation buttons have been changed from medium to small
- The icons should be small icon only buttons
- The user profile may or may not be changed from an Avatar (initials variant) to a profile icon

He is reaching out to Justin B. for more confirmation.

**Comment by KennyAtHPE** [comment]
Confirmed w/ Justin that the first three changes need to be applied.

The change from an Avatar to a profile icon is currently just a recommendation and hasn't been solidified yet by Gina.

**Comment by KennyAtHPE** [comment]
4/28 update:

The following changes have been made to the Global Header component:
- The logo has been changed from 48px to 36px
- The navigation buttons have been changed from medium to small
- The icons were changed to small icon only buttons
- The navigation tabs padding has been reduced from 24px to 12px inbetween
- Height of the global header has been changed from 72px to 60px
- A new dropdown menu has been added next to the logo, there should be a 48px padding between
- The default profile has been switched from an Avatar to a profile icon. Users can still switch between having an Avatar w/ initials or a profile icon

Questions we had:
- Is the spacing between icons supposed to be 24px or 12px? Asked Chris for confirmation.

------------------------
Chris's [file for the global header component](https://www.figma.com/file/6lbTKt1JAhpRVmmcHQ4s4t/Header-Comparo?node-id=0%3A1&t=5dYnDoYEPeljMy1d-1)
Pinging @vavalos5 for [review](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=9735%3A115021&t=04AYgwyqu90K0gv5-1)

**Comment by vavalos5** [comment]
Looked good to me, good job! 👏

**Comment by KennyAtHPE** [comment]
Figma component has been finalized and published. Follow on ticket is #3330. Closing ticket.

**Comment by KennyAtHPE** [comment]
5/2 share out notes:

- Search and help icons are smaller than the other icons. We currently do not have an appropriate-sized icon for these however Eric and Chris are working on this. Will need to follow up with them.
- Stack badging icon needs to be updated to meet the brand refresh change. Connect w/ Vicky on these changes.

**Comment by vavalos5** [comment]
As a ticket to help close this out, i've created #3333 . I'll be connecting w/ Kurt to swarm on this issue.

**Comment by MikeKingdom** [comment]
What happens for responsive? (ie smaller sizes where the category nav won't fit?)

**Comment by vavalos5** [comment]
@MikeKingdom This is something that we're still awaiting from Gina.

**Comment by vavalos5** [comment]
Kurt and I replaced the buttons on [Global Header](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=3028%3A58403&t=1Pga7BJ5yKjvrae2-1) with badge with our new button w/ badge and published.

Adding @taysea for a final review before closing.

**Comment by vavalos5** [comment]
Kurt and I have updated the Global Header to reflect the newest button changes with the badge. This is done!! :)
