### ISSUE TITLE
Design Tokens — Stakeholder share out

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3310]
Chris, Ashley, and Joelle are organizing a share out of Design Tokens work with stakeholders (Chris is in charge of determining the appropriate attendees). Eric and myself will be involved to demo the dev side of the work. This ticket can track the progress.

- [ ] Schedule and conduct design tokens share out
- [ ] Create follow on tickets based on stakeholder feedback

**Comment by taysea** [comment]
This is likely going to occur 5/11 instead of next week because Chris is attending Tech Con in person.

**Comment by halocline** [comment]
@taysea can this be closed?

**Comment by taysea** [comment]
Yes this can be closed. Closing.
