### ISSUE TITLE
Barebones NextJS + React Server Component app

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#3319]
Parent issue: https://github.com/grommet/hpe-design-system/issues/3320

Tasks:
- [x] create a NextJS (v13+) application that demonstrates a React server component and a client component.
  - Should use the `app` directory instead of the legacy `pages` directory
  - Should use vanilla React + HTML (i.e. no dependencies on other libraries)
  - Note any findings at this stage
- [x] add styled components to the app.

Deliverables:
- [x] share out information gathered from this exercise to the team

**Comment by jcfilben** [comment]
Update 4/28: I have done a bit of research on react server components and have started setting up a NextJS application

**Comment by jcfilben** [comment]
Update 5/5: 🟢 I have a NextJS application created that demonstrates server and client components. I have also added styled components to the app and used them to style both server and client components. I have scheduled a share out with the team on 5/9.

**Comment by halocline** [comment]
Thank you for the share out, @jcfilben! Great job, investigation, and dissemination of information. 

Do you want to add the link to the recording here, then this can be closed out, correct?

**Comment by jcfilben** [comment]
Yup we are good to close this out! Here is the recording link: https://hpe-my.sharepoint.com/:v:/p/jessica_cheyenne_filben/EdOeAIL2XAZCn3w0jmK-8GYBO0AIRkMptHxlNNGL46RcCg
