### ISSUE TITLE
Fix content column layout issue

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3357]
The  [Grid page](https://design-system.hpe.design/components/grid), isn't rendering correctly, there is content from one column overlapping content in the next. Looks like the column structure isn’t working correctly.

The layout issue was replicated in both chrome and safari mac browsers

**Comment by SOjaHPE** [comment]
Reference the following screen grabs - 

![Image](https://github.com/grommet/hpe-design-system/assets/83719939/eaa92031-cd26-4de5-b6c5-bfb4d4f7c18d)
![Image](https://github.com/grommet/hpe-design-system/assets/83719939/db704180-aaa1-4ab1-ad7e-89a100b76528)

**Comment by halocline** [comment]
Closed by https://github.com/grommet/hpe-design-system/pull/3360
