### ISSUE TITLE
Card component examples need to be refreshed to follow v5 HPE Theme

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3358]
Several [card component](https://design-system.hpe.design/components/card) examples that include secondary buttons need to be refreshed to use the latest v5 HPE Theme 2 px wide button border, not 1px as currently rendering.

See the screen capture as a point of reference:

![Image](https://github.com/grommet/hpe-design-system/assets/83719939/828997d2-8e3c-473c-9ab0-99aba93bd922)

**Comment by halocline** [comment]
Closed by https://github.com/grommet/hpe-design-system/pull/3360
