### ISSUE TITLE
Check and update all embedded component pages examples with figma links

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3359]
Problem: The HPE Design System guidance site has embedded links in the pattern examples that have not been updated to point to the latest Figma Refresh HPE Design System - components sub pages.

Check and update all pattern examples w/ old embedded figma links which point to ‘pre-figma refresh’ individual figma pattern pages. These links should be redirected to point to the parent HPE Design Systems - component  sub component pages.

Example - [Button component](https://design-system.hpe.design/components/button) figma file links to this [old figma file](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?type=design&node-id=1-2&t=zwjFY9cMV88Nrh31-0), should link to the new [HPE Design System Components button page](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=4489%3A78687&t=mFMVF2JEjHyLj0aH-1)

Acceptance Criteria

- [x] Review the different [https://design-system.hpe.design/](https://design-system.hpe.design/) component and guidance pages and check of the cross links to the corresponding figma is linked correctly
- [x] Create a list of page URLs and the anchor links to incorrectly linked figma files, provide the correct link that can be used to update the pages
- [ ] Try to 'edit this page' functionality at the bottom of each page to make the updates and create/submit PR's

**Comment by ashifalinadaf** [comment]
- I did go through each Component and Layouts on Design system site.
- Checked for all the cross links to the corresponding Figma files. 
- Created **[a file](https://hpe.enterprise.slack.com/files/U01MW4X7L3D/F05CXLBS28P/_3359_-_check_and_update_all_embedded_component_pages_examples_with_figma_links_xlsx)** where links need to be updated to the component/layout with old links or missing links.

**Comment by ashifalinadaf** [comment]
Revising the Design System sites for any additional links that are missing.
updated the file with additional links. 

Created PR for each component with updated links. 
PRs can be found in the [Same file](https://hpe.enterprise.slack.com/files/U01MW4X7L3D/F05CXLBS28P/_3359_-_check_and_update_all_embedded_component_pages_examples_with_figma_links_xlsx)

**Comment by ashifalinadaf** [comment]
@taysea @halocline @jcfilben 
If anyone of you can have a look at the following PRs and let me know if we can resolve them. 
if there are any issues please let me know. 

https://github.com/grommet/hpe-design-system/pull/3414, https://github.com/grommet/hpe-design-system/pull/3415, https://github.com/grommet/hpe-design-system/pull/3416, https://github.com/grommet/hpe-design-system/pull/3416
https://github.com/grommet/hpe-design-system/pull/3417, https://github.com/grommet/hpe-design-system/pull/3418, https://github.com/grommet/hpe-design-system/pull/3419, https://github.com/grommet/hpe-design-system/pull/3420, https://github.com/grommet/hpe-design-system/pull/3421, https://github.com/grommet/hpe-design-system/pull/3422, https://github.com/grommet/hpe-design-system/pull/3423, https://github.com/grommet/hpe-design-system/pull/3424, https://github.com/grommet/hpe-design-system/pull/3424, https://github.com/grommet/hpe-design-system/pull/3425, https://github.com/grommet/hpe-design-system/pull/3426, https://github.com/grommet/hpe-design-system/pull/3427, https://github.com/grommet/hpe-design-system/pull/3428.

**Comment by ashifalinadaf** [comment]
- Changes have been made to the PRs with conflicting links for Figma. Raised new PR for the same. 

- Following errors were found during the DS site inspection. Please have a look if these can be raised as a new issues. 

1. Github Edit page error as '404 not found' for Layer component. DS url: https://design-system.hpe.design/components/layer Github url: https://github.com/grommet/hpe-design-system/tree/master/aries-site/src/pages/components/layer.mdx
3. https://design-system.hpe.design/templates/scrolling-and-pagination with 'coming soon' display ( I am not sure this is already been discussed.)

**Comment by taysea** [comment]
@ashifalinadaf The layer link has been fixed now.

**Comment by ashifalinadaf** [comment]
https://github.com/grommet/hpe-design-system/pull/3449

**Comment by halocline** [comment]
Since https://github.com/grommet/hpe-design-system/pull/3449 got merged, can this be closed?

**Comment by ashifalinadaf** [comment]
Yes, we can close this. 
As all the 'refactored Figma component links' have been updated.
