### ISSUE TITLE
DS/Figma feature: New icon for GLCP Contextual Help

### ISSUE THREAD

**Issue by bettyad** [grommet/hpe-design-system#3361]
### What component does this request relate to?

HPE Icons, Global Header

### Describe the feature you'd like to request.

Gina Taylor created a new icon for Contextual help, and need to add it to the HPE Icons.

### Links to Figma files with use cases or ideations from you.

https://www.figma.com/file/lO9SS8xsx1uS42mUw2lLyJ/In-App-Contextual-Help?type=design&node-id=6720-108402

This is the icon
![HPE Icon- Contextual Help](https://github.com/grommet/hpe-design-system/assets/20525083/c8b10b3c-4781-4222-bd70-dcd5425660bd)

**Comment by SmWorkGitHub** [comment]
Update following discussion with Lauren, Chesley, and Mike:  Please hold on this until we follow up. The user-preferred icon in the context of the global header is different to the one requested above. That icon was preferred stand-alone, but users did not want two icons with question marks in context. Chris C also had concerns about a second question mark icon.

**Comment by SmWorkGitHub** [comment]
@jcfilben I met with Lauren and Mike K tihs morning. Lauren gave more details on the user research and, with that additional info, we came to the same decision Gina did. So please go ahead with creating this "? on a book" icon.
