### ISSUE TITLE
Actions' Menu - Adding button chrome (as in secondary button) for greater visual prominence and discoverability.

### ISSUE THREAD

**Issue by ashifalinadaf** [grommet/hpe-design-system#3373]
During the discussion of ticket #3290 Scott suggested adding the button chrome (as in secondary button) to actions' menu for greater visual prominence and discoverability.

Need to try out the actions menu button guidance change, gather feedback and justification if change of the design wouldn't be a recommended direction.

**Comment by ashifalinadaf** [comment]
I had a initial discussion with the GLCS team on using the action menu as a secondary button (Button chrome for increased prominence and discoverability.

Some of the inputs from the team as below: 
- Chrome can be used to highlight the action menu. 
- It will make things complicated, confusion for the user. 
- Most of the users can easily identify the action menu as its the only button, no need for highlight. 
- Square grey border can be added to the action menu than button chrome (HPE brand - Green) 
- Existing action menu working good and there is no need for any changes.

**Comment by ashifalinadaf** [comment]
Gathering some inputs on the previous iterations on the action menu. 
Research on the other design systems to see how action menus are being used.

**Comment by vavalos5** [comment]
Met with Asif earlier. He mentioned he was unable to find any kind of guidance across other frameworks. I'll be doing some research to see if I can find anything in regards to this to help out.

In addition, I mentioned to Asif to gather examples of different menus instead to compare and analyze.

**Comment by vavalos5** [comment]
[Carbon ](https://carbondesignsystem.com/components/overflow-menu/style/)
[Material.io](https://m3.material.io/components/menus/overview)
[Salesforce ](https://www.lightningdesignsystem.com/components/page-headers/)

[Here are all of the use cases](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?type=design&node-id=61%3A4086&t=CbNOH3HeOeekzDZ6-1) I had previously collected when working on PageHeader. 80% of use cases are using menu with no border. In addition, when looking at other examples such as GitHub, they're not using the secondary button as an action menu button. I think we should keep our menu as is. 

You can also find previous research and examples gathered [here](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?type=design&node-id=5%3A31&t=CbNOH3HeOeekzDZ6-1).

Plus, the feedback you received from teams is helpful to back this up.

**Comment by ashifalinadaf** [comment]
- Based on the analysis of the examples and design systems most of the use cases doesn’t use action menu with border (stroke). Menu component is being used as a default button. 
- Feedback from the GLCS team was also in view of border stroke will create more confusion that any use. 
- I’d suggest not to move forward with changing the menu component with border stroke for increased prominence for now. 
- If there are any use cases in future that has issues with visual weight to action menu we can have a look into it. 

Research file - [Figma ](https://www.figma.com/file/qo85m6K5Sti6Il4dAoC8bX/HPE-Menu-Component---Research?type=design&node-id=2%3A5369&t=0Xr9bzQ7GzaN2olk-1)
