### ISSUE TITLE
Order of button placement - Button order of the 'action menu' and other buttons(primary/secondary/default).

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3387]
Original question was phrased by @ashifalinadaf (@halocline just turned the note into an issue)

Should actions menu be placed after primary button or vice versa?

- [ ] Follow up with Bhim when work is completed.

**Comment by vavalos5** [comment]
Is this in regards to the PageHeader @ashifalinadaf?

**Comment by KennyAtHPE** [comment]
Current DS button ordering [guidance](https://design-system.hpe.design/components/button?q=butt#button-ordering)

**Comment by ashifalinadaf** [comment]
This is related to Page header button properties too @vavalos5

**Comment by ashifalinadaf** [comment]
@KennyAtHPE I did go through the guidance but couldn't find the order of action menu with Primary/secondary button. 
Are we considering action menu as default button here?

**Comment by KennyAtHPE** [comment]
> @KennyAtHPE I did go through the guidance but couldn't find the order of action menu with Primary/secondary button. Are we considering action menu as default button here?

@ashifalinadaf our current menu is styled the same as a default button. Additionally, our current guidance states that primary buttons should always go first, regardless of whether or not the buttons are right or left-aligned. Taking into account both these points, I would expect the menu to go last in the button group.

It could however be helpful to see how other design systems are handling this.

**Comment by ashifalinadaf** [comment]
I will have a look and post here, thanks for the comment. 

> > @KennyAtHPE I did go through the guidance but couldn't find the order of action menu with Primary/secondary button. Are we considering action menu as default button here?
> 
> @ashifalinadaf our current menu is styled the same as a default button. Additionally, our current guidance states that primary buttons should always go first, regardless of whether or not the buttons are right or left-aligned. Taking into account both these points, I would expect the menu to go last in the button group.
> 
> It could however be helpful to see how other design systems are handling this.

**Comment by MikeKingdom** [comment]
Although there is styling overlap, I think it's important to note that an action menu is not a primary or secondary button and we should be careful not to think of a menu in terms of a primary button. I feel like it's getting too confused with one just because of some styling.

**Comment by SeamusLeonardHPE** [comment]
Hey Team, 
I duplicated another Figma file to use as a research template for this ticket.

Pulled in relevant components & linked to documentation:

- Buttons
- Action Menu (Thanks Mikes previous comment)
- Page header (Since its upstream of the button order)

Please let me know where should this file reside (since its currently in mydrafts) and any components Ive overlooked that will impact this. 


https://www.figma.com/file/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?type=design&node-id=2%3A37210&t=EfM0qTRHq7XGWf0P-1

The second page contains a quick mock of of a right/left aligned button group component, but it might suffer from over nesting!

**Comment by vavalos5** [comment]
> Hey Team, I duplicated another Figma file to use as a research template for this ticket.
> 
> Pulled in relevant components & linked to documentation:
> 
> * Buttons
> * Action Menu (Thanks Mikes previous comment)
> * Page header (Since its upstream of the button order)
> 
> Please let me know where should this file reside (since its currently in mydrafts) and any components Ive overlooked that will impact this.
> 
> https://www.figma.com/file/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?type=design&node-id=2%3A37210&t=EfM0qTRHq7XGWf0P-1
> 
> The second page contains a quick mock of of a right/left aligned button group component, but it might suffer from over nesting!

Hi @SeamusLeonardHPE when we work on a component or template that is already pre-existing, we have a folder in the Design System section in Figma called "Working Files" (see image below). There you'll find files we've previously worked out of prior to transferring the final results to the "[HPE Design System Components](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=0%3A1&t=rGQvbp9S4LtiycEi-1)" Library.
![Screen Shot 2023-06-08 at 9 07 24 AM](https://github.com/grommet/hpe-design-system/assets/62117454/95a4dee6-8efb-4bd1-a714-9830bb96fdfc)

In the this "Working Files" folder, you'll find the buttons Figma file we worked out of. Here, all of the research and use cases can be found. Notice we have a "[research and use cases](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?type=design&node-id=4650%3A9438&t=FiPZVantR5QHVD7z-1)" page here. Please work from there :) 

Let me know if you have further questions, hope this helps!

**Comment by SeamusLeonardHPE** [comment]
Adding in some links in relation to the work previewed during show & tell. Ive aded tome text into these screens to signify their state.

Desktop - 
https://www.figma.com/proto/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?page-id=7%3A32501&type=design&node-id=7-32502&viewport=625%2C390%2C0.63&scaling=scale-down

Tablet - 
https://www.figma.com/proto/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?page-id=14%3A39959&type=design&node-id=14-39960&viewport=503%2C531%2C0.72&scaling=scale-down 

Mobile -
https://www.figma.com/proto/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?page-id=7%3A32500&type=design&node-id=7-32503&viewport=365%2C329%2C0.87&scaling=scale-down


Those prototypes contain are left and right aligned button groups variants in accordance with the guidance.
![Image](https://github.com/grommet/hpe-design-system/assets/135040188/e20c93aa-6f84-4725-8c37-4839c97b06c4)

I added a variation where the "action menu/overflow menu" is aligned which a higher priority than the primary button  (as I understood was a question for this ticket to resolve), however thats not a pattern I have seen anywhere In the documents. 

Do we have set rules for how many buttons can be displayed at given breakpoint, along with rules for how the "action menu/overflow menu" should be displayed (text or icon only and at what break points).

So 3 primary questions for now

- [ ] - Action/overflow menu position in relation to alignment
- [ ] - Button number to display at  breakpoints
- [ ] - Action/overflow menu visual (word vs icon at breakpoints)


When those are I can investigate the best way to add variants that obey those rules into a component.

Link to working file ( Ill import this work into the correct working file tomorrow)

https://www.figma.com/file/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?type=design&node-id=0%3A1&t=AGzE6WutnEJmVQvB-1

**Comment by SeamusLeonardHPE** [comment]
@SOjaHPE can you review the previous note.

**Comment by ashifalinadaf** [comment]
Discussed with @SeamusLeonardHPE on different use cases that can be collected and suggested to look into [Figma file](https://www.figma.com/file/BHp0KrOcPvbnzNyshfHkd8/HPE-Page-Header?type=design&node-id=2%3A3&t=GfyYX6QNhNTqkity-1) that were collected during the research of Page header component #3290. 
Also suggested how material design that use react js can be taken as a reference to our guidelines. Overflow menu is used at the right of the page header. 

![image](https://github.com/grommet/hpe-design-system/assets/132882230/5d1433c0-8bda-4b0e-805a-9e7f703fa34f)

**Comment by SylviaShenCC** [comment]
Hi team

these are some more examples of page-level actions button placement   [](https://www.figma.com/file/fNJhhmEO66r8pfFuBEp0Dk/GLCP-Component-research?type=design&node-id=1609%3A98788&t=yKFGvboiy7Nav0H9-1)

Based on my observations, menu buttons are commonly utilized in detail pages within GLCP, where the narrow layout restricts space in the page header section. In my opinion, implementing predictable locations for the menu button could enhance the user experience. Although I'm unsure about the specific challenges in Grommet or do against the button placement rule in the design system, I think establishing a consistent placement for the menu button would allow users to become familiar with its location. This would result in smoother and more intuitive interactions, especially for actions that have less visibility since they are hidden within the menu button.

**Comment by SeamusLeonardHPE** [comment]
Based on feedback from Sylvia, Revanth, Bhim and Edgar along with comments in this thread.


Variants that show various orders & styles so we can share and discuss options.

https://www.figma.com/file/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?type=design&node-id=283-42762&t=xI38ZHAWNUgIBlvJ-4


The first draft of some rulesets based on feedback  gathered during research.

https://www.figma.com/file/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?type=design&node-id=204-41223&t=xI38ZHAWNUgIBlvJ-4

@SOjaHPE @vavalos5 @ashifalinadaf @halocline

**Comment by ashifalinadaf** [comment]
I'd suggest to go ahead with the current button ordering. 
Primary/secondary buttons have the most preferred actions than Action menu. 
Secondary button can be put under action menu with first dropdown option. 
Assuming there will be rare cases of primary and action menu being together action menu being shifting may not have much of bad user experience. 
We can set the rules for using the action menu hierarchy only after the primary and secondary button. 

Shown below is the order I'd suggest to go ahead with, 
<img width="842" alt="Screenshot 2023-06-21 at 7 14 01 PM" src="https://github.com/grommet/hpe-design-system/assets/132882230/89358d46-a543-4c7b-acc7-574628a00d24">

**Comment by SeamusLeonardHPE** [comment]
Thanks @ashifalinadaf 

Feedback from consumers of the system has mostly indicated their. desire to see the actions right aligned, which would mirror the layout above table data section, and provide a consistent location for users to discover non primary actions.



![Image](https://github.com/grommet/hpe-design-system/assets/135040188/1ba449a8-9e70-4c2e-8459-ce64925a5d47)




This does raise the question about styling the action menu button (adding chrome ticket) to make its importance stand out. The following image is just an example, but would do 2 things, 
1- raise visibility of the action menu
2- avoid re-using the secondary style which might lead to confusion

The similarity of styling between a styled button with right aligned icon (whether default or secondary style) & an action menu is problematic 

![Image](https://github.com/grommet/hpe-design-system/assets/135040188/6d3c14a3-0e01-43d2-9dae-126746969466)

**Comment by vavalos5** [comment]
Nice work @ashifalinadaf and @SeamusLeonardHPE. I just got around to reading your guidance and like the direction. Based on the mixed feedback you've received from different stakeholders, I feel that this is a great candidate to test the ordering of the buttons - that way research can be our back up and reasoning behind direction.

**Comment by vavalos5** [comment]
Seamus, feel free to add a different ticket for this problem that was brought up during GLCP Crit. if you feel it isn't a part of this ticket scope, but wanted to put it in here in case we want to consider it:

The action button is hanging out at the far right when on a XL view, can the action button be moved further in so it’s not so far out? Adding[ Figma link](https://www.figma.com/file/9JDPwHsK6dnut8HWXtsdOb/branch/1GmOWvQBhlmyMbftWww0Xr/API-Management?type=design&node-id=4600-56289&mode=design&t=jA5GFSpIFby6YPrV-0) and example below

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/49ff76ea-c8e2-4c25-9c01-bf76378eae7b)

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf @SOjaHPE @KennyAtHPE @halocline 

I've added in my recommendations based on research & added in the 2 templates for "problem statement" and a 'discovery summary' that should serve as as an intro/directory for the research.


Link to my recommendations where Ive included rules on alignment, order & breakpoints. Please review and let me know anywhere my logic is flawed or my definitions need work.

https://www.figma.com/file/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?type=design&node-id=394-15475&mode=design&t=kuHUtfbAvMQyTeOh-4

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE left a couple of comments in your file. It was a bit hard for me to go through everything in depth due to the amount of content (not sure where my focus should be). If availability allows, happy to hop on a call to discuss further.

**Comment by halocline** [comment]
> @KennyAtHPE @ashifalinadaf Thanks for the review. Agreed there is a lot of rules & content in there.
> 
> As suggested by Ashif I think we should proceed by just answering the initial ticket question: "Should actions menu be placed after primary button or vice versa?"
> 
> My proposal based on research is that **action menu appears on the right on all breakpoints.**
> 
> Additional discussion and rule suggestions that arose during this ticket a (for when primary, secondary etc can be used, how many buttons per break point etc) can be resolved in subsequent and more focused tickets and my research can be added into those tickets.

Given this, I recommend we close out this issue with recommendation by creating a follow on issue for:
- Order button placement - Finalize design direction with design rationale

**Comment by halocline** [comment]
Closing with this follow on work: https://github.com/grommet/hpe-design-system/issues/3478
