### ISSUE TITLE
DateTime Format - Review and make recommendation about adopting Microsoft's guidance on DateTime formatting

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3388]
Parent Issue: https://github.com/grommet/hpe-design-system/issues/2463

Storage is adopting Microsoft's guidance on DateTime formatting. Please review Microsoft's guidance and make recommendation for whether or not the HPE Design System should also adapt this guidance.

ToDos:
- [x] Review "background" provided on #2463 
- [x] Review Microsoft's DateTime formatting guidance.
- [x] Make recommendation on aspects HPE Design System should/should not adopt.

Deliverable:
- [x] Share-out with team either in Show & Tell or in dedicated session.
- [x] Recommendation documented in comment in this issue. Link to comment from here: [Recommendation]().

**Comment by KennyAtHPE** [comment]
6/20 Update:

Have been preoccupied with support for ASP and intern planning. Will add my rec and next steps for this ticket by EOD and send it out to the team for review.

**Comment by KennyAtHPE** [comment]
After reviewing: 
- Microsoft's DateTime formatting guidance
- Storage's proposal
- Atlassian
- Medium articles
- Collins Dictionary
- International System of Units (SI)

My recommendation on how to abbreviate units of time:
- Second, Seconds - sec
- Minute, Minutes - min
- Hour, Hours - hr
- Day, Days - day, days
- Week, Weeks - wk
- Month, Months - mo
- Year, Years - yr

Qs from Storage and rationale:
- **Should we show plural vs singular? Ex. secs, mins, hrs, days, wks, mos, yrs**
        - Do not use plurals for abbreviations. Days can and should be used since it is not abbreviated.

- Adopt Microsoft UI rules for abbreviation, but instead use “hr” for hours and “day or days”?
     - Yes, these should be used since they are clear to users and fitting for HPE use cases.
     - Keep all abbreviations consistent to 2-3 letters
     - Using these longer abbreviations could help eliminate confusion in use cases where DateTime abbreviations may appear alongside other abbreviations.
     - It is clearer to read and quicker to digest: ex.12 days 4 hr ago vs. 12 d 4 h ago

--------------------------------------------------------------

Next steps:
-
- Create a DateTime Format page in the Foundation section on the DS site
- Explore and include within the new page:
    - Use cases + examples on when/when not to use these abbreviations
    - Zero padding within dates
    - Locale-specific formatting
         
Follow up ticket
