### ISSUE TITLE
NameValuePair - Adding all the variants into one single component.

### ISSUE THREAD

**Issue by ashifalinadaf** [grommet/hpe-design-system#3440]
It has come our notice that due to a lot of separated components in NameValueList, NameValuePair, and NameValueGrid (is this a separate component from NameValueList?) it was confusing for the designers to choose the correct ones. 
Chandan (From GLCS) has come up with a solution for adding all the variants into one single component for easy toggle between the variants. 
[Figma ](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/branch/YppI5Jh0X4EUiqm69yzr5q/HPE-Name-Value-List?type=design&node-id=2%3A87&mode=design&t=bBVHxOJtawziQwAr-1)

Deliverables: 
1. Review the design variant submitted. 
2. Create a branch and add all the variants into one component with toggles. 
3. Check with other designers and developers. 
4. Merge with the main branch. 

**Success Criteria**

NameValueList: Controls the layout of the NameValuePairs
- [ ] Controls the width/alignment of the name for the NameValuePairs (nameProps)
- [ ] Controls the width/alignment of the value for the NameValuePairs (valueProps)

NameValuePair: controls styling of what they display
- [ ] Can accept string
- [ ] Can accept number
- [ ] Can accept custom element

**Comment by ashifalinadaf** [comment]
**1. Reviewed the design variant submitted by Chandan -** 
- Some of the proposed variant properties can be incorporated Like orientation/ length/ Icon. 
- The design has an option for having icon for Name and Value at eh same time- which is against what DS site guidance, DS guidance suggest using icon for either Name or Value to avoid unnecessary visual noise and distract from vital information.
-Need to create a new branch to retain all the variants. 

Created a [Figma](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/branch/liKNgKYkAeGdCElbGitZVc/HPE-Name-Value-List?type=design&node-id=798-1484&mode=design&t=PswsjTWEgsyIv4zF-11) branch and some initial component with important variants have been added. Added appropriate toggles for the variants. 

@KennyAtHPE If you can have a look let me know if we can have a chat on that.

**Comment by KennyAtHPE** [comment]
Ashif and I were able to connect last night to go over the current status of the component. I helped answer a couple of his questions on how what variants are needed and how best to create them. We will be focusing on the NameValuePair component for now and a follow on ticket (if there is time during this sprint we may be able to fit it in this ticket) will be created for the NameValueList and NameValueGrid components.

I did not see any blockers.

**Comment by ashifalinadaf** [comment]
Inputs from the @taysea included using the name/value t-shirt sizing for to make it more aligned with the grommet. 

Should be able to use the t-shirt sizing for Name and Value. 
as per the DS guidance default size for **Name is small** and **medium for Value.** 
We can modify the **width sizes** for name value pair with following sizes. 
Name - Small and X-small 
Value - Medium and Large 

And also regarding the alignment - need to explore on the use cases to involve right alignment options for both name and value.

**Comment by ashifalinadaf** [comment]
Created another [component ](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/branch/liKNgKYkAeGdCElbGitZVc/HPE-Name-Value-List?type=design&node-id=3591-4144&mode=design&t=sbEJ4PRf0LnYS8C4-11)which aligns more with the grommet part of name value pair. 
@KennyAtHPE If you can have a look and tell which component is more appropriate to finalise and let the designers use.

**Comment by KennyAtHPE** [comment]
Reviewed the two components. The second component is definitely more aligned with our Grommet component. Left some comments on that component.

**Comment by ashifalinadaf** [comment]
Created a final[ component ](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/branch/liKNgKYkAeGdCElbGitZVc/HPE-Name-Value-List?type=design&node-id=798-1431&mode=design&t=3DObrtmhmmeHKO9G-11)with all the feedbacks and aligning with grommet. 
@KennyAtHPE if you can have a final review on this.

**Comment by taysea** [comment]
@KennyAtHPE @ashifalinadaf I connected with Matt and it would be valuable to make the component refinements to align with Grommet as part of this work. This will help enforce design to dev parity. Happy to connect on a call to walk through the Grommet component structure at any point.

**Comment by taysea** [comment]
@KennyAtHPE With what I talked about with Matt, he felt comfortable leaving the work as part of this ticket. I updated the success criteria above of what should be achieved before closing.

**Comment by KennyAtHPE** [comment]
After discussing with Asif, Taylor, Matt, and Scott, I'll be closing this ticket and tracking the rest of the work in #3484. The scope of the new ticket will include creating the NameValueList and NameValuePair components, deprecating the old components, and publishing the finished new components.
