### ISSUE TITLE
Anchor - Consider supporting Anchor in our text styles

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3446]
In our [hpe-design-system](https://hpe.slack.com/archives/C04LMJWQT/p1687881321161059) channel, Edgar brought up the point of how we're currently not supporting Anchor styles to match our text-styles.  He brought up a use case where the PageHeader subtext uses text-large but the xlarge size we currently offer in the theme is a different size. In addition, we're currently not offering text styles large and up in anchor styling. 

Should we consider matching our anchor styles to our default text styles? How often would designers use anything larger than large with our current styles?

Edgar's example:
<img width="525" alt="Screen Shot 2023-06-27 at 2 04 27 PM" src="https://github.com/grommet/hpe-design-system/assets/62117454/13b7492f-23ad-4ad8-9280-33a58dec22d8">

What's in the theme:

![Screen Shot 2023-06-27 at 1 47 08 PM](https://github.com/grommet/hpe-design-system/assets/62117454/4e508a97-332c-41d9-ad20-37108ccbb2b7)

**Comment by vavalos5** [comment]
[Grommet Example Link](https://github.com/grommet/hpe-design-system/issues/3432)

Anchor in the theme:

anchor: {
color: 'text-strong',
textDecoration: 'underline',
fontWeight: 500,
gap: 'xsmall',
hover: {
textDecoration: 'underline',
},
size: {
large: {
color: 'brand',
fontWeight: 700,
textDecoration: 'none',
},
xlarge: {
color: 'brand',
fontWeight: 700,
textDecoration: 'none',
},
xxlarge: {
color: 'brand',
fontWeight: 700,
textDecoration: 'none',
},
'3xl': {
color: 'brand',
fontWeight: 700,
textDecoration: 'none',
},
'4xl': {
color: 'brand',
fontWeight: 700,
textDecoration: 'none',
},
'5xl': {
color: 'brand',
fontWeight: 700,
textDecoration: 'none',
},
'6xl': {
color: 'brand',
fontWeight: 700,
textDecoration: 'none',
},
},

-------------------------------------------------------------------

I've updated the Anchor text styles in Figma in both light and dark mode. @KennyAtHPE @taysea can you take a look please.

I noticed that when we were doing brand refresh, I left a sticky on whether we'd still like to keep the bold styles that we previously had before the new theme enhancements as they're still available for our designers to use. I believe they're available in Grommet too? Would be good to confirm so we know whether to remove them or keep and update them. Thanks!

**Comment by vavalos5** [comment]
Including an example where i've applied the updated anchor into the PageHeader so we can see how it'll look like to meet Edgar's need.

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/df209ff7-4a02-47ad-ac6f-c41fdaafd5a7)

**Comment by vavalos5** [comment]
Chatted with Taylor on the bold anchor text in Figma and whether we want to remove it from Figma. From a dev side, what they're trying to do is not to have custom color or custom weight on the anchors and use the anchor as it comes from the theme without overrides so it's easier for the theme changes to come through easily when changes have been made.

Perhaps we should have a quick convo between @taysea @SOjaHPE @halocline on whether or not we want to remove the bold anchor styles in Figma. We are trying to move away from bold but still wondering what your perspective is.

**Comment by taysea** [comment]
I reviewed the sizes and they are aligned with the theme, thanks!

With regards to removing or keeping bold anchor styles, agree with queuing up a 15min call next week to chat so everyone is on same page on that topic.

**Comment by KennyAtHPE** [comment]
I double-checked and saw that the text/normal and anchor text styles match. Side question, how come we have a 6xl text style if its identical to 5xl?

**Comment by taysea** [comment]
That is for backwards compatibility, but Chris didn't wanted text getting larger than the 5xl so we flatten it above that.

**Comment by vavalos5** [comment]
Published and will be sending a message on DS Channel.
