### ISSUE TITLE
Anchor - Deprecate Figma file

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3447]
It has come to our attention that we have Anchor text styles in the [Typography Figma file](https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?type=design&node-id=0%3A1&mode=design&t=1SdNDoV3LhCWJG5z-1) which is correct and a previous Anchor component which we'll need to deprecate.

<s> In addition, we'll need to update the Anchor text styles in the Typography file.

[Grommet example
](https://storybook.grommet.io/?path=/story/controls-anchor-size--size&globals=theme:hpe)
Anchor in the theme:

anchor: {
    color: 'text-strong',
    textDecoration: 'underline',
    fontWeight: 500,
    gap: 'xsmall',
    hover: {
      textDecoration: 'underline',
    },
    size: {
      large: {
        color: 'brand',
        fontWeight: 700,
        textDecoration: 'none',
      },
      xlarge: {
        color: 'brand',
        fontWeight: 700,
        textDecoration: 'none',
      },
      xxlarge: {
        color: 'brand',
        fontWeight: 700,
        textDecoration: 'none',
      },
      '3xl': {
        color: 'brand',
        fontWeight: 700,
        textDecoration: 'none',
      },
      '4xl': {
        color: 'brand',
        fontWeight: 700,
        textDecoration: 'none',
      },
      '5xl': {
        color: 'brand',
        fontWeight: 700,
        textDecoration: 'none',
      },
      '6xl': {
        color: 'brand',
        fontWeight: 700,
        textDecoration: 'none',
      },
    }, </s>

Text styles have been updated in ticket #3446 but will begin deprecation of the Anchor component in Figma to avoid confusions between component and text style.

**Comment by vavalos5** [comment]
[Figma Link](https://www.figma.com/file/I7PsiUmvr7OEJ6311rBUfg/HPE-Anchor-Component?type=design&node-id=0%3A1&mode=design&t=A4A2M9Lso4PNwwKN-1)

I've deprecated components, moved components to "deprecated components" page and moved file to "working files". I've also updated the thumbnail. Can you review @KennyAtHPE and lmk if you see anything missing. Thanks :)

**Comment by KennyAtHPE** [comment]
Hey @vavalos5 looks like the description within the thumbnail hasn't been updated. Otherwise, everything else looks good. The last step is to publish those changes with an accompanying message/description.

**Comment by vavalos5** [comment]
Thanks for catching that @KennyAtHPE Done :)
