### ISSUE TITLE
DateTime Format - Create guidance

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3450]
Parent [Issue](https://github.com/grommet/hpe-design-system/issues/2463)
Previous [Issue](https://github.com/grommet/hpe-design-system/issues/3388)

-----------------------------------------------------

There is a need across our platform to establish guidelines around the display of time and date stamps.

### To do
Explore and create guidance for:
- [x] Review this [guidance and best practices](https://hpe.sharepoint.com/:o:/r/teams/hpe-design/_layouts/15/Doc.aspx?sourcedoc=%7Ba99eae23-950c-45af-95e8-e31766899ceb%7D&action=edit&wd=target(ST%20-%20GreenLake%20HC.one%7CD6469E82-6DB5-4612-8F8F-0D6267F2F101%2FDate%20and%20Time%7C6468AAEC-8A68-4ACD-B2DB-DADA009F168F%2F)) which Edgar had written up for Eric
- [x] How users should be [abbreviating units of time](https://github.com/orgs/grommet/projects/12/views/1?pane=issue&itemId=30199969)
- [x] Use cases + examples on when/when not to use these abbreviations
            - Use only when UI is cramped. Otherwise, do not use abbreviations (should not be common) 
- [x] Research if we can leverage browser APIs for easier implementation
            - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat
            - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat
            - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
- [x] Zero padding within dates
- [x] Locale-specific formatting
- [x] Send out to team for review
      - Draft of [guidance  ](https://www.figma.com/file/Mf9if6zyGETTWW5b9PsYNQ/HPE-Date-Input-Component?type=design&node-id=2753%3A6717&mode=design&t=ZArIoxZQBO3KY9u5-1)
- [ ] Create follow on ticket to draft a PR

-------------------------------------------------------

Share out with Judy Wu, Bhim, Edgar, Mattu Fu, and Sherry Mead for review

**Comment by KennyAtHPE** [comment]
Related question that came up from Bhim in office hours. "My query related to Data tables alignment for DateTime formatting was to understand whether to align the cell contents right or left in case we are using a mixed of seconds, minutes and hours.
We feel it should be based on cell content similar to how we have done it in the below shared examples which make use of both left and right alignment"



![Image](https://github.com/grommet/hpe-design-system/assets/86075038/a589c38a-45f8-435b-961d-99b55541b4f3)


![Image](https://github.com/grommet/hpe-design-system/assets/86075038/ee2d0101-2860-4314-8fda-5fdb280ce5dd)

**Comment by KennyAtHPE** [comment]
7/24 update:
Sent out the [initial draft](https://www.figma.com/file/Mf9if6zyGETTWW5b9PsYNQ/HPE-Date-Input-Component?type=design&node-id=2753%3A6717&mode=design&t=xp93UY27R6jJFHqv-1) to the team for review. Will be making edits based on feedback and will be sharing out in Show n Tell.

**Comment by KennyAtHPE** [comment]
Having a bit of a hard time with writing guidance for when to display UTC time. To my understanding, UTC:
- Should always be used to store timestamps
- Should be displayed for historical events such as log files and other use cases where absolute time (use ISO 8601 formatting) is required

My main questions are:
- Should UTC ever be displayed over local time for current or future events?
- Should local time ever be displayed over UTC for historical events that require absolute time to be shown?

Any thoughts @halocline @taysea @SOjaHPE?

**Comment by taysea** [comment]
Closing this ticket, any content adjustments/additions will be handled in the PR itself: https://github.com/grommet/hpe-design-system/issues/3494
