### ISSUE TITLE
Design - Create an "infrastructure" issue

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3458]
An infrastructure issue which will make your team more efficient, more pain-free, etc. This issue will automatically make it into the next sprint.

Issues should be written and submitted to me on the Friday preceding end of sprint.

**Comment by vavalos5** [comment]
Nice work Seamus! I've added comments to your word document! 😄

**Comment by SeamusLeonardHPE** [comment]
Should have linked this word doc in here previously. Thanks for all the thoughtful feedback and I will expand on this as soon as we choose which item to pursue for the next sprint. 

https://hpe-my.sharepoint.com/:w:/p/seamus_leonard/EV8sHnE6Uh9Ku0CHkO4OzIQBvTGDl_N4mJFVc7hmIsk6PQ

**Comment by SeamusLeonardHPE** [comment]
Ticket created [#3481](https://github.com/grommet/hpe-design-system/issues/3481)

**Comment by taysea** [comment]
Closing because infrastructure issue is in progress.
