### ISSUE TITLE
Dev - Create an "infrastructure" issue

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3459]
An infrastructure issue which will make your team more efficient, more pain-free, etc. This issue will automatically make it into the next sprint.

Issues should be written and submitted to me on the Friday preceding end of sprint.

**Comment by taysea** [comment]
Proposing this ticket: https://github.com/grommet/hpe-design-system/issues/3444

**Comment by taysea** [comment]
Proposing this ticket now: https://github.com/grommet/hpe-design-system/issues/3471
