### ISSUE TITLE
Design - Create an "education" issue

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3460]
An educational proposal. This needs more definition, but the seed of the idea is to present a noteworthy learning opportunity to our stakeholders. For example, GLCP has recently reinstituted a bi-weekly UI meeting. We should have a best practice share-out prepared for each of these. I would like a similar forum identified on the design side. --- This issue will be conditional based on our commitments, but the proposal is requested.

Issues should be written and submitted to me on the Friday preceding end of sprint.

**Comment by SeamusLeonardHPE** [comment]
Suggestions for education issues, I will adapt this document based on feedback and go further in-depth when we select the best item to tackle for the first sprint.

https://hpe-my.sharepoint.com/:w:/p/seamus_leonard/EV8sHnE6Uh9Ku0CHkO4OzIQBvTGDl_N4mJFVc7hmIsk6PQ

**Comment by SeamusLeonardHPE** [comment]
Created ticket [#3479](https://github.com/grommet/hpe-design-system/issues/3479)

**Comment by taysea** [comment]
Closing because education issue is in progress.
