### ISSUE TITLE
Dev - Create an "education" issue

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3461]
An educational proposal. This needs more definition, but the seed of the idea is to present a noteworthy learning opportunity to our stakeholders. For example, GLCP has recently reinstituted a bi-weekly UI meeting. We should have a best practice share-out prepared for each of these. I would like a similar forum identified on the design side. --- This issue will be conditional based on our commitments, but the proposal is requested.

Issues should be written and submitted to me on the Friday preceding end of sprint.

**Comment by taysea** [comment]
After discussion with the dev team, this ticket has been created: https://github.com/grommet/hpe-design-system/issues/3472
