### ISSUE TITLE
Tag - Update Figma component to use "Close" icon.

### ISSUE THREAD

**Issue by ashifalinadaf** [grommet/hpe-design-system#3467]
Replacing the close icon for the Tag from 'form icon' to 'core icon'
Related ticket - https://github.com/grommet/hpe-design-system/issues/3256

Deliverables:

- [x] Create a branch and replace the close icon with 'core icon'.
- [x] Check with other designers and developers.
- [x] Merge with the main branch.
- [x] Create issue for `grommet-theme-hpe` to implement the `Close` icon:
   - https://github.com/grommet/grommet/issues/6870
   - https://github.com/grommet/grommet-theme-hpe/issues/363

**Comment by ashifalinadaf** [comment]
Created a **[branch]**(https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/yKAVgSjg0aGo9CnJ8FoqAw/HPE-Design-System-Components?type=design&mode=design&t=EUFlrP4hG4SZcY0K-1) and updated all the 'Close Icons' from 'form close icon' to 'core close icon'.

@kenny If you can a final look and let me know if there are any issues.

**Comment by vavalos5** [comment]
@KennyAtHPE @taysea Can both of you take a look at the branch and tell me if you notice any of the tags using the incorrect "close icon" please. Thanks!

**Comment by taysea** [comment]
It looks like the correct icon is being used. Also, if it's a quick fix (<5min) can the page be named "Tag" instead of "Tags"? If not a quick fix, can a ticket be filed to align with the Grommet component name?

**Comment by vavalos5** [comment]
@taysea Yea, good call out. I'll make those changes today.

**Comment by KennyAtHPE** [comment]
@vavalos5 can confirm that all the variants are using the correct 'core / close' icon.

**Comment by vavalos5** [comment]
Icons have been merged to [main DS file](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=9685%3A105805&mode=design&t=eKnFN4g6lCVZz0nS-1) and published.
