### ISSUE TITLE
Cell & Header component- Adding all variants into one single component.

### ISSUE THREAD

**Issue by ashifalinadaf** [grommet/hpe-design-system#3468]
It has come our notice that due to a lot of separated components in Cell component it was confusing for the designers to choose the correct ones.
Chandan (From GLCS) has come up with a solution for adding all the variants into one single component for easy toggle between the variants for **'Header Cells and Cells'**.
[Figma](https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/branch/cftUhW9CCbWZOz9veBqrWf/HPE-DataTable?type=design&node-id=11241-155828&mode=design&t=E05mXYuDnNkS0Jd0-11)

Deliverables:

Review the design variant submitted.
Create a branch and add all the variants into one component with toggles.
Check with other designers and developers.
Merge with the main branch.

**Comment by SOjaHPE** [comment]
@ashifalinadaf  the work that Chandan put into the location components to support all the different variants combinations in those two table elements: 'table row header' and the 'table body cells' into two are very thorough. I'm concerned that it might be a bit too much to combine those into a **_single table component_**. The table column header is distinct enough that I see advantages to still allowing the figma consumer of these table components to insert assets that are closer to their specific use. The table cell component is where I see this growing and getting out of hand as more and more unique use cases and layouts need to be supported.

Q. What would the name of the new component be? How would it show up in the assets panel. What strings/meta data would we expose to ensure the component our customers are looking for is returned in the query.

I could be wrong but it might we worth gathering feedback from designers to defend or push back on my statement above. Whether 

If there was a combined local component that showed the header and cell functionality and props in a toggle-able component. I wasn't able to locate it for assessment. Left a comment in the figma file.

**Comment by ashifalinadaf** [comment]
It might be a bit too much to combine those into a single table component. - **for easier, time saving acts.**
Pros- Easy to toggle, save time, easy reflect on the nested components, besides these are the existing variants.
Cons- difficulty in edit/add the new component variants, deprecate?, less flexibility. 

The table column header is distinct enough that I see advantages to still allowing the figma consumer of these table components to insert assets that are closer to their specific use. - **it is confusing for the designers while selecting the specific component needed - multiple component show up on assets, there is no hover option also to see what the component it is.**

Designers have to go through the component main file/DS site to understand the types of component and usage - if we provide the single component - designer can choose from the pre-defined variants. This will also include restricting some of the rules according to the DS guidance. 

The table cell component is where I see this growing and getting out of hand as more and more unique use cases and layouts need to be supported. - **we need a separate ticket to collect use cases and modify and include all the major use cases.**
What would the name of the new component be? - **Data table components as 'Header cell component' & 'Cell component'. we can include the prefix Data table too**
How would it show up in the assets panel. - **Data table components as 'Header cell component' & 'Cell component'.**
What strings/meta data would we expose to ensure the component our customers are looking for is returned in the query. - **Need to ask the developers on this.**
Gathering feedback from designers to defend or push back on my statement above. - **Vicky did suggest me to have a component with variants for easy work for the designers and also GLCS team asking for such component.**

**Comment by SeamusLeonardHPE** [comment]
Resurfaced do to our branch cleaning projects.
https://hpe-my.sharepoint.com/:x:/p/kenny_tran/EagZuftPiF9Hj2m-hR6hiMMBx1_aL8mrD9ZscMFTtQhAVQ?e=ghXMmX

Figma branch linked:

Archived branch to facilitate tidy up.
File can still be retrieved via link in excel sheet
