### ISSUE TITLE
StyledComponents - RESEARCH SPIKE - Create styled components plan of attack

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3476]
As we've begun migration to styled-components v6, there are more considerations to take into account than initially expected.

Current progress/notes captured here: https://docs.google.com/document/d/1SLnJLBdVdpBByUTPaCzlwKksViRl9Q_cZ1yagnU7C7o/edit?usp=sharing

**Deliverables:**
- [ ] Clarity on approach for adopting v6, order of components/number of components per sprint/plan for pre-release/communications/etc.
- [ ] Any follow-on tickets filed

**Questions:**
- [ ] Can we make the props that should be transient behavior more like private variables?
- [ ] Should we continue moving forward with styled components?
- [ ] Should we evaluate other CSS solutions?

**Comment by jcfilben** [comment]
Closing, we ave an agreed upon direction for styled components here https://github.com/grommet/grommet/pull/7165
