### ISSUE TITLE
Order button placement - Finalize design direction with design rationale

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3478]
Use the "design rationale" proposed framework and apply it to the button placement work and recommendations.

- This will be a collaboration effort with @halocline and whomever would like to contribute.
- [ ] Use @gregfuruiye as a sounding board / reviewer / critique. He is has related work (Global Header) which is this is related to and to which he will be testing the "design rationale" framework.
- [ ] Schedule dedicated share out with team
- [ ] Follow up with Bhim as well

**Comment by SeamusLeonardHPE** [comment]
Added in a very high level wireframe of the component similar to the data  collection toolbar ticket as a starting point for discussion & rules.

https://www.figma.com/file/NxYDaNotc7soxZhXJ7lhcQ/Order-of-button-placement---%233387?type=design&node-id=573-5582&mode=design&t=bsfjzezDgVbJyD5e-4

@SOjaHPE

**Comment by SeamusLeonardHPE** [comment]
@halocline I have updated the wireframe and made a first draft of design rational in a similar format to Vicky's work on the collection toolbar.
Please comment on the file or we can arrange a call to collaborate when you have time.

https://www.figma.com/file/gA2H7eqJWHMmTjhwRDTXlP/Order-button-placement-%233478?type=design&node-id=16-14328&mode=design&t=7Fj7ewrsXroNcKUc-4

**Comment by SeamusLeonardHPE** [comment]
Updated guidance based on feedback from figjam async review and Matts input.

https://www.figma.com/file/gA2H7eqJWHMmTjhwRDTXlP/Order-button-placement-%233478?type=design&node-id=16-14560&mode=design&t=62m74tTzM5TIwQQd-4


Visual examples of guidance in practice

https://www.figma.com/file/gA2H7eqJWHMmTjhwRDTXlP/Order-button-placement-%233478?type=design&node-id=63-2992&mode=design&t=62m74tTzM5TIwQQd-4

**Comment by KennyAtHPE** [comment]
Left some minor comments.

**Comment by SeamusLeonardHPE** [comment]
Reached out to @gregfuruiye and Bhim on figma comment to review updated recommendations and examples:
https://www.figma.com/file/gA2H7eqJWHMmTjhwRDTXlP/Order-button-placement-%233478?type=design&node-id=16-14560&mode=design&t=Z3pJoT4G4Zu0asxP-4

Related discussion on slack design channel brought up question about the need to re-order when left aligned:
https://hpe.slack.com/archives/C04LMJWQT/p1693320788517519

Impact of updating alignment rules examined here:
https://www.figma.com/file/gA2H7eqJWHMmTjhwRDTXlP/Order-button-placement-%233478?type=design&node-id=95-826&mode=design&t=Z3pJoT4G4Zu0asxP-4

@halocline

**Comment by halocline** [comment]
@SeamusLeonardHPE I think this is where we need to be for the deliverables on this issue. 

Remaining items:
- Give a little time for external stakeholders and DS team members to review and provide any final feedback.
- Ensure the owner of https://github.com/grommet/hpe-design-system/issues/3290 knows the direction, so that the updates to the PageHeader component may be finished.
- Ensure there is an issue for updating the button order guidance on the DS site.

**Comment by SeamusLeonardHPE** [comment]
- Tagged stakeholders in figma file to solicit feedback.
- Spoke with @ashifalinadaf so we can collaborate on finishing out [#3290](https://github.com/grommet/hpe-design-system/issues/3290) and associate guidance.
- Created follow up ticket re-guidance [#3530](https://github.com/grommet/hpe-design-system/issues/3530)
