### ISSUE TITLE
NameValueList - Publish Figma components

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3504]
[Working file](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/branch/liKNgKYkAeGdCElbGitZVc/HPE-Name-Value-List?type=design&node-id=3745%3A43526&mode=design&t=S5YG0nVbqElkkL2M-1)
Previous Ticket #3484 

----------------------------------------

#### Deliverables
- [x] Send to Chandan for review
- [x] Deprecate old NameValueList and NameValuePair components ([guide](https://www.figma.com/file/grsz2h0yjVw0lGalHIcu2A/Deprecation-Process?type=design&t=aOjQqG70CrqgAQ5H-6))
      - Follow the guide and review with Kenny once on step 5
- [x] Create a new NameValueList page in the main DS components file under "Visualizations"
      - Move the new components here
      - Fill out this [component file template
](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=1461%3A28232&mode=design&t=vsHnmoYVpwgH19MS-1)
- [x] Create a small visual on how to use namevaluelist (include slot component demonstration)
      - Visuals should show users the different width options for both name and value, how to create a grid layout by grouping multiple NameValueList, and how to make their own custom Value using the slot component approach. - [Guidance](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=14891-99209&mode=design&t=NMXseOM8DgRzez2V-11)
- [x] Review with Kenny
- [x] Publish ONLY the NameValueList component
      - To hide a component from the publishing view, include a '.' at the beginning of the name
- [x] Announce in HPE-Design-System channel - [ hpe-design-system ](https://hpe.slack.com/archives/C04LMJWQT/p1693493890770279)
- [x] Create follow on ticket to review and update (figma links) the NameValueList page on the DS site as needed. https://github.com/grommet/hpe-design-system/issues/3527

**Comment by ashifalinadaf** [comment]
Name value list - Discussed with Kenny on the further steps,
[NameValueList page](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=14891%3A86382&mode=design&t=p3gTp8rhDKU0Tqxf-1) created on DS component file, moved new component,
Created [component file](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=14891-99209&mode=design&t=p3gTp8rhDKU0Tqxf-11)
Working on the [visuals](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=14912-100562&mode=design&t=p3gTp8rhDKU0Tqxf-11).

**Comment by KennyAtHPE** [comment]
Left some comments. Noticed that the old NameValueList component file has been unpublished somehow. Will try and republish to push the name update for old NameValueList components.

**Comment by ashifalinadaf** [comment]
Changes have been made to the visuals and cleaned up the file for publishing.

**Comment by ashifalinadaf** [comment]
Connected with Kenny this morning, 
Together deprecated the old component and have published the refactored component.
Announced on the[ hpe-design-system ](https://hpe.slack.com/archives/C04LMJWQT/p1693493890770279) channel on Slack.
