### ISSUE TITLE
Figma - Reevaluate whether components should have prototype interactions built-in

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3509]
[Original slack thread ](https://hpe.slack.com/archives/C04LMJWQT/p1692206885556619)

### Problem

Amanda and other designers have expressed their frustrations with using the built-in prototype interactions that some of our Figma components have. When first refactoring our components, we had a couple of requests to include these within our most used atomic components which were initially received positively. However, based on the strong reactions in Amanda's thread, it sounds like it's throttling people's work flows instead. A summary of issues that were brought up:
- It's annoying to have to detach prototype interactions when it's not needed
- When presenting it can lead to confusion if some components change states when clicked on
- Users aren't aware that this is a feature. If they need prototype interactions then they could always prototype the designs themselves.

#### Deliverables

- [ ] Research whether or not Figma has any built-in features that might solve this issue (can prototype interactions be toggled?)
- [ ] Share out, discuss, and formulate a plan with the team
- [ ] (ACTION PLAN TBD)
- [ ] Communicate with designers before publishing any changes

**Comment by SeamusLeonardHPE** [comment]
To removes all interactions is very simple:

1. Change figma panel to "prototype" view
2. Select main component set
3. Right click
4. select "remove interactions"

<img width="790" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/02d13a85-1c0f-45dc-8406-c44dfc514b88">

**Comment by SeamusLeonardHPE** [comment]
Alternative solution:

All buttons are currently set to prototype mode "on click"
<img width="434" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/ca3c8ff7-6616-46de-b8e1-351e781f079f">

Each click cycles through state (except disabled) and stops on "active" - The prototype has to be reloaded to undo this
enabled -> hover -> focus -> active
<img width="332" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/d871f930-1cea-48ff-88e1-5ad40d6db9a5">

Changing the initial "default" button interaction to "while hovering" means that the in prototype mode, you will gget a hover effect, but not the "flashing" of multiple click targets

<img width="384" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/8f347d2e-5ed8-4192-983e-842a921b8873">

Gif to demo

![button states](https://github.com/grommet/hpe-design-system/assets/135040188/e9ecaa76-5e83-42f8-8f9e-7defe47f913a)


- A hover state should not be triggered by click in a prototype anyway
- is it worth having the other "click" events, unless to switch between "hover" and "active" 
- Are we trying to showcase all out states, or reflect browser behaviour?
- Product teams have voted to remove this feature, but if it was applied correctly would it be acceptable?

**Comment by SeamusLeonardHPE** [comment]
@KennyAtHPE @taysea @halocline @oliverHPE 

Quick fix is to remove (could be done on Olivers tidy branch to avoid conflict).

Alternatively could create some demo files updating the default button interaction to  "while hovering" and share with Greg, Sylvia & Tales for feedback. 

Would like to get this one out the door before next week Office hours.

**Comment by taysea** [comment]
I'd vote for the quick win of turning them off and leave the "while hovering" feedback as a future exploration unless there is a clear better solution than turning them off.

**Comment by KennyAtHPE** [comment]
I vote to turn these off as well. Have heard several folks ask for interactions throughout the years but the feedback from users after actually using them has been overwhelmingly negative.

**Comment by SeamusLeonardHPE** [comment]
Closed with followup task https://github.com/grommet/hpe-design-system/issues/3701
