### ISSUE TITLE
Create the new SelectMultiple figma component

### ISSUE THREAD

**Issue by ashifalinadaf** [grommet/hpe-design-system#3526]
Working file - Figma
Main ticket - #2887
Previous tickets- #3477, https://github.com/grommet/hpe-design-system/issues/3507

-----------

Deliverables: 
- [ ] Create the new SelectMultiple Figma component version supporting the new functionality. 
- Create a branch.
- Make changes to the component 
- Check with designers/developers 
- [ ] Create follow on issue for Grommet to extend the SelectMultiple component to allow for a custom action button to be appended to the select's drop

**Comment by SeamusLeonardHPE** [comment]
Closed as work will be part of #3685
