### ISSUE TITLE
Figma bug: CheckBoxGroup not using CheckBox asset

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#3548]
### Link to bug

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=5732%3A80299&mode=design&t=lUUGz8fbopUteANN-1

### Current Behavior

- The checkboxgroup figma asset is not using the checkbox figma asset.
- While the text in checkbox and checkbox group are showing the same "placeholder" style, the styles being exposed in the figma assets are different. Wierd?
- What is the text style for checkbox?

### Expected Behavior

CheckboxGroup is using the checkbox asset and the assets are using the same text styles. Also expect the text style for checkbox is not 'placeholder' but either "value" or default "text"

### Screenshot or recording of bug

![checkbox](https://github.com/grommet/hpe-design-system/assets/17889451/984f2938-3ab2-4959-87f8-2f9fd7b93b02)

### Steps To Reproduce

1. In figma, select the checkbox asset
2. In figma, select the checkboxgroup asset
3. For fun, detach the checkboxgroup asset and drop in the checkbox asset, the format of the checkbox gets whacky 😀

**Comment by halocline** [comment]
@SeamusLeonardHPE @CillianHPE is this still an issue?

**Comment by SeamusLeonardHPE** [comment]
The styling issues for this was resolved for the text styles for checkbox/checkboxgroup label.
"Form Value" text style  is used in both components for the checkbox label.

The 'atomic build' using the same checkbox sub component will be addressed in the inputs refactor 
https://github.com/grommet/hpe-design-system/issues/3685

Closed and linked in other issue.
