### ISSUE TITLE
Metadata & Description in figma

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3561]
**Goal:** Aid discoverability of existing components, and design patterns in the guidance site.

**Approach:** Add metadata that includes alternative names & usage descriptions to both figma components (and variants) as well as adding searchable metadata to DS site pages.

Suggested keyword data has been added to linked excel sheet:
[Link to audit research](https://hpe-my.sharepoint.com/:x:/r/personal/ashifali_nadaf_hpe_com/Documents/Design%20System%20-%20Master%20sheet%20.xlsx?d=w7cced741a7514bb5bf581ea8be865fe4&csf=1&web=1&e=HHnAen)

**Deliverable 1:** Guidance & Metadata template 

- [ ] Create guidance for adding/updating metadata (what should be included, what format how to publish)
[draft guidance/discovery ](https://hpe-my.sharepoint.com/:w:/p/seamus_leonard/ESjA0dLSdDxMiH-nhnqs96UBq1ixCYSnfSgXXy-S8CjmXA?e=9YXea1)
- [ ] Create and document process and reviewing metadata amongst team before adding to figma. 
- [ ] Define what is included and what order to display in figma (Keyword, Description, Usage?) 
- [ ] Create template for the “description” inside figma to existing components (use layer/modal component for first example) & get approval from team 
- [ ] Share with devs to discuss how to add values in DS site (meta name="description" meta name="keywords" ?), document approach and add to guidance
- [ ] Document if there is a need to add specific meta data for component variants (e.g. ‘toggle’ variant within checkbox component) 

**Deliverable 2:**  Individual components & pages to update.

- [ ] Box
- [x] Card
- [x] Footer
- [ ] Grid
- [ ] Header
- [x] Header
- [x] Layer
- [ ] Main
- [ ] Page
- [ ] Stack
- [x] Accordion
- [ ] Anchor
- [x] Button
- [ ] Menu
- [x] Pagination
- [x] Search
- [x] Tabs
- [x] Tip
- [x] Checkbox
- [ ] Button Groups / Toggle
- [x] Checkbox Group
- [x] DateInput
- [x] FileInput
- [x] MaskedInput
- [x] RadioButton Group
- [x] RangeInput
- [x] Select
- [x] SelectMultiple
- [x] TextArea
- [x] TextInput
- [x] Avatar
- [x] DataTable
- [x] NameValueList
- [x] Notification
- [ ] Skeleton
- [x] Spinner
- [x] Tag
- [x] DataTable Customization
- [x] Feedback
- [x] Lists
- [x] Global Header
- [ ] Forms
- [ ] Page Layouts
- [ ] Content Layouts
- [ ] Filtering
- [x] Navigation
- [x] Wizard
- [x] Global Header

**Questions about figma "description" and link fields**

- Should we include links in the description of just the link field?
- What link/links should be included, Design system, Grommet or Storybook
- What order priority for adding metas data existing components. 
- Other unpublished changes need to be catalogued and published prior to theme update launch. 
- Clean out any old component meta data that doesn't align with new process. 
- Document any issues with components noted as we work on this (toggle switch inside checkbox, anything that is out of date, deprecated nested components etc)

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf is proceeding with just adding Keywords & links to the Ds site to top level components (not variants). 
We will revisit to add descriptions as soon as theses changes have been socialised and feedback has been gathered.

We will avoid editing & publishing metadata on the following components until we consult @KennyAtHPE to uncover if there have been visual changes that need reviewed: (As these components currently show up in figma as having unpublished changes.)

- Global Header
- List
- Menu
- PageHeader
- SelectMultiple
- Responsive Tabs

**Comment by SeamusLeonardHPE** [comment]
Hey @KennyAtHPE can we schedule a call on Monday to review the components in the previous comment & see if visual changes have been made before we add and publish the metadata.

@taysea @jcfilben, we have added keywords to our figma components, and would like to add the same terms as searchable metadata on the DS site. We need a bit of guidance on how best to approach this, we can use one component as a test case and then see if the work can be carried out by a designer & reviewed via pull request.

**Comment by jcfilben** [comment]
Hey @SeamusLeonardHPE the terms can be added to this file: 
https://github.com/grommet/hpe-design-system/blob/master/aries-site/src/data/structures/components.js
Each component has a `tags` section. Terms can be added to `tags` for each component and then when these terms are used in search the associated component will show in the search results.

Agree on starting with just one component, opening a pull request and ensuring it is working correctly, then we can move forward from there.

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE apologies, I will take a look today and review the unpublished changes to those components you mentioned previously.

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE reviewed the components. Feel free to publish, I do not see any visual changes—a reminder to include a message explaining the change and who to contact if there are any issues.

Side note, we may have to change to using the branching feature to avoid similar issues in the future. The branching feature provides a side-to-side comparison of the old and new versions of components. It's tough to see how a component has changed otherwise.

**Comment by ashifalinadaf** [comment]
@KennyAtHPE thanks for the clarification, I will publish the remaining component with metadata.

**Comment by ashifalinadaf** [comment]
Added meta data to all the component in Figma file, except 'data table component' (as there are many smaller components). 
Meta data was not applicable for guidance related components coloured beige on [Master sheet ](https://hpe-my.sharepoint.com/:x:/r/personal/ashifali_nadaf_hpe_com/Documents/Design%20System%20-%20Master%20sheet%20.xlsx?d=w7cced741a7514bb5bf581ea8be865fe4&csf=1&web=1&e=aOytdx) @SeamusLeonardHPE @KennyAtHPE 

Created a PR to test the discoverability on DS site for 'selectmultiple' component https://github.com/grommet/hpe-design-system/pull/3566  @jcfilben @taysea if you have a look and merge it.

**Comment by KennyAtHPE** [comment]
@ashifalinadaf thank you for adding the metadata for those components, did you already go ahead and publish those changes? If not, feel free to publish since this should not be breaking any existing instances.

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf 

- [ ] 1. List all DS figma components that have not been updated with keywords from master file (is it only figma components that have not been refactored? )
- [ ] 2. Add comma separated keywords to the DS site via link below (Make sure we are ADDING to keywords, and not removing any existing ones.  Taylor has confirmed we can do this all in one pull request) [link](https://github.com/grommet/hpe-design-system/blob/master/aries-site/src/data/structures/components.js. 
- [ ] 3. Confirm addition of metadata in the excel master sheet for visibilty


Subsequent task, 

- [ ] aggregate dev links in an excel doc (DS site, Grommet, storybook, git repo) for each component - (May require dev assistance to we can collaborate on this)
- [ ] When completed we can add those via the dev mode on figma - Experiment was done on the ‘selectMultiple’



![Image](https://github.com/grommet/hpe-design-system/assets/135040188/cbdadf19-9073-4711-b2ca-c5d7e805821a)

**Comment by ashifalinadaf** [comment]
Completed adding metadata to the components PR https://github.com/grommet/hpe-design-system/pull/3569, @taysea please have a look and merge if all goes well.  

Currently working on adding metadata to the templates.

**Comment by ashifalinadaf** [comment]
PR for adding keywords to the Templates - https://github.com/grommet/hpe-design-system/pull/3571
