### ISSUE TITLE
Review & publish bug fix branch

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3602]
Review bug fixes branch:

- [x] Compare and record fixes in figma link against initial notes in sharepoint excel
- [x] Update branch to take in changes from 5.1 update
- [x] Merge branch into master
- [x] Publish changes to components with acceptable messaging

**Figma branch**
https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/j8TQq7BB7okLAstfvtUDTp/HPE-Design-System-Components?type=design&node-id=0%3A1&mode=design&t=CEAQ6SGoAnhtOcXZ-1

**Bug tracking document**
https://hpe-my.sharepoint.com/:x:/r/personal/seamus_leonard_hpe_com/Documents/Design%20System%20-%20Fixes.xlsx?d=w621ab821dc184a2fab29866f96fec473&csf=1&web=1&e=B3L80k

**Comment by KennyAtHPE** [comment]
Consideration for the future, we should not be pulling in so many updates from the main file into the branch file. After trying to pull in updates from the main branch (5.1 updates + lots of other past updates), the branch file completely crashed on me. Had to completely delete it altogether.

**Comment by KennyAtHPE** [comment]
Requesting reviews @SeamusLeonardHPE

A log of everything that's been changed within this [branch](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/j8TQq7BB7okLAstfvtUDTp/HPE-Design-System-Components?type=design&node-id=0%3A1&mode=design&t=c680MeTLz9lXP6VS-1) so far including what has been mentioned above:

#### Inputs (Checkbox, CheckBoxGroup, DateInput, File Input, RadioButtonGroup, TextInput, Search, RadioButton, Select, SelectMultiple:

Bug Fixes:
- Input field border has been changed to 'inside.' Clipping inside groups no longer occurs.
       - [Checkbox, CheckBoxGroup, RadioButton, RadioButtonGroup] checkbox borders have been changed to 'inside'
- Icon within the info message is now centered on text line height
- [DateInput] Calendar icon color for dark variants has been updated to dark mode
- [File Input, Search, Select] Grids have been turned off for list items, previously showed a red line that confused users
- [Search] No longer using deprecated components

Aligning w/ Grommet:
- Label changed to Text/Medium/xsmall
- Info message icon changed to 16x16

#### Misc. updates
- Center Layer
     - No longer using deprecated components
- Tip
     - Removed title variant
- DataTable Customization
     - Order tab is now selecting when in Order variant


#### Blocker
Currently waiting for #3604 to be reviewed and approved before I update the page layout file with the new global header components.

**Comment by KennyAtHPE** [comment]
Branches merged and updates have been published with update notes for each individual component. Closing out ticket.
