### ISSUE TITLE
Figma feature: Update Global Header with new header logo, add breakpoint sizes, etc.

### ISSUE THREAD

**Issue by L0ZZI** [grommet/hpe-design-system#3604]
### What component does this request relate to?

Global Header

### Describe the feature you'd like to request.

Update global header logo to use latest guidance brand guidance by removing the [Special Use](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=3028-58403&mode=design&t=Beis2ino4tQmUvCq-11) logo treatment.

**Comment by KennyAtHPE** [comment]
Adding on additional changes made to the global header component as part of this update:
- Removed special use logo, replaced w/ HPE Product logo

![Image](https://github.com/grommet/hpe-design-system/assets/86075038/efd34245-8f66-4f1c-b751-6373f99c5d44)

**Comment by KennyAtHPE** [comment]
Requesting review @SeamusLeonardHPE on the [Global Header changes](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/0GTx9N19QpdMwJQdgS8wXY/HPE-Design-System-Components?type=design&node-id=3028%3A58745&mode=design&t=bEZ7HIDsRJIDi9yx-1).

Once this change has been pushed and merged, I can update the global header components on the page layouts file as mentioned in #3602

**Comment by KennyAtHPE** [comment]
Branches merged and updates have been published with update notes. Closing out ticket.
