### ISSUE TITLE
Figma - Lucas's exploration

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3614]

**Comment by luketa8** [comment]
Mockup Exploration File:

https://www.figma.com/file/1MtqBzaj2zbJuo0Qk3wO0j/Mockup-Exploration?type=design&node-id=9-422&mode=design&t=P5lIgQs8rRPjYRHO-0

**Comment by luketa8** [comment]
**Naming**

- Removing `HPE` and `Component` from the naming convention
- Rename Side Drawer following this logic:
Layer/Side
Layer/Center
Layer/Fullscreen

**Comment by luketa8** [comment]
![Screenshot 2023-12-13 at 17 21 49](https://github.com/grommet/hpe-design-system/assets/5853565/d3a7e456-f6a0-4dd9-a0a5-c7f7874833e9)

`HPE Select Component` to be unpublished

**Comment by luketa8** [comment]
## First steps for using the new variables features in Figma

Variables are reusable definitions, like styles, that can be assigned to various design attributes like color, numbers, and strings. Unlike styles, variables can switch between definitions depending on the theme that is applied, unlocking design theming and tokens

- Scheme a plan for using the new variables features into HPE's Design System: exploration, definition, implementation.
- Create collections of variables laying out the scope of each collection
- Create modes inside of each collection
- Define the best usage of primitives and semantic tokens

**Comment by halocline** [comment]
There are good recommendations in here. Can we please separate these into separate issues and link from this issue to each? This will break up this work into smaller achievable tasks. Once that is done this can be closed.

cc: @SeamusLeonardHPE
