### ISSUE TITLE
Fix page layouts template page

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3624]
The existing[ page layouts figma templates file](https://www.figma.com/file/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?type=design&node-id=190%3A3718&mode=design&t=Efw10JnPdGFPXs2I-1) has a number of issues that make it less than ideal for a product to designer to copy & paste as a starting point.

- The page templates use a mix of frames, groups and shapes that are hard to interact with and add content to.
- The our figma grid styles do not comply to the recommended margins in the page guidance.
- There are on page guidance layers that re not locked.
- Page widths seem 

These page templates should be modified to make them easier to comprehend & copy/paste & populate with content.

- [x] Fix and standardise page layout (frames, alignment, global header, auto-layout?)
- [x] Decide if needed guidance overlay is needed per page, if so how to lock it.
- [x] Investigate, and recommend a better way to incorporate/enforce guidance with figma layout grids.
- [x] Decide if these modified templates should be moved into the template library
- [x] If existing page template file is to be left in place, all WIP & exploration pages should be archived elsewhere.
- [x] If guidance is to remain on page, update, reformat & tidy to new specs
- [ ] Check guidance site for links & copy that may need updated.

**Comment by julauxen** [comment]
The details on this issue will be considered under #3797
