### ISSUE TITLE
Figma feature: Updates to Global Header Component

### ISSUE THREAD

**Issue by GinaTaylor** [grommet/hpe-design-system#3625]
### What component does this request relate to?

Header

### Describe the feature you'd like to request.

The Figma component for the GLP Header in the Design System needs to be updated to align with the latest version for Istanbul and Jhansi. (including updated responsive patterns)

Variations: GLP/Console, MSP, MSP-Tenant, CoP, GLoP

### Links to Figma files with use cases or ideations from you.

[Istanbul/Jhansi Header for GLP](https://www.figma.com/file/AbxAC3KU59pPyHG5mnnh7R/GLP-Header-2023-2024?type=design&node-id=9728%3A118059&mode=design&t=50FhKrLk3nLwl75S-1)

**Comment by GinaTaylor** [comment]
Linked issue (DS Site Documentation work/ @halocline): https://github.com/grommet/hpe-design-system/issues/3628

**Comment by KennyAtHPE** [comment]
3/11 update: Connected w/ Jeff S. and Gina. The global header changes have been made and are currently being reviewed by them. 

@SeamusLeonardHPE would you mind testing the component as well to see if anything is broken? The variants, spacing, and naming will be reviewed by Jeff S. and Gina so I wouldn't worry about that.

[Update branch](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/zwghgCEe3i7SfBthlwyMim/HPE-Design-System-Components?type=design&node-id=3028%3A58403&mode=design&t=ebf0iGDONhYFZVRG-1)

**Comment by KennyAtHPE** [comment]
The component has been reviewed and merged. Will push out early tomorrow morning. Notes for follow on ticket:
- Create ticket for issues with Stack on icon-only buttons (ex. notification w/ badging)
- Connect w/ Chris on the HPE Product and Special Logo use cases

**Comment by KennyAtHPE** [comment]
Component has been pushed and announce, next steps documented in #3767. Closing ticket
