### ISSUE TITLE
Pagination - Create interactive prototype for PaginationControls

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3626]
Following requests from product teams to expand on the existing grommet "pagination" component & add functionality that will improve the usability of data collections.

Request for a prototype to support research & designs linked below: 
https://www.figma.com/file/nxI308Yvt4HKJ1rjgrEXCk/Feature-Request--Pagination-Section?type=design&node-id=7-8027&mode=design&t=QloRwsmqFQfRxUfj-4

Follow on to:
https://github.com/grommet/hpe-design-system/issues/3612
https://github.com/grommet/hpe-design-system/issues/3521

**Comment by MikeKingdom** [comment]
Here's a simple working example of the pagination controls and their responsiveness as stated in the Figma.
There's 2 examples, one that doesn't try to limit the controls to the width of the table and a second that does limit the controls to the width of the table.
The background colors and borders are just to make it easy to tell the sizes of the different pieces

https://codesandbox.io/p/sandbox/pagination-responsive-k58sjn?file=%2Fsrc%2FContents.js%3A39%2C35

**Comment by halocline** [comment]
Prototype has been completed and demoed.

Please do the following to close out this issue:
- [ ] Summarize open questions / feedback notes from the demo.
- [ ] Create an issue(s) for next steps.
