### ISSUE TITLE
Refactor existing "notifications" components  & add to main component file.

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3627]
**Rationale**
- The [ current notifications component ](https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?type=design)in figma exists outside of the main component library file.
- Incorporating component assets into a single file will make branching/tracking/releasing more reliable.
- Older components need to be refactored to upgrade with new figma features.
- Opportunity to bring figma assets inline with grommet component.

**Usage**
Usage[ documented in the design system site](https://design-system.hpe.design/components/notification#variants)

**Variations**
-- Explain the types
[Toast notification](https://design-system.hpe.design/templates/toast-notifications)
[Global Banner](https://design-system.hpe.design/templates/global-banner-notifications)
[Inline notification](https://design-system.hpe.design/templates/inline-notifications)

**Considerations**
- Should components be merged into since component with props to match grommet
- Connect with dev to align naming conventions
- Review existing documentation - can it be improved/clarified
- Rebuild with best practices autoflow/naming/responsive
- Review, document and update if required the related metadata to each variation.

**Deliverables**
- [x] Refactored notification component(s)
       - Create a new branch within the Notifications file
       - Determine whether or not we should be updating existing components or creating new master components. If updating existing components, then be sure to update what currently exists (update light mode for toasts and global notifications)
       - Review w/ Seamus + Kenny and at least 1 dev. Hold off on publishing before reviews are done.
- [x] Prep main library file for component migration
       - Create a branch
       - Create and setup new page for notifications
       - Review w/ Seamus + Kenny
- [x] Once reviews are finalized, publish the component update and then move the component to the new file
       - These should all be done together
       - Include an update message
- [x] Deprecate remaining legacy components ( can deprecation process be improved?)
       - [Deprecation process](https://www.figma.com/file/grsz2h0yjVw0lGalHIcu2A/Deprecation-Process?type=design&node-id=0%3A1&mode=design&t=NXMQ7cMvG7oLqjXn-1)
- [x] Announce update in design system channel & on DS site
- [x] Note down areas where we can improve, fill gaps, create additional guides, etc.

**Comment by KennyAtHPE** [comment]
@luketa8 recommended agenda for sync-up
- Review and close out all comments
- Merge branch within main file
- Deprecate old components and update "finished" page within the Notifications file
- Push deprecated component update w/ update message
- Move Notifications file to the working files 
- Push the Notification components update on the main file w/ update message (might not be needed since they are new instances)
- Announce on Slack

**Comment by luketa8** [comment]
## Changelog

Component level:

- 5 components were replaced by 3, integrating `light`and `dark` themes as variants.
- `close`, `title` are now booleans instead of variants, simplifying the component
