### ISSUE TITLE
Ship updated grommet-theme-hpe

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3630]
Changes on master include `data.button.kind` which is needed for Data + friends styling.

Notes: 
- We should likely release this after we have moved the Data + friends components out of beta in grommet, so we can set the peerDependency of the theme to that latest version of grommet.
- Once we release grommet-theme-hpe, we should update grommet package.json of grommet-theme-hpe so the Storybook examples will reflect the latest theme styles.

Steps:
- [x] Once grommet is released, updated the `peerDependency` on grommet-theme-hpe
- [x] Release theme

**Comment by taysea** [comment]
v5.2.0 is released! https://github.com/grommet/grommet-theme-hpe/releases/tag/v5.2.0
