### ISSUE TITLE
Create realistic dataset + environment to test DataTable "Select All" (#6946)

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3631]
Rephrasing as of 1/4: Before moving Data + friends out of beta, let's use SpaceX / Star Wars datasets to test "Select all" functionality.

See comment: https://github.com/grommet/grommet/pull/6973#issuecomment-1781842805

Related issue: #6946

**Comment by halocline** [comment]
@taysea with the "select all" improvements made in April-ish, can this be closed?

**Comment by taysea** [comment]
Yes this can be closed, closing now.
