### ISSUE TITLE
Checkbox - Align input values w/ Grommet

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3644]
[Figma Branch
](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/93HcLdmyUJEclX3I8jYtdq/HPE-Design-System-Components?type=design&mode=design&t=7Bw3d2BryMPfk4hw-1) [Original Slack thread
](https://hpe.slack.com/archives/C04LMJWQT/p1705967035604109)

Currently within Figma, the following changes are required to align with Grommet:
- [CheckBox](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/93HcLdmyUJEclX3I8jYtdq/HPE-Design-System-Components?type=design&node-id=2940%3A62424&mode=design&t=7Bw3d2BryMPfk4hw-1) + [CheckBoxGroup](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/93HcLdmyUJEclX3I8jYtdq/HPE-Design-System-Components?type=design&node-id=5732%3A78041&mode=design&t=7Bw3d2BryMPfk4hw-1) input values need to be changed from 'form/placeholder' to 'form/value'
- [SelectMultiple](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/93HcLdmyUJEclX3I8jYtdq/HPE-Design-System-Components?type=design&node-id=3206%3A58995&mode=design&t=7Bw3d2BryMPfk4hw-1) checkbox input value need to be changed from 'form/placeholder' to 'form/value.' Additionally, the text sizes should be changed to 19px, which will be a manual text style.

**Comment by KennyAtHPE** [comment]
@ashifalinadaf @SeamusLeonardHPE @luketa8 @oliverHPE Could one designer review it before I merge?

**Comment by ashifalinadaf** [comment]
Looks good to me ✅

**Comment by SeamusLeonardHPE** [comment]
@KennyAtHPE reviewed and looks good.
My only comment, is we are using the 19px font -  24px line height in more than one place (medium button) should we create a cusomt style name that signifies that it's an accessibility fix? For some designers comining into a file and finding not styled text seems like its erroneous, and that comment has came up before. (maybe a comment in the metadata is an alternative signal) 

@halocline @taysea

**Comment by KennyAtHPE** [comment]
The branch has been merged and the update has been pushed. Follow on ticket #3649.

Closing out this ticket.
