### ISSUE TITLE
Finalise “pagination footer” component

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3651]
Follow on to 
https://github.com/grommet/hpe-design-system/issues/3621
https://github.com/grommet/hpe-design-system/issues/3612
https://github.com/grommet/hpe-design-system/issues/3521

[Figma recent working file](https://www.figma.com/file/nxI308Yvt4HKJ1rjgrEXCk/Feature-Request--Pagination-Section?type=design&node-id=7-8027&mode=design&t=QloRwsmqFQfRxUfj-4
)

Mikes demo requested & delivered: https://github.com/grommet/hpe-design-system/issues/3626
https://codesandbox.io/p/sandbox/pagination-responsive-k58sjn?file=%2Fsrc%2FContents.js

- [x] General - Seek agreement naming conventions for component, parts, states & props.
- [x] Grommet - Incorporate feedback form demo to figma designs & mark for follow up action if required in code.
- [x] Figma - demo versions with varying degrees of customisation amongst product team & make actions from feedback

**Comment by KennyAtHPE** [comment]
Left a couple of comments!

**Comment by SeamusLeonardHPE** [comment]
Created new branch from main library file to house pagination component
https://www.figma.com/file/tlRprPDp1yY1AaSOhoiiSH/%233651---Pagination-component?type=design&node-id=26125-326&mode=design

**Comment by SeamusLeonardHPE** [comment]
Requested figma review for @oliverHPE @KennyAtHPE 

Questions remaining for dev alignment.

- [ ] Default step values are different on grommet than the HPE site
- [ ] Padding for breakpoint sizes
- [ ] Confirm that for medium and up breakpoints - when summary is not displayed pagination controls (step & buttons) remain right aligned. This should also be the case in code.

**Comment by KennyAtHPE** [comment]
Left comments on the Pagination file.

**Comment by SeamusLeonardHPE** [comment]
[New component published ](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=26125-326&mode=design)

Previous component deprecated and moved to archive project folder.

Follow up task to replace all instances in template library
