### ISSUE TITLE
Utility file - create components

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#3657]
Create a utility file with non-coded components to be used by design system maintainers.

Components

- [x] Page header - components
- [x] Page header - component parts
- [x] Page header - documentation
- [x] Component labels
- [x] Tags
- [ ] Cover
- [x] Text blocks

**Comment by KennyAtHPE** [comment]
Should we house them in the main file [here](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=141%3A582&mode=design&t=S8wb3jAiSHer5oBe-1)? We can add the '.' prefix to prevent them from showing up in the publishing modal.

**Comment by oliverHPE** [comment]
Hey Kenny,

**Comment by oliverHPE** [comment]
Hey Kenny,

I've placed them in this [file](https://www.figma.com/file/IFHe056XfdPcXI2IdAxkX9/%E2%9C%8F%EF%B8%8F-Utilities?type=design&node-id=3%3A27&mode=design&t=5xE8c2eTo33cKuAy-1) for now. Was thinking we could have a dedicated utility file to house such components. There are other utility components that won't be used in the component library but used else where.

**Comment by SeamusLeonardHPE** [comment]
@oliverHPE can we clarify if this work is complete or if it will be expanded to create components for consumption for design system team members only?

- If we create a shared library where should it be housed.
- What additional components are required (anatomy table, arrows, annotations ...)
