### ISSUE TITLE
Edit/Update search button guidance

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#3660]
In Office hours some issues regarding the 'Search' component guidance were raised. We'll need to edit update the guidance to attend to these issues.

Issues raised were:

1. The placeholder text recommendations could be improved.
2. The guidance on icon placement could be improved - indicating how strict/flexible the guidance is, and some additional guidance into which placement to use when and where (when to use left or right).
3. Making it known that the clear search 'x' button uses the browsers default, native close icon.
4. Accessibility guidance concerning the button on search. Currently the guidance says:
"Search inputs should be accessible. Ensure users have the ability to return results using their keyboard as well as clicking a button."

Update guidelines accordingly to address the above concerns:

1. **Placeholder text**

- [x] Update guidance (draft)
- [x] Review
- [x] Update on website

2. **Icon placement**

- [x] Update guidance (draft)
- [x] Review
- [x] Update on website

3. **Close button**

- [x] Update guidance (draft)
- [x] Review
- [x] Update on website

**4.  Acessibility.** 
- [x] Update guidance (draft)
- [x] Review
- [x] Update on website

**Comment by SeamusLeonardHPE** [comment]
Adding slack conversation for context

https://hpe.slack.com/archives/GPPLUK6LR/p1706269191516699
