### ISSUE TITLE
Fix issues with deprecated Menu component

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3662]
The previously refactored  menu component is still discoverable via the figma asset panel.

![Image](https://github.com/grommet/hpe-design-system/assets/135040188/5a97ce50-6a58-432b-897f-91f695ebca2e)

- [x] rename any components & variants to remove reference to menu
- [x] publish changes to library file
- [x] test for success via searching in figma asset menu

**Comment by SeamusLeonardHPE** [comment]
Updated library file with 🛑 Deprecated name added to relevant components, and variants renamed to hide.

Note - Menu was originally Deprecated on 01-17-2023 - this file should be eligible to be unpublished form the library now @KennyAtHPE @oliverHPE

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE I definitely think we should unpublish this from our Library. A majority of deprecated components have passed the "grace period," maybe we can go through a similar auditing process as we did for the Figma branches cleanup.

**Comment by SeamusLeonardHPE** [comment]
Closed ticket with follow up task of deprecation & documentation linked below
https://github.com/grommet/hpe-design-system/issues/3700
