### ISSUE TITLE
FileInput - The Figma component implementation is missing info message

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3675]
### Link to problem

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=1340-31908&mode=design&t=S70B04dzcMcuQFhj-0

### Current problem

@GinaTaylor asks "I have a quick question about FileInput. Will FileInput support having an info message below, as seen on other form fields, in the future (or near future)?"

### Expected behavior or solution

All inputs should have label, description, info/error messages, and validation states.

Can we do a quick fix to patch this for @GinaTaylor?

Architecturally, to provide consistency and reduce maintenance, can we build a FormField component which wraps a child input. The FormField provides the label, description, info/error messages, and validation states. Then the various inputs are only worried about the input's internals and doesn't have to worry about it's outside elements. If we don' have an existing issue for this refactoring, please create one.

**Comment by SeamusLeonardHPE** [comment]
Requesting a review on changes made to File input  component in branch  "3675 - FileInput info message"

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/fnoYR4q2BmcXa8bYhBfohY/HPE-Design-System-Components?type=design&node-id=387%3A1967&mode=design&t=HjXLryxVz2FOH7I2-1

@oliverHPE @KennyAtHPE 

Steps taken:

- Copied in "Info message" layer from the text input (dark & light mode)
- Set responsive to "fill" for text block & parent frame
- Created a boolean for visibility named "Info Message" matching naming convention on other inputs
- Switched visibility of "Info Message" to "false" for all variants so it doesn't show by default.

Test requested:
Copy updated component instance to draft file

- Test presence of "Info Message" in each variant (toggle on)
- Update text and switch variants (does override text propagate between variants including dark mode)
- Update text and check responsive behaviour (text should stretch & reflow)
- Darkmode check for text color

**Comment by oliverHPE** [comment]
@SeamusLeonardHPE

**Comment by oliverHPE** [comment]
Have tested the presence of info message and it appears in each variant.

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE had similar discoveries in my review. One other small comment is whether or not we want to change the component name from 'File Input' to 'FileInput' to better align with Grommet. We're currently including spaces within some components or completely omitting them (CheckBoxGroup vs File Input).

**Comment by SeamusLeonardHPE** [comment]
Merged fix after review and published changes to library.
Will update conversation in slack to notify @GinaTaylor
