### ISSUE TITLE
Color Library, tidy & update

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3702]
Tidy the existing [HPE color library file](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?type=design&t=hlYSpZomglxp1Hw0-6) & archive all WIP/exploration.

One completion of that branch & import additional styles that have been created by the brand team.

- [x] Create color backup file in archive.
- [x] Move all pages & content that is not directly displaying the current color styles that a have been created in that file.
- [x] Branch figma color file -  Add new color styles and make additions to example page (linked below)

Review work that [Joelle has researched & proposed](https://www.figma.com/file/QXcCKvgzJpfaOTzu7F7AEn/Data-Visualization?type=design&node-id=930-14274&mode=design&t=iPGp7qbvLza7X5i4-4) and questions that have surfaced in the [design system slack](https://hpe.slack.com/archives/C04LMJWQT/p1706645939536219)

Suggested additions and modifications to the existing [design system graph color palette](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?type=design&node-id=6201-687&mode=design&t=hrNb3hnFy2wWDm3j-4)

**Comment by luketa8** [comment]
[Branch with updates](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/branch/TUx5JWzzplZA7WT6mW1pZc/HPE-Color-Styles?type=design&node-id=0%3A1&mode=design&t=UQXKqJb2UShBPnYB-1) ready to review.

**Comment by SeamusLeonardHPE** [comment]
[Moved color experimentation assets  to this file](https://www.figma.com/file/ZWDM0wEJYV9xzQuVWrjfOE/Archived-HPE-Color-Explorations?type=design&t=O8FsqyG7VHk7j7sr-6) - Note -  no styles were relocated or edited

**Comment by SeamusLeonardHPE** [comment]
@luketa8 first pass of this re-structure looks good.
Can you request a review inside figma from @oliverHPE and myself.


Few notes

### Layout
The "secondary" colors palette should maybe be moved below the primary colors to avoid giving it visual prominence?


### Followup  ticket steps

I see you have added in, but not created styles from new colors related to this follow up ticket.
https://github.com/grommet/hpe-design-system/issues/3623

I think we could publish with those just as Hex values, but few questions prior to making styles out of those new colors.

The "secondary" colors palette were used for our "graph" colors in the mains branch (see image). Can you connect with a dev and ask what naming conventions are used in grommet for graph colors, and if we add or edit to them what the release process will be for the HPE theme code.




![Image](https://github.com/grommet/hpe-design-system/assets/135040188/9790c22f-f4bc-419a-af6d-c7ce44bca191)

**Comment by luketa8** [comment]
Graph colors are used currently with the above mentioned names:

example:
`<LabelledChart label="Used" value={98.2} color="graph-2" />`

**Comment by luketa8** [comment]
Quick question @taysea @Sulaymon333 

Can we add and/or edit the colors to align with this? 
 
![image](https://github.com/grommet/hpe-design-system/assets/5853565/904a573c-1590-4f49-a374-47bfe6d4a8bb)

**Comment by taysea** [comment]
@luketa8 Yes, these color names could be added to the theme in the future.

**Comment by luketa8** [comment]
File ready for final review/merge -> [Branch](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/branch/TUx5JWzzplZA7WT6mW1pZc/HPE-Color-Styles?type=design&mode=design&t=oWWsq1ajLFwX6z22-1)

**Comment by SeamusLeonardHPE** [comment]
Merged into main.

Just a note - updated were made to some color style metedata/names but have not been published.
This will not impact usage as the updated file is just presentational and no hex values have been edited in the styles.

Note that follow up ticket #3623   will consider

- How do we deprecate/migrate color styles in cases where there are errors or duplication.
- Tidy and standardise naming conventions
- Prep for tokens



![Image](https://github.com/grommet/hpe-design-system/assets/135040188/76cdac27-35ae-49d4-b045-4452ef5ccc92)
