### ISSUE TITLE
Pagination -- step selector subcomponent

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3708]
![Image](https://github.com/grommet/hpe-design-system/assets/12522275/d7c0c611-78ee-465e-8c09-3b1c61cc044d)

Figma: https://www.figma.com/file/nxI308Yvt4HKJ1rjgrEXCk/%233651---Pagination-Component?type=design&node-id=7-8028&mode=design&t=si0IuTW6QOuNtobF-4

Pagination prototype: https://codesandbox.io/p/sandbox/pagination-responsive-k58sjn?file=%2Fsrc%2FContents.js

This component allows the user to define their page size via a select control. This component should include:
- Label of "Items per page"
- Select control where the options are configurable

Deliverables:
- [ ] Draft PR of internal components that will be consumed by Pagination

**Comment by britt6612** [comment]
follow on tracked by #3734
