### ISSUE TITLE
Pagination -- pagination summary subcomponent

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3709]
![Image](https://github.com/grommet/hpe-design-system/assets/12522275/f796b15d-c1c4-4bbe-a850-9d9095a22856)

Figma: https://www.figma.com/file/nxI308Yvt4HKJ1rjgrEXCk/%233651---Pagination-Component?type=design&node-id=7-8028&mode=design&t=si0IuTW6QOuNtobF-4

Pagination prototype: https://codesandbox.io/p/sandbox/pagination-responsive-k58sjn?file=%2Fsrc%2FContents.js

This component should display "Showing X - Y of Z", where "X" is the start of page, "Y" is end of page, and "Z" is the total number of items.

Deliverables:
- [ ] Drafted PR of component

**Comment by britt6612** [comment]
follow on tracked by #3734
