### ISSUE TITLE
Github - Updating board to better fit teams and stakeholders needs

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3720]
This issue focus on tackling the organization of the designers board into more detailed and actionable views, facilitating the tracking of issues, priorization of backlog and visibility for stakeholders.

- [ ] Create a new project board that:
       - Has separate views for biweekly sprints, backlog, and other high-priority tickets (external requests, OH questions, sandbox contributions, etc.)
       - Has automation set up

**Comment by julauxen** [comment]
@SeamusLeonardHPE should we take the part about templates out of this ticket considering the effort and impact matrix?

**Comment by julauxen** [comment]
Hey Vicky, of course! Thank you for keeping me accountable. 
This ticket is pretty old and has been reshaped a few times. It's a continuation on work that seamus did during down-sprint, which you can find [here](https://www.figma.com/board/FIZu9BAAREDxGBCiuk1Pf4/%233819---Improving-board-structure-and-organization?node-id=0-1&t=zocGzA1HWu3BG6Mj-1). He also created new views in our board for explorations.

Right now this ticket is about cleaning up our board views and organizing the ones we want to keep and try to use. 
I had a meeting yesterday with @SeamusLeonardHPE and defined that, for now, we want: 

- Prioritized backlog
- View for OKR'S/Big Things
- View for current sprint

I am still doing some research on a few impacts that we might have to create a ticket and what might happen if we delete the first view. Once I have those answers I will finish the clean up.

**Comment by julauxen** [comment]
Closing this issue having delivered a board for current sprint, next sprint, backlog and big things. An OKR board needs more discussion and will be handled separately.
