### ISSUE TITLE
Notification - post publish tasks

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3727]
Tasks to be carried out as a result of recent notification component update.

This list is not exhaustive and can be expanded upon:

- [x] Replace deprecated instances in other components (Center Layer)
- [x] Replace deprecated instances in [Template Library file](https://www.figma.com/file/fupkQ4sOefx3qUVoV6WfJi/Template-Library?type=design&t=lyVzCjSTt1r2BH3w-6)
- [x] Update site guidance to remove all inconsistencies uncovered during research phase (out dated images, link color etc)
- [x] Align with devs to see if grommet hpe theme & story book are accurate to figma design

**Comment by SeamusLeonardHPE** [comment]
Branch created for first task

"[#3727 - Notification - Update deprecated components](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/GUEJkcdGZUqebx708QtrCK/HPE-Design-System-Components?type=design&node-id=5735%3A85900&mode=design&t=noXIQzAtZPoiXUIa-1)"

**Comment by SeamusLeonardHPE** [comment]
Notification fix branch has been reviewed and merged with main. Waiting to publish changes.


@luketa8 I have imported the guidance pages into [this figma file](https://www.figma.com/file/NHwIYhHjCIDi8aiWxd4jPP/%233727---Notification---post-publish-tasks?type=design&node-id=0%3A1&mode=design&t=Bh76Q7YMWFgTTheP-1)

Can you please add comments and make modifications based on all the errors and inconsistencies you discovered during your research? Let me know if this workflow suits. I find it easier to edit on figma and then plan how we can update the site code.

**Comment by luketa8** [comment]
- Deprecated instances replaced in Component Library and Template Library
- Suggested changes to Design System Guidance added to [Figma](https://www.figma.com/file/NHwIYhHjCIDi8aiWxd4jPP/%233727---Notification---post-publish-tasks?type=design&node-id=0%3A1&mode=design&t=EVmJA9QphzoMVFON-1)
- Revisited Grommet designer and Storybook for accuracy. In Grommet Designer there is a [bug](https://designer.grommet.io/?name=notifications%20test) related to padding in custom icon Inline Notifications. More details in this [File](https://www.figma.com/file/RQN7u7R418WJYKfQc07ZFx/Notification-with-custom-icon?type=design&node-id=0%3A1&mode=design&t=iOFbUt2F3JNbLNlH-1)
