### ISSUE TITLE
Create Selector component - #3646 Follow up

### ISSUE THREAD

**Issue by luketa8** [grommet/hpe-design-system#3729]
### Overview:

We propose the creation of a new design system component in Figma called "Selector." This component aims to streamline the process of making single and multiple selections, providing efficient filtering in data tables, and facilitating rapid selection processes during onboarding, support, and chat interactions.

## Features:

- **Single and Multiple Selections:** The Selector component should allow users to make both single and multiple selections seamlessly.

- **Efficient Filtering in Data Tables:** Incorporate features that enhance the efficiency of filtering in data tables, enabling users to quickly locate and select items.
- **Rapid Selection Processes:** The Selector component should be optimized for use during filtering, onboarding, support, and chat interactions, ensuring a swift and user-friendly selection experience.

## Use Cases

- **Data Tables**: Users should be able to use the Selector component to efficiently filter and select items in data tables, improving the overall user experience in managing large sets of data.
- **Onboarding, Wizard**: The Selector component should provide a user-friendly and rapid selection process during onboarding and/or configuration stages, making it easier for users to navigate and choose preferences.
- **Inbox**: Enhance case management usability by allowing users to efficiently filter through numerous cases/items, selecting multiple options at once. 
- **Support and Chat Interactions:** Implement the Selector component to enhance the selection process during support and chat interactions, reducing the time required for users to make choices.

## Additional Considerations:
- **Accessibility:** Prioritize accessibility features to ensure the Selector component is usable by individuals with diverse abilities.
- **Responsiveness:** Design the Selector component to be responsive across different devices and screen sizes.

## Deliverables

- Figma Component
- Component anatomy breakdown
- Additional documentation
- Use Cases

### Links to Figma files

[Research and proposal](https://www.figma.com/file/WellQcIogaHFdrAR0RYNz8/%233646---Quick-selection?type=design&node-id=287-4784&mode=design&t=hpEv1ARRCLOibzsC-0)

[Component building file](https://www.figma.com/file/gEl7V4t4Dd1ZGOZy6EswmQ/Selector-component-%233729?type=design&node-id=1%3A532&mode=design&t=kBtk82Ooy8cyKEDt-1)

@SeamusLeonardHPE 
@britt6612

**Comment by SeamusLeonardHPE** [comment]
Hey @luketa8 can you connect with @taysea and add an assignee to this task from the dev side.

**Comment by jcfilben** [comment]
Can this be closed?

**Comment by britt6612** [comment]
yes I believe we can close!
