### ISSUE TITLE
Fix figma Dateinput components

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3736]
Multiple issues have been uncovered with the existing date input components.

Sizing & icon alignment across multiple variants:

- Document and repair all errors in current state
- Follow up work will be how can we repair all inputs & build atomically to prevent such errors in future.

![Image](https://github.com/grommet/hpe-design-system/assets/135040188/e3ae2a7d-6302-476b-ab19-da8399ac8b4d)

**Comment by KennyAtHPE** [comment]
[Figma branch](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/dT2od9GrX3CpJxKdncUfxJ/HPE-Design-System-Components?type=design&node-id=212%3A578&mode=design&t=OXiKbOT9J78oberO-1)

Requesting review @SeamusLeonardHPE @ashifalinadaf 

I have gone ahead and updated the dateinput component based on user feedback and findings. **THE FOLLOWING CHANGES ARE NOT BREAKING CHANGES UNLESS SPECIFIED*

DateInput changes:
Input field
- Input field height set to 36px
- To achieve a left and right 12px padding for the value, the value has been shifted over and changed to 330px width
- Icons have been swapped out for icon-only buttons. The padding has been manually modified to reflect Grommet’s implementation
  
Misc:
- Label and Description are now filled widths and will resize correctly
- Error message layers have all been renamed to be the same (previously had two different spellings which would have prevented proper text overriding from variant to variant). **THIS MAY OVERRIDE USERS EXISTING ERROR MESSAGES**... I can omit if needed but didn't feel like this would be a major issue
- Error message set to fill
- Info message set to fill

----------------------------------------------
**TO AVOID BREAKING CHANGES, I HAVE NOT UPDATED**:
- Grouping and layers have not been deleted, restructured, or renamed (error message layers were renamed)        
         - Text will not override currently because of the current implementation. Will need to be changed in the future.

**Comment by ashifalinadaf** [comment]
Reviewed and left some comments on the figma reviewing. 
@KennyAtHPE

**Comment by KennyAtHPE** [comment]
@ashifalinadaf @SeamusLeonardHPE made all the changes you both recommended. Requesting just ONE reviewer from you two before merging.

**Comment by SeamusLeonardHPE** [comment]
Hey Kenny, 2 issues I see:

1- The "icon right" visibility boolean is applied to all variants expect the default. (could is be removed completely? surely the button is required to launch the calendar overlay?)
2- The "range" visibility prop is applied to some Date:Single text inputs

Dropped comments on figma also.

![image](https://github.com/grommet/hpe-design-system/assets/135040188/870b05b7-5ce5-499f-89e3-671f5da3f1ce)
![image](https://github.com/grommet/hpe-design-system/assets/135040188/a77cedf0-0e70-494e-972a-aecb4e6592cf)

**Comment by KennyAtHPE** [comment]
Changes made and merged. Changes listed in #3767. Closing ticket
