### ISSUE TITLE
Input components - Review and correct inconsistencies

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3741]
[OH question](https://www.figma.com/file/Lh01flLH73cFNGZiFxEFth/HPE---Office-Hours?type=design&node-id=7034%3A1216&mode=design&t=uiwsVq3FVpM0mdC9-1) from Tales

![Image](https://github.com/grommet/hpe-design-system/assets/86075038/fc04bf0b-29c8-4894-9930-0185ddf41109)

---------------------------------------------

### Deliverables
- [ ] Review all input components and list inconsistencies. **Confirm with devs on correct values,*check:
      - Auto layout settings (padding + space between elements)
      - Color for text, border, icons, and backgrounds
      - Labels, value, descriptions, and text generally are using the correct text style
      - Border radius and alignment
- [ ] Create a branch (multiple?) and stage fixes
- [ ] Review w/ 1 dev and 1 designer
- [ ] Merge changes
- [ ] Update files as needed
- [ ] Announce update + reach out to Tales

**Comment by KennyAtHPE** [comment]
dateinput changes are being done as part of #3635

**Comment by SeamusLeonardHPE** [comment]
In order to better manage branch & merging this ticket will only deal with the requests for fixes on the dateinput.

Additional tickets and figma branches specific to those fixes should be created to deal with the select input and the Maskedinput.

**Comment by SeamusLeonardHPE** [comment]
The date input issues were initially tracked 
https://github.com/grommet/hpe-design-system/issues/3736

The broader refactor will be managed
https://github.com/grommet/hpe-design-system/issues/3685

**Comment by KennyAtHPE** [comment]
DateInput bug fix branch reviewed and merged. A follow-up branch for the readOnly update has been created and is tracked in #3635. Fixes listed in #3767. Closing ticket
