### ISSUE TITLE
List Variation

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#376]
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [ ] Theme
- [ ] Grommet
- [ ] Code Examples
- [x] Guidance  

**Figma File**
https://www.figma.com/file/tMYTr17r6hhGajSlNRiPje/HPE-List-Tempalates?node-id=0%3A1

**Comment by saggiemilva** [comment]
Thanks for the suggestion. I will look into to making that this week.

**Comment by saggiemilva** [comment]
First pass at Guidance for list:

### List Variation Template 

**Best Practices(Why):** 

- Be consistent with layout and visual treatments for all list items. 
- Keep list item descriptions brief and concise. 
- Use Icons or Images in list items to help draw attention and support scanning. 
- Maintain sufficient space between list items or consider using dividers between rows. 
- Sort lists in a logical order such as alphabetically, numerically, chronologically, or by user preference. 

 

**Lists Types:** 

- Single-line lists are optimal for scan-ability, especially with the addition of an image. 
- Two-line lists provide a primary and secondary text which can be helpful when more detail is needed. 
- Three-line lists of a primary text and two lines of secondary text are not recommended. 
- Grid lists are made of image tiles and require more space. 

 

**Image + Name + Description + Action** 
Two-line list with an image, primary title, description, and an action button. 

**Image + Name + Option + Action** 
Single-line list with an image, primary title, short status tag, and an action button. 

**Name + Option + Action** 
Single-line list with a primary title, short status tag and an action button. 

**Name + Description + Option** 
Two-line list with primary title, description, and an action button. 

**Name + Action** 
Single-line list with only a primary title and an action button. 

**Tile + Left** 
Grid list with an image, primary title, description, and an action button. 

**Tile + Centered** 
Grid list with an image, primary title, description.

**Comment by L0ZZI** [comment]
@halocline on the list are you looking for a slimmer vertical height? Or are you just looking for a Label only? I'm just trying to understand whether you want to remove height or is it more for something inline with copy?

**Comment by halocline** [comment]
> @halocline on the list are you looking for a slimmer vertical height? Or are you just looking for a Label only? I'm just trying to understand whether you want to remove height or is it more for something inline with copy?

Probably more along the lines of a simple unordered list / being inline with copy. I was just thinking about use cases like "steps to resolve" or like we are using in the site's copy: 
![Screen Shot 2020-05-11 at 4 18 19 PM](https://user-images.githubusercontent.com/1756948/81617704-2c46a100-93a3-11ea-8ff1-9bd9e95d1d6b.png)

**Comment by ericsoderberghp** [comment]
Merged Lists page 9 months ago.
