### ISSUE TITLE
Guideline Structure - Build proposal of structure

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#3776]
**Who is requesting this?** (add contact details here)
Internal Initiative to improve the DS website experience.

**What is the problem this ask is trying to solve?**
Our website makes it hard for our consumers to find valuable information, causing confusion during the design phase. Besides, developers tend to go to storybook and grommet to find code examples that are not always right. We are trying to provide a source of truth for our consumers.

**Add links that contain a proposal, if it exists.**
Working file where we defined the problem and start explorations [here.](https://www.figma.com/board/UztDSvUrdpW73dvlMJif9N/Guidelines-Website?node-id=0-1&t=anIBXve9UqEwhwyC-1)
_______________________________________________________________
**Reviewers:**

- [x] Matt
- [x] Taylor
- [x] Oliver

**List possible consequences, involved assets and components:**
This ticket contains only explorations for future implementation, so no severe consequences.

**Define MVP for this ticket** (format, amount of detail, where it should live, etc):
Deliver templates that will guide us into delivering a new DS website experience. Possible templates: component page, parent page, pattern page.

**Follow up tickets:** (if necessary)
1.

**Checklist** (add your progress in the comments)
- [x] Define the Problem (build a small presentation about the problem)
- [x] Ideate (present at least two option with pros and cons)
- [x] Build _(not necessary as this issue is purely for exploration)_
- [x] [Guidance on writing guidelines](https://hpe.atlassian.net/wiki/spaces/DS/pages/2517172344) _(the current work is trying to define these guidelines)_
- [x] Gather feedback
- [x] Create a PR or new file _(not necessary as this issue is purely for exploration)_
- [x] Ask for review
- [x] Publish _(some new guidance was published using the MVP new content structure)_
- [x] Communicate

**Comment by vavalos5** [comment]
Hey Julia, can we add a description on what this ticket is about in addition to any links that would be helpful to reference. Thank you!

**Comment by julauxen** [comment]
Hey Vicky, I updated the description using one of our layouts and I will retrofit the work that has been done in the comments.

**Comment by julauxen** [comment]
## Ideate

The current proposal can be found in [this file](https://www.figma.com/design/r6ryakFwT3YB0bX8EOWbjM/Guidelines-Page?node-id=153-695&t=ECXJKCJtq0Sujf3f-1).

We developed the template according to our best guess and choose a few existing pages to test. By doing so we discovered that our current template works well for components, but not for parent pages and pattern pages. 

The next agreed step is to map the paths our consumers go through to understand how to define those.

**Comment by julauxen** [comment]
I interviewed George, Antonio and Marina and created their journeys [here.](https://www.figma.com/board/UztDSvUrdpW73dvlMJif9N/Guidelines-Website?node-id=328-912&t=92xUH7n250Q5mhCP-1). i also took some notes about pains and good things they like about the website. 

Next step: I will meet with the working group (taylor, oliver and matt) and present my findings.

**Comment by julauxen** [comment]
After presenting my findings to the working group it was decided that I would keep close to guidance to try to keep the content structure. All the other problems found will be handled and monitored through this Big Things ticket: [#3933](https://github.com/grommet/hpe-design-system/issues/3933)
