### ISSUE TITLE
Investigate proposal for new icon button active state.

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3779]
Investigate scope & impact of suggestion by Gina for additional icon button active state:

Should this be limited to her example, or could it be adopted by the design system

https://www.figma.com/file/7inaTPbYxswsiHhZmh7anq/For-review-with-DS?type=design&node-id=6-42766&mode=design&t=NBWzjp8JgPQXqT5J-4

> "There are a couple of use cases with my work for a variation of the icon-only button on the Contextual Help Side Panel, in the Virtual Assistant for support, and in Case Management.
 
> For the Side Panel – Chesley has requested that we make the active state of the “pinned” icon-only button stand out more as it does not provide enough affordance that it is active with the current default icon-only button’s active state.
 

> I created many variations with Chris Carlozzi and we landed on the stroke icon changing color to Brand green, changing to a glyph/filled icon, and rotating to look “pinned". You can find explorations and animations [in this figma file](https://www.figma.com/file/7inaTPbYxswsiHhZmh7anq/For-review-with-DS?type=design&node-id=6%3A42766&mode=design&t=MqSfDV5QLMk3LYXU-1)."

**Comment by KennyAtHPE** [comment]
- Check w/ GLP as to when they need this. This is doable with the current theme, but we will need to make a demo for them

**Comment by KennyAtHPE** [comment]
Reach back out to Gina once the release date is confirmed.

**Comment by KennyAtHPE** [comment]
3/11 update: Connected with Jeff S. and Gina. 

Next steps:
- [ ] Pair w/ dev to mock coded example
- [ ] Share with team to estimate delivery date

**Comment by KennyAtHPE** [comment]
More details for this ticket @SeamusLeonardHPE

### Problems + Guiding Questions
- Our current icon-only button does not provide enough affordance when selected and when in an active state.
       - Does this apply to all icon-only buttons? Specific use cases only for selection?
       - Does this apply to filled, outline, or both types of icons?
       - Are animations required to be in this first pass?

### Acceptance Criteria
- Treatment color + animation must align with Design System guidelines (MUST BE ACCESSIBLE!)
- Treatment must provide additional affordance for selected/active icon-only buttons
- Reviewed and approved by Gina + stakeholders

### Next Steps
- [WIP] Identify use cases
         - What type and for what use case(s) would this treatment and behavior be expected?
         - Should icons default to being outlined when used for selection?
- [WIP] Explore visual treatments for icon-only buttons
         - Explore animation details
         - Keep in mind dark mode
- [WIP w/ Brittany] Create a coded prototype example
         - Provide an estimated release timeline
- [ ] Review w/ Team
- [ ] Review w/ Gina + stakeholders

**Comment by KennyAtHPE** [comment]
3/28 update: Provided Gina w/ the prototype link and received positive feedback. Will be closing out this ticket and creating a new one to tackle the guidance site update.
