### ISSUE TITLE
Forms with Character Limits - Implementation doesn't follow accessibility guidance

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#3787]
In the Design System site Forms - Fields with Charater Limit section we have the following accessibility guidance:

- Announce the max character allowed before the user begins typing.
- Announce when the user has typed beyond the threshold of the max allowed.

The examples on the page are not following this guidance. We should update the examples so that they are accessible and are built with the functionality added in this PR: https://github.com/grommet/grommet/pull/6550.

https://design-system.hpe.design/templates/forms?q=form#fields-with-character-limits

**Comment by britt6612** [comment]
closed by #4484
