### ISSUE TITLE
Typography file tidyup

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3789]
Ladders up to OKR **[2024 Q2 Objective 4 - Improve Designer Experience and productivity](https://hpe.sharepoint.com/:p:/r/teams/hpe-design/_layouts/15/Doc.aspx?sourcedoc=%7B578BCD68-03C8-4054-88BC-B24EADABBE7A%7D&file=HPExs%20Goals%20Jan%202024%20-%20DS.pptx&action=edit&mobileredirect=true)**

Follow on task related to #3648 

The public facing[ typography styles file ](https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?type=design)contains out of date experimentation

- [x] Backup typography file with branch & create version history point
- [x] Create new figma file in archive project folder to back up pages
- [x] Move all non essential items to archive
- [x] Branch icon file to create "tidy" branch  where we will modify frames & positioning with Olivers template.
- [x] Request review
- [ ] Merge tidy into main

**Comment by SeamusLeonardHPE** [comment]
[Archived type experiments moved here ](https://www.figma.com/file/xLLc6X7unhzYpFS1pp7vOR/Archived-Typography-Exploration?type=design&t=O8FsqyG7VHk7j7sr-6)- Note no styles were moved of edited

**Comment by SeamusLeonardHPE** [comment]
Requested review from @oliverHPE & @luketa8

**Comment by SeamusLeonardHPE** [comment]
Merged after review by Oliver

**Comment by vavalos5** [comment]
@SeamusLeonardHPE I was taking a look at the Typography styles, they look great! One thing I noticed is that we're still using the MetricHPEXS name on the thumbnail, we'll just have to remove "XS" from the name. :)
