### ISSUE TITLE
Selector component - Component in branch

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3810]
Ladders up to "**2024 Q2 Objective 2** - Deliver tools for presenting, manipulating, and acting on data collections"

Ship “quick filter” variants (grommet+figma) move up​

Follow up to 
https://github.com/grommet/hpe-design-system/issues/3729
https://github.com/grommet/hpe-design-system/issues/3646

- [x] Create branch off main 3810 - Styled selector
- [x] Define name for new component & page name.
- [x] Import most up to date agreed upon component to branch (no need for dark mode)
- [ ] Define and populate metadata
- [ ] Request figma review of branch
- [ ] Align with dev release prior to figma merge

**Comment by luketa8** [comment]
- Created [Figma branch](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/QNzyc61prL0zNDyDPHLGz1/HPE-Design-System-Components?type=design&node-id=27691%3A1164&mode=design&t=dPXZTzBDqdltQUN4-1)
- Completed first version of Selector
- Added first round of metadata

Next steps:

- Create a user testing file to gather feedback from product designers.
- Assign a Dev to start working on first protype.

**Comment by SeamusLeonardHPE** [comment]
@luketa8 can you please add links to the user testing file and update this ticket with progress.

**Comment by luketa8** [comment]
- [User testing file](https://www.figma.com/file/JDUMKQHGWy3vwN2OeDFacY/Selector-component---User-test?type=design&node-id=3%3A2414&mode=design&t=IQ2ZRohKGBbUXM2n-1) ready

- Moved component and parts to [Figma branch] -> Ready for Development (https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/QNzyc61prL0zNDyDPHLGz1/HPE-Design-System-Components?type=design&node-id=27691-1164&mode=design&t=d0jUS005b4k7V31Y-0)

**Comment by SeamusLeonardHPE** [comment]
@luketa8 have the remaining checkbox tasks been completed for this?

If there are no outstanding design tasks for this it could be closed as complete.

**Comment by SeamusLeonardHPE** [comment]
Closing pending

1. Dev capacity & feedback when coding prototype
2. Any potential impact on build based on slot component  definition
