### ISSUE TITLE
Avatar - Adding text prop

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#3812]
- [x] Create branch
- [x]  Complete update work
- [x] Get Reviews from @KennyAtHPE @SeamusLeonardHPE 
- [x] Create a version history point in the main file
- [x] Merge Branch
- [x] Publish and announce

**Link to branch**
https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/xhSGnOlYxc9dP2PeiUOmAS/HPE-Design-System-Components?type=design

**Comment by CillianHPE** [comment]
Added the content property for the initials.

**Comment by SeamusLeonardHPE** [comment]
Reviewing component modification.

### Changes - Non Breaking
- Addition of Text Property to Initials text string on "Initials" variants

### Affected Items
- GlobalHeader
- PageHeader

**Comment by SeamusLeonardHPE** [comment]
![Image](https://github.com/grommet/hpe-design-system/assets/135040188/725829ff-3c42-4b58-832c-9ae43dd139ef)

**Comment by KennyAtHPE** [comment]
Quick template for update messages:

"The following changes have been made to the [component]:
- List of changes

For any questions or concerns, please reach out to [designer who made the changes] or [1 other designer]"

--------------------------------------------------
What update message should we have for components that have been directly affected by another component being updated? In this case, would it be fine to say "The Global Header and PageHeader components have been updated to consume the latest Avatar changes. For any questions or concerns, please reach out to [designer who made the changes] or [1 other designer]"
