### ISSUE TITLE
Prototype - Data collection create and manage saved views pattern

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3813]
### What does this request relate to?

Data and friends pattern

### Describe the feature you'd like to request.

Develop a prototype for create and manage saved views pattern that may then be used in user testing by the research team.

Need to provide Harsha and Gerry from research team a commitment for when the prototype(s) will be available so that they can align the study and participants accordingly.

Goal is to get research finding back within Jhansi.

### Links to Figma files with use cases or ideations from you.

Hello everyone,

 

Thanks for attending yesterday’s demo, for those who could not make it, you can view the ​mp4 icon[ recording](https://hpe-my.sharepoint.com/:v:/p/harsha_kr/Eb1KuFeEhM1KuY9efZG39ksBxy1IZP4q0kdSpoqenIVtww?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view).

Below are the key points discussed and the next steps:

 

We will go ahead with the device inventory data table for testing table personalization.
The quick filters might become less useful once the user starts creating saved views.  
The quick filters are a set of static filters and might not be useful. We could have them as a read only information or explore other data visualization options.
We would not have a [2 click filter along with select views](https://www.figma.com/file/kvvK2veLByNrSf3cKRAmwN/Tables-Design-Spike?type=design&node-id=406%3A7993&mode=design&t=CoySAbP7mSXzoQri-1) since they both have an overlapping use case. We can combine both under select views.
We can remove the quick filters for this research and test the saved views.
In the 2nd option can provide the ability to reorder the saved views under manage views section.
We can do a A/B test b/w both the options.
We can include the ability to toggle b/w different data views (like map view) and consult with the research on how we can test this.
 

Next steps:

 

I would refine the designs based on our discussions and handover the designs to the design system team to build a prototype.
Matt to work on the timelines for building the prototype.
Once the designs are complete I would work on building the initial test cases for the research.
 

Meanwhile, feel free to go through the [designs](https://www.figma.com/file/kvvK2veLByNrSf3cKRAmwN/Tables-Design-Spike?type=design&node-id=959%3A92555&mode=design&t=CoySAbP7mSXzoQri-1) (WIP) and add your feedback/comments.

 

Thanks,

Harsha

### How urgent is this request?

Fairly urgent

**Comment by taysea** [comment]
Prototype has been delivered! Closing this ticket
