### ISSUE TITLE
Design guidelines

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3818]
Design checklists
• A check-list was suggested to help guide our work.
• The check-list can serve as a reference for designers to ensure they cover all important points in their process.

Design templates
• Design templates, such as Figma templates, can provide a structured framework for designers to follow.
• These templates can include pages for each major step in the design process.

**Comment by KennyAtHPE** [comment]
Down sprint objective: Create GitHub templates for common issues/tickets. These templates will:
- Help guide work
- Provide a quick start for common issues/tickets
- Set a standard on how to approach common issues

Work is being tracked in the 'Templates' tab within this project board

**Comment by SeamusLeonardHPE** [comment]
https://www.figma.com/file/NgilbfnEOkrT8Yn92OmP6s/%233818---Design-guidelines?type=whiteboard&node-id=0%3A1&t=Wz86sTqGdTvoAa9A-1
