### ISSUE TITLE
Effective problem-solving strategies

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3821]
Clearly articulate success criteria
• Clearly define the criteria for evaluating solutions.
• Use objective yes/no evaluations to determine if a solution meets the criteria.

Seek input and feedback
• Set up focused huddles with stakeholders to address stalled or blocked issues.
• Ask for input and feedback from others.

Connect with others
• Connect with others as soon as possible to collaborate and gather different perspectives.

**Comment by CillianHPE** [comment]
FigJam Link Here

https://www.figma.com/file/0Sd6FlHgnMsP84SQMqsDHY/Process-%2B-Success-criteria?type=whiteboard&node-id=0%3A1&t=vTy5UrD0M4Rt101b-1

**Comment by oliverHPE** [comment]
Update:
The first outcome of this work is that we need to encourage healthy behaviours regarding 'problem solving'. 

For example, these behaviours might include:

- Writing success criteria
- Following some form of design thinking process, which might include:
 - Understanding the problem and context
 - Defining the problem
 - Solving at a macro, then micro level
- etc.

Ideas to encourage this behaviour were:
- Ticket template (problem solving orientated) -  a ticket template that has checks for success criteria, etc.
- Figma file template, focused on problem solving
- Introduce a way to classify work as small or large
- Solve issues (pick-up tickets) only after refinement
- Consensus / go-ahead on whether to spend the time to refine a ticket or submission to the system

At this point we need to assess which of these ideas, if any, to refine and produce.
