### ISSUE TITLE
Problem-solving steps

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3823]
Define the problem
• Focus on written comprehension before design work.
• Use the 5 whys to get to the root of the problem.
• Clearly articulate the problem and avoid ambiguity.
• Review the problem statement and assess any drift or direction change.

Clearly articulate success criteria
• Define a success criteria for each problem being solved.
• The criteria serves as an objective evaluation of the solution.
• The success criteria should be a guidepost for all work that follows.

**Comment by oliverHPE** [comment]
Figjam Board for this ticket:

https://www.figma.com/file/0Sd6FlHgnMsP84SQMqsDHY/Process-%2B-Success-criteria?type=whiteboard&node-id=0%3A1&t=vTy5UrD0M4Rt101b-1

**Comment by oliverHPE** [comment]
Closing this ticket as it the same piece of work as ticket [#3821](https://github.com/grommet/hpe-design-system/issues/3821)
