### ISSUE TITLE
DataTable Customization - Locked column order

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3842]
#### Who requested the changes? Include all stakeholders
- [Original Slack thread
](https://hpe.slack.com/archives/GPPLUK6LR/p1712617932867599)
- [Original ticket
](https://github.com/grommet/hpe-design-system/issues/3829)
- Brittany is working on changing the Grommet theme for this enhancement

#### What components will be affected? Include links to branches, working files, etc.
[DataTable Customization 
](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=2914%3A52754&mode=design&t=kYDChKNwmDQptT3c-1)
[Branch](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/pTzF9LQDo6dWt8HNBLFgCc/HPE-Design-System-Components?m=auto&node-id=2914-52754&t=KiC1IhkC2O9S8Z2F-1)

#### What changes will be made? Why?
[Design rationale
](https://github.com/grommet/hpe-design-system/issues/3829)
- [x] Subcomponent '.DataTable Customization/Order items'
       - A new variant for the lock icon will be added
#### Who will be reviewing this work? At least one designer is required. Include developers for review when possible
- [ ] Seamus
- [ ] Brittany
#### Are there any anticipated breaking changes? Will local components be overridden when updated?
N/A

---------------------------------------------------------------------------------
### Publishing steps
- [ ] [Create a version history](https://help.figma.com/hc/en-us/articles/360038006754-View-a-file-s-version-history#h_01HAW5W5YMDRGASWXX2CV1KXZF) on the parent file
- [ ] [Merge branch](https://help.figma.com/hc/en-us/articles/5691189138839-Merge-branch-into-main-file#merge)
- [ ] Publish Component w/ message
```
The following changes have been made to the [Component]:
- [Change]
- [Change]
For any questions or concerns, please reach out to [designer].
```
~~[ ] (For large enhancements) Announce within Slack on the `HPE-Design-System` channel~~

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf  This edit will be inherited by Toolbar component and should be tested there.

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf tasks remaining on this issue that you will take over from Kenny are all related to the tabs refactor.

- [ ] Insert and customize the new tabs component into DataTable
- [ ] Check responsive behaviour in DataTable to make sure it mimics code
- [ ] Remove dark mode variants & sub component variants
- [ ] Request review

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE @SeamusLeonardHPE confirming with devs that the build is correct, will update if necessary

**Comment by ashifalinadaf** [comment]
Working on the tasks assigned

**Comment by ashifalinadaf** [comment]
Based on the inputs from D&D
following changes have been applied to the DataTable customisation 
- Changing the width of tabs to fill container
- Width of the DataTable customisation is reduced from 311px to **304**px to align with grommet as flex width. 
- Tabs width  from 287px to **280**px

Up for review
