### ISSUE TITLE
Tidy the HPE template library

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3843]
Whats in the scope of work:  

### MVP:

- Tidy existing pages (fit & finish match component library)  
- Remove any ‘patterns’ that have been made into components (pagination) 

### Suggested steps

- Create brach of Library file
- Import headers & supporting assets from [Utility file](https://www.figma.com/file/IFHe056XfdPcXI2IdAxkX9/%E2%9C%8F%EF%B8%8F-Utilities?type=design&t=WqTL3D6e4g5T8fgP-6)
- Create example page with similar formatting/spacing to component/parts & seek review.
- Connect with Oliver for any additional assets or visual requirements
- Connect with team to decide on what pages to edit/remove/archive

Secondary tasks & team sessions to discuss and define for follow up work in Q3:
- Define the purpose of the template library:  
- Should stickier sheets live here for components? On a single page?  
- Ultimate goal is page templates - but how do we evolve to reach that.
- Current experimentation on data-viz - is this still a suitable home.
- Is the library a suitable place for our “alpha” release components for upcoming/wip component releases.

**Comment by luketa8** [comment]
Working notes:

There seems to be a discrepancy of page background colors:
- Utilities library: Cover page is `#F5F5F5` while components page is `#EAEAEA`
- Components Library: All pages are `#E5E5E5`
- Template Library: All pages are `#F5F5F5`

**Comment by luketa8** [comment]
### Purpose of the Template Library

The Template Library can serve as a repository of pre-designed layouts, wireframes, or starting points for common product design scenarios. While our Guidance site provides documentation and best practices, and our Component Library offers reusable Figma UI elements, a template library can complement these by providing holistic starting points for entire design compositions.

### Sticker sheets

A sticker sheet can serve as a collection of commonly used UI elements, icons, and graphics that designers can easily drag and drop into their designs. It essentially acts as a repository of pre-made assets, providing quick access to frequently used configurations and layouts of components without the need to reconfigure or set them from scratch.

**Comment by luketa8** [comment]
- Updated [Figma Branch](https://www.figma.com/file/fupkQ4sOefx3qUVoV6WfJi/branch/NmgalNiG3nVXiRG4ElXWn5/Template-Library?type=design&node-id=163-77&mode=design&t=DyFXKNOaKVd0vSA5-0)

- Added comments on pages to be removed/redesigned

- Working on example page [Forms](https://www.figma.com/file/NmgalNiG3nVXiRG4ElXWn5/%233843---Tidy-up?type=design&node-id=163-77&mode=design)

**Comment by luketa8** [comment]
- Moved Data Viz pages to [Data Visualization Library](https://www.figma.com/file/2Y4caVQLZjjXtQ2kwHJfUy/Data-Visualization-Library?type=design&node-id=0-1&mode=design&t=zRKiad0ls4z56NZr-0) for future development.

**Comment by luketa8** [comment]
[Figma branch](https://www.figma.com/file/fupkQ4sOefx3qUVoV6WfJi/branch/NmgalNiG3nVXiRG4ElXWn5/Template-Library?type=design&node-id=129-4306&mode=design&t=tGEnDol94rfTVWEw-0) cleaned up and ready for review 

@SeamusLeonardHPE @oliverHPE 

### Dependencies for follow-up ticket: 
- [ ] [Slot component](https://github.com/grommet/hpe-design-system/issues/3826) -> to compose Layer templates
- [ ] [DataTable](https://github.com/grommet/hpe-design-system/issues/3705) component -> to compose templates that consume Data Toolbar + Data Table + Pagination Footer.
