### ISSUE TITLE
POPOVER - Draft guidelines for Popover component

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#3844]
Who is requesting this? (add contact details here)
Follow on from [Inline help popup / Enhanced tooltip #3780](https://github.com/grommet/hpe-design-system/issues/3780)

What is the problem this ask is trying to solve?
Deliver guidance on the new popover component.

Add links that contain a proposal, if it exists.
Check [this work file](https://www.figma.com/file/r1YUOdncOi0Bdl8msDF7Ni/Popover---%233780?type=design&node-id=0%3A1&mode=design&t=bCUDCDInuL7rzHcD-1) (OUTDATED) to see preliminary guidelines.
[
Current draft guidance](https://www.figma.com/design/mLtxaB1Yga3T9cXiZQSp8I/Popover---%233844-%2B-%234050?node-id=2005-23605&t=YNJ7A0odNMNMz4XV-1)

Other details and links.
_______________________________________________________________
Reviewers:
- [x] Seamus
- [x] Julia

Checklist (add your progress in the comments)
- [x] Define the Problem
- [x] Build
- [x] Guidance on writing guidelines (WIP)
- [x] Gather feedback
- [x] Ask for review
- [x] Dev ticket created https://github.com/grommet/hpe-design-system/issues/4087

**Comment by KennyAtHPE** [comment]
8/6 EOD Update:
[WIP]

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE Closing for now. Further refinement will be done within the dev ticket #4087
