### ISSUE TITLE
SelectMultiple - Align content w/ Grommet + DS site

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#3846]
#### Who requested the changes? Include all stakeholders
Amanda Vogel, [original slack thread](https://hpe.slack.com/archives/C04LMJWQT/p1713463164560469)
#### What components will be affected? Include links to branches, working files, etc.
[SelectMultiple](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=3206%3A58995&mode=design&t=dsWcqThgY8JjQy04-1), [Branch](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/e9XHkn0excAN0FqYUCYksT/HPE-Design-System-Components?type=design&node-id=3206%3A58995&mode=design&t=10xgyFywMk6a1SjE-1)
- .SelectMultiple/Select
- .Selection Summary
#### What changes will be made? Why?
Amanda pointed out that the component currently differs from Grommet and the DS site guidance. Updating to align. Confirmed by Taylor that these changes should be made.
- [x] .SelectMultiple/Select
    - Change Value from "6 items" to "6 selected"
- [x] .Selection Summary
    - Change Selection from "6 of 12 selected" to "6 selected of 12"
#### Who will be reviewing this work? At least one designer is required. Include developers for review when possible
- [x] 1 Designer
#### Are there any anticipated breaking changes? Will local components be overridden when updated?
N/A

---------------------------------------------------------------------------------
### Publishing steps
- [x] [Create a version history](https://help.figma.com/hc/en-us/articles/360038006754-View-a-file-s-version-history#h_01HAW5W5YMDRGASWXX2CV1KXZF) on the parent file
- [x] [Merge branch](https://help.figma.com/hc/en-us/articles/5691189138839-Merge-branch-into-main-file#merge)
- [x] Publish Component w/ message
```
The following changes have been made to the SelectedMultiple:
- Updated content to better align with Grommet.
For any questions or concerns, please reach out to Kenny Tran.
```
- [x] Reach back out to Amanda

**Comment by luketa8** [comment]
Branch reviewed. Looks good to me.

**Comment by SeamusLeonardHPE** [comment]
Changes merged

<img width="479" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/2efbe0b6-c610-462b-98a2-06addc44e9f3">
<img width="263" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/7f0ce842-1ee7-4ea9-884f-9a60d2a2f970">
