### ISSUE TITLE
Audit labels and create new ones for blocked issues

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#3850]
This ticket is a follow up from the Process Workshop.

### Problem it's trying to solve:
HMW help the team have visibility on blocked issues and its reasons?

**Examples for reasons of blocked issues:**

- Capacity
- Lack of clarity about the task
- Sign off / Review
- Lack of consensus
- Scope creep
- External to team
- Waiting on dependence
- Definition of done

Figma: https://www.figma.com/file/ZbmozZ6mRDLhJh9BQYowSi/%233822-Structuring-meetings-for-Ticket-unblocking?type=design&node-id=0%3A1&mode=design&t=BwVZKKBzeb8Z8uOk-1

**Comment by julauxen** [comment]
Talk to devs about creating this specific tags, can we delete tags

**Comment by halocline** [comment]
> Talk to devs about creating this specific tags, can we delete tags

Yes, we can delete tags/labels. However, before we do so can we have a proposal to review prior to deletion?

**Comment by julauxen** [comment]
See edited label repo here: https://github.com/grommet/hpe-design-system/labels
See best practices about labels here: https://hpe.atlassian.net/wiki/x/moYPkw
