### ISSUE TITLE
Define Process for documenting, reviewing and implementing feedback

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#3853]
**Who is requesting this?** (add contact details here)
Internal Request. This issue is a follow on to the Process Workshop.

**What is the problem this ask is trying to solve?**
We often struggle as a team to ask for the right feedback, provide the right feedback and decide what feedback should be implemented and what should be taken with a grain of salt. We also struggle to document those feedbacks.

_______________________________________________________________
**Reviewers:**

- [x] Seamus
Feedback will be request from the full team.

**List possible consequences, involved assets and components:**
1.

**Define MVP for this ticket** (format, amount of detail, where it should live, etc):
This ticket will encompass exploratory work on how we can improve these practices, so therefore there are not deliverables defined. A best guess is best practices defined and assets that could help team member gather and document feedback.

**Follow up tickets:** (if necessary)
1.

**Checklist**(add your progress in the comments)

- [x] Define the Problem (build a small presentation about the problem)

- [x] Ideate (present at least two option with pros and cons)

- [x] Gather feedback

**Comment by julauxen** [comment]
@luketa8 @vavalos5 
Hey guys, adding you here cause I will be working on this in the current sprint and I've heard you are doing something similar. Might be good for us to sync.

**Comment by julauxen** [comment]
Met with @luketa8 and @vavalos5 yesterday and decided to start by doing an exercise to uncover the root cause. 
Also adding here previous work done by @SeamusLeonardHPE: [Figma file.](https://www.figma.com/board/5XfmekigAxNCq2Y6GU6aha/Demos-%26-Feedback?node-id=0-1&t=KSav2hE5wcikfxpJ-1)

**Comment by julauxen** [comment]
## Define the Problem
After doing the 5 why's activity, here are some problems identified:

- There's no agreed and documented expectations for each session and for each participant (presenter, reviewer, facilitator, note taker, etc)
- There's no owner for specific area and no decision hierarchy
- There's no agreed amount of time that we should spend providing/digesting feedback
- There's no agreed structure to document both the design thinking process and feedback

**Comment by julauxen** [comment]
## Ideate
### For each problem, here's where we are with solutions:
**There's no agreed and documented expectations for each session and for each participant (presenter, reviewer, facilitator, note taker, etc**)
I started to document the sessions expectations [here](https://hpe.atlassian.net/wiki/spaces/DS/pages/2447081748/Sprint+Schedule#Meetings-Description). I am waiting on some agreements being made among leadership. 

**There's no owner for specific area and no decision hierarchy**
Ongoing discussion with Scott on how to go about this.

**There's no agreed amount of time that we should spend providing/digesting feedback**
Not started.

**There's no agreed structure to document both the design thinking process and feedback**
Not started.

See [here](https://www.figma.com/board/5XfmekigAxNCq2Y6GU6aha/Demos-%26-Feedback?node-id=2156-489&t=jppjHDqVbnP4azLi-1) the brainstorm.

**Comment by julauxen** [comment]
## Ideate

I shared the root cause analysis and the brainstorming with the team and then discussed it in critique. Here are the points the team agreed on:

- There's a need for alignment on meeting expectations. @SeamusLeonardHPE will help with this and align with the rest of leadership.
- No need to invest time in delivering standard templates, techniques and best practices for presentations. The team agrees everyone has their own method, but we also agree we can try templates/methods that might help us get better results - that will be a personal responsibility.
- There's a need to define "area owners" who will be stronger voices in the decision-making process. @SeamusLeonardHPE will help with this and align with the rest of leadership.
- The team agrees we must have a place to document decision rationale - Specific place and agreed practices tbd.
- We will create a channel specific for async feedback requests between designers. @KennyAtHPE will help with that.

**Comment by KennyAtHPE** [comment]
@julauxen Been a bit caught up with tickets I'm on but will prioritize creating that channel + researching plugins that can simplify that flow during the start of this new sprint.

**Comment by SeamusLeonardHPE** [comment]
Closing with follow up tasks in 
https://github.com/grommet/hpe-design-system/issues/4047
