### ISSUE TITLE
Refine page templates

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3871]
[Branch Figma file](https://www.figma.com/design/fupkQ4sOefx3qUVoV6WfJi/branch/4qIbh5eqm2vFfkAqdEkzww/Template-Library?m=auto&node-id=4040%3A6121&t=kCITWh3D2mtTNpYk-1)

Ticket size: S/M

### Objective
Refine Page Templates i've previously created utilizing refactored or updated components + Seamus's new PageLayout skeletal templates. In addition, let's define naming conventions and nesting elements in correct container.

**Success Criteria**
- Easy to digest templates
- Proper naming conventions/aligned within Figma layers and DS site
- Easy start up templates + swappable content with updated refactored components

**Deliverables**
- [x] Create a branch on new PageLayouts page
- [x] Review previous templates created with Seamus and agree on the ones we'd like to transfer over
- [x] Refine and replace any necessary components to bring up to date
- [x] Refine naming conventions + place elements in correct frames using the naming conventions discussed
- [x] Share out w/ team
- [x] Implement feedback
- [x] Refine where "skeletal" and actual page templates will live
- [x] Review w/ 2 designers

Seamus's File
https://www.figma.com/design/fupkQ4sOefx3qUVoV6WfJi/Template-Library?node-id=4040-6121

Vicky's previous file
https://www.figma.com/design/4rdBkUlHd5MCVq3hvUOXHd/Page-Layouts?m=auto&node-id=5639%3A166208&t=qnaplY9YsM2qF3Km-1

**Comment by vavalos5** [comment]
@SeamusLeonardHPE Take a look at the branch i've created from the work you previously did implementing the work i've previously done. As discussed, i'm proposing we call the "skeletal" work you've done as "PageLayout Breakpoints" and the work i've done "PageLayout Templates".

Please review stickies in file with questions and proposals in file. Thanks!

**Comment by vavalos5** [comment]
Sent for a branch review to Seamus.

**Comment by vavalos5** [comment]
Seamus and I have merged branch. Done!
