### ISSUE TITLE
Individual 'Tab' for enabled state is missing underline

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#3879]
**Describe the bug**
The individual 'Tab' component does not have an underline stroke applied. The underline stroke is only applied on the Responsive Tabs component. Therefore, I am required to add in a bottom border in the autolayout frame for my set of tabs.

**To Reproduce**
Use the Individual tab component, create an autolayout frame, add multiple tabs with the 'enabled' state -> No bottom border.

**Expected behavior**
I would expect to do one of two things: A bottom border is built in to the individual tab component OR I have direct guidance to add  a bottom border to the frame that contains my set of tabs.

**Screenshots**

**Additional context**
![image](https://github.com/grommet/hpe-design-system/assets/17889451/b8f5acbf-9e14-45b2-9af9-0c7e7ca91f87)

**Comment by SeamusLeonardHPE** [comment]
Refactor component to match expected behaviour as demoed at link

https://v2.grommet.io/tabs?theme=hpe

Explore if we should add "badge" feature

**Comment by ashifalinadaf** [comment]
[WIP file ](https://www.figma.com/design/AE0Nk0dfPcZkGSNBowMm3t/3879---Tab-refactor?node-id=1-6&t=CX4X20etLswACBye-1)

**Comment by vavalos5** [comment]
@ashifalinadaf Thanks for including your link here. Is this still up for a review?

If so, can you specify where we should be looking (the solution), a description of what changes have been made, any suggestions or questions you have. 

In addition, tag who you're looking for a review from.

Thanks!

**Comment by ashifalinadaf** [comment]
@vavalos5 
This is under review with designers, 
[Branch for tab refactor](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/pTzF9LQDo6dWt8HNBLFgCc/HPE-Design-System-Components?m=auto&node-id=8985-115760&t=BdOmSc5VRh9P0a7C-1)

Motive is not allowing designers to build their own component out of single tab
New component resolves the issue of having only one tab or have a tab group with border - tab group frame with bottom border.
Original request was about adding underline to ‘individual tab’
Underline in grommet is on parent “tabs’ container
Solution:
Move individual tab into unpublished - part/sub component
Provide ability to select number of tabs
New component
Default - Tabs set to hug, underline on parent container which can be adjusted to any size.
Overflow - adds navigation buttons and tab group has horizontal overflow

**Comment by SeamusLeonardHPE** [comment]
Closed as done - follow up work on using tabs inside DataTable Customization  [#3842](https://github.com/grommet/hpe-design-system/issues/3842)

Component will be published when that work is complete
