### ISSUE TITLE
Documentation - Toggle Group

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3882]
[Figma File](https://www.figma.com/design/bMVkdgHkimCENGHiKPGcYH/Maps?node-id=1866-37552&t=t6cw8uoOcCKWZTZC-1)

Scope: Written guidance draft only. Code examples can be added later.

HMW: HMW ensure we successfully create guidance and layout content for easier discoverability for our users using existing template created by Julia?

Guidance sections to be drafted:
- **What and why** (a concise message for what the component is and why it exists).
- **Use case examples** (generate a shortlist of common use cases for this component and a one sentence description of why it applies to this use case). Code examples will be created as a separate scope of work.
- **Anatomy**
   - Follow [table format](https://design-system.hpe.design/components/layer?q=layer#anatomy). Coded diagram will be separate scope.
- **Types** (this should capture that it can be single or multiple selection)
- **Accessibility**
   - Keyboard behavior (tab to group, use arrow keys within group)
   - In icon-only cases, ensure each icon has a clear a11yTitle.

Deliverable:
- [x] Review and familiarize myself with Asif's Toggle Group work, review guidance i've previously created + note down any questions
- [x] HMW problem statement
- [x] Using layout template, layout i've previously created, create a second draft on guidance.
- [x] Share with Amanda, Greg and Tales for feedback
- [x] Share w/ 3 designers: Asif + Seamus + Kenny for feedback
- [x] Share w/ team
- [x] Implement feedback
- [x] Draft of ToggleGroup written guidance added to [PR](https://github.com/grommet/hpe-design-system/pull/3883)

**Comment by vavalos5** [comment]
I did some digging around as I recall creating guidance for this already in the past. I've found the [link to the guidance](https://www.figma.com/design/bMVkdgHkimCENGHiKPGcYH/Maps?node-id=955-88206&t=ejvPDfitTZu4BtkE-1) i've previously created. I've worked on this with Matt and Scott in the past. I'm happy to rework it to be aligned to the template Julia has started in the past and build on it.


![Image](https://github.com/grommet/hpe-design-system/assets/62117454/bf82bb5f-5595-478a-956e-1ea7a1522d64)

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/e95ebf8d-6ef6-4655-a994-04cfba1b3333)

**Comment by vavalos5** [comment]
@SeamusLeonardHPE @KennyAtHPE @ashifalinadaf Can you please take a look at the [2 options i've created for the ToggleGroup](https://www.figma.com/design/bMVkdgHkimCENGHiKPGcYH/Maps?node-id=1866-37552&t=t6cw8uoOcCKWZTZC-1) guidance/layout. I've used the[ layout template that Julia created](https://www.figma.com/design/r6ryakFwT3YB0bX8EOWbjM/Guidelines-Page?node-id=29-1266&t=INce4tAYQHTgQ0j8-0) but also identified other small explorations. I'm looking for feedback on the following:

- the live demo section - discoverability of resizing button ( this button enables users to interact with components/templates at different resolutions through visual information on what t-shirt size they’re viewing it in) + clarity on what it does
- thoughts on code box hidden until code icon is selected
- easiness to peruse and understand
- option 1 vs option 2
- open to any other feedback and suggestions

I'll also be sharing out tomorrow for D&D.

Feel free to also peruse through my stickies. Thanks!!

**Comment by ashifalinadaf** [comment]
Live demo can be implemented - gives an idea of different sizing 
Hidden code is also makes sense 
Option 1 looks good

**Comment by vavalos5** [comment]
Looking for feedback on the following:


**Visual Design**

- Code blocks- new approach on hiding code. We can fine tune since visual I've mocked up requires a bit more fixing. [See here.](https://www.figma.com/design/bMVkdgHkimCENGHiKPGcYH/Maps?node-id=1891-42204&t=RVNI60xCwmBJsyAc-1)
- T-shirt sizing + resizing button - is it clear on what these two do? Thoughts on it + discoverability
- Live demo - is it apparent what you can do here?
- Which layout do you preference: Option 1 or 2? Why?

**Guidance/Examples**

- Do we want to show a generic option for label button group like within Grommet? We don’t have any use cases from the research conducted where we may have it.
- Do we want to include text editor in this? We have the explorations [here](https://www.figma.com/design/evH1LQewFPc8Y2fteywMxM/HPE-Text-Area-Component?m=auto&node-id=3095-13649&t=Hpax9YdtPYeXqPm4-1) but we haven’t implemented it onto the site. Also we only have the need of one button at the moment
- A question for the devs would be if it would be too much for them to create[ a container with configurable options for each component?](https://www.figma.com/design/bMVkdgHkimCENGHiKPGcYH/Maps?node-id=1866-37552&t=RVNI60xCwmBJsyAc-1)

**Comment by vavalos5** [comment]
PR ready for review @taysea

**Comment by SeamusLeonardHPE** [comment]
@vavalos5 
2 resources that might be useful - We have combined the functionality of these 2 salesforce components into 1 

https://www.lightningdesignsystem.com/components/radio-button-group/
https://www.lightningdesignsystem.com/components/checkbox-button-group/

[I added a few examples and notes here](https://www.figma.com/design/pqy731ig8afLGLZUwfqqUb/%233882---Toggle-Group-Guidance---Figma?node-id=10-2208&t=81dUsETjN0TUrZat-4)

**Comment by vavalos5** [comment]
@SeamusLeonardHPE Thanks for creating these examples.

It would be nice to get some clarity from @halocline and or @SOjaHPE on whether we want to implement more generic examples into ToggleGroup, or if we'd like to only include those that are real use cases within our products?

For this ticket, are we ok with what we already have implemented in the PR or do we want add other generic use cases?

**Comment by SOjaHPE** [comment]
@vavalos5 let's keep the guidance for this component more generic, the dataCollection common toolbar view toggle is just that, an instance of a single select use case from GLP. But overall it should be easy to describe the application of this in its two common types - single or multi-select.

This is in alignment with the original ticket description scope which asked for: "**_Types (this should capture that it can be single or multiple selection_**)" - If you view our grommet [storybook example for ToggleGroup](https://storybook.grommet.io/?path=/story/controls-togglegroup-multiple--multiple&globals=theme:hpe) it has examples of both types: single and multi-select use cases. ToggleGroup is an common component that is included in every rich text editors to support multi-select use cases. 

@SeamusLeonardHPE provided similar feedback in this [figma link](https://www.figma.com/design/pqy731ig8afLGLZUwfqqUb/%233882---Toggle-Group-Guidance---Figma?node-id=10-2208&t=5zCJiRIxsO9eSJ5I-4)

Keep it simple, use the storybook examples for multiple selection and the simple 'single' selection from our view toggle.

**Comment by vavalos5** [comment]
I've updated the PR to have a more generic approach. @taysea @SeamusLeonardHPE. Ready for review.

**Comment by SOjaHPE** [comment]
@taysea & @SeamusLeonardHPE  - I added some feedback directly to [https://github.com/grommet/hpe-design-system/pull/3883](https://github.com/grommet/hpe-design-system/pull/3883) in a comment. I only tagged @vavalos5 , forget to add you as well.

**Comment by vavalos5** [comment]
@taysea, @britt6612 and I connected on how to lay the content out on the PR. PR reflects changes.

Looking to get feedback from team on generic examples again only because we want to understand whether or not we're in agreement of showing examples we're not sure we want to promote. Will be bringing up during D&D.
