### ISSUE TITLE
AVATAR - Auto-layout fix

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3892]
### **Who is requesting this fix?**

Requested by @luketa8. This is a known [Figma issue](https://forum.figma.com/t/instance-change-size-from-nested-component-swap/39773) that is commonly worked around using auto-layout

###  **Where is this fix needed?**

Each one of the individual [Avatar component variants](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=3027-58201) needs to be an auto-layout for Figma to update its real dimensions upon insertion in a host component, for example the Card on the [Slot Demo Library](https://www.figma.com/design/MSQ0GGdGUCzSbzueqmPWx8/Slot-Demo-Library?node-id=6735-1355&t=ETnRCemtJm47BB87-0).

### **Expected Behavior**

- The host component should grow or shrink accordingly upon variant change. 

### **Current Behavior**

![image](https://github.com/grommet/hpe-design-system/assets/5853565/bbacb1f5-8d9d-4a1b-a0d6-ec932015f39f)

__________________________________________________________
### Reviewers:

- @SeamusLeonardHPE 
- @KennyAtHPE 

### List possible consequences, involved assets and components:
1. Removal of unused Avatar dark theme variants.

### Checklist (add your progress in the comments)

- [x] Align with stakeholders
- [x] Gather historical information
- [x] Build proposal
- [x] Gather feedback
- [x] Create [Figma Branch](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/fA8njWjMcx3KFsAqqeckOC/HPE-Design-System-Components?m=auto)
- [x] Ask for review
- [ ] Publish
- [ ] Communicate

**Comment by vavalos5** [comment]
@luketa8 I see this ticket is in review, can you specify what you're looking for? Are you in need of a review from @SeamusLeonardHPE ? If so, can you tag him here please. Thanks!

**Comment by luketa8** [comment]
Avatar refactor branch reviewed and ready to merge -> [Figma](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/fA8njWjMcx3KFsAqqeckOC/HPE-Design-System-Components?t=0t9fwX1AxSZdIglB-0)

**Comment by SeamusLeonardHPE** [comment]
Affected items 53

![Image](https://github.com/grommet/hpe-design-system/assets/135040188/a3db11bc-f76e-489a-adfb-c5af62bf9f22)

Avatar - All 39 variants
Page header - All 10 Variants (hidden avatar - will be removed in upcoming refactor)
GlobalHeader - 8 Variants (HPE product & HPE Special use variants - avatar in identifier menu)

Updated instance is custom table cells also.

![Image](https://github.com/grommet/hpe-design-system/assets/135040188/a10b328d-f971-4ca1-97c0-e94706c2575f)



### Impact
Changes that require publishing


![Image](https://github.com/grommet/hpe-design-system/assets/135040188/de1c5f8f-8a9c-4f1f-9800-b1c363618eb5)
