### ISSUE TITLE
Selector - Align Figma component to code template

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3893]
Follow-on to [#3867](https://github.com/grommet/hpe-design-system/issues/3867)

Once the coded Selector template has been finalized, align the Figma component build with the coded prototype. The things that might need re-alignment:
- available props and their names
- general architecture (what regions are configurable with props vs what are slots)

Deliverables:
- [ ] Figma branch with Selector component updated to align with code
- [ ] Approved by Seamus, Brittany, and Taylor

**Comment by luketa8** [comment]
Adding re-alignment working file
[ Link to Figma file](https://www.figma.com/design/JdxGK83bJAdoAyiEFIABeY/Selector-rebuild?node-id=0-1&t=qg7uu9KAzANzM6xl-0)

**Comment by luketa8** [comment]
Selector component updated in [Figma file](https://www.figma.com/design/JdxGK83bJAdoAyiEFIABeY/%233893---Selector-re-align-to-code?node-id=97-162&t=aPk8FL4ZPG6yjeJM-1)

**Comment by vavalos5** [comment]
@luketa8 Are you looking for feedback/approval on the Selector component in Figma?

**Comment by luketa8** [comment]
- Selector component aligned to code and ready for review in [Figma file](https://www.figma.com/design/JdxGK83bJAdoAyiEFIABeY/%233893---Selector-re-align-to-code?node-id=451-1736)

- @britt6612 will be updating the [Pull Request](https://github.com/grommet/hpe-design-system/pull/3865/)

**Comment by SeamusLeonardHPE** [comment]
@luketa8 Added comments and examples on that files as there was some issues with responive text and layer structure.

Quick fixes but otherwise looks good interms of build & alignment - 
We we can swam on getting the modified version into a branch asap 
One question -connect with @oliverHPE on[ your suggested  icon sizing ](https://www.figma.com/design/JdxGK83bJAdoAyiEFIABeY?node-id=451-1824#868207869)

**Comment by luketa8** [comment]
- Connected with @taysea and @britt6612 about icon size vs height code update. 
- Added finished component to [Figma branch](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/OluDhdAb61htjFTQHhpR43/HPE-Design-System-Components?m=auto) and added @SeamusLeonardHPE as reviewer

**Comment by SeamusLeonardHPE** [comment]
Figma work complete - branch will be mergrged as soon as documentation has been published & grommet component published.
