### ISSUE TITLE
SELECTOR - Draft documentation in MDX

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3894]
The scope of this ticket is to create an MVP draft of the "Selector" content in MDX.

Guidance sections to be drafted:

- What and why (a concise message for what the component is and why it exists).
- Use case examples
   - Right now we have "Onboarding/support" and "Quick filtering". Please write a concise description of why "Selector" should be used in each of these). 
   - Any other common use cases we're missing?
- Anatomy
   - Follow [table format](https://design-system.hpe.design/components/layer?q=layer#anatomy). Coded diagram will be separate scope.
- Types (this should capture that it can be single or multiple selection)
- Accessibility
   - Keyboard behavior (tab to group, tab within group, press space/enter to select or unselect)

Deliverable: 
- [x] Draft MVP written guidance for "Selector" in the MDX of this [PR](https://github.com/grommet/hpe-design-system/pull/3865)

**Comment by vavalos5** [comment]
[Figma file w/ above asks](https://www.figma.com/design/FfdDpYT7macdnOCusPx5kc/%233894---Selector-documentation?node-id=30-279&t=1BI9yBnfcjSjlngD-1). Writing in Figma before putting it in MDXw/ Lucas. Scrappy, but would like your feedback on it @luketa8 @julauxen @britt6612

**Comment by vavalos5** [comment]
Brittany and I transferred contented from [Figma file](https://www.figma.com/design/FfdDpYT7macdnOCusPx5kc/%233894---Selector-documentation?node-id=30-279&t=TuM3rvulCSybJZz6-1) into MDX in the [PR above](https://deploy-preview-3865--keen-mayer-a86c8b.netlify.app/templates/selector). Ready for review @taysea @SeamusLeonardHPE @luketa8 . Including Julia for content/layout.

**Comment by vavalos5** [comment]
Received feedback from Julia & Brittany and I implemented feedback.

In regards to the types section, we'll have to wait on approval on Selector styling as there are 2 select indicator styling: radio button for single select and checkbox for multi-select - these each have different functionalities that we'd like to explicitly show the difference between each variant. Since @luketa8 is sharing out tomorrow, we'll await on approval before implementing this into "types" section in guidance.

**Comment by vavalos5** [comment]
Awaiting review from @taysea

**Comment by SeamusLeonardHPE** [comment]
@vavalos5 that PR looks good to me if the "kitchen sink" content was removed

**Comment by taysea** [comment]
<img width="1204" alt="Screen Shot 2024-07-10 at 4 29 39 PM" src="https://github.com/grommet/hpe-design-system/assets/12522275/7f4ffc4f-d5fb-47a6-81da-8c524cd1188a">

@britt6612 The letters 3a, b, c don't align to the table descriptions. Can you update that and remove "Kitchen sink"?

Then I'm good with the PR!

**Comment by britt6612** [comment]
> <img alt="Screen Shot 2024-07-10 at 4 29 39 PM" width="1204" src="https://private-user-images.githubusercontent.com/12522275/347445897-7f4ffc4f-d5fb-47a6-81da-8c524cd1188a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjQxMDEsIm5iZiI6MTcyMDYyMzgwMSwicGF0aCI6Ii8xMjUyMjI3NS8zNDc0NDU4OTctN2Y0ZmZjNGYtZDVmYi00N2E2LTgxZGEtOGM1MjRjZDExODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE1MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZTBjYTY4MjY0ZWQyMzFiODYyYjQ0NDU5YzVlZjBkNDZjYWQ2MWQ4YzdlMTE2OGIzMmYxZDZiNzY0NzFlMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-sXqOU_GvVpuIPAX-J7t12KZRDa60j0lhVRiiCrcObs">
> @britt6612 The letters 3a, b, c don't align to the table descriptions. Can you update that and remove "Kitchen sink"?
> 
> Then I'm good with the PR!

Yes thank you forgot I changed order! sounds good!

**Comment by vavalos5** [comment]
@britt6612 @luketa8 I have a question about the filters being applied in the layer. If the selector has successful filtered but in the layer I select "failed" as well, it's being reflected on the table, but the selector is still showing that i'm only viewing "successful" items. Does this experience make sense? By default I can see both, but once filtering, should I be able to see both if it's being filtered by the selector? See screenshot below.

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/21042a00-5797-43ef-b7a9-aecce3daf3ad)

**Comment by SeamusLeonardHPE** [comment]
@vavalos5 @britt6612 
In relation to the behaviour you uncovered on the page Vicky.

When clicked the quick filter/selector choices are being applied, and reflecting in the state of the filters in the side drawer form.
However any filters applied (or modified) via the side drawer form is not reflected in the state of the quick filter/selector elements.

**Comment by vavalos5** [comment]
PR has been merged, closing ticket.
