### ISSUE TITLE
Decide on where "static" typography and dimension tokens live

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3908]
For headings and body copy, we want typography to be responsive to the viewport width. For components like button/inputs/etc, we don't.

- Should these "static" typography/dimension tokens live in the "primitive" collection?
  - If so, nested under "base"? or as a peer?

**Comment by oliverHPE** [comment]
@taysea Here's a summary regarding yesterdays discussion on responsive vs static typography. Let me know if you think I've captured our thoughts.

- We'll tentatively continue to use `text` tokens. (Unless @halocline has some insights into the future of responsive text in our system, as @taysea mentioned that this has been an ask. What will the impact be on our components using `text` tokens if `text` becomes responsive (we'll need to decide whether we want our component text to be responsive or not)).
- We'll use `text` tokens on components, for example `text.large.normal` - if not directly on a component, component-specific tokens will refer to them.
- Currently `text` is not responsive, so the modes for small and large screens will use the same values. 
- There wont not be a static primitive typography scale, e.g. no `static.fontSize.large`. 
- `text` tokens will refer to our standard primitive typography scale, e.g. fontSize.100 (in both modes, so it remains static)

**Comment by taysea** [comment]
I am good with this particularly because we'll have `component.medium.fontSize` , etc. and the component specific tokens.

It is easy to add `static` in the future if we need and won't have an effect on consumer who will be consuming the component specific tokens/"component t-shirt size" tokens in cases where we don't have component specific.
