### ISSUE TITLE
Establish usage of each semantic colour token - 1st pass

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3909]
Semantic color tokens are chosen and named with usage in mind. While the name captures the intended use-case for the design token, additional guidance will help consumers understand their intended application. This will be added to the guidelines on the design system website.

Usage descriptions 1st pass (feedback needed):

- [x] Text
  - [x] Write usage guidelines
  - [x] Add to token description
- [x] Icons
  - [x] Write usage guidelines
  - [x] Add to token description
- [x] Backgrounds
  - [x] Write usage guidelines
  - [x] Add to token description
- [x] Borders
  - [x] Write usage guidelines
  - [x] Add to token description
- [x] Decorative
  - [x] Write usage guidelines
  - [x] Add to token description

- [x] Request feedback

**Comment by oliverHPE** [comment]
Feedback has been given here: https://www.figma.com/board/dhLvZlAKU0SMGi12FCKJs5/Descriptions-feedback?node-id=0-1&t=KTmLkbl3NLe1qduB-1

We'll use this feedback to update our semantic token usage descriptions in coming sprint.
