### ISSUE TITLE
Establish elevation colour tokens

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3910]
Establish and elevation system that enhances theming, particularly dark themes.

- [x] Elevation scale (amount)
- [x] Elevation names

**Comment by oliverHPE** [comment]
Have presented the concept of additional elevation levels to the design system team. These new levels would live in additiona to the current levels, `background`, `background.back` and `background.front`. These additional levels names are:

`Raised` (for cards etc.)
`Floating` highest level (dropdown menus, layers, modals, Side layers)

The Figma file can be found here [here](https://www.figma.com/design/ywI9vZo15KY02nJxhKOof9/Colour-token-names?node-id=310-38835&t=fIo4YevGozXDa61L-1)

These new levels are to give us additional ways to style elevational layers using colour and make different levels more visible and easier to distinguish, especially in a dark theme.

Feedback is positive so far, and there is agreement that these additional levels would be useful. Concerns are:

- Naming - Could there be better and easier to understand alternatives
- Amount - Do we need both `front` and `raised` or could these be consolidated?

**Comment by taysea** [comment]
@oliverHPE In the spirit of “we can always add a token later, but can’t break the contract once we publish”, let’s not have “raised” right now. And for alpha, let’s stick with the term “floating”, but leep it in our shortlist though for a name to revisit before v1 publish.

If also sounds good, can you align the Figma variables accordingly and close this ticket?

**Comment by oliverHPE** [comment]
- [ ] Update alpha variables Figma file with token `color.background.floating`
