### ISSUE TITLE
Which components or groups of components share similar requirements to how height is defined/restricted/etc.

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3911]
Determine which components and assets should share similar sizing, and if or how we could tokenise this. For example, some components should look similar sized when next to each other, e.g. solid or outlined buttons. Determine if components can be grouped into ways of being sized.

**Comment by oliverHPE** [comment]
Determine which components and assets should share similar sizing methods, and if or how we could tokenise this. 

For example, icons, avatar, and spinners are basic atomic components that come in various sizes. Should sizes be standardised across these kinds of components using the same method or token set. e.g. `size.small`, `size.medium` and `size.large`

Buttons and form fields are another kind of component that should share size. How should size be standardised across these? Height can be achieved in various ways, perhaps they do or do not need to be built in the same way.

**Comment by oliverHPE** [comment]
Having explored the various sizes in our system we have more officially established sizes for icons, elements, typography and components.

The upshot is that there are official sizes, we can tokenise them, and there is a formula for nesting sizes.

 Consult the following files for the current state of sizes:

[Figma file](https://www.figma.com/design/ppSM0nDlJb07ySbglGVfQT/Sizing?node-id=245-1922&t=gVdx7KYSM2lvB7pG-1)
[Confluence documentation](https://hpe.atlassian.net/wiki/x/-wMGmQ)

Having established an official sizing chart, some components will need to be updated, however, this should steadily happen by virtue of having tokens applied with the correct values.
