### ISSUE TITLE
Populate Test "Input"/"FormField" tokens

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3913]
Add pre-alpha experimental tokens for form field styled components, e.g. Text input, date input, checkbox (form field style) etc. These tokens will be used in the Figma token test to style the text input field - issue 3920 [https://github.com/grommet/hpe-design-system/issues/3920](url)

**Comment by oliverHPE** [comment]
Test file and task related to form fields has been created and completed by users. Figma file: https://www.figma.com/design/5FrUonU5ex6NhgOvvh7P3Q/Token-Testing-(Cillian-%26-Julia)?node-id=65-12807&t=0cGJ7StUoRG6bT8d-1

Some feedback has been given and captured in the file.
