### ISSUE TITLE
Color - Semantic - Establish and populate semantic colors (alpha)

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3915]
Semantic tokens are tied to use case and are named with usage in mind.

Identify semantic tokens by looking into colour usage and confirm names for

- [x] backgrounds
- [x] borders
- [x] text
- [x] icon
- [x] Decorative
- [ ] Data visualisation

This should include light + dark modes.

Deliverable:
- [ ] Populate tokens and their values into the "Decisions" file: https://www.figma.com/design/6jIlhmjbSrRiwI3TkLLRv8/Decisions-Tokens---Alpha?node-id=0-1&t=G2dUT6b7JimI1RUl-1

**Comment by oliverHPE** [comment]
The majority of colours have been entered, with a few outstanding which have dependencies:

Disabled colours - Need to present and get feedback from team
Primary hover colour - gradient or solid? Discuss
Elevation colors, **raised** and **floating** - Need to present concept and get feedback from team
Background validation unknown - get agreement on color
DataVis - need to establish whether we're using the original 5 color system or new 7 color system

**Comment by oliverHPE** [comment]
@taysea All alpha Semantic colors are in except Datavis colours.

**Comment by taysea** [comment]
@oliverHPE Can you create a separate ticket for "datavis" colors? Feels like otherwise we can close this ticket

**Comment by oliverHPE** [comment]
@taysea Have created an issue here for data visualisation color tokens: issue [#4042](https://github.com/grommet/hpe-design-system/issues/4042)
