### ISSUE TITLE
Establish disabled colours

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3916]
As we will have disabled colour tokens, e.g. `color.text.disabled` , we need to establish disabled colours for 

- [ ] Text
- [ ] Icon
- [ ] Borders
- [ ] Backgrounds
- [x] Present to team if we should just have semantic "color.text.disabled" as opposed to component specific everything

Deliverable:
- [ ] Define and populate disabled colors in "Decisions" file: https://www.figma.com/design/5FrUonU5ex6NhgOvvh7P3Q/Token-Testing-(Cillian)?node-id=0-1&t=DHuMY8da9pEQC8Kn-1

**Comment by oliverHPE** [comment]
Have created 3 different visual approaches to disabled colours for our light theme. We'll present these approaches to the wider team for feedback. Figma file is here: https://www.figma.com/design/5NmAR91IphL4aJ6JPiW9VZ/Disabled-colours?node-id=33-7711&t=v20rnla3kR0yFMAg-1

**Comment by taysea** [comment]
@oliverHPE Based on Matt's comments, let's move forward with direction 1a. Closing this ticket, the work to populate these tokens will be covered in #3915.
