### ISSUE TITLE
Create state matrix

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3922]
There a variety of states, some can exist together, some can't.

For example,
- enabled
- disabled
- hover
- selected
- selected + hover ..

- [x] Gather visual examples
- [x] Align with team on state names and combinations
- [ ] Create list of state names we can use going forward

**Comment by oliverHPE** [comment]
![Image](https://github.com/grommet/hpe-design-system/assets/149663138/ceef3ed6-63a3-446a-a704-388fa1a344c6)

**Comment by oliverHPE** [comment]
@taysea There is ambiguity around the meaning of the pressed/active. Essentially, there are two kinds of thing we need to have names for: 

1. The first is the state of something **while** it is being pressed, a temporary state change that exists after a click/tap and ends at release. 
2. The second is the state of something that stays active or pressed (not unlike selected, or checked). 

Think it's worth having a discussion with the wider team to align on this question.

**Comment by taysea** [comment]
Based on convention from reputable design systems, we'll follow "selected" as terminology for the persistent state: https://hpe.slack.com/archives/GPPLUK6LR/p1719256167536559

**Comment by taysea** [comment]
@oliverHPE Is this an accurate representation of state matrix you're proposing? https://hpe.atlassian.net/l/cp/SY97H6j7

**Comment by oliverHPE** [comment]
@taysea Almost. We'll just need to add 'dragged' and possibly validation states, like critical (or error). So that you could get something like `error.enabled`

**Comment by taysea** [comment]
Re-opening because I have a few questions on the validation states.
