### ISSUE TITLE
Test -- Build Tag

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3929]
Task:
Build "Tag" using available tokens and following approach documented in "achieving component height"
Documentation: "achieving component height": https://hpe.atlassian.net/l/cp/U1L001h3

As there are no component-specific tokens for **Tags** yet, please build them with semantic tokens. Furthermore, see if you can build them with `component` (as opposed to component-specific) tokens, for example, `component.medium.minHeight`.

- [x] Apply available tokens to build "Tag" (**[Figma Link](https://www.figma.com/design/mJ8d7bv5I8zgfo8BTJOpUO/Approach-2?node-id=38279-9)**)
- [x] Document any places where a token was not available: https://hpe.atlassian.net/l/cp/HfwSr6hd
- [x] Document any places where a token value seemed incorrect: https://hpe.atlassian.net/l/cp/HfwSr6hd

Reviewers (check this box once reviewed and approved):
- [x] @oliverHPE 
- [x] @taysea

**Comment by taysea** [comment]
I review the build and notes. Dropped a few minor comments on the build re: which tokens were applied.

The main takeaway for me is if the `textToElement` tokens are helping or adding confusion. Creating a ticket to discuss further:

**Comment by oliverHPE** [comment]
As it stands the current build large and xlarge would use the same horizontal padding. The large Tag horizontal padding could have used a 16px or 18px padding. This goes back to our t-shirt granularity exploration #3906

**Comment by taysea** [comment]
Closing issue as done, can file any follow on work as new ticket
