### ISSUE TITLE
Test tokens by "changing back" to v3 of HPE theme

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3979]
We should be able to achieve v3 of grommet-theme-hpe with our token architecture without adding any new tokens.

Test this in a branch off of design-tokens-alpha.

To test:

Task 1:
- [x] Paste [v5 comparison](https://github.com/grommet/hpe-design-system/pull/3549) of “all component variants” set up into sandbox/grommet-app OR apply token "theme" to aries.js theme
- [x] Modify token values in design-tokens/tokens to align with grommet-theme-hpe v3 values
    1. Don’t add any new tokens
- [x] Run yarn build in design-tokens
- [x] Compare the published grommet-theme-hpe v3 with the tokens version
- [x] Document any differences

Task 2:
- [x] Use sandbox/grommet-app "Acme Next" from workspace dropdown.
- [x] Compare what token theme of these dashboard + sustainability insights pages looks like compared to grommet-theme-hpe v3 published version.

**Deliverables:**
- [x] Documentation of differences/gaps: https://www.figma.com/board/oaDRdh9Zu2OlY7IQ8tz49N/v3-Tokens---%3E-grommet-theme-hpe?node-id=1-3&t=CusjQYcgz2I0fUPU-4
- [x] Token-based theme file: https://github.com/grommet/hpe-design-system/pull/4024/files#diff-fbf1e45d4f4ddfa8c1ea72a7109f8a3e804c33b12a6a27c19f90d7525d6bdc61

**Comment by jcfilben** [comment]
Branch for this work can be found here:
https://github.com/grommet/hpe-design-system/pull/4024

**Comment by britt6612** [comment]
Anchor text sizes are different 
<img width="349" alt="Screen Shot 2024-07-23 at 2 00 33 PM" src="https://github.com/user-attachments/assets/5aa9f2fc-4b79-4240-9256-f3b57aa6fdcd">
Paragraph & Heading sizes are off:
<img width="653" alt="Screen Shot 2024-07-23 at 2 00 43 PM" src="https://github.com/user-attachments/assets/584b8de6-a054-4c6d-b7da-1e4a4d0616b9">
<img width="663" alt="Screen Shot 2024-07-23 at 2 00 50 PM" src="https://github.com/user-attachments/assets/dfd96c70-96bb-4aed-9fff-505858a4ce4f">
Button differences: 
<img width="447" alt="Screen Shot 2024-07-23 at 2 01 11 PM" src="https://github.com/user-attachments/assets/e207793b-52d8-4d2c-b8c1-011d52df0ccb">
<img width="455" alt="Screen Shot 2024-07-23 at 2 01 00 PM" src="https://github.com/user-attachments/assets/fc7be8bf-d428-4ae7-b9cd-1847c727f077">
Checkbox & Accordion & CheckBoxGroup
<img width="636" alt="Screen Shot 2024-07-23 at 2 01 35 PM" src="https://github.com/user-attachments/assets/dc2c2a58-21b1-4060-bb96-02b1c36eea9b">
Menu & TextInput
<img width="535" alt="Screen Shot 2024-07-23 at 2 05 12 PM" src="https://github.com/user-attachments/assets/2e5307e8-53f9-4025-8df9-ebd48360fe69">
<img width="446" alt="Screen Shot 2024-07-23 at 2 05 27 PM" src="https://github.com/user-attachments/assets/35a7f704-6efc-4158-9837-f7d6cd038e72">

**Comment by jcfilben** [comment]
Tokens theme with v3 changes:
<img width="1778" alt="Screenshot 2024-07-23 at 2 20 24 PM" src="https://github.com/user-attachments/assets/708a1283-f6c1-4622-b832-202347c00ce7">

<img width="1767" alt="Screenshot 2024-07-23 at 2 22 07 PM" src="https://github.com/user-attachments/assets/d8b2aa9e-9724-45e6-b354-f92712e24b95">

<img width="1753" alt="Screenshot 2024-07-23 at 2 22 27 PM" src="https://github.com/user-attachments/assets/9ff6a6f3-d2f1-4d1a-b59e-d6e885970d53">

**Comment by jcfilben** [comment]
Hpe v3.1.0 theme

<img width="1771" alt="Screenshot 2024-07-23 at 2 40 25 PM" src="https://github.com/user-attachments/assets/25111013-2b92-4a88-818d-7a35def0298d">

<img width="1765" alt="Screenshot 2024-07-23 at 2 41 50 PM" src="https://github.com/user-attachments/assets/2d91f129-bf4d-4bd7-94e0-4d912a560dc4">

<img width="1769" alt="Screenshot 2024-07-23 at 2 42 05 PM" src="https://github.com/user-attachments/assets/5a79101a-c092-4dbc-9607-a83cc6ca57c1">
