### ISSUE TITLE
Tokens - Map all available tokens to HPE theme

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3980]
Take all values in current token set and map to sandbox/grommet-app theme.js.

**Comment by jcfilben** [comment]
We mapped the tokens to the HPE theme and tested it in the grommet-app in hpe-design-system and in grommet storybook.

Here is the branch for this work on hpe-design-system: https://github.com/grommet/hpe-design-system/tree/design-tokens-alpha
Navigate to the sandbox/grommet-app and then run `yarn dev`.

Branch on grommet to test with storybook: https://github.com/grommet/grommet/pull/7276
Deploy preview:

Note that both of these branches are using a version of the tokens theme where we commented out tokens that were not coming through correctly. So the deploy previews might not show all the issues.

Here are the differences we noticed:
- Drop background is transparent and not rounded (See Drop/All not stretched
- Drop/Inline background color of the drop is different
- Menu/Bottom control button height is bigger, text color is darker, actions icon is different
- Tabs active tab styling is different (see Tabs/Controlled)
- TextInput icon placement is slightly different, icon is a lighter color
- DateInput placeholder text font weight is different and icon size
- FileInput border width, padding, rounding, and browse button styling is different
- RadioButton font weight (see RadioButton/simple)
- RadioButtonGroup icon size
- Error text missing icon (See Form/help and error)
- CheckBox doesn’t have focus indicator (see CheckBox/No label)
* Calendar: Focus is not on arrows, or whole calendar 
- Active primary button is the wrong color (see Button/Basic story)
- Primary button hover behavior isn’t working
- Dark/light text not working correctly (see Button/kind story)
- Button secondary border width is incorrect
- Secondary button, getting a border on plain buttons (see Button/kind story)
- Secondary button, border color isn’t changing (see Button/kind story)
- Button/Multiple story looks different
- Button/Sizes story, buttons are slightly smaller
- Toolbar button is bigger than(see Data/Complex story)
- Select placeholder text has more weight, hover and selected styling is different (see data/composed toolbar)
- Table sort icon is different
- RadioButton group hover styling is different in a formfield, the background doesn’t stretch all the way horizontally
- Form spacing is different
- Formfield label text is different
- Form error and disabled state (see Form/Field states)
- MaskedInput placeholder text weight
- Select padding, hover, selected colors different
* Notifications:  Toast title Only Icon and title no longer align 
* Meter: Current Circle story not working
* Diagram: animated not working, connections, 
* DataTable: tokens no focus (shadow box) on select all, no focus on whole table
* Clock: green color not coming thru storybook
* Tag: Needs box shadow 
* Video: no box shadow 
* Carousel: no box shadow	
* Header: no hover on button
* RangeSelector: no focus, all grey line 
* TextInput: green color, no focus color
* TextArea: no focus color
