### ISSUE TITLE
Tokens Test - Alpha test approach 1 - Map tokens in Figma to HTML native elements

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3981]
### Map tokens to HTML native elements in our Figma component library.

**Border build approach**: Please build components with borders excluded from size calculation (default setting in Figma).

For this initial task, two testers will map component-specific tokens to the following components: 

Build method

**Cillian**
- [x] Button
- [x] td (data cell)
- [x] th (header cell)
- [x] formfield
- [x] menu (item)
- [x] radiobutton

**Julia**
- [x] select (option)
- [x] checkbox
- [x] Toggle (switch)

--------------

**In this task we hope to learn:**

Usability:

- If the token names makes sense
- If they are discoverable

Required tokens:

- If we have provided the tokens required for the above task (e.g. kind and availability of token to make a specific button variant)
- If the provided tokens have the correct value

Gerneral feedback

- Anything else that the tester thinks could be improved

--------------

### Feedback

Please provide feedback on the following:

**General feedback regarding tokens**

- This might include anything related to how the component is built vs the tokens provided etc.

**For each component please say:**

- If you had all the required tokens to build the component
- The naming made sense
- Colour issues or observations
- Spacing issues or observations
- Sizing issues or observations
- Corner radius issues or observations
- Typography issues or observations
- Build issues or observations

--------------

### Not ready
- Anchor

Doesn't apply to Figma components (only styles)
- Heading
- Text
- Paragraph

**Comment by CillianHPE** [comment]
@taysea @oliverHPE 

I have coimpleted my feedback for these components.

**[See feedback here.](https://hpe.atlassian.net/wiki/spaces/~7120200aef6dd18fe543fb94524027e72fd862/pages/2583631528/Cillian)**
