### ISSUE TITLE
Test tokens by applying any exploratory designs from Chris

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3982]
We should be able to achieve a “future brand refresh” with our token architecture without adding any new tokens.

Test this using this design: https://www.figma.com/design/EtKzcSHpLwtu6RBpkMIHdb/Design-Tokens---Chris-Application?node-id=2522-24&t=8K0f4fghBjBYL4LN-1

- [x] Build one of Chris's "future" designs with the Design. Systems "variable"-ized components
- [x] Modify token values to achieve the desired designs
    1. Don’t add any new tokens
- [x] Document anywhere that tokens were missing, anything that could not be achieved, and anywhere that required manual re-styling

**Comment by joellegregory** [comment]
https://www.figma.com/design/EtKzcSHpLwtu6RBpkMIHdb/Design-Tokens---Chris-Application?node-id=2522-24&t=8K0f4fghBjBYL4LN-1
