### ISSUE TITLE
Test - Build Figma page layout using variables

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3983]
- Using the semantic tokens and HPE Design System components, build the pages found on this file under 'LAYOUT': https://www.figma.com/design/mgOVt0Udt2ya03ETPh4CQO/%F0%9F%9F%A0-HPE-Design-System-Components-(Duplicate-Test)?m=auto&t=YSuyi62Kt86A0MZV-1

Create a list of anything that required a hard coded value rather than a token, anything that could not be achieved:  https://hpe.atlassian.net/wiki/x/hRoAmg

NOTE: Using the "variable" versions of Design System components will be blocked until #3981 is completed. However, this work can be started by using "semantic" variables to build the page layout (spacing, colors, borderRadius, cards, typography, etc.) and the individual components like "button" can be replaced later.

[Link to Figma](https://www.figma.com/design/mgOVt0Udt2ya03ETPh4CQO/%F0%9F%9F%A0-HPE-Design-System-Components-(Duplicate-Test)?node-id=38195-139)

Link to **[Confleunce](https://hpe.atlassian.net/wiki/spaces/~7120200aef6dd18fe543fb94524027e72fd862/pages/2611216693/Page+Layouts)**

Reviewers (check this box once reviewed and approved):
- [x] @oliverHPE 
- [x] @taysea

**Comment by CillianHPE** [comment]
[Rebuilding layouts here.](https://www.figma.com/design/mgOVt0Udt2ya03ETPh4CQO/%F0%9F%9F%A0-HPE-Design-System-Components-(Duplicate-Test)?node-id=38195-139)

Added comments to **[Confleunce](https://hpe.atlassian.net/wiki/spaces/~7120200aef6dd18fe543fb94524027e72fd862/pages/2611216693/Page+Layouts)**

**Comment by oliverHPE** [comment]
In the test, couldn't find tokens for page padding. We Should provide guidance on what tokens to use here, or consider adding page padding tokens.

**Comment by taysea** [comment]
Closing issue as done, can file any follow on work as new ticket
