### ISSUE TITLE
Populate alpha 'Button' tokens

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#3987]
Populate tokens for buttons:

**Types**

- [x] Default
- [x] Primary
- [x] Secondary
- [x] Toolbar

**Sizes**

- [x] Small
- [x] Medium
- [x] Large
- [x] Xlarge

**Comment by taysea** [comment]
@oliverHPE I believe these have all been populated except the "selected" state is just one level -- it doesn't reflect the complex "selected.enabled", "selected.hover", ...

**Comment by oliverHPE** [comment]
@taysea correct me if I'm wrong, but buttons don't have that styling or behaviour right now - for example, there is no `selected.hover`. It's either selected or not selected. The components that have that more complex levels are radio buttons, checkboxes and switches for example. On those we have examples like the one's you're describing - `checkbox.control.selected.enabled.background`.

**Comment by taysea** [comment]
Correct, we don't have it but wasn't sure if we should still have a consistent structure. So something like:

`selected.enabled.background` as opposed to currently we just have `selected.background`.

small beans for alpha learnings, but just a small question for consistency.

**Comment by oliverHPE** [comment]
I see. To be safe, we could go with the full name `button.primary.selected.enabled.background`. This route means:

**Comment by oliverHPE** [comment]
I see. To be safe, we could go with the full name `button.primary.selected.enabled.background`. This route means we could:

1. Introduce more substates easily, e.g. a selected.hover - `button.primary.selected.hover.background`
2. It's consistent with other components with a selected state

The cons being

1. It's longer
2. Is it necessary on components that we can assume will never have these complex state scenarios? For example, will a selected tab have a selected.hover in the future?

**Comment by taysea** [comment]
Good to have these pros/cons documented. Let's go with the "full name" for alpha. And for now, just have "selected.enabled" for button.

**Comment by oliverHPE** [comment]
@taysea ran into an issue when choosing colors for selected button backgrounds, which is currently a semi-transparent grey (what's called contrast at the moment). Currently our alpha semantic selected `color.background.selected` points to the brand color, however, our we need something at the semantic level that is called selected, and points to the grey, so it can be consumed by button tokens. Currently pointing it to hover, because this works color wise, but we'll need to come up with a new semantic token name for this kind of selected thing.

**Comment by oliverHPE** [comment]
Have put something into the [backlog](https://github.com/orgs/grommet/projects/34/views/1?pane=issue&itemId=70581888) re the above issue.

**Comment by oliverHPE** [comment]
@taysea have gone through and updated button tokens. Would you please give it a once over.
