### ISSUE TITLE
Populate semantic typography tokens

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4003]
This should include "headings" and "text" (which applies to Text and Paragraph).

- [x] Headings
- [x] Text
- [x] Paragraph

**Comment by oliverHPE** [comment]
@taysea It would be great for us to settle on which tokens to use on our components. We have component family typography tokens for `formField`, but we need to converge on our approach for other components. For example, does a checkbox label use the semantic composite style `text.medium.normal` or will it use `checkbox.label.fontSize`, `checkbox.label.lineHeight` and `checkbox.label.fontWeight` either individually or combined in a composite style `checkbox.label` (or whatever name we go for). Whichever approach we take, both design and dev should use the same tokens.

**Comment by oliverHPE** [comment]
@taysea Having spoken to some other designers, they favoured having component specific tokens for typography. So let's go with that for the alpha test. The last thing to settle on is whether to have composite tokens for component-specific typography tokens.

**Comment by taysea** [comment]
Agree with the component specific. As we discussed yesterday, for alpha testing can we mirror what we have set up in formfield for tokens and text styles?

For example, in variables we will have:
- `checkbox.label.fontSize`
- `checkbox.label.lineHeight`
- `checkbox.label.fontWeight`

Then in Figma text styles we'll have:
"checkbox/label"

and that will use the above 3 tokens?

**Comment by oliverHPE** [comment]
Perfect. Thanks @taysea
