### ISSUE TITLE
Layer - Align component with current guidance and update slots

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4006]
**Who is requesting this fix?** 
DS team

**Where is this fix needed?**
All components that contain slots

**Expected Behaviour**

Standardize language everywhere slot, slot variant & instance swap is used in the component set.
All Slots live in variants named
Content = Default (configurable/simple variant that loads first)
Content = Slot  

All instance swaps are named: [Region] Swap.

Apply updated slot to (or create follow-up tickets)
Layer - Center
Layer - Sidedrawer
Layer - Fullscreen

**Current Behaviour**
Currently no single approach
__________________________________________________________
**Reviewers:**

- [x] Seamus

- [x] Lucas

**List possible consequences, involved assets and components:**
1.

**Checklist** (add your progress in the comments)

- [x] ~~Align with stakeholders~~ Talked to Seamus and we are updating based on previous explorations. Low risk to change in the future, lets get this out ASAP and iterate based on feedback

- [x] Gather historical information

- [x] Build proposal

- [x] Gather feedback

- [x] Create [branch](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/PKChAVJo4KnqHJ3CCGTSti/HPE-Design-System-Components?m=auto&t=84D9MhMVBcbF6VhV-1)
      - Changes:
      - Switched variant “Content” to “Layer type.” Contains the values “Actionable” and “Informational”
      - Changed variant “Example” to “Content”
      - Removed slot variant for footer
      - Swapped slots to new slot component

- [x] Ask for review

- [x] Publish

- [x] Communicate

**Comment by KennyAtHPE** [comment]
List of changes (to be reorganized):
- Removed dark mode
- Switched “Content” to “Layer type.” Contains the values “Actionable” and “Informtational”
- Changed “Example” to “Content”
- Removed slot variant for footer
- Swapped slots to new slot component
- Changed height of Side Drawer layer to 1020px for all variants
- Nested the .Footer and .Slot variants
- Removed drop shadow of Fullscreen layer
- Removed close icon inside actionable center layers and removed close icon boolean prop in the comp.

**Comment by KennyAtHPE** [comment]
Next steps:
- Create a ticket for finalizing the internal guide and sharing/educating designers
- Updating external guide as needed
