### ISSUE TITLE
Build "marketing" style page layout in Figma

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4013]
Use the variables to build this Figma screen: https://www.figma.com/design/dKQiJx8UfEbk6cFTavhliE/Token-Testing---Marketing?node-id=1-951&t=VQqnj0EwVFOmQBwX-1

Deliverables:
- [x] Screens with semantic variables applied for color, typography, spacing, radius
- [x] Comments alongside any instances where tokens were not available

**Comment by joellegregory** [comment]
https://www.figma.com/design/dKQiJx8UfEbk6cFTavhliE/Token-Testing---Marketing?node-id=47-400&t=FOn8LfmFVhI6LbDC-1
