### ISSUE TITLE
Analyse tokens test 1 feedback

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4034]
Analyse feedback from token test 1: Issue [#3981](https://github.com/grommet/hpe-design-system/issues/3981)

**Comment by oliverHPE** [comment]
Temporary Figma file:

https://www.figma.com/design/1oYTgR5ZxPESOBoBtOzDfi/Feedback-1?node-id=0-1&t=eboGAPZy8z0f3jWc-1

**Comment by oliverHPE** [comment]
Have created an issue here for data visualisation color tokens: issue [#4042 ](https://github.com/grommet/hpe-design-system/issues/4042)

**Comment by taysea** [comment]
@oliverHPE Thanks for summarizing,  can you file these notes as "items" in the backlog?

**Comment by oliverHPE** [comment]
Further Native HTML feedback:

Buttons
* Need icon only tokens
* Figma, toolbar button changes to primary on disabled

DataCell
Revisit token name to align with code
No disabled state
Need primary ID token
Need tokens for minHeight?

HeaderCell
No tokens for:
* Sortable controls
* GapX
* Min-Height
* No typography token for “unit” text

Menu
* Token is called menGroup but the component is called menu list
* No menu item hover state
* Figma: Becauses there is background token for menuItem renders an invisible background, the focus effect will appear on the text.
* The border-width token for the border/separator is on the menu item component cannot be applied due to the way component is built.
* The border styling is built using a svg line rather then an actual border.
* This is something that should be fixed with a refactor.

formField
* Error message comes with an icon. So there should be a color and gap token. Unless we intend to make a dedicated component for error message, which would point to it’s own dedicated collection.
