### ISSUE TITLE
Color - How to handle ‘inverse’ color in light themes. For example, how do we enable white text in a light theme for text on a dark background?

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4037]
In theme modes, such as light and dark, the generic text colors are selected to pair with the theme mode's background colors. That said, there are some use cases where, for example, a section of a page might use a darker background color in light mode. In that scenario, what text color should be used and how should it be represented in token system?

This scenario is more common on marketing pages but can occur in platform as well.

Examples:
- The sidebar/global header in this are rendered in more of a 'dark' context: https://www.figma.com/design/JZMRkPCwhXmd23d0zkGPPo/Visual-exploration?node-id=2052-33520&t=Ch3EQgjB4JQ2TDd0-4
- This marketing page has a dark video behind it

![Image](https://github.com/user-attachments/assets/e059b03b-7613-435c-869b-8706827b7ff9)

Deliverables:
- [x] Audit approaches from other reputable systems (Primer, Polaris, Material, Spectrum, Pajamas, etc.)
- [x] Try "scoped" approach where a section within the frame is rendered in "dark" mode
- [x] Try "strong" background / "inverse" text approach.

https://www.figma.com/design/ywI9vZo15KY02nJxhKOof9/Colour-token-names?node-id=477-5312&t=YNRmREo9RFD7TvYk-1

**Comment by oliverHPE** [comment]
Figma file here: https://www.figma.com/design/ywI9vZo15KY02nJxhKOof9/Colour-token-names?node-id=477-5312&t=YNRmREo9RFD7TvYk-1
