### ISSUE TITLE
Test -- Build Toast

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4048]
Task:
Build "Toast notification" using available tokens.

- [x]   Apply available tokens to build "Toast notification" **[(Figma Link)](https://www.figma.com/design/mJ8d7bv5I8zgfo8BTJOpUO/Approach-2?node-id=38264-6471)**
- [x]   Document any places where a token was not available: https://hpe.atlassian.net/l/cp/Kmtmp41i
- [x]   Document any places where a token value seemed incorrect: https://hpe.atlassian.net/l/cp/Kmtmp41i

**Comment by CillianHPE** [comment]
@oliverHPE 

See Figma rebuild **[here](https://www.figma.com/design/mJ8d7bv5I8zgfo8BTJOpUO/Approach-2?node-id=38264-6471)** and commonets in Confluence **[here](https://hpe.atlassian.net/wiki/spaces/~7120200aef6dd18fe543fb94524027e72fd862/pages/2613838630/Toast)**.

**Comment by taysea** [comment]
Did an initial review and dropped a few minor comments!

**Comment by oliverHPE** [comment]
Think the main takeaway here is to clearly describe the usage for static and responsive tokens.

**Comment by taysea** [comment]
Closing issue as done, can file any follow on work as new ticket
