### ISSUE TITLE
Test -- Global Header

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4049]
Task:
Build "Global header" using available tokens.

- [x] Apply available tokens to build "Global header": https://www.figma.com/design/mgOVt0Udt2ya03ETPh4CQO/branch/mJ8d7bv5I8zgfo8BTJOpUO/%F0%9F%9F%A0-HPE-Design-System-Components-(Duplicate-Test)?m=auto&node-id=38279-10&t=8xWAXmi9JNwzHOmP-1
- [x] Document any places where a token was not available: https://hpe.atlassian.net/wiki/spaces/~7120200aef6dd18fe543fb94524027e72fd862/pages/2616164992/Global+Header
- [x] Document any places where a token value seemed incorrect: https://hpe.atlassian.net/wiki/spaces/~7120200aef6dd18fe543fb94524027e72fd862/pages/2616164992/Global+Header

Reviewers (check this box once reviewed and approved):
- [x] @oliverHPE 
- [x] @taysea

**Comment by julauxen** [comment]
Issue done.
[Feedback](https://hpe.atlassian.net/wiki/x/gILvmw)
[Build](https://www.figma.com/design/mgOVt0Udt2ya03ETPh4CQO/branch/mJ8d7bv5I8zgfo8BTJOpUO/%F0%9F%9F%A0-HPE-Design-System-Components-(Duplicate-Test)?m=auto&node-id=38279-10&t=8xWAXmi9JNwzHOmP-1)

**Comment by taysea** [comment]
Did an initial review of the build and feedback and dropped a few minor comments!

**Comment by oliverHPE** [comment]
As mentioned in the comments, the Figma build could use modes for responsive padding, rather than using variants with different padding values.

**Comment by taysea** [comment]
Closing issue as done, can file any follow on work as new ticket
