### ISSUE TITLE
Popover component - Draft component & request Dev build 

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4050]
**Who is requesting this?** (add contact details here)
Platform & Internal

**What is the problem this ask is trying to solve?**
Follow on from https://github.com/grommet/hpe-design-system/issues/3780

**Add links that contain a proposal, if it exists.**
Followup work from Julias popover exploration.
Using new slot method and building "default" 

[Working file
](https://www.figma.com/design/mLtxaB1Yga3T9cXiZQSp8I/Popover---%233844-%2B-%234050?node-id=2005-207&t=YNJ7A0odNMNMz4XV-1)
[Drafted Guidance](https://www.figma.com/design/mLtxaB1Yga3T9cXiZQSp8I/Popover---%233844-%2B-%234050?node-id=2005-23605&t=YNJ7A0odNMNMz4XV-1)
_______________________________________________________________
**What is the issue about:**
Drafting Popover component and handing off to devs.

**Reviewers:**

- [x] Seamus

- [x] Julia

**Define MVP for this ticket** (format, amount of detail, where it should live, etc):
- [x] Component drafted w/ Slot and Default variants
- [x] Styling choices + Design Rationale  

**Follow up tickets:** (if necessary)
1. Refine based on Dev feedback
2. Publish and announce

**Checklist** (add your progress in the comments)

- [x] Define the Problem

- [x] Ideate (present at least two option with pros and cons)

- [x] Build

- [x] [Check the Component Checklist](https://hpe.atlassian.net/wiki/spaces/DS/pages/2517205174)

- [ ] Test with users

~~- [ ] Test with Bill for accessibility~~ Will be done with devs in #4087 

- [x] Ask for review

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE Work is being captured in the same [file](https://www.figma.com/design/r1YUOdncOi0Bdl8msDF7Ni/Popover---%233780?node-id=0-1&t=1OLsIxotj6TFAZ3H-1) that Julia started

**Comment by KennyAtHPE** [comment]
8/6 Update:
[WIP]

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE Closing out ticket. Next steps can be tracked in the dev ticket #4087
