### ISSUE TITLE
Determine which background colors need an `on[Color]` text color

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4061]
For text colors, we have `text-default`, `text-weak`, and `text-strong`. While using these colors on most background colors meets contrast requirements, there are certain backgrounds where it does now.

Deliverables:
- [x] List which background colors we're saying that our generic text colors can be used on (aka will meet contrast requirements): https://www.figma.com/design/ywI9vZo15KY02nJxhKOof9?node-id=465-4261#921919967
- [x] List which background color will need specific text colors. For example, `background.primary`, `text.onPrimary`: https://www.figma.com/design/ywI9vZo15KY02nJxhKOof9?node-id=465-4261#921919967
- [x] Add docs to confluence: https://hpe.atlassian.net/wiki/x/IwYdo
- [x] Populate the `on[Color]` colors

**Comment by oliverHPE** [comment]
Figma link here: https://www.figma.com/design/ywI9vZo15KY02nJxhKOof9/Colour-token-names?node-id=477-5312&t=YNRmREo9RFD7TvYk-1

**Comment by oliverHPE** [comment]
For alpha we'll have tokens for the following on-colors:

`color.text.onPrimary`
`color.text.onSelectedStrong`
`color.text.onSelectedWeak`
`color.text.onStatus`

`color.icon.onPrimary`
`color.icon.onSelectedStrong`
`color.icon.onSelectedWeak`

These are for colours that are use-case specific, and what we're calling flexible colours, where the tone of the colour, say primary, is unpredictable in the long-term.

For a summary of our dicovery and findings, please consult the confluence page: https://hpe.atlassian.net/wiki/x/IwYdo

Note that there are token concepts we will want to revisit prior to v1 release. Please find those here: https://hpe.atlassian.net/wiki/x/hwAYmQ

Still to be done:
Exact naming of on-colours, e.g. `color.text.onSelectedStrong` or `color.text.onSelected.strong`
Refinement of `onStatus` colors
Refinement of emphasised or strong colors to be decided in future issues.

**Comment by taysea** [comment]
Thank you! Closing this ticket
