### ISSUE TITLE
The 'user' icon in the Figma asset icon library is not the HPE Grommet icon

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#4078]
**Describe the bug**
In the Figma assets for HPE icon library, the provided 'user' icon is not aligned to the HPE Grommet theme icon for user. To be specific, the Figma icon does not have arm lines, while the Grommet icon includes arm lines.

**To Reproduce**
See the Figma asset: https://www.figma.com/design/G99KGffGLFKICy8xRs51lW/HPE-Icons?m=auto&node-id=24172-8&t=laRXC8d3x3co0Slq-1
Versus the Grommet icon: https://icons.grommet.io/?theme=hpe&s=user

**Expected behavior**
The Figma asset would be the same as the Grommet icon
https://icons.grommet.io/?theme=hpe&s=user

**Screenshots**
![image](https://github.com/user-attachments/assets/fdf72d49-dfec-41be-bcac-9a8c74fbcb5e)
![image](https://github.com/user-attachments/assets/91a80579-3fcd-4bb5-9ac6-b2b96cab2221)

**Additional context**

**Comment by julauxen** [comment]
Changes made and branch was sent to @SeamusLeonardHPE for review.
