### ISSUE TITLE
Tokens - `--hpe-button-small-default-font-weight` should be 600 instead of 700

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#4097]
The font-weight for default buttons should be 600 but in tokens it is set to 700

https://storybook.grommet.io/?path=/story/controls-button-sizes--sizes&globals=theme:hpe

<img width="559" alt="Screenshot 2024-08-09 at 2 15 34 PM" src="https://github.com/user-attachments/assets/efd13e57-8186-4129-a24a-ea43e2fbcfdc">

<img width="278" alt="Screenshot 2024-08-09 at 2 15 57 PM" src="https://github.com/user-attachments/assets/9d0dbd63-463c-4678-9966-56547a9ff43c">

**Comment by taysea** [comment]
This has been resolved.
