### ISSUE TITLE
Add `focusIndicator.outline` token

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4102]
Should have a standardized focusIndicator.outline token that follows CSS outline syntax added to `global.default.json`.

Deliverables:
- [x] Add token following design token spec: https://tr.designtokens.org/format/#border
- [x] Adjust build steps to properly transform for ESM/CJS/CSS/Figma: https://github.com/grommet/hpe-design-system/commit/affd70cfa5e22ba6f7c9e308d3900327c554da0a

**Comment by taysea** [comment]
Added `focusIndicator.outline` to "global" collection.

@jcfilben Can you pull in the latest for CSS outputs on stable branch and confirms this works as expected?

**Comment by jcfilben** [comment]
Tested the token in the global header repo and it is working
