### ISSUE TITLE
Add secondary hover border width tokens

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4103]
On hover, the border width of secondary buttons increases. This styling is an outlier from our broader styling system, therefore the entire token system does not need to accommodate this concept for all tokens. However, we do need to decide where this token will live.

My immediate thought is:
- `button.medium.secondary.hover.borderWidth`
OR
- `button.medium.secondary.hover.boxShadow`

With box-shadow, we wouldn't need to also maintain the recalculated padding values. I feel this might be more sustainable and even in high-contrast mode people would still receive a cursor change to indicate interactivity.

Should discuss as a group.

Deliverable:
- [x] Add `button.[size].secondary.hover.boxShadow`: https://github.com/grommet/hpe-design-system/commit/b10d70691683c9ece1db21d5541a60f214e2ade7

**Comment by taysea** [comment]
@jcfilben Can you pull in latest to global header and try out this new token, let me know if it works as you expect?

**Comment by jcfilben** [comment]
Yeah I tested and it is working as expected
