### ISSUE TITLE
Establish content height/width t-shirt scale

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4110]
Follow-on to https://github.com/grommet/hpe-design-system/issues/3905

There was consensus that we need more granularity in our content width/height (`size.content`) t-shirt scale.

Deliverables:
- [x] Determine where those steps are added and their values
- [ ] Determine how steps are named (s/m approach vs shifting whole scale)
- [x] Add tokens
- [x] Document decisions: https://github.com/grommet/hpe-design-system/issues/4110#issuecomment-2334039793

**Comment by oliverHPE** [comment]
For Alph released we''' add two new sizes. These will be:

**Comment by MikeKingdom** [comment]
I think it's impractical to rename any existing sizes. It's hard enough to get people to upgrade and that would be a huge barrier and difficult to assess/fix in a large application.

**Comment by taysea** [comment]
Closing, follow on work (if any) will be handled in: https://github.com/grommet/hpe-design-system/issues/4170
