### ISSUE TITLE
September Grommet Release 2024

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#4112]
Issues to be resolved first:

QA:
- [x] Ensure that there is a test for every bug fix and enhancement

Storybook:
 - [x] Chrome (hpe theme) Jessica
 - [x] FireFox (grommet theme) Jessica
 - [x] Safari (grommet theme) Brittany

Grommet site:
no action needed

Grommet Designer: 
no action needed

Release Process:
-  [x] Release notes - Jessica
-  [x] Contributors - Jessica

Final steps:
- [x]  Update changelog
- [x]  Announce in slack (#announcements in Grommet, #ccs-ui, and #hpe-design-system)
- [x]  Upload new release in code insight tool, run a scan, generate SBOM
- [x]  Load SBOM into VTN
- [x] Create ticket for next month's release

**Comment by britt6612** [comment]
new ticket for next month made here
https://github.com/grommet/hpe-design-system/issues/4172

**Comment by jcfilben** [comment]
Closing, Grommet v2.40.1 has been released https://github.com/grommet/grommet/releases/tag/v2.40.1
