### ISSUE TITLE
Determine if `component.paddingX` tokens could be added

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4115]
`paddingX` is the only "component" style we don't have captured in our generic component tokens.

Deliverables:
- [x] Proposal for what tokens would be called and how it would accommodate components of varying shapes (standard, pill, etc.)
- [x] Populate tokens according to decision

**Comment by oliverHPE** [comment]
We'll proceed with the idea of component sizing tokens for the alpha release. One of the barriers to this path was the different horizontal padding we use on components, that are not all alike - even within a certain size. For example, one medium size component might have 12px horizontal padding, while another might have 18px. We can account for these dissimilar padding tokens by allwoing for different padding tokens within a particular size. As such, each component size will have 3 different horizontal padding widths available.

**Comment by oliverHPE** [comment]
We'll proceed with the idea of component sizing tokens for the alpha release. One of the barriers to this path was the different, and unlike, horizontal padding used across components of the same size. For example, 12px horizontal padding on one medium size component, with 18px horizontal padding on another medium component. That said, we can account for dissimilar horizontal padding tokens by having multiple options available within each component size group. As such, each component size will have 3 different horizontal padding widths available. These tokens will be named according to the property and width they afford.

paddingX.narrow
paddingX.standard
paddingX.wide

The full token would look like:

`component.medium.paddingX.narrow`

There’s general a rule to how these tokens are calculated. 

Narrow: has a 1 : 1 ratio with the vertical padding. E.g. paddingY = 6px and paddingX.narrow = 6px
Standard: has a 1 : 2 ratio with the vertical padding. E.g. paddingY = 6px and paddingX.narrow = 12px
Wide: has a 1 : 3 ratio with the vertical padding. E.g. paddingY = 6px and paddingX.narrow = 18px
