### ISSUE TITLE
Next steps  for upload/progress template

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4120]
Align with the team if we need to address follow on steps for the upload/progress bar 

- [x] Importing the current work into the template file (confirm is it ok to add to template library as an .unpublished component ahead of releasing guidance since code already exists)
- [x] Determine if guidance if the "progress bar" gets a standalone page as a template as a data viz organism (that pattern can be used elsewhere - eg processing files - making a backup - performing maintenance task - uploading a file)
- [x] Determine if we adding the uploading  created as a component variant as an extension of the file input
- [x] The file input component already has a guidance page, how do our decisions & enhancments impact his page
https://design-system.hpe.design/components/fileinput

**Comment by SeamusLeonardHPE** [comment]
Added branch and moved over the unpublished components:

https://www.figma.com/design/fupkQ4sOefx3qUVoV6WfJi/branch/gVHxtGSH8YXBHI7ROTOzKG/Template-Library?m=auto&node-id=5218-2063&t=V0RwmyNObWO2bXvc-1

**Comment by vavalos5** [comment]
I think progress bar should have its own separate page that we link to the FileInput component page. It is not for DataViz 
as progress indicators, or commonly known as spinners, express an unspecified wait time or displays the length of a process. 

There is some [previous research](https://www.figma.com/design/feIeYk1zX36y9E7e7rprc2/HPE-Spinner-Component?m=auto&node-id=1-18&t=Y9FSqlUUfCyYLM3X-1) me and a few other folks on the team have gathered in the past on loading indicators.

I've also seen [Julia has done some research on loading indicators](https://www.figma.com/design/UphG4MqF2bhPYAyMC6nGt3/Loading-Indicators?node-id=3-57&t=lIMLWa7GgdM04cYP-1) that we can utilize in the near future.

FileInput created for Ethan should be seen as a state of the current FileInput component and not a separate organism. It could be a type such as FileInput with Progress bar or as Mike mentioned to me: not a flavor for a component with item renderers. 

As for the last checkbox, initially I was thinking we could add this new state to our current page as a win, however, considering we're looking to improve our guidance, I think we should dedicate the time to make the enhancements using the new template we've been using. That guidance work will be implemented in #4134.

**Comment by julauxen** [comment]
Hey @vavalos5 I am always for implementing the template, however I am unsure about the urgency of this and the amount of extra effort it would take, so I will leave it to @SeamusLeonardHPE to make that decision.

**Comment by vavalos5** [comment]
> Added branch and moved over the unpublished components:
> 
> https://www.figma.com/design/fupkQ4sOefx3qUVoV6WfJi/branch/gVHxtGSH8YXBHI7ROTOzKG/Template-Library?m=auto&node-id=5218-2063&t=V0RwmyNObWO2bXvc-1

Thank you. I made a couple of changes yesterday and sent for a review to you and Kenny. However, given Matt mentioned we should wait until devs has the capacity to implement, we can leave as a branch and not merge.

**Comment by vavalos5** [comment]
In regards to the second checkbox: 

As I was reviewing Dell Design System's [FileInput](https://www.delldesignsystem.com/components/file-input/?tab=Design) and [Progress Bar](https://www.delldesignsystem.com/components/progress-bar/?tab=Design) guidance, it occurred to me that while we've baked these two organisms together: FileInput and Progress bar, they should be developed and documented separately. 

1. **FileInput** - This is the standard UI element that allows users to browse for and select files from their device.
2. **Progress Bar** - This component visually represent the progress of an operation, typically the upload of a file.

When these two are combined in a single UI, the FileInput remains a FileInput, but the progress bar is a separate component that enhances the user experience by providing feedback on the upload process. They work together but are distinct in terms of their roles and functions.

These should be treated as modular components that are often used together but documented separately.

So we can either:

1. restructure FileInput page to use new template and not include examples using Progress Bar
2. OR focus on Progress Bar use cases (such as a FileInput with a Progress Bar), it's anatomy, then guidance and examples of how it could be paired with Progress Bar


Thoughts @SeamusLeonardHPE @MikeKingdom ?

**Comment by MikeKingdom** [comment]
They are very separate. For FileInput we're talking about how to use it in the context of uploading a file from the FileInput. But ProgressBar is used for many other things like time consuming tasks and such.

**Comment by SeamusLeonardHPE** [comment]
@vavalos5 the progress bar should have its own guidance and definition as its an organism that can be used in multiple cases.

Here is an anatomy and definition that was created by Ashif before Ginas design was coded. There are some style differences but should be enough similarities to use as a base.

https://www.figma.com/design/MxyJM1rihzo6XgAwHKRID8/%233641-Dev-Request---Progress-Bar?node-id=26-1876&t=J3gugoydxmNfqMU9-4

If you duplicate the [guidance template](https://www.figma.com/design/JHrCWRKF7V5JfqzSsChgQy/Guidance-Template?node-id=4-1174&t=CX8NrCZg8qeVdxIq-4) and start to populate that with guidance and examples from the component we created that will be good progress.

**Comment by vavalos5** [comment]
Thanks @SeamusLeonardHPE helpful to see this.

Although similar, there are differences. I imagine there must've been a lot of time and effort put into this research, are we going to follow the example with the stacked information or are we going in this direction or the direction in the FileInput component we've put in the template? I assume the one we've implemented in FileInput as this one is a bit heavy with content on the left and the other more balanced.

**Comment by vavalos5** [comment]
As this ticket noted down a couple of next steps to consider, i'll be opening a separate ticket for guidance for Progress Bar as this is not a guidance ticket.

**Comment by vavalos5** [comment]
Decision has been made, we're taking the base of the work we've already done for Progress Bar and the work Asif has done, creating a simple template for Progress Bar in ticket #4139
