### ISSUE TITLE
FileInput - Create new FileInput with Upload Progress into Component for Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#4125]
[New FileInput Figma File](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/znqQIiMTvKAyJRXHJbM7kH/HPE-Design-System-Components?m=auto&node-id=387-1967&t=WtXKZEaknhXMW28a-1)

Create the new FileInput component into Figma for product designers to utilize. Continue work already started in link above.

**Comment by vavalos5** [comment]
@SeamusLeonardHPE Do you think we should keep this ticket if we're going to be refactoring at some point down the line?

**Comment by SeamusLeonardHPE** [comment]
@vavalos5 
Taylor said during D&D that the dev team would be working on the progress bar next sprint sprint - 

Lets confirm their goals and deliverables (is it to make into a component or just have template examples/). We should keep in step with their plans so we can have parity - ie will what we publish in figma be achievable in code. 
Steps likely  to include:

- [ ] Move the “progress” figma work from template library into the component library  (create branch)
- [ ] Create a variant of file-input upload that houses the progress bar group 
- [ ] Publish the updated file upload component
- [ ] Decide if the progress bar component should be published also (should products designers be allowed to use it outside of the file upload context)
- [ ] Create followup up issues to update file-input guidance page

**Comment by vavalos5** [comment]
Seamus, adding comments/answering questions above.

1. Confirmed from Taylor that FileInput with Upload (so keeping in template branch and not moving to a component branch) will be implemented as template examples. 
2. AND Progress Bar ( create a branch for Progress Bar in template file) will be implemented as template examples. 
3. Current Progress Bar is only shown as a template, so states are not available and being utilized from the uploader states we created. Do we want to create variants for the Progress Bar or is what we've got now enough? Product designers would turn elements off/on through layers panel.
4. Since we're not making Progress Bar into a component, it will stay as a template.
5. I'm not sure what else would be updated on FileInput page since we're adding uploader as a variant in FileInput site ([devs backlog](https://github.com/orgs/grommet/projects/22/views/1?pane=issue&itemId=81381471)) with a short description.

Let's discuss these points tomorrow.

**Comment by vavalos5** [comment]
**Creating a Variant of FileInput with Upload Progress**
As a quick and "cheap" win, we had to:

1. Create a variant of the FileInput Multiple
2. Replace the FileInput ListItem Group with the .upload-progress-group
3. Change vertical height from Fixed to Hug for list items to size properly
4. Remove Error Validation property to variant as it already has states applied to the list items w/ icons
5. Create a "N/A" Validation property to apply to "uploading" state to prevent it from switching to the regular FileInput component

Some questions that came to mind when working on the FileInput:

We should just refactor FileInput as it has some wacky things happening in it. Not for this sprint, but once we get around to it for v2 with our tokens. I've documented those issues in #4229 

Should we keep progress bar component housed in FileInput or should it be a separate component? It would also make it easier as a product designer looking for the component in Figma since we'll have it as a "template" (code component example) available on our site but currently being house in FileInput component in Figma due to it already had been built with Uploader with Progress in mind. Something to keep in mind when refactoring. (ticket to be created for this if we move in this direction).

**Comment by vavalos5** [comment]
## Option 2

Here is a screenshot of a second option: FileInput with Uploader Progress as a separate component with booleans if we decided to make it it's own component instead due to the complications in FileInput.![Image](https://github.com/user-attachments/assets/5ca18254-a0ef-4849-9791-b55eb01bdf6e)

Although devs will be adding the above as a "template example". It's code of the component - In Figma we had it as a template, but have moved in the direction of including it as a component. The component wasn't hard to do as we already had this built and made additional small changes. However, as a product designer, i'd have to use 2 separate components: FileInput and FileInput with Upload Progress.

**Pros:**
Much easier to maintain due to not having as many properties
Product Designers won't be bombarded or confused on other properties that are not relevant to the component
Already built and easy to use/can already be published
Don't need to configure so many properties as Option 1


**Cons:**
Not aligned to code
Won't be a "variant"

**Comment by vavalos5** [comment]
Shared out yesterday during D&D.

Consensus was to await on devs on direction.

Although Devs is implementing as a template on our site and Designers had done the same, for usability and easy access for product designers, we're suggesting having the FileInput with Upload Progress as a separate component for now until we refactor for v2. This component is already built out, but awaiting on devs on whether we'd be ok heading in this direction. This would be similar to how Selector is a template on the site but a component in Figma.

tagging @halocline and @taysea

**Comment by vavalos5** [comment]
I've set up a call to discuss with a few folks on Monday. Aside from the visual success criteria, here are other factors to consider as to why having the FileInput with Upload Progress as it's own separate component:

- It's already built, no extra time needed to build
- simplify product designers' workflow, enabling them to design faster when found in assets panel in Figma
- expedites usage consumption as the FileInput with Upload Progress won't be wonky when toggling properties
- No error or confusions tickets would be added to our backlog from product designers consuming it
- reduces complexity
- to be integrated in v2 as a subcomponent, reducing building time and maintainability![Image](https://github.com/user-attachments/assets/c336c0fe-3864-4b7f-bea3-e0ee1921430e)

**Comment by vavalos5** [comment]
After the call, Matt gave consensus with us moving forward with option 2 until we rebuild with a slot later on for v2 and link to the template example. We also concluded that the FileInput Uploader Progress is separate from the FileInput component within code so this direction is in par with code.

I've [transferred the component we've built into a separate Figma file](https://www.figma.com/design/VnSULUmgxKuMpy6p8iCGrV/%234125---FileInput-Upload-Progress-Component?node-id=0-1&t=UeVerOK8oiJwWyZt-1) so it is no longer a variant of the FileInput component.

[Ready for review](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/WroIB3eUxmdRTwFFX2zj0b/HPE-Design-System-Components?m=auto&node-id=38060-8&t=Iwbuao7oGRypa1I9-1) @SeamusLeonardHPE - no changes were made to component other than being transferred to a new branch with its own separate component page.

**Comment by SeamusLeonardHPE** [comment]
@vavalos5 that first link doesnt work.

When I review the second link the subcomponents are disconnected  - When you copy them from the main file you need to remove the .dot in any of the parts.

**Comment by vavalos5** [comment]
Oops yea, I didn't mean to have that as a Figma link. Please ignore.

Thanks for your help on the build. I've changed the vertical resizing from Fixed to Hug contents so the FileInput Upload Progress container resizes when more list items are added or a info message

Closing as complete. Will merge branch once devs merge.
