### ISSUE TITLE
Wizard follwoup - test with Ds team and validate

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4127]
Validate suggested changes with DS team, gain alignment.

Create non interactive prototype screen to demo redesign examples in browser context
Break page into sections so we can discuss each element independently for faster alignment and gain comporension of any debt that may arise

Separating MVP from non MVP enhancements:

### MVP ------

**Wizard anatomy**
- [ ]  Aggregate historical research/rationale
- [ ]  Define regions & common utility (eg navigation can happen in header, footer & stepper) 
- [ ] Define success criteria for section/pattern
- [ ] Propose solutions accompanied with prevailing logic

**Comment by luketa8** [comment]
**Items to test:

Footer width: Dynamic vs Static.

Prototype a Wizard template that has a fixed footer width of XL (1152px) and a dynamic width footer to A/B test.
Stickyness: Sticky header/footer.

Prototype a Wizard template that has a non-sticky header and a conditionally sticky footer (check feasibility width a dev) -> Explore a solution that maintains the footer's position when screen space allows but reverts to a non-sticky footer when space is limited. **

**Comment by SeamusLeonardHPE** [comment]
#1914 
#1915

**Comment by luketa8** [comment]
1. Divide into relevant focus areas
2. Recreate original success criteria for each focus area
3. Populate with relevant feedback, user testing and issues raised
4. Update the success criteria according to the feedback
5. Add notes / recommendations to update the Template and Guidance

**Comment by SeamusLeonardHPE** [comment]
@luketa8 can you link to the updated file here and request that @julauxen review progress.

Would like to connect on this tomorrow.

**Comment by SeamusLeonardHPE** [comment]
added followup task
https://github.com/grommet/hpe-design-system/issues/4171
