### ISSUE TITLE
Search Items go to the page and not the anchor

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#413]
### Is this issue related to the design system core library or design system website?
design-system-website

### Expected Behavior

when selecting a search item in search, i should be taken to the anchored item on the page, not the page in general
### Actual Behavior

when clicking on the search item, I am taken to the page header, not the anchored location for the search item
### Steps to Reproduce

1. From the home page, in search, type "footer" 2. click on "footer" 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by britt6612** [comment]
This is related/same to issue #320

**Comment by taysea** [comment]
Closing, this issue has been fixed.
