### ISSUE TITLE
Review submitted resumes

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4137]
Categorizing the candidates into appropriate buckets, such as those suitable for a product design position and those with UI/UX experience relevant to a design system team. 

Use our [design core competencies assessment](https://www.figma.com/board/r1GkNvHAlZ3wdqT2bucKYx/Core-Competencies-Workshop?node-id=477-1304&t=BBmgFjxB3zbwiANN-4) to lay out the baseline skills we're looking

**Comment by SeamusLeonardHPE** [comment]
Submissions to date Aug 30th

[Nishigandha Vyas \[UI_UX Designer\].pdf](https://github.com/user-attachments/files/16818734/Nishigandha.Vyas.UI_UX.Designer.pdf)
[Sachin Amalanvanan \[UI_UX Designer\].pdf](https://github.com/user-attachments/files/16818736/Sachin.Amalanvanan.UI_UX.Designer.pdf)
[Kiruba Joseph Layola \[UI_UX Designer\].pdf](https://github.com/user-attachments/files/16818735/Kiruba.Joseph.Layola.UI_UX.Designer.pdf)
[Raghvendra Singh \[UI_UX Designer\].pdf](https://github.com/user-attachments/files/16818738/Raghvendra.Singh.UI_UX.Designer.pdf)
[Ravi Peter Malekar \[UI_UX Designer\].pdf](https://github.com/user-attachments/files/16818737/Ravi.Peter.Malekar.UI_UX.Designer.pdf)

**Comment by vavalos5** [comment]
Do we had a deadline on when we'd like to find a candidate?

**Comment by SOjaHPE** [comment]
@vavalos5 for this current initial set of candidates, it would be great to get something into the inbox of Bhim & Harsha with our feedback by the time they coming into work Monday. If we see anyone that looks promising, it would be good to get their take. This way we can push back, ask for more candidates from the contracting company.

Doesn't need to be too extensive w/ this first pass - review of their portfolios & CV. Let's connect if you have time today

**Comment by jcfilben** [comment]
I think we might want to avoid posting any resumes or hiring info on Github since it has people's personal info

**Comment by vavalos5** [comment]
@SeamusLeonardHPE I deleted your list of candidate's resumés for personal info. protection. We will refer to email sent. Ty @jcfilben

**Comment by vavalos5** [comment]
Closing as this has been completed on 8/30
