### ISSUE TITLE
CARD - Update the misuses section with a selector examples

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4141]
**Who is requesting this fix?** 
@julauxen 

**Where is this fix needed?** (links and screenshots)
https://design-system.hpe.design/components/card?q=card#misuses

**Expected Behaviour** (tell us what should happen)
The misuse example should reflect the selector component.

**Current Behaviour** (show us the current behaviour)
This example is obsolete now that we have the [Selector](https://design-system.hpe.design/templates/selector). When fixing this, please involve @luketa8 since he was the designer responsible for selector.

**Comment by luketa8** [comment]
Added [Pull Request](https://github.com/grommet/hpe-design-system/pull/4204) to address this issue

**Comment by luketa8** [comment]
PR Merged. Moving to Done
