### ISSUE TITLE
INLINE NOTIFICATION - Example has tabs centered, conflicting with tabs guidance

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4164]
**Who is requesting this fix?**
@julauxen 

**Where is this fix needed?**
https://design-system.hpe.design/templates/inline-notifications?q=inline#additional-detail

**Expected Behaviour**
According to [tabs guidance](https://design-system.hpe.design/components/tabs?q=tabs#alignment), tabs should always be left align.

**Current Behaviour**
In this example, the tabs are centered.
![image](https://github.com/user-attachments/assets/bc54cd4e-60b3-49b8-ab52-29fe52ac4d49)

**Comment by luketa8** [comment]
PR merged, moving to Done
