### ISSUE TITLE
October Grommet Patch Release

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#4172]
Issues to be resolved first:
This release should be a patch that only include the Accordion useId fix (https://github.com/grommet/grommet/pull/7345).

Steps for this release are a little different:
- [x] UseID fix PR, branch off of 2.40.1 tag (https://github.com/grommet/grommet/pull/7345)
- [x] Create new branch also off of 2.40.1 (https://github.com/grommet/grommet/tree/react-compatibility)
- [x] Update circle release script to only point to new branch (https://github.com/grommet/grommet/pull/7346)
- [x] Merge UseID fix into new branch
- [x] QA ensure stable branch looks good
- [x] Release
- [x] Switch circles release script back to point to master branch (https://github.com/grommet/grommet/pull/7352)
- [x] Merge new branch into master (https://github.com/grommet/grommet/pull/7351)

QA:
- [x] Ensure we are not using any react 18 only features

Storybook:
 - [x] Chrome (grommet theme) 

Grommet site:
no action needed

Grommet Designer: 
no action needed

Release Process:
-  [x] Release notes
-  [x] Contributors

Final steps:
- [x]  Update changelog
- [x]  Announce in slack (#announcements in Grommet, #ccs-ui, and #hpe-design-system)
- [x]  Upload new release in code insight tool, run a scan, generate SBOM
- [x]  Load SBOM into VTN

**Comment by jcfilben** [comment]
v2.40.2 of Grommet has been released https://github.com/grommet/grommet/releases/tag/v2.40.2
