### ISSUE TITLE
Theme - Update data visualization colors

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4175]
Update graph colors in grommet theme to align with the latest colors from design tokens: https://deploy-preview-3967--keen-mayer-a86c8b.netlify.app/design-tokens/all-design-tokens

Search "dataVis".

For now, we can stick with the grommet-theme-hpe namespace of `graph-`.

Deliverables:
- [ ] Adjust existing graph colors
- [ ] Add new graph colors for the additional steps.

**Comment by halocline** [comment]
@taysea - Has this work been completed? Can this be closed?

**Comment by taysea** [comment]
Yes this is merged into tokens branch, closing.
