### ISSUE TITLE
DSCC Audit  - Compare dashboard page

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4184]
Prepare side by side of comparison DSCC dashboard page & GLP Dashboard

Using the audit traffic light template to record divergences in DSCC from brand

https://www.figma.com/design/Z1OnPnNfM0QX204ykpWos8/DSCC-Audit-Visuals?node-id=136-11951

**Comment by vavalos5** [comment]
We've completed this and awaiting further review from @SeamusLeonardHPE . Scott has reviewed and liked direction.

**Comment by vavalos5** [comment]
Completed and confirmed done with Scott
