### ISSUE TITLE
DSCC Audit - Compare Table/List page

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4185]
Prepare side by side of comparison 

**DSCC list view page (large table) and a GLP page w/ a large table.**

Using the audit traffic light template to record divergences in DSCC from brand

https://www.figma.com/design/Z1OnPnNfM0QX204ykpWos8/DSCC-Audit-Visuals?node-id=153-13459

**Comment by vavalos5** [comment]
Completed and confirmed done with Scott
