### ISSUE TITLE
DSCC Audit - Refining findings & deliverables

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4186]
Oversee alignment on expectations  and deliverables for DSCC audit outputs.

- Seek agreement on supporting assets for review (template & stoplight component)
- Coordinating page and template level reviews by Kenny & Lucas
- Refining and standardizing existing research (atoms)

**Comment by vavalos5** [comment]
Completed and confirmed done with Scott
