### ISSUE TITLE
BUTTON - Execute final build

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4197]
### Build & review

- [x] Build
- [ ] Check the Component Checklist
- [ ] Ask for review (Providing success criteria & build checklist)
- [ ] If passed review move to V2 library from construction site

### Follow up
- [ ] Create followup issue for testing with consumers
- [ ] Create accessibility audit followup issue for Beta release

**Comment by CillianHPE** [comment]
Confirming the build part of this is completed and ready for a Review.

**Comment by SeamusLeonardHPE** [comment]
Updated with .focus sub component and fixed scaling issues - 
Documented rational on figma file


Follow up task to add build rational to confluence

**Comment by julauxen** [comment]
Review being done on following issues:
#4330 
#4331 
#4332
