### ISSUE TITLE
Refactor tag component

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4212]
Based on the updated guidance that is use case driven for tag component 

### Refactor existing tag to include variants

- [x] Static
- [ ] Interactive
- [x] Removable
- [x] Highlight

These should have name & name value options

Guidance mock up here 
https://www.figma.com/design/IiBz42hz6zRVC9g2TFMlTU/%234033-TAGS-Documentation?node-id=2-7078&t=akTjfpowslSbirTH-4

PR draft here
https://deploy-preview-4079--keen-mayer-a86c8b.netlify.app/components/tag

- Check with team and get alignment on how many size variant should be included in HPE theme?
- Consider the product designer experience
- Does the build prevent misconfiguration.
- Does the component achieve parity (can this be built in code)

Follow on from 
https://github.com/grommet/hpe-design-system/issues/4033

**Comment by luketa8** [comment]
Updated [Figma file](https://www.figma.com/design/Q30xl24dsthFzVbigR3mMS/%234212---Refactor-Tag-component?node-id=40-1273&node-type=frame&t=Q44PGZ6hcSt41Mx4-0) with component rebuild.

Using Primary/Blue for highlight variant for now. 

I have left two [Questions](https://www.figma.com/design/Q30xl24dsthFzVbigR3mMS/%234212---Refactor-Tag-component?node-id=40-1273&t=Q44PGZ6hcSt41Mx4-4) regarding the build.



@SeamusLeonardHPE @vavalos5

**Comment by luketa8** [comment]
Presented in Design Critique and updated [Figma FIle](https://www.figma.com/design/Q30xl24dsthFzVbigR3mMS/%234212---Refactor-Tag-component?node-id=11-273&t=jt6xXKAGKCVkuoix-4) with solid build candidate for static Tags, taking team's feedback into account.

**Comment by luketa8** [comment]
Added [Branch](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/branch/rBukBBwl6mLOwmr8n4cU6z/HPE-Design-System-Components?node-id=9685-105805&node-type=canvas&t=5UFobxURlioUvS7a-0) ready to review

**Comment by luketa8** [comment]
I took the opportunity to apply Variables and this question came up on spacing tokens. 

![Screenshot 2024-10-10 at 5 55 04 PM](https://github.com/user-attachments/assets/84b383c5-cb97-4941-b2d9-ad999c430dbd)


## Current horizontal-padding dimensions in code are 16px and 18px. Shall we match the closest Variable or add new ones?

**Comment by luketa8** [comment]
Tag refactor moved to [Tag rebuild](https://github.com/grommet/hpe-design-system/issues/4549). Closing this task.
