### ISSUE TITLE
Status color token enhancements

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4220]
- [ ] Establish whether we should omit 'status' from status color tokens: ADD LINK
- [ ] Establish whether to add additional tokens for status text and borders: ADD LINK

**Comment by oliverHPE** [comment]
We’ll omit the term ‘status’ from status color tokens. As such, `color.text.status.critical` will become `color.text.critical`  and so on for icons, backgrounds etc. The reason being that ‘status’ is seemingly superfluous and makes the name longer than necessary.
We’ll add status color tokens for borders and text. In the spirit of making the token schema adaptable to change (one of the criteria we always try meet), these tokens would be beneficial to controlling status colors for things like borders and text, that while they do not currently exist as separate colors, could very well be introduced at any point. Adding them now will reduce impact down the line.
