### ISSUE TITLE
Avatar - Tokenise Existing component

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4233]

**Comment by julauxen** [comment]
After talking with the team we decided that we would improve the component build as well as apply tokens.

**Comment by julauxen** [comment]
[Decision log](https://hpe.atlassian.net/wiki/spaces/DS/pages/2787344578/Avatar+-+V2)

This work is blocked as it is waiting on tokens.

**Comment by CillianHPE** [comment]
Review Links
[Figma Build](https://github.com/grommet/hpe-design-system/issues/4313)
[Code Parity ](https://github.com/grommet/hpe-design-system/issues/4315)
[Tokens](https://github.com/grommet/hpe-design-system/issues/4314)

**Comment by julauxen** [comment]
Avatar passed 2 rounds of review and can considered ready to be published.
