### ISSUE TITLE
FORM FIELD - Build Discovery

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4235]
- [x] Grommet prop audit
- [x] Determine props to be represented in Figma
- [x] Explore ways of building
- [ ] Document decisions

**Comment by SeamusLeonardHPE** [comment]
Added build options for review:

https://www.figma.com/design/f64po8pohL7ub95iIZabSt/%234242---Apply-tokens-to-Tabs?node-id=2164-2232

Success criteria for review of options:
- [ ] Applies component & state specific tokens
- [ ] Manages the prop panel to enhance product designers experience
- [ ] Provides maintainability for DS team
- [ ] Uses grommet prop terminology for variants
- [ ] Matches current HPE theme styles
- [ ] Achieves visual parity with code (this is not bi-directional)

**Comment by CillianHPE** [comment]
Review Links
[Figma Build](https://github.com/grommet/hpe-design-system/issues/4347)
[Tokens](https://github.com/grommet/hpe-design-system/issues/4348)
[Code Parity](https://github.com/grommet/hpe-design-system/issues/4345)
