### ISSUE TITLE
Tabs - Build Discovery

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4242]
Working in the v2 library apply tokens to the tabs component.

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2164-2232

- [x] Create branch specific to this issue
- [x] Replace existing styles with tokens
- [x] Note any missing tokens or unused tokens related to state

**Comment by vavalos5** [comment]
**Focus**
`hpe.color.focus` token not working properly

**Icon Color**
When I was changing the icon color, I was confused on when to use `hpe.color.icon.xweak` vs `hpe.color.icon.disabled` . Despite reading the definition we've got on our site, I was still unsure on which one to use.![Image](https://github.com/user-attachments/assets/fb702fe2-0560-4803-bd1a-4f04a8f9d6de)
![Image](https://github.com/user-attachments/assets/dcfa641b-93f0-4c08-92d2-3e92217ea916)

**Text Styles**

- Text styles haven't been created into token, so having to break it, apply Metric 2 HPE and correct font-weight took a little longer.
- Ensuring I was applying the correct font-weight took time as I had to refer to our [token values](https://design-system.hpe.design/design-tokens/all-design-tokens) for font-weights.
- Can't group change text styles (seems like a Figma limitation)


Overall, pretty easy to apply by searching the token name on library panel.

**Comment by SeamusLeonardHPE** [comment]
Linking to branch
https://www.figma.com/design/f64po8pohL7ub95iIZabSt/%234242---Apply-tokens-to-Tabs?node-id=2164-2232

Will review and add feedback asap

**Comment by julauxen** [comment]
Waiting on a decision on what token collection to use (large or medium)

**Comment by CillianHPE** [comment]
Review Links
[Figma Build](https://github.com/grommet/hpe-design-system/issues/4312)
[Code Parity](https://github.com/grommet/hpe-design-system/issues/4311)
[Token Review](https://github.com/grommet/hpe-design-system/issues/4310)

**Comment by julauxen** [comment]
Tabs passed 2 rounds of review and is ready to be published.
