### ISSUE TITLE
Menu - Phase 2 - Build

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4244]
Working in the v2 library apply tokens to the menu component.

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2192-542

- [x] Create branch specific to this issue (I applied changes to the main branch)
- [x] Replace existing styles with tokens
- [x] Note any missing tokens or unused tokens related to state

**Comment by julauxen** [comment]
- [ ] All tokens applied to the current build.

**Notes:** No specific token to text color for focus state in menu item, so we are using enabled.
![Image](https://github.com/user-attachments/assets/786085a5-5a36-4363-972e-bbef9d440e76)

- [ ] Reviewed prop panel to follow [Conventions.](https://hpe.atlassian.net/wiki/x/04Yrog)

**Waiting for focus sub-component to have it move to done.**

**Comment by SeamusLeonardHPE** [comment]
reviewed and accepted

**Comment by julauxen** [comment]
Reopening issue for proper review under our new process (figma build, tokens and code parity)

**Comment by julauxen** [comment]
Adding @SeamusLeonardHPE to the ticket as he is exploring the icon variants

**Comment by julauxen** [comment]
Closing as menu is published
