### ISSUE TITLE
Dateinput - Calendar exploration

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4262]
### Changelog

DateInput update:
- Variant 'Theme' removed including Dark mode

Calendar subcomponent update:
- '.Calendar/Default' renamed to '.Calendar'
- Added auto layouts throughout layers to fix spacing and grouping
- Replaced arrow icons with icon-only buttons
- Added subcomponents for individual days
    - Includes variants for all states
- Drop now correctly overlays on top of info and error messages

**Comment by KennyAtHPE** [comment]
Published and announced component update. Closing ticket.
