### ISSUE TITLE
Tag - Phase 1 - Discovery

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4264]

**Comment by luketa8** [comment]
Static and Interactive Tag component ready for review [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2619-41124)

**Comment by luketa8** [comment]
@oliverHPE 

Taylor shared a code update here:

https://deploy-preview-4498--keen-mayer-a86c8b.netlify.app/components/tag

Could we update the Button component with xsmall and these dimensions? 

T-shirt size| px size in code|px size in Figma
-------|-------|-------
xsmall | 24x24 | N/A
small  | 30x30 | 28x28
medium | 36x36 | ✓
large  | 48x48 | ✓
