### ISSUE TITLE
November Grommet Release

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#4266]
Issues to be resolved first:

QA:
- [x] Ensure that there is a test for every bug fix and enhancement
https://github.com/grommet/grommet/pull/7415

Storybook:
 - [x] Chrome (grommet theme) - Jessica
 - [x] FireFox (grommet theme)  - Jessica
 - [x] Safari (hpe theme) Brittany

Grommet site:
https://github.com/grommet/grommet-site/pull/528
https://github.com/grommet/grommet-site/pull/527

Grommet Designer: 
No changes needed

Release Process:
-  [x] Release notes
2.42.0

General:
- Added `cssGap` to propTypes and typescript for Box.(#7383)
- Enhanced Notification theme for status/kind `message` and `title` colors.(#7411)
- Enhanced Button theme with elevation.(#7408)
- Fixed the use of `useId` within Accordion to use a polypill useId.(#7405)
- Fixed the typescript for `onChange` in FileInput.(#7400)
- Fixed accessibility for Pagination to ensure that that `<ul>` does not contain any `div` elements.(#7379)
- Fixed DataSort to use the labels defined in the Data `properties`. (#7416)
- Fixed nested interactive elements accessibility issue on SelectMultiple component. (#7430)

Calendar:
- Added bolding to Calendar `range` of dates to meet accessibility requirements.(#7402)
- Enhanced Calendar to support additional state styles and rounding.(#7402)
- Fixed Calendar to allow for `space` key to be used to select dates.(#7357)

DataTable:
- Enhanced DataTable with `theme.dataTable.body.selected`.(#7384)
- Fixed space key interaction for clickable DataTable rows. (#7363)

List:
- Improved keyboard behavior by only calling `event.preventDefault()` when `onClickItem` or `onOrder` is used.(#7415)

Select: 
- Added `theme.select.clear.container.hover` for Select.(#7397)
- Fixed the typescript for `onMore` in Select.(#7395)
- Fixed `aria-label` for Select.(#7376)
- Fixed a bug in Select to allow for `jsx` elects to be passed in Select `options` prop.(#7333)
- Fixed Select to ensure `focusIndicator` prop only works if `plain=true`. (#7353)
- Fixed nested interactive elements accessibility issue on Select component. (#7420)

Tag:
- Added a default size of medium for Tag to default.(#7398)
- Enhanced Tag theme for `remove` Buttons.(#7386)

ToggleGroup:
- Enhanced theme with `toggleGroup.button.kind`(#7409)
- Enhanced ToggleGroup theme to allow divider to be removed and rounding on individual Buttons.(#7390)
- Fixed `aria-pressed` and `aria-checked` being set at the same time. (#7428)

-  [x] Contributors 

Final steps:
- [x]  Update changelog
- [x]  Announce in slack (#announcements in Grommet, #ccs-ui, and #hpe-design-system)
- [x]  Upload new release in code insight tool, run a scan, generate SBOM
- [x]  Load SBOM into VTN
- [x] Create ticket for next month's release

**Comment by jcfilben** [comment]
Grommet v2.42.0 has been released
