### ISSUE TITLE
DataVis - Revisit light mode categorical colors

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#4267]
Follow on to [#4042](https://github.com/grommet/hpe-design-system/issues/4042)

- After seeing the DataVis colors in the [deploy preview,](https://clinquant-seahorse-2f461d.netlify.app/) determined that the colors should be tweaked.

Deliverables:
- [x] Light mode values for each of the existing `dataVis.categorical` colors. Ensure proper accessibility requirements for color contrast on background colors.

**Comment by taysea** [comment]
Light mode colors have been updated in https://www.figma.com/design/vH5MOEoXU5Kv7qWvBqiUC2/Design-Tokens---Semantic?node-id=0-1&t=ppPaNfWIbmouaamG-1
