### ISSUE TITLE
Auditing DSCC Figma assets

### ISSUE THREAD

**Issue by KennyAtHPE** [grommet/hpe-design-system#4268]
Perform an audit on the DSCC Figma library. Make a note of:
- All their assets (components, templates, etc.)
- Compare discrepancies between our assets and theirs
     - Naming differences 
     - What do we have and they don't?
     - What do they have and we don't?

-----------------------
**Core Links**
- [Working File
](https://www.figma.com/design/wo6szj9Lmtw257mhXQAUWY/DSCC-Figma-Audit?node-id=4-2011&t=0libn54CKUtJ1eth-1)
- [Vicky's previous audit document](https://hpe.atlassian.net/l/cp/AyU5LFzw)
- [DS + DSCC component comparison checklist](https://www.figma.com/design/wo6szj9Lmtw257mhXQAUWY/DSCC-Figma-Audit?node-id=3-13180&t=0libn54CKUtJ1eth-1)

**Misc. Links**
- [Example of an inventory sheet](https://www.figma.com/design/IpxvTNHkD0Oz2GXw3KWgcw/Audit---HPE-Design-System-Library?node-id=450-11361&t=t2DrWWNZYy6C7JQs-1) we had used for comparing components in the past.

**Comment by KennyAtHPE** [comment]
10/31 update:
- Met with Taylor, Matt, and Scott to redefine scope
- Started a component comparison checklist between our library and DSCC's
- Matt and I will work together to further redefine the scope

**Comment by taysea** [comment]
The initial working session with Judy has occurred. Given this will be ongoing work and more directly related to v2 library adoption, closing this ticket to allow future more specific tickets to be opened.
