### ISSUE TITLE
PageHeader - Build discovery/Apply tokens

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4271]
The most recent build from v1 was copied over to teh v2 library & the menu & button were replaced  with the new v2 versions.

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2563-6917

- Apply tokens to text & bg color
- Apply tokens (if possible) to reverse anchor

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE [Branch file](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/branch/6n8XtP4WIuIROkj2HZNgrG/v2-Construction-Site?m=auto&node-id=2563-6917&t=f6KlAhZdIWWh0hgF-1). Parking this within in review, but would like to make updates together synchronously so I can have a better understanding of what was right/wrong.

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE Ready for another round of review. I've doubled checked the component using FigLint and Variable Vision

**Comment by julauxen** [comment]
Review and final build are being considered here: [#4460](https://github.com/grommet/hpe-design-system/issues/4460)
