### ISSUE TITLE
Define element t-shirt size tokens -- when to use

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4285]
Deliverables:
- [x] Write a definition for what `element` refers to in generic `element` t-shirt size tokens: https://hpe.atlassian.net/l/cp/KecqhzTF

**Comment by oliverHPE** [comment]
Taylor, this is great thank you. I think this works for internal documentation that explains what `element` tokens are for and how to use them.

Let's create a follow up issue to plan and create content for guidance on component sizing and related topic `element` tokens for both consumers and DS maintainers. We could go a little further into our component sizing system of tier 2 components and how they relate to element tokens and the component build. We'll want to plan how we can organise this info on our foundations and Tokens documentation pages.

**Comment by taysea** [comment]
Added #4319 , #4320
