### ISSUE TITLE
NOTIFICATION - Figma Build Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4302]
Branch: https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/branch/mO02iMASrrXu9aYmO6nXIW/v2-Construction-Site?m=auto&node-id=2168-1437&t=jh11zVPuF98gg8Wh-1

**Comment by luketa8** [comment]
All Updates made to [Figma file](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/branch/mO02iMASrrXu9aYmO6nXIW/v2-Construction-Site?node-id=2168-1437&node-type=canvas&t=auMXoLjFqy0LKhEQ-0)


- Fixed layer and prop naming
- Fixed missing properties
- Fixed color tokens for dark mode
- Added a couple of comments

**Comment by julauxen** [comment]
hey Lucas, assigning back to you since you are applying the requested changes.
