### ISSUE TITLE
EMPTY STATE - Token review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4307]

**Comment by julauxen** [comment]
Component ready for review [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3417-7807&t=VuDNaju0piBucfRz-1)

**Comment by CillianHPE** [comment]
@julauxen 

Review done here.

JUst one issue for a missing token.

**Comment by julauxen** [comment]
Thank you, it's fixed now, so I am closing this issue.
