### ISSUE TITLE
TABS - Code Parity

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4311]
[Link to Figma](https://www.figma.com/design/OFZvINDPeCzL4jFROxVpSz/Cillian-Review?node-id=2164-2232)

**Comment by CillianHPE** [comment]
@julauxen I have completed my review.

**Comment by julauxen** [comment]
Applied the agreed fixes. Ready for second round of review [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=2164-2232&t=t2e2QGYyE5HZnXCf-1). @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen

Everything looks good; I’m happy to finalize this review.
