### ISSUE TITLE
Layers - Phase 1 - Discovery

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4323]
V1 version of layers have been imported to the v2 library - 

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3120-18461

- [x] Replace any atoms with suitable v2 versions 
- [x] Update surfaces & text with suitable tokens
- [x] Note any future add-ons (eg awaiting some form field elements)

Buttons and slot already replaced, and in one case a textinput  - look into tokenizing colors, bgs, elevation, text etc

For now don't worry about the sidebar with form fields and thos are still WIP, but all other elements would be ready to tackle

**Comment by oliverHPE** [comment]
Updated tasks:

- [ ] Please archive the current v2 center layer and side drawer in an archive section on the 'layers' page in the v2 construction site.
- [ ] Propose new versions of center layer and side drawer that do not have examples as variants
    - [ ] Center layer
       - [ ] Actionable with slot
       - [ ] Informational with slot
    - [ ] Side drawer
       - [ ] Actionable with slot
       - [ ] Informational with slot
- [ ] Update background color to `color.background.floating` for Center layer and Side drawer

**Comment by luketa8** [comment]
- Layer components archived
- Removed examples as variants
- Updated V2 Button
- Updated background color to `color.background.floating` in Center layer and Side drawer

Outstanding items to address:
- Button Group component instead of footer
- Template Library V2 and Preferred values for Slot usage.

**Comment by luketa8** [comment]
Layer components ready for review [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3654-3921), moving to done.
