### ISSUE TITLE
BADGE - Token Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4325]

**Comment by julauxen** [comment]
First review is done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3167-1658&t=gQH3LDO6xkwfCv26-1) @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen 

Changes made and key decisions logged in [Confluence](https://hpe.atlassian.net/wiki/spaces/DS/pages/2733345422/Badge+-+V2)

**Comment by julauxen** [comment]
Looks good, ready to close @CillianHPE
