### ISSUE TITLE
BADGE - Figma Build Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4326]

**Comment by julauxen** [comment]
Review done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3260-7619&t=gQH3LDO6xkwfCv26-1). @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen 

Changes applied.

**Comment by julauxen** [comment]
Hey, the only new comment I have is that now, in the value variant, the container is not hugging the content. See [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os?node-id=3321-14708#1015616760). @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen 

Thanks that's fixed now.

**Comment by julauxen** [comment]
Thanks, looks right to me, good to close
