### ISSUE TITLE
TIP - Token Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4328]

**Comment by julauxen** [comment]
Token review ready [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=28-2455&t=GVldR0MEqnifTU6y-1).

**Comment by CillianHPE** [comment]
@julauxen 

Changes have been made.

**Comment by julauxen** [comment]
Hey CillAN, i just have a final question on the choice of the text token for the tip. I added the comment [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3269-7912&t=GVldR0MEqnifTU6y-1). @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen 

Changes applied.

**Comment by julauxen** [comment]
I am good with changes, good to close. @CillianHPE
