### ISSUE TITLE
TIP - Figma Build Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4329]

**Comment by julauxen** [comment]
Review done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3260-7423&t=GVldR0MEqnifTU6y-1).

**Comment by CillianHPE** [comment]
@julauxen 

Changes applied.

**Comment by julauxen** [comment]
I am good with changes, good to close @CillianHPE
