### ISSUE TITLE
BUTTON - Token Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4331]

**Comment by julauxen** [comment]
Review ready [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3142-3915&t=GVldR0MEqnifTU6y-1).

**Comment by CillianHPE** [comment]
@julauxen 

Changes applied.

**Comment by julauxen** [comment]
Token review 2 is done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3305-11133&t=7oSyM0EE9t8X2mO8-1). @CillianHPE
