### ISSUE TITLE
BUTTON - Figma Build Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4332]

**Comment by julauxen** [comment]
Review is done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3302-6144&t=gQH3LDO6xkwfCv26-1). @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen 

Changes have been made.

**Comment by julauxen** [comment]
Looks good to me, ready to close @CillianHPE
