### ISSUE TITLE
Input Switch [in FormField]- Token review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4340]
Link to token test region

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5012-161187&t=P9ZIdBb6Hf53Whzq-4

**Comment by julauxen** [comment]
hey @SeamusLeonardHPE Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=5012-161187&t=8t8wxtZHxqe4DNbr-1) There's just one token misused, once that's fixed we can close this issue. No need for a second review.

**Comment by SeamusLeonardHPE** [comment]
Token fixed and [published](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3026-1771)
