### ISSUE TITLE
Form Field - Figma Build Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4347]
Token Test region - 

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4741-22956&t=zXrECwilarlrNMTJ-4

NOTES - for build testing

- All visibility booleans are switched on for testing convenience, however Required / Help / Info will all be toggled off for published formfield + input components
- All text variants were removed to help reduce prop panel clutter in nested inputs
- Error message layer was removed from all other variants to avoid potential misconfiguration and is managed by variant, not boolean.

**Comment by SeamusLeonardHPE** [comment]
Fixed in fromField/input components & closed
