### ISSUE TITLE
Form Field - Tokens Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4348]
Token test region - 

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4741-22956&t=zXrECwilarlrNMTJ-4

**Comment by CillianHPE** [comment]
@SeamusLeonardHPE 

Added some comments.

**Comment by SeamusLeonardHPE** [comment]
Closed as completed after connecting with Cillian
