### ISSUE TITLE
Checkbox control - Build Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4349]

**Comment by julauxen** [comment]
Hey @CillianHPE, first review done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3754-6904&t=M5qCTiW2PG4LvQ4g-1).

**Comment by julauxen** [comment]
Yesterday Seamus applied the changes requested.
Today I gave it a second review and it looks good to close. @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen 

Changes made

**Comment by julauxen** [comment]
I am good to close, thanks @CillianHPE
