### ISSUE TITLE
Checkbox control - Tokens Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4350]

**Comment by julauxen** [comment]
Hey @CillianHPE, first review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3754-6906&t=M5qCTiW2PG4LvQ4g-1)

**Comment by CillianHPE** [comment]
@julauxen 

Checkbox tokens have been updated

**Comment by julauxen** [comment]
Hey @CillianHPE, I am good to close, thanks!
