### ISSUE TITLE
Update Icon and Foreground color Tokens in code

### ISSUE THREAD

**Issue by luketa8** [grommet/hpe-design-system#4352]
### Describe the feature you'd like to request.

Color Tokens were updated in this [Ticket](https://github.com/grommet/hpe-design-system/issues/2446)

Now we need to make those updates in code following the same [scheme](https://www.figma.com/design/6oYsSnnf9j8BJDhFwzNCWq/%232446---Notifications-accesibility?node-id=160-2027)

**Comment by britt6612** [comment]
All of these values are updated in the correct places once we do the `hpe-grommet` release then we will see changes on the DS site.
