### ISSUE TITLE
Icons — Non-Grommet implementation spike

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4355]
We would like to deliver the updated icon set for Grommet and non-Grommet teams. This research spike is focused on how we might deliver icons for non-Grommet teams.

From a dev experience standpoint, it would be ideal for teams to easily:
- Adjust the size of icons in alignment with our icon size tokens
- Adjust the color of icons in alignment with our icon color tokens

The mechanism for doing so (prop-based, class name, etc.) is up to be determined based on research into common approaches across other icon libraries.

Considerations:
- Consume as an svg element to embed in DOM
- Consume as an .svg asset file loaded as a request by the client at runtime

Deliverables:
- [x] Research and summarize different approaches to icon package delivery that is compatible across React/Angular/etc.: see comments below

**Comment by MikeKingdom** [comment]
Greenlake header currently uses grommet-icons like this:
```jsx
import bellSvg from "grommet-icons/img/notification.svg";

<img class='menu-button-icon' src=${bellSvg} aria-label='Notifications'/>
```

**Comment by MikeKingdom** [comment]
Another option for using the existing SVGs is include them directly into the DOM as `<svg>` related elements and then style them with some CSS:
```jsx
import bellSvg from 'grommet-icons/img/notification.svg!raw';
...
<div class="grommet-icon">{bellSvg}</div>
```
CSS
```css
.grommet-icon path {
  stroke: red;
  stroke-width: 2;
}
```

If the SVG uses `currentColor` for a stroke or fill attribute it's easier to color the icon simply with whatever `color` attribute is inherited in the CSS at that point rather than targetting the stroke or fill of the SVG,

**Comment by MikeKingdom** [comment]
Creating a font for the icons (much like font-awesome or material icons) is a rather convenient and efficient way to use the icons and makes styling them with color or size a lot easier. And the font can easily be provided by a CDN (and therefore cached at various levels) or included in the app.

Example:
```html
  <link rel="stylesheet" href="grommet-icons.css">
   <i class="icon icon-accessibility" style="color: red; font-size: 48px;"></i>
```

The example font was created from grommet-icons via `@twbs/fantasticon`, `svgo` and `oslllo-svg-fixer`:
```bash
svgo -f ./node_modules/grommet-icons/img -o svg
oslllo-svg-fixer -s ./svg -d ./svg
fantasticon ./svg -o font --name grommet-icons
```

The result (via the preview HTML it creates):
![image](https://github.com/user-attachments/assets/8e42a842-1fa3-44c0-b146-877a9a5bb565)

**Comment by MikeKingdom** [comment]
Another way of using the existing svg files of grommet-icons and styling them with design tokens. Stroked icons have to target `stroke` whereas filled icons have to target `fill`.

CSS
```css
.gi-color-brand path {
  stroke: var(--hpe-color-icon-brand);
}
.gi-colorf-brand path {
  fill: var(--hpe-color-icon-brand);
}
.gi-size-xsmall svg {
  width: var(--hpe-size-icon-xsmall);
}
``` 
JSX
```jsx
import bellSvg from 'grommet-icons/img/notification.svg?raw';

...
<div class="gi-color-brand gi-size-xsmall">
    ${bellSvg}
</div>
```

Filled icon:
```jsx
import arubaSvg from 'grommet-icons/img/aruba.svg?raw';

...
<div class="gi-colorf-brand gi-size-xsmall">
    ${arubaSvg}
</div>
```

**Comment by MikeKingdom** [comment]
A popular option for icons is to provide an icon font (similar to Material's Outline Icon font, fontawesome, etc.).These are fairly easy to style (color/size) via CSS and therefore works well with design tokens. An icon font file, although loaded up front, can be set up to be cached, prefetched, served from a CDN etc.

We can create a fairly decent font version of grommet icons automatically as part of a CI/CD with OSS npm packages like `@twbs/fantasticon` with a little help from `oslllo-svg-fixer` (to convert stroked icons to filled outlined icons) and optimize the svgs via `svgo`.

For example:
```bash
oslllo-fixer -s ./node_modules/grommet-icons/img -d ./svg
svgo -f ./svu -o svg
fantasticon ./svg -o font --name grommet-icons
```

`fantasticon` has a nice side benefit of creating an html file that makes it easy to view all the icons in the font.

Example of using the font icons:
Token usage in CSS
```css
.icon-color-default {
  color: var(--hpe-color-icon-default);
}
.icon-color-brand {
  color: var(--hpe-color-icon-brand);
}
.icon-size-xsmall {
  font-size: var(--hpe-size-icon-xsmall);
}
```
HTML or JSX
```jsx
import './font/grommet-icons.css';

...
<i class="icon-accessibility icon-size-xsmall"></i>
<i class="icon-accessibility icon-color-brand icon-size-small"></i>
```

**Comment by MikeKingdom** [comment]
The Material icon font does provide a font that allows "variations" via css. One main variation they provide for some icons is a filled option as well as weight and size variations. For example, this css can make the icon filled with a size of 24 and weight 400:
```css
font-variation-settings: "FILL" 1, "wght" 400, "opsz" 24;
```
It looks like a fair bit of work and requires font editing tools to add variants for specific glyphs in the font, but it's certainly an option. We've definitely had requests for some filled versions of certain icons.
