### ISSUE TITLE
Status Indicator - Figma Build Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4372]

**Comment by julauxen** [comment]
Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3462-7205&t=3KWZlg3p5g0W55ZP-1) @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen 

Changes now made.

Alot of the comments are irrelevant as we decided to remove the "stacked version"

**Comment by CillianHPE** [comment]
@julauxen 

Sorry I missed that, it's removed now.
