### ISSUE TITLE
Date Time - Tokens Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4377]

**Comment by julauxen** [comment]
Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3462-7834&t=3KWZlg3p5g0W55ZP-1) @CillianHPE

**Comment by CillianHPE** [comment]
@julauxen 

Gap token was added as discussed in today's sync.

**Comment by julauxen** [comment]
Looks good @CillianHPE, good to close.
