### ISSUE TITLE
Accordian - Code Parity Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4381]

**Comment by julauxen** [comment]
Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3505-18092&t=3uqpa6uwSbNyUH0B-1) @CillianHPE

**Comment by CillianHPE** [comment]
No need to preform code parity review as its was a lift and shift from previous library.
