### ISSUE TITLE
FocusIndicator - test build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4386]
The styling of the focus indicator might change. Given the that focusIndicator is a subcomponent in Figma, we need to ascertain the impact of updates and the ability of the focus to handle new sttling. For example, a double border. 

The focusIndicator might require a nested layer with a border that imitates an offset outline in code. Furthermore, the color might be updated.

We need to test the following:

Can we update the .focus with a new nested layer that has a stroke applied and measure the impact on updating consuming subcomponents with the new focus update, considering the new nested layer will have to match the corner radius of consuming components.

This will determine:

- Whether our current focusIndicator is sufficient to handle such updates
- The effort involved in updating consuming components

Deliverables

- [x] A test FocusIndicator subcomponent with a nested layer, styled with a border that extends beyond the boundaries of the parent layer to mimic an offset outline in CSS.
- [ ] A summary, with examples, of the testing process of updating a component consuming the test FocusIndicator

**Comment by CillianHPE** [comment]
Converting the existing Focus indicator to have a 2px offset works effectively but we need to keep the following in mind.

**Border radius**
- Anywhere component where a border-radius is used, the focus indicator must also use the same border radius.
- The "Blue ring" of the focus indicator must also have the same border radius token applied.
