### ISSUE TITLE
Menu - Code parity review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4387]
Code party review for naming conventions & functionally for Menu competent

The linked section in figma contains 2 instances 
1 - Menu component
2- sub component Menu item

Please review the props in dev mode playground and note anything that is unexpected
 
https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3895-25111&t=520kuyXigFlR4ZFP-4

**Comment by britt6612** [comment]
@SeamusLeonardHPE 

### Menu 
Is there an option `label` are users able to edit the label?
What is the aligned doing? I see no difference when changing from left to right?
Extra color in the variables modes.. should just be dark/light


### Menu Item:
Should the hovered be rounded?
Should the focused be rounded?

**Comment by SeamusLeonardHPE** [comment]
passed by Brittany on a call
