### ISSUE TITLE
Menu - Token review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4388]
[Link to v2 menu component](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3622-35344&t=d4Z65am0elBlgyWC-4)

**Comment by julauxen** [comment]
Hey @SeamusLeonardHPE review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3622-35346&t=M5qCTiW2PG4LvQ4g-1)
