### ISSUE TITLE
Menu - Figma Build Review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4389]
[Link to v2 menu component](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3622-35344&t=d4Z65am0elBlgyWC-4)

**Comment by julauxen** [comment]
Hey @SeamusLeonardHPE review done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3622-35344&t=M5qCTiW2PG4LvQ4g-1)

**Comment by SeamusLeonardHPE** [comment]
@julauxen I made edits as required and added notes on your comments.

Tagging Brittany for dev review in [#4387](https://github.com/grommet/hpe-design-system/issues/4387)

**Comment by julauxen** [comment]
Hey @SeamusLeonardHPE, review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3907-10833&t=VuDNaju0piBucfRz-1)
No new issues found, ready to close from my side.
