### ISSUE TITLE
Center layer - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4390]

**Comment by luketa8** [comment]
@julauxen @oliverHPE

Hey! 3 Layer components and 2 parts sets are ready for review [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3654-3921)

**Comment by julauxen** [comment]
Review tickets:
#4435

**Comment by julauxen** [comment]
Closing as Published
