### ISSUE TITLE
Data Cell - Figma build review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4395]
**[Link to Figma](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2591-7742)**

**Comment by julauxen** [comment]
Hey cillian, review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4386-7976&t=1SRwjp3IvVk9BcrI-1) Most of the "feedback" are questions, so feel free to ignore if ti makes no sense.
