### ISSUE TITLE
Data cell - Token review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4396]
**[Link to Figma](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2591-7742)**

**Comment by julauxen** [comment]
hey @CillianHPE see review [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4058-18289&t=7CAWpjsg1RyFNBqQ-1)

**Comment by CillianHPE** [comment]
@julauxen 

Updates made.

**Comment by julauxen** [comment]
Looks good, I am good to close!
