### ISSUE TITLE
Icon audit

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4399]
Audit the new Figma v2 icons to determine

- Icon parity
  - Indicate missing icons in the v2 library, if any.

- Naming parity
  - List the names of the new icons and compare to the old icons
  - Indicate name mismatches

Deliverable:
A file that provides a visual of icon parity and naming parity displaying both v1 and v2 icons and names. Clearly indicate errors or missing icons. (This file can be used as a reference to give the v2 icon library status and to indicate icon issues we need to address.)

**Comment by SeamusLeonardHPE** [comment]
LInk to audit

https://www.figma.com/design/vtvb9X3y3UqTbaDoZ25w1I/HPE-ICON-AUDIT?node-id=0-1&t=dYXRBPMVNgtrPikG-1
