### ISSUE TITLE
Update 'Use the Colors' link on the color page 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#442]
### Is this issue related to the design system core library or design system website?

Update the Use the Color link at the top of the page to the below 

Color accessibility (https://theme-designer.grommet.io/Accessibility) 
* Im open to changing the words but want to make sure they reflect where the link is going. 

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by halocline** [comment]
Closing, no longer relevant.
