### ISSUE TITLE
Switch - Token review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4423]
[Link to Figma ](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3822-10750)

**Comment by CillianHPE** [comment]
@julauxen 

Switch is ready for review.

There's currently an issue with mapping the tokens for the Dark mode. But you can still continue with token test.

**Comment by julauxen** [comment]
@CillianHPE review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3822-12274&t=VuDNaju0piBucfRz-1)

**Comment by julauxen** [comment]
Hey @CillianHPE, thanks! Second round of review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3926-20402&t=9Xqb5bF7rSKmC0Vc-1). There's just one comment about the border radius on focus indicator. Once that's fixed I am good to close the review.
