### ISSUE TITLE
Switch - Figma Build

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4424]
[Link to Figma ](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3822-10750)

**Comment by julauxen** [comment]
Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3822-12270&t=VuDNaju0piBucfRz-1) @CillianHPE

**Comment by julauxen** [comment]
Thanks, it looks good now! I am good to close
