### ISSUE TITLE
Popover - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4432]

**Comment by luketa8** [comment]
[Popover](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3958-3274) ready for review

**Comment by julauxen** [comment]
Review tickets:
#4465 
#4466 

I have not created the issue for code parity review because I am unsure if it's necessary. I will leave it up to you @luketa8

**Comment by SeamusLeonardHPE** [comment]
Popover edit & republish complete.

Removed frame that contained close button and switched close button to not be absolute positioned.
