### ISSUE TITLE
Centre Layer - Token Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4436]

**Comment by julauxen** [comment]
@luketa8 Review done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3991-16170&t=BPNm2QsYDOiskWXR-1)

**Comment by luketa8** [comment]
All updates made, assigning back to you @julauxen

**Comment by julauxen** [comment]
Hey @luketa8 I have just some extra comments [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4061-11721&t=quwEGzXKiLoJHRSy-1). Thanks!

**Comment by julauxen** [comment]
Looks right @luketa8, I am goos to close. Thanks!
