### ISSUE TITLE
Full screen - Figma Build Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4439]

**Comment by luketa8** [comment]
Changes done, back to you @julauxen

**Comment by julauxen** [comment]
Hey @luketa8 just a few more comments [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4112-11626&t=ikkBeJoUuifYjN3t-1)

**Comment by luketa8** [comment]
Changes done, back to you @julauxen
