### ISSUE TITLE
Full screen - Token Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4440]

**Comment by julauxen** [comment]
@luketa8 Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=3991-16672&t=bXrKtkNxAJbi56A6-1)

**Comment by luketa8** [comment]
Changes done, back to you @julauxen

**Comment by julauxen** [comment]
Hey @luketa8 just a few more comments [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4112-11633&t=ikkBeJoUuifYjN3t-1)

**Comment by luketa8** [comment]
Changes done, back to you @julauxen
