### ISSUE TITLE
Update Header with code example, desktop/mobile controls 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#445]
![image](https://user-images.githubusercontent.com/17712467/75711346-816b8580-5c83-11ea-9499-80a1e8ae1382.png)

Related to: https://github.com/hpe-design/design-system/issues/440

**Comment by britt6612** [comment]
## Discuss if we want to add the desktop and mobile view to the header and footer examples in components page 

* Add component to be able to switch views from desktop to mobile
* Change the Header example to include hidden text when mobile view

**Comment by halocline** [comment]
Needs discussion / resolution as to whether this work makes sense / fits / is consistent with the rest of the examples on this page.

**Comment by halocline** [comment]
Closing due staleness.
