### ISSUE TITLE
Footer Cells - Tokens Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4454]

**Comment by julauxen** [comment]
Hey @CillianHPE review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4058-18104&t=7CAWpjsg1RyFNBqQ-1) From the tokens application side it looks correct, I just have one doubt there for oliver.

**Comment by CillianHPE** [comment]
@julauxen 

Tokens now updated.

**Comment by julauxen** [comment]
Thanks, I am good to close! @CillianHPE
