### ISSUE TITLE
Header Cell - Figma Build Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4458]

**Comment by julauxen** [comment]
hey @CillianHPE review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4058-17914&t=ikkBeJoUuifYjN3t-1)

**Comment by CillianHPE** [comment]
@julauxen 

I've applied that change. I'll close the ticket now.
