### ISSUE TITLE
Header Cell - Tokens

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4459]

**Comment by julauxen** [comment]
Hey @CillianHPE review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4058-17918&t=ikkBeJoUuifYjN3t-1)

**Comment by CillianHPE** [comment]
@julauxen 

Changes made, ready for second review.

**Comment by julauxen** [comment]
Thanks @CillianHPE it looks correct, I am good to close
