### ISSUE TITLE
Page Header - Token review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4461]

**Comment by julauxen** [comment]
@SeamusLeonardHPE Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4060-5134&t=quwEGzXKiLoJHRSy-1)

**Comment by julauxen** [comment]
Hey @SeamusLeonardHPE I just have one open question on tokens [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4451-2994&t=qe5fzpkDKcMsVHSC-1). If that's intentional, feel free to close the issue.
