### ISSUE TITLE
Page Header - Figma build review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4462]

**Comment by julauxen** [comment]
Hey @SeamusLeonardHPE Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4060-5132&t=quwEGzXKiLoJHRSy-1)

**Comment by julauxen** [comment]
Hey @SeamusLeonardHPE I just have some minor comments on the props panel and the component name. [See here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4451-2846&t=qe5fzpkDKcMsVHSC-1)
Once those are done, feel free to close the issue
