### ISSUE TITLE
Popover - Figma Build Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4465]

**Comment by julauxen** [comment]
@luketa8 Review done [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4061-7075&t=quwEGzXKiLoJHRSy-1)

**Comment by julauxen** [comment]
Hey @luketa8 thanks! I am just seeing a few weird behaviours in terms of responsiveness. [See here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4129-19898&t=7CAWpjsg1RyFNBqQ-1)

**Comment by julauxen** [comment]
Hey @luketa8 just a few more comments [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os?node-id=3958-3312#1041006182) and [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os?node-id=3958-3832#1044605753). Thanks!

**Comment by luketa8** [comment]
Updates made!

**Comment by julauxen** [comment]
looks good, i am good to close @luketa8
