### ISSUE TITLE
Popover - Token Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4466]

**Comment by julauxen** [comment]
@luketa8 Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4061-7077&t=quwEGzXKiLoJHRSy-1)

**Comment by luketa8** [comment]
Thanks! Component updated based on review, back to you.

**Comment by julauxen** [comment]
Hey @luketa8 thanks you! I have just a few doubts still on the paragraph, [see here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4129-20506&t=7CAWpjsg1RyFNBqQ-1)

**Comment by julauxen** [comment]
Hey @luketa8 token testing is good to close!

**Comment by luketa8** [comment]
Updates made!

**Comment by julauxen** [comment]
looks good, i am good to close
