### ISSUE TITLE
Selector - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4494]

**Comment by luketa8** [comment]
Added updated build [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4335-15660). Not ready for review.

To discuss
- New utility -> Icon wrapper [component](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4348-7931&t=9weBtLAhYqV10NAW-4)

**Comment by luketa8** [comment]
Selector, Parts and iconWrapper are Ready for Review [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4726-4377&t=ush4KjB28ylPj1hT-4)
