### ISSUE TITLE
Card - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4496]

**Comment by luketa8** [comment]
Card is ready for review [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4392-4868)

**Comment by julauxen** [comment]
Review tickets:
#4625 
#4624

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3062-2494&t=2NvL5zJQMKMthYdM-4)
