### ISSUE TITLE
Grid 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#451]
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [ ] Theme
- [ ] Grommet
- [ ] Code Examples
- [ ] Guidance  

https://www.figma.com/file/OvLyDPjqHbwoDI97r2nD8j/HPE-Grid-Component?node-id=177%3A12

**Comment by ericsoderberghp** [comment]
Superseded by https://github.com/grommet/hpe-design-system/issues/1517
