### ISSUE TITLE
Selector - Token Review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4520]

**Comment by julauxen** [comment]
@luketa8 Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4799-24640&t=yvzhP0tYU8MwUz5H-1)

**Comment by luketa8** [comment]
Updated, back to you!

**Comment by julauxen** [comment]
hey @luketa8 just a few more comments on a gap token [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4917-1241&t=zKnWFb3rK3JlvzQg-1)

**Comment by luketa8** [comment]
Gap token applied and published, thanks!
