### ISSUE TITLE
Selector - Figma build review

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4521]

**Comment by julauxen** [comment]
Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4799-24638&t=yvzhP0tYU8MwUz5H-1)

**Comment by luketa8** [comment]
Updated, back to you!

**Comment by julauxen** [comment]
Looks good @luketa8 I am good to close
