### ISSUE TITLE
Checkbox / Radio / ToggleSwitch - Phase 1 - Discovery

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4533]

**Comment by SeamusLeonardHPE** [comment]
Link to testing area - 

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5012-58258&t=tnGyyXYUo2Ax9CHy-4

**Comment by SeamusLeonardHPE** [comment]
Completed by demo & decisions made here Bed 13th

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4901-7047&t=XAs2ZHjsVfRavH9j-4
