### ISSUE TITLE
Name Value Pair - Code Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4534]
Hey @britt6612 please take a look at the name value pair component [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4702-14589&t=0VmMCq1f5sThzf9y-1) Feel free to leave your comments in this issue.
Keep in mind we are delivering the name value pair, and the list will be handled in templates in the future.

Thanks!

**Comment by britt6612** [comment]
@julauxen 

I had a few questions..

- If I select kind `anchor` I dont see an option to edit the `text` it just shows `anchor` Should there be an option to change or designer will know how?
<img width="845" alt="Screenshot 2024-12-09 at 8 51 02 PM" src="https://github.com/user-attachments/assets/aa9788d8-148f-477f-bdd2-5119014243f7">


- Do we need the kind `date and time`? 
- I do see `width` under name and value in code this is done in the NameValueList. I know you mentioned a template will come later so will there be an option in both? will that be confusing?

**Comment by julauxen** [comment]
hey @britt6612 thanks for the review! Here are the answers:

- If I select kind anchor I dont see an option to edit the text it just shows anchor Should there be an option to change or designer will know how?
**The designer will know. The reason we don't have the option to edit here is because of a bug in figma where, if the user edits on the props panel, the anchor styling breaks.**

- Do we need the kind date and time?
**This is a decision done specifically for the figma assets, to help designers standardize the way date and time is presented in name value pairs, table and so on.**

- I do see width under name and value in code this is done in the NameValueList. I know you mentioned a template will come later so will there be an option in both? will that be confusing?
**I was trying to represent the following props: `nameValueList.name.width` and `nameValueList.value.width`. I get that they are applied in the list level, but they refer to the name and the value separately. In figma, it's harder to build the kind of flexibility where a parent can affect a child, so that's why we decided to apply for name and value in the pair itself. In the future we will have templates showcasing many different configurations, but the editing will always happen at the pair level.**

**Comment by britt6612** [comment]
@julauxen 

Thank you for the follow up these make sense.

**Comment by julauxen** [comment]
Thanks! Closing as done
