### ISSUE TITLE
RadioGroup [in FormField] - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4536]
Link to release candidate

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5053-11880&t=Q8SypSwHFQYOzVT5-4

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-13162&t=2NvL5zJQMKMthYdM-4)
