### ISSUE TITLE
ToggleSwitchGroup [in FormField] - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4537]
Link to release candidate

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5057-45799&t=Q8SypSwHFQYOzVT5-4

**Comment by SeamusLeonardHPE** [comment]
[Closed and published](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-14588&t=QFASKe9igCFMtLMb-4)
