### ISSUE TITLE
Global Header - Figma Build Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4539]
**[Link to Figma](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4468-13385)**

**Comment by julauxen** [comment]
Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4468-13426&t=0VmMCq1f5sThzf9y-1)

**Comment by CillianHPE** [comment]
@julauxen 

Updated.

**Comment by julauxen** [comment]
Looks good to me, I am good to close
