### ISSUE TITLE
Global Header - Tokens Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4540]
**[Link to Figma](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4468-13385)**

**Comment by CillianHPE** [comment]
@julauxen 

Gap tokens updated.

**Comment by julauxen** [comment]
Hey @CillianHPE I just have 2 more questions, after those are clarified I am good to close. [See here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4807-34208&t=yvzhP0tYU8MwUz5H-1)

**Comment by CillianHPE** [comment]
@julauxen  thanks!

I've updated the places with tokens.

I'll close now.
