### ISSUE TITLE
Input Build Discovery

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4548]
Inputs can appear in and outside of formFields. If we wish to provide inputs outside of formFields, what is the best way to build them in Figma?

**As separate components:**

1. Text Input
2. Text Input in Formfield

**As separate variants within one component set:**

- Text input
1.  Variants: In formfield
2.  Variants: standalone

**One variant set, using booleans to turn off formField layers**

**Key question:**
As inputs can be consumed by other components, e.g. a Select in a Data collection toolbar, should we allow or limit misconfiguration in these scenarios.

**Comment by oliverHPE** [comment]
Using

Select #4552 
Search #4551 

To determine how best to solve this.

**Comment by SeamusLeonardHPE** [comment]
Vote on input types as published SOLO or inside formField

https://www.figma.com/board/KBGMTGm9NZoacUoKM02N7J/Input---Outside-of-Formfield?node-id=0-1&t=7RU3GZSG0ca5XPFf-1
