### ISSUE TITLE
Search - Phase 1 - Discovery

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4551]

**Comment by SeamusLeonardHPE** [comment]
Discovery & build
https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=3214-28175

**Comment by SeamusLeonardHPE** [comment]
Updated link to testing

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4766-53752&t=tnGyyXYUo2Ax9CHy-4
