### ISSUE TITLE
Text Area [in FormField] - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4556]
**[Link to Figma](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4997-9367)**

**[Token Review](https://github.com/grommet/hpe-design-system/issues/4622)**
**[Figma Build Review](https://github.com/grommet/hpe-design-system/issues/4620)**
**[Code Parity Review](https://github.com/grommet/hpe-design-system/issues/4621)**

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3062-2494&t=2NvL5zJQMKMthYdM-4)
