### ISSUE TITLE
Star Rating - Tokens Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4564]
**[Link to Figma](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4758-70140)**

**Comment by julauxen** [comment]
@CillianHPE Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4758-70185&t=ctT8DfhFg6K9bNA5-1) No comments, good to close.
