### ISSUE TITLE
Thumbs Rating - Figma Build Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4566]
**[Link to Figma](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4758-70140)**

**Comment by julauxen** [comment]
@CillianHPE Review done [here. ](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4758-70181&t=ctT8DfhFg6K9bNA5-1). Only comments on props panel and layers, so once you fix it no need for a second review.
