### ISSUE TITLE
Footer - Figma Build Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4571]
Figma link for review: https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=4858-12545&t=ctT8DfhFg6K9bNA5-1

**Comment by CillianHPE** [comment]
@julauxen 

Just one comment added.

Once you implement that change you can close.

**Comment by julauxen** [comment]
thanks, fixed it! closing as done
