### ISSUE TITLE
Checkbox [in FormField] - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4581]
Link to release candidate build region

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5012-58472&t=P9ZIdBb6Hf53Whzq-4

**Comment by SeamusLeonardHPE** [comment]
Token review
[#4344](https://github.com/grommet/hpe-design-system/issues/4344)

Build review
https://github.com/grommet/hpe-design-system/issues/4597

**Comment by SeamusLeonardHPE** [comment]
[Published to v2 library](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3026-1769)
