### ISSUE TITLE
ToggleSwitch [in FormField] - Phase 2 - Build

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#4582]
Build page

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5012-161181

**Comment by SeamusLeonardHPE** [comment]
Token review
https://github.com/grommet/hpe-design-system/issues/4600

Build review

**Comment by SeamusLeonardHPE** [comment]
[Published to v2 library](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3026-1771)
