### ISSUE TITLE
Input CheckboxGroup [In FormField] - Token Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4608]
Link to test section

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5057-42750&t=NPGWU78NgJnRo7M3-4

**Comment by CillianHPE** [comment]
@SeamusLeonardHPE I left some minor comments in the **[file.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2615-37729)**

**Comment by CillianHPE** [comment]
@SeamusLeonardHPE 

Thanks this is good to close now.

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-11270&t=2NvL5zJQMKMthYdM-4)
