### ISSUE TITLE
Input radioGroup [In FormField] - Token Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4611]
Link to token test section

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5053-11315&t=Q8SypSwHFQYOzVT5-4

**Comment by CillianHPE** [comment]
@SeamusLeonardHPE 

Left some comments in the **[file.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2615-37819)**
