### ISSUE TITLE
Input radioGroup [In FormField] - Figma Build Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4612]
Link to test section

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5053-11307&t=Q8SypSwHFQYOzVT5-4

**Comment by CillianHPE** [comment]
@SeamusLeonardHPE 

Review done, good to close.

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-13162&t=2NvL5zJQMKMthYdM-4)
