### ISSUE TITLE
Input switchGroup [In FormField] - Token Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4613]
Link to section

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5057-48165&t=Q8SypSwHFQYOzVT5-4

**Comment by julauxen** [comment]
@SeamusLeonardHPE Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=5057-48165&t=AVvkCtjXXA44tSks-1)

**Comment by SeamusLeonardHPE** [comment]
[Closed and published](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-14588&t=QFASKe9igCFMtLMb-4)
