### ISSUE TITLE
Input switchGroup [In FormField] - Figma Build Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4614]
Link to test region

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5057-48153&t=Q8SypSwHFQYOzVT5-4

**Comment by julauxen** [comment]
@SeamusLeonardHPE Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=5057-48153&t=AVvkCtjXXA44tSks-1).

**Comment by SeamusLeonardHPE** [comment]
@julauxen  can you check the notes Ive added re responsive behaviour and focus -
Should be good to close out after a quick review

**Comment by julauxen** [comment]
Looks good @SeamusLeonardHPE, I am good to close!

**Comment by SeamusLeonardHPE** [comment]
[Closed and published](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-14588&t=QFASKe9igCFMtLMb-4)
