### ISSUE TITLE
Tags - Token Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4615]
Link to region

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5048-192060&t=Q8SypSwHFQYOzVT5-4

**Comment by CillianHPE** [comment]
@luketa8 

Tag review done. See comment with changes applied.

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3039-2382&t=2NvL5zJQMKMthYdM-4)
