### ISSUE TITLE
TextArea (Form Field) - Figma Build Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4620]

**Comment by luketa8** [comment]
Added [first pass review](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=4997-9367)

**Comment by CillianHPE** [comment]
@luketa8 Metadata added.

Is this ticket good to close?

**Comment by luketa8** [comment]
![Screenshot 2024-12-19 at 10 23 05 AM](https://github.com/user-attachments/assets/df5125b4-b53d-42e7-9683-739a4b6de106)
I still see detached props in [this component](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5103-25435&t=8pYc4RVG01A8dIoV-4)

**Comment by CillianHPE** [comment]
@luketa8 THanks that's now removed

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3039-91&t=2NvL5zJQMKMthYdM-4)
