### ISSUE TITLE
TextArea (Form Field) - Code Parity Review

### ISSUE THREAD

**Issue by CillianHPE** [grommet/hpe-design-system#4621]

**Comment by CillianHPE** [comment]
No need for Code Parity review as there are no additional changes from V1

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3039-91&t=2NvL5zJQMKMthYdM-4)
