### ISSUE TITLE
Card - Token Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4625]

**Comment by julauxen** [comment]
@luketa8 Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=5089-90012&t=pBOIAdMkoMn5m2gN-1)

**Comment by julauxen** [comment]
I see you fixed the things I pointed out. It's looking good, I am good to close this.

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3062-2494&t=2NvL5zJQMKMthYdM-4)
