### ISSUE TITLE
ToggleSwitch + label - Token Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4626]
Link to work area

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5139-32083&t=g093yfGdet8PIiUl-4

**Comment by CillianHPE** [comment]
@SeamusLeonardHPE 

Review done, good to close.

**Comment by SeamusLeonardHPE** [comment]
[Published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-11046&t=2NvL5zJQMKMthYdM-4)
