### ISSUE TITLE
Checkbox + label - Token Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4628]
Link to test area

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5139-32647&t=g093yfGdet8PIiUl-4

**Comment by julauxen** [comment]
@SeamusLeonardHPE Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=5139-32647&t=6TFq2vpgKdCJK4gA-1). I have one comment, but it seems to be a token mapping issue and not related tot his specific issue, so I am good to close.

**Comment by SeamusLeonardHPE** [comment]
[published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-10920&t=2NvL5zJQMKMthYdM-4)
