### ISSUE TITLE
Checkbox + label - Figma Build Review

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4629]
Link to test area

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=5139-32639&t=g093yfGdet8PIiUl-4

**Comment by julauxen** [comment]
hey @SeamusLeonardHPE Review done [here.](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=5139-32639&t=6TFq2vpgKdCJK4gA-1)
I have no comments, I am good to close this issue.

**Comment by SeamusLeonardHPE** [comment]
[published and closed](https://www.figma.com/design/HDckqS2MWhINfC8EIQPMV1/Component-Library-v2?node-id=3060-10920&t=2NvL5zJQMKMthYdM-4)
