### ISSUE TITLE
DateInput [Solo] - Figma Build Review

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4630]
Figma link: https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?m=auto&node-id=2615-38121&t=6TFq2vpgKdCJK4gA-1

**Comment by CillianHPE** [comment]
@julauxen 

Just left a few minor observations. If you decide to implement, feel free to close the ticket after.
