### ISSUE TITLE
Broken link to Figma assets

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/hpe-design-system#500]
### Is this issue related to the design system core library or design system website?

design-system-website

### Expected Behavior
The link to figma from this page should work.

https://design-system.hpe.design/design

### Actual Behavior

Get a 404.

### URL, screen shot, or CodeSandbox exhibiting the issue
![image](https://user-images.githubusercontent.com/6393696/76533062-1a955b80-643d-11ea-9025-7b9946e04266.png)

### Steps to Reproduce

Click on link.

**Comment by halocline** [comment]
Looks like viewing permissions need to be modified in the Figma file.

**Comment by karatechops** [comment]
Giving this issue a bump. I just ran into it as well.

**Comment by jcfilben** [comment]
Closing, the https://design-system.hpe.design/design page no longer exists on the design system site
