### ISSUE TITLE
RangeInput 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#519]
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [ ] Theme
- [ ] Grommet
- [ ] Code Examples
- [ ] Guidance  

**Figma File**
https://www.figma.com/file/BqCjvjc0rECQ4Ln2QhyjNi/hpe-RangeInput?node-id=0%3A1

**Comment by ericsoderberghp** [comment]
RangeInput can be difficult to put into context.
- what is the actual value selected?
- what is the range of possible values? linear? logarithmic? other? min? max?

Some guidance starters:
- when to use this vs. RadioButtonGroup, Select, or MaskedInput with fixed options showing units?

**Comment by saggiemilva** [comment]
Range Input 

The Range Input component is a slider control that provides a handle the user can move to make changes to values. 

 

Guidance 

Range Input provides a range of values along a bar that users may select. Sliders can have icons or other indicators on both ends of the bar that reflect the value range. 

Usage  

To create a predictable experience for users, adhere to the following guidelines for using RangeInput 

Use RangeInput only when approximate values are sufficient. This may include inputs such as volume or brightness. Do not use Range Input when values need to be precise. If a precise value is required, try using MaskedInput, or Select. 

Use RangeInput only when there is a wide range of values to select from. This component is not intended for value ranges of 5 or less. If this is the case, try RadioButtonGroup. 

Changes made with range input should be immediate. Updating range input values in real time provides feedback that allows users to quickly find their preference. Range Input should not be used with setting that have any minor delays or cannot provide automatic feedback. If this is the case try RadioButtonGroup or Select. 

what is the actual value selected? 

what is the range of possible values? linear? logarithmic? other? min? Max? 

Accessibility 

Using a Range input to select a specific value requires good motor skill and can propose a challenge to some users. Therefore, it is not recommended to use RangeInput for picking an exact value.  

In addition, keep in mind that as the density of values increases the harder it will be for a user to select a desired value. 

Labeling 

-Labels should be short, concise, and always visible to the user 

-For touchscreens, labels should be displayed above or beside the component to ensures the user's hand will not block the label while adjusting the slider. 

- Value labels can be placed on either end of the component if necessary. These labels can in the form of icons, numerical values, or brief text values. It is important to keep these values as short and direct as possible. Values should appear in an order that corresponds to the language the component will be shown in. 

Variants 

A RangeInput's visual state informs the user of its ability to be interacted with and my also provide necessary guidance. 

Description 

Adding a description provides the user additional information about the context or purpose of the RangeInput. 

Value Labels 

Value labels can be added outside the RangeInput component to provide further understanding for the user.  

Validation 

Used to indicate that a RangeInput does not meet the validation requirements of its bounding Form Field. 

Disabled 

Used to indicate that a RangeInput cannot be interacted with.

**Comment by saggiemilva** [comment]
Create(How): 

- First, use the Tabs Component is the outer wrapper. 
- 
- Then add Tab Components as its children. 
- 
- Providing a Title Property to a Tab will populate the text on the actual tab.  
- 
- The child elements of a Tab will form the content displayed when a Tab is active. 

Best Practices(Why): 

- Range input should be use only when approximate values are sufficient - selecting a specific value requires good motor skill and can be challenging. 
- 
- Keep in mind that as the density of values increases the harder it will be for a user to select a desired value. 
- 
- Changes made with range input should be immediate and not require updating 
- 
- It is recommended that you only use this component when the is a range of options for the user to select 

 

Conventions(Do): 

- Keep your Range Input labels short and concise.  
- 
- Add icons, numerical values, or brief text values to either side of the component when necessary 
- 
- Values labels should appear in an order that corresponds to the language the component will be shown in 

 
Usage(Don't): 


- Do not use Range Input when exact values need to be given. 

- Place labels below the Range Input 

- Pair Range Input with setting that do not change in real time
