### ISSUE TITLE
Moving Icons from site to either grommet-icons or core library.

### ISSUE THREAD

**Issue by ShimiSun** [grommet/hpe-design-system#525]
Need a discussion around the way we are consuming icons from SVG today instead of letting the grommet-icons library to leverage its logic for us.

* Why aren't the icons on grommet-icons?
* Should we at least move the icons to the core lib from the site?

The current approach is creating unneeded code complexity, and we can remove plenty of files if we can consume the icons from grommet-icons.

**Comment by taysea** [comment]
Icons in the site have been published in grommet-icons and are being imported from there. Closing this issue.
