### ISSUE TITLE
CheckBox styling with Grommet

### ISSUE THREAD

**Issue by britt6612** [grommet/hpe-design-system#544]
- background-color, selected: 'selected-background'
- use new checkmark svg

There are two issues left that need to be looked at for the checkbox theme. Currently there are some things in Grommet that we should discuss. As of now there the border takes the same color that is defined for the check mark. https://v2.grommet.io/checkbox#checkBox.color

We would not want this behavior if we want to fill the checkbox with brand color as it is checked and then have the checkmark either be white. We would also need to add in a fill color that would only be used if the checkmark is checked other wise it would stay the default of the page color depending if user is on dark/light mode.

**Comment by halocline** [comment]
Has been addressed through other theme work.
