### ISSUE TITLE
Fix test-cafe warnings

### ISSUE THREAD

**Issue by ShimiSun** [grommet/hpe-design-system#573]

**Comment by ShimiSun** [comment]
Many many warnings are coming from test-cafe during the project installation, we should use the tool without warnings 
![image](https://user-images.githubusercontent.com/6320236/77585696-86021300-6eaa-11ea-8c59-cfa0edf2f65d.png)

**Comment by ericsoderberghp** [comment]
We haven't prioritized this in too long
