### ISSUE TITLE
Create Icon Component Library

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#578]
Take the icons from sticker sheet to component library

**Figma Link**
https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/hpe-icons?node-id=261%3A0

**Comment by saggiemilva** [comment]
Figma File:
https://www.figma.com/file/G99KGffGLFKICy8xRs51lW/hpe-icons?node-id=261%3A0
