### ISSUE TITLE
Remove local icons from site and use grommet-icons stable instead

### ISSUE THREAD

**Issue by ShimiSun** [grommet/hpe-design-system#581]
Update context:
We no longer need a repo for the icons since we did an [extensive work of adding icons to grommet icons](https://github.com/grommet/grommet-icons/issues/174). 
Though, the next step for the design-system would be to clean up the icon files (svg+js) from the site repo and refer to the new icons on the grommet-icons stable instead.
This would light-up the site package.
******

Some icons we are using on the design-system-site would not be placed on Grommet-icons repo. hence we need to organize those resources on a separate repo within the monorepo.
The icons could be shared between the site and the core library.

**Comment by halocline** [comment]
👍
