### ISSUE TITLE
Exploration: Checkbox in Grommet vs Design Systen 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#653]
How can we match the below primary checkbox states. 
https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/hpe-checkbox?node-id=1315%3A0
https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/hpe-checkbox%2Ftoggle?node-id=1433%3A591

**Comment by halocline** [comment]
No longer relevant.
