### ISSUE TITLE
Avatar 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#707]
Acceptance criteria is based on alignment across the below 
- [ ] Figma 
- [ ] Theme
- [ ] Grommet
- [ ] Code Examples
- [ ] Guidance

**Comment by vavalos5** [comment]
Discussion on whether we have a hover state for Avatar are needed. IF so, how do we show hover.
Discussion on accessibility for focus state needed too.

**Comment by vavalos5** [comment]
Adding/working on some guidance text for when we're ready to publish:

### **Avatar**

An Avatar is a visual representation of a user. 

### **Usage**

All Avatars come in a default size and variant as a placeholder. 
The user may change their default placeholder to an image, image with inline text, or have only their show.

### **Accessibility**

Always use alt-text when using an Avatar, except when showing and Avatar with inline text as the screen reader will read the name twice.

### **Variants**

**Default Avatar**

**Initials Avatar**

**Image Avatar**

 **Image with Inline Text Avatar**

**Comment by vavalos5** [comment]
### **Avatar**
An Avatar is a visual representation of a user.

**Create(How):**

- 
- 
- 
- 

**Best Practices(Why):**

- All Avatars come in a default size and variant as a placeholder
- The user may change their default placeholder to an image, image with inline text, or have only their show

**Conventions(Do):**

- Have a focal point on your Avatar
- Only use alt-text on: default avatar, initials avatar and image avatar.

**Usage(Don't):**

- Do not use alt-text when pairing an image with inline text
