### ISSUE TITLE
Menu with focus+hover has a bad background color

### ISSUE THREAD

**Issue by ecircenis** [grommet/hpe-design-system#761]
### Is this issue related to the design system core library or design system website?

design-system-core

### Expected Behavior

When I click on a menu, the menu should not change from having a white background to having a black background.

### Actual Behavior

Here are some images showing what happens:

Normal menu: 
![image](https://user-images.githubusercontent.com/17883783/81423838-3e5de080-9112-11ea-8893-25932b9c103f.png)
Hovered menu: 
![image](https://user-images.githubusercontent.com/17883783/81423941-62212680-9112-11ea-8b89-c07cb3c20631.png)
Open menu: 
![image](https://user-images.githubusercontent.com/17883783/81423984-72d19c80-9112-11ea-8778-cf9197118718.png)
Open menu with hover (!!!): 
![image](https://user-images.githubusercontent.com/17883783/81424019-83821280-9112-11ea-8c92-bf5e030abd36.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

Using grommet designer and this theme:
https://grommet.github.io/grommet-theme-hpe/grommet-theme-hpe-next.min.js
Chrome browser on windows 10

**Comment by MikeWalrath** [comment]
Linked to #734

**Comment by taysea** [comment]
Closing, this has been fixed.
