### ISSUE TITLE
Hover indicator for a plain button on a dark background washes out the button

### ISSUE THREAD

**Issue by ecircenis** [grommet/hpe-design-system#764]
### Is this issue related to the design system core library or design system website?

design-system-core

### Expected Behavior

Expect subtle hover effect

### Actual Behavior

Not hovered:
![image](https://user-images.githubusercontent.com/17883783/81435527-47a47880-9125-11ea-806b-b88ee88db7be.png)

Hovered:
![image](https://user-images.githubusercontent.com/17883783/81435570-58ed8500-9125-11ea-9535-886db303165b.png)

### Your Environment

Using grommet designer
Theme: 
https://grommet.github.io/grommet-theme-hpe/grommet-theme-hpe-next.min.js
Chrome
Windows 10

**Comment by ecircenis** [comment]
Also, text no longer shows up for buttons on a dark background:

Not hovered:
![image](https://user-images.githubusercontent.com/17883783/81436173-445dbc80-9126-11ea-9baf-1ae75d95dfaa.png)

Hovered:
![image](https://user-images.githubusercontent.com/17883783/81436199-4c1d6100-9126-11ea-8b9a-21e9968e6b8b.png)

**Comment by ShimiSun** [comment]
I think this one was fixed with https://github.com/grommet/grommet/pull/4062

**Comment by taysea** [comment]
Closed by https://github.com/grommet/grommet/pull/4062
