### ISSUE TITLE
Text color on select / dark mode incorrect color

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#770]
### Is this issue related to the design system core library or design system website?
Design System Website

### Expected Behavior
Text color should be white and once a value has been selected, the text should go from regular to medium.

### Actual Behavior
Right now the text color is black and when a value is selected, it doesn't change from regular to medium.

### URL, screen shot, or CodeSandbox exhibiting the issue
<img width="335" alt="Screen Shot 2020-05-12 at 10 42 00 AM" src="https://user-images.githubusercontent.com/62117454/81727351-af1c3a00-943d-11ea-8875-f7b7848c6010.png">

**Comment by taysea** [comment]
Closing, this has been fixed.
