### ISSUE TITLE
Selected value on Select doesn't wrap around entire area

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#771]
### Is this issue related to the design system core library or design system website?

Design System Website

### Expected Behavior

Selected value should have the green box wrapping around the entire area from the left to the right.

### Actual Behavior

Right now it has and extra 12px padding on left and right and extra 6px padding on top and bottom. 

### URL, screen shot, or CodeSandbox exhibiting the issue

<img width="318" alt="Screen Shot 2020-05-12 at 10 42 10 AM" src="https://user-images.githubusercontent.com/62117454/81727659-2f429f80-943e-11ea-9602-9ddf6ec7e51c.png">

**Comment by taysea** [comment]
Closing as this has been resolved.
