### ISSUE TITLE
horizontal RadioButtonGroup affinity is broken

### ISSUE THREAD

**Issue by ecircenis** [grommet/hpe-design-system#772]
### Is this issue related to the design system core library or design system website?

design-system-core

### Expected Behavior

My expectation is that, regardless of gap, the affinity between a radio button and its label is good.

### Actual Behavior

![image](https://user-images.githubusercontent.com/17883783/81740549-5effa080-945a-11ea-856f-d6493dd103aa.png)
As you can see, for gaps up to and including medium, there is no affinity between the button and its label.  And, for larger gaps, the visualization is simply too wide to be generally useful.  All gaps should result in usable radio button groups.

### Your Environment

Using grommet designer
Theme: https://grommet.github.io/grommet-theme-hpe/grommet-theme-hpe-next.min.js
Windows 10
Chrome

**Comment by MikeWalrath** [comment]
Related to #518

**Comment by ecircenis** [comment]
https://designer.grommet.io/?id=RadioButtonGroup-issue-edgar-circenis-hpe-com

**Comment by taysea** [comment]
<img width="658" alt="Screen Shot 2024-05-31 at 10 12 30 AM" src="https://github.com/grommet/hpe-design-system/assets/12522275/1823c3cd-398e-4b6e-99b2-5d171fa0fd5f">

Closing, affinity has been tightened.
