### ISSUE TITLE
Refresh Navigation Examples

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#779]
Phase 1 work completed in https://github.com/hpe-design/design-system/pull/769:
- [x] Navigation Page
- [x] Hub and Spoke Page
  - [x] Hub and Spoke as Cards
- [x] Persistent Navigation Page
  - [x] Header
  - [x] Minimal Sidebar

Remaining examples to fill in:
- [ ] Hub and Spoke as List
- [ ] Extended Sidebar
- [ ] Persistent + Hub & Spoke (a.k.a. cocktail)
- [ ] Nav vs. Tabs
- [ ] Global Header

**Comment by ericsoderberghp** [comment]
Tied to https://github.com/grommet/hpe-design-system/issues/1564 exploration

**Comment by vavalos5** [comment]
@ericsoderberghp do we want to continue refreshing Navigation examples>

**Comment by ericsoderberghp** [comment]
I'd be fine with linking this to the Navigation Audit ticket and then closing this, allowing our swarm on Navigation to refresh the set of next steps.

**Comment by vavalos5** [comment]
Closing since we've already commenced auditing and covered by other action items within the big ticket item
