### ISSUE TITLE
Main variations

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#798]
Outline variations of Main content:

- Cards
- List
- Table
- Document
- 2 column

I'm not sure if this needs anything in Figma. If it does, glad to have it.
For the design system site, I'm thinking this is the Main component and is mostly a place that references how Main is used, where it fits in the Layouts and what are some common things it contains. For what it contains, I was thinking it would reference the Cards, List, and Table templates, not just the components. See #799, #800, and #801.

**Comment by saggiemilva** [comment]
@ericsoderberghp Can you give some context to what you mean by document layout?

**Comment by ericsoderberghp** [comment]
> @ericsoderberghp Can you give some context to what you mean by document layout?

I'd say the design system site has a document layout. Headings, Paragraphs, Images, etc.
