### ISSUE TITLE
Some cards don't have an image

### ISSUE THREAD

**Issue by cherih** [grommet/hpe-design-system#813]
As I was browsing around the DS website using Chrome on my PC, I noticed this issue. 

Specific cards that don't have images:
-  Foundation
   - Accessibility
- Components
   - Main
- Templates
   - Hub and Spoke Navigation
   - Navigation
   - Persistent Navigation
   - Page Layouts
- Extend
   - Designer Guidance
   - Developer Guidance
   - React Router

**Comment by halocline** [comment]
Addressed.
