### ISSUE TITLE
publish design system consumer screenshots

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#820]
Reach out to design system consumers to build a catalog of screenshots of existing screens. Make this open so consumers can give feedback on which screens we should use over time. This catalog can then be used for our template explorations to see how we are covering aspects. One key will not be to able to render the screen precisely but to handle the spirit of what can be done.

### Deliverables
- [ ] screenshots loosely organized and published to a URL that can be seen by anyone on the team
- [ ] ability for anyone on the team to add or update them

Expected to take < 1 day

**Comment by L0ZZI** [comment]
Link to a collection of prototypes:
https://hpe.slack.com/files/TH0KDGMRB/F014RMQBZ0D?origin_team=TH0KDGMRB
