### ISSUE TITLE
Data Visualization initial exploration 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#846]
Initial exploration to break down how we want to approach the topic.

This is a big topic. The idea here is to start wide, looking at a variety of aspects, and getting an initial lay of the land. This should help us as we dig deeper into things to help us determine how to divide the problem space up.
Time bounding to a single sprint.

### Deliverables

- publish initial research, when and why are data visualizations helpful, what problems are they solving, etc.
- come up with a rough taxonomy for types of visualizations. For example: big number, meter, sparkline, chart, map, diagram, ...
- create new items in the backlog to delve further into a single type at a time

### Subsequently

Here's an idea for where to go afterwards for each type of visualization, we would likely break it up into:

- **phase 1** user scenarios with a some detail, a simple base design, break up into multiple aspects, accessibility, related templates and components, deliverables: publish research and designs in Figma, GitHub issues for phase 3
- **phase 2** design details for the various aspects broken out in phase 1, initial design site implementation of simple base, start any grommet work
- **phase 3** design site implementation of design details, any grommet work

Other aspects to consider:

- how to differentiate data aspects, colors, thickness, style, opacity, symbols
- interaction with the visualization, drilling in, navigating

**Comment by MikeWalrath** [comment]
Mike to follow up with the below to gather requirements. 

Mead, Sherry
Lives in San Fran, CA
Email address
sherry.mead@hpe.com

**Comment by MikeWalrath** [comment]
Article for reference https://medium.com/carbondesign/color-palettes-and-accessibility-features-for-data-visualization-7869f4874fca

**Comment by taysea** [comment]
Closing in favor of future issues
