### ISSUE TITLE
Asynchronous Notifications Templates 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#847]
## GreenLake notification examples
https://hpe.sharepoint.com/:w:/t/hpe-design/EWBWpLxIyCFLhRefZSflkUwBqIPDwaTDF1pk5R82A0TU9w?e=cDH0K1
https://designer.grommet.io/index?id=Persistent-errors-edgar-circenis-hpe-com
https://designer.grommet.io/?id=Notification-Manager-edgar-circenis-hpe-com
https://www.figma.com/file/tpNTgU0w7V5XptWG1JoVK2/CaaS-Notification-Exploration-and-Design?node-id=125%3A2778
https://www.figma.com/file/tpNTgU0w7V5XptWG1JoVK2/CaaS-Notification-Exploration-and-Design?node-id=0%3A1

**Comment by ericsoderberghp** [comment]
Nimble folks are also wanting this as part of their Task Manager and Bulk Actions topic.

**Comment by gregfuruiye** [comment]
Figma File reviewing Use Cases and Research
https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=0%3A1

**Comment by gregfuruiye** [comment]
I've pulled all the resources and research into this Figma File:
https://www.figma.com/file/FGvOd2htjrChVVS2oz73ds/HPE-Notifications?node-id=0%3A1

Notifications is a huge subject. The exploration was more of a landscape view. Next steps:

synthesize the data collection
provide recommendations
generate patterns/behaviors/templates

**Comment by gregfuruiye** [comment]
A set of additional issues have been generated to follow up on this exploration:

#1168 #1169 #1172 #1173
