### ISSUE TITLE
Wizard Guide/Support Template 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#849]
Here is the Figma File for current work:
[https://www.figma.com/file/GEhgYzx3b8MejBjg9gAxyA/Wizarding?node-id=0%3A1](https://www.figma.com/file/GEhgYzx3b8MejBjg9gAxyA/Wizarding?node-id=0%3A1)

Lauren's Design for reference. She's working in the context of Consumption Analytics:
[https://www.figma.com/file/2Hy1q0vY7IhHa9lfHFr1Y7/US11666-Add-Data-Source-UX-AWS?node-id=68%3A0](https://www.figma.com/file/2Hy1q0vY7IhHa9lfHFr1Y7/US11666-Add-Data-Source-UX-AWS?node-id=68%3A0)

**Comment by halocline** [comment]
Completed
