### ISSUE TITLE
Create larger circle icon to be used as the checked state of RadioButton

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#851]
RadioButton designs call for the checked radiobutton circle to have a diameter of 16px which is larger than the default circle of 12px.

[Figma](https://www.figma.com/file/aZyY606ENQedz4FXugdzgS/HPE-Radio-Button-Group-Component?node-id=77%3A323)

- [x] Where should this icon live? May be a bit specific to live amongst grommet-icons. Is this part of the work @saggiemilva has done for icons?
- [x] Needs to be reference-able/importable by hpe theme
  - Theme to reference similar to:
```
icons: {
  circle: () => (
    <Blank color="selected-background">
      <circle cx="12" cy="12" r="8" />
    </Blank>
  ),
}
```

**Comment by ericsoderberghp** [comment]
Can we add a grommet issue for this? I think we should enhance RadioButton.js to pull the size of the circle from the theme via something like `radioButton.check.size`.
