### ISSUE TITLE
[Performance Dev] Layout component re-renders on each page load

### ISSUE THREAD

**Issue by ShimiSun** [grommet/hpe-design-system#852]
### Is this issue related to the design system core library or design system website?
design system core library

### Expected Behavior
Currently, each time the user routes to a new page the Layout component rerenders although there is no need to render the AppHeader or other generic elements that are part of the Layout component.
Here is a blog that might help and improve the performance https://adamwathan.me/2019/10/17/persistent-layout-patterns-in-nextjs/

### Actual Behavior
All page rerenders.

### URL, screen shot, or CodeSandbox exhibiting the issue
each file on the pages directory calls Layout.

### Your Environment
latest

- Design System version: beta
- Grommet version: n/a
- Browser Name and version: all
- Operating System and version (desktop or mobile): all

**Comment by taysea** [comment]
Good catch. We do have a custom _app.js file existing already, so it seems like we could do some work to lift the Layout component up to this file.

**Comment by ericsoderberghp** [comment]
We haven't prioritized this for too long
