### ISSUE TITLE
Rename the "Extend" nav button

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#860]
Looking to bring clarity to the "Extend" nav item. Suggestions welcome!!!!

### Deliverables
- [ ] hold a review meeting with the team to review the current cards
- [ ] create new issues as needed based on feedback

estimated to take < 1 day

**Comment by halocline** [comment]
I am wondering if the "Extend" label is okay as is, and the update should be related to updating the accompanying description? Currently the site reads "Why does HPE have a design system? All the aesthetics, best practices, and information about the platform and how to wield it."

![Screen Shot 2020-06-08 at 2 30 02 PM](https://user-images.githubusercontent.com/1756948/84077538-baa74600-a994-11ea-89ac-db4a7ec1a222.png)

What if it were rephrased to be something along the lines of "Extend the HPE Design System with this collection of recommended resources, plug-ins, tutorials, and more."?

**Comment by taysea** [comment]
Agreed with the above, but to throw out a suggestion for a rename, maybe "Tools" and a description along similar lines of what matt suggested above?

If that were the case, I feel like "Design Guidance" and "Developer Guidance" should be moved to "Foundation" so that the focus of this section is truly external/global tools.

**Comment by MikeWalrath** [comment]
@ericsoderberghp do you have a preference here? I think the copy needs to be cleaned up regardless. The goal would be to add clarity to what the user can expect when they click on the nav item. I was leaning toward "Resources" however Ill defer to the team here and we might just need a decision that we can test at during the next usability test.

**Comment by ericsoderberghp** [comment]
Agreed on changing the copy to be more descriptive of the content. My concern with "Resources" is that the whole site is resources. That feels too vague. I'm more inclined towards "Guides", which aligns with "Developer Guidance", and having each page be perhaps a mini tutorial or how-to.

**Comment by taysea** [comment]
Will the content of the pages for "Grommet Designer" and "HPE Audience" etc. be guides as well? I like that name if so. I wasn't sure if those cards would just be an introduction to what they are or something more.

**Comment by ericsoderberghp** [comment]
I can see "Grommet Designer" being a How-To guide. I'm not sure what "HPE Audience" is meant to include.

**Comment by taysea** [comment]
Gotcha. It would be good to take a pass as a team or small group at the cards currently under "Extend" and have a sense of what kind of content we think would go under each to help decide if "Guides" is an accurate category for all of them, and if not where else in the site they might be housed.

**Comment by ericsoderberghp** [comment]
We haven't prioritized this for too long
