### ISSUE TITLE
Create Figma Component Use Video

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#890]
Follows the intro video: 
https://d3hq6blov2iije.cloudfront.net/media/design/DS+Figma+Intro.mp4

A 2-3 minute video about using components from the libraries.

- Accessing and viewing quick review
- Updating
- Drag and drop
- Instances (including button group, checkbox group, radio button group)
- States (note error message on field validation requires adjusting the frame for auto layout in Form to occur correctly)
- Overrides
- Breaking instances

### Deliverables
- [ ] a video published somewhere that it can be shared for internal review with the team
- [ ] either solicit feedback over slack or hold a watch party to gather feedback
- [ ] create a fresh backlog item to respond to any feedback received

expected to take < 1 day

**Comment by ericsoderberghp** [comment]
Now that we have the new Figma onboarding guide, don't think we need this.
