### ISSUE TITLE
RadioButtonGroup - keyboard focus behavior (e.g. arrowing through options changes selection, but focus is inconsistent)

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#899]
Related: https://github.com/hpe-design/design-system/issues/518#issuecomment-639097244 & https://github.com/hpe-design/design-system/issues/898 & https://github.com/hpe-design/design-system/issues/656

When changing selected values within a RadioButtonGroup, contained in a FormField, the FormField content box receives and loses focus treatment each time the selected option changes.

**Video Demo**
![Screen-Recording-2020-06-16-at-10 56 49-AM](https://user-images.githubusercontent.com/1756948/84804700-66b5e600-afc0-11ea-9050-6dc331e6f07a.gif)

Current design calls for the FormField content box to receive focus treatment, however it would be good to clarify whether focus should be transferred to each input option like: https://www.w3.org/WAI/tutorials/forms/grouping/#radio-buttons

Right now, the behavior has a mixture of sometimes having two elements with focus and a single element at other times.

**Comment by ericsoderberghp** [comment]
Is there more to this than waiting for some grommet enhancements to theme support and documentation? The title of the issue has "research" in it. Can you clarify the description of this issue more?

**Comment by halocline** [comment]
> Is there more to this than waiting for some grommet enhancements to theme support and documentation? The title of the issue has "research" in it. Can you clarify the description of this issue more?

I have added additional detail to the description above.

I think the "research" part is two fold:
1. Get to consistent behavior by making a decision as to what the focus treatment behavior should be:
  a. Follow rule that only one element should have focus at any given time?
  b. Okay with bounding box and RadioButton input having focus treatments at same time?
1. Resolve the inconsistency in Grommet. It would seem that there is some sort of interplay in behaviors between RadioButton/RadioButtonGroup and FormField, but I haven't looked into where that interplay is occurring and why it results in inconsistent focus treatment.

**Comment by ShimiSun** [comment]
The recommended focus behavior for RadioButtonGroup in a nutshell:
1. https://webaim.org/techniques/forms/controls#radiobutton
2. https://www.w3.org/WAI/tutorials/forms/grouping/#radio-buttons

Seems like the outer border focus is not needed, and it's using up/down keyboard navigation to move between the radio-button elements in a cyclic loop.
If we decide to keep the FomField outer border focus, it should be removed once the internal RadioButton element has the focus, so it won't be confusing which element has the focus (one at a time).
