### ISSUE TITLE
Aligning/Defining the definition of Main

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#911]
### Is this issue related to the design system core library or design system website?
Design system, design system website + Grommet

Right now, in Grommet, we're describing "main" as the area where content goes: https://v2.grommet.io/main

But in Design system Figma file, we're showing "main" to be the overall browser size. 
https://www.figma.com/file/gz8B7G0jAD9B8DsLEAROT6/HPE-Main-Component?node-id=0%3A1

Would a designers and devs misinterpret what main means? Let's discuss so we can make sure we're aligning the vocabulary correctly so there's no confusion between designers + devs.

**Comment by taysea** [comment]
Closing, will not be including "Main" as a Figma component.
