### ISSUE TITLE
Fill in Developer Getting Started Introduction Content

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#916]
Related: https://github.com/hpe-design/design-system/issues/900

[Content Outline for Discussion/Reaction/Prioritization](https://docs.google.com/document/d/1XNOoNX9CIG10Ei-MBOFw1qTfoGgQeZI5eaat38L6Trg/edit?usp=sharing)

**Comment by ericsoderberghp** [comment]
We haven't prioritized this for too long
