### ISSUE TITLE
Forms -> open in docs -> storybook bad examples

### ISSUE THREAD

**Issue by ecircenis** [grommet/hpe-design-system#929]
If I go to the design system forms page there is a link to "open in docs".  The resulting doc includes a storybook link that has form examples that do not match the DS styling at all.

In general, the DS (and DS docs) should not point to storyook because storybook does not use the HPE theme.  Please check for other instances of storybook links.

**Comment by ericsoderberghp** [comment]
One proposal, enhance grommet storybook to take a URL search property that sets the theme to use.

**Comment by ericsoderberghp** [comment]
We are planning a refactor of the grommet documentation, including better storybook integration. We should address this as part of that work.

**Comment by ericsoderberghp** [comment]
At some point, many months ago, these links were changed to use the hpe theme.
