### ISSUE TITLE
Evaluate color contrast between weak, extra weak and disabled 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#933]

**Comment by ShimiSun** [comment]
Currently, we still  have multiple "background contrast" warnings coming from https://design-system.hpe.design/foundation/color#background-colors

14 warning from axe:
![image](https://user-images.githubusercontent.com/6320236/104512054-db7aee00-55aa-11eb-88bd-926ce64285ce.png)

10 warnings from lighthouse:
![image](https://user-images.githubusercontent.com/6320236/104512139-f9e0e980-55aa-11eb-8618-bd39f1601af3.png)

**Comment by ericsoderberghp** [comment]
Superceded by #2230
