### ISSUE TITLE
Address Color Style Naming in Figma

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#935]
### Is this issue related to the design system core library or design system website?
Core Library

### Expected Behavior
Ease of use of color styles

### Actual Behavior
Color styles in Figma can be confusing to use because of current naming conventions in Figma

### URL, screen shot, or CodeSandbox exhibiting the issue
You can view Raja's screen shot in slack:
https://hpe.slack.com/files/UJH8BN9BP/F015X94G61K/image.png

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by MikeWalrath** [comment]
Related to #932

**Comment by taysea** [comment]
@SeamusLeonardHPE -- Can you review this and see if it's still an issue?
