### ISSUE TITLE
Create first pass at Sidebar component on design system website

### ISSUE THREAD

**Issue by cherih** [grommet/hpe-design-system#947]
The new Page Layout template is built using Sidebar, Header, Main and Footer components. Each of these components is documented on the DS website, except for Sidebar.

- Add Sidebar component card to the Components -> Layouts section of the website
- Add Sidebar component page with initial content

Vicky mentioned to me that she is working on some Figma designs for Sidebar already - not sure where they are located.

**Comment by taysea** [comment]
Closing, we are not supporting this pattern at the moment.
