### ISSUE TITLE
Create first pass at fleshing out Global Sidebar component on design system website

### ISSUE THREAD

**Issue by cherih** [grommet/hpe-design-system#948]
The Navigation and Page Layout templates pages include references to the Global Sidebar. When you navigate to the Global Sidebar page from these areas, the "under construction" page is displayed.

- Flesh out Global Sidebar component page with initial real content
- Per Eric, the current Global Sidebar home in the Navigation template is good.

Don't know if there are  Figma designs for Global Sidebar yet.

**Comment by halocline** [comment]
Closing, no longer relevant.
