### ISSUE TITLE
Color page to MDX

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#954]
On an initial pass at converting Color page to MDX, there was an issue compiling certain variables that build the color rows. I believe this is because of the structure MDX requires for creating and using variables in .mdx files but that it is pulling in variables from an external file as well. 

I did not want to let the rest of the MDX PR be hung up on a single page, but this page should be converted to MDX as well.

**Comment by ericsoderberghp** [comment]
We haven't prioritized this for too long
