### ISSUE TITLE
Add Simple data styles

### ISSUE THREAD

**Issue by bowdeng** [grommet/hpe-design-system#960]
On some occasions the monospaced font HPE Simple is a better fit for rendering meters and labels. To this end, once available as part of a theme, some controls should have the option to leverage monospaced fonts such as simple. The easiest implementation would be to provide a monospace={true} boolean property to those controls that would benefit.

Initially this could be
- Anchor
- Text
- Button
- TextInput
- TextArea
- Meter
- Distribution
- Diagram
- DataTable (per column?)
- DataChart
- Clock
- Chart

### Is this issue related to the design system core library or design system website?

design-system-core

### Expected Behavior

When the property monospace={true} is supplied, the style should use the monospaced (simple) font to render labels, annotations or simply the text.

### Actual Behavior

There is currently no option to switch to a monospaced font without creating new CSS and using ClassName references.

### URL, screen shot, or CodeSandbox exhibiting the issue

Not applicable.

### Steps to Reproduce

1. Render any component with the standard style.
2. Stare in awe and minor disappointment at the non-monospaced type.
3. Create a new stylesheet whilst contemplating the better life.

### Your Environment

- Design System version: June 2020
- Grommet version: 2.14.0
- Browser Name and version: All
- Operating System and version (desktop or mobile): All

**Comment by taysea** [comment]
Closing, will be handled by https://github.com/grommet/hpe-design-system/issues/959
