### ISSUE TITLE
Update Figma Designs for initial pass of Lists template

### ISSUE THREAD

**Issue by cherih** [grommet/hpe-design-system#974]
See #941 - Create first pass at Lists template. This has a link to the initial Figma designs that Maggie did for this.

Taylor is working on PR #956 - First pass at Lists page. The Preview for this page, includes the examples we're working with.

Cheri is working on #964 - Add List Guidance, using an initial pass done by Maggie.

**Comment by halocline** [comment]
Superseded by https://github.com/grommet/hpe-design-system/issues/2922
