### ISSUE TITLE
Handling delayed content, placeholders, transistions

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#975]
Examples and guidance for:

- initial app/page/screen loading content
- delayed content arrival for things like List, Table, details, etc. What we show while we're waiting for the content to arrive from the server.

**Comment by MikeWalrath** [comment]
Closing as the above is reflected in the Loading Behavior work. https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Loading-Indicator-Component?node-id=1%3A17
