### ISSUE TITLE
Checkbox file needs cleaning

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#976]
### Is this issue related to the design system core library or design system website?

Figma File: https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/HPE-Checkbox-Component?node-id=1744%3A1

### Expected Behavior

There should only be one published state for each instance. Right now there is more than one published state for each instance.

### URL, screen shot, or CodeSandbox exhibiting the issue
<img width="237" alt="Screen Shot 2020-07-13 at 3 54 49 PM" src="https://user-images.githubusercontent.com/62117454/87361505-3743bc00-c521-11ea-8f18-9510d7b1e8c8.png">

**Comment by halocline** [comment]
Confirm whether or not this issue is still relevant or may be closed.

**Comment by taysea** [comment]
@SeamusLeonardHPE -- can you see if this can be closed?

**Comment by SeamusLeonardHPE** [comment]
Thanks @taysea 

Closed, old checkbox file deprecated and replace in [central library](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=2940-62424)
