### ISSUE TITLE
Checkbox padding not aligned with Figma file

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#977]
### Is this issue related to the design system core library or design system website?
Design System Website

### Expected Behavior
https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/HPE-Checkbox-Component?node-id=1744%3A1

The box around the checkbox and the text is 50px in height but should be 36px. Just looks like it has 4 extra pixels of padding on top and bottom.
### URL, screen shot, or CodeSandbox exhibiting the issue

<img width="451" alt="screen_shot_2020-07-14_at_9 39 02_am" src="https://user-images.githubusercontent.com/62117454/87461029-a4f3f480-c5c2-11ea-857a-4601866987e6.png">

**Comment by halocline** [comment]
No longer relevant
