### ISSUE TITLE
Guidelines for the combination Global and App Header 

### ISSUE THREAD

**Issue by ShimiSun** [grommet/hpe-design-system#990]
### Is this issue related to the design system core library or design system website?
design-system website should elaborate with code/design example on the combination of App Header with Global Header.
The feedback we got from the Superdome-Flex team, is that they have used the guidelines on the Header page for App Header https://design-system.hpe.design/components/header#app-header, but it is still not clear what would be the right choices of one Header vs the other, for example, which colors should be used for each Header, what is the right spacing, and the insights on the which type of content would go to which Header.

### Steps to Reproduce

1.  Go https://design-system.hpe.design/components/header#app-header
2. See there are no code or design examples. 

### Your Environment

- Design System version: N/A
- Grommet version: N/A
- Browser Name and version: N/A
- Operating System and version (desktop or mobile): N/A

**Comment by taysea** [comment]
Closing, guidace has been added: https://design-system.hpe.design/components/header?q=header#global-header
